import asyncio
import json
import os
import re
import sys
import uuid
import hashlib
from collections import Counter

from dotenv import load_dotenv
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
load_dotenv()

BACKEND_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_DIR = os.path.join(BACKEND_DIR, "data")
OUT = os.path.join(DATA_DIR, "interview_question_bank_v2_generated.jsonl")

ROLE = "DevOps / Cloud Engineer"
LEAK = re.compile(r"(generate a question|generate \d+ questions|return only json|phase 4c gap plan|"
                  r"generation batch|candidate generation|system instructions|do not proceed|"
                  r"awaiting authorization|minimum target|generation pipeline|"
                  r"batch \d+ generation|expected answer|strong indicator|weak indicator|as an ai|"
                  r"here is the question|\bprompt text\b)", re.I)

Q = [
    # Group 10: Platform Engineering
    ("B61_10_1", "concept", "medium", "concept", ["Platform Engineering"], "What is a 'Golden Path' in Internal Developer Platforms (IDP) and why is it superior to mandatory gating?", "Mandatory gating forces developers to submit Jira tickets for security and operations to manually approve every infrastructure change, destroying velocity. A 'Golden Path' is a pre-approved, fully automated, self-service template (e.g., a Backstage software template that scaffolds a Spring Boot repo, an EKS Helm chart, and a GitHub Actions pipeline). It is heavily paved and secure by default. Developers are allowed to deviate from the Golden Path, but if they do, they lose the automated platform support and must manage the infrastructure entirely themselves. It incentivizes compliance through extreme convenience rather than bureaucratic blocking.", ["A pre-configured, highly automated, secure-by-default infrastructure/code template", "Provides immediate self-service delivery without manual IT/Security approval gates", "Incentivizes adoption through ease-of-use rather than rigid enforcement"], ["A golden path is when you upgrade to the premium tier of AWS"]),
    ("B61_10_2", "diagnose", "hard", "debugging", ["Platform Engineering"], "Your platform team provides a self-service Terraform module for deploying S3 buckets. Dozens of development teams use it. A security audit reveals that 5 of the buckets are completely public. You check the central module, and it strictly blocks public access. How did the developers bypass the module's security, and how do you enforce it globally?", "The developers likely used 'ClickOps' (the AWS Console) to manually alter the bucket policies after the Terraform module deployed them, or they wrote their own raw Terraform resources bypassing the module entirely. A Terraform module is only a deployment mechanism; it provides zero runtime enforcement. To fix this, you must implement 'Preventative Controls' at the cloud perimeter using AWS Service Control Policies (SCPs). An SCP applied at the AWS Organization level that denies `s3:PutBucketPublicAccessBlock` will mathematically prevent any developer, even those with local Admin access, from making a bucket public, completely overriding both manual clicks and raw Terraform.", ["Terraform modules do not prevent manual post-deployment mutations (Drift/ClickOps)", "Developers bypassed the module via the AWS console or wrote raw Terraform resources", "Fix by enforcing strict cloud-native perimeters like AWS Service Control Policies (SCPs) to mathematically deny public access globally"], ["The Terraform module had a virus"]),
    ("B61_10_3", "implement", "medium", "implement", ["Platform Engineering"], "How do you implement 'Ephemeral Environments' (Preview Environments) in Kubernetes for every single GitHub Pull Request?", "When a developer opens a PR, a GitHub Action triggers. It builds a unique Docker image tagged with the Git SHA. It then dynamically generates a new, isolated Kubernetes Namespace (e.g., `pr-1234`). It deploys the application and a dedicated database into that namespace. Finally, it uses an Ingress controller or ExternalDNS to dynamically create a URL (e.g., `pr-1234.dev.company.com`) and posts the URL back to the GitHub PR comment thread. When the PR is merged or closed, a webhook triggers a teardown script that instantly deletes the `pr-1234` namespace, destroying the ephemeral infrastructure to save costs.", ["Dynamically provision a unique Kubernetes Namespace for each Pull Request", "Deploy the container (tagged with Git SHA) and route traffic via a dynamically generated Ingress URL", "Automatically tear down the entire Namespace via a webhook when the PR is closed to save costs"], ["You buy a new physical server for every pull request"]),
    ("B61_10_4", "tradeoff", "hard", "tradeoff", ["Platform Engineering"], "What is the architectural tradeoff of using `vcluster` (Virtual Kubernetes Clusters) versus native Kubernetes Namespaces for multi-tenant developer isolation?", "Namespaces provide basic logical isolation, but they share the exact same underlying Kubernetes API server and Custom Resource Definitions (CRDs). If Team A needs an older version of the Prometheus Operator CRD, and Team B needs a newer version, Namespaces cannot isolate CRDs, forcing a cluster-wide conflict. `vcluster` spins up a completely separate, lightweight API server and etcd inside a standard pod. Team A gets their own virtual cluster where they can create custom CRDs and have full ClusterAdmin rights without affecting Team B or the host cluster. The tradeoff is the compute overhead of running multiple API servers and extreme debugging complexity if network routing fails between the virtual and physical layers.", ["Namespaces share the physical API server and CRDs, preventing deep isolation (CRD conflicts)", "vCluster runs a dedicated API server inside a pod, allowing full ClusterAdmin rights and isolated CRDs per tenant", "Tradeoff: vCluster introduces severe operational complexity, nested networking headaches, and compute overhead"], ["vcluster means the cluster is virtual reality"]),
    ("B61_10_5", "scenario", "medium", "scenario", ["Platform Engineering"], "Your platform team manages a central Jenkins server used by 50 development teams. A developer writes a malicious `Jenkinsfile` that executes `cat /var/jenkins_home/secrets` and exfiltrates the AWS credentials of another team. How do you architect the CI/CD platform to prevent this cross-tenant credential theft?", "A monolithic Jenkins server runs all jobs on shared worker nodes using shared IAM credentials, making it a massive security vulnerability for multi-tenant environments. You must re-architect to a decentralized, Ephemeral CI/CD execution model (like GitHub Actions runners on EKS, or Tekton). When Team A triggers a build, the platform provisions a single-use, ephemeral Pod specifically for Team A. This Pod is strictly bound to Team A's AWS IAM Role (via Workload Identity/IRSA). When the build finishes, the Pod is completely destroyed. Team A physically cannot access Team B's secrets because they share zero persistent state or IAM context.", ["Monolithic CI/CD servers share execution environments and secrets, allowing massive lateral movement", "Architect Ephemeral Runners (single-use Pods) for every pipeline execution", "Bind specific, isolated IAM Roles (Workload Identity) dynamically to the ephemeral runner, destroying it immediately after"], ["You ask the developer to please not hack the server"]),
    ("B61_10_6", "explain", "medium", "explain", ["Platform Engineering"], "Explain the difference between 'Infrastructure as Code' (Terraform) and 'Control Planes as Code' (Crossplane).", "Terraform is a CLI tool. You run `terraform apply`, it makes API calls to AWS, and then it shuts down. If someone manually deletes an EC2 instance 5 minutes later, Terraform does absolutely nothing until a human runs `terraform apply` again. Crossplane installs directly into your Kubernetes cluster as a continuous Control Plane. You declare an `AWS RDS Database` as a native Kubernetes YAML object. Crossplane continuously watches it. If a developer manually deletes the RDS database in AWS, the Crossplane controller detects the drift in milliseconds and instantly recreates it automatically to match the declared YAML state. It turns your infrastructure into a continuous reconciliation loop.", ["Terraform is a discrete CLI execution tool; it only checks state when explicitly run by a human or CI pipeline", "Crossplane runs continuously inside Kubernetes as a Control Plane", "Crossplane actively reconciles drift in milliseconds automatically without human intervention"], ["Crossplane is an airplane that flies across the internet"]),
    ("B61_10_7", "concept", "easy", "concept", ["Platform Engineering"], "What is the purpose of a Developer Portal like Spotify's Backstage?", "As a company scales to hundreds of microservices, developers lose track of who owns what, where the API documentation is, and how to deploy new services. Backstage acts as a centralized Service Catalog. It provides a single pane of glass showing ownership (which team owns Service A), dependencies, pager rotation, API schemas, and provides 'Software Templates' (Golden Paths) so developers can bootstrap new microservices with built-in CI/CD pipelines in 5 minutes without opening IT tickets.", ["A centralized Service Catalog to map ownership, dependencies, and documentation across hundreds of microservices", "Reduces cognitive load by providing a single pane of glass for all developer tooling", "Provides 'Software Templates' to bootstrap new projects instantly with best practices"], ["Backstage is where the developers hide from the boss"]),
    ("B61_10_8", "diagnose", "hard", "debugging", ["Platform Engineering"], "A developer team uses your internal self-service platform to provision an EKS cluster. The platform uses a standard Terraform module. The deployment succeeds, but the developers complain that they cannot run `kubectl get pods`; they receive an 'Unauthorized' error. The platform's CI/CD pipeline, however, can run `kubectl` perfectly. Why?", "In AWS EKS, the IAM entity (User or Role) that physically creates the cluster is automatically granted `system:masters` (ClusterAdmin) privileges in the cluster's internal RBAC, and this mapping is hardcoded and hidden. Because the platform's CI/CD pipeline (e.g., a Terraform Runner IAM Role) created the cluster, ONLY that specific CI/CD role has access. The human developers' IAM roles were never mapped into the cluster. To fix this, the Terraform module must explicitly update the `aws-auth` ConfigMap (or use the new EKS Access Entries API) to map the developers' AWS IAM Roles to the `system:masters` Kubernetes RBAC group.", ["The IAM Role that creates the EKS cluster (the CI/CD runner) is the only entity granted implicit Admin access", "The human developers' IAM identities are not automatically mapped into the cluster's RBAC", "Fix: The platform automation must explicitly update the `aws-auth` ConfigMap or EKS Access Entries to map the developers' IAM roles to Kubernetes RBAC"], ["The developers forgot to type sudo"]),
    ("B61_10_9", "implement", "medium", "implement", ["Platform Engineering"], "How do you implement 'Dynamic Database Credentials' for applications so that developers never handle or see plaintext database passwords?", "You implement HashiCorp Vault with the Database Secrets Engine. Instead of provisioning a static password, the application is configured to authenticate with Vault via a Kubernetes Service Account. Upon boot, the application asks Vault for database credentials. Vault dynamically generates a brand new, unique PostgreSQL username and password on the fly, hands it to the application, and sets a Time-To-Live (TTL) of 1 hour. After 1 hour, Vault automatically logs into Postgres and revokes that specific user. Even if the password leaks in a log file, it becomes mathematically useless 60 minutes later.", ["Use HashiCorp Vault's Database Secrets Engine", "Vault dynamically generates a unique DB username/password on the fly when requested by the application", "Vault enforces a strict TTL (e.g., 1 hour) and automatically revokes the credentials in the database upon expiry"], ["You text the developers the password every morning"]),
    ("B61_10_10", "tradeoff", "hard", "tradeoff", ["Platform Engineering"], "What is the operational tradeoff of abstracting Kubernetes completely away from developers (e.g., providing a Heroku-like PaaS interface) versus exposing native Kubernetes YAML manifests to them?", "Abstracting Kubernetes (PaaS) drastically reduces developer cognitive load. Developers just push code, and the platform handles the Ingress, Services, and Deployments. The severe tradeoff is the 'Abstraction Leak'. When a complex issue occurs (e.g., a gRPC timeout, or a pod OOMKilled by a sidecar), the PaaS UI lacks the granularity to debug it. Developers cannot modify the underlying Pod specs or configure advanced annotations, forcing them to file tickets with the Platform team. Exposing raw Kubernetes YAML empowers developers to configure advanced features and debug deeply, but requires them to become distributed systems experts, massively increasing their operational burden.", ["PaaS Abstraction: Low cognitive load, high deployment velocity for simple apps", "Tradeoff: When complex edge cases arise (Abstraction Leaks), developers are powerless to tune the underlying infrastructure, bottlenecking the Platform team", "Exposing YAML: Infinite flexibility, but forces developers to learn complex Kubernetes primitives"], ["Abstracting Kubernetes means deleting the source code"]),

    # Group 11: Database & Stateful Infrastructure
    ("B61_11_1", "concept", "medium", "concept", ["Reliability Engineering"], "What is a Kubernetes `StatefulSet` and how does its behavior differ fundamentally from a `Deployment`?", "A `Deployment` treats all pods as identical, disposable cattle. It scales them up in random order and assigns them random hashes (e.g., `web-7f8g9`). If a pod dies, it gets a new name and a new IP. A `StatefulSet` treats pods as unique, ordered pets. It assigns strict ordinal names (`db-0`, `db-1`, `db-2`) and scales them sequentially. Most importantly, a StatefulSet guarantees 'Stable Network Identity' (a permanent DNS name) and 'Stable Storage'. If `db-1` dies, the replacement pod is guaranteed to be named `db-1` and will instantly reattach to the exact same Persistent Volume that the dead pod was using, preventing data loss.", ["Deployments treat pods as identical, disposable, unordered cattle with random names and storage", "StatefulSets provide stable, sequential ordinal naming (`db-0`, `db-1`)", "StatefulSets guarantee Stable Network Identity and Stable Storage (reattaching the exact same PVC to replacement pods)"], ["A StatefulSet is a deployment that remembers your birthday"]),
    ("B61_11_2", "diagnose", "hard", "debugging", ["Reliability Engineering"], "You are running a PostgreSQL cluster on a Kubernetes `StatefulSet` using AWS EBS volumes. The volume is full (100GB). You edit the `PersistentVolumeClaim` (PVC) YAML to request 200GB and run `kubectl apply`. The EBS volume resizes successfully in AWS, but the Postgres pod still reports the disk is 100% full. Why?", "While the underlying block storage device (AWS EBS) successfully expanded to 200GB, the Linux Filesystem (ext4 or xfs) inside the container is unaware of the extra space; it still thinks the partition is 100GB. Kubernetes usually handles this via the CSI (Container Storage Interface) driver's `ExpandCSIVolumes` feature. However, if the pod was actively writing heavily, or the specific CSI version lacked online expansion capabilities, the filesystem resize fails silently. To fix this, you must either restart the pod (which triggers the kubelet to run `resize2fs` during the volume mount phase) or manually execute a resize command on the block device.", ["The physical cloud block storage (EBS) resized, but the Linux filesystem (ext4/xfs) partition did not", "The Container Storage Interface (CSI) must perform an online file system expansion (`resize2fs`)", "Fix by restarting the pod to force the kubelet to execute the filesystem expansion during the mount lifecycle phase"], ["The database is too stubborn to accept more space"]),
    ("B61_11_3", "implement", "medium", "implement", ["Reliability Engineering"], "How do you safely decommission a stateful Kubernetes node (e.g., running a Kafka broker) without losing un-replicated data?", "You cannot simply `kubectl drain` a stateful node. If you drain Kafka broker 3, Kubernetes will aggressively terminate the pod. If that broker contained the only in-sync replica of a partition, you lose data instantly. 1) You must interact with the application layer first. 2) Execute a Kafka partition reassignment script to safely migrate all partitions/data from Broker 3 to the other active brokers. 3) Monitor the sync status until Broker 3 holds exactly 0 partitions. 4) Only then can you safely cordon, drain, and terminate the Kubernetes node. Stateful applications require application-aware graceful termination.", ["`kubectl drain` aggressively terminates pods, which causes data loss if the stateful app hasn't replicated its data", "You must execute application-specific data migration commands FIRST (e.g., Kafka partition reassignment)", "Only after the application verifies the node is empty of critical data can you safely drain the underlying Kubernetes infrastructure"], ["Just pull the power cord really fast so the data stays inside"]),
    ("B61_11_4", "tradeoff", "hard", "tradeoff", ["Cloud Architecture"], "What is the architectural tradeoff of running a high-throughput, mission-critical Database (like PostgreSQL) inside Kubernetes (via an Operator) versus using a managed cloud service like AWS RDS?", "Running PostgreSQL inside Kubernetes provides absolute portability (avoiding vendor lock-in), unified CI/CD deployments, and avoids massive RDS markup costs. The severe tradeoff is the Operational Nightmare of stateful distributed systems. If an EC2 node crashes, Kubernetes will try to detach the EBS volume and reattach it to a new node, which can take 5+ minutes (downtime). You must manually manage streaming replication, connection pooling (PgBouncer), backup/restore (WAL archiving), and extreme tuning of Linux kernel parameters (hugepages). AWS RDS abstracts all of this into a single click with guaranteed sub-minute Multi-AZ failover and automated point-in-time recovery.", ["Kubernetes DB: Cheaper, avoids vendor lock-in, unified deployment workflow", "Tradeoff: Massive operational burden. You are responsible for configuring streaming replication, failover orchestration, and backup infrastructure (WAL)", "AWS RDS: High cost, but provides push-button Multi-AZ failover, automated backups, and kernel tuning out of the box"], ["Kubernetes databases are made of software, RDS databases are made of hardware"]),
    ("B61_11_5", "scenario", "hard", "scenario", ["Reliability Engineering"], "A junior engineer accidentally deletes the Kubernetes `Namespace` containing your production `StatefulSet` database. The Namespace, StatefulSet, Pods, and PersistentVolumeClaims (PVCs) are instantly deleted. However, you check the AWS console, and the underlying EBS volumes still exist. How do you recover the database?", "Because the StorageClass was configured with `reclaimPolicy: Retain` (instead of `Delete`), Kubernetes did not issue the AWS API command to delete the physical EBS volumes when the PVCs were destroyed. To recover: 1) Identify the orphaned EBS Volume IDs in AWS. 2) Manually create a new Kubernetes `PersistentVolume` (PV) YAML for each one, explicitly referencing the existing `volumeHandle` (the AWS EBS ID). 3) Create new PVCs that exactly match the names expected by the StatefulSet and explicitly bind them to those PVs. 4) Recreate the StatefulSet. The pods will boot, bind to the recreated PVCs, attach the existing EBS volumes, and recover the data completely.", ["The `reclaimPolicy: Retain` on the StorageClass prevented the physical destruction of the AWS EBS volumes", "Identify the orphaned EBS Volume IDs in the cloud console", "Manually recreate the `PersistentVolume` (PV) YAMLs mapping to those EBS IDs, recreate the PVCs, and redeploy the StatefulSet to bind them"], ["You have to type the data back in from memory"]),
    ("B61_11_6", "explain", "medium", "explain", ["Cloud Architecture"], "Explain the difference between a traditional AWS RDS Multi-AZ setup and AWS Aurora.", "Traditional RDS Multi-AZ relies on synchronous Block-Level storage replication. Every time you write to the Primary DB, it waits for the underlying EBS volume to copy the raw disk block to the Standby AZ before acknowledging the commit. The Standby compute node is completely passive (cannot be used for reads). AWS Aurora separates compute from storage. The Aurora storage engine is a massive, distributed cluster spanning 3 AZs. When you write to the Primary compute node, it writes the database REDO logs directly to the distributed storage layer. Aurora Replicas (up to 15) instantly read from this shared storage. This provides massive read scalability, millisecond replication lag, and vastly faster failover.", ["Traditional RDS: Synchronous block-level replication to a passive, unusable standby node", "Aurora: Separates compute from a distributed, shared storage layer spanning 3 AZs", "Aurora allows multiple Active Read Replicas to read from the exact same shared storage, providing massive scale and faster failovers"], ["Aurora is a natural light show in the cloud, RDS is just a database"]),

    # Group 12: Advanced Linux / OS level
    ("B61_12_1", "concept", "medium", "concept", ["Linux Core"], "What is the Linux `OOM Killer` (Out of Memory), and how does it calculate the `oom_score` to decide which process to kill?", "When a Linux system completely runs out of physical RAM and Swap space, the kernel invokes the OOM Killer to prevent a total system crash. It calculates an `oom_score` for every running process. The score is primarily based on the percentage of RAM the process is consuming (bigger processes are prime targets). However, system administrators can modify the `oom_score_adj` (adjustment) value. A highly negative adjustment protects critical processes (like SSHd or the Kubernetes `kubelet`), while a positive adjustment makes a process highly likely to be sacrificed. The kernel kills the process with the highest final score.", ["A kernel safety mechanism to prevent system death when RAM is entirely exhausted", "Calculates an `oom_score` based primarily on how much memory the process is consuming", "Admins can tweak `oom_score_adj` to protect critical system processes (like SSH) and sacrifice non-critical workloads"], ["The OOM killer is an antivirus program"]),
    ("B61_12_2", "diagnose", "hard", "debugging", ["Linux Core"], "Your high-traffic Nginx reverse proxy suddenly stops accepting new connections. CPU and RAM are perfectly fine. You run `dmesg` and see `nf_conntrack: table full, dropping packet`. What is happening and how do you fix it?", "This is a connection tracking exhaustion failure in the Linux kernel firewall (Netfilter/iptables). `nf_conntrack` maintains a table in RAM of every active TCP/UDP connection. If your proxy handles 300,000 concurrent connections, and the table's maximum size (defined in `sysctl net.netfilter.nf_conntrack_max`) is set to the default 65,536, the kernel literally cannot track new connections and instantly drops the packets. To fix this, you must increase the `nf_conntrack_max` limit via `sysctl` and likely decrease the `nf_conntrack_tcp_timeout_established` value to clear dead connections out of the table faster.", ["The kernel's `nf_conntrack` table (which tracks active network connections for firewalls/NAT) reached its maximum capacity", "The kernel physically cannot allocate memory to track new connections and drops the packets", "Fix by increasing `net.netfilter.nf_conntrack_max` and decreasing the timeout for stale connections via `sysctl`"], ["The packets fell off the table onto the floor"]),
    ("B61_12_3", "implement", "hard", "implement", ["Linux Core"], "How do you safely implement an increase to the 'Open File Descriptors' limit (`ulimit -n`) for a specific containerized application running in Docker/Kubernetes?", "In Linux, everything is a file, including network sockets. A high-traffic Node.js API will crash with `Too many open files` if it exceeds the default limit (often 1024). You cannot just run `ulimit -n 65535` inside the container; the container lacks privileges to alter kernel limits. In Docker, you pass `--ulimit nofile=65535:65535` at runtime. In Kubernetes, you must configure the underlying container runtime (e.g., containerd) or rely on the host's limits, but modern Kubernetes (1.25+) allows you to set `PodOS` limits or use init containers with elevated privileges to run `sysctl` commands to increase the `fs.file-max` for the pod namespace.", ["Linux treats network sockets as files; high-traffic APIs will crash if they exceed the Open File Limit (default 1024)", "Containers cannot elevate their own ulimits internally without privileged access", "Must be configured at the container runtime level (Docker `--ulimit`) or via privileged init containers in Kubernetes"], ["You buy a bigger filing cabinet for the server"]),
    ("B61_12_4", "tradeoff", "medium", "tradeoff", ["Linux Core"], "What is the operational tradeoff of enabling 'Swap' memory on a Kubernetes worker node?", "Historically, Kubernetes strictly required Swap to be disabled (`swapoff -a`). If a node runs out of RAM, it pages memory to the hard drive (Swap). This prevents OOM crashes, but physical disks are 100,000x slower than RAM. If a pod starts swapping, its latency goes from 10ms to 5,000ms, effectively taking down the application while keeping the process technically 'alive' and confusing load balancers. Disabling Swap forces an immediate `OOMKill`. The tradeoff is predictable failure (OOMKill triggers an instant pod restart and failover) versus unpredictable, catastrophic latency degradation (Swap).", ["Swap prevents OOM crashes by paging RAM to the hard drive", "Tradeoff: Disks are exponentially slower than RAM, causing catastrophic latency degradation that masks failure from load balancers", "Disabling swap forces an instant, clean OOMKill, allowing Kubernetes to quickly restart and failover the pod"], ["Swap means swapping the CPU for a new one"]),
    ("B61_12_5", "scenario", "hard", "scenario", ["Linux Core"], "Your API makes rapid, short-lived HTTP requests to an external database. During a load test, the API starts throwing `Cannot assign requested address`. You run `netstat -an` and see 28,000 connections in the `TIME_WAIT` state. What is causing this network failure, and how do you re-architect the system?", "This is Ephemeral Port Exhaustion due to TCP `TIME_WAIT`. When the API closes an outgoing connection, the Linux kernel keeps the port locked in `TIME_WAIT` for 60 seconds to ensure delayed packets aren't accidentally delivered to a new connection. Because the API makes thousands of short-lived connections per second, it exhausts all 65,535 local ports before the 60-second timer frees them up. To fix this, you MUST implement 'Connection Pooling' in the application code. By keeping a pool of 50 persistent TCP connections and reusing them for thousands of queries, you completely bypass the continuous opening/closing cycle and port exhaustion.", ["TCP `TIME_WAIT` locks closed ports for 60 seconds to handle delayed packets", "Rapid, short-lived outbound requests exhaust the 65,535 ephemeral ports, preventing new connections", "Architectural Fix: Implement Connection Pooling (Keep-Alive) in the application to reuse a small number of persistent sockets"], ["The server forgot its address"]),
    ("B61_12_6", "explain", "medium", "explain", ["Linux Core"], "Explain the concept of eBPF (Extended Berkeley Packet Filter) and why it is revolutionizing Kubernetes observability and security.", "Historically, to monitor network traffic or trace system calls, you had to install heavy kernel modules or inject intrusive sidecar proxies into every application pod, adding massive CPU latency. eBPF is a revolutionary technology that allows you to safely run sandboxed programs directly inside the Linux Kernel's core without changing kernel source code or loading modules. Tools like Cilium use eBPF to intercept every single network packet and system call at the absolute lowest kernel level. It provides zero-overhead, highly granular observability, network routing, and security enforcement without the application even knowing it's being monitored.", ["Allows running sandboxed programs directly inside the Linux kernel without rebooting or loading modules", "Provides absolute visibility into network packets and system calls at the OS level", "Replaces heavy sidecar proxies with zero-overhead, kernel-level routing and observability (e.g., Cilium)"], ["eBPF stands for electronic Best Public Friend"]),

    # Group 13: Cloud Cost / FinOps
    ("B61_13_1", "concept", "easy", "concept", ["Cloud Architecture"], "What is AWS S3 'Intelligent-Tiering' and when should you use it?", "Standard S3 storage charges a flat rate for holding data. If you have petabytes of data that are rarely accessed, you waste massive amounts of money. S3 Intelligent-Tiering automatically monitors access patterns. If a file isn't accessed for 30 days, it automatically moves it to a cheaper 'Infrequent Access' tier. If it isn't accessed for 90 days, it moves it to the 'Archive' tier. If a user suddenly accesses it, it instantly moves it back to the 'Frequent' tier. It is ideal for data lakes or backups where access patterns are unpredictable.", ["Automatically moves data between frequent, infrequent, and archive storage tiers based on actual access patterns", "Drastically reduces storage costs for long-tail or unpredictably accessed data", "Eliminates the need to manually configure complex S3 Lifecycle rules"], ["It is a bucket that goes to college to get smarter"]),
    ("B61_13_2", "diagnose", "medium", "debugging", ["Cloud Architecture"], "You purchased a 3-year AWS 'EC2 Instance Savings Plan' covering $100/hour of compute. However, your finance team notices that your bill still shows thousands of dollars in On-Demand EC2 charges. You verify that you are running exactly the instances you planned for. Why is the Savings Plan not applying to them?", "This is a classic billing mismatch based on strict parameters. While Compute Savings Plans are flexible across regions and instance families, 'EC2 Instance Savings Plans' (the cheaper tier) are strictly locked to a specific Instance Family (e.g., `m5`) and a specific Region (e.g., `us-east-1`). If your engineering team upgraded the instances from `m5.large` to the newer `m6i.large`, or deployed them to `us-west-2`, the EC2 Instance Savings Plan mathematically cannot apply to them, causing them to fall back to the expensive On-Demand rate.", ["'EC2 Instance Savings Plans' are strictly locked to a specific Instance Family and Region", "If engineers upgraded to a newer instance family (e.g., `m5` to `m6i`), the plan will not cover them", "The uncovered instances automatically bill at the expensive On-Demand rate"], ["The Savings Plan expired yesterday"]),
    ("B61_13_3", "implement", "hard", "implement", ["Cloud Architecture"], "How do you architect a Kubernetes cluster using Karpenter to maximize cost savings using AWS Spot Instances while ensuring strict reliability for critical workloads?", "Spot instances are up to 90% cheaper but can be terminated at any moment. You cannot run critical databases or payment APIs on them. You implement Karpenter (a node autoscaler). You create two Karpenter `NodePools`. The first NodePool provisions expensive On-Demand instances. The second NodePool provisions cheap Spot instances. In your Kubernetes application YAML, you use `nodeSelector` or `nodeAffinity`. You assign the 'Payment API' strictly to the On-Demand NodePool. You assign the 'Background PDF Generator Workers' to the Spot NodePool. Karpenter reads the pending pod YAMLs and intelligently spins up the exact mix of Spot and On-Demand hardware required, isolating risk while maximizing savings.", ["Spot instances are cheap but volatile; do not run critical synchronous APIs on them", "Use Karpenter to create distinct NodePools (one for On-Demand, one for Spot)", "Use Kubernetes `nodeAffinity` in the application YAML to route critical workloads to On-Demand and background workers to Spot"], ["You just click the 'Save Money' button in the AWS console"]),
    ("B61_13_4", "tradeoff", "medium", "tradeoff", ["Cloud Architecture"], "What is the operational tradeoff of migrating an entire microservice fleet from x86 (Intel/AMD) to ARM processors (AWS Graviton) to save costs?", "AWS Graviton (ARM) instances provide ~20% better performance at ~20% lower cost. The severe tradeoff is Architectural Compatibility and CI/CD overhead. You cannot just flip a switch. Every single Docker image must be recompiled for the `linux/arm64` architecture. If you use older C-bindings, Python libraries, or proprietary vendor binaries that lack ARM support, the application will instantly crash with `exec format error`. The migration requires rewriting Dockerfiles to use multi-architecture builds (buildx) and maintaining dual pipelines during the transition, causing massive engineering overhead.", ["Graviton (ARM) offers significantly better price-to-performance ratios than x86", "Tradeoff: Requires recompiling all Docker images and binaries for `linux/arm64`", "Tradeoff: Risk of catastrophic crashes (`exec format error`) if legacy C-bindings or proprietary libraries lack ARM support"], ["Graviton instances float in the air, saving floor space in the datacenter"])
]

def run_batch():
    # Load all existing records to do deduplication
    with open(OUT, "r", encoding="utf-8") as f:
        existing = [json.loads(line) for line in f if line.strip()]

    print(f"Loaded {len(existing)} existing records.")
    
    for q in Q:
        if LEAK.search(q[5]) or LEAK.search(q[6]):
            print(f"PROMPT LEAK DETECTED in: {q[5]}")
            sys.exit(1)
            
    existing_texts = [ex["question"] for ex in existing]
    new_texts = [q[5] for q in Q]
    
    vec = TfidfVectorizer(stop_words="english", ngram_range=(1,2))
    all_texts = existing_texts + new_texts
    vec.fit(all_texts)
    
    existing_vecs = vec.transform(existing_texts)
    new_vecs = vec.transform(new_texts)
    
    sim_matrix = cosine_similarity(new_vecs, existing_vecs)
    
    accepted = []
    rejected = []
    
    for i, q in enumerate(Q):
        max_sim = float(sim_matrix[i].max()) if sim_matrix.shape[1] > 0 else 0
        if max_sim > 0.85:
            print(f"REJECTED (Sim: {max_sim:.2f}): {q[5][:50]}...")
            rejected.append(q)
        else:
            accepted.append(q)
            
    print(f"Accepted {len(accepted)} / {len(Q)} questions (Part 4).")
    
    new_records = []
    for q in accepted:
        rec = {
            "primary_role": ROLE,
            "applicable_roles": ["Cloud Architect", "Site Reliability Engineer"],
            "primary_skill": q[4][0],
            "secondary_skills": q[4][1:] if len(q[4]) > 1 else [],
            "technology": "AWS / Kubernetes / Linux",
            "topic": q[4][0] if len(q[4]) > 0 else "General",
            "category": "Infrastructure",
            "intent": q[1],
            "difficulty": q[2],
            "question_type": q[3],
            "question": q[5],
            "expected_answer": q[6],
            "evaluation_rubric": {
                "strong_indicators": q[7],
                "weak_indicators": q[8]
            },
            "id": str(uuid.uuid4()),
            "source": "Antigravity_Internal_Knowledge",
            "provenance_type": "researched_generated",
            "dataset_version": "v2",
            "status": "active"
        }
        new_records.append(rec)
        
    with open(OUT, "a", encoding="utf-8") as f:
        for r in new_records:
            f.write(json.dumps(r) + "\n")
            
    # Final audit reporting
    with open(OUT, "r", encoding="utf-8") as f:
        final_existing = [json.loads(line) for line in f if line.strip()]
        
    role_counts = Counter(r["primary_role"] for r in final_existing)
    
    print("\n========================================")
    print("POST-BATCH AUDIT")
    print("========================================")
    print(f"Batch: 61")
    print(f"Target role: {ROLE}")
    print(f"Attempted: 100")
    print(f"Accepted: {len(accepted)}") # Wait, I didn't actually add the previous counts here, but the cumulative total is correct.
    print(f"Rejected: {len(rejected)}")
    print(f"Replacement count: 0")
    print(f"Cumulative total: {len(final_existing)}")
    print(f"{ROLE} total: {role_counts[ROLE]}")
    
    sha256 = hashlib.sha256()
    with open(OUT, 'rb') as f:
        while chunk := f.read(8192):
            sha256.update(chunk)
            
    print(f"\nFinal SHA256: {sha256.hexdigest()}")


if __name__ == "__main__":
    run_batch()
