import asyncio
import json
import os
import re
import sys
import uuid
import hashlib
from collections import Counter

from dotenv import load_dotenv
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
load_dotenv()

BACKEND_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_DIR = os.path.join(BACKEND_DIR, "data")
OUT = os.path.join(DATA_DIR, "interview_question_bank_v2_generated.jsonl")

ROLE = "Full Stack Developer"
LEAK = re.compile(r"(generate a question|generate \d+ questions|return only json|phase 4c gap plan|"
                  r"generation batch|candidate generation|system instructions|do not proceed|"
                  r"awaiting authorization|minimum target|generation pipeline|"
                  r"batch \d+ generation|expected answer|strong indicator|weak indicator|as an ai|"
                  r"here is the question|\bprompt text\b)", re.I)

Q = [
    # Group 1: Authentication & Identity (End-to-End)
    ("B60_1_1", "concept", "medium", "concept", ["Authentication"], "Explain the end-to-end security tradeoff of storing a JWT in `localStorage` versus a `HttpOnly` Cookie.", "Storing a JWT in `localStorage` makes it incredibly easy for the frontend (React/Vue) to attach it to API headers, but leaves it 100% exposed to any XSS attack (malicious JavaScript can read and exfiltrate the token). Storing it in an `HttpOnly` cookie prevents JavaScript from reading it entirely, eliminating XSS token theft. However, the browser automatically attaches the cookie to all requests to that domain, which introduces a severe vulnerability to CSRF (Cross-Site Request Forgery) attacks, requiring backend anti-CSRF tokens to mitigate.", ["localStorage: Easy frontend usage but highly vulnerable to XSS token theft", "HttpOnly Cookie: Immune to XSS (JS cannot read it)", "Tradeoff: HttpOnly cookies are vulnerable to CSRF, requiring backend anti-CSRF tokens"], ["localStorage requires a database, cookies require a browser"]),
    ("B60_1_2", "diagnose", "hard", "debugging", ["Authentication"], "A user logs in via a Single Page Application (SPA). The backend issues a JWT with a 1-hour expiration. An admin bans the user's account in the database 5 minutes later. However, the user continues to successfully use the app for the next 55 minutes. Why did the ban fail, and how do you fix it end-to-end?", "JWTs are stateless; the backend cryptographically verifies the signature without checking the database. Therefore, the banned user's token remains mathematically valid until it expires natively (55 minutes). To fix this, you must introduce state. Option 1: Keep JWTs short-lived (e.g., 5 minutes) and issue a stateful Refresh Token; the backend checks the ban status when a new JWT is requested. Option 2: Implement a fast in-memory 'Token Denylist' (Redis). The API Gateway checks Redis on every request to see if the JWT's `jti` (ID) or the `user_id` was actively revoked.", ["JWTs are stateless and mathematically valid until native expiration, regardless of DB state", "The backend does not query the DB on every request, so it misses the ban", "Fix by using short-lived JWTs + Refresh Tokens, or an in-memory Redis Denylist"], ["The admin forgot to click save in the database"]),
    ("B60_1_3", "implement", "hard", "implement", ["Authentication"], "How do you implement the OAuth 2.0 PKCE (Proof Key for Code Exchange) flow for a mobile app or SPA where you cannot securely store a Client Secret?", "Because SPAs/Mobile apps are public clients (the source code can be inspected), storing a static Client Secret is insecure. PKCE replaces the static secret with a dynamic one. 1) The client generates a random string (`code_verifier`) and hashes it (`code_challenge`). 2) The client redirects the user to the Auth Server, passing the `code_challenge`. 3) The Auth Server authenticates the user and returns an Authorization Code. 4) The client requests the actual tokens by sending the Authorization Code AND the original unhashed `code_verifier`. 5) The server hashes the verifier and compares it to the original challenge. This proves the client requesting the token is the exact same client that initiated the login, completely neutralizing authorization code interception attacks.", ["Public clients (SPA/Mobile) cannot securely store static Client Secrets", "Client generates a dynamic `code_verifier` and sends a hashed `code_challenge` to start login", "Client exchanges the Auth Code for tokens by proving it holds the unhashed `code_verifier`"], ["PKCE uses blockchain to secure the passwords"]),
    ("B60_1_4", "tradeoff", "medium", "tradeoff", ["Authentication"], "What is the architectural tradeoff of handling User Authentication at the API Gateway layer versus inside the individual Backend Microservices?", "Handling Auth at the API Gateway centralizes security. The Gateway validates the JWT, strips it, and passes a trusted HTTP header (e.g., `X-User-ID=123`) to the microservices. This makes the microservices blazing fast and agnostic to Auth protocols (SAML, OIDC). The severe tradeoff is that if an attacker bypasses the Gateway (e.g., SSRF or internal network compromise), the microservices blindly trust the headers, resulting in total system compromise. Doing Auth inside each microservice requires distributed secret management and duplicate verification logic, but provides 'Zero Trust' internal security.", ["Gateway Auth: Centralized, fast, simplifies microservices by passing trusted headers", "Tradeoff: Eliminates internal Zero Trust; if the network/gateway is breached, the entire system falls", "Microservice Auth: Requires duplicate logic and distributed keys, but guarantees Zero Trust security"], ["Gateway auth uses more RAM than microservice auth"]),
    ("B60_1_5", "scenario", "medium", "scenario", ["Authentication"], "You are building a SaaS application that serves multiple enterprise clients (Multi-Tenancy). A user logs in and the backend issues a session cookie. The user then opens a second browser tab and logs into a *different* tenant account using a different email. What severe UI/Backend data corruption occurs, and how do you prevent it?", "This is a 'Cross-Tenant Session Overwrite'. The browser shares the single session cookie across both tabs. When the user logs into Tenant B in Tab 2, the cookie is overwritten with Tenant B's session. If the user goes back to Tab 1 (which still displays Tenant A's UI) and clicks 'Delete Project', the frontend sends an API request. The backend reads the cookie, identifies the user as Tenant B, and deletes Tenant B's project (if IDs collide) or throws an auth error. You must fix this by namespacing cookies (e.g., subdomains `tenantA.app.com`), or explicitly sending the expected `Tenant-ID` in the API payload/header and validating it against the session cookie.", ["Browsers share cookies across tabs; logging into Tab 2 overwrites the session for Tab 1", "UI actions in Tab 1 will execute using Tab 2's session, causing severe data corruption or leaks", "Fix by using Subdomain-scoped cookies or enforcing explicit Tenant-ID header validation in the backend"], ["The user's computer will crash from too many tabs"]),
    ("B60_1_6", "explain", "medium", "explain", ["Authentication"], "Explain the end-to-end mechanism of CSRF (Cross-Site Request Forgery) and how the 'SameSite' cookie attribute mitigates it.", "In a CSRF attack, a user logs into your bank (Bank.com), receiving a session cookie. The user then visits a malicious site (Evil.com). Evil.com contains a hidden form that submits a POST request to `Bank.com/transfer`. Because the browser automatically attaches cookies to requests destined for that domain, the bank sees a valid session and transfers the money. The `SameSite=Lax` or `SameSite=Strict` cookie attribute instructs the browser: 'Do NOT attach this cookie if the request originated from a different domain (Evil.com)', effectively killing the CSRF attack at the browser level.", ["Attack: Malicious site forces the user's browser to make an authenticated request to a target site", "Browsers automatically attach cookies based on destination domain, bypassing origin checks", "SameSite attribute tells the browser to drop the cookie if the request origin doesn't match the destination"], ["CSRF is when a hacker steals your keyboard"]),
    ("B60_1_7", "concept", "easy", "concept", ["Authentication"], "What is the fundamental difference between Authentication and Authorization?", "Authentication (AuthN) verifies *who* the user is (e.g., verifying an email/password, validating a biometric, or checking a Google OAuth login). Authorization (AuthZ) verifies *what* that authenticated user is legally allowed to do within the system (e.g., checking if the user has the 'Admin' role required to delete a database record). Authentication is Identity; Authorization is Permissions.", ["Authentication (AuthN): Verifies Identity (Who you are)", "Authorization (AuthZ): Verifies Permissions (What you can do)", "AuthN = Login; AuthZ = RBAC/Permissions"], ["Authentication is for frontend, Authorization is for backend"]),
    ("B60_1_8", "diagnose", "hard", "debugging", ["Authentication"], "A React frontend sends a POST request with a valid JWT in the `Authorization: Bearer <token>` header. The backend responds with `401 Unauthorized` instantly, without hitting the application controller. However, GET requests to the exact same endpoint work perfectly. What network-level misconfiguration is causing this?", "This is a CORS (Cross-Origin Resource Sharing) Preflight failure. For complex requests (like POST, PUT, DELETE, or requests containing custom headers like `Authorization`), the browser automatically sends an HTTP `OPTIONS` request first (the preflight) to ask the server for permission. If the backend API Gateway or CORS middleware is not configured to explicitly allow the `OPTIONS` method or the `Authorization` header, the preflight fails. The browser intercepts the failure and blocks the actual POST request, but the developer tools often surface it confusingly as a network/auth failure.", ["CORS Preflight (OPTIONS) failure", "Complex requests (POST/Custom Headers) require a preflight check before the actual request", "Backend must explicitly allow the OPTIONS method and the 'Authorization' header in its CORS config"], ["The JWT expired exactly when they clicked POST"]),
    ("B60_1_9", "architecture", "medium", "architecture", ["Authentication"], "How do you architect a 'Refresh Token Rotation' system to prevent a stolen refresh token from providing perpetual access?", "If an attacker steals a long-lived Refresh Token, they can generate infinite JWTs. Refresh Token Rotation mitigates this by making refresh tokens single-use. When the client uses Refresh Token A to get a new JWT, the server returns a new JWT *and* a new Refresh Token B, and immediately invalidates A in the database. If an attacker uses the stolen Token A later, the server detects that a previously used/invalidated token was presented. This triggers a catastrophic security breach protocol: the server immediately invalidates the entire token family (Token B, C, D), locking out both the user and the attacker and forcing a hard re-login.", ["Make Refresh Tokens single-use (returning a new one every time)", "If a previously used token is presented again, it implies theft/cloning", "Instantly invalidate the entire token family, forcing a hard re-login for all devices"], ["You rotate the tokens by spinning the hard drive faster"]),
    ("B60_1_10", "tradeoff", "hard", "tradeoff", ["Authentication"], "What is the tradeoff of using standard RBAC (Role-Based Access Control) versus ABAC (Attribute-Based Access Control) in a complex Full Stack application?", "RBAC assigns static roles ('Admin', 'Editor') to users, making frontend UI rendering (e.g., hiding a button if `role != admin`) and backend validation incredibly simple. The tradeoff is 'Role Explosion'; if an editor can only edit documents in the 'Finance' department created after 2023, you have to create hyper-specific roles like `Finance_Editor_2023`. ABAC solves this by evaluating dynamic attributes at runtime (e.g., `user.department == doc.department AND doc.date > 2023`). ABAC is infinitely flexible, but it creates massive overhead: the backend must query the database for document metadata before authorizing the action, adding heavy latency.", ["RBAC is simple to implement and fast, but suffers from 'Role Explosion' for complex logic", "ABAC evaluates dynamic attributes (user, resource, environment) for infinite flexibility", "Tradeoff: ABAC requires complex policy engines and extra database queries to fetch resource attributes, adding latency"], ["RBAC uses roles, ABAC uses the abacus for math"]),

    # Group 2: Data Flow & Caching
    ("B60_2_1", "concept", "medium", "concept", ["State Management & Consistency"], "What is 'Optimistic UI Update', and what edge-case responsibility does it force on the frontend developer?", "An Optimistic Update assumes the backend API call will succeed. When a user clicks 'Like', the frontend instantly updates the UI to show the 'Like' before the HTTP request even completes, providing a zero-latency UX. The responsibility it forces on the frontend developer is 'Rollback Handling'. If the backend eventually responds with an HTTP 500 or network timeout, the frontend must manually catch the error, reverse the UI state (remove the 'Like'), and surface an error toast to the user. Without rollback logic, the frontend state and backend database will permanently diverge.", ["Updates the UI instantly before the HTTP request completes for zero-latency UX", "Forces the frontend to handle Rollbacks", "If the API fails, the UI must manually revert the state to prevent divergence from the Database"], ["Optimistic UI means the UI always smiles at the user"]),
    ("B60_2_2", "diagnose", "hard", "debugging", ["State Management & Consistency"], "A user updates their profile picture. The backend successfully processes the upload and updates the database. The frontend receives a 200 OK. However, the user's screen still shows the old picture. Refreshing the page (F5) doesn't fix it. Only a Hard Refresh (Ctrl+F5) fixes it. Why?", "This is a severe 'Cache Invalidation' failure between the CDN/Browser cache and the API. The browser is heavily caching the image URL (e.g., `profile.jpg`). Because the backend updated the file but kept the exact same URL, the browser serves the stale cached image locally. To fix this end-to-end, you must implement 'Cache Busting' (or Content-Addressable Storage). The backend should save the new image with a hash in the filename (e.g., `profile_a9f2.jpg`) and update the database pointer. The frontend will request the new unique URL, instantly bypassing all stale caches.", ["The browser/CDN cached the image URL heavily; updating the file without changing the URL serves stale cache", "Refreshing normally (F5) relies on cache; Hard Refresh (Ctrl+F5) bypasses it", "Fix by using Cache Busting (fingerprinting/hashing the filename, e.g., `profile_v2.jpg`)"], ["The picture was too heavy to download quickly"]),
    ("B60_2_3", "implement", "medium", "implement", ["State Management & Consistency"], "How do you implement HTTP `ETag` caching to minimize backend database load and frontend bandwidth for a large JSON payload?", "When the frontend requests the JSON, the backend calculates a hash of the response (the ETag) and sends it in the headers alongside the payload. The browser caches the JSON and the ETag. On the next request, the frontend automatically sends the `If-None-Match: <ETag>` header. The backend intercepts this, queries the DB, hashes the result, and compares it to the header. If they match, the backend aborts sending the payload and returns an empty `HTTP 304 Not Modified`. This saves massive network bandwidth and frontend parsing time.", ["Backend generates a hash of the payload (ETag) and sends it in headers", "Frontend sends `If-None-Match` with the saved ETag on subsequent requests", "If the backend data hasn't changed, it returns HTTP 304 (empty payload), saving bandwidth"], ["ETags are electronic tags you attach to the physical server"]),
    ("B60_2_4", "tradeoff", "hard", "tradeoff", ["State Management & Consistency"], "What is the architectural tradeoff of managing global frontend state using a rigid tool like Redux/Zustand versus a Server-State caching tool like React Query / SWR?", "Redux treats ALL data as 'Client State'. You must manually write thunks, reducers, and loading/error flags to fetch data, store it, and manually invalidate it. This provides absolute, granular control over the data flow, but requires massive boilerplate and usually results in stale data. React Query treats API data as 'Server State' simply borrowed by the client. It automatically handles fetching, caching, background refetching (on window focus), and garbage collection. The tradeoff is loss of synchronous, granular control; you must trust the library's cache lifecycle, which can cause confusing UI flashes if `staleTime` is misconfigured.", ["Redux requires massive boilerplate to manually manage async loading, errors, and caching", "React Query automates caching, refetching, and deduping by treating data as 'borrowed Server State'", "Tradeoff: Loss of strict synchronous control; misconfigured `staleTime` can cause unpredictable UI refetches"], ["Redux is for Red Hat Linux, React Query is for Windows"]),
    ("B60_2_5", "scenario", "medium", "scenario", ["State Management & Consistency"], "Your SPA displays a live 'Available Inventory' count for an item. The frontend fetches the count, sees '1 left', and allows the user to click 'Buy'. The backend processes the purchase. However, another user bought the exact same item a millisecond earlier. How do you architect the end-to-end flow to prevent overselling?", "The frontend state is inherently stale the millisecond it arrives. You cannot trust the frontend's '1 left' state. You must enforce integrity at the Database level using Optimistic Concurrency Control (OCC) or Row-Level Locking (`SELECT FOR UPDATE`). The backend transaction must explicitly lock the inventory row, verify the count is still > 0, decrement it, and commit. If it was already 0, the backend transaction rolls back and returns a `409 Conflict`. The frontend must catch this 409, display a 'Sold Out' error, and refresh the inventory state.", ["Frontend state is always stale; never trust client-side inventory validation", "Backend must use DB Transactions with Row-Level Locking or Optimistic Concurrency Control", "If sold out, return HTTP 409; frontend catches this and updates the UI gracefully"], ["Make the frontend check the database every 1 millisecond"]),
    ("B60_2_6", "explain", "medium", "explain", ["State Management & Consistency"], "Explain the 'Cache Stampede' (Thundering Herd) problem between a high-traffic frontend and a backend database.", "A Cache Stampede occurs when a highly requested, expensive API payload expires from the cache (e.g., Redis). Instantly, 5,000 concurrent frontend requests hit the API. Because the cache is empty, all 5,000 threads simultaneously bypass the cache and query the backend database for the exact same data. The database CPU hits 100% and crashes. To fix this, you must implement 'Cache Locking' (only the first thread is allowed to query the DB, the other 4,999 wait for the cache to be repopulated) or use background pre-computation to refresh the cache *before* it expires.", ["Occurs when a popular cache key expires and thousands of requests hit simultaneously", "All requests bypass the empty cache and query the database at once, causing a DB crash", "Fix using Cache Locking (Mutex) or background cache warming"], ["It happens when the server farm gets attacked by actual cows"]),
    ("B60_2_7", "concept", "easy", "concept", ["State Management & Consistency"], "What is 'Debouncing' in frontend development, and how does it protect the backend?", "Debouncing is a programming pattern used to limit the rate at which a function fires. If a user types into an autocomplete search bar ('h-e-l-l-o'), firing an API request on every single keystroke will overwhelm the backend with useless partial searches. A Debounce function forces the frontend to wait a specified time (e.g., 300ms) *after the user stops typing* before firing the actual API request, drastically reducing database load and network traffic.", ["Limits the rate at which a function fires during rapid events (e.g., typing, scrolling)", "Waits a specified time (e.g., 300ms) after the user stops acting before executing", "Protects the backend/DB from being flooded with useless partial queries"], ["Debouncing means bouncing the user to a different server"]),
    ("B60_2_8", "diagnose", "hard", "debugging", ["State Management & Consistency"], "A user submits a 'Create Order' form. The API takes 5 seconds to respond. Impatient, the user clicks the 'Submit' button 4 more times. The frontend finally redirects them. The user checks their account and sees 5 identical orders, and their credit card was charged 5 times. Where did the architecture fail, and how do you fix it end-to-end?", "The architecture failed on both the Frontend and the Backend. Frontend fix: The UI failed to disable the Submit button and show a loading state immediately upon the first click, allowing rapid re-submissions. Backend fix: The API lacks 'Idempotency'. The backend must require the frontend to generate a unique `Idempotency-Key` (UUID) when the form loads, and send it in the POST headers. The backend checks a fast cache (Redis) for that key; if it exists, it ignores the duplicate request and safely returns the cached original response, preventing duplicate DB inserts and charges.", ["Frontend Failure: UI did not disable the submit button or show a loading state on click", "Backend Failure: API is not Idempotent (it blindly processed duplicate POSTs)", "Fix: Use unique `Idempotency-Key` headers; backend skips processing if the key was already used"], ["The credit card company was too greedy"]),
    ("B60_2_9", "architecture", "hard", "architecture", ["State Management & Consistency"], "How do you architect a data flow to handle 'Pagination' on a rapidly changing database table (e.g., a live Twitter feed)?", "Using traditional Offset/Limit pagination (`OFFSET 20 LIMIT 10`) is catastrophically broken for real-time feeds. If a new tweet is inserted while the user is on Page 1, all records shift down by 1. When the user requests Page 2 (Offset 20), the last item from Page 1 has shifted into the 20th position, causing the frontend to display the exact same item twice (or skip items). You must architect 'Cursor-Based Pagination'. The frontend requests `LIMIT 10 AFTER_ID=945`. The backend uses the physical indexed ID (or timestamp) to fetch the next 10 items. Because it is tied to an absolute anchor, shifting data does not cause duplicates.", ["Traditional Offset/Limit pagination causes duplicates/skips when data shifts in real-time", "Must architect Cursor-Based Pagination (e.g., `LIMIT 10 AFTER_ID=X`)", "Uses an absolute database anchor (ID/Timestamp) to fetch the next items, immune to row shifting"], ["You paginate by printing the feed onto physical paper"]),
    ("B60_2_10", "tradeoff", "medium", "tradeoff", ["State Management & Consistency"], "What is the tradeoff of relying on the Backend to stitch together data from 5 microservices versus having the Frontend SPA make 5 independent API calls?", "Having the Frontend make 5 independent calls allows it to render each component progressively (e.g., the profile loads instantly, the feed loads later), making the app feel incredibly fast. The tradeoff is severe battery/bandwidth drain on mobile devices and complex frontend state management to handle 5 independent loading/error states. Having a Backend-For-Frontend (BFF) stitch the data into one massive JSON payload simplifies the frontend code and reduces HTTP overhead, but creates a 'Waterfall' bottleneck: the frontend cannot render *anything* until the slowest of the 5 microservices finishes.", ["Frontend orchestration: Progressive rendering, but causes battery/bandwidth drain and complex UI state", "Backend orchestration (BFF): Single payload, simple UI state, low HTTP overhead", "Tradeoff: BFF creates a waterfall bottleneck (UI blocked by the slowest microservice)"], ["Microservices cannot talk to each other, only to the frontend"]),

    # Group 3: Real-Time & Event-Driven
    ("B60_3_1", "concept", "medium", "concept", ["Real-Time Systems"], "What is the architectural difference between WebSockets and Server-Sent Events (SSE)?", "WebSockets provide full-duplex, bi-directional communication. The client and server can send messages to each other simultaneously over a single persistent TCP connection. It is ideal for highly interactive apps (like Multiplayer Games or Chat). Server-Sent Events (SSE) provide unidirectional, server-to-client communication over standard HTTP. The client opens the connection, and only the server can push updates down. SSE is vastly simpler to scale, natively supports HTTP/2 multiplexing, and gracefully handles automatic reconnects, making it perfect for live dashboards or notification feeds where the client doesn't need to stream data back.", ["WebSockets: Bi-directional, full-duplex communication over a custom protocol", "SSE: Unidirectional (Server-to-Client) streaming over standard HTTP", "SSE is simpler to scale and auto-reconnects, ideal for live feeds and notifications"], ["WebSockets use sockets, SSE uses events"]),
    ("B60_3_2", "diagnose", "hard", "debugging", ["Real-Time Systems"], "Your React app establishes a WebSocket connection to a Node.js backend to receive live stock prices. It works perfectly on your local machine. In production, the WebSocket connects, but exactly 60 seconds later, it silently drops. The browser shows no errors until the user tries to interact. What infrastructural issue is causing this?", "This is a Load Balancer / Reverse Proxy (Nginx/AWS ALB) Idle Timeout issue. In production, WebSockets route through proxies. If the stock market is quiet and no messages are sent for 60 seconds, the Load Balancer assumes the TCP connection is dead/zombied and aggressively terminates it to save resources. To fix this end-to-end, you must implement a 'Ping/Pong' heartbeat mechanism. The frontend or backend must send a tiny generic ping message every 30 seconds to keep the connection active in the proxy's routing table.", ["Load Balancers/Proxies aggressively terminate idle TCP connections (often at 60s)", "Local environments lack these strict infrastructural proxies, masking the issue", "Fix by implementing a Ping/Pong heartbeat mechanism to keep the connection active"], ["The stock market closed"]),
    ("B60_3_3", "implement", "medium", "implement", ["Real-Time Systems"], "How do you implement scalable 'Presence' (knowing which users are currently online) in a horizontally scaled chat application with 10 backend server nodes?", "If User A connects to Node 1 via WebSocket, Node 2 has no idea they are online. You cannot store presence in local server memory. You must implement a centralized, fast Key-Value store (Redis). When a user connects, the Node writes a key `presence:userA` with an expiry (TTL) of 30 seconds into Redis. The frontend must send a heartbeat every 15 seconds to refresh the TTL. If the user closes the browser or their network drops, the heartbeat stops, the Redis TTL expires automatically, and a Pub/Sub event is broadcast to all nodes to update the UI showing the user as 'Offline'.", ["Local memory fails because WebSockets are distributed across multiple horizontal nodes", "Use Redis to store presence keys with a short TTL (e.g., 30s)", "Frontend heartbeats refresh the TTL; if disconnected, TTL expires and triggers an offline broadcast"], ["Ask users to click an 'I am online' button every 5 minutes"]),
    ("B60_3_4", "tradeoff", "hard", "tradeoff", ["Real-Time Systems"], "What is the tradeoff of using Long Polling versus WebSockets for a real-time notification system?", "Long Polling works over standard HTTP: the client requests data, the server holds the request open until data is available, sends it, and the client immediately reconnects. It is incredibly robust, works through corporate firewalls/proxies that block WebSockets, and is easy to load-balance statelessly. The severe tradeoff is massive HTTP overhead (headers/handshakes on every reconnect) and latency. WebSockets maintain a persistent low-overhead connection for instant delivery, but are highly stateful. Load balancing WebSockets requires sticky sessions or central Pub/Sub (Redis), vastly complicating the backend deployment.", ["Long Polling is robust, stateless, and traverses firewalls easily", "Tradeoff: Massive HTTP overhead and latency due to constant reconnects", "WebSockets are instant and low-overhead, but highly stateful, requiring complex load balancing (sticky sessions/PubSub)"], ["Long polling uses a longer ethernet cable"]),
    ("B60_3_5", "scenario", "medium", "scenario", ["Real-Time Systems"], "A user is editing a shared document. Their train goes through a tunnel, and they lose internet for 2 minutes. They continue typing. When the internet returns, how do you architect the system to sync their offline changes without overwriting what other users typed during those 2 minutes?", "You cannot simply send a massive `PUT` request replacing the entire document. You must architect the system using Operational Transformation (OT) or Conflict-Free Replicated Data Types (CRDTs). The frontend must record the user's edits as an ordered log of granular operations (e.g., 'Insert letter H at position 5'). When the connection restores, the frontend pushes this log to the backend. The backend's CRDT algorithm mathematically merges these operations with the operations submitted by other users during the offline window, guaranteeing eventual consistency without destroying anyone's work.", ["Cannot blindly overwrite the document; requires granular merging", "Use Operational Transformation (OT) or CRDTs (Conflict-Free Replicated Data Types)", "Frontend queues granular edit operations offline, backend mathematically merges them upon reconnection"], ["Just ban users from editing on trains"]),
    ("B60_3_6", "explain", "medium", "explain", ["Real-Time Systems"], "Explain the 'Thundering Herd' problem that occurs when a real-time WebSocket server crashes.", "If a backend WebSocket server node crashes, 100,000 users are instantly disconnected. All 100,000 client browsers will immediately detect the disconnect and instantly attempt to reconnect to the surviving nodes at the exact same millisecond. This massive spike in TCP handshakes and Auth queries will overwhelm the surviving nodes and the database, causing a cascading failure that takes down the entire system. To prevent this, the frontend reconnect logic MUST implement 'Exponential Backoff with Jitter' (adding a random delay before retrying) to spread the traffic wave out over several minutes.", ["Server crash disconnects all clients simultaneously", "Clients instantly attempt to reconnect at the exact same millisecond, crashing the surviving infrastructure", "Frontend MUST implement Exponential Backoff with Jitter to randomize and spread out reconnect attempts"], ["It is a herd of actual rhinos in the datacenter"]),
    ("B60_3_7", "concept", "easy", "concept", ["Real-Time Systems"], "What is 'Eventual Consistency' in distributed/real-time systems?", "Eventual Consistency means that if you stop making changes to a system, eventually all nodes, databases, and connected UI clients will synchronize and reflect the exact same data. It acknowledges that propagating data across networks takes time. For example, if you change your profile picture, Node A might update instantly, but Node B (and users connected to it) might show the old picture for a few seconds. The system sacrifices 'Strong Consistency' (locking the whole system until everyone updates) to achieve massive scalability and low latency.", ["Acknowledges that data propagation across distributed networks takes time", "If updates stop, all nodes/clients will eventually reflect the identical state", "Trades strict synchronous locking for high availability and low latency"], ["It means the backend developers will eventually fix the bugs"]),
    ("B60_3_8", "diagnose", "medium", "debugging", ["Real-Time Systems"], "Your frontend listens to a WebSocket for live chat messages. Users complain that occasionally, a message appears twice in their UI. You check the backend database, and the message is only saved once. What architectural edge case causes this duplicate UI rendering?", "This is an 'Echo' or 'Race Condition' between the REST API and the WebSocket Pub/Sub. When the user sends a message, the frontend optimistically renders it in the UI and sends a POST request. The backend saves it, and publishes it to Redis. The WebSocket server pushes the new message to ALL connected clients, *including the sender*. If the frontend does not assign a unique idempotency ID (UUID) to the optimistic message, it receives the WebSocket push, assumes it's a brand new message, and renders it again. The frontend must filter incoming socket messages against its local optimistic UI list.", ["Race condition between Optimistic UI and the WebSocket broadcast return (Echo)", "The sender receives their own message back via the WebSocket broadcast", "Frontend must use UUIDs to deduplicate incoming socket messages against its local optimistic state"], ["The user clicked the send button twice really fast"]),
    ("B60_3_9", "architecture", "hard", "architecture", ["Real-Time Systems"], "How do you architect a scalable WebSocket backend using Redis Pub/Sub?", "WebSockets are stateful; a connection is locked to a specific physical server (e.g., Node A). If User 1 connects to Node A, and User 2 connects to Node B, they cannot chat directly. You must architect a backplane. When User 1 sends a message to a chatroom, Node A receives it and publishes the payload to a Redis Pub/Sub channel (e.g., `channel:chatroom123`). ALL WebSocket nodes (A, B, C) are subscribed to this Redis channel. Node B receives the event from Redis and pushes it down the active WebSocket connection to User 2. Redis acts as the high-speed nervous system connecting the isolated stateful nodes.", ["WebSockets are stateful and locked to isolated physical nodes", "Use Redis Pub/Sub as a central message backplane", "Nodes publish incoming messages to Redis; all nodes subscribe and broadcast relevant events to their connected clients"], ["You wire all the servers together with a single USB cable"]),
    ("B60_3_10", "tradeoff", "hard", "tradeoff", ["Real-Time Systems"], "What is the tradeoff of relying entirely on WebSockets for all API communication (Data fetching, Auth, Mutations) instead of mixing REST/GraphQL with WebSockets?", "Relying 100% on WebSockets eliminates HTTP overhead (headers) and provides incredible speed. The severe tradeoff is the complete destruction of the standard web ecosystem. WebSockets cannot leverage Browser/CDN caching (no ETags, no HTTP 304). They lack standard HTTP status codes (no 404, 500, 401), forcing you to reinvent error handling and routing JSON schemas from scratch. Mixing them (REST for heavy/cacheable data fetching, WebSockets purely for live event triggers) provides the best of both worlds.", ["100% WebSockets provides extreme speed and zero HTTP overhead", "Tradeoff: Completely breaks Browser/CDN caching, requiring you to reinvent state management", "Tradeoff: Lacks standard HTTP routing/status codes, forcing custom error handling logic"], ["WebSockets use up all the electricity in the datacenter"])
]

def run_batch():
    with open(OUT, "a", encoding="utf-8") as f:
        for q in Q:
            rec = {
                "primary_role": ROLE,
                "applicable_roles": ["Frontend Developer", "Backend Developer"],
                "primary_skill": q[4][0],
                "secondary_skills": q[4][1:] if len(q[4]) > 1 else [],
                "technology": "Full Stack",
                "topic": q[4][0] if len(q[4]) > 0 else "General",
                "category": "Software Engineering",
                "intent": q[1],
                "difficulty": q[2],
                "question_type": q[3],
                "question": q[5],
                "expected_answer": q[6],
                "evaluation_rubric": {
                    "strong_indicators": q[7],
                    "weak_indicators": q[8]
                },
                "id": str(uuid.uuid4()),
                "source": "Antigravity_Internal_Knowledge",
                "provenance_type": "researched_generated",
                "dataset_version": "v2",
                "status": "active"
            }
            f.write(json.dumps(rec) + "\n")
            
    print(f"Appended {len(Q)} questions (Batch 60 Part 1).")

if __name__ == "__main__":
    run_batch()
