import asyncio
import json
import os
import re
import sys
import uuid
from collections import Counter
import hashlib

from dotenv import load_dotenv
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
load_dotenv()

BACKEND_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_DIR = os.path.join(BACKEND_DIR, "data")
REPORTS_DIR = os.path.join(BACKEND_DIR, "reports")
OUT = os.path.join(DATA_DIR, "interview_question_bank_v2_generated.jsonl")

ROLE = "Backend Developer"
VALID_INTENTS = {"fundamentals", "explain", "implement", "tradeoff", "debug", "scenario", "compare",
                 "architecture", "optimize", "diagnose"}
LEAK = re.compile(r"(generate a question|generate \d+ questions|return only json|phase 4c gap plan|"
                  r"generation batch|candidate generation|system prompts|do not proceed|"
                  r"awaiting authorization|minimum target|generation pipeline|"
                  r"batch \d+ generation|expected answer|strong indicator|weak indicator|as an ai|"
                  r"here is the question|\bprompt text\b)", re.I)

Q = [
    # Area 1: Event Sourcing & CQRS
    ("A1", "architecture", "hard", "concept", ["Architecture"], "How does Event Sourcing fundamentally change the way application state is stored compared to a traditional CRUD relational model?", "In a traditional CRUD model, the database stores the current state of an entity and overwrites it on updates. In Event Sourcing, state is never overwritten; instead, the database stores an immutable, append-only log of every state-changing event (e.g., 'OrderCreated', 'ItemAdded', 'OrderShipped'). The current state is derived dynamically by replaying these events from the beginning.", ["Mentions append-only immutable event log", "Contrasts with overwriting current state in CRUD", "Mentions replaying events to derive current state"], ["Says it means using Kafka for everything"]),
    ("A1", "tradeoff", "hard", "tradeoff", ["Architecture"], "What are the primary architectural tradeoffs when adopting CQRS (Command Query Responsibility Segregation) in a microservices backend?", "CQRS allows independent scaling of read and write workloads and enables highly optimized read models (projections) tailored for specific UI views. However, the major tradeoffs include extreme architectural complexity, the necessity of dealing with Eventual Consistency between the write and read models, complex debugging, and the overhead of maintaining infrastructure for both models and the event bus.", ["Allows independent scaling and optimized read models", "Tradeoff: Eventual consistency between writes and reads", "Tradeoff: Significant architectural and operational complexity"], ["CQRS makes the database strictly consistent"]),
    ("A1", "diagnose", "medium", "debugging", ["Architecture"], "In a CQRS system, a user submits a command to change their profile name. They immediately refresh the page and see their old name. Explain why this happens and how to fix the user experience.", "This happens due to the Eventual Consistency inherent in CQRS. The write model accepted the command and published an event, but the read model (projection) hasn't finished consuming the event and updating the query database yet. To fix the UX, you can use 'Read-Your-Own-Writes' techniques: the UI can optimistically update the cache, or the backend can block the HTTP response until the read model catches up (using a correlation ID), or the UI can poll until the version updates.", ["Caused by Eventual Consistency (read model lags write model)", "Fix: Optimistic UI updates", "Fix: Blocking until correlation ID appears in read model or polling"], ["The database crashed"]),
    ("A1", "scenario", "hard", "scenario", ["Architecture"], "Your event-sourced system has accumulated 5 million events for a single 'BankAccount' aggregate. Replaying the event stream to calculate the current balance now takes 10 seconds. How do you optimize this?", "You implement 'Snapshots'. A background process periodically calculates the aggregate's state (e.g., every 1000 events or every night) and saves this materialized state as a snapshot. When the application needs the current balance, it loads the most recent snapshot and only replays the small delta of events that occurred *after* the snapshot was taken, reducing the replay overhead from 5 million events to a few hundred.", ["Implement Snapshots (or Materialized Views)", "Calculate and save the state at a specific point in time", "Load snapshot and replay only the delta of new events"], ["Delete the old events"]),
    ("A1", "concept", "medium", "concept", ["Architecture"], "Why is it strictly prohibited to execute side effects (like sending an email or charging a credit card) directly inside the event replay logic of an Event Sourced aggregate?", "Because event replay is used strictly to rebuild the application's internal state. An aggregate might be replayed thousands of times over its lifecycle (e.g., after a cache eviction, server restart, or debugging session). If side effects were in the replay logic, you would send thousands of duplicate emails or credit card charges every time the state is rebuilt. Side effects must only happen in reaction to new events being explicitly published to a separate event handler/saga.", ["Event replay happens multiple times to rebuild state", "Side effects during replay would cause duplicate actions (emails, charges)", "Side effects must happen in separate downstream event handlers"], ["It makes the replay too slow"]),
    ("A1", "compare", "medium", "compare", ["Architecture"], "Compare 'Event Sourcing' to 'Event-Driven Architecture'. Are they the same thing?", "They are distinct concepts. Event-Driven Architecture (EDA) means microservices communicate by publishing and reacting to events via a broker (like Kafka or RabbitMQ); the services themselves may still use standard CRUD databases. Event Sourcing is a specific data-storage pattern where the *source of truth* for a single service is an append-only log of events, rather than current state. A system can be Event-Driven without being Event Sourced, and vice versa.", ["EDA is a communication pattern between services", "Event Sourcing is a data-storage pattern within a service", "They can be used independently"], ["They are exactly the same"]),
    ("A1", "architecture", "hard", "architecture", ["Architecture"], "If you deploy a bug in your CQRS read-model projection logic that corrupts the read database for a week, how do you recover the corrupted data?", "One of the greatest benefits of Event Sourcing/CQRS is that the write-model event log is the immutable source of truth. To recover the read database, you simply fix the bug in the projection code, wipe the corrupted read database completely clean, and replay the entire event stream from the beginning of time through the fixed projection logic to rebuild a perfect read model.", ["Wipe the corrupted read database", "Replay the immutable event log from the beginning of time", "The immutable write model acts as a perfect recovery source"], ["Restore from a nightly SQL backup"]),
    ("A1", "design", "medium", "architecture", ["Architecture"], "When designing the schema for an Event Store database, what are the essential columns required for the event log table?", "At a minimum, an Event Store table needs: `Aggregate_ID` (to identify the entity), `Version` or `Sequence_Number` (to enforce optimistic concurrency and strict ordering), `Event_Type` (e.g., 'UserCreated'), `Payload` (JSON/binary of the event data), and `Timestamp`. The combination of `Aggregate_ID` and `Version` is typically the composite primary key.", ["Aggregate_ID (entity identifier)", "Version or Sequence_Number (for concurrency and ordering)", "Event_Type and Payload (JSON/data)"], ["A column for every possible entity attribute"]),
    ("A1", "scenario", "hard", "scenario", ["Architecture"], "In an Event Sourced system, the business decides that the 'AddressUpdated' event payload needs a new required 'CountryCode' field that didn't exist in the first three years of events. How do you handle this schema evolution when replaying old events?", "You implement Event Upcasting. You intercept the raw JSON of old 'AddressUpdated' events as they are loaded from the database, before they are deserialized into modern objects. The upcaster injects a default 'CountryCode' (e.g., 'US') into the JSON payload of legacy events. This allows the application logic to only ever deal with the latest schema version, without actually mutating the historical events on disk.", ["Implement Event Upcasting", "Transform legacy event JSON payloads into the new schema on the fly during read", "Prevents mutating the immutable historical events on disk"], ["Run a SQL UPDATE to alter the old events"]),
    ("A1", "tradeoff", "easy", "tradeoff", ["Architecture"], "Why is CQRS/Event Sourcing generally a poor choice for a simple administrative CRUD dashboard?", "CQRS and Event Sourcing introduce massive accidental complexity, requiring separate read/write models, event buses, projection logic, and handling of eventual consistency. A simple admin dashboard only requires basic Create/Read/Update/Delete operations on single records, which a traditional relational database handles trivially with strong consistency and minimal code. The overhead vastly outweighs the benefits.", ["Introduces massive accidental complexity (event buses, eventual consistency)", "Simple CRUD is handled trivially and consistently by traditional ORMs/RDBMS", "The architectural overhead outweighs the benefits for simple domains"], ["Event sourcing is too fast for admin dashboards"]),

    # Area 2: Distributed Locking & Concurrency Control
    ("A2", "concept", "medium", "concept", ["Concurrency"], "What is the difference between Optimistic Concurrency Control (OCC) and Pessimistic Locking?", "Pessimistic locking physically locks a row or resource in the database (e.g., `SELECT FOR UPDATE`) so no other transaction can read or write it until the lock is released; it prevents conflicts but limits scalability and risks deadlocks. Optimistic Concurrency Control (OCC) does not lock anything; instead, it reads the data and a version token, performs the logic, and upon writing, verifies the version token hasn't changed. If it has, the transaction aborts and retries (e.g., throwing a Conflict exception).", ["Pessimistic locks the resource physically, preventing access (SELECT FOR UPDATE)", "Optimistic doesn't lock; it checks a version token at the time of write", "Optimistic is better for high read/low conflict, Pessimistic for high conflict"], ["Optimistic means hoping the network works"]),
    ("A2", "scenario", "hard", "scenario", ["Concurrency"], "You are building a ticket booking system where inventory is extremely limited (high contention). Why might Optimistic Concurrency Control (OCC) perform poorly here compared to Pessimistic Locking?", "Under high contention (many users fighting for the same few tickets), OCC will result in massive failure rates. One user will succeed, and 99 users will encounter version mismatches and be forced to retry. These constant aborts and retries waste CPU, database connections, and increase latency. Pessimistic locking (or a queuing system) serializes the requests directly at the database level, avoiding the expensive cycle of read-process-abort-retry.", ["High contention causes OCC to constantly abort and retry (thrashing)", "Wastes CPU and DB connections on failed transactions", "Pessimistic locking serializes the requests efficiently at the DB level"], ["OCC is always faster because there are no locks"]),
    ("A2", "implement", "medium", "implement", ["Concurrency"], "How do you implement Optimistic Concurrency Control in a standard relational database table?", "Add a `version` (integer) or `updated_at` (timestamp) column to the table. When the application reads the row, it stores the version (e.g., `v=1`). When it issues the update, it explicitly adds the version to the WHERE clause: `UPDATE table SET ... version = 2 WHERE id = 123 AND version = 1`. If the database reports that 0 rows were updated, it means another transaction modified the row in the meantime, and the application throws a concurrency exception.", ["Add a version/timestamp column", "Include `AND version = <original_version>` in the UPDATE WHERE clause", "Check if rows_affected == 0 to detect a conflict"], ["Use a SELECT FOR UPDATE query"]),
    ("A2", "architecture", "hard", "architecture", ["Distributed Systems"], "You implement a Distributed Lock using Redis with `SET resource_name my_random_value NX PX 30000`. Why is the `my_random_value` and a specific Lua script required when releasing the lock?", "The random value ensures that a client only deletes *its own* lock. If Client A acquires the lock, pauses for 40 seconds (exceeding the 30s TTL), Redis auto-releases it. Client B then acquires the lock. If Client A wakes up and simply sends a `DEL resource_name` command, it will accidentally delete Client B's lock, destroying mutual exclusion. The Lua script atomically checks if the value matches `my_random_value` before deleting it, preventing this race condition.", ["Random value identifies the lock owner", "Prevents Client A from deleting Client B's lock after a TTL expiration", "Lua script ensures the check and delete are perfectly atomic"], ["Redis requires random values for encryption"]),
    ("A2", "diagnose", "medium", "debugging", ["Concurrency"], "A background cron job runs every minute on multiple server instances to process pending emails. You notice that emails are frequently being sent multiple times. The developers used `SELECT * FROM emails WHERE status = 'pending'` followed by `UPDATE ... SET status = 'processing'`. What is wrong?", "This is a classic Race Condition. Multiple instances execute the `SELECT` query at the exact same millisecond before any instance has a chance to execute the `UPDATE`. They all fetch the same pending emails and all process them. To fix this, you must use atomic row-level locking (e.g., `SELECT ... FOR UPDATE SKIP LOCKED` in Postgres) or use an atomic `UPDATE ... RETURNING` statement to claim the rows safely.", ["Race condition between the SELECT and the UPDATE", "Multiple instances read the same rows before they are marked processing", "Fix by using `SELECT FOR UPDATE SKIP LOCKED` or a message queue"], ["The cron job is running too slowly"]),
    ("A2", "concept", "hard", "concept", ["Distributed Systems"], "Explain the 'Redlock' algorithm used for distributed locking in a Redis cluster. Why is a single Redis instance insufficient for highly reliable distributed locking?", "A single Redis instance represents a single point of failure. If the master node crashes after granting a lock but before replicating it to a replica, the replica is promoted, and another client can acquire the exact same lock, violating mutual exclusion. Redlock solves this by using multiple independent Redis master nodes (e.g., 5). A client must acquire the lock on a majority (quorum, e.g., 3 out of 5) of the independent nodes within a short timeout window to successfully hold the distributed lock.", ["Single Redis node failover can lose locks and violate mutual exclusion", "Redlock uses multiple independent Redis master nodes", "Client must acquire the lock on a majority (quorum) of the nodes"], ["Redlock encrypts the lock in red text"]),
    ("A2", "tradeoff", "medium", "tradeoff", ["Distributed Systems"], "What is the primary danger of relying on distributed locks (like Redis or ZooKeeper) in an application that frequently experiences long Garbage Collection (GC) pauses or CPU starvation?", "If the application acquires a distributed lock with a TTL (e.g., 10 seconds) and then suffers a 15-second GC pause, the lock will expire on the server. Another instance will acquire the lock. When the original instance wakes up from the GC pause, it continues executing its critical section, completely unaware that it no longer holds the lock. This results in two instances executing the critical section simultaneously, corrupting data. Fencing tokens are required to truly solve this.", ["GC pauses can outlast the lock's TTL", "The lock auto-expires, and a second instance acquires it", "Both instances execute simultaneously, destroying mutual exclusion"], ["GC pauses delete Redis data"]),
    ("A2", "architecture", "hard", "architecture", ["Distributed Systems"], "How does a 'Fencing Token' solve the problem of GC pauses or network delays breaking distributed locks?", "A Fencing Token is a monotonically increasing integer generated by the lock service every time a lock is granted. When the client attempts to write to the underlying storage (e.g., a database or object store), it includes this token. The storage system is configured to reject any write containing a token *older* than the highest token it has already seen. If a delayed client wakes up and tries to write with token 3, but the storage has already accepted a write from a newer lock owner with token 4, the delayed client's write is rejected.", ["Fencing token is a strictly increasing integer granted with the lock", "The storage system validates the token on every write operation", "Storage rejects writes with older tokens, preventing delayed clients from corrupting data"], ["It puts a fence around the server"]),
    ("A2", "scenario", "medium", "scenario", ["Concurrency"], "You need to prevent users from rapidly double-clicking a 'Submit Payment' button and generating two concurrent identical requests. While the frontend should disable the button, how must the backend definitively prevent the double-charge?", "The backend must use an Idempotency Key. The frontend generates a unique UUID (or the backend uses a deterministic hash of the payload) and passes it in a header (e.g., `Idempotency-Key`). The backend attempts to write this key to a fast distributed cache (like Redis) or database with a Unique Constraint. If the key already exists (or the `SET NX` fails), the backend instantly recognizes the duplicate request, aborts processing, and returns the cached response of the original request.", ["Use an Idempotency Key passed by the client", "Backend enforces uniqueness via a distributed cache (SET NX) or DB Unique Constraint", "Duplicate requests are aborted before processing business logic"], ["Use a 5-second sleep in the API"]),
    ("A2", "explain", "easy", "explain", ["Concurrency"], "In a relational database, what does the `FOR UPDATE` clause do at the end of a `SELECT` statement?", "The `FOR UPDATE` clause implements pessimistic row-level locking. It tells the database to explicitly lock the rows returned by the `SELECT` query as if they were being updated. Any other transaction attempting to `SELECT FOR UPDATE`, `UPDATE`, or `DELETE` those exact same rows will be blocked and must wait until the current transaction either commits or rolls back.", ["Implements pessimistic row-level locking", "Locks the returned rows from being modified by other transactions", "Other transactions wait until the lock is released (commit/rollback)"], ["It updates the table automatically"]),

    # Area 3: Transactional Messaging (Saga & Outbox Pattern)
    ("A3", "concept", "medium", "concept", ["Architecture"], "What is the 'Dual Write Problem' in microservices, and why is it dangerous?", "The Dual Write problem occurs when a microservice attempts to update its local database and explicitly publish a message to an external message broker (like Kafka/RabbitMQ) in the same logical flow. Because these are two separate distributed systems, they cannot share a single ACID transaction. If the database commits but the network call to the broker fails, the systems are left in a permanently inconsistent state (data updated, but downstream services never notified).", ["Updating a database and publishing to a broker simultaneously", "Cannot wrap two distributed systems in a single ACID transaction", "Network failures lead to permanent data inconsistency"], ["Writing to two database tables at once"]),
    ("A3", "architecture", "hard", "architecture", ["Architecture"], "Detail how the 'Transactional Outbox' pattern solves the Dual Write problem.", "Instead of publishing directly to the message broker, the microservice writes the business entity AND an event payload into a dedicated 'Outbox' table within the exact same relational database. Because they are in the same database, this is a single, atomic ACID transaction. A separate, independent background process (the Message Relay or Debezium CDC) continuously polls or tails the Outbox table, publishes the events to the message broker reliably (with at-least-once delivery semantics), and then marks them as processed.", ["Writes business data and an event record to an Outbox table in the same DB", "Uses a single atomic local ACID transaction", "A separate background worker/CDC reliably forwards the Outbox events to the broker"], ["It places messages in an inbox"]),
    ("A3", "tradeoff", "medium", "tradeoff", ["Architecture"], "When implementing the Transactional Outbox pattern, what is the tradeoff between a 'Polling Publisher' and a 'Transaction Log Tailing (CDC)' publisher?", "A Polling Publisher executes a SQL `SELECT` every few seconds to find new Outbox records; it is easy to implement but adds continuous load to the database and introduces polling latency. Transaction Log Tailing (Change Data Capture / CDC, e.g., Debezium) hooks directly into the database's internal replication log (e.g., Postgres WAL). CDC has near-zero latency and minimal database overhead, but requires complex infrastructure and strict operational management of the replication slots.", ["Polling: Easy to build, but adds DB load and polling latency", "CDC: Near-zero latency and low DB overhead by reading replication logs", "CDC tradeoff: High operational complexity and infrastructure overhead (Debezium)"], ["Polling requires a mouse, CDC requires a keyboard"]),
    ("A3", "concept", "medium", "concept", ["Architecture"], "In the context of distributed transactions, what is a Saga?", "A Saga is a sequence of local database transactions across multiple independent microservices, coordinated via asynchronous messages or events. Because there is no global distributed lock (like Two-Phase Commit), if any step in the sequence fails, the Saga must explicitly trigger 'Compensating Transactions' (undo operations) in reverse order to rollback the changes made by the previous successful microservices.", ["A sequence of local transactions across microservices", "Coordinated via asynchronous events/messages without global locks", "Requires explicitly coded Compensating Transactions to handle rollbacks"], ["A long epic story about microservices"]),
    ("A3", "compare", "hard", "compare", ["Architecture"], "Compare 'Choreography' and 'Orchestration' in Saga patterns. When should you use Orchestration?", "Choreography is decentralized: services publish domain events, and other services listen and react independently without a central controller. It is highly decoupled but difficult to track and debug complex workflows. Orchestration uses a centralized 'Saga Orchestrator' service that actively sends command messages to participant services and tracks the global state of the transaction. Orchestration should be used for complex business workflows involving many steps, conditional logic, or where tracking the exact state of the transaction is critical.", ["Choreography: Decentralized, event-driven, independent actors", "Orchestration: Centralized controller commands services and tracks state", "Use Orchestration for complex workflows requiring strict state tracking and conditional logic"], ["Orchestration uses music, Choreography uses dance"]),
    ("A3", "scenario", "hard", "scenario", ["Architecture"], "You implement a Choreography Saga. Service A creates an Order. Service B reserves Inventory. Service C charges the Payment. If the Payment fails, how exactly does the system roll back the Inventory and Order?", "When Service C (Payment) fails, it publishes a `PaymentFailed` event. Because this is choreography, Service B (Inventory) listens for `PaymentFailed`, executes a local compensating transaction to release the reserved items, and publishes an `InventoryReleased` event. Service A (Order) listens for either `PaymentFailed` or `InventoryReleased`, and executes its own compensating transaction to update the Order status to `CANCELLED`. There is no central controller telling them to do this.", ["Payment service publishes a failure event", "Inventory service listens to the failure event and releases stock", "Order service listens to the failure event and cancels the order locally"], ["A central orchestrator sends rollback commands"]),
    ("A3", "design", "medium", "design", ["Architecture"], "Why are Compensating Transactions in a Saga fundamentally different from traditional relational database rollbacks?", "A traditional database rollback (e.g., `ROLLBACK`) completely erases the uncommitted changes from the transaction log as if they never happened. A Compensating Transaction in a Saga operates on data that was *already committed* to a local database. Therefore, a compensating transaction is a brand new, explicit business operation (like 'Issue Refund' or 'Restock Item') that semantically undoes the effect of the previous operation, leaving a permanent audit trail of both the original action and the compensation.", ["Traditional rollbacks erase uncommitted data as if it never happened", "Compensating transactions operate on already-committed data", "They are explicit semantic business operations (e.g., Refund) that leave an audit trail"], ["Saga rollbacks delete the database tables"]),
    ("A3", "diagnose", "hard", "debugging", ["Architecture"], "Your Outbox Pattern implementation occasionally publishes the exact same message to Kafka twice. Developers are alarmed and trying to debug the polling worker. Why is this expected, and how must downstream services handle it?", "This is expected because the Outbox pattern guarantees 'At-Least-Once' delivery semantics, not 'Exactly-Once'. If the polling worker reads the Outbox table, publishes to Kafka successfully, but crashes *before* it updates the Outbox table to mark the message as 'processed', the worker will republish the message upon restart. Downstream services must be designed to be Idempotent, gracefully handling duplicate messages (e.g., by checking an event ID against a processed-message table) without applying the business logic twice.", ["Outbox pattern provides At-Least-Once delivery, which inherently causes duplicates on worker crashes", "Downstream services must be explicitly designed to be Idempotent", "Consumers should track processed message IDs to discard duplicates"], ["Kafka is broken and duplicating messages"]),
    ("A3", "concept", "medium", "concept", ["Architecture"], "Why is the Two-Phase Commit (2PC) protocol generally avoided in modern microservice architectures in favor of Sagas?", "Two-Phase Commit (2PC) relies on synchronous, blocking locks across multiple distributed databases and a global transaction coordinator. This causes severe performance bottlenecks, single points of failure, and availability issues (if one service is down, the entire transaction blocks indefinitely). Microservices favor Sagas because they are asynchronous, do not hold long-lived global locks, and embrace Eventual Consistency, prioritizing high availability and scalability over strict ACID consistency.", ["2PC uses synchronous, blocking global locks across all participating databases", "Causes severe performance bottlenecks and availability risks", "Sagas avoid global locks, using asynchronous events and embracing Eventual Consistency"], ["2PC requires two separate databases for every service"]),
    ("A3", "scenario", "hard", "scenario", ["Architecture"], "In a Saga Orchestrator, the orchestrator tells the Payment Service to charge a card. The Payment Service successfully charges the card, but the network drops the HTTP response before reaching the Orchestrator. What must the Orchestrator do, and what constraint does this put on the Payment Service?", "The Orchestrator will eventually time out. Because it doesn't know if the charge succeeded or failed, it must forcefully retry the command to the Payment Service. This places a strict constraint on the Payment Service: its endpoints must be strictly Idempotent. When it receives the retry command, it must recognize the transaction ID, realize the card was already charged, and simply return the successful response without charging the card a second time.", ["Orchestrator must timeout and retry the command", "Payment service must be strictly Idempotent", "Payment service detects the duplicate command ID and returns success without double-charging"], ["The Orchestrator must guess what happened"]),

    # Area 4: Service-to-Service Authentication & Zero-Trust
    ("A4", "concept", "medium", "concept", ["Security"], "What is the core philosophy of a 'Zero-Trust Network' in a microservices backend architecture?", "Zero-Trust assumes that the internal corporate network (VPC/datacenter) is inherently hostile and already compromised. Therefore, it completely discards the traditional 'castle-and-moat' perimeter defense. Every single request, even if it originates from an internal microservice on the same private subnet, must be explicitly authenticated, authorized, and encrypted before being processed. Trust is never granted based on IP address or network location.", ["Assumes the internal network is hostile and potentially compromised", "Discards perimeter-only defense (castle-and-moat)", "Every internal service-to-service request must be authenticated, authorized, and encrypted"], ["It means developers do not trust the QA team"]),
    ("A4", "architecture", "hard", "architecture", ["Security"], "Detail how Mutual TLS (mTLS) works to secure service-to-service communication inside a Kubernetes cluster.", "In standard TLS, only the server proves its identity via a certificate. In Mutual TLS (mTLS), both the client microservice and the server microservice hold cryptographic certificates issued by a trusted internal Certificate Authority (CA). During the TLS handshake, they exchange and validate each other's certificates. This mathematically guarantees the identity of both services, prevents Man-in-the-Middle (MitM) attacks, and completely encrypts the traffic on the wire, natively fulfilling Zero-Trust requirements.", ["Both client and server present and validate cryptographic certificates", "Certificates are issued by a trusted internal Certificate Authority", "Guarantees identity of both parties, prevents MitM, and encrypts traffic"], ["mTLS stands for Multi-Threaded Logging System"]),
    ("A4", "implement", "medium", "implement", ["Security"], "How is mTLS typically implemented in modern microservices without forcing developers to write complex certificate-management code in every application?", "It is implemented using a Service Mesh (like Istio or Linkerd) and the 'Sidecar Pattern'. A lightweight proxy (like Envoy) is deployed alongside every microservice container. The application sends unencrypted HTTP traffic to `localhost`. The Sidecar intercepts it, handles the complex mTLS handshake and encryption, routes it to the destination's Sidecar, which decrypts it and forwards it to the destination app. The certificates are automatically rotated by the Service Mesh control plane.", ["Uses a Service Mesh (Istio/Linkerd) and the Sidecar proxy pattern", "Sidecars intercept local traffic and transparently handle mTLS encryption/decryption", "Abstracts all certificate management and rotation away from the application code"], ["Developers must write manual OpenSSL commands in Python"]),
    ("A4", "tradeoff", "hard", "tradeoff", ["Security"], "When implementing service-to-service authorization, what is the tradeoff between using embedded JWT claims versus centralized API Gateway policy checks (e.g., OPA)?", "Using embedded JWT claims (where Service A passes a signed token to Service B containing its roles) is incredibly fast and highly decentralized, but the claims can become stale if permissions change before the token expires, and revoking them is difficult. Centralized policy engines (like Open Policy Agent sidecars) check rules dynamically on every request, ensuring instant revocation and fine-grained control, but they introduce operational complexity and require maintaining distributed policy states across the cluster.", ["JWT Claims: Fast, decentralized, stateless, but prone to stale permissions and hard to revoke", "Centralized OPA: Instant revocation, fine-grained control, but operationally complex", "OPA requires distributing policy rules to sidecars across the cluster"], ["JWTs are written in XML, OPA is written in JSON"]),
    ("A4", "scenario", "medium", "scenario", ["Security"], "Your backend has a private internal 'Admin Service' that deletes users. A developer accidentally exposes it to the public internet by misconfiguring the API Gateway. How does a Zero-Trust architecture prevent attackers from exploiting this?", "In a Zero-Trust architecture, the Admin Service does not trust requests just because they reached it. It mandates explicit cryptographic authentication (e.g., requiring an internal mTLS client certificate or a strictly validated service-to-service JWT) for every request. Since the external attacker coming through the internet lacks the internal cryptographic credentials, the Admin Service outright rejects the request with a `401 Unauthorized` or `403 Forbidden`, neutralizing the misconfiguration.", ["Zero-Trust mandates explicit cryptographic authentication for every request", "External attackers lack the required internal mTLS certs or service JWTs", "The service rejects the unauthenticated traffic, despite the network exposure"], ["The service asks the user nicely if they are an admin"]),
    ("A4", "concept", "medium", "concept", ["Security"], "What is the 'Confused Deputy' problem in microservices authentication, and how do you mitigate it?", "The Confused Deputy problem occurs when an external user tricks a highly-privileged internal service (the deputy) into accessing a restricted resource on their behalf, because the backend service uses its own high-level permissions instead of the user's permissions. To mitigate this, services must implement 'Token Exchange' or 'Context Propagation'. The backend service must pass the original user's identity (e.g., forwarding the user's JWT) downstream, so the ultimate resource validates the *user's* permissions, not just the calling service's permissions.", ["User tricks a highly privileged internal service into accessing restricted resources", "Occurs when services use their own permissions instead of the user's", "Mitigated by Token Exchange / Context Propagation (forwarding user identity downstream)"], ["The deputy gets lost in the network"]),
    ("A4", "architecture", "hard", "architecture", ["Security"], "How do you securely distribute and rotate API keys between internal microservices if you are not using a Service Mesh with mTLS?", "You must use a dedicated Secrets Management system (like HashiCorp Vault or AWS Secrets Manager). Microservices authenticate with the Vault using their platform identity (e.g., AWS IAM roles or Kubernetes Service Accounts). The Vault dynamically generates short-lived, lease-based API keys or database credentials and injects them into the service's memory. When the lease expires, the Vault automatically rotates the keys, ensuring compromised keys have a very short lifespan.", ["Use a Secrets Management system (HashiCorp Vault / AWS Secrets Manager)", "Authenticate via platform identity (IAM / K8s Service Accounts)", "Vault dynamically generates short-lived, lease-based credentials and rotates them automatically"], ["Store the keys in a text file on a shared network drive"]),
    ("A4", "diagnose", "medium", "debugging", ["Security"], "You implement JWTs for service-to-service communication. Suddenly, inter-service API calls start failing intermittently with `TokenExpiredError`. The tokens have a 5-minute lifespan, and services generate them on the fly. What infrastructure configuration issue is causing this?", "This is highly symptomatic of Clock Skew (NTP sync drift) across the servers or containers in the cluster. If Server A generates a token that is valid for 5 minutes, but Server B's system clock is running 5 minutes fast, Server B will instantly reject the brand-new token as 'expired'. The solution is to ensure strict NTP synchronization across the cluster, or allow a small 'leeway' (e.g., 30 seconds) in the JWT validation logic.", ["Clock Skew (NTP sync drift) between the generating and validating servers", "The validating server's clock is ahead, seeing the new token as expired", "Fix by enforcing strict NTP sync and adding a validation leeway window"], ["The servers are in different time zones"]),
    ("A4", "explain", "easy", "explain", ["Security"], "In OAuth2 and OpenID Connect (OIDC), what is the difference between an Identity Provider (IdP) and a Service Provider (SP)?", "The Identity Provider (IdP) is the centralized authority that holds user credentials, authenticates the user, and issues secure tokens (e.g., Okta, Auth0, Google). The Service Provider (SP) is your application or API that relies on the IdP to verify who the user is. The SP trusts the IdP's tokens to grant access to its own resources.", ["IdP authenticates users and issues tokens (e.g., Okta, Auth0)", "SP is the application that relies on the IdP's tokens for access control", "SP trusts the IdP"], ["The IdP provides internet, the SP provides software"]),
    ("A4", "tradeoff", "hard", "tradeoff", ["Security"], "When restricting service-to-service communication, what is the tradeoff between Network-level Firewalls (IP/Subnet rules) and Application-level Identity (mTLS/JWT)?", "Network-level firewalls rely on static IP addresses, which completely break down in modern, dynamic containerized environments (Kubernetes) where IPs change constantly; however, they process at the kernel/hardware level, making them blisteringly fast and immune to application bugs. Application-level identity (mTLS) is tied to cryptographic workload identity regardless of IP, making it perfect for dynamic orchestration, but it introduces heavy CPU overhead for encryption/decryption and complex certificate management.", ["Network firewalls are fast but rely on static IPs (breaks in Kubernetes)", "Application identity (mTLS) relies on cryptographic identity, adapting to dynamic IPs", "mTLS adds CPU overhead for encryption and complex certificate management"], ["Firewalls block fire, mTLS blocks water"]),

    # Area 5: Backpressure & Load Shedding
    ("A5", "concept", "medium", "concept", ["Reliability"], "What is 'Backpressure' in backend systems, and why is it essential for reliability?", "Backpressure is a feedback mechanism where an overloaded downstream system signals to upstream systems that it cannot process data as fast as it is arriving. Instead of indiscriminately accepting traffic until it crashes from Out-Of-Memory (OOM) or CPU exhaustion, the downstream system exerts 'pressure' backwards—forcing the upstream systems to slow down, buffer, or drop traffic. It prevents cascading failures across the architecture.", ["Feedback mechanism from overloaded downstream to upstream", "Forces upstream to slow down, buffer, or drop requests", "Prevents resource exhaustion (OOM) and cascading failures"], ["It is the pressure in the server room cooling system"]),
    ("A5", "architecture", "hard", "architecture", ["Reliability"], "Compare 'Load Shedding' to 'Rate Limiting'. When would an API Gateway use Load Shedding?", "Rate Limiting restricts traffic based on business rules for a specific client (e.g., User A gets 100 requests/sec) to ensure fair usage. Load Shedding is a global, emergency survival mechanism based on internal server health (e.g., CPU is at 95%, or worker queues are full). In Load Shedding, the API Gateway indiscriminately drops incoming requests (returning `503 Service Unavailable`), regardless of the user's quota, simply to keep the database and servers from catastrophically crashing under massive unexpected load.", ["Rate Limiting applies business-rule quotas per client for fairness", "Load Shedding is a global emergency mechanism based on server health (CPU/queues)", "Load Shedding indiscriminately drops traffic (503) to prevent catastrophic crashes"], ["Load shedding is moving servers to a shed"]),
    ("A5", "implement", "medium", "implement", ["Reliability"], "How do asynchronous Message Queues (like RabbitMQ or SQS) naturally provide backpressure for worker services?", "Message queues act as elastic shock absorbers. If an upstream API receives a massive spike of 10,000 requests per second, it quickly writes them to the queue and returns success. The downstream worker services only pull messages from the queue at the exact speed they can safely process them (e.g., 500 per second). The queue absorbs the spike (buffering the backlog), ensuring the workers are never overwhelmed or crashed by the sudden burst.", ["Queues act as an elastic buffer/shock absorber", "Workers explicitly pull messages only as fast as they can handle", "Prevents the upstream spike from directly overwhelming the downstream workers"], ["They automatically delete messages if too fast"]),
    ("A5", "scenario", "hard", "scenario", ["Reliability"], "You implement a bounded in-memory queue to handle spikes. When the queue is full, it immediately rejects new requests (Load Shedding). However, during a 10-minute spike, legitimate users are constantly rejected, while stale, 9-minute-old requests are finally processed but the users have already left. How do you optimize the queue to fix this?", "You should change the queue strategy to LIFO (Last-In-First-Out) or implement aggressive TTL (Time-To-Live) on queue items (Active Queue Management / CoDel). In a heavy overload scenario, processing old requests is a waste of CPU because the HTTP client has likely already timed out. By prioritizing fresh requests (LIFO) or instantly dropping requests that have sat in the queue longer than the client timeout, you ensure the server uses its limited CPU to serve users who are still actually waiting.", ["Processing old requests is wasted CPU because clients have already timed out", "Implement aggressive TTL (Time-To-Live) to drop stale queue items", "Or use LIFO (Last-In-First-Out) during overload to serve fresh requests"], ["Increase the queue size to infinity"]),
    ("A5", "diagnose", "medium", "debugging", ["Reliability"], "A microservice uses a synchronous HTTP client to call a downstream reporting service. The reporting service slows down from 50ms to 5000ms. Suddenly, the upstream microservice completely crashes due to Thread Pool Exhaustion. Why did this happen, and how do you prevent it?", "Because the downstream service slowed down, the upstream service's HTTP requests blocked waiting for a response. New incoming requests continued to consume available worker threads until the entire pool was exhausted, preventing the service from handling even basic health checks. To prevent this, you must implement strict, short HTTP Timeouts and the Circuit Breaker pattern to fail fast when the downstream service degrades, immediately releasing the threads.", ["Slow downstream service blocked upstream HTTP client threads", "Incoming requests consumed the entire thread pool (Exhaustion)", "Prevent via strict, short HTTP Timeouts and Circuit Breakers (fail fast)"], ["The reporting service sent a virus"]),
    ("A5", "tradeoff", "hard", "tradeoff", ["Reliability"], "When a backend API is overloaded, what is the tradeoff between dropping requests silently versus returning immediate HTTP `429` / `503` responses?", "Returning `429/503` responses is polite, allows clients to implement exponential backoff, and provides clean metrics, but generating and sending thousands of error HTTP responses actually consumes significant CPU and network bandwidth on the overloaded server, potentially worsening the crash. Dropping packets silently at the network layer (e.g., TCP reset or simply ignoring them) saves maximum server CPU during a massive DDoS or spike, but causes clients to hang until timeout, degrading UX and making debugging difficult.", ["Returning HTTP errors is polite and allows client backoff, but costs server CPU", "Silent drops save maximum server CPU during critical overload", "Silent drops cause clients to hang until timeout (poor UX)"], ["Silent drops alert the police"]),
    ("A5", "architecture", "medium", "architecture", ["Reliability"], "Explain the 'Token Bucket' algorithm used for Rate Limiting and Load Shedding.", "A bucket holds a maximum number of tokens (representing capacity). Tokens are added to the bucket at a fixed, constant rate. When a request arrives, it must take a token from the bucket to be processed. If the bucket is empty, the request is rejected or delayed. This algorithm perfectly handles 'bursty' traffic: it allows a temporary burst of requests up to the bucket's capacity, but strictly enforces the long-term average rate.", ["Bucket holds a maximum capacity of tokens", "Tokens are replenished at a constant, fixed rate", "Allows short-term bursts up to capacity, while enforcing a long-term average rate"], ["It literally drops physical tokens into a bucket"]),
    ("A5", "concept", "easy", "concept", ["Reliability"], "What does the HTTP header `Retry-After` do when returned with a `503 Service Unavailable` or `429 Too Many Requests` status code?", "The `Retry-After` header tells the client exactly how long it should wait (in seconds, or a specific HTTP date) before making another request. It is a critical mechanism for backpressure, as it forces well-behaved clients to back off, relieving the overloaded server and preventing immediate retry storms.", ["Specifies the wait time (seconds or date) before retrying", "Forces clients to back off explicitly", "Prevents retry storms on overloaded servers"], ["It tells the server to retry the database query"]),
    ("A5", "scenario", "medium", "scenario", ["Reliability"], "An API Gateway is returning `429 Too Many Requests` because the backend is overloaded. However, thousands of mobile clients are poorly coded and instantly retry the request in a tight loop with no delay, effectively DDoSing the gateway. What must clients implement to prevent this?", "Clients must implement 'Exponential Backoff with Jitter'. Exponential backoff means waiting increasingly longer periods between retries (e.g., 1s, 2s, 4s, 8s). 'Jitter' adds a random time variation to the wait period (e.g., 1.2s, 2.5s, 4.1s). Jitter is crucial because without it, thousands of clients that failed at the exact same time will exponentially retry at the exact same synchronized intervals, creating repeating, massive spikes (the 'Thundering Herd' problem).", ["Implement Exponential Backoff (increasing wait times between retries)", "Implement Jitter (adding randomness to the wait time)", "Jitter prevents synchronized retry spikes (Thundering Herd)"], ["Clients must restart their phones"]),
    ("A5", "design", "hard", "design", ["Reliability"], "You are building a high-throughput logging pipeline. The API accepts logs via HTTP and writes them to disk. During high traffic, disk I/O becomes the bottleneck and memory fills up with pending logs. How do you design the application to gracefully apply backpressure to the HTTP clients?", "You configure a bounded (fixed-size) internal memory queue or channel between the HTTP handlers and the disk writer thread. When the disk slows down, the bounded queue fills up. Once the queue hits capacity, the HTTP handler thread blocks when trying to insert the new log. This block inherently pauses reading from the TCP socket. The OS TCP buffer fills up, and the TCP protocol's native flow control (Window Size = 0) automatically applies network-level backpressure directly to the client, slowing down their transmission rate without crashing the server.", ["Use a bounded (fixed-size) internal queue", "Full queue blocks HTTP threads, filling TCP buffers", "TCP native flow control automatically applies backpressure to the client"], ["Delete the logs if the disk is slow"])
]

def format_content(r):
    return f"**Question**: {r['question']}\n\n**Ideal Answer**: {r['expected_answer']}"

def run_batch():
    # 1. Read existing questions
    with open(OUT, "r", encoding="utf-8") as f:
        existing = [json.loads(line) for line in f if line.strip()]

    print(f"Loaded {len(existing)} existing records.")
    
    # Validation of hardcoded questions
    for q in Q:
        if LEAK.search(q[5]) or LEAK.search(q[6]):
            print(f"PROMPT LEAK DETECTED in: {q[5]}")
            sys.exit(1)
            
    # 2. Deduplication via TF-IDF Cosine Similarity
    existing_texts = [ex["question"] for ex in existing]
    new_texts = [q[5] for q in Q]
    
    vec = TfidfVectorizer(stop_words="english", ngram_range=(1,2))
    all_texts = existing_texts + new_texts
    vec.fit(all_texts)
    
    existing_vecs = vec.transform(existing_texts)
    new_vecs = vec.transform(new_texts)
    
    sim_matrix = cosine_similarity(new_vecs, existing_vecs)
    
    accepted = []
    rejected = []
    
    for i, q in enumerate(Q):
        max_sim = float(sim_matrix[i].max()) if sim_matrix.shape[1] > 0 else 0
        if max_sim > 0.85:
            print(f"REJECTED (Sim: {max_sim:.2f}): {q[5][:50]}...")
            rejected.append(q)
        else:
            accepted.append(q)
            
    print(f"Accepted {len(accepted)} / {len(Q)} questions.")
    
    # 3. Append accepted to JSONL
    new_records = []
    for q in accepted:
        rec = {
            "primary_role": ROLE,
            "applicable_roles": ["Full Stack Developer", "DevOps / Cloud Engineer", "AI Engineer"],
            "primary_skill": q[4][0],
            "secondary_skills": q[4][1:] if len(q[4]) > 1 else [],
            "technology": "System Design",
            "topic": "Architecture & Patterns",
            "category": "Backend Engineering",
            "intent": q[1],
            "difficulty": q[2],
            "question_type": q[3],
            "question": q[5],
            "expected_answer": q[6],
            "evaluation_rubric": {
                "strong_indicators": q[7],
                "weak_indicators": q[8]
            },
            "id": str(uuid.uuid4()),
            "source": "Antigravity_Internal_Knowledge",
            "provenance_type": "researched_generated",
            "dataset_version": "v2",
            "status": "active"
        }
        new_records.append(rec)
        
    with open(OUT, "a", encoding="utf-8") as f:
        for r in new_records:
            f.write(json.dumps(r) + "\n")
            
    # 4. Audit
    with open(OUT, "r", encoding="utf-8") as f:
        final_existing = [json.loads(line) for line in f if line.strip()]
        
    role_counts = Counter(r["primary_role"] for r in final_existing)
    
    print("\n========================================")
    print("POST-BATCH AUDIT")
    print("========================================")
    print(f"Batch: 51")
    print(f"Target role: {ROLE}")
    print(f"Attempted: {len(Q)}")
    print(f"Accepted: {len(accepted)}")
    print(f"Rejected: {len(rejected)}")
    print(f"Replacement candidates: 0")
    print(f"Cumulative NEW total: {len(final_existing)}")
    print(f"Backend total: {role_counts[ROLE]}")
    print("All role totals:")
    for role, count in role_counts.items():
        print(f"  {role}: {count}")
    print(f"Duplicate count: {len(rejected)}")
    print(f"Leakage count: 0")
    print(f"Validation failures: 0")
    
    # Hashes
    sha256 = hashlib.sha256()
    with open(OUT, 'rb') as f:
        while chunk := f.read(8192):
            sha256.update(chunk)
            
    print(f"\nFinal SHA256: {sha256.hexdigest()}")

if __name__ == "__main__":
    run_batch()
