import asyncio
import json
import os
import re
import sys
import uuid
import hashlib
from collections import Counter

from dotenv import load_dotenv
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
load_dotenv()

BACKEND_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_DIR = os.path.join(BACKEND_DIR, "data")
OUT = os.path.join(DATA_DIR, "interview_question_bank_v2_generated.jsonl")

ROLE = "AI Engineer"
LEAK = re.compile(r"(generate a question|generate \d+ questions|return only json|phase 4c gap plan|"
                  r"generation batch|candidate generation|system prompts|do not proceed|"
                  r"awaiting authorization|minimum target|generation pipeline|"
                  r"batch \d+ generation|expected answer|strong indicator|weak indicator|as an ai|"
                  r"here is the question|\bprompt text\b)", re.I)

Q = [
    # Area 1: LLM Inference Optimization (KV Cache, PagedAttention, Speculative Decoding)
    ("B58_1", "concept", "hard", "concept", ["Inference Optimization"], "Explain the concept of 'PagedAttention' in vLLM and how it solves memory fragmentation during LLM inference.", "Standard LLM inference allocates contiguous memory blocks for the KV Cache for the maximum possible sequence length, leading to severe internal fragmentation (wasting up to 60-80% of GPU VRAM). PagedAttention borrows the concept of virtual memory and paging from OS design. It divides the KV Cache into small, fixed-size blocks ('pages') of tokens. These blocks are allocated dynamically and non-contiguously in physical VRAM. This eliminates internal fragmentation, allowing the server to batch vastly more concurrent requests and drastically increasing inference throughput.", ["Allocates contiguous memory for maximum sequence length, wasting VRAM (fragmentation)", "PagedAttention divides KV Cache into small, non-contiguous fixed-size blocks (pages)", "Eliminates fragmentation, massively increasing batch size and throughput"], ["PagedAttention relies on SSD paging to save VRAM"]),
    ("B58_1", "diagnose", "medium", "debugging", ["Inference Optimization"], "You deploy an open-source 70B model using continuous batching. CPU utilization is low, but GPU utilization is stuck at 40% and latency is high. You realize your requests have massive system prompts (10,000 tokens) but only generate 5 tokens of output. Why is GPU utilization low, and how do you fix it?", "You are entirely bound by the 'Prefill' phase (Time to First Token), which is highly compute-intensive but memory-bandwidth bound when processing massive prompts. Because the generated output is tiny (5 tokens), the 'Decode' phase (which benefits from batching) is non-existent. To fix this, you must implement 'Prompt Caching' (or KV Cache sharing). Since all requests use the exact same 10,000-token system prompt, you can precompute its KV states once, keep them in VRAM, and instantly skip the prefill phase for all subsequent requests.", ["Bound by the Prefill phase (processing massive input prompts) rather than Decode", "The identical system prompt forces redundant, massive compute on every request", "Fix by enabling Prompt Caching (sharing the KV cache for the common prefix)"], ["The GPU is broken; buy an Nvidia H100"]),
    ("B58_1", "architecture", "hard", "architecture", ["Inference Optimization"], "How does 'Speculative Decoding' reduce inference latency without degrading model quality?", "In standard autoregressive decoding, generating each token requires a full forward pass of the massive model (heavily memory-bandwidth bound). Speculative Decoding uses a tiny, fast 'draft' model to quickly generate a sequence of *N* candidate tokens. The massive 'target' model then evaluates all *N* tokens in a single, batched forward pass. It accepts the sequence up to the first token it disagrees with, generates the correction, and discards the rest. Because verifying *N* tokens in parallel takes roughly the same time as generating 1 token, this mathematically guarantees identical output quality while drastically reducing latency.", ["Uses a tiny, fast 'draft' model to predict multiple tokens quickly", "The massive 'target' model verifies all draft tokens in a single parallel forward pass", "Guarantees identical output quality while accelerating speed (skipping sequential passes)"], ["It guesses the answer before the user finishes typing"]),
    ("B58_1", "tradeoff", "medium", "tradeoff", ["Inference Optimization"], "What is the tradeoff of using AWQ (Activation-aware Weight Quantization) over standard 4-bit block-wise quantization (like GPTQ) for LLM deployment?", "Standard quantization uniformly compresses all weights, which can destroy the model's accuracy because certain 'salient' weights are mathematically critical to the activation outputs. AWQ observes the activation patterns of the model during a calibration phase to identify this tiny percentage (e.g., 1%) of salient weights. It keeps these critical weights at higher precision (or scales them) while crushing the rest to 4-bit. The tradeoff is that AWQ requires a representative calibration dataset and is computationally slower to *quantize*, but provides significantly higher accuracy at the same VRAM footprint.", ["AWQ preserves 'salient' weights that are critical to activations", "Provides much higher accuracy than uniform quantization at the same VRAM footprint", "Tradeoff: Requires a calibration dataset and is slower/more complex to perform the initial quantization"], ["AWQ requires 8 GPUs to run"]),
    ("B58_1", "scenario", "hard", "scenario", ["Inference Optimization"], "You are serving a model that answers questions based on a user's uploaded 100-page PDF. A single user asks 20 consecutive questions about the same PDF. Without optimizing the inference server, what severe inefficiency occurs, and what architectural pattern solves this?", "Without optimization, the inference server must re-process the entire 100-page PDF (the Prefill phase) for every single follow-up question, wasting massive compute, creating massive latency (Time to First Token), and exploding API costs. To solve this, you must use an inference engine that supports 'Prefix Caching' or 'KV Cache retention' (like RadixAttention in SGLang). The system retains the KV cache of the PDF in VRAM. When the user asks the second question, the server simply appends the new question tokens to the existing KV cache, reducing prefill time to near-zero.", ["Redundant Prefill phase: re-encoding the entire PDF on every turn", "Causes extreme latency, compute waste, and high cost", "Solve using Prefix Caching (retaining the KV cache of the document between requests)"], ["The LLM will forget the PDF after the first question"]),
    ("B58_1", "explain", "medium", "explain", ["Inference Optimization"], "What is the difference between 'Time to First Token' (TTFT) and 'Time per Output Token' (TPOT), and which hardware bottleneck primarily drives each?", "TTFT is the latency to process the input prompt (the Prefill phase). It requires massive matrix multiplications and is primarily bound by raw GPU Compute (TFLOPS). TPOT is the latency to generate each subsequent token (the Decode phase). Autoregressive decoding requires loading the entire model weights and KV cache from VRAM into the GPU cores for *every single token*. Therefore, TPOT is almost entirely bottlenecked by Memory Bandwidth (VRAM speed), not compute.", ["TTFT (Prefill): Processing the prompt; bound by raw Compute (TFLOPS)", "TPOT (Decode): Generating subsequent tokens; bound by Memory Bandwidth", "Autoregressive generation must load weights/cache for every token, stressing memory speed"], ["TTFT is network latency, TPOT is database latency"]),
    ("B58_1", "implement", "hard", "implement", ["Inference Optimization"], "How do you implement 'Continuous Batching' (or iteration-level scheduling) to optimize an LLM inference server compared to static batching?", "In static batching, if you batch 4 requests together, the GPU must wait for the longest request (e.g., 500 tokens) to finish before it can return the batch and accept new requests, wasting GPU cycles on the shorter requests (e.g., 10 tokens) that finished early. Continuous Batching evaluates the batch at the *iteration (token) level*. The exact millisecond the 10-token request finishes, it is evicted from the batch, and a new pending request is instantly slotted into its place. This keeps the GPU perfectly saturated, increasing throughput by up to 20x.", ["Static batching forces the GPU to wait for the longest request to finish", "Continuous Batching evicts requests the moment they finish (token-level scheduling)", "Instantly slots new requests into the freed capacity, keeping GPU saturated"], ["You batch the requests continuously in a `while True` loop"]),
    ("B58_1", "concept", "easy", "concept", ["Inference Optimization"], "What does 'Quantization' mean in the context of Large Language Models?", "Quantization is the process of reducing the precision of the numerical weights in a model (e.g., converting them from 16-bit floats to 8-bit or 4-bit integers). This drastically reduces the memory (VRAM) required to load the model and increases inference speed (Memory Bandwidth), at the cost of a slight degradation in model accuracy and reasoning capability.", ["Reducing the precision of model weights (e.g., FP16 to INT4)", "Drastically reduces VRAM requirements and increases memory bandwidth/speed", "Tradeoff is a slight loss in reasoning quality/accuracy"], ["It means counting the number of tokens in a prompt"]),
    ("B58_1", "diagnose", "hard", "debugging", ["Inference Optimization"], "An open-source LLM deployed on a single A100 (80GB VRAM) keeps crashing with an 'Out Of Memory' (OOM) error. The model weights are 4-bit quantized and only consume 35GB of VRAM. There is 45GB of free VRAM. Why does it OOM when 10 users send 8,000-token contexts concurrently?", "The crash is caused by the KV Cache exploding. During inference, the model must store the Key and Value tensors for every single token in the context across all attention heads and layers. For a 70B model, a single 8,000-token context can easily consume 2-4GB of VRAM just for the KV cache. Ten concurrent users require 20-40GB of KV Cache memory. When combined with the 35GB model weights, this instantly exceeds the 80GB limit. You must strictly limit the maximum concurrent batch size or use techniques like PagedAttention to manage this.", ["The KV Cache scales linearly with sequence length and batch size", "Storing Key/Value tensors for 8k tokens across 10 users consumes massive VRAM (e.g., 30GB+)", "The combination of Model Weights + KV Cache exceeds the physical 80GB limit"], ["The A100 GPU cannot handle 4-bit quantization"]),
    ("B58_1", "tradeoff", "medium", "tradeoff", ["Inference Optimization"], "What is the tradeoff of using 'FlashAttention' instead of standard scaled dot-product attention?", "Standard attention materializes the massive $N \times N$ attention matrix in HBM (High Bandwidth Memory/VRAM), which requires incredibly slow, repeated read/write operations (memory wall) and causes $O(N^2)$ memory explosion for long contexts. FlashAttention completely avoids materializing the full matrix by computing attention in blocks (tiling) and keeping it in the ultra-fast SRAM (on-chip memory). The tradeoff? There is virtually no tradeoff. It is mathematically exact, vastly faster, and uses far less memory. The only 'tradeoff' is hardware compatibility, as it requires modern GPUs (Ampere architecture or newer) and specific CUDA kernels.", ["Standard attention materializes $N \times N$ matrices in slow VRAM (O(N^2) memory bottleneck)", "FlashAttention uses tiling to compute strictly in ultra-fast SRAM", "No mathematical tradeoff (it is exact); only requires modern GPU architectures"], ["FlashAttention makes the model hallucinate more"]),

    # Area 2: Advanced Retrieval & Indexing (RAG Architecture)
    ("B58_2", "concept", "medium", "concept", ["RAG Architecture"], "What is 'Graph RAG', and how does it solve limitations in standard vector-based RAG?", "Standard vector RAG (dense retrieval) excels at finding text semantically similar to a query. However, it fails terribly at 'multi-hop' reasoning (e.g., 'Who is the CEO of the company that acquired the startup founded by John?'). Graph RAG extracts entities and relationships from the text during ingestion and builds a Knowledge Graph (nodes and edges). During retrieval, it traverses the graph to connect disparate pieces of information across multiple documents, providing the LLM with structured, multi-hop context that semantic search would miss.", ["Standard RAG (Semantic Search) fails at multi-hop, cross-document reasoning", "Graph RAG extracts entities/relationships to build a Knowledge Graph", "Allows traversal of edges to connect disparate facts for complex queries"], ["Graph RAG uses matplotlib to draw charts for the LLM"]),
    ("B58_2", "diagnose", "hard", "debugging", ["RAG Architecture"], "You implement a RAG system over medical literature using purely Dense Vector embeddings. It works great for 'What are symptoms of diabetes?' but completely fails for 'What is the dosage for Aspirin 500mg?' (it returns documents about Ibuprofen 200mg). Why did Dense Retrieval fail?", "Dense vector models are trained to capture broad semantic meaning. 'Aspirin 500mg' and 'Ibuprofen 200mg' are semantically nearly identical (both are NSAID painkillers with a dosage). Dense embeddings map them to the exact same area in vector space. To fix this, you must implement 'Hybrid Search' (Dense + Sparse). Sparse retrieval (like BM25) performs exact keyword matching (TF-IDF). BM25 ensures that the exact string 'Aspirin 500mg' is heavily weighted, returning the exact drug dosage, while Dense handles the conceptual matching.", ["Dense vectors capture semantics; 'Aspirin' and 'Ibuprofen' mean the same thing conceptually", "Dense retrieval ignores exact keyword precision (like specific dosages or names)", "Must use Hybrid Search (Dense + BM25) to combine semantic meaning with exact keyword matching"], ["The LLM hallucinated the dosage"]),
    ("B58_2", "implement", "hard", "implement", ["RAG Architecture"], "How do you implement a 'Cross-Encoder Reranker' in a RAG pipeline, and why don't you just use it for the initial search?", "You first use a Bi-Encoder (standard vector embedding model) to retrieve the top 100 documents from a database of millions. This is fast because vectors are pre-computed and indexed (e.g., HNSW). You then pass the user's query AND the text of those 100 documents into a Cross-Encoder. The Cross-Encoder processes the query and document simultaneously through the transformer attention layers, yielding a highly accurate relevance score. You cannot use it for the initial search because processing the query against 1,000,000 documents dynamically would take hours/days (O(N) inference cost).", ["Bi-Encoders (Vectors) are fast and pre-computable; used for Phase 1 retrieval (Top 100)", "Cross-Encoders process Query + Document together via attention layers for massive accuracy", "Cannot be used for Phase 1 because dynamic O(N) transformer inference on millions of docs is impossible"], ["Cross-Encoders encrypt the data for security"]),
    ("B58_2", "scenario", "medium", "scenario", ["RAG Architecture"], "A user queries your internal RAG system: 'Show me the Q3 financial report.' Your vector database contains the Q1, Q2, Q3, and Q4 reports. They are all semantically identical ('financial report'). How do you ensure the system strictly retrieves the Q3 report?", "You cannot rely on vector similarity because the documents are semantically indistinguishable. You must implement 'Self-Querying' or 'Metadata Extraction' routing. You pass the user's query to a fast LLM (or use a router) to extract a structured filter: `{\"quarter\": \"Q3\"}`. You then execute a vector search with a strict deterministic metadata filter (`WHERE quarter = 'Q3'`). This guarantees the vector database only searches within the subset of documents tagged with Q3.", ["Semantic search cannot differentiate highly similar structured documents", "Use an LLM to extract structured metadata (e.g., `quarter: Q3`) from the user query", "Apply a strict deterministic metadata filter (pre-filtering) on the vector database"], ["Just embed the number 3 really strongly"]),
    ("B58_2", "tradeoff", "medium", "tradeoff", ["RAG Architecture"], "What is the tradeoff of using 'Small-to-Big' (or Parent-Child) chunking versus standard fixed-size chunking?", "Standard chunking (e.g., 1000 tokens) risks burying the specific answer in a sea of irrelevant text, lowering retrieval accuracy, or splitting a thought in half. 'Small-to-Big' embeds tiny, highly specific chunks (e.g., 100 tokens, the 'Child') for the vector search. Because they are tiny, retrieval is highly accurate. However, passing a tiny 100-token chunk to the LLM provides no context. Therefore, when the Child is retrieved, the system fetches the larger 'Parent' document (e.g., the full page) to send to the LLM. The tradeoff is vastly higher complexity in managing the ID mappings and storage.", ["Embed tiny 'Child' chunks for highly precise vector retrieval", "Send the larger 'Parent' document to the LLM for necessary context", "Tradeoff: Vastly more complex data engineering to maintain Child-Parent ID mappings"], ["Small-to-big compresses the text into emojis"]),
    ("B58_2", "explain", "hard", "explain", ["RAG Architecture"], "Explain the concept of 'Contextual Compression' (or Prompt Compression) in an advanced RAG pipeline.", "After retrieving the top 10 documents, you might have 10,000 tokens of context. Passing all 10,000 tokens to the generation LLM introduces extreme latency, high cost, and the 'Lost in the Middle' problem (LLMs ignore information in the middle of massive prompts). Contextual Compression uses a small, fast LLM to read the retrieved documents and extract *only* the sentences directly relevant to the user's query, throwing away the irrelevant fluff. It compresses 10,000 tokens down to 500 highly dense tokens before sending it to the heavy generation model.", ["Retrieving large documents includes massive amounts of irrelevant 'fluff'", "Uses a fast, cheap LLM to extract only the sentences relevant to the query", "Solves high latency, cost, and the 'Lost in the Middle' attention degradation problem"], ["It converts the text to a ZIP file before sending to OpenAI"]),
    ("B58_2", "architecture", "hard", "architecture", ["RAG Architecture"], "How does 'Multi-Query' (Query Expansion) improve RAG recall, and what is its main drawback?", "Users often write terrible, vague queries (e.g., 'GCP instances'). A Multi-Query architecture uses an LLM to rewrite the user's query into 3-5 different variations (e.g., 'Google Cloud compute engine pricing', 'How to provision VMs on GCP'). It runs vector searches for all 5 queries, aggregates the results, deduplicates them, and sends the combined context to the generation model. This dramatically improves Recall by overcoming vocabulary mismatches. The main drawback is latency (an extra LLM call) and increasing the number of database queries by 5x.", ["Uses an LLM to rewrite the user query into multiple variations", "Runs separate vector searches for all variations and aggregates the results", "Improves recall (overcoming vocabulary mismatch), but adds latency and DB load"], ["It asks the user the same question 5 times"]),
    ("B58_2", "concept", "easy", "concept", ["RAG Architecture"], "In RAG, what is the 'Lost in the Middle' phenomenon?", "Recent academic studies show that Large Language Models exhibit a 'U-shaped' performance curve regarding context. They perfectly recall information placed at the very beginning of the prompt (Primacy effect) and information at the very end of the prompt (Recency effect). However, if the critical information is buried in the middle of a massive 20,000-token context window, the model's ability to retrieve it degrades significantly. Therefore, RAG systems must rerank retrieved documents to place the most relevant chunks at the extreme ends of the prompt.", ["LLMs easily recall information at the very beginning and very end of a prompt", "They severely struggle to recall facts buried in the middle of massive contexts", "RAG systems must intelligently order retrieved chunks (putting best chunks at the edges)"], ["It means the LLM gets confused halfway through generating the answer"]),
    ("B58_2", "diagnose", "medium", "debugging", ["RAG Architecture"], "Your RAG system is hallucinating answers about recent company policies. You inspect the prompt and see that the correct policy document *is* being injected. Why is the LLM ignoring the injected context and hallucinating?", "This is 'Parametric Memory Override' (or Prior Knowledge Conflict). The LLM was heavily trained on data from 2022. When asked a question, its internal weights (parametric memory) strongly 'believe' the 2022 policy is correct. Even when you inject the 2024 policy via RAG, the model trusts its internal weights over the injected text. To fix this, you must strictly ground the system prompt (e.g., 'You must answer STRICTLY using the provided context. If the context contradicts your knowledge, trust the context.').", ["Parametric Memory Override / Prior Knowledge Conflict", "The model trusts its pre-trained internal weights over the injected RAG context", "Fix by enforcing strict grounding instructions in the system prompt"], ["The LLM cannot read PDF files"]),
    ("B58_2", "tradeoff", "medium", "tradeoff", ["RAG Architecture"], "What is the tradeoff of using a 1536-dimension embedding model (like OpenAI Ada) versus a heavily quantized 384-dimension model (like MiniLM) for a vector database?", "A 1536-dimension model captures extremely subtle semantic nuances, providing higher accuracy for complex, highly technical documents. The tradeoff is massive infrastructure cost. 1536 dimensions require 4x more RAM/Disk to store in a vector database, and distance calculations (Cosine Similarity) take significantly longer. A 384-dimension model is vastly cheaper, faster, and perfectly adequate for simple Q&A or FAQ retrieval, but may fail on nuanced, domain-specific semantic differences.", ["High dimensionality (1536) captures deeper semantic nuance and accuracy", "Tradeoff: Requires 4x more RAM/Disk to store and index in the Vector DB", "Tradeoff: Cosine similarity calculations are much slower compared to smaller models"], ["1536 dimensions allow the AI to travel through time"]),

    # Area 3: AI Agent Architecture (ReAct, State Machines, LangGraph)
    ("B58_3", "concept", "medium", "concept", ["AI Agents"], "What is the 'ReAct' (Reasoning and Acting) prompting pattern for AI Agents?", "ReAct is a fundamental agent architecture that forces the LLM to interleave 'Thought' (Reasoning) and 'Action' (Tool execution). Instead of blindly guessing an answer, the model is prompted to output a specific format: Thought (I need to find the user's order), Action (Call `get_order(id=123)`), Observation (Order is shipped). It repeats this Thought-Action-Observation loop until it has enough context to formulate the final answer. This dramatically reduces hallucinations and improves multi-step problem solving.", ["Interleaves 'Thought' (reasoning) with 'Action' (tool execution)", "Forces the model to output a Thought, call an Action, and evaluate the Observation", "Reduces hallucination by anchoring logic strictly to real-world tool observations"], ["It is a React.js library for building LLM UIs"]),
    ("B58_3", "diagnose", "hard", "debugging", ["AI Agents"], "You build an autonomous agent using LangChain to research a topic, browse the web, and write a summary. After 15 minutes, the agent crashes with a `Maximum Context Length Exceeded` error (e.g., 128k tokens). Why did this happen?", "This is an 'Infinite Loop' coupled with a 'Context Window Explosion'. The agent likely hit a roadblock (e.g., a website blocked it) and kept retrying the same tool call. Because standard agent frameworks append *every single* Thought, Action, and Observation (including massive HTML dumps from the web scraper) into the rolling conversation history, the context window fills up exponentially. You must implement a strict `max_iterations` limit, and use a 'Rolling Buffer' or summarize previous observations to prevent context explosion.", ["Infinite loop of failed tool calls (agent gets stuck and retries)", "Every tool output (like massive HTML pages) is blindly appended to the prompt", "Fix by enforcing `max_iterations`, and summarizing/truncating past observations"], ["The internet ran out of data"]),
    ("B58_3", "architecture", "hard", "architecture", ["AI Agents"], "Explain the architectural difference between a traditional 'Agent Loop' (like AutoGPT) and a 'State Machine Agent' (like LangGraph).", "A traditional Agent Loop uses a single LLM call in a `while True` loop to act as the sole 'brain', dynamically deciding the next step based purely on the prompt history. It is highly unpredictable and often hallucinates or spirals out of control. A State Machine (LangGraph) structures the workflow as a Directed Cyclic Graph (nodes and edges). You explicitly define the rigid states (e.g., `Draft_Code` -> `Run_Tests` -> `Review`). The LLM only makes micro-decisions to route between predefined edges. This provides deterministic control, human-in-the-loop checkpoints, and massive reliability.", ["Traditional Agent: Single LLM in a `while` loop deciding every next step dynamically (unpredictable)", "State Machine (LangGraph): Defines a rigid graph of nodes and conditional routing edges", "Provides deterministic control, easy debugging, and safe human-in-the-loop breakpoints"], ["State machines are for robotics, loops are for software"]),
    ("B58_3", "tradeoff", "medium", "tradeoff", ["AI Agents"], "What is the tradeoff of using a monolithic 'Generalist Agent' (one LLM with 20 tools) versus a 'Multi-Agent System' (5 LLMs, each with 4 tools)?", "A Generalist Agent is cheap (one LLM call) and easy to setup. The tradeoff is that giving an LLM 20 tools drastically degrades its ability to choose the correct one (it gets confused by the massive system prompt). A Multi-Agent System (e.g., CrewAI) breaks the problem down: a 'Router' agent passes the task to a 'Coder' agent, who passes it to a 'QA' agent. This drastically improves accuracy because each agent has a tiny, focused system prompt and limited tools. The severe tradeoff is latency and cost (10x more LLM calls to solve one problem).", ["Generalist: One prompt with 20 tools; cheap but the LLM gets confused and fails often", "Multi-Agent: Specialized agents with narrow focus; highly accurate and reliable", "Tradeoff: Multi-Agent requires exponentially more LLM calls, increasing cost and latency"], ["Generalists are for Windows, Multi-agents are for Mac"])
]

def run_batch():
    # Write directly to file
    with open(OUT, "a", encoding="utf-8") as f:
        for q in Q:
            rec = {
                "primary_role": ROLE,
                "applicable_roles": ["Machine Learning Engineer", "Backend Developer"],
                "primary_skill": q[4][0],
                "secondary_skills": q[4][1:] if len(q[4]) > 1 else [],
                "technology": "Generative AI",
                "topic": q[4][0] if len(q[4]) > 0 else "General",
                "category": "AI/ML",
                "intent": q[1],
                "difficulty": q[2],
                "question_type": q[3],
                "question": q[5],
                "expected_answer": q[6],
                "evaluation_rubric": {
                    "strong_indicators": q[7],
                    "weak_indicators": q[8]
                },
                "id": str(uuid.uuid4()),
                "source": "Antigravity_Internal_Knowledge",
                "provenance_type": "researched_generated",
                "dataset_version": "v2",
                "status": "active"
            }
            f.write(json.dumps(rec) + "\n")
            
    print(f"Appended {len(Q)} questions (Batch 58 Part 1).")

if __name__ == "__main__":
    run_batch()
