"""Batch 7 question content (Machine Learning Engineer). Antigravity-native, no Gemini API."""

ROLE = "Machine Learning Engineer"

# key: (plan skill, plan topic, applicable_roles)
BUCKET_KEYS = {
    "LIN": ("Supervised Learning", "Linear Regression", ["Data Analyst", "AI Engineer"]),
    "TRE": ("Supervised Learning", "Trees", ["Data Analyst", "AI Engineer"]),
    "SVM": ("Supervised Learning", "SVM", ["AI Engineer"]),
    "PRE": ("Model Evaluation", "Precision", ["Data Analyst", "AI Engineer"]),
    "ROC": ("Model Evaluation", "ROC-AUC", ["Data Analyst", "AI Engineer"]),
}

# (bucket, intent, difficulty, qtype, secondary_skills, question, expected_answer, strong, weak)
Q = [
# ---------------- Linear Regression ----------------
("LIN", "fundamentals", "easy", "concept", [],
 "What does a linear regression model actually learn, and how should you read one feature's coefficient?",
 "It learns a weight for each feature plus an intercept so that the prediction is a weighted sum of the inputs. A coefficient is the expected change in the target for a one-unit increase in that feature while the other features are held constant.",
 ["Weighted sum plus intercept", "Change per unit with other features held constant"],
 ["Reads the coefficient as feature importance without considering scale"]),
("LIN", "explain", "easy", "concept", [],
 "What quantity does ordinary least squares minimize when fitting a line?",
 "It minimizes the sum (or mean) of squared residuals, the squared differences between actual and predicted values. Squaring penalizes large errors more heavily and gives a smooth objective with a closed-form solution.",
 ["Sum of squared residuals", "Squaring penalizes large errors"],
 ["Says it minimizes the sum of absolute errors"]),
("LIN", "fundamentals", "easy", "concept", [],
 "What is the role of the intercept term in linear regression, and what happens if you leave it out?",
 "The intercept is the predicted value when all features are zero and lets the fitted line shift vertically. Without it the model is forced through the origin, which biases the fit unless the data is truly centered around zero.",
 ["Baseline prediction at zero features", "Forces line through the origin if removed"],
 ["Believes the intercept has no effect on predictions"]),
("LIN", "explain", "easy", "concept", [],
 "If a model reports an R-squared of 0.80, what does that tell you and what does it not tell you?",
 "About 80% of the variance in the target is explained by the model on that data. It does not show that predictions are unbiased or accurate in absolute terms, nor that the model will generalize, and it never decreases when more features are added.",
 ["Proportion of variance explained", "Does not guarantee generalization", "Increases with extra features"],
 ["Interprets it as 80% prediction accuracy"]),
("LIN", "fundamentals", "easy", "concept", [],
 "What are residuals, and what does a curved pattern in a residual plot suggest?",
 "A residual is actual minus predicted value. Residuals should look like random noise around zero. A curve indicates a non-linear relationship the straight-line model is missing, so you may need transformed features or polynomial terms.",
 ["Residual defined correctly", "Curved pattern signals non-linearity", "Suggests feature transformation"],
 ["Says a curve means the data is too noisy"]),
("LIN", "explain", "easy", "concept", [],
 "When training linear regression with gradient descent, what does the learning rate control?",
 "It sets the step size of each weight update along the negative gradient. Too small makes training slow, while too large can overshoot the minimum, oscillate or diverge.",
 ["Step size", "Too large diverges or oscillates", "Too small is slow"],
 ["Confuses it with the number of epochs"]),
("LIN", "diagnose", "medium", "debugging", ["Debugging"],
 "Two highly correlated features cause your regression coefficients to flip sign between training runs. What is going on and how would you handle it?",
 "This is multicollinearity: the model cannot separate the correlated features' effects, so coefficient estimates become unstable with large variance even though predictions may stay fine. Detect it with correlation matrices or VIF, then drop or combine features, use PCA, or apply ridge regularization.",
 ["Names multicollinearity", "Unstable coefficients, stable predictions", "VIF to detect", "Drop, combine or regularize"],
 ["Blames random initialization of weights"]),
("LIN", "compare", "medium", "comparison", [],
 "How do ridge and lasso regression differ, and when would you pick one over the other?",
 "Ridge adds an L2 penalty that shrinks coefficients smoothly toward zero without eliminating them, helping with multicollinearity. Lasso adds an L1 penalty that can set coefficients exactly to zero, performing feature selection. Prefer lasso when you expect a sparse set of useful features, ridge when many features contribute and are correlated.",
 ["L2 shrinks, L1 zeroes out", "Lasso gives feature selection", "Ridge suits correlated features"],
 ["Says both always remove features"]),
("LIN", "explain", "medium", "concept", ["Data Preprocessing"],
 "Why can't you feed a categorical column such as 'city' directly into linear regression as integers, and what is the dummy variable trap?",
 "Integer codes impose a false ordering and equal spacing the model will treat numerically. One-hot encoding creates a binary column per category. If you keep all k columns together with an intercept they sum to one, creating perfect collinearity (the dummy variable trap), so drop one category as the reference or drop the intercept.",
 ["Integer codes imply false order", "One-hot encoding", "Perfect collinearity with intercept", "Drop one reference level"],
 ["Says label encoding is always fine for linear models"]),
("LIN", "diagnose", "medium", "debugging", ["Debugging"],
 "A polynomial regression model scores R-squared 0.99 on training data but 0.40 on a held-out set. What is happening and what are your options?",
 "The model is overfitting: the high-degree polynomial memorizes noise. Options include lowering the degree, adding L2 or L1 regularization, collecting more data, using cross-validation to choose complexity, and checking for data leakage between sets.",
 ["Identifies overfitting", "Reduce complexity or regularize", "Cross-validation for model selection"],
 ["Suggests training longer"]),

# ---------------- Trees ----------------
("TRE", "fundamentals", "easy", "concept", [],
 "How does a decision tree choose which feature and threshold to split on at a node?",
 "It evaluates candidate splits and picks the one that gives the largest reduction in impurity (information gain for entropy, or Gini decrease) in the child nodes, usually by greedy search at each node.",
 ["Evaluates candidate splits", "Maximizes impurity reduction", "Greedy per node"],
 ["Says it picks splits at random"]),
("TRE", "explain", "easy", "concept", [],
 "What does Gini impurity measure, and what does a Gini value of 0 mean at a node?",
 "Gini impurity is the probability of misclassifying a randomly chosen sample if labeled according to the node's class distribution. A value of 0 means the node is pure and contains only one class.",
 ["Misclassification probability", "0 means pure node"],
 ["Says Gini is the same as accuracy"]),
("TRE", "explain", "easy", "concept", [],
 "What do the hyperparameters max_depth and min_samples_leaf control in a decision tree?",
 "max_depth limits how many levels the tree can grow, and min_samples_leaf requires a minimum number of samples in every leaf. Both restrict complexity and help prevent overfitting.",
 ["Depth limit", "Minimum leaf size", "Both reduce overfitting"],
 ["Thinks they control the number of features used"]),
("TRE", "explain", "easy", "concept", [],
 "Why are single decision trees considered easy to interpret?",
 "Predictions follow a sequence of human-readable if/else rules from root to leaf, so you can trace exactly why a sample was classified and visualize the rules. This holds mainly for shallow trees.",
 ["Rule-based path from root to leaf", "Visualizable", "Mostly true for shallow trees"],
 ["Says trees are interpretable regardless of size"]),
("TRE", "explain", "easy", "concept", [],
 "Why don't decision trees need feature scaling?",
 "Splits compare a single feature against a threshold, so only the ordering of values matters and monotonic rescaling does not change which splits are chosen. Unlike distance- or gradient-based models, scale does not affect the result.",
 ["Splits use thresholds on one feature", "Invariant to monotonic scaling"],
 ["Says scaling is required for tree models"]),
("TRE", "fundamentals", "easy", "concept", [],
 "What does a leaf node return in a classification tree versus a regression tree?",
 "A classification leaf returns the majority class (or class probabilities from the sample proportions) of the training samples that reached it. A regression leaf returns the mean target value of those samples.",
 ["Majority class or proportions", "Mean value for regression"],
 ["Says leaves always return the root's value"]),
("TRE", "diagnose", "medium", "debugging", ["Debugging"],
 "A fully grown decision tree has 100% training accuracy but poor test accuracy. How do you address that?",
 "The tree has overfit by creating leaves for individual noisy samples. Limit growth (max_depth, min_samples_leaf), apply cost-complexity pruning (ccp_alpha) chosen via cross-validation, or move to an ensemble such as a random forest.",
 ["Overfitting identified", "Pre-pruning or cost-complexity pruning", "Cross-validation", "Ensembles"],
 ["Says a perfect training score means the model is good"]),
("TRE", "compare", "medium", "comparison", [],
 "Why does a random forest usually generalize better than a single decision tree?",
 "A random forest averages many trees trained on bootstrap samples with random feature subsets at each split, so the trees are decorrelated and their individual errors average out. This lowers variance without much increase in bias.",
 ["Bagging", "Random feature subsets decorrelate trees", "Variance reduction"],
 ["Says forests are simply deeper trees"]),
("TRE", "compare", "medium", "comparison", [],
 "How do gradient boosting and random forests differ in how they build trees?",
 "Random forests train deep trees independently in parallel and average them, reducing variance. Gradient boosting trains shallow trees sequentially, each fitting the residual errors of the ensemble so far, reducing bias, and is more sensitive to hyperparameters and overfitting.",
 ["Parallel versus sequential", "Boosting fits residuals", "Variance versus bias focus"],
 ["Says boosting averages independent trees"]),
("TRE", "explain", "medium", "concept", ["Interpretation"],
 "Why can impurity-based feature importance from a tree ensemble be misleading, and what would you use instead?",
 "Impurity-based importance is computed on training data and is biased toward high-cardinality or continuous features, and it splits credit among correlated features. Permutation importance on held-out data, or SHAP values, give more reliable estimates.",
 ["Bias toward high-cardinality features", "Computed on training data", "Permutation importance or SHAP"],
 ["Treats the built-in importance as ground truth"]),

# ---------------- SVM ----------------
("SVM", "fundamentals", "easy", "concept", [],
 "What is the maximum-margin hyperplane in an SVM, and what are support vectors?",
 "The SVM picks the separating hyperplane that maximizes the distance to the nearest points of each class. Those nearest points that lie on or inside the margin are the support vectors, and they alone determine the decision boundary.",
 ["Maximizes the margin", "Support vectors are the closest points", "Only support vectors define the boundary"],
 ["Thinks all training points affect the boundary equally"]),
("SVM", "explain", "easy", "concept", [],
 "In a soft-margin SVM, what does the C parameter control?",
 "C sets the penalty for margin violations. A large C punishes misclassifications heavily, giving a narrower margin and risk of overfitting. A small C tolerates more violations, giving a wider margin and a simpler model.",
 ["Trade-off between margin width and violations", "Large C risks overfitting", "Small C is more regularized"],
 ["Says C is the kernel width"]),
("SVM", "explain", "easy", "concept", [],
 "Why is feature scaling important when training an SVM?",
 "The margin and kernel functions depend on distances between points, so features with large numeric ranges dominate the distance calculation. Standardizing features lets all of them contribute fairly and speeds up optimization.",
 ["Distance-based margin", "Large-range features dominate", "Standardize"],
 ["Says SVMs are scale-invariant"]),
("SVM", "explain", "easy", "concept", [],
 "What is the kernel trick, in simple terms?",
 "It lets the SVM behave as if data were mapped into a higher-dimensional space where classes become linearly separable, without computing that mapping explicitly. The kernel function directly computes the inner product in the transformed space.",
 ["Implicit higher-dimensional mapping", "Kernel computes inner products", "Avoids explicit transformation"],
 ["Says it increases the number of rows"]),
("SVM", "compare", "easy", "comparison", [],
 "What is the difference between a hard-margin and a soft-margin SVM?",
 "A hard margin demands perfect separation with no violations, so it only works for linearly separable data and is sensitive to outliers. A soft margin allows some points to be misclassified or inside the margin, controlled by C, making it practical for noisy real data.",
 ["Hard margin needs separable data", "Soft margin allows violations", "Outlier sensitivity"],
 ["Says soft margin removes the margin"]),
("SVM", "fundamentals", "easy", "concept", [],
 "Does an SVM natively output class probabilities?",
 "No, it outputs a signed distance to the decision boundary. Probabilities can be approximated afterwards with Platt scaling (a logistic fit on the scores) or isotonic calibration, as scikit-learn does with probability=True using internal cross-validation.",
 ["Outputs margin distance, not probability", "Platt scaling or calibration"],
 ["Says the decision score is a probability"]),
("SVM", "diagnose", "medium", "debugging", ["Debugging"],
 "An RBF-kernel SVM gets perfect training accuracy but poor validation accuracy. How do gamma and C factor into the fix?",
 "A large gamma makes each point's influence very local and a large C punishes violations, so the boundary becomes very wiggly and overfits. Reduce gamma and C, tune them together with a grid or random search using cross-validation, and verify features are scaled.",
 ["Large gamma gives local influence", "Large C penalizes violations", "Tune jointly with cross-validation"],
 ["Only suggests more training data without tuning"]),
("SVM", "tradeoff", "medium", "tradeoff", ["Performance"],
 "How would you choose between a linear kernel and an RBF kernel for a text classification task with 100,000 sparse features and 50,000 samples?",
 "Text data in a high-dimensional sparse space is often already close to linearly separable, so a linear SVM is accurate, fast and scalable (training roughly linear in samples). Kernel SVMs scale between quadratic and cubic in samples and need a kernel matrix, which is expensive at this size and adds little over linear.",
 ["High-dimensional sparse data is near linearly separable", "Kernel SVM scaling cost", "Linear SVM is efficient"],
 ["Always recommends the RBF kernel"]),
("SVM", "explain", "medium", "concept", [],
 "SVMs are inherently binary classifiers. How are they extended to multiclass problems?",
 "Use one-vs-rest, training one classifier per class against all others and choosing the highest score, or one-vs-one, training a classifier for every pair of classes and voting. One-vs-one trains more models on smaller subsets and is common for kernel SVMs such as libsvm.",
 ["One-vs-rest", "One-vs-one with voting", "Number of classifiers differs"],
 ["Says SVMs natively handle any number of classes"]),
("SVM", "compare", "medium", "comparison", [],
 "How does a linear SVM differ from logistic regression in what it optimizes and what it outputs?",
 "A linear SVM minimizes hinge loss plus regularization, focusing on points near the margin and ignoring well-classified points, and outputs margins. Logistic regression minimizes log loss over all points and outputs calibrated probabilities. Accuracy is often similar, but logistic regression suits probability estimates and SVMs focus on maximum margin.",
 ["Hinge loss versus log loss", "Support vectors versus all points", "Probabilities from logistic regression"],
 ["Says they use the same loss"]),

# ---------------- Precision ----------------
("PRE", "fundamentals", "easy", "concept", [],
 "How is precision defined, and what question does it answer about a classifier?",
 "Precision is TP / (TP + FP): of everything the model labelled positive, the fraction that was actually positive. It answers how trustworthy a positive prediction is.",
 ["TP / (TP + FP)", "Trust in positive predictions"],
 ["Defines it as TP / (TP + FN)"]),
("PRE", "fundamentals", "easy", "concept", [],
 "A spam filter flags 100 emails and 80 of them really are spam. What is its precision, and what does that mean?",
 "Precision is 80 / 100 = 0.80, so 20% of flagged emails are legitimate messages wrongly sent to spam. It says nothing about how much spam the filter missed.",
 ["Computes 0.80", "20% false positives", "Missed spam not captured"],
 ["Divides by the total number of emails"]),
("PRE", "explain", "easy", "concept", [],
 "Which kind of error hurts precision, and in what applications is it the metric you most want high?",
 "False positives lower precision. It matters when a false alarm is costly, such as spam filtering of important mail, flagging legitimate transactions as fraud, or recommending unsafe content.",
 ["False positives reduce precision", "Costly false alarms"],
 ["Says false negatives reduce precision"]),
("PRE", "explain", "easy", "concept", [],
 "A model predicts 'positive' for exactly one sample and is correct. Its precision is 1.0. Why is that not a good model?",
 "Precision ignores positives the model failed to find. Predicting only one very certain positive gives perfect precision while missing almost all real positives, so precision must be read together with recall.",
 ["Ignores missed positives", "Needs recall alongside"],
 ["Concludes the model is perfect"]),
("PRE", "explain", "easy", "concept", [],
 "How does raising the classification threshold usually affect precision?",
 "A higher threshold labels fewer samples positive and only the most confident ones, which generally increases precision (fewer false positives) while reducing the number of true positives captured. The relationship is not strictly monotonic on noisy data.",
 ["Higher threshold increases precision typically", "Fewer positives predicted"],
 ["Says it always decreases precision"]),
("PRE", "fundamentals", "easy", "concept", [],
 "What does precision@k mean for a recommender or search system?",
 "It is the fraction of the top k returned items that are relevant, computed only over the first k results. It reflects what a user sees on the first page and ignores items beyond rank k.",
 ["Fraction relevant in top k", "Only considers first k results"],
 ["Confuses it with recall@k"]),
("PRE", "compare", "medium", "comparison", [],
 "In a multiclass problem, how do macro, micro and weighted precision differ?",
 "Macro precision averages per-class precision equally, so rare classes count as much as common ones. Micro pools all TP and FP across classes before computing, so it is dominated by frequent classes (and equals accuracy in single-label multiclass). Weighted averages per-class precision weighted by class support.",
 ["Macro treats classes equally", "Micro pools counts", "Weighted uses support"],
 ["Says the three are identical"]),
("PRE", "explain", "medium", "concept", [],
 "Why can a model's precision drop in production even when its recall and ROC curve stay unchanged?",
 "Precision depends on class prevalence. If positives become rarer in production, the same false-positive rate yields proportionally more false positives among predicted positives, so precision falls although the model's ranking ability is unchanged.",
 ["Precision depends on base rate", "Same FPR with fewer positives", "Prevalence shift"],
 ["Blames the model weights changing"]),
("PRE", "implement", "medium", "implementation", ["Model Evaluation"],
 "Your business requires at least 95% precision on fraud alerts. How would you choose the decision threshold?",
 "Compute the precision-recall curve on a validation set (for example with precision_recall_curve), find the lowest threshold at which precision is at least 0.95 to preserve the most recall, and confirm on a separate test set because the threshold estimate is noisy. Check the recall you give up and recheck after prevalence shifts.",
 ["Uses precision-recall curve", "Lowest threshold meeting the target", "Validates on separate data", "Reports resulting recall"],
 ["Keeps the default 0.5 threshold"]),
("PRE", "diagnose", "medium", "debugging", ["Debugging"],
 "Your classifier shows 95% accuracy but only 12% precision for the positive class. What are the likely causes?",
 "The data is highly imbalanced, so accuracy is dominated by the negative class while the model makes many false positives relative to true positives. Check class balance, the threshold, and calibration, and evaluate with precision-recall metrics instead of accuracy.",
 ["Class imbalance inflates accuracy", "Many false positives", "Use PR metrics and review threshold"],
 ["Concludes the model is fine because accuracy is high"]),

# ---------------- ROC-AUC ----------------
("ROC", "fundamentals", "easy", "concept", [],
 "What do the x-axis and y-axis of a ROC curve represent?",
 "The y-axis is the true positive rate (recall) and the x-axis is the false positive rate, each computed across all possible classification thresholds.",
 ["TPR on y-axis", "FPR on x-axis", "Across thresholds"],
 ["Plots precision against recall"]),
("ROC", "explain", "easy", "concept", [],
 "How would you interpret ROC-AUC values of 0.5 and 1.0?",
 "0.5 means the model ranks positives and negatives no better than random chance, lying on the diagonal. 1.0 means every positive is ranked above every negative, a perfect ranking.",
 ["0.5 is random ranking", "1.0 is perfect separation"],
 ["Says 0.5 means 50% accuracy"]),
("ROC", "explain", "easy", "concept", [],
 "Does ROC-AUC depend on the classification threshold you choose?",
 "No. It summarizes performance over all thresholds by looking at how the model ranks samples, so it does not reflect the behavior at any single operating threshold.",
 ["Threshold independent", "Based on ranking"],
 ["Says it is computed at the 0.5 threshold"]),
("ROC", "diagnose", "easy", "debugging", [],
 "A trained binary model yields an ROC-AUC of 0.15. What does that suggest?",
 "The model is ranking systematically in the wrong direction, worse than random. Inverting its scores would give about 0.85, so check for flipped labels, a reversed score or class mapping, or a bug in the pipeline.",
 ["Below 0.5 means inverted ranking", "Check label or score direction"],
 ["Concludes the model is just very bad and unfixable"]),
("ROC", "fundamentals", "easy", "concept", [],
 "How do you compute one point on the ROC curve from predictions?",
 "Pick a threshold, label scores above it positive, and compute TPR = TP / (TP + FN) and FPR = FP / (FP + TN) from the confusion matrix. Repeating over all thresholds traces the curve.",
 ["TPR and FPR formulas", "Threshold sweep traces the curve"],
 ["Uses precision as one axis"]),
("ROC", "explain", "easy", "concept", [],
 "Why might you compare models with ROC-AUC rather than accuracy?",
 "ROC-AUC measures ranking quality independent of a threshold and is less affected by class imbalance than accuracy, so it compares how well models separate classes before committing to an operating point.",
 ["Threshold independent comparison", "Less distorted by imbalance than accuracy"],
 ["Says accuracy cannot be computed for probabilistic models"]),
("ROC", "explain", "medium", "concept", [],
 "What is the probabilistic interpretation of ROC-AUC?",
 "AUC equals the probability that the model assigns a higher score to a randomly chosen positive sample than to a randomly chosen negative one (equivalent to the Mann-Whitney U statistic with ties counted as one half).",
 ["Probability positive scored above negative", "Mann-Whitney equivalence"],
 ["Says it is the probability of a correct prediction"]),
("ROC", "compare", "medium", "comparison", [],
 "For a dataset with 0.5% positives, why might PR-AUC tell you more than ROC-AUC?",
 "ROC uses the false positive rate, whose denominator is the huge negative class, so a large number of false positives barely moves the curve and ROC-AUC can look excellent. Precision-recall focuses on positive predictions, so it reveals the poor precision that matters under heavy imbalance.",
 ["FPR denominator is large", "ROC looks optimistic under imbalance", "PR curve reflects precision"],
 ["Says ROC-AUC is invalid for imbalanced data"]),
("ROC", "implement", "medium", "implementation", [],
 "How can ROC-AUC be extended to a multiclass classifier?",
 "Use one-vs-rest, computing an AUC for each class against all others and averaging (macro, or weighted by support), or one-vs-one, averaging AUC over all class pairs, which is less sensitive to imbalance. The model must output class probabilities or scores.",
 ["One-vs-rest averaging", "One-vs-one alternative", "Needs probability scores"],
 ["Says ROC-AUC only works for binary problems"]),
("ROC", "scenario", "medium", "scenario", ["Calibration"],
 "Your model has an ROC-AUC of 0.93, yet the predicted probabilities are far from observed frequencies. Is that contradictory?",
 "No. AUC measures only the ranking of scores, so any monotonic transformation leaves it unchanged. A model can rank well while being poorly calibrated. If you need meaningful probabilities, check a calibration curve or Brier score and apply Platt scaling or isotonic regression.",
 ["AUC measures ranking, not calibration", "Monotonic transforms preserve AUC", "Calibration curve and recalibration"],
 ["Believes high AUC guarantees calibrated probabilities"]),
]
