"""Batch 8 question content (Data Analyst). Antigravity-native, no Gemini API."""

ROLE = "Data Analyst"

# key: (plan skill, plan topic, applicable_roles)
BUCKET_KEYS = {
    "MIS": ("Data Cleaning", "Missing Values", ["Machine Learning Engineer", "AI Engineer"]),
    "OUT": ("Data Cleaning", "Outliers", ["Machine Learning Engineer"]),
    "AGG": ("Python Pandas", "Aggregation", ["Python Developer"]),
    "VAR": ("Statistics Basics", "Variance", ["Machine Learning Engineer"]),
    "CHT": ("Data Visualization", "Chart Types", []),
}

# (bucket, intent, difficulty, qtype, secondary_skills, question, expected_answer, strong, weak)
Q = [
# ---------------- Missing Values ----------------
("MIS", "explain", "easy", "concept", [],
 "Why does it matter whether a missing entry is a NULL, an empty string or a zero when you analyze a dataset?",
 "Each means something different: NULL means the value is unknown, an empty string is a recorded blank, and zero is a real measurement. Averages, counts and filters treat them differently, so treating NULL or blank as zero biases results, and treating zero as missing throws away real data.",
 ["Distinguishes unknown from zero", "Aggregates handle NULL differently", "Treating missing as zero biases results"],
 ["Treats all three as interchangeable"]),
("MIS", "implement", "easy", "implementation", ["Python Pandas"],
 "In pandas, how would you see how many values are missing in each column and then drop only rows that lack a customer_id?",
 "Use df.isna().sum() for per-column counts, then df.dropna(subset=['customer_id']) to drop rows where only that column is missing, leaving rows with gaps in other columns intact.",
 ["isna().sum() for counts", "dropna(subset=...) targets a column"],
 ["Uses plain dropna() and loses every incomplete row"]),
("MIS", "explain", "easy", "concept", [],
 "Why is deleting every row that contains any missing value usually a poor default?",
 "Listwise deletion can discard a large share of the data, shrinking sample size and statistical power. If missingness is not completely random it also biases the remaining sample, so you should understand why values are missing before deleting.",
 ["Loses data and power", "Can bias the sample"],
 ["Says deletion is always the safest option"]),
("MIS", "explain", "easy", "concept", [],
 "What is a missing-value indicator column, and why might you add one next to an imputed feature?",
 "It is a binary flag marking rows where the original value was missing. After imputation the filled value looks real, so the flag preserves the information that it was absent, which can be predictive and lets you audit the imputation.",
 ["Binary flag of missingness", "Preserves information lost by imputation"],
 ["Thinks the flag replaces the imputed value"]),
("MIS", "debug", "easy", "debugging", ["Python Pandas"],
 "You run df['age'].fillna(0) but the DataFrame still shows NaN values in age afterwards. What went wrong?",
 "fillna returns a new Series and does not modify the DataFrame unless you assign the result (df['age'] = df['age'].fillna(0)) or use inplace=True, which is discouraged. The original column was never changed.",
 ["fillna returns a new object", "Assign the result back"],
 ["Blames the data type of the column"]),
("MIS", "explain", "medium", "concept", [],
 "How do MCAR, MAR and MNAR differ, and why does the distinction affect how you handle missing data?",
 "MCAR: missingness is unrelated to any data, so deletion or simple imputation is mostly unbiased. MAR: missingness depends on observed variables, so imputation conditioned on those variables is appropriate. MNAR: missingness depends on the unobserved value itself (for example high earners hiding income), which cannot be fixed by simple imputation and needs modelling of the missingness or sensitivity analysis.",
 ["Defines all three", "MAR allows conditional imputation", "MNAR needs special treatment"],
 ["Says the mechanism does not affect the method"]),
("MIS", "tradeoff", "medium", "tradeoff", [],
 "When would you impute with a median instead of using a model-based approach such as KNN or iterative imputation?",
 "Median imputation is quick, robust to outliers and keeps the dataset size, but it ignores relationships between features and shrinks variance. KNN or iterative imputation uses other features to produce more plausible values and preserves correlations, but costs more compute, can leak information if fit on all data, and is harder to explain. Use simple imputation for low missingness or baselines and model-based when missingness is substantial and features are informative.",
 ["Simple methods ignore feature relationships", "Model-based preserves structure but costs compute", "Matches choice to missingness level"],
 ["Claims one method is always better"]),
("MIS", "scenario", "medium", "scenario", [],
 "High-income respondents skip the income question far more often than others. What problem does that create and how would you respond?",
 "Missingness depends on the unobserved value itself (MNAR), so mean imputation will understate average income and distort the distribution. Respond by investigating the mechanism, using auxiliary variables or models of missingness, reporting results with sensitivity analysis or bounds, and being transparent about the limitation rather than silently filling the mean.",
 ["Identifies MNAR", "Mean imputation understates income", "Sensitivity analysis and transparency"],
 ["Fills with the mean and moves on"]),
("MIS", "implement", "medium", "implementation", ["Python Pandas"],
 "How would you fill missing salaries with the median salary of each employee's own department in pandas?",
 "Compute a per-group median with groupby and transform so it aligns to the original index: df['salary'] = df['salary'].fillna(df.groupby('dept')['salary'].transform('median')). Departments whose salaries are all missing still need a fallback such as the overall median.",
 ["groupby().transform('median')", "fillna with aligned series", "Fallback for empty groups"],
 ["Uses a single global mean for every department"]),
("MIS", "diagnose", "medium", "debugging", ["Machine Learning"],
 "A model's validation score looks great, but it drops sharply on live data. You imputed missing values with the dataset mean before splitting into train and test sets. What is the issue?",
 "Computing the mean on the full dataset leaks information from the test set into training, inflating validation scores. Split first, fit the imputer on the training data only, and apply that fitted imputer to validation and test data, ideally inside a pipeline.",
 ["Data leakage via imputation before split", "Fit on training only", "Use a pipeline"],
 ["Blames random seed differences"]),

# ---------------- Outliers ----------------
("OUT", "fundamentals", "easy", "concept", [],
 "What is an outlier, and why shouldn't you remove one automatically?",
 "An outlier is an observation far from the bulk of the data. It may be a data-entry error, a measurement fault or a genuine rare event that carries real information (like a fraud case or a viral product), so you should investigate its cause before dropping it.",
 ["Definition", "Could be error or genuine", "Investigate before removing"],
 ["Says outliers are always errors"]),
("OUT", "implement", "easy", "implementation", ["Python Pandas"],
 "How do you flag outliers with the IQR rule in pandas?",
 "Compute Q1 and Q3 with quantile(0.25) and quantile(0.75), IQR = Q3 - Q1, then mark values below Q1 - 1.5*IQR or above Q3 + 1.5*IQR, for example with a boolean mask on the column.",
 ["Q1, Q3 and IQR", "1.5 * IQR fences", "Boolean mask"],
 ["Uses mean plus three standard deviations only"]),
("OUT", "explain", "easy", "concept", [],
 "A value has a z-score of 4. What does that tell you, and what assumption does the interpretation rely on?",
 "It lies four standard deviations above the mean, which is very unusual if the data is roughly normal (about 0.003% probability). The interpretation relies on approximate normality; for skewed data a large z-score may be common.",
 ["Four standard deviations from the mean", "Assumes roughly normal data"],
 ["Says z-score of 4 means 4% above average"]),
("OUT", "explain", "easy", "concept", [],
 "How does a box plot display outliers?",
 "The box spans Q1 to Q3 with a line at the median, whiskers extend to the most extreme points within 1.5 times the IQR, and points beyond the whiskers are drawn individually as outliers.",
 ["Box is Q1 to Q3 with median", "Whiskers at 1.5 * IQR", "Points beyond are outliers"],
 ["Says whiskers always show min and max"]),
("OUT", "scenario", "easy", "scenario", [],
 "A temperature sensor log contains a reading of 4,000 degrees at an office. How do you decide whether it is an error or a real extreme?",
 "Check against domain limits and context: 4,000 degrees is physically impossible for an office, so it is almost certainly a sensor or entry fault. Compare with neighbouring readings, other sensors and the device's valid range, then correct, mark as missing or remove it and document the decision.",
 ["Uses domain knowledge", "Compares with neighbouring data", "Documents the handling"],
 ["Keeps it because the sensor reported it"]),
("OUT", "compare", "medium", "comparison", [],
 "When does the z-score method for detecting outliers break down compared with the IQR method?",
 "The mean and standard deviation are themselves pulled by outliers, so large outliers inflate the standard deviation and can hide themselves (masking), and skewed distributions break the normality assumption. IQR uses quartiles, which are robust, so it is more reliable for skewed data or when extreme values exist.",
 ["Mean and SD are sensitive to outliers", "Masking effect", "IQR is robust"],
 ["Says both always give the same flags"]),
("OUT", "tradeoff", "medium", "tradeoff", [],
 "How would you choose between removing outliers, winsorizing them and applying a log transform?",
 "Removing is appropriate for confirmed errors but discards information and shrinks the sample. Winsorizing caps extremes at percentiles, keeping rows while limiting influence. A log transform compresses a right-skewed scale for all values, helping models but making results harder to interpret. Choose based on cause, analysis goal and interpretability.",
 ["Removal for errors", "Winsorizing keeps rows", "Log transform for skew", "Matches choice to cause and goal"],
 ["Always removes anything beyond 3 SD"]),
("OUT", "scenario", "medium", "scenario", [],
 "A dashboard shows average order value jumped 40% because of a single $2M enterprise order. How would you handle the reporting?",
 "Confirm the order is genuine, then avoid letting it silently distort the headline. Report the median or a trimmed mean alongside the mean, show the outlier separately or annotate it, and consider segmenting enterprise and standard orders. Do not delete a real order, but make its effect visible.",
 ["Verify the data point", "Median or trimmed mean alongside", "Segment or annotate", "Do not delete real data"],
 ["Deletes the order to make the chart look normal"]),
("OUT", "implement", "medium", "implementation", ["Python Pandas"],
 "How would you cap a numeric column at its 1st and 99th percentiles in pandas?",
 "Compute lower, upper = df['x'].quantile([0.01, 0.99]) and then df['x'] = df['x'].clip(lower, upper). Compute the bounds on training data only when the result feeds a model.",
 ["quantile bounds", "clip(lower, upper)", "Bounds from training data for models"],
 ["Drops rows outside the percentiles"]),
("OUT", "diagnose", "medium", "debugging", ["Regression"],
 "A regression slope changes dramatically when you remove three data points. How do you identify those points and what can you do?",
 "Those points have high leverage or influence on the fit. Identify them with residual plots, leverage and Cook's distance, check whether they are errors, and then fix or document them, or use robust regression (Huber, RANSAC) or a transformation so a few points do not dominate.",
 ["Influential points", "Cook's distance or leverage", "Robust regression"],
 ["Removes points without investigating"]),

# ---------------- Pandas Aggregation ----------------
("AGG", "implement", "easy", "implementation", [],
 "How do you compute total revenue per region from a sales DataFrame in pandas?",
 "Use df.groupby('region')['revenue'].sum(), which splits rows by region and returns a Series of totals. Add .reset_index() if you want a DataFrame.",
 ["groupby on region", "Select revenue and sum"],
 ["Loops over rows manually"]),
("AGG", "explain", "easy", "concept", [],
 "What does the split-apply-combine pattern behind groupby mean?",
 "Pandas splits the data into groups by key, applies a function (aggregation, transformation or filter) to each group independently, and combines the results into a single object.",
 ["Split by key", "Apply a function per group", "Combine results"],
 ["Thinks groupby sorts the DataFrame only"]),
("AGG", "explain", "easy", "concept", [],
 "On a groupby object, what is the difference between count() and size()?",
 "count() returns the number of non-null values per column in each group, while size() returns the number of rows in each group including those with NaN.",
 ["count excludes NaN", "size counts all rows"],
 ["Says they are identical"]),
("AGG", "implement", "easy", "implementation", [],
 "How would you build a table with regions as rows, months as columns and total sales as values?",
 "Use pd.pivot_table(df, index='region', columns='month', values='sales', aggfunc='sum'), optionally with fill_value=0 for missing combinations.",
 ["pivot_table with index and columns", "aggfunc='sum'", "fill_value for gaps"],
 ["Uses groupby without reshaping"]),
("AGG", "compare", "medium", "comparison", [],
 "What is the difference between agg, transform and apply on a pandas groupby?",
 "agg reduces each group to one row per group. transform returns a result with the same length and index as the input, so it can be assigned back as a column. apply is the most general, can return scalars, Series or DataFrames, but is the slowest and least predictable.",
 ["agg reduces", "transform keeps original shape", "apply is general but slow"],
 ["Uses them interchangeably"]),
("AGG", "implement", "medium", "implementation", [],
 "How would you add a column showing each row's share of its category's total sales?",
 "Use df['share'] = df['sales'] / df.groupby('category')['sales'].transform('sum'). Transform returns the group total aligned to each row, so division is vectorized.",
 ["transform('sum')", "Vectorized division", "Aligned to original rows"],
 ["Uses groupby().sum() and loops to merge"]),
("AGG", "debug", "medium", "debugging", [],
 "After grouping by 'channel', some rows with missing channel are absent from the totals. Why does this happen and how do you keep them?",
 "By default groupby drops rows whose key is NaN, so their values never appear in the totals. Pass dropna=False to groupby, or fill the key with an explicit label such as 'Unknown' beforehand.",
 ["NaN keys dropped by default", "dropna=False", "Or fill with a label"],
 ["Blames sum() for skipping NaN"]),
("AGG", "optimize", "medium", "optimization", [],
 "A groupby.apply with a Python lambda takes minutes on 20 million rows. How would you speed it up?",
 "apply runs Python code per group, which is slow. Replace it with built-in vectorized aggregations or named aggregation with agg, use transform with optimized methods, convert the group key to a categorical type, and only fall back to apply when logic cannot be expressed vectorized.",
 ["apply is Python-level per group", "Built-in agg and transform", "Categorical keys"],
 ["Suggests only adding more RAM"]),
("AGG", "implement", "medium", "implementation", [],
 "How do you compute several different aggregations on different columns and give the result readable column names?",
 "Use named aggregation: df.groupby('region').agg(total_sales=('sales', 'sum'), avg_price=('price', 'mean'), orders=('order_id', 'nunique')). Each keyword becomes an output column name.",
 ["Named aggregation", "Different functions per column", "Readable output names"],
 ["Runs separate groupby calls and concatenates"]),
("AGG", "scenario", "medium", "scenario", [],
 "A report needs a 7-day rolling revenue figure per store. How would you compute it in pandas?",
 "Sort by store and date, then use df.groupby('store')['revenue'].rolling(7).sum() or set a date index and use rolling('7D'). If days are missing, reindex to a complete calendar per store first so the window means seven calendar days.",
 ["Group by store", "Rolling window", "Handles missing dates"],
 ["Applies rolling to the whole table without grouping"]),

# ---------------- Variance ----------------
("VAR", "fundamentals", "easy", "concept", [],
 "What does variance measure, and why are its units hard to interpret?",
 "Variance is the average squared deviation from the mean and measures how spread out values are. Because deviations are squared, its units are the square of the data's units (dollars squared), which is why the standard deviation is often used for interpretation.",
 ["Average squared deviation", "Squared units"],
 ["Says variance is the average value"]),
("VAR", "explain", "easy", "concept", [],
 "Why do analysts usually report standard deviation rather than variance?",
 "Standard deviation is the square root of variance and is in the same units as the data, so it is easy to relate to the mean and to describe typical deviation.",
 ["Same units as data", "Square root of variance"],
 ["Says they are unrelated measures"]),
("VAR", "scenario", "easy", "scenario", [],
 "Two products both average 4.0 stars, but one has a standard deviation of 0.2 and the other 1.5. What do you conclude?",
 "The first product's ratings are consistently close to 4.0. The second has widely spread ratings, perhaps polarized between very high and very low, so the average alone hides important differences. Look at the distribution, not just the mean.",
 ["Same mean, different spread", "Consistency versus polarization", "Mean alone is misleading"],
 ["Concludes they are equally good"]),
("VAR", "explain", "easy", "concept", [],
 "Can variance be negative, and what does a variance of zero mean?",
 "Variance cannot be negative because it is an average of squared values. A variance of zero means all values are identical, so there is no variability.",
 ["Never negative", "Zero means identical values"],
 ["Says negative variance indicates a decrease"]),
("VAR", "explain", "easy", "concept", [],
 "How do variance and standard deviation change if you add 10 to every value, or multiply every value by 3?",
 "Adding a constant shifts all values and the mean equally, so variance and standard deviation do not change. Multiplying by 3 multiplies the standard deviation by 3 and the variance by 9.",
 ["Shift does not change spread", "Scaling multiplies SD by k and variance by k squared"],
 ["Says variance triples under multiplication"]),
("VAR", "explain", "medium", "concept", [],
 "Why does sample variance divide by n-1 rather than n?",
 "The sample mean is estimated from the same data and is closer to the sample points than the true mean, so dividing by n underestimates the population variance. Dividing by n-1 (Bessel's correction, the degrees of freedom) gives an unbiased estimator.",
 ["Sample mean estimated from data", "Underestimates with n", "Unbiased with n-1"],
 ["Says it is just a convention"]),
("VAR", "compare", "medium", "comparison", [],
 "When would you use the IQR or median absolute deviation instead of variance to describe spread?",
 "Variance squares deviations, so a few extreme values strongly inflate it and skewed data gives misleading spread. IQR and MAD depend on quantiles or the median, so they are robust to outliers and appropriate for skewed or heavy-tailed data.",
 ["Variance is sensitive to outliers", "IQR and MAD are robust", "Skewed or heavy-tailed data"],
 ["Says they always agree with variance"]),
("VAR", "debug", "medium", "debugging", ["Python"],
 "Pandas reports a standard deviation of 2.58 for a column, but NumPy gives 2.45 for the same values. Why?",
 "Pandas std uses ddof=1 (sample standard deviation) by default, while NumPy's np.std uses ddof=0 (population). Set ddof explicitly in both to compare them consistently.",
 ["ddof=1 versus ddof=0", "Specify ddof explicitly"],
 ["Blames floating-point rounding"]),
("VAR", "scenario", "medium", "scenario", [],
 "You need to compare how variable delivery times (in minutes) are versus order values (in dollars). How do you do it fairly?",
 "Raw variances are in different units and scales, so they cannot be compared. Use the coefficient of variation (standard deviation divided by mean) or standardize both metrics so spreads are relative to their own scale.",
 ["Different units are not comparable", "Coefficient of variation", "Standardization"],
 ["Compares raw standard deviations directly"]),
("VAR", "diagnose", "medium", "debugging", ["Feature Analysis"],
 "A feature column in your dataset has a variance close to zero. What does that imply and what would you do?",
 "Nearly all rows share the same value, so the feature carries almost no information for distinguishing records. Verify it is not a data-loading issue, then usually drop it or keep it only if rare values are meaningful, for example a rare flag.",
 ["Almost constant", "Verify data issue", "Drop unless rare values matter"],
 ["Keeps it because it is harmless"]),

# ---------------- Chart Types (Tableau) ----------------
("CHT", "fundamentals", "easy", "concept", [],
 "When would you choose a line chart over a bar chart?",
 "Use a line chart for continuous or ordered data such as time series, where the slope and trend matter. Use bars to compare discrete categories where lengths show magnitude.",
 ["Line for trend over time", "Bars for categories"],
 ["Says they are interchangeable"]),
("CHT", "explain", "easy", "concept", [],
 "Why are pie charts discouraged when there are many categories?",
 "Humans compare angles and areas poorly, and many thin slices are hard to read and compare. A sorted bar chart shows values precisely and is easier to scan.",
 ["Poor comparison of angles", "Many slices unreadable", "Sorted bar as alternative"],
 ["Says pie charts are always best for composition"]),
("CHT", "implement", "easy", "implementation", [],
 "In Tableau, how do you build a scatter plot that shows the relationship between profit and sales for each customer?",
 "Place one measure (sales) on Columns and the other (profit) on Rows, and add the Customer dimension to Detail (or Marks) so each customer becomes a point. Aggregation must be disaggregated or customer level so points are not summed into one mark.",
 ["Two measures on axes", "Dimension on Detail", "Granularity is per customer"],
 ["Puts both measures on one axis"]),
("CHT", "compare", "easy", "comparison", [],
 "What is the difference between a histogram and a bar chart?",
 "A histogram shows the distribution of a continuous variable by grouping it into numeric bins, with bars touching to show a continuous range. A bar chart compares values across discrete categories, with gaps between bars.",
 ["Histogram bins continuous data", "Bar chart is categorical"],
 ["Says only the colour differs"]),
("CHT", "explain", "easy", "concept", [],
 "What kind of problem does a dual-axis chart solve, and what is one risk of using it?",
 "It overlays two measures with different scales, such as revenue (bars) and margin percent (line), on one chart sharing an x-axis. The risk is that unsynchronized or arbitrary axis scales can imply false correlations or exaggerate relationships.",
 ["Two measures with different scales", "Risk of misleading scale"],
 ["Says it is for plotting two dimensions"]),
("CHT", "scenario", "medium", "scenario", [],
 "A manager wants to compare three KPIs against their targets in a compact view. What chart would you choose in Tableau and why?",
 "A bullet chart: a bar shows the actual value against a reference line for the target, with shaded bands for performance ranges. It is compact and more precise than gauges or pie charts.",
 ["Bullet chart", "Actual versus target reference line", "Compact and precise versus gauges"],
 ["Picks a pie chart"]),
("CHT", "tradeoff", "medium", "tradeoff", [],
 "How do you decide between stacked bars and grouped (side-by-side) bars?",
 "Stacked bars show the total and the composition but only the bottom segment shares a baseline, making comparison of other segments difficult. Grouped bars share a baseline so individual values compare easily but totals are harder to read. Choose stacked for part-to-whole, grouped for comparing categories.",
 ["Stacked shows totals", "Common baseline for grouped", "Matches choice to the question"],
 ["Says stacked bars are always clearer"]),
("CHT", "debug", "medium", "debugging", [],
 "In Tableau, your line chart over order dates appears as separate dots or headers instead of a continuous line. What is the likely cause?",
 "The date field is set as a discrete (blue) date part rather than a continuous (green) date, so Tableau draws separate headers or points per value. Change it to continuous (or choose the correct date level) so the line connects across time.",
 ["Discrete versus continuous date", "Switch pill to continuous", "Correct date level"],
 ["Blames the data source connection"]),
("CHT", "scenario", "medium", "scenario", [],
 "You need to show the salary distribution per department, including its outliers. Which chart types would you consider?",
 "A box plot per department compactly shows median, quartiles and outliers across groups. A histogram or density plot per department shows the shape in more detail but takes more space, and a violin plot adds shape to the summary. Choose box plots for comparing many groups.",
 ["Box plot for comparison", "Histogram or violin for shape", "Consider number of groups"],
 ["Uses a bar chart of averages"]),
("CHT", "tradeoff", "medium", "tradeoff", [],
 "When is it acceptable to truncate the y-axis so it does not start at zero?",
 "For bar charts the length encodes value, so a truncated axis distorts proportions and should be avoided. For line charts, where trend and change matter, a non-zero baseline is acceptable if clearly labelled. Always label the axis so the viewer is not misled.",
 ["Bars should start at zero", "Lines can use non-zero baselines", "Label the axis"],
 ["Says truncating is always fine"]),
]
