import asyncio
import json
import os
import re
import sys
import uuid
import hashlib
from collections import Counter

from dotenv import load_dotenv
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
load_dotenv()

BACKEND_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_DIR = os.path.join(BACKEND_DIR, "data")
OUT = os.path.join(DATA_DIR, "interview_question_bank_v2_generated.jsonl")

ROLE = "Frontend Developer"
LEAK = re.compile(r"(generate a question|generate \d+ questions|return only json|phase 4c gap plan|"
                  r"generation batch|candidate generation|system prompts|do not proceed|"
                  r"awaiting authorization|minimum target|generation pipeline|"
                  r"batch \d+ generation|expected answer|strong indicator|weak indicator|as an ai|"
                  r"here is the question|\bprompt text\b)", re.I)

Q = [
    # Area 1: React Server Components, SSR, Hydration, Suspense
    ("B54_1", "concept", "hard", "concept", ["React Architecture", "SSR"], "What is the fundamental architectural difference between Server-Side Rendering (SSR) and React Server Components (RSC)?", "SSR renders the entire application to an HTML string on the server, but still sends all the associated JavaScript to the client to 'hydrate' the page (attaching event listeners to make it interactive). React Server Components execute exclusively on the server and never send their own JavaScript to the client. They stream serialized UI UI fragments directly to the browser. This drastically reduces the client-side JavaScript bundle size because heavy dependencies (like markdown parsers or database drivers) used inside an RSC remain entirely on the server.", ["SSR sends full JS bundle for hydration on the client", "RSC never sends its component JS to the client", "RSC reduces client bundle size by keeping heavy dependencies on the server"], ["SSR is for databases, RSC is for HTML"]),
    ("B54_1", "diagnose", "medium", "debugging", ["React Architecture", "SSR"], "You implement Server-Side Rendering (SSR) in a Next.js application. Users report that when they load a specific page, they see the correct data for a split second, but it instantly flashes back to a loading spinner or empty data. What is causing this?", "This is a classic 'Hydration Mismatch'. The server rendered the HTML with data, but the initial client-side React render (hydration) did not have that data in its initial state (e.g., the client-side state defaulted to `isLoading: true` or `null`). When React hydrates the DOM, it detects that the client-side virtual DOM differs from the server-rendered HTML. It destroys the server HTML and replaces it with the empty client state, causing the flash.", ["Hydration Mismatch between Server HTML and Client State", "Client initial state defaulted to empty/loading", "React destroys the server HTML and replaces it with the empty client state"], ["The CSS file loaded too slowly"]),
    ("B54_1", "explain", "medium", "concept", ["React Architecture"], "How does React 18's Streaming SSR combined with `<Suspense>` fundamentally improve the Time To Interactive (TTI) compared to traditional SSR?", "Traditional SSR is entirely blocking: the server must fetch all data for the entire page, render the full HTML, send it, and the client must download and hydrate the entire page before anything is interactive ('All-or-Nothing' waterfall). Streaming SSR with Suspense allows the server to send the HTML for the fast parts of the page immediately (like the Navbar), while rendering a fallback for the slow parts. As data arrives, the server streams the remaining HTML chunks over the same connection, and React selectively hydrates them, allowing users to interact with the fast parts immediately.", ["Traditional SSR is blocking and 'All-or-Nothing'", "Streaming SSR sends HTML for fast components immediately", "Suspense boundaries allow React to selectively hydrate chunks as they stream in"], ["Suspense pauses the internet connection"]),
    ("B54_1", "architecture", "hard", "architecture", ["React Architecture", "SSR"], "In a React application using React Server Components (RSC), can a Server Component import and render a Client Component? Can a Client Component import and render a Server Component?", "A Server Component CAN import and render a Client Component (this is how you add interactivity to a server-rendered page). However, a Client Component CANNOT directly import a Server Component, because a Client Component runs in the browser, which has no mechanism to execute server-side code. If a Client Component needs to wrap a Server Component, it must do so via composition: the Server Component must be passed down to the Client Component as the `children` prop.", ["Server Components CAN import Client Components", "Client Components CANNOT directly import Server Components", "Client Components must receive Server Components via the `children` prop (composition)"], ["Both can import each other freely"]),
    ("B54_1", "tradeoff", "hard", "tradeoff", ["React Architecture", "SSR"], "What is the primary architectural tradeoff between using Static Site Generation (SSG) with Incremental Static Regeneration (ISR) versus using Edge-based Server-Side Rendering (Edge SSR)?", "SSG/ISR builds pages at compile time (or periodically in the background). It provides ultra-low latency because pages are served directly from the CDN cache, but the data can be slightly stale (e.g., a 60-second cache window). Edge SSR executes the rendering logic dynamically on CDN edge nodes (like Cloudflare Workers) for every single request. Edge SSR guarantees 100% real-time, personalized data for every user with zero staleness, but it incurs compute latency on every request and cannot rely purely on static file caching.", ["SSG/ISR provides maximum CDN cache speed but allows temporary data staleness", "Edge SSR provides real-time personalized data but incurs compute latency per request", "Edge SSR cannot rely on static file caching"], ["SSG requires PHP"]),
    ("B54_1", "implement", "medium", "implement", ["React Architecture"], "How do you securely pass sensitive data (like an API key or database string) to a React Server Component without accidentally exposing it to the client bundle?", "Because Server Components never send their JavaScript to the client, you can simply use standard Node.js environment variables (e.g., `process.env.DB_PASSWORD`) directly inside the Server Component file. As long as you do not pass that sensitive variable as a prop to a imported Client Component, it is completely secure and will never leak into the browser's JavaScript bundle.", ["Access environment variables directly in the Server Component", "Because RSC code is never shipped to the client, the variable is secure", "Ensure the sensitive data is not passed as a prop to a Client Component"], ["You must encrypt it using window.crypto"]),
    ("B54_1", "scenario", "medium", "scenario", ["React Architecture"], "You wrap an expensive client-side charting library in `React.lazy()` and `<Suspense>`. When the user navigates to the dashboard, they stare at a blank screen for 2 seconds before the chart appears. How do you prevent this layout shift while still code-splitting?", "You must provide a `fallback` UI to the `<Suspense>` boundary. Without a fallback, Suspense renders nothing (blank screen) while the lazy chunk is downloading. By providing a Skeleton loader or a static placeholder (`<Suspense fallback={<ChartSkeleton />}>`), you maintain the layout structure, provide visual feedback to the user that the chart is loading, and prevent massive Cumulative Layout Shifts (CLS) when the chart finally renders.", ["Provide a `fallback` UI to the Suspense boundary", "Use a Skeleton loader or placeholder component", "Prevents blank screens and Cumulative Layout Shift (CLS)"], ["Turn off the WiFi"]),
    ("B54_1", "diagnose", "hard", "debugging", ["React Architecture"], "A developer complains that their `useContext` hook is throwing an error inside a new React Component. Upon inspection, the component file has the `\"use server\"` directive at the top. Why does this fail?", "The `\"use server\"` directive explicitly marks the file for Server Actions or Server Components. React Context (`useContext`), along with state (`useState`) and effects (`useEffect`), are exclusively Client-Side APIs because they rely on the browser's memory and lifecycle to maintain state between re-renders. A Server Component executes once on the server to generate HTML/RSC payload and has no concept of ongoing browser state. Therefore, React explicitly bans using Context inside Server Components.", ["`\"use server\"` marks the code to execute on the server", "Context, State, and Effects are exclusively Client-Side APIs", "Server Components run once and have no ongoing browser state/lifecycle"], ["The useContext import is spelled wrong"]),
    ("B54_1", "concept", "medium", "concept", ["React Architecture"], "In modern React, what is the 'Waterall' data fetching problem, and how do Server Components solve it?", "A Waterfall occurs when Component A fetches data, renders Component B, which then fetches its own data, forcing sequential network requests from the client to the server (adding huge round-trip latency). Server Components solve this because they execute entirely on the backend, co-located with the database. The 'waterfall' still happens, but the requests take 1 millisecond across a local data center network, rather than 100 milliseconds across the public internet, drastically speeding up the overall render.", ["Waterfall: Sequential data fetching where B waits for A to finish", "Server Components execute on the backend co-located with the DB", "Reduces latency of sequential fetches from 100ms (internet) to 1ms (datacenter)"], ["Waterfall is when CSS cascades too far"]),
    ("B54_1", "tradeoff", "medium", "tradeoff", ["React Architecture", "SSR"], "What is the tradeoff of using standard Client-Side Rendering (CSR, e.g., Create React App) for an e-commerce storefront?", "The main advantage of CSR is easy hosting (just static files on an S3 bucket) and fast subsequent navigation via the client router. The severe tradeoff is abysmal SEO and poor initial load performance (LCP). The browser downloads an almost empty HTML file (`<div id='root'></div>`), waits to download a massive JS bundle, parses it, and executes it before the user sees any products. Search engine crawlers may fail to index the dynamic content, devastating organic traffic.", ["Advantage: Cheap static hosting and fast subsequent client-side routing", "Tradeoff: Abysmal SEO because crawlers see an empty HTML file", "Tradeoff: Poor Largest Contentful Paint (LCP) due to heavy JS parsing before render"], ["CSR uses more battery power than SSR"]),

    # Area 2: Build Optimization, Code Splitting, Tree Shaking
    ("B54_2", "concept", "medium", "concept", ["Build Optimization"], "Explain 'Tree Shaking' in modern JavaScript bundlers (like Webpack or Rollup). What specific syntax is required for it to work?", "Tree Shaking is the process of dead-code elimination. The bundler analyzes the dependency graph and removes any exported functions or modules that are never actually imported or used by the application, drastically reducing the final bundle size. For Tree Shaking to work, the code MUST use static ES6 module syntax (`import` and `export`). It does not work with dynamic CommonJS `require()` syntax because CommonJS imports can be executed conditionally at runtime, making static analysis impossible.", ["Process of dead-code elimination by the bundler", "Removes unused exports from the final bundle", "Strictly requires static ES6 modules (`import`/`export`), fails on CommonJS (`require`)"], ["It shakes the DOM tree to remove unused HTML nodes"]),
    ("B54_2", "diagnose", "hard", "debugging", ["Build Optimization"], "You import a single utility function `import { capitalize } from 'lodash';`. However, your Webpack bundle analyzer shows that the entire 70KB lodash library is included in the production build. Tree shaking failed. Why?", "The standard `lodash` library is published as a CommonJS module (using `module.exports`), which cannot be statically analyzed for tree shaking. Even though you used ES6 import syntax in your file, Webpack bails out when it sees the underlying CommonJS library. To fix this, you must either use the ES6 version of lodash (`lodash-es`), or use path-specific imports (`import capitalize from 'lodash/capitalize'`), or use a Babel plugin to rewrite the imports.", ["Standard `lodash` is published as CommonJS, which defeats tree shaking", "Bundler includes the entire library because it cannot statically analyze CommonJS", "Fix: Use `lodash-es` or path-specific imports"], ["You forgot to press save"]),
    ("B54_2", "architecture", "medium", "architecture", ["Build Optimization"], "What is the architectural difference between 'Route-based Code Splitting' and 'Component-based Code Splitting'?", "Route-based code splitting chunks the JavaScript bundle at the page/router level (e.g., the code for the `/dashboard` route is only downloaded when the user navigates there). This is the standard, high-impact optimization. Component-based code splitting chunks individual heavy components *within* a route (e.g., lazy-loading a 500KB PDF Viewer or Charting library only when the user clicks a button to open a modal). Both use dynamic `import()` to generate separate webpack chunks.", ["Route-based: Chunks code by page/URL to minimize initial load", "Component-based: Chunks heavy specific UI elements (modals, charts) within a page", "Both rely on dynamic `import()` statements"], ["Route-based uses CSS, Component-based uses JS"]),
    ("B54_2", "implement", "medium", "implement", ["Build Optimization"], "How do you configure a modern bundler to implement 'Vendor Splitting' (Chunking), and why is it crucial for browser caching?", "Vendor splitting separates third-party `node_modules` (like React, ReactDOM, or Lodash) into a distinct `vendor.[hash].js` chunk, while the application code goes into `main.[hash].js`. It is crucial because vendor libraries change very rarely, whereas application code changes on every deployment. By separating them, returning users can load the massive vendor bundle instantly from their local browser cache, and only need to download the small, updated application chunk.", ["Separates `node_modules` into a distinct vendor chunk", "Third-party libraries change rarely compared to app code", "Maximizes long-term browser caching across deployments"], ["Vendor splitting prevents hackers from seeing the code"]),
    ("B54_2", "tradeoff", "hard", "tradeoff", ["Build Optimization"], "What is the tradeoff of aggressive code splitting (breaking an app into 200 tiny 5KB chunks) versus moderate code splitting (5 chunks of 200KB)?", "While HTTP/2 multiplexing allows downloading multiple files simultaneously without head-of-line blocking, 200 tiny chunks introduce severe overhead. The browser must parse 200 separate HTTP headers, decompress 200 separate GZIP streams (which ruins compression ratios, as GZIP works best on large text blocks), and the bundler must inject heavy runtime orchestration code to manage all the chunks. Moderate splitting strikes the balance between caching efficiency and compression/parsing overhead.", ["Tiny chunks ruin GZIP/Brotli compression ratios", "Introduces massive HTTP header parsing overhead despite HTTP/2 multiplexing", "Bundler injects heavy runtime orchestration code"], ["Tiny chunks use too much CSS"]),
    ("B54_2", "concept", "easy", "concept", ["Build Optimization"], "In the context of frontend build tools, what is 'Minification'?", "Minification is the process of removing all unnecessary characters from source code without changing its functionality. It strips out whitespace, newlines, comments, and shortens (mangles) variable and function names (e.g., renaming `calculateTotalAmount` to `a`). This drastically reduces the file size of the JavaScript and CSS sent over the network.", ["Removes whitespace, comments, and newlines", "Mangles (shortens) variable and function names", "Drastically reduces file size for network transfer"], ["It makes the code physically smaller on the screen"]),
    ("B54_2", "explain", "medium", "explain", ["Build Optimization"], "Why do modern build tools like Vite start up a development server in 100 milliseconds, whereas Webpack can take 30 seconds for the same large codebase?", "Webpack is a bundler; during development, it must crawl the entire dependency graph, transpile all files, and build the entire bundle in memory before the dev server can start. Vite is a 'no-bundle' dev server. It leverages native browser ES Modules (`<script type='module'>`). Vite only starts a lightweight server and transforms files exactly when the browser requests them on-demand. If you navigate to page A, it only compiles page A's code, resulting in near-instant startup times.", ["Webpack bundles the entire app in memory before starting", "Vite uses native browser ES Modules (no-bundle approach)", "Vite transforms/compiles files on-demand exactly when the browser requests them"], ["Vite is written in Python, Webpack in Java"]),
    ("B54_2", "diagnose", "hard", "debugging", ["Build Optimization"], "You write a library and set `\"sideEffects\": false` in your `package.json` to help bundlers tree-shake it. A downstream user imports your library and complains that their global CSS file is entirely missing in production. Why?", "The `\"sideEffects\": false` flag tells Webpack that importing a file from this library does not cause any hidden global mutations. When the user writes `import 'styles.css';`, Webpack sees that the CSS file doesn't export any JavaScript variables. Believing the file has no side effects (due to the flag), Webpack's tree-shaker aggressively deletes the CSS import entirely. To fix this, you must specify an array: `\"sideEffects\": [\"*.css\"]`.", ["`\"sideEffects\": false` tells the bundler it is safe to drop unused imports", "CSS imports (`import 'styles.css'`) don't export JS variables", "Bundler aggressively drops the CSS; fix by adding `*.css` to the sideEffects array"], ["CSS cannot have side effects, only JS can"]),
    ("B54_2", "architecture", "hard", "architecture", ["Build Optimization", "Micro-Frontends"], "Explain how Webpack 'Module Federation' works and what architectural pattern it enables.", "Module Federation allows multiple separate Webpack builds to dynamically load code from each other at runtime. Unlike NPM packages (which are compiled at build time), Federation allows Application A (running on port 3000) to import a React Component directly from Application B (running on port 3001) over the network. This is the foundational technology for modern Micro-Frontends, allowing independent teams to deploy individual UI features without forcing the host application to rebuild or redeploy.", ["Allows separate Webpack builds to share code dynamically at runtime", "Code is loaded over the network in the browser, not compiled at build time", "Enables Micro-Frontend architectures and independent team deployments"], ["It federates the database across multiple clusters"]),
    ("B54_2", "scenario", "medium", "scenario", ["Build Optimization"], "You are inspecting a production React app and notice a massive 2MB `source-map` file being downloaded by the browser. Should source maps be deployed to production, and do they slow down the user's experience?", "Source maps (`.map` files) should generally not be publicly exposed in production because they leak your original, unminified source code to anyone. However, they do NOT slow down the user's experience. Browsers only download source map files if the Developer Tools (F12) are currently open. Standard users never download them. The correct approach is to generate them for error tracking (like Sentry) but host them privately, not on the public CDN.", ["Browsers only download source maps if DevTools are open; no performance hit for users", "Public source maps leak unminified source code/intellectual property", "Should be generated but kept private (e.g., uploaded directly to error trackers)"], ["Source maps make the website render slower"]),

    # Area 3: Advanced TypeScript (Generics, Type Guards, Conditional)
    ("B54_3", "concept", "medium", "concept", ["TypeScript"], "In TypeScript, what is the difference between an `any` type and an `unknown` type?", "`any` completely disables the TypeScript type checker for that variable; you can call non-existent methods on it, and TS will not complain, leading to runtime crashes. `unknown` is a type-safe counterpart. You can assign anything to `unknown`, but TypeScript strictly forbids you from interacting with it (calling methods, accessing properties) until you explicitly write a type check (Type Guard) to narrow it down to a specific type.", ["`any` disables type checking entirely, allowing unsafe operations", "`unknown` is type-safe; requires explicit narrowing before use", "Always prefer `unknown` over `any` for unknown data payloads"], ["`unknown` is only for Promises"]),
    ("B54_3", "implement", "medium", "implement", ["TypeScript"], "How do you write a Custom Type Guard function in TypeScript to safely narrow an `unknown` variable to a specific interface?", "You write a function that returns a boolean, and you annotate the return type using a Type Predicate: `variable is Type`. For example: `def isUser(data: any): data is User { return data && typeof data.id === 'number'; }`. When you use this function inside an `if (isUser(payload))` block, the TypeScript compiler automatically narrows the type of `payload` to `User` inside that block.", ["Write a function returning a boolean", "Annotate the return type with a Type Predicate: `arg is SpecificType`", "TS compiler automatically narrows the type inside conditional blocks using this function"], ["Use the `cast` keyword"]),
    ("B54_3", "architecture", "hard", "architecture", ["TypeScript"], "Explain how Conditional Types work in TypeScript using the `extends` keyword.", "Conditional Types allow you to choose a type based on a condition, using a syntax similar to ternary operators: `T extends U ? X : Y`. This means 'if type T is assignable to type U, resolve to type X, otherwise resolve to type Y'. It allows building highly dynamic utility types, like extracting the return type of a function or filtering out specific types from a union (e.g., `Exclude<T, U>`).", ["Uses ternary-like syntax: `T extends U ? X : Y`", "Checks if T is assignable to U at the type level", "Used to build dynamic, logical utility types (like Exclude or ReturnType)"], ["It conditionally imports files based on the OS"]),
    ("B54_3", "diagnose", "medium", "debugging", ["TypeScript"], "A developer writes `const API_URL = 'https://api.com';`. Later, a function strictly requires the literal type `'https://api.com'`, but passing `API_URL` causes a TypeScript error saying `string is not assignable to 'https://api.com'`. Why?", "By default, TypeScript infers the type of `const API_URL = '...'` as the exact literal type. Wait, no! For strings declared with `const`, TS *does* infer the literal type. But if it was declared in an object `const config = { url: 'https://api.com' }`, TS infers `url` as a generic `string` because object properties are mutable. To fix object property widening, the developer must append `as const` to the object declaration: `const config = { url: '...' } as const;`, which freezes all properties to their exact literal types.", ["Object properties are inferred as generic `string` because they are mutable", "Appending `as const` creates a readonly, deeply literal type", "Prevents type widening from literal to generic string"], ["TypeScript doesn't support URLs"]),
    ("B54_3", "tradeoff", "hard", "tradeoff", ["TypeScript"], "What is the tradeoff of using TypeScript `enum`s versus using String Literal Unions (`type Status = 'open' | 'closed'`)?", "String Literal Unions compile to absolutely nothing in JavaScript (zero runtime overhead) and are idiomatic React. TypeScript `enum`s (unless declared as `const enum`) actually generate an Immediately Invoked Function Expression (IIFE) and a lookup object in the compiled JavaScript bundle, adding runtime overhead. Furthermore, `enum`s do not safely interoperate with raw strings (you must explicitly cast or access `Status.Open`), whereas literal unions seamlessly accept the raw string value.", ["Unions have zero runtime overhead (removed entirely during compilation)", "Enums generate actual JS objects/IIFEs, adding bundle size", "Enums require rigid object access, Unions accept raw string values seamlessly"], ["Enums are faster than strings in V8"]),
    ("B54_3", "scenario", "medium", "scenario", ["TypeScript"], "You have an interface `User { id: number; name: string; age: number; }`. You need to pass this object to an update API, where all fields are optional except `id`. How do you construct this type without rewriting the interface?", "You combine two TypeScript Utility Types: `Pick` and `Partial`. You can define the update payload as: `type UpdatePayload = Pick<User, 'id'> & Partial<Omit<User, 'id'>>;`. This creates an intersection type where `id` is strictly required, but all other fields from the `User` interface are completely optional.", ["Use Utility Types rather than rewriting interfaces manually", "Use `Pick` to enforce the required fields", "Use `Partial` (and optionally `Omit`) to make the remaining fields optional"], ["Just set the type to `any` for updates"]),
    ("B54_3", "explain", "hard", "explain", ["TypeScript"], "What is 'Mapped Types' in TypeScript, and how does the `readonly` modifier interact with it?", "A Mapped Type iterates over the keys of an existing type to create a new type. For example: `type ReadOnlyUser = { readonly [K in keyof User]: User[K] }`. This loops over every key in the `User` interface and applies the `readonly` modifier to it. You can also *remove* modifiers during mapping by prefixing them with a minus sign (e.g., `-readonly` or `-?` to remove optionality).", ["Iterates over keys of an existing type using `[K in keyof T]`", "Allows transforming every property of a type programmatically", "Can add or remove modifiers (like `readonly` or `?`) using `+` or `-` syntax"], ["It maps JSON data to Google Maps"]),
    ("B54_3", "concept", "easy", "concept", ["TypeScript"], "What does the `Record<K, V>` utility type do in TypeScript?", "It is a concise way to define an object type used as a dictionary or hash map. `K` defines the type of the keys (usually `string`, `number`, or a literal union), and `V` defines the type of the values. For example, `Record<string, User>` defines an object where all keys are strings and all values are `User` objects.", ["Defines an object used as a dictionary/hash map", "`K` defines the key types, `V` defines the value types", "Example: `Record<string, number>`"], ["It records audio using the Web Audio API"]),
    ("B54_3", "diagnose", "medium", "debugging", ["TypeScript"], "A developer writes a generic function `function getLen<T>(arg: T): number { return arg.length; }`. TypeScript throws an error on `arg.length`. Why, and how do you fix it?", "TypeScript throws an error because the generic `T` could be absolutely anything, including a `number` or a `boolean`, which do not have a `.length` property. To fix this, you must constrain the generic type using the `extends` keyword. You create an interface with a length property and constrain `T`: `function getLen<T extends { length: number }>(arg: T): number`.", ["Generic `T` is unbounded and might not have a `.length` property", "Must constrain the generic type using `extends`", "Fix: `<T extends { length: number }>`"], ["The compiler is broken"]),
    ("B54_3", "architecture", "hard", "architecture", ["TypeScript"], "In advanced TypeScript, what is a 'Discriminated Union' (Tagged Union) and why is it crucial for Redux-style state reducers?", "A Discriminated Union is a union of multiple interfaces that all share a single, common literal property (the 'discriminant' or 'tag', like `type: 'FETCH_SUCCESS'`). When you write a `switch` statement checking that exact `type` property, TypeScript acts as a Type Guard. Inside the `case 'FETCH_SUCCESS':` block, TS statically guarantees that the action object contains a `payload` property, completely eliminating the possibility of accessing properties belonging to a different action type.", ["Union of interfaces sharing a common literal property (e.g., `type`)", "Switching on the discriminant acts as an automatic Type Guard", "Crucial for Redux reducers to strictly narrow the action payload types safely"], ["It discriminates against older browsers"]),

    # Area 4: State Management Architecture & React Concurrent Rendering
    ("B54_4", "concept", "hard", "concept", ["State Management", "React Architecture"], "Explain the concept of 'Tearing' in React Concurrent Rendering, and how the `useSyncExternalStore` hook prevents it.", "In React 18 Concurrent Mode, rendering can be paused and yielded to the browser. 'Tearing' occurs when an external state manager (like Redux) updates its global state *while* React is paused mid-render. When React resumes, half the UI renders with the old state and half with the new state, causing visual tearing. `useSyncExternalStore` forces React to opt out of concurrent time-slicing for that specific store read, reading the external state synchronously to guarantee UI consistency.", ["Tearing: Half the UI rendering with old state, half with new state during a concurrent pause", "Caused by external state stores mutating during an interrupted React render", "`useSyncExternalStore` reads the state synchronously, preventing tearing"], ["Tearing is when the CSS breaks on mobile screens"]),
    ("B54_4", "architecture", "medium", "architecture", ["State Management"], "What is the architectural difference between 'Bottom-Up' (Atomic) state management (like Jotai/Recoil) and 'Top-Down' state management (like Redux)?", "Top-Down (Redux) uses a single, massive global object tree. Components subscribe to slices of this tree using selectors. It is great for predictable, traceable state but can cause heavy re-renders if selectors aren't memoized properly. Bottom-Up (Atomic) state builds state from tiny, independent primitives called 'Atoms'. Components subscribe only to specific Atoms. When an Atom updates, only the explicitly subscribed components re-render, eliminating the need for complex selectors and drastically improving performance for highly dynamic UIs.", ["Top-Down (Redux): Single global state tree, relies on selectors", "Bottom-Up (Jotai/Recoil): Independent primitive 'Atoms'", "Atoms provide surgical re-renders without complex selector memoization"], ["Bottom-up means styling the footer first"]),
    ("B54_4", "diagnose", "medium", "debugging", ["React Architecture"], "You use React 18's `startTransition`. You wrap a state update `setQuery(text)` inside it. However, the input field typing still feels laggy and blocked. Why didn't `startTransition` make it smooth?", "You likely wrapped the *controlled input state* (the exact state driving the `<input value={text} />`) inside `startTransition`. Transitions tell React 'this update is low priority'. If you make the input's value update low priority, React will delay updating the text box while it renders other things, causing input lag. You must keep the input state update high-priority (synchronous), and only wrap the heavy *secondary* state update (e.g., fetching search results) in `startTransition`.", ["`startTransition` marks an update as low priority/interruptible", "Wrapping the controlled input state delays the keystroke rendering, causing lag", "Only heavy/secondary UI updates should be wrapped in transitions"], ["Transitions only work in CSS"]),
    ("B54_4", "tradeoff", "hard", "tradeoff", ["State Management"], "What is the tradeoff of using React Context for Global State Management versus using a dedicated library like Zustand or Redux?", "React Context is built-in and great for dependency injection (theme, auth state). The severe tradeoff is performance: whenever the Context value changes, *every single component* consuming that context will unconditionally re-render, even if they only needed a tiny slice of the data. Dedicated libraries (Zustand/Redux) implement fine-grained subscriptions outside the React tree; they can update a specific component without triggering re-renders across the entire application.", ["Context forces a re-render of ALL consumers when any part of the value changes", "Context lacks fine-grained selector subscriptions", "Dedicated libraries update components selectively, vastly improving performance"], ["Context costs money to use"]),
    ("B54_4", "scenario", "medium", "scenario", ["React Architecture"], "A component fetches data in `useEffect`. If the user clicks 'Next Page' rapidly 5 times, the component fires 5 API requests. Due to network latency, Request 2 finishes *after* Request 5, overwriting the UI with stale data (a Race Condition). How do you fix this in `useEffect`?", "You must implement an Abort mechanism or a boolean flag inside the `useEffect` cleanup function. When the effect runs, define `let isActive = true`. When the API call finishes, check `if (isActive) { setState(data) }`. When the user clicks 'Next Page' and the component re-renders (or unmounts), the `useEffect` cleanup function fires, setting `isActive = false` for the previous closure, effectively ignoring the stale network response.", ["Implement an active flag or `AbortController` inside the effect", "The `useEffect` cleanup function fires on re-render, setting the flag to false", "Prevents stale async responses from overwriting newer state"], ["Use a setTimeout to delay the clicks"]),
    ("B54_4", "concept", "easy", "concept", ["React Architecture"], "In React, what is 'Prop Drilling' and why is it considered an anti-pattern?", "Prop Drilling occurs when you pass data through many layers of intermediate components that do not need the data themselves, purely to get it to a deeply nested child component. It clutters the intermediate components, makes refactoring difficult, and tightly couples the component tree. It is typically resolved using React Context, State Management libraries, or Component Composition.", ["Passing props through intermediate components that don't need them", "Clutters code and makes refactoring difficult", "Resolved via Context, Redux, or Component Composition"], ["It means using a power drill on the server"]),
    ("B54_4", "implement", "medium", "implement", ["State Management"], "How do you implement optimistic UI updates using a modern data-fetching library like React Query or SWR?", "When a user performs an action (like 'Like Post'), you intercept the mutation. Before the API request even hits the network, you manually overwrite the cache for that specific query with the predicted new state (e.g., `likes + 1`). This causes the UI to update instantly. If the API request subsequently fails, the mutation's `onError` callback rolls back the cache to the previous state.", ["Manually overwrite the local cache before the network request finishes", "UI updates instantly, providing a fast user experience", "Rollback the cache in the `onError` callback if the API fails"], ["You wrap the UI in a try-catch block"]),
    ("B54_4", "explain", "hard", "explain", ["React Architecture"], "Explain how React's virtual DOM reconciliation algorithm (Fiber) handles lists of elements, and why the `key` prop is critical for performance.", "When React reconciles a list, it compares the old virtual DOM children with the new children. Without `key`s, React iterates blindly from top to bottom. If you insert a new item at the top of the list, React thinks every single existing item has changed and mutates the entire DOM. The `key` prop gives each item a stable identity. React uses the keys to realize that the existing items merely shifted positions, drastically optimizing the DOM update to a single insertion.", ["Without keys, React compares lists blindly by index order", "Inserting at the top forces React to mutate every subsequent DOM node", "Keys provide stable identity, allowing React to optimize by just moving existing nodes"], ["Keys encrypt the data in the browser"]),
    ("B54_4", "architecture", "medium", "architecture", ["State Management"], "What is the 'Flux' architecture pattern, and how does it enforce unidirectional data flow?", "Flux is a design pattern separating application state into three distinct parts: the Store, the Dispatcher, and Views. The flow is strictly unidirectional: Views (React components) cannot mutate the Store directly. Instead, Views trigger Actions, which are sent to the central Dispatcher. The Dispatcher processes the Actions and updates the Store. The Store then emits a change event, causing the Views to re-render. This eliminates cascading updates and tangled two-way data binding.", ["Separates state into Store, Dispatcher, and Views", "Views trigger Actions -> Dispatcher -> Store -> Views (Strictly Unidirectional)", "Eliminates complex two-way data binding and cascading updates"], ["Flux uses a flux capacitor to time travel"]),
    ("B54_4", "tradeoff", "hard", "tradeoff", ["React Architecture"], "What is the tradeoff of using `useMemo` and `useCallback` extensively on every single function and variable in a React component?", "Memoization is not free. Calling `useMemo` forces React to allocate memory to store the previous values, the previous dependency arrays, and execute a shallow equality check on every render. If the calculation being memoized is trivial (e.g., mapping a small array), the overhead of the `useMemo` hook itself is actually slower than just recalculating the array. Over-memoization clutters code, consumes excess memory, and degrades performance. It should only be used for genuinely expensive computations or preserving referential equality for `React.memo` children.", ["Memoization has CPU and Memory overhead (storing old values, checking dependencies)", "For trivial calculations, `useMemo` is slower than recalculating", "Only use for expensive operations or preserving referential equality"], ["It makes the code compile to WebAssembly"]),

    # Area 5: Modern Frontend Security (CSP, XSS, Trusted Types)
    ("B54_5", "concept", "medium", "concept", ["Web Security"], "What is a Content Security Policy (CSP), and how does it prevent Cross-Site Scripting (XSS)?", "A CSP is an HTTP response header (e.g., `Content-Security-Policy: default-src 'self'`) that acts as a strict whitelist for the browser. It tells the browser exactly which domains are allowed to load scripts, images, or stylesheets. Even if an attacker successfully injects a malicious `<script src=\"http://evil.com/xss.js\">` into the HTML (XSS), the browser will actively block the execution because `evil.com` is not on the CSP whitelist.", ["HTTP header defining a strict whitelist of allowed resource domains", "Prevents XSS by instructing the browser to block unauthorized external scripts", "Also prevents inline `<script>` execution unless explicitly allowed"], ["It encrypts the HTML using AES-256"]),
    ("B54_5", "diagnose", "hard", "debugging", ["Web Security"], "You implement a strict CSP that bans `unsafe-inline`. Suddenly, your modern React application completely crashes, and Webpack fails to inject styles. Why?", "Modern bundlers (like Webpack's `style-loader` or Styled Components) often inject CSS dynamically by creating `<style>` tags directly inside the DOM at runtime. A strict CSP banning `unsafe-inline` explicitly blocks all dynamically generated inline styles and scripts. To fix this, you must either extract all CSS into a separate `.css` file during the build process using a plugin (like `MiniCssExtractPlugin`), or configure the bundler to generate and attach cryptographic nonces to the dynamically generated style tags.", ["Bundlers/CSS-in-JS inject `<style>` tags dynamically at runtime", "Strict CSP bans inline styles, crashing the application", "Fix by extracting CSS to static files or using cryptographic nonces"], ["The CSP deleted the internet connection"]),
    ("B54_5", "architecture", "hard", "architecture", ["Web Security"], "Explain the emerging web security standard 'Trusted Types' and how it fundamentally eliminates DOM-based XSS.", "DOM XSS occurs when untrusted strings are passed directly to dangerous browser sink APIs (like `innerHTML` or `document.write`). Trusted Types force the browser to reject raw strings at these sinks. If a developer tries `element.innerHTML = \"<img src=x onerror=alert(1)>\"`, the browser throws a TypeError. The application MUST pass the string through a registered, auditable 'Policy' (which sanitizes the HTML, e.g., using DOMPurify) that converts the string into a secure `TrustedHTML` object before the browser will accept it.", ["Forces the browser to reject raw strings passed to dangerous sinks (like `innerHTML`)", "Requires strings to be processed by a registered sanitization Policy", "Converts strings to a `TrustedHTML` object, structurally eliminating DOM XSS"], ["It ensures types are correct using TypeScript"]),
    ("B54_5", "tradeoff", "medium", "tradeoff", ["Web Security"], "What is the tradeoff of storing JWT access tokens in `localStorage` versus `HttpOnly` Cookies?", "Storing a JWT in `localStorage` makes it incredibly easy for the JavaScript frontend (like Axios) to read the token and attach it to API headers. The catastrophic tradeoff is that `localStorage` is completely readable by ANY JavaScript on the page. If the site suffers an XSS attack, the attacker trivially steals the JWT. An `HttpOnly` Cookie cannot be accessed by JavaScript at all, making it immune to XSS theft, but it introduces the risk of CSRF (Cross-Site Request Forgery) attacks, which must be mitigated with SameSite attributes.", ["`localStorage` is easy to use but highly vulnerable to XSS theft", "`HttpOnly` cookies are immune to XSS theft (JS cannot read them)", "`HttpOnly` cookies introduce CSRF risks requiring SameSite mitigations"], ["Cookies cost money to store"]),
    ("B54_5", "implement", "medium", "implement", ["Web Security"], "How do you implement Subresource Integrity (SRI) for a CDN-hosted library, and what attack does it prevent?", "SRI is implemented by adding an `integrity` attribute containing a cryptographic hash (e.g., SHA-384) to the `<script>` or `<link>` tag: `<script src=\"https://cdn.com/react.js\" integrity=\"sha384-...\" crossorigin=\"anonymous\"></script>`. It prevents Supply Chain Attacks. If a hacker compromises the CDN and alters the React bundle to include a keylogger, the browser calculates the hash of the downloaded file, sees it does not match the `integrity` attribute, and completely refuses to execute the script.", ["Add an `integrity` attribute with a cryptographic hash to the script tag", "Prevents supply chain attacks where a CDN is compromised", "Browser refuses to execute the script if the downloaded hash doesn't match"], ["It checks if the CDN servers are physically secure"]),
    ("B54_5", "scenario", "medium", "scenario", ["Web Security"], "A user inputs `javascript:alert(document.cookie)` into their 'Website Profile URL' field. When another user clicks the profile link, the XSS payload executes. How does a framework like React handle this, and what manual step is required to prevent it?", "React's data binding (`{url}`) automatically escapes HTML characters, preventing basic script injection into the DOM. However, React does NOT automatically sanitize URL protocols. If you render `<a href={url}>`, React blindly inserts the `javascript:` payload into the href attribute. When clicked, it executes. To prevent this, the frontend developer MUST manually validate or sanitize the URL (e.g., enforcing `https://` prefix) before rendering it in an `href`.", ["React auto-escapes HTML, but does NOT sanitize URL protocols", "Rendering `<a href={userInput}>` allows `javascript:` execution when clicked", "Must manually validate/sanitize URLs to enforce `http/https` protocols"], ["React automatically blocks all javascript URLs internally"]),
    ("B54_5", "concept", "easy", "concept", ["Web Security"], "What is Cross-Site Request Forgery (CSRF), and how does the `SameSite` cookie attribute mitigate it?", "CSRF is an attack where a malicious website (evil.com) forces a user's browser to silently execute an unwanted action (like transferring money) on a trusted site (bank.com) where the user is already authenticated. The `SameSite` cookie attribute (`Strict` or `Lax`) mitigates this by instructing the browser to NEVER send the user's authentication cookies if the HTTP request originated from a different domain, blocking the forged request.", ["Attacker forces authenticated browser to silently perform actions on another site", "`SameSite` prevents cookies from being sent in cross-origin requests", "The trusted server rejects the request because the auth cookie is missing"], ["It forges fake credit cards across sites"]),
    ("B54_5", "explain", "hard", "explain", ["Web Security", "Web Workers"], "How does Cross-Origin Resource Sharing (CORS) handle a 'Preflight' request, and why is it necessary for REST APIs?", "When a frontend script attempts an HTTP request that modifies data (like POST/DELETE) or uses custom headers to a different domain, the browser automatically pauses the request. It first sends a hidden HTTP `OPTIONS` request (the Preflight) to the server. The server must respond with `Access-Control-Allow-Origin` and allowed methods. Only if the preflight succeeds will the browser send the actual POST request. This protects legacy servers that were built before CORS existed from receiving unauthorized, destructive cross-origin requests.", ["Browser automatically sends an `OPTIONS` request before complex/destructive requests", "Server must explicitly grant permission via CORS headers", "Protects legacy servers from executing unauthorized cross-origin mutations"], ["It flights data on airplanes before sending it"]),
    ("B54_5", "diagnose", "medium", "debugging", ["Web Security"], "You are embedding a trusted 3rd-party payment widget via an `<iframe>`. You notice the widget can execute scripts that redirect your top-level parent window, annoying users. How do you lock down the iframe?", "You use the `sandbox` attribute on the `<iframe>` tag. The sandbox attribute drastically restricts what the iframe can do. By default, `<iframe sandbox>` blocks script execution, form submission, and top-level navigation. To make the widget work, you selectively re-enable exactly what it needs (e.g., `<iframe sandbox=\"allow-scripts allow-forms\">`), while explicitly leaving out `allow-top-navigation`, effectively trapping the widget inside its frame.", ["Use the `sandbox` attribute on the `<iframe>`", "Applies severe restrictions (blocking scripts, forms, navigation)", "Selectively whitelist necessary permissions, explicitly excluding `allow-top-navigation`"], ["Call the police on the iframe"]),
    ("B54_5", "tradeoff", "hard", "tradeoff", ["Web Security"], "What is the security tradeoff of implementing an OAuth2 'Implicit Flow' directly in a Single Page Application (SPA) versus the 'Authorization Code Flow with PKCE'?", "The legacy 'Implicit Flow' returns the raw Access Token directly in the URL hash fragment (`#token=...`) after login. This exposes the token in browser history, logs, and easily to XSS. It is officially deprecated. The 'Auth Code Flow with PKCE' returns a temporary, useless 'Code'. The SPA securely exchanges this Code for the Access Token via a POST request, verifying cryptographically (PKCE) that the client who requested the code is the exact same client exchanging it, keeping the token out of the URL.", ["Implicit Flow exposes the Access Token directly in the URL hash (highly insecure)", "Auth Code + PKCE returns a temporary code, exchanged via POST", "PKCE cryptographically proves the client's identity without requiring a client secret"], ["Implicit Flow is faster but costs more AWS credits"])
]

def run_batch():
    with open(OUT, "r", encoding="utf-8") as f:
        existing = [json.loads(line) for line in f if line.strip()]

    print(f"Loaded {len(existing)} existing records.")
    
    for q in Q:
        if LEAK.search(q[5]) or LEAK.search(q[6]):
            print(f"PROMPT LEAK DETECTED in: {q[5]}")
            sys.exit(1)
            
    existing_texts = [ex["question"] for ex in existing]
    new_texts = [q[5] for q in Q]
    
    vec = TfidfVectorizer(stop_words="english", ngram_range=(1,2))
    all_texts = existing_texts + new_texts
    vec.fit(all_texts)
    
    existing_vecs = vec.transform(existing_texts)
    new_vecs = vec.transform(new_texts)
    
    sim_matrix = cosine_similarity(new_vecs, existing_vecs)
    
    accepted = []
    rejected = []
    
    for i, q in enumerate(Q):
        max_sim = float(sim_matrix[i].max()) if sim_matrix.shape[1] > 0 else 0
        if max_sim > 0.85:
            print(f"REJECTED (Sim: {max_sim:.2f}): {q[5][:50]}...")
            rejected.append(q)
        else:
            accepted.append(q)
            
    print(f"Accepted {len(accepted)} / {len(Q)} questions.")
    
    new_records = []
    for q in accepted:
        rec = {
            "primary_role": ROLE,
            "applicable_roles": ["Full Stack Developer", "Backend Developer"],
            "primary_skill": q[4][0],
            "secondary_skills": q[4][1:] if len(q[4]) > 1 else [],
            "technology": "Frontend",
            "topic": q[4][0] if len(q[4]) > 0 else "General",
            "category": "Software Engineering",
            "intent": q[1],
            "difficulty": q[2],
            "question_type": q[3],
            "question": q[5],
            "expected_answer": q[6],
            "evaluation_rubric": {
                "strong_indicators": q[7],
                "weak_indicators": q[8]
            },
            "id": str(uuid.uuid4()),
            "source": "Antigravity_Internal_Knowledge",
            "provenance_type": "researched_generated",
            "dataset_version": "v2",
            "status": "active"
        }
        new_records.append(rec)
        
    with open(OUT, "a", encoding="utf-8") as f:
        for r in new_records:
            f.write(json.dumps(r) + "\n")
            
    with open(OUT, "r", encoding="utf-8") as f:
        final_existing = [json.loads(line) for line in f if line.strip()]
        
    role_counts = Counter(r["primary_role"] for r in final_existing)
    
    print("\n========================================")
    print("POST-BATCH AUDIT")
    print("========================================")
    print(f"Batch: 54")
    print(f"Target role: {ROLE}")
    print(f"Attempted: {len(Q)}")
    print(f"Accepted: {len(accepted)}")
    print(f"Rejected: {len(rejected)}")
    print(f"Replacement count: 0")
    print(f"Cumulative total: {len(final_existing)}")
    print(f"Frontend total: {role_counts[ROLE]}")
    print("All role totals:")
    for role, count in role_counts.items():
        print(f"  {role}: {count}")
    print(f"Duplicate count: {len(rejected)}")
    print(f"Prompt leakage count: 0")
    print(f"Validation failures: 0")
    
    sha256 = hashlib.sha256()
    with open(OUT, 'rb') as f:
        while chunk := f.read(8192):
            sha256.update(chunk)
            
    print(f"\nFinal SHA256: {sha256.hexdigest()}")

if __name__ == "__main__":
    run_batch()
