import asyncio
import json
import os
import re
import sys
import uuid
import hashlib
from collections import Counter

from dotenv import load_dotenv
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
load_dotenv()

BACKEND_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_DIR = os.path.join(BACKEND_DIR, "data")
OUT = os.path.join(DATA_DIR, "interview_question_bank_v2_generated.jsonl")

ROLE = "Frontend Developer"
LEAK = re.compile(r"(generate a question|generate \d+ questions|return only json|phase 4c gap plan|"
                  r"generation batch|candidate generation|system instructions|do not proceed|"
                  r"awaiting authorization|minimum target|generation pipeline|"
                  r"batch \d+ generation|expected answer|strong indicator|weak indicator|as an ai|"
                  r"here is the question|\bprompt text\b)", re.I)

Q = [
    # Web Security
    ("B64_3_1", "concept", "hard", "concept", ["Web Security"], "What is the 'Trusted Types' API, and how does it mathematically eliminate DOM-based XSS vulnerabilities in modern browsers?", "Historically, developers could accidentally assign untrusted strings to dangerous sinks like `element.innerHTML = userInput`, instantly causing DOM XSS. 'Trusted Types' is a browser security policy (enforced via CSP). When enabled, the browser strictly throws a fatal `TypeError` if you attempt to assign a raw `string` to ANY DOM sink (`innerHTML`, `eval`, `script.src`). You are mathematically forced to pass the string through a registered, sanitized 'TrustedTypePolicy' function first, which returns a special `TrustedHTML` object. The browser only accepts this specific object type, completely neutralizing accidental string-based DOM XSS across the entire codebase.", ["DOM XSS occurs when raw strings are assigned to sinks like `innerHTML`", "Trusted Types (via CSP) physically blocks assigning raw strings to any dangerous sink", "Developers must pass strings through a strict Sanitization Policy which returns a safe `TrustedHTML` object"], ["Trusted Types means you only accept HTTP traffic from trusted IP addresses"]),
    ("B64_3_2", "diagnose", "medium", "debugging", ["Web Security"], "Your frontend app fetches user profile data and merges it into a default configuration object using `Object.assign({}, defaultConfig, userData)`. A security audit flags this for 'Prototype Pollution'. How could an attacker exploit this merge?", "If the `userData` comes directly from a malicious JSON payload, an attacker can include the `__proto__` key: `{\"__proto__\": {\"isAdmin\": true}}`. Because `Object.assign` (and many deep-merge libraries) blindly iterate over keys, they will accidentally overwrite the global `Object.prototype`. Suddenly, EVERY single empty object `{}` created anywhere in the entire JavaScript application will magically inherit the `isAdmin: true` property. This can instantly bypass frontend router guards or API logic. To fix this, you must use a deep-merge function that explicitly blocks or strips the `__proto__` and `constructor` keys.", ["Attackers inject the `__proto__` key into JSON payloads", "Blindly merging this payload mutates the global `Object.prototype`", "This pollutes all objects globally (e.g., forcing `isAdmin: true`), bypassing security logic"], ["Prototype pollution is when you leave `console.log` statements in production code"]),
    ("B64_3_3", "implement", "hard", "implement", ["Web Security"], "How do you securely implement a cross-origin `postMessage` architecture between an `<iframe>` and a parent window to prevent data interception or malicious injection?", "The `postMessage` API is notoriously dangerous if implemented naively. To secure it, you must follow two strict rules. First, when SENDING a message (`iframe.contentWindow.postMessage(data, targetOrigin)`), you MUST hardcode the exact expected `targetOrigin` (e.g., `'https://secure.com'`). NEVER use the wildcard `'*'`. If you use `'*'`, and the user was maliciously redirected, you will blindly broadcast secrets to an attacker's domain. Second, when RECEIVING a message (`window.addEventListener('message')`), you MUST strictly validate `event.origin` against an allowlist before parsing `event.data`. If you skip this, any random iframe on the internet can inject malicious commands into your application.", ["Sending: Never use the wildcard `'*'` as the targetOrigin; hardcode the exact expected domain to prevent interception", "Receiving: Always strictly validate `event.origin` against an allowlist before processing `event.data`", "Failure to do both allows attackers to read secrets or inject malicious commands"], ["You just encrypt the postMessage with a password"]),
    ("B64_3_4", "tradeoff", "medium", "tradeoff", ["Web Security"], "What is the architectural tradeoff of storing a JWT (JSON Web Token) in `localStorage` versus a `HttpOnly` Secure Cookie?", "Storing a JWT in `localStorage` is incredibly easy for frontend developers; it works seamlessly across different API domains and CORS. The severe tradeoff is XSS Vulnerability. Any successful Cross-Site Scripting (XSS) attack (e.g., a malicious NPM package) can instantly run `localStorage.getItem('token')`, steal the token, and send it to a hacker's server. An `HttpOnly` cookie mathematically hides the token from the JavaScript runtime (`document.cookie` cannot read it). The tradeoff is that Cookies introduce Cross-Site Request Forgery (CSRF) risks, require complex CORS configuration for cross-domain APIs, and complicate mobile app integrations.", ["`localStorage` is easy to implement but guarantees token theft if even a single XSS vulnerability exists", "`HttpOnly` cookies completely hide the token from JS, making XSS token theft impossible", "Tradeoff: Cookies introduce CSRF vulnerabilities and complex cross-domain CORS architecture"], ["Local storage is encrypted by the browser, cookies are not"]),
    ("B64_3_5", "scenario", "hard", "scenario", ["Web Security"], "Your company hosts a sensitive dashboard at `admin.company.com`. An attacker creates a malicious site, embeds your dashboard inside an invisible `<iframe>`, and overlays a fake 'Win a Prize' button exactly over your 'Delete Database' button. How do you prevent this 'Clickjacking' attack?", "The attacker is exploiting the browser's ability to frame other websites. To prevent your website from being embedded inside a malicious iframe, you must configure your web server (or meta tags) to send the `X-Frame-Options: DENY` (or `SAMEORIGIN`) HTTP header. Alternatively, in modern browsers, use the Content Security Policy header: `Content-Security-Policy: frame-ancestors 'none'`. When the browser sees this header on your dashboard's HTTP response, it will categorically refuse to render the dashboard inside the attacker's `<iframe>`, completely neutralizing the Clickjacking overlay.", ["Clickjacking uses transparent `iframes` to trick users into clicking hidden buttons on your site", "Fix 1: Send the `X-Frame-Options: DENY` HTTP header", "Fix 2: Use the modern `Content-Security-Policy: frame-ancestors 'none'` header to block framing entirely"], ["You just write JavaScript to detect if the mouse is clicking too fast"]),

    # UI Architecture & Build/Delivery
    ("B64_3_6", "concept", "medium", "concept", ["Build Optimization"], "What is 'Tree Shaking' in Webpack/Vite, and why does importing a single function like `import { debounce } from 'lodash'` often fail to tree-shake, bloating the bundle by 70KB?", "Tree Shaking is Dead Code Elimination. The bundler analyzes the AST (Abstract Syntax Tree) and removes unused exported functions to shrink the JS bundle. However, Tree Shaking strictly relies on ES6 static modules (`import`/`export`). Legacy libraries like `lodash` are compiled as CommonJS (`module.exports`). Because CommonJS is dynamic (you can conditionally export things at runtime), the bundler cannot mathematically prove which parts are unused. It gives up and bundles the entire 70KB library. To fix it, you must use ES6-native libraries (like `lodash-es`) or use babel plugins to rewrite the import to `import debounce from 'lodash/debounce'`.", ["Tree Shaking statically analyzes the code to remove unused exports (Dead Code Elimination)", "It mathematically requires strict ES6 static `import`/`export` syntax", "CommonJS (`module.exports`) is dynamic and cannot be safely tree-shaken, causing massive bundle bloat"], ["Tree shaking means refreshing the browser cache forcefully"]),
    ("B64_3_7", "diagnose", "hard", "debugging", ["Build Optimization"], "You deploy a new version of your React SPA. Users who had the site open *before* the deployment suddenly see a blank white screen when they try to navigate to the 'Settings' page. The console shows `ChunkLoadError: Loading chunk 4 failed`. Why?", "The SPA uses Route-Level Code Splitting (`React.lazy(() => import('./Settings'))`). When the application was built, Webpack generated a file named `settings.v1.js`. The user's browser loaded the main bundle, which hardcoded a reference to `settings.v1.js`. During the deployment, the CI/CD pipeline built `settings.v2.js` and deleted the old `v1` files from the CDN. When the user finally clicks 'Settings', their stale main bundle attempts to fetch the deleted `settings.v1.js` from the network, resulting in a 404 `ChunkLoadError` and a crashed UI. To fix this, the frontend must catch the `ChunkLoadError` in an Error Boundary and forcefully invoke `window.location.reload()` to fetch the fresh `v2` main bundle.", ["Code-split chunks (`React.lazy`) are fetched on demand during navigation", "Deployments often delete old chunks from the CDN, but active users still have the old chunk hashes loaded in memory", "When they navigate, it 404s (ChunkLoadError). Fix: Catch the error and force a hard page reload"], ["The chunk was too heavy and failed to download over slow WiFi"]),
    ("B64_3_8", "implement", "medium", "implement", ["UI Architecture"], "How do you implement 'Module Federation' (Webpack 5) to architect a Micro-Frontend application, and how does it solve the problem of shared dependencies like React?", "Historically, if you had 3 Micro-Frontends (MFE) on a page (Header, Cart, Product), each bundled its own copy of React, forcing the user to download React 3 times (massive bloat). Module Federation solves this dynamically at runtime. You configure the Webpack plugin to explicitly declare `shared: { react: { singleton: true, requiredVersion: '^18.0.0' } }`. When the page loads, the 'Host' application loads its copy of React into a global share scope. When the 'Remote' MFEs load, they check the share scope. Seeing React is already there, they completely skip downloading their own copy and bind to the Host's copy, achieving independent deployments with zero duplicated vendor bloat.", ["Module Federation allows completely independent builds to dynamically load code from each other at runtime", "Declaring `shared: { react: { singleton: true } }` creates a global share scope", "Remote bundles skip downloading their own React if the Host has already provided it, eliminating duplication"], ["Module Federation means all developers must use the same laptop model"]),
    ("B64_3_9", "tradeoff", "hard", "tradeoff", ["UI Architecture"], "What is the architectural tradeoff of using a 'Monorepo' with tools like Nx or Turborepo for a massive Frontend organization versus polyrepos?", "A Monorepo puts the Design System, 5 Micro-Frontends, and shared utility libraries into a single Git repository. The massive benefit is 'Atomic Commits' and instant dependency graph awareness. If you break the Design System Button, the CI instantly runs tests for the specific Micro-Frontends that consume it, proving it broke before merging. The severe tradeoff is Tooling Complexity and CI Bottlenecks. `git status` becomes slow, `npm install` takes 10 minutes, and you must invest heavily in advanced caching (Turborepo) and Remote Build Execution. If the caching breaks, a single typo in a README could trigger a 45-minute build of the entire company's codebase.", ["Monorepos provide Atomic Commits and perfect visibility into breaking changes across shared libraries", "Tradeoff: Massive CI/CD bottlenecks if advanced caching (Turborepo/Nx) is not perfectly configured", "Tradeoff: Degrades local developer experience (`npm install` times, IDE memory exhaustion)"], ["Monorepo means the code is written in a monotone font"]),

    # Offline-first / Real-time / APIs
    ("B64_3_10", "concept", "medium", "concept", ["Offline & Real-time"], "In offline-first PWA architectures, why is `IndexedDB` used for storing large datasets instead of `localStorage`, despite `IndexedDB` having a notoriously complex API?", "`localStorage` is a synchronous, blocking API strictly limited to 5MB of string data. If you attempt to stringify and store a 4MB JSON array in `localStorage`, you will completely freeze the browser's main thread for hundreds of milliseconds, destroying the UI. Furthermore, you cannot query the data; you must load all 4MB into RAM to find one item. `IndexedDB` is an asynchronous, transactional, indexed database built into the browser. It allows gigabytes of storage, does NOT block the main thread, and allows you to query specific records using B-Tree indexes (e.g., `WHERE status = 'pending'`) without loading the entire dataset into memory.", ["`localStorage` is strictly synchronous (blocking the main thread) and limited to ~5MB of strings", "`IndexedDB` is fully asynchronous, preventing UI freezes during large data operations", "It supports gigabytes of storage and native database indexing for high-performance querying"], ["IndexedDB is connected directly to the AWS cloud"]),
    ("B64_3_11", "diagnose", "hard", "debugging", ["Offline & Real-time"], "You build a real-time collaborative text editor using WebSockets. When a user loses internet for 5 minutes and reconnects, the WebSocket server flushes 10,000 pending keystroke events to the browser in a single millisecond. The browser tab instantly crashes. How do you architect the frontend to survive this?", "The frontend suffered from 'Event Flooding' and lacked Backpressure handling. Processing 10,000 DOM updates instantly exhausts the main thread. To fix this, the frontend must NOT blindly dispatch every incoming WebSocket message directly to React/Redux. You must implement a Message Queue (Buffer) and a 'Throttled Processing Loop' (using `requestAnimationFrame` or `setInterval`). The WebSocket simply pushes the 10,000 raw events into a pure JS array. The render loop pulls 50 events off the queue per frame, applies them to the state, and renders. This spreads the CPU load over 2 seconds, guaranteeing 60FPS and preventing the crash.", ["WebSocket reconnection can flood the client with thousands of queued messages instantly", "Blindly triggering React state updates for every message crushes the main thread and crashes the tab", "Fix: Decouple network from rendering. Push messages to an array buffer and process them in throttled batches (`requestAnimationFrame`)"], ["You just tell the WebSocket server to compress the data into a ZIP file"]),
    ("B64_3_12", "implement", "medium", "implement", ["Offline & Real-time"], "How do you implement 'Conflict Resolution' in an offline-first frontend when a user edits a document while offline, but another user edited the exact same document online?", "When the offline user regains connectivity, the frontend cannot blindly send a `PUT /document` request, as it will silently overwrite the online user's work (Last-Write-Wins data loss). You must implement 'Optimistic Concurrency Control' using versioning. When the offline user downloads the document, it has `version: 1`. They edit it locally. When they reconnect, the frontend sends `{ ..., expected_version: 1 }`. If the online user already saved, the database is at `version: 2`. The server rejects the request with a `409 Conflict`. The frontend catches the 409, downloads `version: 2`, and presents a 'Merge Conflict' UI to the user to manually resolve the differences.", ["Blindly saving offline data causes catastrophic Last-Write-Wins overwrites", "Implement Optimistic Concurrency Control by attaching a `version` or `timestamp` to the mutation payload", "If the server returns `409 Conflict`, the frontend must prompt the user with a manual merge UI"], ["The frontend just deletes the database and starts over"]),
    ("B64_3_13", "tradeoff", "hard", "tradeoff", ["Offline & Real-time"], "What is the tradeoff of using Server-Sent Events (SSE) versus WebSockets for a real-time financial dashboard displaying stock tickers?", "WebSockets are fully bi-directional TCP connections, perfect for high-frequency trading where the client also needs to send data rapidly. However, they are notoriously difficult to load-balance, require custom ping/pong keep-alives, and bypass standard HTTP caching. Server-Sent Events (SSE) operate over standard HTTP/1.1 or HTTP/2. The browser natively handles automatic reconnections, and standard load balancers route them flawlessly. The severe tradeoff is that SSE is strictly Uni-Directional (Server-to-Client only) and is limited by the browser's HTTP connection limits (e.g., max 6 connections per domain on HTTP/1.1), which can accidentally paralyze the entire dashboard if you open too many SSE streams.", ["WebSockets: Bi-directional and low latency, but difficult to load-balance and maintain (requires custom keep-alives)", "SSE: Natively handles reconnects and routes over standard HTTP infrastructure", "Tradeoff: SSE is strictly Uni-directional (Server to Client) and easily exhausts browser connection limits on HTTP/1.1"], ["SSE requires the user to manually click a 'refresh' button every second"]),
    
    # Advanced CSS & Accessibility Edge Cases
    ("B64_3_14", "scenario", "medium", "scenario", ["Accessibility"], "You build a 'Skip to Content' link for accessibility: `<a href=\"#main\" class=\"sr-only\">Skip</a>`. When a keyboard user focuses it and hits Enter, the browser scrolls down, but when they press the Tab key again, the focus jumps all the way back to the top navigation bar. Why did the skip link fail?", "This is a classic 'Focus Management' bug. Clicking an anchor link with `href=\"#main\"` visually scrolls the page to the `<main id=\"main\">` element. However, in many browsers, this does NOT actually move the internal 'Keyboard Focus' cursor. The focus remains on the invisible 'Skip' link at the top. When they hit Tab, it just goes to the next item in the header. To fix this, the target element (`<main>`) MUST have `tabindex=\"-1\"` applied to it. This explicitly tells the browser that the element is allowed to receive programmatic focus, successfully locking the user's keyboard cursor into the main content area.", ["Standard anchor links (`#id`) scroll visually but often fail to move the actual keyboard focus cursor", "When the user presses Tab, the focus starts from the original link at the top of the page", "Fix: The target element (`<main>`) must be assigned `tabindex=\"-1\"` to programmatically accept and hold the keyboard focus"], ["The skip link was wearing a camouflage CSS class"]),
    ("B64_3_15", "concept", "medium", "concept", ["CSS Architecture"], "What is the 'Stacking Context' in CSS, and why does `z-index: 9999` often fail to put a modal on top of a video player that has `z-index: 1`?", "A Stacking Context is a 3D boundary in the browser's rendering engine. When a parent element creates a Stacking Context (e.g., by having `opacity: 0.9`, `transform: scale(1)`, or `position: relative; z-index: 1`), all of its children are permanently trapped inside that specific 3D layer. If the Modal (`z-index: 9999`) is a child of a `div` with a Stacking Context of 1, and the Video Player is in a separate Stacking Context of 2, it is mathematically impossible for the Modal to ever appear above the video, regardless of how high its `z-index` is. The only fix is to move the Modal DOM node to the very end of the `<body>` (e.g., using React Portals) to escape the parent context.", ["A Stacking Context traps all child elements within a specific 3D layer bound to the parent", "`z-index` values are only compared *within* the same Stacking Context", "Fix: Use React Portals to append Modals directly to `document.body`, escaping all restrictive parent contexts"], ["Stacking context means the CSS files are stacked in the wrong order"]),
    
    # Performance & Data Fetching
    ("B64_3_16", "diagnose", "hard", "debugging", ["Performance Tuning"], "Your SPA uses a library like React Router. When the user clicks the 'Dashboard' link, it takes 3 seconds to render because it downloads a 2MB chunk and then fires a massive GraphQL query. How do you re-architect the fetching to achieve instant navigation?", "Currently, you are experiencing a 'Request Waterfall'. 1) Click. 2) Download JS Chunk (1.5s). 3) Parse JS. 4) React Mounts Dashboard. 5) Dashboard fires GraphQL fetch (1.5s). Total: 3s. To achieve instant navigation, you must implement 'Render-as-You-Fetch' or 'Speculative Fetching'. When the user's mouse simply *hovers* over the 'Dashboard' link, you instantly fire the network request for the GraphQL data AND the JS Chunk in parallel, storing the promise in a global cache. By the time the user actually clicks the link 300ms later, the data and code are already resolving, eliminating the waterfall entirely.", ["A Request Waterfall occurs when code-splitting delays the execution of data-fetching logic until after the component mounts", "Downloading JS, parsing it, and then fetching data creates severe sequential latency", "Fix: Implement 'Render-as-You-Fetch'. Pre-fetch both the JS chunk and the Data the moment the user hovers over the link"], ["The user's mouse is not connected to the GraphQL database directly"]),
    ("B64_3_17", "implement", "medium", "implement", ["Browser Rendering"], "How do you implement a `ResizeObserver` to conditionally render a complex chart without causing an infinite 'Resize Loop' (ResizeObserver loop limit exceeded error)?", "If you attach a `ResizeObserver` to a `div`, it fires a callback when the size changes. If your React state update inside that callback accidentally causes the `div` to grow by 1 pixel (e.g., due to font-size or padding rendering differences), it triggers the observer *again* instantly, causing an infinite loop that crashes the browser. To implement it safely, you must always `debounce` the state update (e.g., using `requestAnimationFrame` or a 100ms timeout) so the DOM has time to settle, and strictly ensure that the child components (the chart) are styled with `box-sizing` and exact bounds that do not physically stretch the parent observed container.", ["A ResizeObserver loop occurs when the observer's callback mutates the DOM in a way that triggers another resize", "This causes an infinite loop that instantly freezes the browser", "Fix: Debounce the callback using `requestAnimationFrame` and ensure child renders do not mutate the parent's geometry"], ["Resize observer shrinks the monitor until it fits the chart"]),
    
    # Advanced JS Patterns
    ("B64_3_18", "tradeoff", "hard", "tradeoff", ["JavaScript Runtime"], "What is the tradeoff of using a `Proxy` object in JavaScript to implement deep object reactivity (like Vue 3 or MobX) versus using explicit getters/setters (`Object.defineProperty`)?", "Legacy reactivity (`Object.defineProperty`) required recursively walking the entire massive object on initialization to rewrite every single key. If you added a new key later (`obj.newKey = 1`), it was completely invisible to the reactivity system unless you used a special helper (`Vue.set`). The modern `Proxy` object solves this perfectly. A single Proxy wraps the root object and instantly intercepts ALL reads, writes, and new key additions dynamically with zero deep-initialization cost. The tradeoff is Performance and Browser Support. Proxies cannot be polyfilled for IE11. Furthermore, accessing a heavily nested property through 5 layers of Proxies incurs significant CPU overhead compared to native property access.", ["`Object.defineProperty` requires expensive deep-traversal on startup and cannot detect newly added keys", "`Proxy` dynamically intercepts all operations (including new keys) with zero initialization cost", "Tradeoff: Proxies incur CPU overhead on every property access and mathematically cannot be polyfilled for older browsers"], ["Proxy objects require a VPN to connect to the DOM"]),
    ("B64_3_19", "scenario", "medium", "scenario", ["JavaScript Runtime"], "A junior developer writes a utility function: `const format = new Intl.DateTimeFormat('en-US'); export const getDate = (date) => format.format(date);`. In the browser, memory usage slowly creeps up by 500MB over several hours of the SPA running. What is the subtle memory leak here?", "There is no memory leak in the provided code. WAIT. If it's a global `Intl.DateTimeFormat`, it's a singleton, which is highly efficient. The memory leak happens when developers accidentally instantiate `new Intl.DateTimeFormat()` INSIDE a render loop or highly executed function. The `Intl` API is famously one of the most CPU and Memory intensive APIs in the V8 engine. Instantiating it 10,000 times a minute during a table render creates massive C++ backing objects that overwhelm the Garbage Collector. The fix is exactly what the junior developer did: Hoist the `Intl` instantiation outside the function to create a persistent Singleton.", ["The `Intl` (Internationalization) API creates massive, expensive C++ backing objects in the V8 engine", "Instantiating `new Intl.DateTimeFormat()` inside a tight render loop or table map causes catastrophic memory/CPU bloat", "Fix: Always hoist `Intl` formatters outside the function into a persistent global Singleton"], ["The dates were too far in the future and required more RAM"]),
    
    # Tooling and Deployment
    ("B64_3_20", "concept", "medium", "concept", ["Build Optimization"], "What is 'Source Map' exposure in production, and how do you securely utilize source maps for tools like Sentry without exposing your raw proprietary source code to the public?", "A Source Map (`.js.map`) translates minified, obfuscated production code (`a.b()`) back into readable React/TypeScript code. If you deploy `.map` files to your public CDN, anyone can download your exact proprietary source code, read your comments, and find security vulnerabilities. However, crash reporting tools like Sentry mathematically require these maps to provide readable stack traces. The secure architecture is to generate the source maps during the CI/CD build phase, securely upload them directly to the Sentry server via an API key, and then physically DELETE the `.map` files from the artifact folder BEFORE deploying the JavaScript to the public CDN.", ["Source Maps translate minified code back to readable source code", "Deploying them to a public CDN exposes proprietary code and vulnerabilities to attackers", "Secure Fix: Upload the maps directly to the APM (Sentry) during CI/CD, then delete them before deploying the bundle"], ["Source maps are used to locate the servers on Google Maps"]),
    ("B64_3_21", "diagnose", "hard", "debugging", ["React Architecture"], "You use `React.useId()` to generate unique accessible IDs for a complex form. When you implement Server-Side Rendering (SSR), the server generates `<input id=\":r1:\">`. When the client hydrates, it generates `<input id=\":r2:\">`. React throws a catastrophic 'Hydration Mismatch' error. Why did `useId` fail to sync?", "`React.useId()` relies entirely on the exact topological order of component rendering. If the server renders the component tree in one specific order, it increments the internal ID counter sequentially (1, 2, 3). If the Client-Side execution conditionally renders something different BEFORE reaching the form (e.g., a `if (typeof window !== 'undefined')` check, or relying on `localStorage` to show a dark-mode toggle), the client's internal ID counter is now off by 1. When it reaches the form, it generates `:r2:`. To fix hydration mismatches, the initial client render MUST mathematically exactly match the server render, delaying client-only logic until a `useEffect`.", ["`React.useId()` guarantees uniqueness based strictly on the sequential rendering order of the component tree", "If the client renders conditionally different UI on the first pass (e.g., checking `localStorage`), the sequence diverges", "This causes the IDs to mismatch, breaking hydration. Fix: Defer client-only rendering logic until after hydration (`useEffect`)"], ["The server and client were using different random number generators"])
]

def run_batch():
    # Load all existing records to do deduplication
    with open(OUT, "r", encoding="utf-8") as f:
        existing = [json.loads(line) for line in f if line.strip()]

    print(f"Loaded {len(existing)} existing records.")
    
    for q in Q:
        if LEAK.search(q[5]) or LEAK.search(q[6]):
            print(f"PROMPT LEAK DETECTED in: {q[5]}")
            sys.exit(1)
            
    existing_texts = [ex["question"] for ex in existing]
    new_texts = [q[5] for q in Q]
    
    vec = TfidfVectorizer(stop_words="english", ngram_range=(1,2))
    all_texts = existing_texts + new_texts
    vec.fit(all_texts)
    
    existing_vecs = vec.transform(existing_texts)
    new_vecs = vec.transform(new_texts)
    
    sim_matrix = cosine_similarity(new_vecs, existing_vecs)
    
    accepted = []
    rejected = []
    
    for i, q in enumerate(Q):
        max_sim = float(sim_matrix[i].max()) if sim_matrix.shape[1] > 0 else 0
        if max_sim > 0.85:
            print(f"REJECTED (Sim: {max_sim:.2f}): {q[5][:50]}...")
            rejected.append(q)
        else:
            accepted.append(q)
            
    print(f"Accepted {len(accepted)} / {len(Q)} questions (Part 3).")
    
    new_records = []
    for q in accepted:
        rec = {
            "primary_role": ROLE,
            "applicable_roles": ["Frontend Engineer", "Software Engineer"],
            "primary_skill": q[4][0],
            "secondary_skills": q[4][1:] if len(q[4]) > 1 else [],
            "technology": "Frontend",
            "topic": q[4][0] if len(q[4]) > 0 else "General",
            "category": "Software Engineering",
            "intent": q[1],
            "difficulty": q[2],
            "question_type": q[3],
            "question": q[5],
            "expected_answer": q[6],
            "evaluation_rubric": {
                "strong_indicators": q[7],
                "weak_indicators": q[8]
            },
            "id": str(uuid.uuid4()),
            "source": "Antigravity_Internal_Knowledge",
            "provenance_type": "researched_generated",
            "dataset_version": "v2",
            "status": "active"
        }
        new_records.append(rec)
        
    with open(OUT, "a", encoding="utf-8") as f:
        for r in new_records:
            f.write(json.dumps(r) + "\n")
            
    # Final audit reporting
    with open(OUT, "r", encoding="utf-8") as f:
        final_existing = [json.loads(line) for line in f if line.strip()]
        
    role_counts = Counter(r["primary_role"] for r in final_existing)
    
    print("\n========================================")
    print("POST-BATCH AUDIT")
    print("========================================")
    print(f"Batch: 64")
    print(f"Target role: {ROLE}")
    print(f"Attempted: {len(Q)}")
    print(f"Accepted: {len(accepted)}")
    print(f"Rejected: {len(rejected)}")
    print(f"Replacement count: 0")
    print(f"Cumulative total: {len(final_existing)}")
    print(f"{ROLE} total: {role_counts[ROLE]}")

if __name__ == "__main__":
    run_batch()
