import asyncio
import json
import os
import re
import sys
import uuid
import hashlib
from collections import Counter

from dotenv import load_dotenv
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
load_dotenv()

BACKEND_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_DIR = os.path.join(BACKEND_DIR, "data")
OUT = os.path.join(DATA_DIR, "interview_question_bank_v2_generated.jsonl")

ROLE = "DevOps / Cloud Engineer"
LEAK = re.compile(r"(generate a question|generate \d+ questions|return only json|phase 4c gap plan|"
                  r"generation batch|candidate generation|system prompts|do not proceed|"
                  r"awaiting authorization|minimum target|generation pipeline|"
                  r"batch \d+ generation|expected answer|strong indicator|weak indicator|as an ai|"
                  r"here is the question|\bprompt text\b)", re.I)

Q = [
    # Area 1: eBPF & Linux Kernel Performance
    ("B52_1", "explain", "hard", "concept", ["eBPF", "Linux Performance"], "Explain how eBPF fundamentally differs from traditional Linux kernel modules for performance observability.", "Traditional kernel modules require compiling C code against specific kernel headers and carry the risk of fatally crashing the entire OS (kernel panic) if they contain bugs. eBPF (Extended Berkeley Packet Filter) allows safely executing sandboxed programs directly within the kernel. The eBPF code passes through an internal verifier that mathematically guarantees it cannot crash or loop infinitely, allowing safe, ultra-low-overhead observability of kernel tracepoints, network packets, and syscalls without recompiling the kernel.", ["eBPF runs in a secure, guaranteed-safe sandbox inside the kernel", "Traditional modules risk kernel panics and require compilation/rebooting", "eBPF has a verifier to prevent infinite loops and memory corruption"], ["eBPF is just a bash script for top"]),
    ("B52_1", "diagnose", "hard", "debugging", ["eBPF", "Observability"], "You are experiencing mysterious micro-burst network drops on a Kubernetes node. Standard tools like `tcpdump` show no packet loss. How can eBPF help diagnose this?", "Standard tools operate in userspace or at higher kernel layers and may miss packets dropped extremely early in the networking stack (e.g., by NIC drivers, early XDP, or iptables limits). By writing an eBPF program attached to `kfree_skb` (the kernel function called when a network buffer is freed/dropped), you can intercept the exact moment a packet is silently discarded by the kernel, extract the stack trace, and determine precisely which kernel subsystem (e.g., a specific firewall rule or buffer overflow) dropped it.", ["Attach eBPF to kernel tracepoints like `kfree_skb`", "Captures packets dropped before they reach userspace tools like tcpdump", "Provides the exact kernel stack trace causing the drop"], ["Use ping repeatedly"]),
    ("B52_1", "architecture", "medium", "architecture", ["eBPF", "Security"], "How does Cilium use eBPF to replace traditional `kube-proxy` in a Kubernetes cluster?", "Traditional `kube-proxy` relies on massive, sequential `iptables` rules for routing service traffic, which scales poorly (O(n) complexity) and causes high CPU overhead when a cluster has thousands of services. Cilium completely bypasses `iptables` by attaching eBPF programs directly to the XDP (eXpress Data Path) and socket layers. When a pod sends traffic, the eBPF map instantly routes it to the correct destination pod with O(1) hash table lookups, drastically reducing latency and CPU usage.", ["Bypasses massive, slow iptables chains", "Attaches to XDP and socket layers for O(1) routing complexity", "Drastically reduces latency and CPU usage in large clusters"], ["Cilium replaces Docker with eBPF"]),
    ("B52_1", "tradeoff", "medium", "tradeoff", ["Linux Performance"], "What is the tradeoff between monitoring memory usage via the `OOM (Out of Memory)` killer logs versus monitoring `PSI (Pressure Stall Information)`?", "OOM logs are reactive; they only tell you that the system has already catastrophically run out of memory and terminated a process, which is too late to prevent an outage. PSI (Pressure Stall Information) is proactive. It exposes metrics (in `/proc/pressure/memory`) showing the exact percentage of time tasks are blocked waiting for memory (e.g., thrashing swap). Monitoring PSI allows you to detect severe memory pressure and autoscale *before* the OOM killer ever intervenes.", ["OOM is reactive and catastrophic (a process is already dead)", "PSI is proactive, measuring the time tasks spend blocked waiting for resources", "PSI allows autoscaling before failure occurs"], ["PSI measures tire pressure"]),
    ("B52_1", "scenario", "hard", "scenario", ["Linux Performance"], "A Java application on a Linux server is experiencing massive latency spikes. CPU usage is low, but `iostat` shows 100% disk utilization. The app logs exclusively to an asynchronous queue, not disk. What kernel mechanism is likely causing this disk thrashing?", "The application is likely suffering from aggressive swapping. Even though it doesn't write to disk, if the system runs out of physical RAM (or is constrained by aggressive `swappiness` settings), the Linux kernel begins paging active Java heap memory to the swap file on disk. When the JVM's Garbage Collector runs, it must access the entire heap, forcing the kernel to constantly swap pages in and out of disk (thrashing), driving disk I/O to 100% and stalling the JVM.", ["Aggressive swapping (paging memory to disk)", "The Garbage Collector forces the kernel to swap pages back into RAM", "Causes severe disk I/O thrashing and JVM latency despite no direct disk writes"], ["The Java code is secretly saving files"]),
    ("B52_1", "implement", "medium", "implement", ["eBPF", "Observability"], "How do you capture SSL/TLS encrypted payloads in a microservices environment without managing complex proxy sidecars, using eBPF?", "You can attach eBPF uprobes (User-space Probes) directly to the OpenSSL/BoringSSL libraries (e.g., `SSL_read` and `SSL_write` functions) inside the running processes. Because these functions handle the data *before* it is encrypted (on send) or *after* it is decrypted (on receive), the eBPF program can transparently capture the plaintext HTTP payload without needing to manage proxy certificates, alter the application code, or perform expensive MITM decryption.", ["Use uprobes (User-space Probes) attached to OpenSSL/BoringSSL functions", "Intercepts `SSL_read` and `SSL_write` before encryption / after decryption", "Captures plaintext payloads transparently without proxy MITM"], ["You cannot intercept TLS without the private key"]),
    ("B52_1", "diagnose", "medium", "debugging", ["Linux Performance"], "Your monitoring shows a server's CPU is at 100%. However, when you run `top`, the `us` (userspace) and `sy` (system) metrics are low, but the `wa` (iowait) metric is at 95%. What does this mean, and how do you fix it?", "`iowait` (wa) means the CPU is completely idle, but it is forced to wait because processes are blocked attempting to read or write to an extremely slow or overloaded disk. The CPU itself is not overloaded; it is starved of data. To fix it, you must identify the process doing the heavy I/O (using `iotop` or eBPF), optimize the application's disk access (batching/caching), or upgrade the storage to faster NVMe SSDs / higher Provisioned IOPS.", ["CPU is idle but blocked waiting for disk I/O operations to complete", "CPU itself is not the bottleneck; the storage medium is", "Fix by identifying the IO-heavy process (iotop) and upgrading storage/caching"], ["iowait means waiting for the internet"]),
    ("B52_1", "concept", "easy", "concept", ["Linux Performance"], "In Linux performance tuning, what is a `sysctl`?", "`sysctl` is a command and interface (interacting with the `/proc/sys` virtual filesystem) used to read and dynamically modify kernel parameters at runtime. DevOps engineers use it to tune critical system behaviors without rebooting, such as increasing the maximum number of open file descriptors (`fs.file-max`), tuning TCP network buffers, adjusting the ephemeral port range, or modifying memory swappiness.", ["Modifies kernel parameters dynamically at runtime without rebooting", "Interacts with `/proc/sys`", "Used to tune TCP buffers, file descriptors, and memory limits"], ["sysctl controls the system clock"]),
    ("B52_1", "scenario", "hard", "scenario", ["Observability"], "You notice a microservice has sporadic 5-second delays connecting to a database. You run `strace -p <PID>` to debug it. The connection delays immediately stop, but the entire microservice slows down by 50%. Why did both things happen?", "First, `strace` uses the `ptrace` system call, which pauses the target process every single time it makes a system call to read the state. This adds massive overhead (context switching), causing the 50% slowdown. Second, the 5-second delays likely stopped because the delays were caused by a race condition or strict timing bug (a 'Heisenbug'). By drastically slowing down the execution via `ptrace`, the timing shifted, masking the original race condition. eBPF is the modern, non-blocking alternative to `strace`.", ["`strace` uses `ptrace`, which pauses the process on every syscall, causing massive CPU overhead", "Slowing down the execution masked the original timing-based race condition (Heisenbug)", "eBPF provides the same visibility without the blocking overhead"], ["strace fixed the bug automatically"]),
    ("B52_1", "compare", "medium", "compare", ["Linux Performance"], "Compare the Linux `top` metric 'Load Average' with 'CPU Utilization %'. Why can a server have a 5% CPU utilization but a Load Average of 100?", "CPU Utilization % measures exactly how much time the CPU processors spent executing instructions in a specific time window. 'Load Average' measures the length of the *Run Queue*—the number of processes that are either currently running OR waiting to run. A server can have a 5% CPU utilization but a Load Average of 100 if 100 processes are blocked waiting for uninterruptible disk I/O (D-state) or a deadlocked NFS mount. They are stuck in the queue, driving up the Load Average, but consuming zero CPU cycles.", ["CPU % measures actual processing time", "Load Average measures the length of the run/wait queue", "Processes blocked on Disk I/O increase Load Average without consuming CPU"], ["Load average is the weight of the server"]),

    # Area 2: Kubernetes Operators & CRDs
    ("B52_2", "concept", "medium", "concept", ["Kubernetes Operators"], "What exactly differentiates a Kubernetes 'Operator' from a standard Kubernetes 'Controller'?", "All Operators are Controllers, but not all Controllers are Operators. A standard Controller watches built-in Kubernetes resources (like Deployments or Pods) and maintains their state. An Operator specifically watches custom, domain-specific resources (CRDs) and encapsulates human operational knowledge to manage complex stateful applications. For example, a standard ReplicaSet controller just spins up Pods; a Postgres Operator watches a `PostgresCluster` CRD, spins up pods, but also handles database backups, primary/replica failover, and schema upgrades.", ["Operators manage Custom Resource Definitions (CRDs)", "Operators encode human operational/domain knowledge (backups, failovers)", "Controllers manage basic built-in resources (Pods, Deployments)"], ["Operators are humans, controllers are robots"]),
    ("B52_2", "architecture", "hard", "architecture", ["Kubernetes Operators"], "Explain the 'Reconciliation Loop' (Control Loop) inside a Kubernetes Operator. How does it achieve Level-Triggered eventual consistency?", "The reconciliation loop constantly compares the 'Desired State' (defined in the CRD YAML applied by the user) with the 'Current State' (the actual resources running in the cluster or external APIs). It is Level-Triggered, meaning it doesn't just react to a one-time 'create' event (Edge-Triggered); it constantly re-evaluates the entire state. If a user manually deletes a database pod that the Operator manages, the loop detects the deviation from the desired state and automatically creates a new pod to reconcile the difference.", ["Constantly compares Desired State (CRD) with Current State (Cluster)", "Level-Triggered: Evaluates the entire state, not just one-off events", "Automatically acts to correct any drift/deviation continuously"], ["It loops through all pods and restarts them"]),
    ("B52_2", "scenario", "hard", "scenario", ["Kubernetes Operators"], "You deploy a custom Operator that provisions external AWS S3 buckets when a user applies an `S3Bucket` CRD. If a user deletes the `S3Bucket` CRD via `kubectl delete`, the CRD instantly disappears from Kubernetes, but the AWS S3 bucket is never deleted. How do you fix this resource leak?", "You must implement Kubernetes 'Finalizers'. A Finalizer is a metadata string added to the CRD. When Kubernetes sees a Finalizer, it intercepts the `kubectl delete` command and prevents the resource from actually being deleted. Instead, it marks it with a `deletionTimestamp`. The Operator detects this timestamp, executes its cleanup logic (calling the AWS API to delete the real S3 bucket), and only upon success, explicitly removes the Finalizer string. Kubernetes then finally purges the CRD.", ["Implement Kubernetes Finalizers on the custom resource", "Finalizers pause the deletion process and set a `deletionTimestamp`", "The Operator performs external cleanup (AWS API) before removing the Finalizer"], ["Tell the user to delete it in AWS manually"]),
    ("B52_2", "implement", "medium", "implement", ["Kubernetes Operators"], "When writing a Kubernetes Operator in Go (using Kubebuilder), what is the architectural danger of making blocking API calls inside the `Reconcile` function?", "The Reconcile function is executed on a shared worker queue. If you make a synchronous, blocking API call (e.g., waiting 5 minutes for a database to provision) inside the Reconcile loop, you completely block that worker thread. This prevents the Operator from processing updates for any other resources in the cluster. Instead, the Reconcile function must be non-blocking and idempotent: it should trigger the provisioning asynchronously, exit immediately, and rely on periodic requeuing (`return ctrl.Result{RequeueAfter: time.Second * 10}`) to check the status later.", ["Blocking calls exhaust the Operator's worker threads", "Stops the Operator from reconciling other resources", "Must use non-blocking status checks and Requeue the reconciliation"], ["Go doesn't support blocking calls"]),
    ("B52_2", "tradeoff", "medium", "tradeoff", ["Kubernetes Operators"], "What is the tradeoff of using a Helm Chart versus a Kubernetes Operator to deploy a complex stateful application like Kafka or Cassandra?", "A Helm Chart is purely a templating engine; it renders YAML once during deployment (Day 1 operations). If a Kafka broker crashes, a disk fills up, or you need to rebalance partitions (Day 2 operations), Helm does nothing to help you. An Operator runs continuously as a live software process inside the cluster. It can actively detect broker failures, automatically run partition rebalancing scripts, and handle complex version upgrades. The tradeoff is that Operators require writing, testing, and maintaining complex Go/Python code, whereas Helm is just text templates.", ["Helm is static templating for Day 1 deployments only", "Operators run continuously to handle complex Day 2 operations (failover, backups)", "Operators require complex software engineering, Helm is simple text"], ["Helm uses YAML, Operators use JSON"]),
    ("B52_2", "diagnose", "medium", "debugging", ["Kubernetes Operators"], "Your custom Operator watches `MyWebApp` CRDs and creates Deployments. Users complain that their Deployments are being constantly restarted every 5 seconds. You check the Operator logs and see the Reconcile loop is triggering infinitely. What common developer mistake causes an infinite reconciliation loop?", "The Operator is likely modifying the `spec` or `metadata` of the Deployment during the reconciliation process in a way that triggers a new Kubernetes watch event. For example, if the Operator continuously adds a timestamp annotation to the Deployment every time it reconciles, the API Server registers an update, which triggers the Operator's watcher again, causing an infinite loop. Operators should only update the `status` subresource, or ensure their updates to the `spec` are strictly idempotent.", ["The Operator is modifying the resource in a non-idempotent way", "Updates to the spec/metadata trigger a new watch event", "Causes an infinite loop of updates and reconciliations"], ["The cluster is out of memory"]),
    ("B52_2", "concept", "easy", "concept", ["Kubernetes Operators"], "What is a Custom Resource Definition (CRD) in Kubernetes?", "A CRD is a way to extend the Kubernetes API with your own custom data structures. Once registered, the Kubernetes API server will accept, validate, and store YAML manifests for your custom resource (e.g., `kind: DatabaseCluster`) in etcd exactly as if it were a native built-in resource like a Pod or Service. You can then use `kubectl get databasecluster` to interact with it.", ["Extends the Kubernetes API with custom objects/data structures", "Treated natively by the API server and stored in etcd", "Allows interaction via standard kubectl commands"], ["It is a Docker container image format"]),
    ("B52_2", "architecture", "hard", "architecture", ["Kubernetes Operators"], "Explain how Kubernetes 'Mutating Admission Webhooks' differ from 'Validating Admission Webhooks'. When would you use a Mutating Webhook in conjunction with an Operator?", "A Validating Webhook only inspects an incoming API request (like creating a Pod) and returns True or False (accept or reject). A Mutating Webhook intercepts the request and actually alters the JSON payload before it is saved to etcd. Operators frequently use Mutating Webhooks to inject default values into a CRD if the user omitted them, or to inject Sidecar containers (like the Istio Envoy proxy) seamlessly into a user's Pod definition before it starts.", ["Validating Webhooks only accept or reject a request", "Mutating Webhooks dynamically alter the resource payload before saving to etcd", "Used to inject default values or sidecar containers transparently"], ["Mutating webhooks mutate the DNA of the pod"]),
    ("B52_2", "scenario", "hard", "scenario", ["Kubernetes Operators"], "You have two instances of an Operator running for High Availability. How do you prevent both instances from simultaneously attempting to reconcile the exact same CRD, leading to race conditions and duplicate AWS infrastructure?", "Kubernetes Operators implement 'Leader Election'. Using the Kubernetes API (typically via ConfigMaps or Leases), the Operator instances compete to acquire a lock. The instance that acquires the lease becomes the Leader and is the only one actively running the reconciliation loops. The other instance sits idle as a standby. If the leader crashes, its lease expires, and the standby instance instantly acquires the lock and takes over processing, ensuring exactly one active reconciler.", ["Implement Leader Election via Kubernetes Leases/ConfigMaps", "Only the leader actively executes reconciliation loops", "Standby instances wait to acquire the lock if the leader crashes"], ["Use a Redis distributed lock"]),
    ("B52_2", "design", "medium", "design", ["Kubernetes Operators"], "When designing a CRD, why is it critical to strictly separate the `spec` block from the `status` block?", "The `spec` block represents the 'Desired State' provided entirely by the *User* (e.g., `replicas: 3`). The `status` block represents the 'Current Observed State' provided entirely by the *Operator* (e.g., `readyReplicas: 2`). Separating them ensures clear ownership. If the Operator wrote its findings back into the `spec`, it would overwrite the user's intent. Using a dedicated `status` subresource also allows Kubernetes RBAC to grant the Operator permission to update the status without granting it permission to alter the spec.", ["`spec` is the Desired State owned by the User", "`status` is the Current Observed State owned by the Operator", "Prevents the Operator from overwriting user intent and allows strict RBAC"], ["It makes the YAML look prettier"]),

    # Area 3: Service Mesh & Advanced Networking
    ("B52_3", "concept", "medium", "concept", ["Service Mesh", "Cloud Networking"], "What is a Service Mesh, and what specific operational problems does it solve that standard Kubernetes networking cannot?", "A Service Mesh (like Istio or Linkerd) is a dedicated infrastructure layer for managing service-to-service communication. While standard Kubernetes networking (kube-proxy) provides basic routing, it lacks advanced Layer 7 controls. A Service Mesh provides transparent Mutual TLS (mTLS) encryption, deep observability (distributed tracing, metrics), advanced traffic shifting (Canary deployments, circuit breakers, retries), and fine-grained authorization policies, all without requiring developers to write this logic into their application code.", ["Provides transparent mTLS encryption and deep observability", "Enables advanced traffic routing (Canaries, circuit breakers, retries) at Layer 7", "Abstracts complexity away from application code via proxies"], ["It is a mesh network of wifi routers"]),
    ("B52_3", "architecture", "hard", "architecture", ["Service Mesh", "Cloud Networking"], "Explain the architecture of a Service Mesh Data Plane versus the Control Plane.", "The Data Plane consists of thousands of lightweight proxies (like Envoy) deployed as 'sidecars' directly alongside every application container in the cluster. These proxies intercept all inbound and outbound network traffic for the app. The Control Plane (e.g., Istiod) is a centralized management service that does not touch network packets. Instead, it generates the configuration, routing rules, and cryptographic certificates, and pushes them down to all the Data Plane proxies dynamically.", ["Data Plane: Lightweight sidecar proxies (Envoy) intercepting all traffic", "Control Plane: Centralized management service generating config and certs", "Control Plane pushes rules to the Data Plane; it does not touch actual data packets"], ["Data plane is for databases, control plane is for APIs"]),
    ("B52_3", "scenario", "medium", "scenario", ["Service Mesh", "Cloud Networking"], "In an Istio Service Mesh, you want to release a new 'Payment' microservice. You want exactly 5% of production traffic to hit the new V2 version, and 95% to hit the stable V1 version. How do you configure this?", "You configure an Istio `VirtualService` and a `DestinationRule`. The `DestinationRule` defines two subsets (V1 and V2) based on pod labels. The `VirtualService` intercepts the traffic destined for the Payment service and applies a weight-based routing rule: assigning a `weight: 95` to the V1 subset and `weight: 5` to the V2 subset. The Envoy proxies execute this percentage-based routing dynamically at Layer 7.", ["Define subsets (V1/V2) in a DestinationRule", "Create a VirtualService with weight-based routing (95/5)", "Envoy sidecars execute the Layer 7 routing transparently"], ["Configure the AWS Load Balancer manually"]),
    ("B52_3", "tradeoff", "hard", "tradeoff", ["Service Mesh", "Cloud Networking"], "What is the primary architectural tradeoff and performance penalty of deploying a traditional sidecar-based Service Mesh?", "The primary tradeoff is resource consumption and network latency. Because every single pod requires its own Envoy sidecar, a cluster with 1,000 pods now has 1,000 extra Envoy containers consuming significant RAM and CPU. Additionally, every network request suffers a latency penalty because it must traverse the network stack multiple times: App -> Local Sidecar -> Network -> Remote Sidecar -> Remote App. This overhead led to the development of sidecarless architectures like eBPF-based Cilium or Ambient Mesh.", ["High resource consumption (Memory/CPU) due to thousands of proxy containers", "Increased latency due to traffic traversing multiple local proxies", "Requires complex lifecycle management for the sidecars"], ["The proxy makes the code execute slower"]),
    ("B52_3", "diagnose", "medium", "debugging", ["Service Mesh", "Cloud Networking"], "After enabling strict Mutual TLS (mTLS) in your Service Mesh, an older legacy microservice outside the mesh suddenly cannot communicate with the mesh services, returning `503` or connection resets. Why, and how do you migrate gracefully?", "Strict mTLS forces the mesh proxies to reject any inbound traffic that does not present a valid cryptographic client certificate. The legacy app outside the mesh does not have an Envoy sidecar to negotiate mTLS. To migrate gracefully, you must configure the Service Mesh `PeerAuthentication` policy to `PERMISSIVE` mode. This allows the proxies to accept both encrypted mTLS traffic (from mesh apps) and unencrypted plaintext traffic (from legacy apps) until all apps are safely inside the mesh, at which point you switch to `STRICT`.", ["Strict mTLS rejects plaintext/unauthenticated traffic from legacy apps", "Use `PERMISSIVE` mode for graceful migration", "Permissive accepts both mTLS and plaintext until the migration is complete"], ["The legacy app forgot its password"]),
    ("B52_3", "concept", "easy", "concept", ["Cloud Networking"], "In AWS networking, what is the fundamental difference between a Security Group and a Network ACL (NACL)?", "A Security Group acts as a firewall at the Instance/ENI level, is stateful (if an inbound request is allowed, the outbound response is automatically allowed), and strictly uses 'Allow' rules. A Network ACL acts as a firewall at the Subnet level, is stateless (you must explicitly configure both inbound and outbound rules for responses), and allows explicit 'Deny' rules.", ["Security Group: Instance level, Stateful, Allow-only", "NACL: Subnet level, Stateless, supports Deny rules", "Stateful means return traffic is automatically allowed"], ["Security Groups use IAM, NACLs use passwords"]),
    ("B52_3", "implement", "medium", "implement", ["Service Mesh", "Cloud Networking"], "How does a Service Mesh implement the 'Circuit Breaker' pattern without modifying application code?", "The Service Mesh sidecar (Envoy) continuously tracks the response codes and latency of downstream services. You configure a `DestinationRule` specifying the outlier detection thresholds (e.g., 'if the service returns 5xx errors 5 times in a row, eject it for 30 seconds'). When the threshold is breached, the proxy 'trips the circuit breaker' and instantly returns an error (like a 503) to the calling app without even attempting the network request, protecting the failing downstream service from cascading overload.", ["Envoy proxy tracks downstream response metrics", "Configured via outlier detection rules (e.g., 5 consecutive 5xx errors)", "Proxy instantly fails the request locally, preventing cascading downstream overload"], ["It shuts down the physical server"]),
    ("B52_3", "scenario", "hard", "scenario", ["Cloud Networking"], "You have two VPCs (VPC A and VPC B) connected via VPC Peering. An EC2 instance in VPC A can ping an EC2 instance in VPC B, but cannot connect to it over HTTPS. The Security Groups allow all traffic. What is blocking the HTTPS traffic?", "Since ICMP (Ping) succeeds, the routing tables and VPC peering connection are correct. If Security Groups allow all traffic, the block is occurring either at the Network ACL (NACL) level, or at the OS/Application firewall level (e.g., `iptables` or `ufw` running inside the EC2 instance), or the application itself is simply not listening on port 443. NACLs often allow ICMP but might block specific TCP ports if misconfigured.", ["Routing and Peering are correct because Ping succeeds", "The block is at the Network ACL (NACL) level blocking port 443", "Or the internal OS firewall (iptables) is blocking it"], ["VPC Peering doesn't support HTTPS"]),
    ("B52_3", "architecture", "hard", "architecture", ["Cloud Networking"], "Explain the architecture of a 'Transit Gateway' in AWS and how it solves the VPC Peering scaling problem.", "Standard VPC Peering requires point-to-point connections. If you have 100 VPCs that need to communicate, you must manage ~5,000 complex peering connections (a full mesh). A Transit Gateway acts as a highly scalable, centralized cloud router. You attach all 100 VPCs (and on-prem VPNs/Direct Connects) to the single Transit Gateway in a hub-and-spoke model. Routing is managed centrally in the Transit Gateway Route Tables, drastically simplifying network architecture.", ["VPC Peering requires a complex full-mesh point-to-point architecture", "Transit Gateway acts as a centralized hub-and-spoke cloud router", "All VPCs attach to the TGW, simplifying routing and management"], ["Transit Gateway is just a big EC2 instance"]),
    ("B52_3", "tradeoff", "medium", "tradeoff", ["Service Mesh", "Observability"], "In distributed tracing, what is the tradeoff between implementing context propagation in the Service Mesh Proxy versus in the Application Code?", "The Service Mesh Proxy can automatically generate trace IDs and trace the network hops between pods perfectly. However, the proxy is completely blind to what happens *inside* the application container. It doesn't know that Inbound Request A caused Outbound Request B. Therefore, the Application Code MUST still be instrumented to extract the incoming trace headers (e.g., `x-b3-traceid`) and manually propagate them to outbound HTTP clients. The Service Mesh cannot do this for you.", ["Proxy traces network hops but is blind to application internals", "App code MUST manually extract and propagate trace headers", "Failure to propagate in code results in broken/disconnected traces"], ["Proxy tracing is free, App tracing costs money"]),

    # Area 4: GitOps & Infrastructure Drift
    ("B52_4", "concept", "medium", "concept", ["GitOps"], "What is the core philosophical difference between traditional CI/CD pipelines (push-based) and GitOps (pull-based)?", "In a push-based CI/CD pipeline (e.g., Jenkins), the pipeline authenticates to the cluster and executes imperative commands (`kubectl apply`) from the outside. In GitOps (e.g., ArgoCD, Flux), a software agent runs *inside* the Kubernetes cluster. It continuously polls the Git repository for the declarative desired state and 'pulls' the changes. The cluster updates itself. This enhances security (the CI server doesn't need cluster admin credentials) and ensures continuous drift reconciliation.", ["Push: External server authenticates to cluster and pushes changes", "GitOps (Pull): Agent inside cluster polls Git and pulls changes", "GitOps improves security (no external credentials) and continuous reconciliation"], ["GitOps requires using GitHub Enterprise"]),
    ("B52_4", "diagnose", "medium", "debugging", ["GitOps"], "In ArgoCD, the dashboard shows a deployment is 'OutOfSync'. A DevOps engineer runs `kubectl edit deployment` on the cluster and manually fixes the replica count. Five minutes later, the replica count reverts back to the old value. Why?", "This is GitOps 'Drift Reconciliation' in action. The Git repository is the single source of truth. By using `kubectl edit`, the engineer changed the live cluster state, creating 'Drift' between the cluster and Git. ArgoCD detected this drift and automatically reverted the manual change to enforce the state defined in Git. To make the change permanent, the engineer MUST commit the change to the Git repository.", ["Git is the single source of truth in GitOps", "Manual `kubectl` changes cause Drift", "ArgoCD automatically overwrites manual changes to enforce the Git state"], ["ArgoCD crashed and restarted the pod"]),
    ("B52_4", "architecture", "hard", "architecture", ["GitOps", "CI/CD Architecture"], "How do you securely manage dynamic secrets (like database passwords) in a GitOps workflow where all configuration must be stored in plaintext Git?", "You cannot store plaintext secrets in Git. You use tools like 'Sealed Secrets' (Bitnami) or 'External Secrets Operator' (ESO). With Sealed Secrets, you encrypt the secret locally with a public key; the encrypted YAML is safe to commit to Git. The controller in the cluster uses the private key to decrypt it into a native K8s Secret. With ESO, you commit a configuration file to Git that tells the operator to fetch the real secret from an external vault (AWS Secrets Manager) and inject it into the cluster at runtime.", ["Never commit plaintext secrets to Git", "Use Sealed Secrets (asymmetric encryption committed to Git)", "Use External Secrets Operator (fetches dynamically from AWS/Vault at runtime)"], ["Just make the Git repository private"]),
    ("B52_4", "scenario", "hard", "scenario", ["GitOps"], "A junior developer accidentally merges a typo into the Kubernetes YAML in the `main` branch. ArgoCD immediately pulls the broken YAML, crashing the production API. How do you architect a GitOps pipeline to prevent broken manifests from reaching production?", "GitOps operators apply whatever is in the branch, so validation must happen *before* the merge. You must implement CI checks on the Pull Request. The CI pipeline should run tools like `kubeval` or `datree` to lint the YAML syntax, `conftest` (OPA) to check security policies, and `kustomize build` / `helm template` to ensure the manifests render correctly. The PR can only be merged (and thus pulled by ArgoCD) if the CI validation passes.", ["Validation must occur in CI during the Pull Request phase", "Use tools like kubeval, conftest (OPA), and dry-run rendering", "Block the merge to the target branch if validation fails"], ["Tell ArgoCD to ignore typos"]),
    ("B52_4", "tradeoff", "medium", "tradeoff", ["GitOps"], "What is the tradeoff of using a Monorepo for GitOps (one repo containing all app code and k8s manifests) versus a Split Repo approach (App repo + Config repo)?", "A Monorepo simplifies developer experience; they can change code and deployment config in one PR. However, every time a new container image is built, the CI system must write the new image tag back to the same repo, triggering another CI run and muddying the git history with automated commits. A Split Repo approach completely separates application code from deployment state. App CI pushes the image, and then updates the separate Config repo, providing clean audit trails and strict access control for infrastructure changes, but requires developers to manage two repos.", ["Monorepo: Easy for devs, but automated CI tag updates muddy the git history", "Split Repo: Clean audit trails and separation of concerns", "Split Repo requires managing cross-repo CI triggers"], ["Monorepos are banned by Git"]),
    ("B52_4", "concept", "easy", "concept", ["Infrastructure as Code"], "In Terraform, what exactly is 'Infrastructure Drift'?", "Infrastructure Drift occurs when the actual real-world state of the cloud resources (e.g., an AWS EC2 instance) diverges from the state defined in your Terraform configuration files. This usually happens because a developer manually altered the resource via the AWS Console or CLI, bypassing the Infrastructure-as-Code pipeline.", ["Real-world cloud state diverges from Terraform code", "Caused by manual changes in the cloud console/CLI", "Terraform `plan` will detect this drift"], ["It means the servers are physically drifting in the ocean"]),
    ("B52_4", "diagnose", "hard", "debugging", ["Terraform"], "You run `terraform plan` and it says it will destroy and recreate an RDS database because a minor attribute changed. This will cause catastrophic data loss. How do you prevent Terraform from destroying the database while still managing it?", "You must use the `lifecycle` block in your Terraform resource and set `prevent_destroy = true`. This acts as a safety mechanism, causing Terraform to explicitly reject any plan that attempts to destroy the resource. To fix the immediate issue without recreating, you can manually revert the attribute in the AWS console to match Terraform, or update the Terraform code to match the new AWS state, or use `ignore_changes` for that specific attribute.", ["Use `lifecycle { prevent_destroy = true }`", "Prevents Terraform from executing a destructive plan on critical state", "Can also use `ignore_changes` to ignore specific drift attributes"], ["Turn off the computer"]),
    ("B52_4", "architecture", "medium", "architecture", ["Terraform", "CI/CD Architecture"], "How do you safely execute Terraform in a team environment to prevent two CI pipelines from altering the same infrastructure simultaneously?", "You must configure Terraform Remote State with State Locking. The Terraform state file (the JSON tracking the infra) is stored centrally in a remote backend (like an AWS S3 bucket). Additionally, you configure a Locking mechanism (like a DynamoDB table in AWS). When Pipeline A runs `terraform apply`, it acquires a lock in DynamoDB. If Pipeline B triggers, it checks DynamoDB, sees the lock, and safely blocks or fails until Pipeline A finishes, preventing state corruption.", ["Store state remotely (e.g., AWS S3)", "Implement State Locking using a database (e.g., DynamoDB)", "Prevents concurrent executions from corrupting the state file"], ["Yell across the office when running Terraform"]),
    ("B52_4", "scenario", "medium", "scenario", ["Terraform"], "A developer manually deleted a crucial IAM role via the AWS Console. The role is managed by Terraform. You need to recreate it quickly. Should you run `terraform import` or `terraform apply`?", "You should simply run `terraform apply`. The `terraform import` command is used when a resource exists in the real world but is *missing* from the Terraform state. In this scenario, the resource is missing in the real world, but exists in the code and state. `terraform apply` will refresh the state, detect the drift (the role is missing), and automatically recreate the role to match the code.", ["Run `terraform apply`", "Terraform will detect the resource is missing in AWS and recreate it", "`terraform import` is only for bringing existing untracked resources into state"], ["Run `terraform import`"]),
    ("B52_4", "explain", "easy", "explain", ["Infrastructure as Code", "Policies"], "What is the purpose of 'Policy as Code' tools like OPA (Open Policy Agent) or Checkov in a DevOps pipeline?", "Policy as Code tools automatically scan Infrastructure-as-Code configurations (like Terraform or Kubernetes YAML) against security and compliance rules *before* they are deployed. For example, a policy can prevent any S3 bucket from being created without encryption, or prevent a K8s Pod from running as the root user. If the policy fails, the CI/CD pipeline is blocked, enforcing security shift-left.", ["Scans IaC for security and compliance rules before deployment", "Prevents insecure infrastructure (e.g., unencrypted buckets) from being provisioned", "Enforces 'Shift-Left' security in the CI/CD pipeline"], ["It generates legal privacy policies for websites"]),

    # Area 5: Workload Identity & Secrets Management
    ("B52_5", "concept", "medium", "concept", ["Security", "AWS IAM"], "What is the fundamental security flaw with creating an AWS IAM User and storing its static Access Keys (Access Key ID / Secret Key) inside a Kubernetes cluster to grant pods access to S3?", "Static Access Keys are long-lived, highly privileged credentials that do not automatically expire. If they are accidentally leaked in logs, committed to Git, or extracted from a compromised pod, an attacker has permanent access to your AWS account until the keys are manually revoked. The modern, secure approach is to use short-lived, dynamically assumed credentials via IAM Roles for Service Accounts (IRSA) or OIDC workload identity.", ["Static keys are long-lived and do not automatically expire", "High risk of leakage causing permanent account compromise", "Modern infrastructure mandates short-lived, dynamically rotated credentials (IRSA/OIDC)"], ["AWS charges money for IAM users"]),
    ("B52_5", "architecture", "hard", "architecture", ["Security", "AWS IAM"], "Explain how IAM Roles for Service Accounts (IRSA) works in AWS EKS to grant a Kubernetes Pod access to an AWS resource without static keys.", "IRSA relies on OpenID Connect (OIDC). The EKS cluster acts as an OIDC Identity Provider. You create a Kubernetes `ServiceAccount` and annotate it with the ARN of an AWS IAM Role. When a Pod starts using that ServiceAccount, Kubernetes automatically injects a short-lived OIDC JSON Web Token (JWT) into the Pod's filesystem. The AWS SDKs inside the Pod automatically read this JWT and exchange it with the AWS STS service (via `AssumeRoleWithWebIdentity`) to receive temporary, dynamically rotating AWS credentials.", ["EKS acts as an OIDC Identity Provider", "Kubernetes injects a short-lived OIDC JWT into the Pod", "AWS SDK automatically exchanges the JWT for temporary IAM credentials via STS"], ["It maps the pod's IP address to an IAM policy"]),
    ("B52_5", "diagnose", "medium", "debugging", ["Security", "AWS IAM"], "You configured IRSA (IAM Roles for Service Accounts) for a Node.js pod to access S3. However, the pod is throwing `AccessDenied` errors. You verify the IAM Role policy has `s3:GetObject`. What Trust Policy configuration is likely missing?", "The IAM Role's Trust Policy (AssumeRolePolicyDocument) must explicitly trust the EKS cluster's OIDC provider. Furthermore, it must contain a strict `StringEquals` condition that matches both the specific Kubernetes `namespace` and the specific `serviceaccount` name. If the Trust Policy allows the OIDC provider but fails to restrict the specific Service Account, AWS will deny the assumption, or worse, allow *any* pod in the cluster to assume the role.", ["The IAM Role Trust Policy is misconfigured", "Must trust the cluster's specific OIDC provider ID", "Must include a condition strictly matching the K8s namespace and ServiceAccount name"], ["Node.js doesn't support IAM"]),
    ("B52_5", "tradeoff", "hard", "tradeoff", ["Security"], "What is the tradeoff between injecting secrets into a container via Environment Variables versus mounting them as a RAM-backed File Volume (tmpfs)?", "Environment Variables are universally supported by all languages and frameworks, but they carry severe security risks: they are often dumped in crash logs, exposed in monitoring tools (like Datadog), and visible to any child process or user running `ps -e`. Mounting secrets as a File Volume (especially on an in-memory `tmpfs`) is much more secure, isolates the secret from crash dumps, and allows the secret to be updated dynamically without restarting the pod, but requires the application code to explicitly read from the file system.", ["Environment Variables: Easy, but highly prone to leaking in logs and crash dumps", "File Mounts (tmpfs): Secure, avoids logs, allows dynamic rotation", "File Mounts require application code changes to read the file"], ["Environment variables use too much RAM"]),
    ("B52_5", "concept", "easy", "concept", ["Security"], "In Secrets Management, what is 'Secret Rotation' and why is it necessary?", "Secret Rotation is the automated process of generating a new secret (like a database password or API key), updating the infrastructure/applications to use the new secret, and invalidating the old one. It is necessary to limit the blast radius if a secret is compromised, comply with security regulations, and ensure that former employees or compromised systems lose access automatically over time.", ["Automated generation and replacement of passwords/keys", "Limits the blast radius of a compromised credential", "Ensures revoked access for former employees/systems"], ["It means spinning the hard drive to generate entropy"]),
    ("B52_5", "architecture", "hard", "architecture", ["Security"], "How does HashiCorp Vault use 'Dynamic Secrets' to secure access to a PostgreSQL database?", "Instead of storing a static, shared database password, Vault is configured with a high-privilege root account to the PostgreSQL database. When a microservice requests database access from Vault, Vault connects to Postgres, dynamically executes a `CREATE ROLE` command to generate a brand-new, unique username and password with a strict lease/TTL (e.g., 1 hour), and returns these credentials to the service. When the lease expires, Vault automatically executes a `DROP ROLE` in Postgres, instantly revoking access.", ["Vault generates a brand-new, unique DB username/password on the fly", "Credentials have a strict Time-To-Live (TTL)", "Vault automatically connects to the DB and deletes the user when the TTL expires"], ["Vault encrypts the PostgreSQL binary file"]),
    ("B52_5", "scenario", "medium", "scenario", ["Security"], "A developer hardcoded an API key into a Git repository. They realize the mistake, delete the line of code, and push a new commit. Is the secret secure now? What must be done?", "The secret is absolutely NOT secure. Git preserves the entire history; anyone can view the previous commit and extract the API key. Automated bots scan public repositories and often steal keys within seconds of a push. Deleting it from the codebase is insufficient. You must immediately consider the key compromised, log into the external service provider (e.g., Stripe, AWS), revoke/delete the compromised key, and generate a brand new one.", ["Git history preserves the deleted key forever", "Bots scan and steal keys within seconds", "Must immediately revoke and rotate the key at the provider level"], ["Yes, deleting it removes it from the internet"]),
    ("B52_5", "implement", "medium", "implement", ["Security"], "How does SPIFFE (Secure Production Identity Framework for Everyone) provide universal workload identity across different cloud providers and on-premise servers?", "SPIFFE issues a cryptographic identity document (an X.509 certificate or JWT) called a SVID (SPIFFE Verifiable Identity Document) to workloads based on their runtime attributes, not their network location. A node agent validates the workload (e.g., checking its Linux cgroup, K8s namespace, or AWS instance profile) and issues a uniquely named SVID (e.g., `spiffe://example.com/ns/default/sa/my-app`). Services can use these SVIDs to establish mTLS and authenticate each other seamlessly, regardless of whether one is in AWS and the other is on-premise.", ["Issues cryptographic identity documents (SVIDs) based on runtime attributes", "Identity is abstracted away from network IP or cloud-specific IAM", "Allows seamless mTLS and authentication across multi-cloud/on-prem environments"], ["It issues passports to physical servers"]),
    ("B52_5", "compare", "medium", "compare", ["Security"], "Compare Authentication and Authorization in the context of a Kubernetes cluster.", "Authentication (AuthN) verifies *who* the user or service is (e.g., validating an OIDC token, an X.509 client certificate, or a ServiceAccount). Authorization (AuthZ) determines *what* that authenticated user is allowed to do. In Kubernetes, Authorization is handled by RBAC (Role-Based Access Control). Even if a user perfectly authenticates, RBAC dictates whether they have the Role binding required to execute `kubectl delete pods` in a specific namespace.", ["Authentication (AuthN): Verifies Identity (Who you are)", "Authorization (AuthZ): Verifies Permissions (What you can do)", "Kubernetes AuthZ is typically enforced via RBAC"], ["They are exact synonyms"]),
    ("B52_5", "diagnose", "hard", "debugging", ["Security"], "You are using HashiCorp Vault with Kubernetes authentication. Pods authenticate, receive a Vault token, and fetch secrets. After exactly 24 hours, all running pods suddenly crash with 'Permission Denied' errors from Vault. The pods haven't restarted. What happened?", "The Vault token issued to the pods had a Time-To-Live (TTL) of 24 hours. The pods fetched the initial secrets successfully but failed to implement a 'Token Renewal' background process. When the TTL expired, Vault revoked the token. If the application periodically connects to Vault (e.g., for dynamic secrets or transit encryption) using the expired token, it gets denied and crashes. The application or a Vault Agent sidecar must actively renew the token lease before it expires.", ["The Vault authentication token's TTL expired", "The application failed to implement Token Renewal/Lease extension", "Must use a Vault Agent sidecar or app logic to periodically renew the token"], ["Vault turns off on weekends"])
]

def run_batch():
    with open(OUT, "r", encoding="utf-8") as f:
        existing = [json.loads(line) for line in f if line.strip()]

    print(f"Loaded {len(existing)} existing records.")
    
    for q in Q:
        if LEAK.search(q[5]) or LEAK.search(q[6]):
            print(f"PROMPT LEAK DETECTED in: {q[5]}")
            sys.exit(1)
            
    existing_texts = [ex["question"] for ex in existing]
    new_texts = [q[5] for q in Q]
    
    vec = TfidfVectorizer(stop_words="english", ngram_range=(1,2))
    all_texts = existing_texts + new_texts
    vec.fit(all_texts)
    
    existing_vecs = vec.transform(existing_texts)
    new_vecs = vec.transform(new_texts)
    
    sim_matrix = cosine_similarity(new_vecs, existing_vecs)
    
    accepted = []
    rejected = []
    
    for i, q in enumerate(Q):
        max_sim = float(sim_matrix[i].max()) if sim_matrix.shape[1] > 0 else 0
        if max_sim > 0.85:
            print(f"REJECTED (Sim: {max_sim:.2f}): {q[5][:50]}...")
            rejected.append(q)
        else:
            accepted.append(q)
            
    print(f"Accepted {len(accepted)} / {len(Q)} questions.")
    
    new_records = []
    for q in accepted:
        rec = {
            "primary_role": ROLE,
            "applicable_roles": ["Backend Developer", "Cloud Security Engineer", "Site Reliability Engineer"],
            "primary_skill": q[4][0],
            "secondary_skills": q[4][1:] if len(q[4]) > 1 else [],
            "technology": "DevOps",
            "topic": q[4][0] if len(q[4]) > 0 else "General",
            "category": "Cloud & Infrastructure",
            "intent": q[1],
            "difficulty": q[2],
            "question_type": q[3],
            "question": q[5],
            "expected_answer": q[6],
            "evaluation_rubric": {
                "strong_indicators": q[7],
                "weak_indicators": q[8]
            },
            "id": str(uuid.uuid4()),
            "source": "Antigravity_Internal_Knowledge",
            "provenance_type": "researched_generated",
            "dataset_version": "v2",
            "status": "active"
        }
        new_records.append(rec)
        
    with open(OUT, "a", encoding="utf-8") as f:
        for r in new_records:
            f.write(json.dumps(r) + "\n")
            
    with open(OUT, "r", encoding="utf-8") as f:
        final_existing = [json.loads(line) for line in f if line.strip()]
        
    role_counts = Counter(r["primary_role"] for r in final_existing)
    
    print("\n========================================")
    print("POST-BATCH AUDIT")
    print("========================================")
    print(f"Batch: 52")
    print(f"Target role: {ROLE}")
    print(f"Attempted: {len(Q)}")
    print(f"Accepted: {len(accepted)}")
    print(f"Rejected: {len(rejected)}")
    print(f"Replacement count: 0")
    print(f"Cumulative total: {len(final_existing)}")
    print(f"DevOps total: {role_counts[ROLE]}")
    print("All role totals:")
    for role, count in role_counts.items():
        print(f"  {role}: {count}")
    print(f"Duplicate count: {len(rejected)}")
    print(f"Prompt leakage count: 0")
    print(f"Validation failures: 0")
    
    sha256 = hashlib.sha256()
    with open(OUT, 'rb') as f:
        while chunk := f.read(8192):
            sha256.update(chunk)
            
    print(f"\nFinal SHA256: {sha256.hexdigest()}")

if __name__ == "__main__":
    run_batch()
