import asyncio
import json
import os
import re
import sys
import uuid
import hashlib
from collections import Counter

from dotenv import load_dotenv
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
load_dotenv()

BACKEND_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_DIR = os.path.join(BACKEND_DIR, "data")
OUT = os.path.join(DATA_DIR, "interview_question_bank_v2_generated.jsonl")

ROLE = "Data Analyst"
LEAK = re.compile(r"(generate a question|generate \d+ questions|return only json|phase 4c gap plan|"
                  r"generation batch|candidate generation|system prompts|do not proceed|"
                  r"awaiting authorization|minimum target|generation pipeline|"
                  r"batch \d+ generation|expected answer|strong indicator|weak indicator|as an ai|"
                  r"here is the question|\bprompt text\b)", re.I)

Q = [
    # Area 1: Cohort, Retention, Funnels
    ("B57_1", "concept", "medium", "concept", ["Product Analytics"], "What is the difference between N-Day Retention and Unbounded (Rolling) Retention, and when would you use each?", "N-Day Retention measures if a user returned EXACTLY on Day N after their acquisition (e.g., played a mobile game exactly on Day 7). It is strict and used for high-frequency daily habits. Unbounded Retention measures if a user returned ON OR AFTER Day N (e.g., booked a flight anytime after Day 30). Unbounded is used for low-frequency products like travel or e-commerce where users aren't expected to return on a specific calendar day.", ["N-Day requires return on exact day; Unbounded requires return on or after the day", "N-Day suited for high-frequency (social media, gaming)", "Unbounded suited for low-frequency (travel, e-commerce)"], ["N-Day means they stayed for N consecutive days"]),
    ("B57_1", "diagnose", "hard", "debugging", ["Product Analytics"], "Your SaaS company's overall Month-over-Month retention rate has been slowly increasing for the past 6 months. However, the product team hasn't released any new features. You perform a cohort analysis. What phenomenon mathematically explains this overall increase without underlying product improvement?", "This is a classic 'Mix Shift' or survivorship bias effect. Older cohorts naturally have higher retention rates (the users who stay for 12 months are highly loyal). As a SaaS company ages, the proportion of old, loyal users in the denominator grows relative to new, high-churn users. Even if the actual Month 1 retention of *new* cohorts is completely flat or slightly declining, the mathematical average of the whole user base artificially inflates as the 'mix' shifts toward tenured survivors.", ["Mix Shift / Survivorship Bias", "Older, loyal cohorts make up a larger percentage of the total user base over time", "Averages inflate even if specific cohort retention curves are flat"], ["The marketing team bought better ads"]),
    ("B57_1", "implement", "hard", "implement", ["SQL Analytics"], "How do you calculate strict N-Day retention using SQL from a generic `user_logins` event table?", "You first create a CTE to find each user's acquisition date (`MIN(login_date)`). You join this back to the `user_logins` table to calculate the delta in days between their subsequent logins and their acquisition date (`DATEDIFF(login_date, acquisition_date)`). Finally, you aggregate by `acquisition_date` (the cohort) and `COUNT(DISTINCT user_id)` for delta=0 (Cohort Size), delta=1 (Day 1 retained), delta=7, etc., often pivoting the results using `CASE WHEN` statements.", ["Find acquisition date per user using `MIN()`", "Join back to events and calculate `DATEDIFF` between event and acquisition", "Group by acquisition cohort and pivot the distinct user counts based on the delta"], ["Just count all the rows where day = N"]),
    ("B57_1", "scenario", "medium", "scenario", ["Product Analytics"], "A PM notices the 'Sign Up' to 'Purchase' conversion funnel dropped from 10% to 5% yesterday. What three analytical dimensions do you slice the funnel data by to diagnose the root cause?", "To isolate the root cause, I would slice the funnel drop-off by: 1) Device/Platform (e.g., did an iOS app update break the checkout button?), 2) Acquisition Channel/Source (e.g., did a new spammy ad campaign bring in thousands of low-intent users, inflating the denominator?), and 3) Geography/Region (e.g., did a specific country's payment gateway go down?).", ["Device/Platform (OS, Browser, App Version)", "Acquisition Channel/Traffic Source (Ads, Organic, Referrals)", "Geography/Region (Country, State, Payment Gateways)"], ["I would slice it by age, gender, and income"]),
    ("B57_1", "tradeoff", "medium", "tradeoff", ["Product Analytics"], "What is the tradeoff of defining an 'Active User' (for DAU/MAU) as 'Anyone who opens the app' versus 'Anyone who completes a core action'?", "Defining 'Active' as just opening the app inflates the metric (looks good to investors) and is easy to track universally. The tradeoff is that it includes accidental clicks, push notification dismissals, and bounced sessions, completely obscuring true product value. Defining 'Active' as completing a core action (e.g., sending a message, playing a song) results in a much smaller, stricter number, but it perfectly aligns with actual value delivery and correlates strongly with long-term retention and revenue.", ["'App Open' inflates numbers but includes accidental/zero-value sessions", "'Core Action' yields a smaller number but perfectly correlates with actual value and retention", "Tradeoff between vanity metrics (high volume) and actionable metrics (high signal)"], ["Core actions cost more database storage to track"]),
    ("B57_1", "explain", "hard", "explain", ["Product Analytics"], "Explain 'Smile Curve' retention and why it happens.", "Standard retention curves look like an 'L' (steep drop-off, then flatlining). A 'Smile Curve' drops initially but then actually starts trending *upward* over time (retention increases in later months). This happens in products with strong network effects (like Evernote or Slack) where the product becomes vastly more valuable the longer you use it or the more colleagues you invite. Old users who had churned eventually return (resurrection) because their team adopted it or they need their historical data, causing the curve to smile.", ["Retention drops initially, then trends upward in later periods", "Driven by strong network effects or accumulating data lock-in", "Older churned users 'resurrect' because the product value compounded over time"], ["It happens when the UI is redesigned to be happy"]),
    ("B57_1", "diagnose", "medium", "debugging", ["Product Analytics"], "You build a 3-step funnel: Landing Page -> Cart -> Checkout. The funnel conversion rate is exactly 100% from step 2 to step 3, which is practically impossible. What data tracking error likely caused this?", "A 100% conversion usually indicates a tracking implementation error where the events are inextricably linked or misconfigured. For example, the 'Cart' event and 'Checkout' event might be firing on the exact same button click on the frontend, or a backend API automatically fires both events sequentially without requiring user interaction. It means Step 2 mathematically cannot happen without Step 3 firing instantly alongside it.", ["Frontend tracking error: both events bound to the exact same button click", "Backend error: API fires both events sequentially automatically", "Step 2 is structurally incapable of firing without Step 3"], ["The users are just highly motivated to buy"]),
    ("B57_1", "concept", "easy", "concept", ["Product Analytics"], "What is a 'North Star Metric'?", "A North Star Metric is a single, company-wide key performance indicator that best captures the core value a product delivers to its customers. It serves to align all teams (product, marketing, engineering) toward a common goal. For example, Airbnb's might be 'Nights Booked', and WhatsApp's might be 'Messages Sent'. It should be a leading indicator of future revenue, not a lagging indicator like 'Total Monthly Revenue'.", ["A single company-wide metric capturing the core value delivered to customers", "Aligns all cross-functional teams toward a common objective", "A leading indicator of growth and retention, not a lagging financial metric"], ["It is a metric used only at nighttime"]),
    ("B57_1", "architecture", "hard", "architecture", ["Product Analytics"], "In event-driven analytics, what is the architectural difference between 'Client-Side Tracking' and 'Server-Side Tracking'?", "Client-side tracking executes JavaScript in the user's browser/app to send events directly to analytics servers (like Mixpanel). It easily captures rich UI context (scroll depth, mouse clicks, UTM parameters) but is highly vulnerable to Ad Blockers (losing 20-30% of data) and network drops. Server-side tracking triggers events from the backend database/server. It is 100% reliable, bypasses Ad Blockers, and is secure for sensitive data (like exact purchase revenue), but lacks visibility into frontend UI interactions.", ["Client-side runs in the browser: captures rich UI interactions but blocked by Ad Blockers", "Server-side runs on the backend: 100% reliable and secure, bypasses blockers", "Server-side lacks context on frontend UI states (e.g., time spent looking at a button)"], ["Client-side is for Apple, Server-side is for Android"]),
    ("B57_1", "scenario", "medium", "scenario", ["Product Analytics"], "You want to measure the success of a new 'Invite Friends' feature. You track the total number of invites sent. Why is this a flawed success metric, and what metric should you use instead?", "Total invites sent is a vanity metric; a user could spam 100 fake email addresses, inflating the metric while delivering zero value to the business. To measure true success, you must track the 'K-Factor' or 'Viral Loop Conversion'. You should track the number of *Successful Acceptances* (new user registrations) generated per inviting user, and ultimately the Day 7 retention of those new users to ensure they are high-quality acquisitions.", ["Total invites is a vanity metric prone to spam/abuse", "Does not measure actual value or user acquisition", "Should track 'Invites Accepted' (conversion rate) and the retention of the acquired users"], ["You should track the color of the invite button"]),

    # Area 2: Advanced Experiment Design & Stats
    ("B57_2", "concept", "medium", "concept", ["A/B Testing"], "What is 'Statistical Power' in an A/B test, and why is it usually set to 80%?", "Statistical Power (1 - Type II Error rate) is the probability that a test will correctly detect a true effect if one actually exists (avoiding a false negative). Setting it to 80% means we accept a 20% risk of failing to detect a successful feature. It is a mathematical tradeoff: demanding 90% or 95% power requires exponentially larger sample sizes, which drastically slows down the speed of product experimentation. 80% is the industry standard balance between detecting winners and velocity.", ["Probability of correctly detecting a true effect (avoiding false negatives)", "Requires a tradeoff with sample size; higher power requires vastly more users", "80% is the industry compromise between detection accuracy and experiment velocity"], ["Power is how much electricity the server uses during the test"]),
    ("B57_2", "diagnose", "hard", "debugging", ["A/B Testing"], "An A/B test on a button color concludes. The p-value is 0.04, meaning it is statistically significant (p < 0.05). However, the PM checked the dashboard every day for two weeks, and on Day 10 the p-value dipped to 0.04, so they stopped the test early and declared a winner. What statistical sin was committed?", "This is 'Peeking' (or continuous monitoring without correction). P-values fluctuate randomly over time. If you continuously check a test and stop it the exact moment it crosses the 0.05 threshold, you massively inflate the False Positive (Type I Error) rate. Even if the feature has zero real effect, random variance guarantees that the p-value will eventually dip below 0.05 temporarily if you check it enough times. You must wait for the predetermined sample size, or use Sequential Testing frameworks (like SPRT).", ["'Peeking' inflates the False Positive (Type I Error) rate", "Random variance guarantees temporary dips below p=0.05 if checked continuously", "Fix by committing to a fixed sample size beforehand or using Sequential Testing"], ["The PM forgot to tell the engineers to stop coding"]),
    ("B57_2", "tradeoff", "medium", "tradeoff", ["A/B Testing"], "What is the tradeoff of running an A/B test for 2 days to reach sample size, versus running it for 2 full weeks?", "If your site has massive traffic, you might reach statistical power in 2 days. However, the severe tradeoff is that you fail to capture 'Day of Week' seasonality (e.g., weekend users behave entirely differently than weekday users). Furthermore, short tests suffer from 'Novelty Effects', where users click a new feature simply because it's new, skewing the metrics. Running for full 7-day or 14-day cycles normalizes weekly seasonality and allows novelty effects to stabilize.", ["2 days captures enough sample size quickly but ignores time-based behavioral variance", "Fails to capture 'Day of Week' seasonality (weekend vs weekday)", "Highly vulnerable to 'Novelty Effects' (users clicking just because it's new)"], ["2 weeks costs too much in AWS fees"]),
    ("B57_2", "explain", "hard", "explain", ["Statistical Reasoning"], "Explain the 'Multiple Comparisons Problem' (Family-wise Error Rate). How do you adjust for it?", "If you run an A/B test and check 20 different metrics simultaneously (conversion, retention, clicks, time-on-page) using a 5% significance level, the probability of at least one metric showing a false positive is roughly 1 - (0.95)^20 = 64%. By testing multiple hypotheses, you practically guarantee a false positive. To fix this, you must adjust the p-value threshold, most commonly using the Bonferroni Correction (divide your alpha, 0.05, by the number of metrics, 20, making the new threshold 0.0025).", ["Checking multiple metrics simultaneously exponentially increases the False Positive rate", "With 20 metrics at 5% alpha, a false positive is highly likely (~64%)", "Adjust the threshold using corrections like Bonferroni (alpha / number of tests)"], ["You should just delete the metrics that fail"]),
    ("B57_2", "scenario", "medium", "scenario", ["A/B Testing"], "You run an A/B test for 14 days. The results show exactly 0% uplift in conversion, with a p-value of 0.80. The PM says 'The test failed, the new feature is worse.' How do you correct the PM statistically?", "A p-value of 0.80 means we failed to reject the null hypothesis; it does NOT prove the null hypothesis is true (that the feature is exactly 0% different). More importantly, the test didn't 'fail' to be worse, it failed to be *statistically detectably better*. You must look at the Confidence Interval. If the CI is [-2%, +2%], you can confidently say the feature has no meaningful business impact. If the CI is [-15%, +15%], the test simply didn't have enough power to conclude anything.", ["Failing to reject the null hypothesis does not prove the new feature is exactly equal or worse", "Must evaluate the Confidence Interval, not just the p-value", "A wide CI means insufficient power; a narrow CI around 0 means no business impact"], ["I would agree with the PM to save time"]),
    ("B57_2", "implement", "hard", "implement", ["A/B Testing"], "How do you calculate the Minimum Detectable Effect (MDE) required for an A/B test before it starts?", "MDE is calculated using the Baseline Conversion Rate, the desired Statistical Power (usually 80%), the Significance Level (usually 5%), and the expected Sample Size (Traffic). You input these parameters into a power calculator (based on the standard error of proportions). The MDE tells you the smallest true uplift you can reliably detect. If your site only gets 1,000 visitors a week, your MDE might be 20%—meaning unless the feature causes a massive 20% spike, the test is mathematically useless and will just return noise.", ["Requires Baseline Conversion, Power (80%), Alpha (5%), and Sample Size", "Uses standard error formulas for proportions to output the required effect size", "Determines the smallest uplift the test can reliably detect without drowning in noise"], ["You guess a number between 1 and 10"]),
    ("B57_2", "concept", "easy", "concept", ["Statistical Reasoning"], "What is the difference between a Type I and Type II error in hypothesis testing?", "A Type I Error (False Positive) occurs when you conclude that a feature worked, but it actually had zero effect (you got lucky with random variance). A Type II Error (False Negative) occurs when a feature actually worked, but your test failed to detect it (usually due to small sample size). We control Type I errors with the significance level (alpha, usually 5%), and Type II errors with Statistical Power (usually 80%).", ["Type I: False Positive (claiming an effect exists when it doesn't)", "Type II: False Negative (failing to detect a real effect)", "Controlled by Alpha (5%) and Statistical Power (80%) respectively"], ["Type 1 is hardware error, Type 2 is software error"]),
    ("B57_2", "diagnose", "medium", "debugging", ["A/B Testing"], "You run an A/B test on a pricing page. Users are randomly assigned to A (Control) or B (Variant) based on their `user_id`. You notice that Variant B has 55% of the total traffic, while A has 45%. Is this a valid test?", "No, this is a severe 'Sample Ratio Mismatch' (SRM). Random assignment should result in a 50/50 split (within statistical variance). A 55/45 split on a large sample size has a p-value of essentially 0, indicating a systemic bug in the assignment mechanism. Perhaps Variant B causes the app to crash before logging the assignment, or the hashing algorithm is biased. You must completely invalidate the test results, fix the logging bug, and restart.", ["Sample Ratio Mismatch (SRM): The traffic split deviates significantly from 50/50", "Indicates a severe tracking bug, hashing flaw, or crash in one variant", "Results are completely invalid and cannot be trusted"], ["Yes, 55% is close enough to 50%"]),
    ("B57_2", "architecture", "hard", "architecture", ["A/B Testing"], "How do you design a robust randomization mechanism for A/B testing that ensures a user stays in the same variant across different sessions without needing a massive database lookup table?", "You use a deterministic hashing function (like MD5 or MurmurHash). You concatenate the `user_id` (or anonymous device ID) with a unique `experiment_salt` (e.g., `hash(\"user123\" + \"pricing_test_2023\")`). You convert the hash to an integer and take modulo 100. If the result is 0-49, they get Variant A; 50-99 gets Variant B. Because the hash is deterministic, the user will always fall into the same bucket every time they log in, requiring zero database state lookups.", ["Use a deterministic hashing function (e.g., MD5, MurmurHash)", "Hash the `user_id` combined with an `experiment_salt`", "Take modulo 100 to assign buckets deterministically without database lookups"], ["Store every user assignment in a massive Redis cluster"]),
    ("B57_2", "tradeoff", "hard", "tradeoff", ["A/B Testing"], "What is the tradeoff of running a 'Network Effects' experiment (e.g., testing a new chat algorithm on WhatsApp) using standard randomized A/B testing?", "Standard A/B testing assumes the 'Stable Unit Treatment Value Assumption' (SUTVA)—that users behave independently. In a social network, if User A is in the Treatment group and gets a better chat app, they message more often. This directly impacts User B (in the Control group), who receives more messages and becomes more active, heavily contaminating the Control group metrics. The tradeoff is that standard A/B testing completely fails here. You must use cluster randomization (e.g., randomizing entire cities or friend groups) to isolate the network effect.", ["Standard A/B testing violates SUTVA (independence of users) in networks", "Treatment users alter the behavior of Control users (spillover effect)", "Must use Cluster Randomization (e.g., randomizing by city) to prevent contamination"], ["Network effects require testing on multiple WiFi routers"]),

    # Area 3: Causal Inference & Bias
    ("B57_3", "concept", "medium", "concept", ["Causal Inference"], "Explain 'Simpson's Paradox' and how it can lead to catastrophic business decisions.", "Simpson's Paradox occurs when a trend appears in multiple different groups of data but completely disappears or reverses when these groups are combined. For example, Ad Campaign A might have a higher conversion rate than Campaign B for Men, AND a higher conversion rate for Women. But overall, Campaign B has a higher conversion rate. This happens when the group sizes are vastly disproportionate (a hidden confounding variable). Making a decision on the aggregate data without stratifying can lead to choosing the mathematically inferior option.", ["A trend in stratified groups reverses when the data is aggregated", "Caused by unequal group sizes and hidden confounding variables", "Requires analysts to stratify data to avoid mathematically false conclusions"], ["Simpson's paradox is when the data is funny"]),
    ("B57_3", "diagnose", "hard", "debugging", ["Causal Inference"], "Marketing launches an email campaign. They compare the purchase rate of users who *opened* the email vs users who *did not open* the email. The open group bought 300% more. They declare the email a massive success. Why is this causally flawed?", "This is textbook 'Selection Bias' and 'Confounding by Intent'. You cannot compare openers to non-openers because the act of opening an email is a proxy for high engagement. Users who open emails are already your most loyal, high-intent customers who were probably going to buy anyway. The non-openers are churned or low-intent users. To prove causality, you must compare the purchase rate of the randomized Treatment group (people who were *sent* the email, regardless of open) against the randomized Control group (people who were *withheld* the email).", ["Selection Bias / Confounding by Intent", "Openers are inherently more engaged and likely to buy regardless of the email", "Must compare Intent-to-Treat (sent vs not sent), not opened vs not opened"], ["The email was caught in the spam filter"]),
    ("B57_3", "implement", "hard", "implement", ["Causal Inference"], "How do you implement Propensity Score Matching (PSM) to estimate the causal effect of a feature when an A/B test is impossible?", "In observational data, users who choose to use a feature are inherently different from those who don't (selection bias). PSM trains a logistic regression model using user covariates (age, tenure, past activity) to predict the *probability* (propensity score) that a user will adopt the feature. You then take a user who used the feature and pair them with a user who *didn't* use the feature, but who has the exact same propensity score. By comparing only these statistically identical matched pairs, you isolate the causal effect of the feature from the underlying confounding variables.", ["Train a logistic regression to predict the probability of feature adoption based on covariates", "Match users who adopted the feature with non-adopters who have identical propensity scores", "Compare the outcomes of the matched pairs to isolate the causal effect"], ["You swipe left or right on users until they match"]),
    ("B57_3", "scenario", "medium", "scenario", ["Causal Inference"], "A hospital analyzes its data and finds that patients who use a highly expensive, advanced breathing machine die at a much higher rate than patients who use standard oxygen masks. Does this mean the advanced machine kills patients?", "No, this is a classic confounding variable scenario (Confounding by Indication). The underlying severity of the illness dictates both the treatment and the outcome. Only the most critically ill, dying patients are prescribed the advanced breathing machine, while relatively healthy patients get the standard mask. The machine doesn't cause death; the critical illness causes both the use of the machine and the death. You must control for patient severity before analyzing the treatment effect.", ["Confounding by Indication (disease severity is the confounding variable)", "Only the most critically ill patients are assigned the advanced treatment", "Must control for patient baseline health to determine true causality"], ["Yes, the machine is clearly broken"]),
    ("B57_3", "tradeoff", "medium", "tradeoff", ["Causal Inference"], "What is the tradeoff of using Observational Data Analysis (like Regression or PSM) versus a Randomized Controlled Trial (A/B Test) to establish causality?", "The RCT (A/B Test) is the gold standard because randomization mathematically guarantees that both known AND unknown confounding variables are perfectly balanced between groups, definitively proving causality. The tradeoff is that RCTs are expensive, take time, and are sometimes unethical (e.g., withholding medicine). Observational analysis is free, instant, and uses historical data. The severe tradeoff is that it can only control for *known, measured* variables. Hidden, unmeasured confounders can always skew observational results, meaning it rarely provides 100% causal certainty.", ["RCT mathematically eliminates all known and unknown confounders via randomization", "Observational analysis is fast and uses historical data", "Tradeoff: Observational analysis cannot control for unmeasured/hidden confounders"], ["Observational data uses SQL, A/B testing uses Python"]),
    ("B57_3", "concept", "easy", "concept", ["Causal Inference"], "What does the phrase 'Correlation does not imply Causation' mean in data analytics?", "It means that just because two variables move together statistically (e.g., ice cream sales and shark attacks both increase in July), it does not mean one causes the other. They are often linked by a third 'confounding' variable (in this case, summer weather). Relying on correlation to make business decisions without proving the causal mechanism can lead to completely ineffective strategies.", ["Statistical correlation between two trends does not prove a cause-and-effect relationship", "Often driven by a third, hidden confounding variable", "A foundational rule preventing false strategic business conclusions"], ["It means math is sometimes wrong"]),
    ("B57_3", "explain", "hard", "explain", ["Causal Inference"], "Explain the concept of 'Difference-in-Differences' (DiD) and when a Data Analyst would use it.", "DiD is a quasi-experimental technique used when random A/B testing is impossible (e.g., a new law passes in California but not Nevada). It compares the *change* in outcomes over time between a treatment group and a control group. You calculate the baseline difference between CA and NV before the law, and the difference after the law. The 'Difference-in-Differences' is the causal effect. Crucially, it relies on the 'Parallel Trends Assumption': the assumption that, absent the intervention, both groups would have continued on the exact same trajectory.", ["Quasi-experimental method comparing changes over time across treatment and control groups", "Used for policy changes or macro events where individual randomization is impossible", "Strictly requires the 'Parallel Trends Assumption' to be valid"], ["It subtracts numbers twice to make them smaller"]),
    ("B57_3", "diagnose", "medium", "debugging", ["Causal Inference"], "You analyze customer churn. You build a model showing that users who call Customer Support have a 50% higher churn rate. The VP suggests firing the Customer Support team to reduce churn. What is the logical flaw?", "This is a confusion of cause and effect (Reverse Causality). The Customer Support team is not causing the user to churn. Users call Customer Support *because* they are experiencing a severe product bug or billing issue that is already driving them to churn. Firing the support team will actually worsen the churn rate by removing the only mechanism to save frustrated users. The calls are a symptom, not the disease.", ["Reverse Causality / Confusion of cause and effect", "Users call support because they are frustrated (the root cause of churn)", "Removing the symptom (support calls) worsens the actual problem"], ["Customer support is actually doing a great job"]),
    ("B57_3", "architecture", "hard", "architecture", ["Causal Inference"], "What is a 'Synthetic Control' method, and how does it improve upon standard Difference-in-Differences?", "If you launch a massive marketing campaign in Chicago, standard DiD might use New York as a control. But no single city is perfectly comparable to Chicago. Synthetic Control solves this by using machine learning (often weighted regressions) to build a 'Fake Chicago'—a mathematically weighted combination of multiple other cities (e.g., 30% NY, 50% Detroit, 20% LA) that perfectly mimics Chicago's historical pre-intervention trends. You then compare real Chicago to Synthetic Chicago post-intervention, providing a vastly more accurate causal estimate.", ["Constructs a weighted average of multiple control units to mimic the treatment unit", "Overcomes the limitation of finding a single, perfectly comparable control group", "Provides a highly accurate baseline for post-intervention comparison"], ["It uses synthetic AI data generated by ChatGPT"]),
    ("B57_3", "scenario", "medium", "scenario", ["Causal Inference"], "A gym runs a promotion: 'Sign a 12-month contract, get 1 month free.' They note that users who take this promotion stay 3x longer than users on month-to-month plans. They conclude the promotion *causes* extreme loyalty. What bias is present?", "Self-Selection Bias. The promotion requires a 12-month commitment. The only people who willingly sign a 12-month contract are people who are already highly motivated and intend to stay for a year anyway. People who are unsure about the gym choose month-to-month. The promotion didn't magically create loyalty; it simply filtered the user base, attracting users whose underlying intent was already high.", ["Self-Selection Bias", "The requirement of the promotion acts as a filter for highly motivated users", "The promotion identifies loyal users; it does not necessarily create them"], ["Gym users are very healthy"]),

    # Area 4: Time-Series, Forecasting, Anomaly
    ("B57_4", "concept", "medium", "concept", ["Time Series Analysis"], "In Time Series analysis, what are the three foundational mathematical components that make up a time series dataset?", "A classic time series is decomposed into three components: 1) Trend (the long-term macro direction of the data, e.g., yearly revenue growth), 2) Seasonality (repeating, predictable short-term cycles, e.g., higher retail sales every December, or higher traffic every weekend), and 3) Residuals/Noise (the random, unpredictable variance left over after removing trend and seasonality).", ["Trend: Long-term macro direction", "Seasonality: Predictable, repeating cyclical patterns", "Residuals/Noise: Random, unpredictable variance"], ["Past, Present, and Future"]),
    ("B57_4", "diagnose", "hard", "debugging", ["Time Series Analysis"], "You are building an ARIMA forecasting model for daily e-commerce sales. The model's predictions are a flat, straight line, completely failing to capture the massive spikes that happen every single Saturday. What step did you miss in the time series preparation?", "You failed to make the data 'Stationary' regarding seasonality, or you used a standard ARIMA model instead of SARIMA (Seasonal ARIMA). Standard ARIMA models assume there is no seasonal repeating pattern. Because you didn't difference the data by a 7-day lag (to remove the weekly cycle) or configure the seasonal parameters (P,D,Q,s=7), the mathematical algorithm treated the Saturday spikes as random noise and smoothed them out into a flat average line.", ["Failed to account for Seasonality (failed to make data stationary)", "Must use Seasonal differencing (e.g., lag 7) to remove the weekly cycle", "Should use a SARIMA model explicitly designed for seasonal cycles"], ["You forgot to press the predict button"]),
    ("B57_4", "implement", "medium", "implement", ["SQL Analytics"], "How do you calculate a 7-day rolling average in SQL to smooth out daily time-series volatility?", "You use the `AVG()` window function coupled with a specific `ROWS BETWEEN` frame clause. For example: `AVG(daily_sales) OVER (ORDER BY date_column ROWS BETWEEN 6 PRECEDING AND CURRENT ROW)`. This explicitly tells the database to average the current row's value along with the exact 6 chronological rows before it, perfectly calculating the 7-day trailing moving average.", ["Use the `AVG()` window function", "Use `ORDER BY date` to ensure chronological sorting", "Use the frame clause: `ROWS BETWEEN 6 PRECEDING AND CURRENT ROW`"], ["Use the ROLLING_AVG() function"]),
    ("B57_4", "tradeoff", "medium", "tradeoff", ["Time Series Analysis"], "What is the tradeoff of using a simple Moving Average versus Exponential Smoothing (like Holt-Winters) for time series forecasting?", "A simple Moving Average assigns equal mathematical weight to all historical data points in the window (e.g., a sale 30 days ago impacts the forecast exactly as much as a sale yesterday). This makes it slow to react to sudden trend changes. Exponential Smoothing assigns exponentially decreasing weights to older data, meaning yesterday's data heavily drives the forecast, while data from last month has a tiny impact. This allows Exponential Smoothing to react rapidly to sudden real-world changes, but makes it slightly more vulnerable to reacting to single-day noise.", ["Moving Average assigns equal weight to old and new data (slow to react to trends)", "Exponential Smoothing heavily weights recent data (fast reaction to trends)", "Tradeoff: Exponential smoothing is faster to adapt but more sensitive to recent noise"], ["Moving average requires physical movement"]),
    ("B57_4", "scenario", "hard", "scenario", ["Time Series Analysis"], "You are tasked with building an automated Anomaly Detection alert for daily revenue. If revenue drops 20% below the average, it pages the CEO. In November, it falsely paged the CEO 5 times because revenue 'dropped' on Thanksgiving and Black Friday weekends. How do you fix the algorithm?", "A simple threshold based on standard deviation or rolling averages completely fails on predictable holidays and extreme seasonal events. You must implement a forecasting algorithm that explicitly models holiday regressors (like Facebook Prophet) or use historical Year-over-Year (YoY) baseline comparisons. By providing the algorithm with a calendar of expected holidays, the expected baseline drops (or spikes) accordingly, and the anomaly threshold dynamically adjusts, preventing the false positive alerts.", ["Simple statistical thresholds ignore extreme holiday seasonality", "Must use an algorithm supporting Holiday Regressors (like Prophet)", "Or compare against historical Year-over-Year (YoY) baselines for that specific calendar day"], ["Turn off the pager over the holidays"]),
    ("B57_4", "explain", "hard", "explain", ["Time Series Analysis"], "What does it mean for a time series to be 'Stationary', and why is it a strict requirement for models like standard ARIMA?", "A stationary time series is one whose statistical properties (mean, variance, and autocorrelation) are constant over time. It has no upward/downward trend and no seasonal cycles. This is a strict requirement for ARIMA because statistical forecasting equations rely on historical variance repeating predictably in the future. If the mean is constantly increasing (a trend), historical averages are mathematically useless for predicting the future. We make data stationary by 'differencing' it (subtracting yesterday's value from today's).", ["Statistical properties (mean, variance) remain constant over time", "No trends and no seasonality", "Required because forecasting algorithms rely on consistent historical distributions; achieved via differencing"], ["Stationary means the data is written on paper stationery"]),
    ("B57_4", "concept", "easy", "concept", ["Time Series Analysis"], "In the context of evaluating a forecasting model, what does MAPE stand for and what does it measure?", "MAPE stands for Mean Absolute Percentage Error. It measures the accuracy of a forecast by calculating the average absolute percent difference between the actual historical values and the model's predicted values. Because it is a percentage (e.g., 'the model is off by 5% on average'), it is highly intuitive and easy to explain to business stakeholders, compared to metrics like RMSE which are in raw units.", ["Mean Absolute Percentage Error", "Calculates the average percentage difference between predicted and actual values", "Highly intuitive metric for communicating accuracy to non-technical stakeholders"], ["Mapping And Point Estimation"]),
    ("B57_4", "diagnose", "medium", "debugging", ["Time Series Analysis"], "You calculate Year-over-Year (YoY) growth for February 2024. The metric shows a sudden, massive 4% spike in total monthly revenue compared to February 2023, but average daily sales are completely flat. What caused this?", "February 2024 is a Leap Year (29 days). February 2023 only had 28 days. The extra calendar day mathematically injects roughly 3.5% (1/28) more revenue into the monthly aggregate total, completely distorting the YoY comparison. When analyzing monthly time series involving February, you must always normalize the data to 'Average Daily Revenue' rather than using raw aggregate monthly totals to avoid this calendar artifact.", ["Leap Year artifact (February 2024 has 29 days vs 2023's 28 days)", "The extra calendar day artificially inflates the monthly aggregate by ~3.5%", "Must normalize by dividing by the number of days (Average Daily Revenue)"], ["The marketing team ran a leap year sale"]),
    ("B57_4", "architecture", "hard", "architecture", ["Data Engineering"], "When designing a real-time anomaly detection dashboard, what is the architectural tradeoff between 'Tumbling Windows' and 'Sliding Windows'?", "A Tumbling Window segments streaming time-series data into strict, non-overlapping chunks (e.g., 00:00-00:05, 00:05-00:10). It is computationally cheap and easy to aggregate, but if an anomaly occurs exactly across the boundary (00:04 to 00:06), it is split in half and might not trigger an alert. A Sliding Window evaluates data continuously (e.g., the last 5 minutes, recalculated every 1 second). It perfectly captures anomalies regardless of when they start, but requires vastly more RAM and compute power because data points are included in multiple overlapping aggregations.", ["Tumbling: Non-overlapping time blocks (cheap, but misses events crossing boundaries)", "Sliding: Overlapping, continuously updated blocks (captures everything, high compute cost)", "Tradeoff between compute efficiency and edge-case anomaly detection"], ["Tumbling windows break easily, sliding windows don't"]),
    ("B57_4", "scenario", "medium", "scenario", ["Time Series Analysis"], "Your company sells highly seasonal winter coats. You want to know if the underlying business is growing in July. How do you mathematically deseasonalize the time series to find the true trend?", "You perform Seasonal Decomposition. Using a tool like Python's `statsmodels.tsa.seasonal_decompose`, the algorithm analyzes multiple years of history to calculate a 'Seasonal Index' for every month (e.g., December is 2.0x average, July is 0.5x average). You then divide the raw July sales by the 0.5 index. This removes the seasonal depression, revealing the underlying 'Trend' line. If the deseasonalized July number is higher than the deseasonalized June number, the underlying business is actually growing despite raw sales dropping.", ["Use Seasonal Decomposition to calculate a Seasonal Index for each time period", "Divide the raw data by the Seasonal Index", "This isolates and reveals the underlying long-term Trend devoid of seasonal noise"], ["You just guess based on how cold it is"]),

    # Area 5: Advanced SQL - Gap & Island, Sessionization
    ("B57_5", "concept", "medium", "concept", ["Advanced SQL"], "In advanced SQL analytics, what is the 'Gaps and Islands' problem?", "The Gaps and Islands problem involves finding continuous sequences of data (Islands) and the missing periods between them (Gaps) within a time-series or sequential dataset. A common example is analyzing a user's login history to find their longest 'streak' of consecutive daily logins (the island), or identifying periods of inactivity greater than 3 days (the gap). It typically requires complex Window Functions (like `LAG` or `ROW_NUMBER` difference techniques) to solve.", ["Identifying continuous sequences of data (Islands) and missing periods (Gaps)", "Used for streak calculation, sessionization, or detecting downtime", "Requires advanced window functions to compare current rows to previous rows"], ["It is a problem with missing database tables"]),
    ("B57_5", "implement", "hard", "implement", ["Advanced SQL"], "Explain how to solve a basic 'Islands' problem (e.g., finding streaks of consecutive login days) using the `ROW_NUMBER()` difference method in SQL.", "First, you ensure you have distinct login dates per user. Then, you calculate a `ROW_NUMBER() OVER (PARTITION BY user_id ORDER BY login_date)`. The mathematical trick is subtracting the `ROW_NUMBER` integer from the actual `login_date` (e.g., `DATE_SUB(login_date, INTERVAL row_num DAY)`). Because both the date and the row number increment by exactly 1 during a continuous streak, the resulting subtracted 'anchor date' will be identical for all days in that specific streak. You then `GROUP BY` that anchor date to `COUNT` the length of the streak.", ["Use `ROW_NUMBER()` ordered by date", "Subtract the row number from the date", "Continuous streaks will yield the exact same resulting 'anchor date'", "Group by the anchor date to aggregate the streak"], ["Just use the STREAK() SQL function"]),
    ("B57_5", "diagnose", "medium", "debugging", ["Advanced SQL"], "A Junior Analyst writes a query to find the total revenue of all users who signed up in 2023. They write: `SELECT SUM(r.amount) FROM users u LEFT JOIN revenue r ON u.id = r.user_id WHERE u.signup_year = 2023 AND r.status = 'paid'`. Why does this return the wrong total for the cohort?", "By placing the `r.status = 'paid'` condition in the `WHERE` clause, the analyst fundamentally transformed the `LEFT JOIN` into an `INNER JOIN`. If a user signed up in 2023 but has zero revenue records (or only unpaid records), the `WHERE` clause filters out the NULL row entirely. This eliminates all zero-revenue users from the cohort denominator. To preserve the cohort and correctly calculate averages/totals, the condition must be moved into the join clause: `LEFT JOIN revenue r ON u.id = r.user_id AND r.status = 'paid'`.", ["Filtering the right-side table in the `WHERE` clause destroys the `LEFT JOIN`", "It converts it to an `INNER JOIN`, dropping all users with no paid revenue", "Must move the right-table condition into the `ON` clause of the join"], ["The sum function doesn't work on left joins"]),
    ("B57_5", "architecture", "hard", "architecture", ["Advanced SQL"], "How do you implement 'Sessionization' in SQL? (Grouping a stream of raw pageviews into discrete sessions based on a 30-minute inactivity timeout).", "1. Use `LAG(timestamp) OVER (PARTITION BY user_id ORDER BY timestamp)` to get the previous pageview time. 2. Calculate the difference in minutes. If the difference > 30, flag it as `1` (a new session boundary), else `0`. 3. Use a cumulative sum window function: `SUM(new_session_flag) OVER (PARTITION BY user_id ORDER BY timestamp)`. Because the sum increments by 1 every time a 30-minute gap is hit, all pageviews belonging to the same session will mathematically share the exact same cumulative sum integer, acting as a unique session ID.", ["Use `LAG()` to calculate time difference between current and previous event", "Flag events with >30 min difference as `1` (new session boundary)", "Use `SUM(flag) OVER (...)` to create a cumulative rolling sum, yielding a unique session ID"], ["Group by the hour of the day"]),
    ("B57_5", "tradeoff", "medium", "tradeoff", ["SQL Analytics"], "What is the performance tradeoff of using `COUNT(DISTINCT user_id)` on a massive dataset of a billion rows, and what is the modern alternative?", "`COUNT(DISTINCT)` is exceptionally expensive. The database engine must hold every unique string/ID in memory (often building a massive hash table) to ensure it isn't counting duplicates, which destroys RAM and forces slow disk spilling. The modern alternative is `APPROX_COUNT_DISTINCT()` (which uses the HyperLogLog algorithm under the hood). The tradeoff is that HyperLogLog guarantees ~98-99% accuracy rather than 100%, but it executes in milliseconds using kilobytes of RAM, saving massive compute costs for directional analytics.", ["`COUNT(DISTINCT)` requires massive RAM to track every unique ID, causing disk spilling", "`APPROX_COUNT_DISTINCT()` uses HyperLogLog for millisecond performance and low RAM", "Tradeoff: HyperLogLog sacrifices ~1-2% accuracy for massive performance gains"], ["COUNT(DISTINCT) requires manual indexing"]),
    ("B57_5", "scenario", "hard", "scenario", ["Advanced SQL"], "You have a table of subscription price changes: `id, user_id, price, change_date`. You need to query the state of every user's price exactly as it was on '2023-06-01', but users change prices randomly throughout the year. How do you query this 'point-in-time' architecture?", "You must perform an 'As-Of' (or Point-in-Time) query using a Window Function. You filter out all records after the target date (`WHERE change_date <= '2023-06-01'`). Then, you use `ROW_NUMBER() OVER (PARTITION BY user_id ORDER BY change_date DESC)` to rank the historical changes. Finally, you wrap this in a CTE or subquery and filter for `WHERE row_num = 1`. This isolates the single most recent price change that was active exactly on that specific historical date.", ["Filter for dates `<= target_date`", "Use `ROW_NUMBER() OVER (PARTITION BY id ORDER BY date DESC)` to rank history", "Select where `row_num = 1` to get the most recently active state as of that date"], ["Just query the table where date = '2023-06-01'"]),
    ("B57_5", "explain", "medium", "explain", ["Advanced SQL"], "Explain the difference between `ROWS BETWEEN UNBOUNDED PRECEDING` and `RANGE BETWEEN UNBOUNDED PRECEDING` in SQL Window Functions.", "`ROWS` evaluates strictly based on physical row counts in the result set. `ROWS UNBOUNDED PRECEDING` calculates a running total by adding exactly the current physical row to the previous physical rows. `RANGE` evaluates based on logical values in the `ORDER BY` clause. If you use `RANGE` and there is a tie in the `ORDER BY` column (e.g., two sales on the same date), the database processes both tied rows simultaneously, assigning them the exact same aggregated total, rather than incrementing them sequentially like `ROWS` would.", ["`ROWS` evaluates physically row-by-row", "`RANGE` evaluates logically based on value ties in the `ORDER BY` clause", "`RANGE` aggregates tied rows simultaneously, giving them identical running totals"], ["ROWS is for text, RANGE is for numbers"]),
    ("B57_5", "diagnose", "medium", "debugging", ["Advanced SQL"], "You write a query with a CTE: `WITH active_users AS (SELECT * FROM users WHERE status = 'active')`. You then reference `active_users` four times in four different complex joins in the main query. The query is extremely slow. Why?", "In many SQL dialects (especially older PostgreSQL versions or massive analytical DBs), CTEs (Common Table Expressions) act as an 'Optimization Fence'. The query planner calculates the CTE once, materializes it into a temporary memory structure, and scans it 4 times. It fails to push down specific indexes or filters from the main query into the CTE. To fix this, you must either rewrite the query using temporary tables with indexes, or replace the CTE with inline Subqueries, allowing the query planner to globally optimize the joins.", ["CTEs can act as an 'Optimization Fence', preventing global query planning", "Main query filters/indexes are not pushed down into the CTE", "Fix by using temporary tables with indexes or inline subqueries"], ["The CTE name is too long"]),
    ("B57_5", "concept", "easy", "concept", ["Advanced SQL"], "What does the `COALESCE()` function do in SQL, and why is it frequently used with `LEFT JOIN`s?", "`COALESCE()` takes a list of arguments and returns the first non-NULL value it finds (e.g., `COALESCE(revenue, 0)`). It is essential after a `LEFT JOIN` because unmatched rows return NULL. If you try to perform mathematical operations on a NULL (e.g., `base_price + NULL`), the entire result becomes NULL. Wrapping the joined column in `COALESCE(col, 0)` safely converts the missing join data into a zero, allowing mathematical aggregations to succeed.", ["Returns the first non-NULL value in a list of arguments", "Converts NULLs from unmatched `LEFT JOIN` rows into a default value (like 0)", "Prevents mathematical operations from failing due to NULL propagation"], ["It joins two strings together"]),
    ("B57_5", "implement", "hard", "implement", ["Advanced SQL"], "How do you 'Pivot' a dataset in standard SQL (e.g., Postgres) without using proprietary `PIVOT` functions?", "You use conditional aggregation. You `GROUP BY` the main dimension (e.g., `user_id`). Then, you create a new column for each pivot category using a `SUM(CASE WHEN ...)` pattern. For example, to pivot monthly revenue: `SUM(CASE WHEN month = 'Jan' THEN revenue ELSE 0 END) AS jan_rev`, `SUM(CASE WHEN month = 'Feb' THEN revenue ELSE 0 END) AS feb_rev`. This collapses multiple rows of categorical data into a single row with multiple dedicated columns.", ["Use Conditional Aggregation (`SUM` or `MAX` combined with `CASE WHEN`)", "Group by the primary dimension (e.g., `user_id`)", "Each `CASE WHEN` isolates a specific category, collapsing rows into columns"], ["You must export it to Excel to pivot it"])
]

def run_batch():
    with open(OUT, "a", encoding="utf-8") as f:
        for q in Q:
            rec = {
                "primary_role": ROLE,
                "applicable_roles": ["Data Scientist", "Product Manager"],
                "primary_skill": q[4][0],
                "secondary_skills": q[4][1:] if len(q[4]) > 1 else [],
                "technology": "Data Analytics",
                "topic": q[4][0] if len(q[4]) > 0 else "General",
                "category": "Data Engineering",
                "intent": q[1],
                "difficulty": q[2],
                "question_type": q[3],
                "question": q[5],
                "expected_answer": q[6],
                "evaluation_rubric": {
                    "strong_indicators": q[7],
                    "weak_indicators": q[8]
                },
                "id": str(uuid.uuid4()),
                "source": "Antigravity_Internal_Knowledge",
                "provenance_type": "researched_generated",
                "dataset_version": "v2",
                "status": "active"
            }
            f.write(json.dumps(rec) + "\n")
            
    print(f"Appended {len(Q)} questions (Part 1).")

if __name__ == "__main__":
    run_batch()
