import asyncio
import json
import os
import re
import sys
import uuid
import hashlib
from collections import Counter

from dotenv import load_dotenv
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
load_dotenv()

BACKEND_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_DIR = os.path.join(BACKEND_DIR, "data")
OUT = os.path.join(DATA_DIR, "interview_question_bank_v2_generated.jsonl")

ROLE = "Frontend Developer"
LEAK = re.compile(r"(generate a question|generate \d+ questions|return only json|phase 4c gap plan|"
                  r"generation batch|candidate generation|system instructions|do not proceed|"
                  r"awaiting authorization|minimum target|generation pipeline|"
                  r"batch \d+ generation|expected answer|strong indicator|weak indicator|as an ai|"
                  r"here is the question|\bprompt text\b)", re.I)

Q = [
    # PWA & Service Workers
    ("B64_5_1", "concept", "medium", "concept", ["Service Workers"], "What is the 'Cache API' in a Service Worker, and why should you never cache `index.html` with a long TTL (Time To Live)?", "The Cache API allows a Service Worker to intercept network requests and serve files instantly from the browser's hard drive, enabling offline PWAs. However, `index.html` is the absolute entry point of the entire application. It contains the hardcoded links to the dynamically hashed JS/CSS bundles (e.g., `main.a1b2c.js`). If you aggressively cache `index.html` using the Cache API or HTTP headers, the user will permanently load the old HTML, which points to old JS chunks. When you deploy a new version and delete the old chunks from the CDN, the user's cached HTML will 404 on the JS, fatally breaking the app. `index.html` MUST always use `Cache-Control: no-cache`.", ["The Cache API allows Service Workers to intercept requests and serve files offline", "Aggressively caching `index.html` traps the user on an old version of the app", "Because `index.html` points to hashed JS chunks, caching it causes catastrophic 404s when those old chunks are deleted from the CDN"], ["You shouldn't cache index.html because it is too small"]),
    ("B64_5_2", "diagnose", "hard", "debugging", ["Service Workers"], "You implement the 'Background Sync' API in your PWA. When offline, users hit 'Submit Order', the event is registered, and the UI says 'Saved'. However, users complain that their orders randomly disappear and never reach the server, even after reconnecting. Why did Background Sync silently fail?", "Background Sync fires a `sync` event inside the Service Worker exactly once when the browser detects internet connectivity. The Service Worker MUST explicitly read the queued order from `IndexedDB`, fire the `fetch()`, AND pass that Promise to `event.waitUntil(promise)`. If the developer forgets `event.waitUntil()`, the Service Worker thread instantly goes to sleep the microsecond the event block ends, violently aborting the asynchronous `fetch()` mid-flight. The order is lost forever because the sync event will not fire again.", ["Background Sync waits for connectivity and fires an event in the Service Worker", "Service Workers aggressively terminate their own execution thread to save battery", "Fix: You must pass the asynchronous `fetch` promise to `event.waitUntil()` to physically prevent the browser from killing the thread mid-flight"], ["The background sync ran out of background memory"]),
    ("B64_5_3", "implement", "medium", "implement", ["Service Workers"], "How do you implement a 'Cache-First, Network-Fallback' strategy in a Service Worker, and for what type of assets is it architecturally appropriate?", "Inside the Service Worker's `fetch` event listener, you call `event.respondWith()`. You first query the Cache API: `caches.match(event.request)`. If a match is found, you return it instantly (0ms latency). If it is `undefined`, you execute the `fetch(event.request)` to hit the network, optionally caching the result for next time. This strategy is ONLY appropriate for Immutable Assets (images, fonts, and hashed JS/CSS bundles like `chunk-123.js`). It is catastrophically bad for API data or `index.html`, which require a 'Network-First' or 'Stale-While-Revalidate' strategy to prevent serving infinitely stale data.", ["Intercept the `fetch` event and use `caches.match()` to check the local cache first", "If cache misses, fall back to a real network `fetch()`", "Appropriate exclusively for Immutable Assets (fonts, images, hashed JS chunks), NOT mutable API data"], ["Cache-first means the user has to clear their cache before using the app"]),
    ("B64_5_4", "tradeoff", "hard", "tradeoff", ["Service Workers"], "What is the architectural tradeoff of caching an entire 50MB Single Page Application for offline use (using Workbox `precacheAndRoute`)?", "Precaching allows the app to load instantly and function perfectly offline (e.g., in an airplane mode scenario). The severe tradeoff is the 'Installation Tax' and 'Update Penalty'. The very first time a user visits your landing page, the Service Worker silently downloads 50MB of data in the background, consuming massive bandwidth and CPU on mobile data plans. Worse, every time you deploy a tiny 1KB bug fix, the Service Worker detects a hash change in the manifest and forces the user to re-download all changed chunks before the new version activates. This heavily taxes global cellular users.", ["Precaching provides instant loading and true offline capabilities", "Tradeoff 1: Massive initial bandwidth/CPU tax downloading the entire app on the first visit", "Tradeoff 2: Users on slow cellular connections are heavily punished by background downloads for every minor update"], ["Precaching means the app is stored on the server instead of the browser"]),

    # Large-Scale UI Performance
    ("B64_5_5", "concept", "medium", "concept", ["UI Architecture"], "In large-scale data tables, what is the 'Pagination' versus 'Infinite Scrolling' tradeoff regarding DOM memory and accessibility?", "Pagination divides 10,000 records into discrete pages of 50. This guarantees strict O(1) DOM memory usage and is highly accessible, as Screen Readers can announce 'Page 1 of 200' and footer links are easily reachable. Infinite Scrolling dynamically appends new data as the user scrolls. The severe tradeoff is that Infinite Scrolling inherently destroys O(1) memory; if the user scrolls down 5,000 records, there are 5,000 heavy DOM nodes in memory, crashing the browser (unless explicitly mitigated with complex Virtualization). Furthermore, Infinite Scrolling breaks standard keyboard navigation, traps screen readers, and makes reaching footer links impossible.", ["Pagination limits DOM nodes automatically and preserves standard keyboard/accessibility navigation", "Infinite Scrolling provides frictionless UX but destroys memory by accumulating thousands of DOM nodes", "Infinite Scrolling breaks accessibility (traps focus) and makes the page footer unreachable"], ["Pagination requires printing the page, infinite scrolling doesn't"]),
    ("B64_5_6", "diagnose", "hard", "debugging", ["UI Architecture"], "You implement a complex React dashboard. To improve performance, you wrap a heavy chart component in `React.memo()`. However, the React DevTools Profiler proves the chart still re-renders on every single keystroke in the parent's search bar. Why did `React.memo` fail to prevent the re-render?", "`React.memo` performs a Shallow Equality check (`===`) on the component's props. If the parent component passes an inline object (`style={{ margin: 10 }}`) or an inline arrow function (`onClick={() => doSomething()}`) as a prop to the chart, those props are physically brand new objects in memory on EVERY parent render. The shallow equality check mathematically evaluates `new Object() === new Object()` as False. Therefore, `React.memo` thinks the props changed and allows the re-render, completely negating the optimization. To fix this, the parent MUST wrap the object/function props in `useMemo` or `useCallback` to preserve referential equality.", ["`React.memo` relies strictly on shallow equality (`===`) of props", "Passing inline objects or arrow functions from the parent creates brand new memory references on every render", "Fix: The parent must use `useCallback` or `useMemo` to maintain referential equality of the props passed to the memoized child"], ["The memo ran out of memory limit"]),
    ("B64_5_7", "scenario", "medium", "scenario", ["UI Architecture"], "Your SPA fetches a 50MB JSON array of analytics data. The network download takes 2 seconds, but when `fetch().then(res => res.json())` executes, the browser tab completely freezes for 4 seconds, showing the 'Page Unresponsive' dialog. How do you fix this JSON parsing freeze?", "The `JSON.parse()` engine is synchronous and blocks the main thread. Parsing 50MB of complex JSON takes multiple seconds of pure CPU time, paralyzing the UI. You cannot fix this on the main thread. The architectural fix is to offload the parsing to a Web Worker. You pass the raw Response `ArrayBuffer` or text to the Worker. The Worker runs `JSON.parse()` on a separate OS thread, completely freeing the main thread to render loading animations. Once parsed, the Worker uses `postMessage` to send the hydrated object back to the main thread.", ["Massive `JSON.parse()` operations are synchronously CPU-bound, completely freezing the main thread and UI", "Fix: Move the JSON parsing logic into a Web Worker", "The Web Worker parses the payload on a background OS thread and uses `postMessage` to return the result, maintaining 60FPS on the UI"], ["You just tell the server to format the JSON better"]),
    ("B64_5_8", "implement", "hard", "implement", ["UI Architecture"], "How do you implement 'Progressive Rendering' (Streaming) in a React 18 SSR architecture to prevent a single slow database query from blocking the entire initial HTML response?", "In legacy SSR (`renderToString`), the NodeJS server had to wait for ALL data to resolve before sending a single byte of HTML, causing terrible Time to First Byte (TTFB). In React 18, you implement Streaming SSR (`renderToPipeableStream`). You wrap the slow component (e.g., `<HeavyComments />`) in a `<Suspense>` boundary. React instantly streams the HTML for the fast parts of the page (Navbar, Sidebar, Skeleton loader) down the HTTP socket, providing phenomenal TTFB. When the slow database query finally resolves 3 seconds later, React streams a tiny `<script>` tag down the same open HTTP connection that magically injects the finished Comments HTML into the previously sent Skeleton.", ["Legacy SSR waited for all data to resolve, blocking the entire HTML response (terrible TTFB)", "React 18 Streaming SSR sends the fast HTML instantly via HTTP chunked transfer encoding", "When Suspended components finish loading, React streams a script tag that dynamically injects the missing HTML into the active DOM"], ["Progressive rendering means the rendering engine believes in social progress"]),
    ("B64_5_9", "concept", "medium", "concept", ["UI Architecture"], "What is 'Layout Thrashing' in the context of infinite scrolling, and how does appending 100 new DOM nodes trigger it?", "When you fetch 100 new items and append them to the DOM, the browser inherently must recalculate the Layout (geometry) of the page to fit them. If your JavaScript appends the items and then IMMEDIATELY queries the height of the container (`container.scrollHeight`) to adjust the scroll position, you force the browser to halt JS execution and synchronously calculate the exact pixel positions of all 100 new nodes before continuing. This synchronous blocking is Layout Thrashing. It causes a massive stutter exactly at the moment the new items load. You must defer the read operation (e.g., using `requestAnimationFrame`) to allow the browser to paint naturally.", ["Appending nodes marks the DOM tree as 'dirty' (needing layout recalculation)", "Immediately reading geometric properties (`scrollHeight`) forces a synchronous, blocking layout calculation", "This causes massive main-thread stutters (Layout Thrashing); fix by deferring DOM reads"], ["Layout thrashing is when you shake the monitor to fix the alignment"]),

    # Internationalization
    ("B64_5_10", "diagnose", "hard", "debugging", ["Internationalization"], "You translate your SPA into Arabic (a Right-to-Left language). You set `<html dir=\"rtl\">`. Suddenly, all of your UI layout is broken: margins are on the wrong side, back arrows point forward, and flexbox gaps are inverted. Why did this happen and how do you architect CSS to prevent it?", "The CSS was written using Physical Properties (`margin-left: 10px`, `padding-right: 5px`). Physical properties are rigidly locked to the screen geometry and do not care about the reading direction of the language. When the document flips to RTL, a `margin-left` pushes the content the wrong way. To fix this globally, the architecture MUST use CSS Logical Properties. You replace `margin-left` with `margin-inline-start`. In an LTR language, `inline-start` maps to the left. In an RTL language, the browser automatically maps `inline-start` to the right, perfectly flipping the entire layout without requiring a single RTL-specific media query.", ["Using hardcoded Physical Properties (`margin-left`) breaks layout directionality in RTL languages", "Fix: Completely adopt CSS Logical Properties (`margin-inline-start`, `padding-inline-end`)", "Logical properties automatically adapt to the `dir=\"rtl\"` attribute, perfectly mirroring the UI natively"], ["The Arabic translation was too long for the flexbox"]),
    ("B64_5_11", "implement", "medium", "implement", ["Internationalization"], "How do you implement locale-sensitive pluralization in a React application without writing massive `if/else` statements for every language's grammar rules?", "English has two plural forms (1 apple, 2 apples). Russian has three distinct grammatical plural forms depending on the exact number (ending in 1, 2-4, 5+). Arabic has six. You cannot write `count === 1 ? 'apple' : 'apples'` because it mathematically fails in most global languages. You must use the `Intl.PluralRules` browser API, or a standard i18n library (like `i18next` or `react-intl`) that utilizes the ICU Message Format (`{count, plural, =0 {no apples} one {# apple} other {# apples}}`). The library automatically applies the correct linguistic pluralization rules for the target locale dynamically at runtime.", ["Hardcoding `count === 1` fails globally because languages like Arabic and Russian have 3 to 6 distinct plural grammar rules", "Fix: Use the native `Intl.PluralRules` API or a library supporting ICU Message Format", "This delegates the complex grammatical logic to specialized translation engines rather than raw JS logic"], ["You just add an 's' to the end of the word using a regex"]),
    ("B64_5_12", "scenario", "hard", "scenario", ["Internationalization"], "A user in Tokyo books a flight for 'October 10th at 9:00 AM (Tokyo Time)'. The frontend sends `{ date: '2025-10-10T09:00:00' }` to the server. The server stores it. A user in New York views the booking and sees 'October 10th at 9:00 AM'. Why is the time completely corrupted, and how do you fix the frontend payload?", "The frontend sent a 'Floating Time' string (lacking any timezone offset). Because it lacked a 'Z' (UTC) or `+09:00`, the database blindly stored it as a naive timestamp. When the New York user queried it, the UI rendered 9:00 AM local time, which is off by 13 hours. To fix this, the frontend MUST explicitly convert the user's input into a strict UTC ISO-8601 string BEFORE sending it to the network (`new Date('2025-10-10T09:00:00+09:00').toISOString()`, which evaluates to `2025-10-10T00:00:00.000Z`). All servers and databases must strictly communicate and store UTC, while the frontend handles the final local conversion for display.", ["Sending Naive/Floating datetime strings destroys global timezone context", "The server blindly stores 9:00 AM, causing users in other timezones to see 9:00 AM their local time (massive data corruption)", "Fix: The frontend must explicitly serialize all timestamps to absolute UTC ISO-8601 strings (`.toISOString()`) before transmission"], ["The server was located in New York, so it changed the time"]),
    ("B64_5_13", "tradeoff", "medium", "tradeoff", ["Internationalization"], "What is the tradeoff of dynamically loading translation JSON files at runtime (Client-Side) versus pre-baking them into the HTML via Server-Side Generation (SSG)?", "Dynamically fetching translations (`fetch('/locales/fr.json')`) drastically shrinks the initial JS bundle size and allows translators to update copy via a CMS without requiring a code deployment. The tradeoff is 'Layout Shift' and TTFB. The UI initially loads with empty skeleton text (or English fallback) while waiting for the network JSON request, causing a jarring visual flash when the French text finally populates. Pre-baking translations into SSG routes (`/fr/about`) guarantees perfect, zero-latency visual rendering and SEO, but severely complicates the build pipeline and requires compiling a distinct HTML artifact for every single language permutation.", ["Client-Side Translation: Shrinks bundle size and allows dynamic CMS updates, but causes visual flashing (FOUC) and hurts SEO", "SSG Pre-baking: Perfect zero-latency rendering and SEO, but massively complicates CI/CD by multiplying build artifacts per language", "Tradeoff: Runtime flexibility vs Absolute rendering performance"], ["Dynamic loading means the translations are done by Google Translate AI"]),

    # Frontend Platform & Monorepo
    ("B64_5_14", "concept", "hard", "concept", ["UI Architecture"], "In a massive Monorepo with 50 Micro-Frontends (MFEs), what is 'CSS Scope Bleed', and how do modern architectures prevent it across independent teams?", "If Team A deploys an MFE that includes `button { background: red; }` in a standard global CSS file, that rule bleeds into the global `document.styleSheets`. If Team B's MFE is on the same page, their buttons randomly turn red, causing catastrophic cascading UI failures across teams. To prevent this, architectures MUST enforce CSS Isolation. This is done via CSS Modules (which hash class names like `.button_a1b2c`), CSS-in-JS (Styled Components, which generate unique hashes), or Web Components (Shadow DOM, which physically isolates the CSS tree from the rest of the document, completely preventing global bleed).", ["Standard CSS is globally scoped; rules deployed by one MFE will accidentally overwrite rules in another MFE on the same page", "This causes chaotic, cross-team UI regressions (CSS Scope Bleed)", "Fix: Enforce strict isolation using CSS Modules (hashed classes), CSS-in-JS, or Shadow DOM (Web Components)"], ["CSS bleed is when the colors are too bright on an OLED screen"]),
    ("B64_5_15", "diagnose", "medium", "debugging", ["UI Architecture"], "You use NPM Workspaces in a monorepo. Package A requires `react@18.0.0`. Package B requires `react@17.0.0`. The build succeeds, but when the app runs in the browser, it throws the infamous error `Invalid hook call. Hooks can only be called inside of the body of a function component.` Why did NPM Workspaces cause this?", "When dependencies conflict in a monorepo, standard NPM hoists the highest compatible version to the root `node_modules`, but leaves the conflicting version inside `packages/B/node_modules`. Webpack bundles BOTH versions of React into the final JS payload. In React, global Hook state (like `useState`) relies on an internal singleton dispatcher tied to the specific imported instance of React. If Component A uses React 18's dispatcher, but Component B calls a hook using React 17's internal instance, the dispatcher is fundamentally mismatched, causing the fatal 'Invalid hook call' error. You must force strict singleton resolution in Webpack (`resolve.alias.react = path.resolve('./node_modules/react')`).", ["Monorepos can accidentally bundle multiple different versions of the same library if SemVer conflicts exist", "React strictly requires exactly ONE instance to exist in memory to manage Hook state (the internal Dispatcher)", "Bundling two Reacts causes severe state corruption and 'Invalid hook call' errors. Fix: Enforce Webpack alias singletons"], ["The hook call was made from a Class component by mistake"]),

    # Web Platform APIs
    ("B64_5_16", "implement", "hard", "implement", ["Browser APIs"], "How do you implement a direct Peer-to-Peer video call using `WebRTC`, and what is the specific architectural role of the 'Signaling Server'?", "WebRTC transmits massive video data directly from User A's browser to User B's browser (P2P), completely bypassing your backend servers, saving massive bandwidth costs. However, User A cannot magically find User B's IP address on the internet. You must implement a 'Signaling Server' (usually a lightweight WebSocket Node.js backend). User A sends an 'Offer' (their SDP format and public IP via STUN/TURN) to the Signaling Server. The server routes this message to User B. User B sends an 'Answer' back through the server. Once the browsers exchange these metadata packets, they establish a direct P2P connection, and the Signaling Server is no longer involved in the video stream.", ["WebRTC allows direct Browser-to-Browser streaming (P2P), saving backend bandwidth", "Browsers cannot discover each other natively due to NATs and Firewalls", "Fix: A 'Signaling Server' (WebSockets) is required purely to exchange initial metadata (SDP/ICE candidates) to establish the P2P connection"], ["WebRTC requires a 5G connection to work correctly"]),
    ("B64_5_17", "tradeoff", "medium", "tradeoff", ["Browser APIs"], "What is the tradeoff of using the modern `fetch()` API with `ReadableStream` to process a massive 10GB file download, versus relying on the legacy `XMLHttpRequest`?", "Legacy `XHR` downloads the entire file into a massive blob in memory; downloading 10GB will instantly crash the browser tab (OOM). The `fetch()` API exposes the `Response.body` as a `ReadableStream`. You can read the file chunk-by-chunk (e.g., 64KB at a time), process the chunk, and immediately discard it from memory, allowing you to process infinite gigabytes of data with a constant 64KB RAM footprint. The tradeoff is architectural complexity: Streams require manual asynchronous buffer management (`while(true) { const {value, done} = await reader.read() }`), explicit byte decoding (`TextDecoder`), and manual backpressure handling if your processing loop is slower than the network.", ["Legacy XHR buffers the entire response in RAM, causing OOM crashes on massive files", "`fetch` Streams (`ReadableStream`) allow O(1) memory processing by reading data chunk-by-chunk", "Tradeoff: Streams require complex manual buffer iteration, byte decoding, and backpressure management"], ["ReadableStream requires you to read the code out loud"]),
    ("B64_5_18", "scenario", "hard", "scenario", ["Browser APIs"], "Your application uses the `navigator.clipboard.writeText()` API to build a 'Copy to Clipboard' button. It works perfectly when the user clicks the button. You refactor the logic to first fetch a short-link from an API, and THEN copy it. Suddenly, the API throws `NotAllowedError: Document is not focused`. Why did the async refactor break the clipboard?", "For extreme security reasons, modern browsers restrict dangerous APIs (like Clipboard, window.open, or Audio Playback) to 'Transient User Activation'. These APIs are strictly locked. They can ONLY be invoked during the synchronous call stack of a direct, physical user interaction (a click or keystroke). When you inserted a `fetch()` call, you yielded the Event Loop. By the time the Promise resolved 100ms later, the 'Transient User Activation' window had expired. The browser blocked the clipboard access because it no longer recognized it as a direct result of a user click. To fix this, you must use the newer, permission-based asynchronous Clipboard API, or write placeholder text to the clipboard synchronously, then update it asynchronously.", ["Dangerous APIs (Clipboard/Audio) require 'Transient User Activation' (must execute synchronously during a physical user click)", "Inserting asynchronous operations (`fetch`, `setTimeout`) yields the call stack, causing the authorization window to expire", "Fix: Rely on the Permission API or execute the copy synchronously before the async logic"], ["The clipboard was full of other text"]),
    
    # Advanced Frontend Security
    ("B64_5_19", "concept", "medium", "concept", ["Web Security"], "What is 'CORS Preflight' (`OPTIONS` request), and why does making an API request with `Content-Type: application/json` trigger it, but `application/x-www-form-urlencoded` does not?", "CORS (Cross-Origin Resource Sharing) protects servers from unauthorized cross-domain browser requests. Decades ago, ancient HTML `<form>` tags could only send `x-www-form-urlencoded` or `multipart/form-data`. Because legacy servers were already exposed to these, the browser considers them 'Simple Requests' and sends the `POST` immediately. However, modern `application/json` payloads were impossible in ancient HTML. If a browser sent a JSON payload blindly to a legacy server, it might crash or cause vulnerabilities. Therefore, JSON triggers a 'Preflight'. The browser pauses the `POST`, sends an `OPTIONS` request to ask the server for permission, and ONLY proceeds if the server explicitly replies with `Access-Control-Allow-Headers: Content-Type`.", ["Legacy HTML forms could only send URL-encoded or Multipart data; these are 'Simple Requests' that bypass preflight", "`application/json` is a modern addition. To protect legacy servers, the browser executes a Preflight `OPTIONS` request", "The browser refuses to send the JSON payload until the server explicitly grants permission via CORS headers"], ["Preflight means the request is sent to an airplane's WiFi network"]),
    ("B64_5_20", "diagnose", "hard", "debugging", ["Web Security"], "You configure an `<iframe>` to embed a 3rd-party widget. To be secure, you add the `sandbox` attribute. However, the widget breaks, complaining it cannot run its API fetches. You add `sandbox=\"allow-scripts allow-same-origin\"`. A security auditor immediately fails your code. Why is this specific combination catastrophically dangerous?", "The `sandbox` attribute completely isolates the iframe, dropping its privileges to zero. `allow-scripts` lets it run JS. `allow-same-origin` allows it to read its own domain's cookies and API. However, if you combine BOTH of these flags simultaneously, you completely destroy the sandbox. Because the iframe now has both JavaScript execution AND same-origin access, it can simply use JavaScript to reach up and delete the `sandbox` attribute from its own iframe node, or access the parent window's DOM via `window.parent` (if domains match), achieving a total Sandbox Escape and gaining full control over your application.", ["The `sandbox` attribute strips privileges from embedded iframes", "Combining `allow-scripts` and `allow-same-origin` is a fatal architectural flaw", "This specific combination allows the malicious iframe to use JS to break out of the sandbox and attack the parent window"], ["The sandbox got filled with water and turned to mud"]),
    ("B64_5_21", "implement", "medium", "implement", ["Web Security"], "How do you securely implement a 'Logout' mechanism for a frontend application that relies on an `HttpOnly` Secure cookie containing an access token?", "If the token is stored in `localStorage`, the frontend simply runs `localStorage.removeItem('token')`. However, if the token is securely locked in an `HttpOnly` cookie, the JavaScript runtime physically cannot read or delete it (`document.cookie` is blocked). To implement logout, the frontend MUST send an HTTP request (`POST /api/logout`) to the backend server. The backend server responds with a `Set-Cookie` header containing the exact same cookie name, but with a blank value and an explicit expiration date in the past (`Expires=Thu, 01 Jan 1970`). The browser intercepts this header and physically purges the cookie from its internal vault, securely logging the user out.", ["`HttpOnly` cookies physically cannot be deleted or read by Frontend JavaScript", "The frontend cannot perform the logout locally", "Fix: The frontend must call a backend endpoint (`/logout`), which responds with a `Set-Cookie` header setting the expiration to the past (1970) to purge the cookie"], ["You just close the browser tab to log out"])
]

def run_batch():
    # Load all existing records to do deduplication
    with open(OUT, "r", encoding="utf-8") as f:
        existing = [json.loads(line) for line in f if line.strip()]

    print(f"Loaded {len(existing)} existing records.")
    
    for q in Q:
        if LEAK.search(q[5]) or LEAK.search(q[6]):
            print(f"PROMPT LEAK DETECTED in: {q[5]}")
            sys.exit(1)
            
    existing_texts = [ex["question"] for ex in existing]
    new_texts = [q[5] for q in Q]
    
    vec = TfidfVectorizer(stop_words="english", ngram_range=(1,2))
    all_texts = existing_texts + new_texts
    vec.fit(all_texts)
    
    existing_vecs = vec.transform(existing_texts)
    new_vecs = vec.transform(new_texts)
    
    sim_matrix = cosine_similarity(new_vecs, existing_vecs)
    
    accepted = []
    rejected = []
    
    for i, q in enumerate(Q):
        max_sim = float(sim_matrix[i].max()) if sim_matrix.shape[1] > 0 else 0
        if max_sim > 0.85:
            print(f"REJECTED (Sim: {max_sim:.2f}): {q[5][:50]}...")
            rejected.append(q)
        else:
            accepted.append(q)
            
    print(f"Accepted {len(accepted)} / {len(Q)} questions (Part 5).")
    
    new_records = []
    for q in accepted:
        rec = {
            "primary_role": ROLE,
            "applicable_roles": ["Frontend Engineer", "Software Engineer"],
            "primary_skill": q[4][0],
            "secondary_skills": q[4][1:] if len(q[4]) > 1 else [],
            "technology": "Frontend",
            "topic": q[4][0] if len(q[4]) > 0 else "General",
            "category": "Software Engineering",
            "intent": q[1],
            "difficulty": q[2],
            "question_type": q[3],
            "question": q[5],
            "expected_answer": q[6],
            "evaluation_rubric": {
                "strong_indicators": q[7],
                "weak_indicators": q[8]
            },
            "id": str(uuid.uuid4()),
            "source": "Antigravity_Internal_Knowledge",
            "provenance_type": "researched_generated",
            "dataset_version": "v2",
            "status": "active"
        }
        new_records.append(rec)
        
    with open(OUT, "a", encoding="utf-8") as f:
        for r in new_records:
            f.write(json.dumps(r) + "\n")
            
    # Final audit reporting
    with open(OUT, "r", encoding="utf-8") as f:
        final_existing = [json.loads(line) for line in f if line.strip()]
        
    role_counts = Counter(r["primary_role"] for r in final_existing)
    
    print("\n========================================")
    print("POST-BATCH AUDIT")
    print("========================================")
    print(f"Batch: 64")
    print(f"Target role: {ROLE}")
    print(f"Attempted: 100")
    print(f"Accepted: {len(accepted)}")
    print(f"Rejected: {len(rejected)}")
    print(f"Replacement count: 0")
    print(f"Cumulative total: {len(final_existing)}")
    print(f"{ROLE} total: {role_counts[ROLE]}")
    
    sha256 = hashlib.sha256()
    with open(OUT, 'rb') as f:
        while chunk := f.read(8192):
            sha256.update(chunk)
            
    print(f"\nFinal SHA256: {sha256.hexdigest()}")

if __name__ == "__main__":
    run_batch()
