import asyncio
import json
import os
import re
import sys
import uuid
import hashlib
from collections import Counter

from dotenv import load_dotenv
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
load_dotenv()

BACKEND_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_DIR = os.path.join(BACKEND_DIR, "data")
OUT = os.path.join(DATA_DIR, "interview_question_bank_v2_generated.jsonl")

ROLE = "Python Developer"
LEAK = re.compile(r"(generate a question|generate \d+ questions|return only json|phase 4c gap plan|"
                  r"generation batch|candidate generation|system instructions|do not proceed|"
                  r"awaiting authorization|minimum target|generation pipeline|"
                  r"batch \d+ generation|expected answer|strong indicator|weak indicator|as an ai|"
                  r"here is the question|\bprompt text\b)", re.I)

Q = [
    # Distributed Systems & Celery
    ("B63_1_1", "concept", "medium", "concept", ["Distributed Task Execution"], "In a distributed Python task queue (like Celery), what is 'Late Acknowledgement' (`acks_late=True`) and why is it critical for fault tolerance?", "By default, Celery acknowledges (deletes) a task from the broker (RabbitMQ/Redis) the moment a worker picks it up. If the Python worker process crashes (e.g., OOM or Segfault) before finishing the task, that task is permanently lost. Setting `acks_late=True` changes this behavior so the task is only acknowledged AFTER the Python function successfully returns. If the worker crashes mid-execution, the broker's visibility timeout will expire, and the task will be re-queued to another worker, guaranteeing at-least-once execution.", ["Default behavior deletes tasks upon receipt; crashes cause permanent task loss", "`acks_late=True` defers acknowledgement until the task successfully finishes", "Guarantees at-least-once execution, but requires the task to be strictly idempotent"], ["Late acknowledgement means saying thank you the day after"]),
    ("B63_1_2", "diagnose", "hard", "debugging", ["Distributed Task Execution"], "You have a Celery task that takes a SQLAlchemy model instance as an argument: `@app.task def process_order(order)`. When the worker executes it, it randomly throws `DetachedInstanceError` or acts on stale data. What is the fundamental architecture flaw?", "You are passing complex, stateful ORM objects (which hold live database connections and session state) through a distributed message broker (Redis/RabbitMQ). The object is pickled, sent over the network, and unpickled on a different server in a completely different Python process with no active DB session. To fix this, you must NEVER pass ORM objects or complex state to background tasks. You must pass only primitive identifiers (e.g., `@app.task def process_order(order_id: int)`), and the worker must independently query the database to retrieve the fresh, attached object.", ["Passing stateful ORM objects through a message broker causes session detachment and stale data", "The worker unpickles the object in a different process without an active database session", "Fix: Pass only primitive IDs (`order_id`) and have the worker query the database for the fresh object"], ["The worker didn't know how to read the database"]),
    ("B63_1_3", "implement", "medium", "implement", ["Distributed Task Execution"], "How do you implement a 'Poison Task' handler in Celery to prevent a single buggy task payload from infinitely crashing your workers?", "A poison task is a payload that causes a hard crash (e.g., an unhandled `Exception` or infinite loop). With `acks_late=True`, the worker crashes, the broker re-queues it, and it crashes the next worker infinitely. To handle this, you must configure a maximum retry limit (`max_retries`) and a Dead Letter Queue (DLQ). When catching the exception in the task, you call `self.retry(exc=e)`. Once `max_retries` is exceeded, the task is routed to an error queue (DLQ) where developers can inspect it manually, preventing it from halting the main queue.", ["Use `self.retry` with a strict `max_retries` limit", "If the limit is exceeded, route the task to a Dead Letter Queue (DLQ) rather than dropping it", "This isolates the poison payload and unblocks the main worker pool"], ["You feed the poison task to a virtual rat"]),
    ("B63_1_4", "tradeoff", "hard", "tradeoff", ["Distributed Task Execution"], "What is the tradeoff of using Redis versus RabbitMQ as the message broker for a highly-scaled Python Celery architecture?", "Redis is an in-memory key-value store; it is incredibly fast and trivial to set up, but it is not a true message broker. Its tradeoff is reliability: under severe memory pressure, Redis might evict tasks (data loss), and its Pub/Sub or List implementations lack native complex routing. RabbitMQ is a persistent, disk-backed AMQP broker. It natively supports complex routing keys, strict acknowledgements, and dead-letter exchanges, guaranteeing zero task loss even during crashes. The tradeoff is that RabbitMQ is significantly slower, requires complex Erlang infrastructure management, and demands careful tuning of prefetch limits.", ["Redis: Extremely fast and simple, but risks data loss on eviction/crash and lacks advanced routing", "RabbitMQ: True AMQP broker guaranteeing zero data loss with advanced routing and DLQs", "Tradeoff: RabbitMQ is heavier, slower, and harder to operate than Redis"], ["Redis is red and RabbitMQ is white"]),
    ("B63_1_5", "scenario", "medium", "scenario", ["Distributed Task Execution"], "A Python worker process (using Celery/RQ) executes a task that makes a 3rd-party API call. The external API goes completely unresponsive. Within 5 minutes, your entire pool of 100 workers is totally frozen and no other tasks are processed. How do you prevent this?", "The workers are suffering from unbounded blocking I/O. Because the 3rd-party API didn't close the TCP connection, the `requests.get()` call hangs infinitely. Since there are only 100 worker processes, they all quickly become occupied with hanging tasks, starving the queue. To prevent this, you MUST enforce strict network timeouts on all external calls (e.g., `requests.get(url, timeout=5)`). Furthermore, you should configure the task queue to enforce a hard `time_limit` and `soft_time_limit` on the task itself, so the worker supervisor automatically kills and recycles the process if it hangs.", ["Worker starvation occurs when blocking I/O calls hang infinitely without returning", "Fix 1: Always enforce strict network timeouts (e.g., `timeout=5` in `requests`)", "Fix 2: Enforce task-level `soft_time_limit` and `time_limit` so the supervisor kills stalled worker processes"], ["You just restart the workers manually every hour"]),
    ("B63_1_6", "explain", "hard", "explain", ["Distributed Task Execution"], "Explain why using the `prefork` execution pool in Celery can cause devastating memory leaks over time, and how the `max_tasks_per_child` setting mitigates it.", "The `prefork` pool uses Python's `multiprocessing` to fork worker processes. Python has notorious issues with memory fragmentation and cyclic garbage collection failing to release memory back to the OS (RSS bloat). Over days, a single worker process might balloon to 2GB of RAM due to un-freed C-extensions or fragmented allocations, eventually causing an OOM kill. The `max_tasks_per_child = 100` setting mitigates this by forcing the supervisor to gracefully terminate the worker process and fork a brand new, clean process after it completes 100 tasks. This guarantees memory is completely flushed back to the OS periodically.", ["Python's memory allocator and C-extensions often cause RSS (memory) bloat and fragmentation that isn't released", "Long-lived `prefork` worker processes accumulate this bloat until they crash the server (OOM)", "Fix: `max_tasks_per_child` recycles the OS processes after N tasks, guaranteeing the OS reclaims all fragmented memory"], ["Prefork means eating with a fork before the meal"]),
    ("B63_1_7", "concept", "medium", "concept", ["Distributed Task Execution"], "What is 'Idempotency', and why is it absolutely mandatory for Python background tasks?", "Idempotency means that executing a task multiple times produces the exact same side effect as executing it once. In distributed systems, network partitions or worker crashes mean the broker will inevitably re-deliver the exact same task twice (At-Least-Once delivery). If your task is `charge_credit_card(100)`, running it twice charges the user $200. To make it idempotent, you must pass a unique `transaction_id`, check the database to see if `transaction_id` is already marked 'completed', and if so, safely return without charging again.", ["Tasks will inevitably be delivered multiple times due to worker crashes or network blips", "Idempotency guarantees that duplicate execution does not corrupt data or cause duplicate side-effects", "Implemented by checking a unique ID against a database state before performing mutations"], ["Idempotency means the task cannot have children"]),

    # Advanced Web/ASGI Architecture
    ("B63_1_8", "concept", "hard", "concept", ["ASGI / Web Architecture"], "What is the fundamental architectural difference between WSGI (e.g., Flask/Django) and ASGI (e.g., FastAPI/Starlette) regarding how they handle concurrent HTTP connections?", "WSGI is strictly synchronous and blocking. Each incoming HTTP request is handed to a dedicated OS thread or process (e.g., via Gunicorn). If the endpoint sleeps for 1 second, that OS thread is completely blocked. Scaling to 10,000 connections requires 10,000 threads, which crashes the OS. ASGI is asynchronous. A single OS thread runs an Event Loop (via Uvicorn/asyncio). When an endpoint awaits I/O (like a DB query), it yields control back to the Event Loop, which immediately picks up the next HTTP request. ASGI can effortlessly handle 10,000 concurrent connections on a single OS thread.", ["WSGI is synchronous: 1 request = 1 blocked OS thread (poor concurrency scaling)", "ASGI is asynchronous: A single thread uses an Event Loop to interleave thousands of requests", "ASGI yields control during I/O, allowing massive concurrency without Thread/Memory exhaustion"], ["ASGI uses AI to handle requests, WSGI uses humans"]),
    ("B63_1_9", "diagnose", "medium", "debugging", ["ASGI / Web Architecture"], "You deploy a FastAPI application using Uvicorn. You notice that a specific endpoint `def calculate_primes():` causes the entire server to freeze. No other users can access the API while this endpoint runs. Why?", "The endpoint was defined as a synchronous `def` (or it uses `async def` but executes heavy, non-awaitable CPU-bound math). In FastAPI, if you use `def`, the framework automatically runs the function in a separate ThreadPool, keeping the main Event Loop unblocked. However, if you use `async def` but perform blocking CPU-bound work (like calculating primes or calling `time.sleep()`), you physically block the single Event Loop thread. The server is completely paralyzed until the math finishes. To fix this, you must offload CPU-bound work to a `ProcessPoolExecutor` or use `run_in_executor`.", ["CPU-bound operations inside an `async def` physically block the single Event Loop thread", "When the Event Loop is blocked, no other incoming HTTP requests can be accepted or processed", "Fix: Offload heavy math or blocking code to a Thread/Process pool using `asyncio.to_thread` or executors"], ["The prime numbers were too large for the CPU cache"]),
    ("B63_1_10", "implement", "hard", "implement", ["ASGI / Web Architecture"], "How do you correctly implement an ASGI Middleware to log the execution time of a request, considering the asynchronous nature of the ASGI specification (scope, receive, send)?", "A raw ASGI middleware is a class/function that takes `app` and returns an asynchronous `__call__(scope, receive, send)`. To log execution time, you capture `start = time.time()`. However, you cannot simply `await app(scope, receive, send)` and then log, because in ASGI, the response might be a streaming body. The `send` callable is invoked multiple times (e.g., `http.response.start`, `http.response.body`). You must intercept the `send` callable by creating a wrapper function that checks for `event['type'] == 'http.response.start'`, logs the time, and then calls the original `send`.", ["Raw ASGI uses a 3-part callable signature: `scope` (metadata), `receive` (async stream in), `send` (async stream out)", "You cannot simply wrap the app call because streaming responses execute iteratively", "You must inject a wrapper around the `send` callable to intercept the exact moment the response headers are transmitted"], ["You just put a timer on the frontend"]),
    ("B63_1_11", "tradeoff", "medium", "tradeoff", ["ASGI / Web Architecture"], "What is the tradeoff of running FastAPI using Gunicorn with Uvicorn workers (`gunicorn -k uvicorn.workers.UvicornWorker`) versus running pure Uvicorn directly?", "Pure Uvicorn is a single-process ASGI server. If you run it directly, it only utilizes a single CPU core, regardless of how powerful the server is. By wrapping it in Gunicorn, Gunicorn acts as a robust Process Manager (Master Process). It spawns multiple Uvicorn worker processes (e.g., 4 workers for a 4-core machine), monitors their health, and automatically restarts them if they crash (Segfault/OOM). The tradeoff is increased architectural complexity, higher memory usage (4x processes), and the inability to share in-memory state (like a simple global dictionary cache) across the different Gunicorn workers.", ["Pure Uvicorn runs a single process, utilizing only 1 CPU core and crashing entirely on fatal errors", "Gunicorn acts as a Process Manager, spawning multiple ASGI workers to utilize all cores and providing auto-restarts", "Tradeoff: Multi-process architectures prevent sharing simple in-memory state (requires Redis)"], ["Gunicorn has horns, Uvicorn has wings"]),
    ("B63_1_12", "scenario", "hard", "scenario", ["ASGI / Web Architecture"], "In your FastAPI application, you have an endpoint that queries a database and then triggers a long-running background email task using FastAPI's `BackgroundTasks`. During a deployment, the server restarts. Users complain that they never received their emails. What is the fundamental flaw with this background execution model?", "FastAPI's `BackgroundTasks` execute inside the exact same memory space and event loop as the web server, AFTER the HTTP response is sent. They are entirely volatile. When Kubernetes or Gunicorn initiates a deployment/restart, it sends a `SIGTERM` to the process. The process finishes the current HTTP requests and shuts down, immediately killing any `BackgroundTasks` that were currently running or queued in memory. To fix this, mission-critical asynchronous work (like emails) MUST be offloaded to a persistent, durable distributed queue (like Celery or RQ backed by Redis/RabbitMQ) that survives web server restarts.", ["`BackgroundTasks` run in the web server's volatile memory and are tied to the process lifecycle", "A server restart (`SIGTERM`) instantly obliterates any queued or running background tasks", "Fix: Mission-critical tasks must be pushed to a durable external queue (Celery/RabbitMQ)"], ["The emails got stuck in the internet tubes"]),
    ("B63_1_13", "explain", "medium", "explain", ["ASGI / Web Architecture"], "Explain the concept of 'Request-Scoped State' (Context Variables) in Python 3.7+ (`contextvars`), and why `threading.local()` fails in async web frameworks.", "In synchronous WSGI (Flask), you track the current user by storing their ID in `threading.local()`, because 1 request = 1 dedicated OS thread. In ASGI (FastAPI), 10,000 requests are interleaved on a SINGLE OS thread. If you use `threading.local()`, Request A writes user ID 1, Request B writes user ID 2, and when Request A resumes, it accidentally reads user ID 2 (a catastrophic security leak). Python 3.7 introduced `contextvars`. A `ContextVar` is tied to the specific asynchronous `Task` (coroutine), not the OS thread. This allows you to safely store and retrieve request-specific state (like correlation IDs or database sessions) across deep async call stacks without explicitly passing it through every function argument.", ["`threading.local()` leaks data across requests in ASGI because thousands of requests share a single thread", "`contextvars` isolates state to the specific `asyncio.Task` (coroutine lifecycle)", "Crucial for passing implicit state (like Correlation IDs or User Sessions) securely in async web frameworks"], ["Contextvars are used to change the background color of the terminal"]),
    ("B63_1_14", "concept", "hard", "concept", ["ASGI / Web Architecture"], "What is the 'Sync/Async Boundary' problem in Python web applications, and what happens if you invoke a heavy SQLAlchemy (synchronous) query inside an ASGI middleware?", "The boundary problem occurs when mixing legacy synchronous code (like `requests` or `psycopg2`) with modern async frameworks. If you put a synchronous SQLAlchemy query inside an ASGI middleware, the query executes directly on the Event Loop thread. While the query waits 500ms for the database, the Event Loop is physically blocked. The web server is completely paralyzed and cannot accept new connections or process other concurrent users. The entire point of ASGI is defeated. You must cross the boundary safely by pushing the sync query into a ThreadPool (`run_in_executor`) or upgrading to an async database driver (like `asyncpg` or SQLAlchemy 2.0 Async).", ["Synchronous I/O in async frameworks physically blocks the core Event Loop", "A single blocking DB query paralyzes the entire web server, dropping concurrency to zero", "Fix: Use native async drivers (`asyncpg`) or offload sync code to a ThreadPoolExecutor"], ["The boundary is the firewall between the server and the database"]),

    # Testing & Debugging
    ("B63_1_15", "concept", "medium", "concept", ["Testing & Debugging"], "In pytest, what is a 'Fixture Scope' and why would setting a database connection fixture to `scope='function'` cause a massive test suite to take an hour to run?", "Fixture scope dictates how often the fixture's setup/teardown code executes. `scope='function'` (the default) means pytest will execute the setup code before EVERY single test, and tear it down after. If the fixture creates a Postgres database, runs migrations, and inserts seed data, doing this 5,000 times (once per test) will cause massive I/O overhead and take an hour. To fix this, you change the scope to `scope='session'`. The database is created exactly once when you type `pytest`, shared across all 5,000 tests, and torn down once at the end. (You must then use nested transaction rollbacks to isolate test state).", ["`scope='function'` executes setup/teardown for every single test independently", "Heavy operations (like DB migrations) cause astronomical I/O overhead if run per-test", "Fix: Use `scope='session'` to run expensive setup once, and use DB transactions to isolate individual test state"], ["Function scope means the fixture can only be used by functions, not classes"]),
    ("B63_1_16", "diagnose", "hard", "debugging", ["Testing & Debugging"], "You have a suite of asynchronous tests using `pytest-asyncio`. Test A creates an `asyncio.Queue`. Test B checks the queue. Randomly, Test B fails with `RuntimeError: Task attached to a different loop`. Why?", "By default, `pytest-asyncio` creates a brand new `asyncio` Event Loop for every single test to guarantee isolation. If Test A creates an object that binds to the running event loop (like an `asyncio.Queue` or `asyncio.Lock`) and stores it globally or in a session-scoped fixture, that object is permanently tied to Test A's Event Loop. When Test B runs, it executes in a brand NEW Event Loop. When Test B tries to await the Queue, Python detects a loop mismatch and throws a `RuntimeError`. To fix this, you must explicitly redefine the `event_loop` fixture to have `scope='session'`, forcing all tests to share the same loop, or carefully restrict async state to `function` scope.", ["`pytest-asyncio` strictly isolates tests by creating a new Event Loop for each test function", "Async primitives (Queues/Locks) are inherently bound to the loop they were created in", "Sharing async primitives across tests causes fatal Loop Mismatch errors"], ["The queue got confused and went to the wrong test"]),
    ("B63_1_17", "implement", "medium", "implement", ["Testing & Debugging"], "How do you implement 'Property-Based Testing' using the `Hypothesis` library in Python, and how is it different from traditional Unit Testing?", "In traditional Unit Testing, a developer hardcodes specific inputs (`assert add(2, 2) == 4`). This suffers from confirmation bias; you only test the edge cases you can think of. Property-Based Testing (Hypothesis) generates thousands of randomized, adversarial inputs automatically. You define the *properties* of the output. Example: `@given(st.lists(st.integers())) def test_sort(my_list):`. Hypothesis will feed your test empty lists, negative numbers, massive integers, and NaNs. If it finds a failure (e.g., your sort crashes on negative numbers), it performs 'Shrinking'—automatically stripping down the massive random input to find the absolute minimal reproducible example (e.g., `[-1]`) and reports it.", ["Traditional tests use hardcoded examples (confirmation bias)", "Hypothesis automatically generates thousands of edge-case inputs based on data types", "If a failure occurs, it 'Shrinks' the input to provide the absolute minimal reproducible test case"], ["Property based testing tests the real estate value of the code"]),
    ("B63_1_18", "tradeoff", "hard", "tradeoff", ["Testing & Debugging"], "What is the tradeoff of mocking external API dependencies (using `unittest.mock.patch`) versus using a tool like `VCR.py` to record and replay HTTP interactions?", "Mocking with `patch` is completely isolated and runs instantly. However, the tradeoff is 'Mock Drift'. The developer hardcodes what they *assume* the Stripe API returns. If Stripe changes their API tomorrow, your tests will still pass 100% locally, but production will crash violently. You are testing your own assumptions, not reality. `VCR.py` solves this by actually making the real HTTP request once, recording the exact binary response to a YAML file (cassette), and replaying it on future runs. The tradeoff is that VCR tests are brittle to dynamic data (timestamps/UUIDs), require managing cassette files, and occasionally require you to delete the cassettes and hit the real network to prevent staleness.", ["Mocking is fast but suffers from Mock Drift: tests pass even if the external API contract changes in reality", "VCR.py records real HTTP traffic to YAML cassettes, ensuring you test against real-world payloads", "Tradeoff: VCR cassettes become stale, break on dynamic data (timestamps), and require periodic re-recording"], ["Mocking means making fun of the code, VCR means recording it on tape"]),
    ("B63_1_19", "scenario", "medium", "scenario", ["Testing & Debugging"], "You have a Python CI/CD pipeline. Locally, the test suite takes 10 seconds. In CI (GitHub Actions), the tests randomly hang forever and the job times out after 60 minutes. You notice the tests use `multiprocessing.Pool`. Why does it hang only in CI?", "This is a classic Deadlock caused by `multiprocessing` Forking combined with implicit Thread/Lock state (often from logging or DB drivers). In Linux (CI), `multiprocessing` defaults to the `fork` start method. If the main process holds a lock (e.g., the global logging lock) at the exact millisecond the `fork` occurs, the child process inherits the locked state but NOT the thread that was going to release it. When the child process tries to log, it waits for the lock infinitely, causing a silent deadlock. To fix this, explicitly configure Python to use the `spawn` start method (`multiprocessing.set_start_method('spawn')`), which creates a fresh, clean Python interpreter without inheriting corrupted lock states.", ["`fork` duplicates memory state instantly, but only copies the calling thread", "If any other thread held a lock during the fork, the child inherits an un-releasable locked state (Deadlock)", "Fix: Explicitly set the multiprocessing start method to `spawn` for safe, clean worker processes"], ["The CI server is just slower than your laptop"]),
    ("B63_1_20", "explain", "medium", "explain", ["Testing & Debugging"], "Explain the concept of 'Mutation Testing' (e.g., using `mutmut`) and what metric it measures that Code Coverage misses.", "Code Coverage (100%) only proves that every line of code was *executed* during the test suite. It does not prove the tests actually assert anything; a test could just run a function and lack an `assert` statement. Mutation Testing physically modifies (mutates) your application's source code at runtime (e.g., changing `a + b` to `a - b`, or `if x > 5` to `if x >= 5`). It then runs your test suite. If the test suite STILL PASSES despite the source code being intentionally broken, that mutant 'survived'. This proves your tests are weak and missing critical assertions. Mutation testing measures the actual *strength and strictness* of your assertions, not just execution paths.", ["100% Code Coverage only means code was executed, not that it was rigorously asserted", "Mutation testing intentionally breaks the source code (e.g., changing `+` to `-`) and runs the tests", "If the tests still pass, the mutant 'survived', proving the assertions are weak or missing"], ["Mutation testing is when you expose the server to radiation"])
]

def run_batch():
    # Load all existing records to do deduplication
    with open(OUT, "r", encoding="utf-8") as f:
        existing = [json.loads(line) for line in f if line.strip()]

    print(f"Loaded {len(existing)} existing records.")
    
    for q in Q:
        if LEAK.search(q[5]) or LEAK.search(q[6]):
            print(f"PROMPT LEAK DETECTED in: {q[5]}")
            sys.exit(1)
            
    existing_texts = [ex["question"] for ex in existing]
    new_texts = [q[5] for q in Q]
    
    vec = TfidfVectorizer(stop_words="english", ngram_range=(1,2))
    all_texts = existing_texts + new_texts
    vec.fit(all_texts)
    
    existing_vecs = vec.transform(existing_texts)
    new_vecs = vec.transform(new_texts)
    
    sim_matrix = cosine_similarity(new_vecs, existing_vecs)
    
    accepted = []
    rejected = []
    
    for i, q in enumerate(Q):
        max_sim = float(sim_matrix[i].max()) if sim_matrix.shape[1] > 0 else 0
        if max_sim > 0.85:
            print(f"REJECTED (Sim: {max_sim:.2f}): {q[5][:50]}...")
            rejected.append(q)
        else:
            accepted.append(q)
            
    print(f"Accepted {len(accepted)} / {len(Q)} questions (Part 1).")
    
    new_records = []
    for q in accepted:
        rec = {
            "primary_role": ROLE,
            "applicable_roles": ["Systems Engineer", "Software Engineer"],
            "primary_skill": q[4][0],
            "secondary_skills": q[4][1:] if len(q[4]) > 1 else [],
            "technology": "Python",
            "topic": q[4][0] if len(q[4]) > 0 else "General",
            "category": "Software Engineering",
            "intent": q[1],
            "difficulty": q[2],
            "question_type": q[3],
            "question": q[5],
            "expected_answer": q[6],
            "evaluation_rubric": {
                "strong_indicators": q[7],
                "weak_indicators": q[8]
            },
            "id": str(uuid.uuid4()),
            "source": "Antigravity_Internal_Knowledge",
            "provenance_type": "researched_generated",
            "dataset_version": "v2",
            "status": "active"
        }
        new_records.append(rec)
        
    with open(OUT, "a", encoding="utf-8") as f:
        for r in new_records:
            f.write(json.dumps(r) + "\n")
            
    # Final audit reporting
    with open(OUT, "r", encoding="utf-8") as f:
        final_existing = [json.loads(line) for line in f if line.strip()]
        
    role_counts = Counter(r["primary_role"] for r in final_existing)
    
    print("\n========================================")
    print("POST-BATCH AUDIT")
    print("========================================")
    print(f"Batch: 63")
    print(f"Target role: {ROLE}")
    print(f"Attempted: {len(Q)}")
    print(f"Accepted: {len(accepted)}")
    print(f"Rejected: {len(rejected)}")
    print(f"Replacement count: 0")
    print(f"Cumulative total: {len(final_existing)}")
    print(f"{ROLE} total: {role_counts[ROLE]}")

if __name__ == "__main__":
    run_batch()
