import asyncio
import json
import os
import re
import sys
import uuid
from collections import Counter

from dotenv import load_dotenv
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
load_dotenv()

from phase4d_diversity_audit import fetch_all_supabase, normalize_text

BACKEND_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_DIR = os.path.join(BACKEND_DIR, "data")
REPORTS_DIR = os.path.join(BACKEND_DIR, "reports")
OUT = os.path.join(DATA_DIR, "interview_question_bank_v2_generated.jsonl")

ROLE = "Database Developer"
VALID_INTENTS = {"fundamentals", "explain", "implement", "tradeoff", "debug", "scenario", "compare",
                 "architecture", "optimize", "diagnose"}
LEAK = re.compile(r"(generate a question|generate \d+ questions|return only json|phase 4c gap plan|"
                  r"generation batch|candidate generation|system prompts|do not proceed|"
                  r"awaiting authorization|minimum target|generation pipeline|"
                  r"batch \d+ generation|expected answer|strong indicator|weak indicator|as an ai|"
                  r"here is the question|\bprompt text\b)", re.I)

def existing_supabase():
    out = []
    for r in asyncio.run(fetch_all_supabase()):
        meta = r.get("metadata", {})
        if meta.get("status") == "inactive":
            continue
        c = r.get("content", "")
        if "### Instruction:" in c and "### Output:" in c:
            q = c.split("### Instruction:")[1].split("### Output:")[0].strip()
            if "write a program" in q.lower() or "implement a function" in q.lower():
                continue
            a = c.split("### Output:")[1].strip()
        elif "**Answer:**" in c:
            q = c.split("**Answer:**")[0].replace("### Technical Interview Question", "").replace("**Question:**", "").strip()
            a = c.split("**Answer:**")[1].strip()
        else:
            q = meta.get("question", c[:200])
            a = meta.get("expected_answer", "")
        if len(set(re.findall(r"[a-z0-9]+", q.lower()))) < 3:
            continue
        out.append((q, a))
    return out

def opening(q, n=3):
    return " ".join(normalize_text(q).split()[:n])

Q = [
    # Bucket 1: DISTRIBUTED CONSENSUS (RAFT/PAXOS)
    ("B1", "tradeoff", "medium", "tradeoff", ["Consensus"], "When building a distributed database, what is the primary engineering tradeoff between choosing the Paxos consensus algorithm versus the Raft consensus algorithm?", "Mathematically and theoretically, Paxos and Raft are equivalent in fault tolerance. The primary tradeoff is 'Understandability' and implementation complexity. Paxos allows for peer-to-peer, leaderless or multi-leader variants which can theoretically reduce bottlenecking, but it is notoriously difficult to implement correctly in production. Raft enforces a strict, easily understandable Leader-Follower topology. Raft decomposes consensus into distinct, testable sub-problems (Leader Election, Log Replication, Safety), making it vastly safer and faster for engineering teams to implement and debug in production.", ["Raft enforces strict Leader-Follower topology; Paxos is often peer-to-peer/multi-leader", "Raft prioritizes understandability and decomposability", "Raft is vastly easier/safer to implement correctly in production"], ["Paxos uses SQL, Raft uses NoSQL"]),
    ("B1", "diagnose", "hard", "debugging", ["Consensus"], "In a 5-node Raft cluster, a network partition isolates the Leader (Node A) and Node B from the rest of the cluster (Nodes C, D, E). What exactly happens when a client sends a write request to Node A, and what happens when the partition heals?", "Node A (the isolated Leader) will accept the write request, append it to its local log, and attempt to replicate it to the followers. Because it can only reach Node B, it will never receive a majority quorum (needs 3). The write will stall and never be committed. Meanwhile, Nodes C, D, E form a majority, increment the Term number, and elect a new Leader. When the partition heals, Node A attempts to talk to the cluster, sees a higher Term number, instantly steps down to Follower, and completely discards its uncommitted, stalled writes.", ["Node A cannot reach majority quorum (3 nodes), so writes stall and are not committed", "Nodes C, D, E elect a new leader with a higher Term number", "When partition heals, Node A sees the higher term, steps down, and discards uncommitted logs"], ["Node A commits the write locally and causes a split brain"]),
    ("B1", "scenario", "medium", "scenario", ["Consensus"], "A distributed cluster experiences repeated, rapid leader elections every few seconds ('Flapping Leader'), even though the network is perfectly stable. What system-level failure mode on the Leader node could cause this?", "This is typically caused by severe 'Stop-the-World' Garbage Collection (GC) pauses (e.g., in Java-based systems like ZooKeeper/Cassandra) or severe CPU starvation. If the Leader's application process is frozen by the JVM for longer than the Raft/Paxos 'Election Timeout' configuration, it fails to send its periodic heartbeat messages to the followers. The followers assume the leader is dead and trigger a new election, even though the network and OS are perfectly healthy.", ["Stop-the-World Garbage Collection (GC) pauses", "CPU starvation/thrashing freezing the application process", "Leader fails to send heartbeats before the Election Timeout expires"], ["The followers are malicious"]),
    ("B1", "architecture", "medium", "architecture", ["Consensus"], "Explain how the Raft consensus algorithm prevents 'Split Votes' where two candidates endlessly tie during Leader Election.", "Raft prevents endless split votes by using 'Randomized Election Timeouts'. Instead of all followers waking up and declaring candidacy at the exact same millisecond when a leader dies, each follower is assigned a random timeout (e.g., between 150ms and 300ms). The follower with the shortest random timeout wakes up first, requests votes, and establishes a majority before any other node even starts its election process.", ["Randomized Election Timeouts", "Followers wake up at slightly different, randomized times", "The first to wake up secures the majority before others compete"], ["It asks a human administrator to break the tie"]),
    ("B1", "explain", "hard", "concept", ["Consensus"], "In Raft, what is the 'Commit Index', and how does it guarantee consistency across the state machine?", "The Commit Index is the highest log entry index known to be safely replicated to a majority of nodes. When the Leader replicates a log entry to a quorum, it increments its local Commit Index and piggybacks this updated index on the next heartbeat to the followers. Only when a log entry's index is <= the Commit Index is it considered 'safe', and only then do the Leader and Followers actually apply that log entry to their internal State Machine (e.g., updating a database table). This guarantees all nodes apply the exact same logs in the exact same order.", ["Highest log entry index safely replicated to a majority of nodes", "Piggybacked on heartbeats to notify followers", "Logs are only applied to the actual State Machine AFTER being committed"], ["It is the primary key of the database table"]),
    ("B1", "tradeoff", "hard", "tradeoff", ["Consensus"], "You are deploying a globally distributed consensus ring (e.g., Google Spanner/Paxos) across 3 regions: US, Europe, and Asia. What is the CAP theorem tradeoff regarding write latency?", "Because Paxos/Raft requires a strict majority quorum to commit a write, a global ring requires synchronous cross-oceanic network round-trips for every single write transaction. If the Leader is in the US, it must wait for an ACK from either Europe or Asia before committing. The tradeoff is absolute Consistency (C) and high Availability (A/Partition Tolerance) at the severe cost of massive Write Latency (often 100ms+ per transaction due to the speed of light).", ["Requires majority quorum, forcing synchronous cross-oceanic network round-trips", "Guarantees strict Consistency and high Availability/Partition Tolerance", "Severe tradeoff is massive Write Latency limited by the speed of light"], ["The database will run out of space"]),
    ("B1", "compare", "easy", "compare", ["Consensus"], "What is the difference between Crash Fault Tolerance (CFT) (e.g., Raft/Paxos) and Byzantine Fault Tolerance (BFT) (e.g., Blockchain consensus)?", "CFT assumes that nodes may fail, crash, drop messages, or experience network partitions, but they will never explicitly *lie* or send malicious/corrupted data. Raft and Paxos are CFT and require `(N/2) + 1` nodes to tolerate failures. BFT assumes that nodes might be actively compromised, malicious, or send conflicting lies to different peers. BFT algorithms are vastly more complex, slower, and typically require `(2/3)N + 1` honest nodes to reach consensus.", ["CFT: Nodes crash/drop messages but do not lie. Requires majority (N/2 + 1)", "BFT: Nodes may be malicious, compromised, or lie. Requires supermajority (2/3N + 1)", "Raft/Paxos are CFT, not designed for malicious actors"], ["CFT uses passwords, BFT does not"]),
    ("B1", "architecture", "medium", "architecture", ["Consensus"], "To prevent the Raft Write-Ahead Log (WAL) from growing infinitely and consuming all disk space, what architectural mechanism is used, and how does it help new nodes join the cluster?", "The mechanism is 'Snapshotting' (or Log Compaction). Periodically, the node takes the entire current in-memory state of the state machine and dumps it to disk as a snapshot, deleting all the raw WAL entries that preceded it. When a brand new, empty node joins the cluster, the Leader does not send millions of historical WAL logs; it simply transmits the latest massive Snapshot file over the network, and then resumes sending the recent WAL delta.", ["Snapshotting / Log Compaction", "Dumps current state machine state to disk and deletes historical WAL", "New nodes download the Snapshot instead of replaying millions of logs"], ["Zip compression of the text logs"]),
    ("B1", "scenario", "hard", "scenario", ["Consensus"], "A Raft leader receives a read request. How does it ensure it doesn't serve stale data if it was secretly partitioned from the network a millisecond ago and doesn't know it's no longer the leader?", "To serve a strictly consistent (linearizable) read, the Leader cannot simply read its local state, because it might be a 'Stale Leader' (a ghost) partitioned from the true quorum. The Leader must execute a 'Read Quorum' or send a round of 'Heartbeats' to a majority of the cluster *before* returning the read result to the client. If it receives majority ACKs, it proves it is still the true Leader and the local data is fresh.", ["Must prevent 'Stale Leader' (ghost) reads caused by sudden partitions", "Leader must send heartbeats/ping a majority quorum BEFORE returning read results", "Proves it still holds the leadership lease before serving local data"], ["It checks the atomic clock on the motherboard"]),
    ("B1", "diagnose", "medium", "debugging", ["Consensus"], "In a distributed consensus system, a write operation is sent to the Leader. The Leader successfully replicates it to the quorum and commits it, but the Leader crashes immediately *before* sending the 'Success' ACK back to the client. What is the state of the database, and what must the client do?", "The write is definitively committed in the database and will be present when the new leader takes over. However, from the client's perspective, the operation timed out or returned an error. The client does not know if the write succeeded or failed. The client must retry the operation. To prevent duplicating the data upon retry, the database architecture and the client request must be designed to be 'Idempotent' (e.g., using a unique transaction ID or UPSERT logic).", ["Write is successfully committed and persisted in the cluster", "Client receives a timeout/error and does not know the true state", "Client must retry, requiring Idempotent database design to prevent duplication"], ["The data is lost forever"]),

    # Bucket 2: REPLICATION & HIGH AVAILABILITY
    ("B2", "diagnose", "medium", "debugging", ["Replication"], "A replica database normally stays within 100ms of the primary. During an unoptimized batch UPDATE that touches 1 million rows, the replica falls 30 minutes behind, despite having massive CPU and Disk IO available. What architectural bottleneck causes this?", "The bottleneck is Single-Threaded WAL Replay. While the primary can execute massive batch jobs or concurrent writes using many threads, traditional replication (e.g., MySQL/Postgres default) streams the Write-Ahead Log (WAL) to the replica, which must replay those changes sequentially in a single thread to guarantee exact data consistency. A massive batch job blocks that single apply-thread, causing massive replication lag regardless of hardware. (Mitigated by logical replication or parallel replication).", ["Single-Threaded WAL Replay bottleneck", "Replica must apply changes sequentially to guarantee exact ordering", "Massive batch updates on primary block the single replay thread on replica"], ["The network cable is too slow"]),
    ("B2", "tradeoff", "easy", "tradeoff", ["Replication"], "What is the tradeoff between Synchronous Replication and Asynchronous Replication?", "Synchronous Replication guarantees absolute Zero Data Loss (Durability) because the primary waits for an ACK from the replica before confirming the commit to the client. The severe tradeoff is increased write latency and reduced availability (if the replica goes offline, the primary blocks writes). Asynchronous Replication offers lightning-fast write latency and high availability, but the tradeoff is the risk of Data Loss (if the primary crashes before the async WAL reaches the replica).", ["Synchronous: Zero data loss (high durability), but high latency/blocks on failure", "Asynchronous: Low latency/high availability, but risks data loss on primary crash", "Tradeoff between Durability/Consistency and Latency/Availability"], ["Synchronous means both databases are in the same building"]),
    ("B2", "architecture", "hard", "architecture", ["Replication"], "You use asynchronous replication for read-scaling. A user updates their profile picture (write to Primary) and immediately refreshes the page (read from Replica), but they see their old picture. How do you architect 'Read-After-Write Consistency' without abandoning async replication?", "You can solve this using Log Sequence Numbers (LSN) or Global Transaction IDs (GTID). When the user writes to the Primary, the API returns the exact LSN/GTID of that commit. When the user refreshes, the frontend passes that LSN to the backend. The backend routes the read to a Replica and explicitly asks: 'Have you applied up to this LSN yet?' If no, it waits, or it routes the specific read back to the Primary. This guarantees consistency for the writer while keeping async speed for everyone else.", ["Pass the write's LSN or GTID back to the client", "Client includes LSN on subsequent read requests", "Replica waits to apply up to LSN, or request is routed to Primary"], ["Just use a `time.sleep(2)` in the API code"]),
    ("B2", "scenario", "medium", "scenario", ["Replication"], "In a Multi-Region Active-Active database setup, User A in Europe and User B in the US simultaneously update the same exact row. How do distributed databases mechanically resolve this Write Conflict?", "Active-Active databases must resolve conflicts asynchronously since there is no single leader lock. They typically use 'Last-Write-Wins' (LWW) based on highly synchronized atomic clocks (e.g., Google Spanner TrueTime or NTP), where the highest timestamp overwrites the others. Alternatively, they use Vector Clocks to detect the conflict and either present it to the application layer to resolve, or use specialized data structures like CRDTs (Conflict-Free Replicated Data Types) which mathematically merge concurrent updates without data loss.", ["Last-Write-Wins (LWW) using synchronized atomic clocks (TrueTime/NTP)", "Vector Clocks to detect conflicts and push resolution to the app", "CRDTs (Conflict-Free Replicated Data Types) for mathematical merging"], ["The database shuts down to prevent data corruption"]),
    ("B2", "explain", "medium", "concept", ["Replication"], "What is 'Semi-Synchronous Replication' (e.g., in MySQL), and what failure scenario is it specifically designed to prevent?", "Semi-Synchronous Replication sits between Async and Sync. The primary writes to its local log, sends the log to the replicas, and waits for an ACK from *at least one* replica that the log has been received (written to the replica's disk/relay log, but not necessarily applied to the state machine yet). It is specifically designed to prevent Data Loss ('Phantom Commits') if the Primary suffers a catastrophic hardware failure. It guarantees the transaction exists on at least one surviving machine before acknowledging the client.", ["Waits for ACK from at least ONE replica that WAL is received (not applied)", "Prevents Data Loss / Phantom Commits if Primary suffers catastrophic failure", "Guarantees the transaction survives on at least one other machine"], ["It only synchronizes half of the database tables"]),
    ("B2", "diagnose", "hard", "debugging", ["Replication"], "You have a Primary and a Replica with Async replication. The Primary network disconnects. Your automated script immediately promotes the Replica to Primary. 10 minutes later, the old Primary network reconnects. What catastrophic state has your database entered, and how do modern systems prevent this?", "You have entered a 'Split-Brain' state. The old Primary still thought it was leader and accepted writes from localized clients, while the new Primary accepted writes from global clients. The data has fundamentally diverged and cannot be easily merged. Modern systems prevent this using a Consensus Manager (like ZooKeeper or etcd) and 'Fencing Tokens' (or Leases). The old Primary loses its lease timeout and self-demotes (or is physically STONITH fenced) *before* the new Primary is allowed to accept writes.", ["Split-Brain state: Both nodes act as primary and data diverges", "Automated failovers require a Consensus Manager (ZooKeeper/etcd)", "Uses Leases, Fencing Tokens, or STONITH to guarantee old primary is demoted"], ["The database automatically merges all conflicting rows perfectly"]),
    ("B2", "scenario", "hard", "scenario", ["Replication"], "In PostgreSQL, a data analyst runs a massive `SELECT` query on an asynchronous Replica that takes 2 hours. Meanwhile, the Primary is handling thousands of heavy `UPDATE`s. Why might this cause the Replica's replication stream to halt or crash?", "This is caused by MVCC Replication Conflicts. The Primary is updating rows and running `VACUUM` to delete the old, dead row versions. It sends these 'delete old rows' WAL records to the Replica. However, the 2-hour `SELECT` query on the Replica still explicitly needs those old row versions to maintain its Snapshot Isolation. To prevent corrupting the analyst's query, the Replica must pause applying the WAL (causing massive replication lag), or the Primary will force-cancel the analyst's query.", ["MVCC Replication Conflict", "Primary deletes old row versions (VACUUM) needed by the Replica's long query", "Replica must pause replication (lag) or cancel the long-running query"], ["The analyst's computer ran out of memory"]),
    ("B2", "optimize", "medium", "optimize", ["Database Operations"], "Your Primary database produces WAL logs at 500MB/s. Your Replica can only apply them at 200MB/s. You cannot upgrade the Replica hardware. To prevent the Replica from falling infinitely behind, what must you configure on the Primary?", "You must implement 'Replication Backpressure'. By configuring the Primary database to monitor the replica's lag (or bounding the size of the WAL retention queue), the Primary will intentionally throttle or block incoming client `WRITE` requests to match the 200MB/s speed of the replica. This degrades write throughput for clients, but guarantees the replica doesn't fall permanently behind or cause the Primary to run out of disk space storing unacknowledged WAL.", ["Implement Replication Backpressure", "Primary intentionally throttles/blocks incoming client writes", "Matches Primary throughput to the Replica's maximum apply speed"], ["Delete the WAL logs on the Primary immediately"]),
    ("B2", "architecture", "easy", "architecture", ["Database Operations"], "In database high-availability, what do the metrics RTO and RPO stand for, and how do they dictate replication strategy?", "RTO (Recovery Time Objective) is the maximum acceptable downtime (how fast you must failover to a replica). RPO (Recovery Point Objective) is the maximum acceptable data loss (e.g., losing the last 5 minutes of data). If the business demands an RPO of strictly 0.00 seconds (zero data loss), you *must* architect the system using Synchronous Replication. If an RPO of 5 minutes is acceptable, Asynchronous Replication is sufficient.", ["RTO: Recovery Time Objective (max downtime duration)", "RPO: Recovery Point Objective (max acceptable data loss)", "RPO of strictly zero demands Synchronous Replication"], ["RTO means Read Throughput Output"]),
    ("B2", "diagnose", "medium", "debugging", ["Replication"], "A primary database crashes catastrophically. You promote an async replica. Later, you extract the raw WAL files from the dead primary's hard drive. You notice the Primary's WAL is longer than the Replica's WAL. What does this mean for your application?", "It means Data Loss occurred. The Primary accepted writes, committed them locally, and returned 'Success' to the application clients, but crashed before those specific WAL logs could be transmitted over the async network to the Replica. The application believes those transactions exist, but the newly promoted database does not have them. You must either write a complex script to replay the orphaned WAL delta, or accept the permanent loss.", ["Data Loss occurred due to async replication lag before the crash", "Primary returned 'Success' to clients but failed to transmit WAL to replica", "Application state and database state are now inconsistent"], ["It just means the WAL file wasn't zipped properly"]),

    # Bucket 3: DISTRIBUTED DATABASES & SHARDING
    ("B3", "tradeoff", "hard", "tradeoff", ["Sharding"], "When horizontally partitioning a massive database, what is the architectural tradeoff between 'Hash-based Sharding' and 'Range-based Sharding'?", "Hash-based Sharding (e.g., `hash(user_id) % N`) guarantees perfectly even data distribution and prevents 'hot spots' on new data, but entirely destroys the ability to perform efficient Range Queries (e.g., `WHERE user_id BETWEEN 100 AND 200`), forcing a scatter-gather full cluster scan. Range-based Sharding preserves data locality for highly efficient Range Queries, but is incredibly susceptible to 'Hot Partitions' (e.g., all new users get inserted into the exact same shard, overloading one machine).", ["Hash: Perfectly even distribution, but destroys Range Queries (requires scatter-gather)", "Range: Efficient Range Queries, but highly susceptible to Hot Partitions/bottlenecks", "Tradeoff between read efficiency on ranges vs write distribution"], ["Hash uses MD5, Range uses SHA256"]),
    ("B3", "diagnose", "medium", "debugging", ["Sharding"], "You implement Hash-based sharding by `tenant_id`. Your cluster has 50 shards. Shard #7 has 99% CPU utilization and crashes, while the other 49 shards are at 5% CPU. What is the diagnosis and how do you mitigate it?", "This is a 'Hot Partition' (or Data Skew/Hot Key) caused by a massive 'Whale' tenant. Even though hashing distributes *keys* evenly, it does not distribute *volume* evenly if one tenant generates 1000x more traffic than others. To mitigate, you must implement 'Compound Sharding Keys' (e.g., `hash(tenant_id + user_id)`) to force the whale tenant's data to spread across multiple shards, or manually isolate the whale tenant onto dedicated hardware.", ["Hot Partition / Data Skew caused by a 'Whale' tenant", "Hash distributes unique keys evenly, but not traffic volume per key", "Mitigate using Compound Sharding Keys to split the whale across shards"], ["The hashing algorithm was implemented in Python instead of C++"]),
    ("B3", "architecture", "hard", "architecture", ["Distributed Databases"], "Why do Cross-Shard Transactions (implementing Two-Phase Commit / 2PC) drastically severely degrade throughput in a distributed database?", "Two-Phase Commit requires a central coordinator. In Phase 1 (Prepare), the coordinator asks all participating shards to lock their rows and guarantee they can commit. If all say yes, Phase 2 (Commit) executes. This requires multiple network round-trips while holding exclusive write locks on rows across multiple physical machines. If any network delay occurs, or one node is slow, the locks are held open, blocking all other transactions in the cluster from touching those rows, crushing concurrency and throughput.", ["Requires multiple synchronous network round-trips across machines", "Holds exclusive distributed locks during the 'Prepare' phase", "Slow nodes/network jitter cause lock queuing, crushing concurrency"], ["2PC requires downloading the entire database to the coordinator"]),
    ("B3", "scenario", "medium", "scenario", ["Distributed Databases"], "In a Dynamo-style eventual consistency database (like Cassandra), the cluster is configured with a Replication Factor of 3. You want strong consistency for a critical banking read. How do you configure the Quorum parameters (`R` and `W`) to guarantee you never read stale data?", "You must configure the Read and Write parameters such that `R + W > N` (where N is the Replication Factor, 3). For example, if you set `W=2` (Wait for 2 nodes to acknowledge the write) and `R=2` (Read from 2 nodes and take the latest timestamp), the read quorum (2) and the write quorum (2) strictly overlap. At least one node in your read quorum is mathematically guaranteed to have the absolute latest write, ensuring strong consistency without needing a single leader.", ["Must configure R + W > N (Replication Factor)", "E.g., Write=2, Read=2 overlaps on at least one node", "Mathematical overlap guarantees the Read Quorum catches the latest Write"], ["Set W=0 and R=3"]),
    ("B3", "explain", "medium", "concept", ["Sharding"], "Explain how 'Consistent Hashing' solves the massive data migration problem when adding a new node to a sharded cluster.", "In naive modulo sharding (`hash(key) % 5`), adding a 6th node changes the denominator (`% 6`), completely altering the hash result for almost every key, requiring a catastrophic reshuffling of the entire database. Consistent Hashing maps keys and nodes onto a conceptual 'Ring'. A key belongs to the first node located clockwise on the ring. When a new node is added, it simply takes over a specific slice of the ring from its immediate neighbor. Only that specific subset of data moves, while 90% of the cluster data remains entirely untouched.", ["Naive modulo sharding forces 100% data reshuffle when N changes", "Consistent Hashing maps nodes and keys to a Ring topology", "Adding a node only requires moving data from its immediate neighbor"], ["Consistent hashing ensures the hashes never change passwords"]),
    ("B3", "architecture", "hard", "architecture", ["Distributed Databases"], "You have a massively sharded database partitioned by `user_id`. You frequently need to search for users by their `email_address`. Why is this architecturally problematic, and what are the two indexing strategies to solve it?", "Searching by `email_address` does not contain the `user_id` shard key, forcing a 'Scatter-Gather' query that hits every single shard in the cluster (highly inefficient). To solve this, you use Secondary Indexes. Option 1: 'Local Secondary Index'—each shard indexes its own emails, still requiring scatter-gather but faster locally. Option 2: 'Global Secondary Index' (GSI)—a completely separate, asynchronously updated sharded table partitioned specifically by `email_address` that maps to the `user_id`.", ["Query lacks the shard key, forcing a full cluster scatter-gather scan", "Local Secondary Index: Each shard indexes itself (still requires scatter-gather)", "Global Secondary Index: A separate table sharded by email mapping back to user_id"], ["Use a SELECT * WHERE email query"]),
    ("B3", "explain", "medium", "concept", ["Distributed Databases"], "In eventual consistency distributed databases, what is 'Hinted Handoff' and what failure mode does it solve?", "When a coordinator node tries to write to a replica node that is temporarily offline, the write normally fails. Hinted Handoff solves this: the coordinator accepts the write anyway, stores a local 'hint' (the data payload) on its own disk, and monitors the dead node. The moment the dead node comes back online, the coordinator automatically forwards the hints to it. It ensures high write availability during temporary network blips without requiring full data repairs later.", ["Stores a local 'hint' of the write when target node is temporarily offline", "Automatically forwards the data when the node reconnects", "Ensures high write availability during temporary network blips"], ["It gives hints to the SQL optimizer"]),
    ("B3", "tradeoff", "easy", "tradeoff", ["Distributed Databases"], "What is the CAP theorem tradeoff for a distributed database during a Network Partition?", "The CAP theorem states that during a Network Partition (P) (e.g., the network link between two datacenters is physically severed), the system MUST choose between Consistency (C) and Availability (A). It cannot have both. If it chooses Consistency, it must block/reject writes to ensure data doesn't diverge (sacrificing Availability). If it chooses Availability, it accepts writes on both sides of the severed link, allowing data to diverge and resolving conflicts later (sacrificing Consistency).", ["During a Network Partition (P), you must choose between C and A", "Consistency blocks writes to prevent data divergence", "Availability accepts writes but causes data divergence (split brain)"], ["CAP means CPU, Availability, and Power"]),
    ("B3", "diagnose", "medium", "debugging", ["Distributed Databases"], "You are using an AP (Available/Partition Tolerant) distributed database. A developer notices that immediately after writing a record, reading it back sometimes returns `NULL`. A second later, it returns the data. What is happening?", "This is standard 'Eventual Consistency' and replication lag. In an AP system, the write is quickly acknowledged by the coordinator or a local node, but it takes a few milliseconds to asynchronously replicate to the other nodes. If the immediate read request happens to hit a different node that hasn't received the replication payload yet, it returns stale data (`NULL`). The developer must implement a 'Read-Your-Writes' consistency session or use Quorum reads to fix this.", ["Eventual Consistency / Asynchronous replication lag", "The immediate read hit a node that hadn't received the write payload yet", "Requires session consistency (Read-Your-Writes) or Quorum reads"], ["The hard drive is spinning up"]),
    ("B3", "scenario", "hard", "scenario", ["Distributed Databases"], "You bring a brand new, completely empty shard online to expand cluster capacity. Suddenly, the entire database cluster slows to a crawl and crashes. What distributed systems problem caused this?", "This is the 'Thundering Herd' (or Cache Stampede / Hot Shard) problem during rebalancing. Because the new shard has zero data, the Consistent Hashing algorithm immediately assigns it a massive chunk of the hash ring. Thousands of concurrent requests instantly route to this new node. Because its caches are completely cold and it is busy streaming gigabytes of data from peers to hydrate itself, the CPU locks up, causing requests to time out, which causes clients to violently retry, cascading the failure.", ["Thundering Herd / Cache Stampede on a cold node", "New node receives massive traffic routing while its caches are totally cold", "Causes instant CPU lockup and cascading timeout retries from clients"], ["The new shard was infected with a virus"]),

    # Bucket 4: SCHEMA MIGRATION & ZERO-DOWNTIME ENGINEERING
    ("B4", "architecture", "hard", "architecture", ["Schema Migration"], "You need to rename a column `first_name` to `given_name` on a billion-row production table. If you simply run `ALTER TABLE RENAME`, the application code will crash during the deployment window. Detail the 'Expand and Contract' pattern for zero-downtime.", "Zero-downtime schema migrations require 4 distinct deployments. 1. EXPAND: Add the new `given_name` column (nullable) to the DB. 2. DUAL-WRITE: Update app code to write to BOTH columns, but read from the old. 3. BACKFILL & SWAP: Run a background script to backfill old rows. Update app code to read/write ONLY from the new column. 4. CONTRACT: Safely drop the old `first_name` column from the DB. This decouples database state from application code deployment.", ["1. Expand: Add new column (nullable)", "2. Dual-Write: App writes to both, reads from old", "3. Backfill & Swap: Backfill old data, app reads/writes to new only", "4. Contract: Drop old column safely"], ["Just shut down the website at 3 AM"]),
    ("B4", "diagnose", "medium", "debugging", ["Database Operations"], "You run `CREATE INDEX idx_user ON users(email)` on a massive production table. The database instantly locks up, and all application `INSERT` and `UPDATE` statements timeout. What architectural mistake did you make?", "A standard `CREATE INDEX` statement takes an aggressive exclusive write lock (e.g., ShareLock) on the entire table to ensure data stability while it builds the B-Tree. For massive tables, this build can take hours, completely blocking all production writes. You must architect migrations using Online Index Creation (e.g., `CREATE INDEX CONCURRENTLY` in Postgres), which builds the index in the background over multiple passes without blocking ongoing DML writes.", ["Standard CREATE INDEX takes a table-level exclusive write lock", "Blocks all INSERT/UPDATE/DELETE queries for the duration of the build", "Must use Online Index Creation (e.g., CREATE INDEX CONCURRENTLY)"], ["The index name was too long"]),
    ("B4", "tradeoff", "medium", "tradeoff", ["Schema Migration"], "When planning a massive database architecture migration, what is the tradeoff between a 'Roll-Forward' failure strategy versus a 'Rollback' failure strategy?", "A Rollback strategy attempts to undo the migration and revert to the previous database schema/state. The tradeoff is that restoring massive databases from backup takes hours, resulting in catastrophic downtime, and any data written during the migration window is lost. A Roll-Forward strategy abandons the old system entirely; if a failure occurs, engineering pushes hotfixes to the new system to stabilize it. Roll-forward is often the only mathematically viable option for massive, stateful distributed systems.", ["Rollback: Restoring massive state takes hours (downtime) and loses new writes", "Roll-Forward: Fixes the new system via hotfixes without losing state", "Roll-Forward is often mandatory for massive stateful distributed systems"], ["Roll-forward uses a mouse, Rollback uses a keyboard"]),
    ("B4", "scenario", "hard", "scenario", ["Schema Migration"], "You execute an `ALTER TABLE` to add a new column with a `DEFAULT` value to a Postgres table with 10 Billion rows. The database disk usage doubles and the query takes 5 hours. Why did this happen, and how do modern databases optimize this?", "In older database versions (e.g., Postgres < 11), adding a `DEFAULT` value forces the database engine to physically rewrite every single one of the 10 Billion rows on disk to append the new value (Table Rewrite). This causes massive I/O, lock contention, and disk bloat. Modern databases optimize this via 'Metadata Defaults': they simply store the default value once in the system catalog metadata. When reading old rows, if the column is physically missing, it instantly injects the catalog default.", ["Older DBs physically rewrite every row on disk to append the default (Table Rewrite)", "Modern DBs use 'Metadata Defaults' stored in the system catalog", "Injects the default value dynamically on read without rewriting disk"], ["The database downloaded the default value from the internet"]),
    ("B4", "architecture", "medium", "architecture", ["Schema Migration"], "During a Zero-Downtime migration, your application consists of a fleet of 50 Kubernetes pods. A deployment takes 10 minutes to roll out, meaning old pods and new pods are running simultaneously. How does this impact your database migration strategy?", "This requires strict 'Schema-Version Compatibility'. Because both v1 and v2 of the application code are hitting the database simultaneously during the 10-minute rollout window, the database schema MUST support both. You cannot drop a column, rename a table, or add a strict `NOT NULL` constraint until you mathematically guarantee that 100% of the old pods have been terminated. Database changes must be strictly additive.", ["Requires strict Schema-Version Compatibility", "Database must support both v1 and v2 application logic simultaneously", "Cannot execute destructive changes (DROP, NOT NULL) until rollout completes"], ["Just restart all 50 pods at the exact same millisecond"]),
    ("B4", "diagnose", "hard", "debugging", ["Database Operations"], "You run a simple, fast `ALTER TABLE add column phone (nullable)` that normally takes 5 milliseconds. Suddenly, the entire database goes down. You check `pg_stat_activity` and see a massive queue of `SELECT` queries waiting behind your `ALTER TABLE`. What caused this?", "This is 'Lock Queuing' caused by a long-running transaction. The `ALTER TABLE` requires a brief `AccessExclusiveLock`. However, there was an uncommitted, long-running transaction (e.g., a massive `SELECT` or a sleepy session) holding a weak lock on the table. The `ALTER` must wait for that session to finish. While the `ALTER` is waiting in the queue, it blocks *all* subsequent queries (even simple reads) from acquiring weak locks, instantly cascading into a total database freeze.", ["Lock Queuing / Lock Contention", "ALTER requires AccessExclusiveLock but waits for a long-running transaction", "While waiting, it blocks ALL subsequent reads/writes, causing a cascade freeze"], ["The column name was a reserved SQL keyword"]),
    ("B4", "scenario", "medium", "scenario", ["Schema Migration"], "You are migrating a massive monolithic database to a Sharded architecture. The monolithic database uses strict Foreign Key (FK) constraints everywhere. Why must you fundamentally redesign the data integrity model?", "Foreign Keys require the database to instantly verify the existence of a row in another table. In a distributed, sharded architecture, the parent table and the child table are often located on completely different physical servers. Enforcing a physical FK would require synchronous, cross-network locks for every single `INSERT` or `DELETE`, crushing performance. In sharded systems, physical FKs are almost always dropped, and referential integrity is enforced purely at the application code layer.", ["Sharding places tables on different physical servers", "Physical FKs require slow, synchronous cross-network distributed locks", "Must drop DB-level FKs and enforce integrity at the application layer"], ["Foreign Keys only work in English"]),
    ("B4", "optimize", "medium", "optimize", ["Schema Migration"], "You need to run a data backfill script across 500 Million rows in a live production OLTP database. If you run `UPDATE users SET status = 'active'`, it takes down production. Architect a safe backfill execution strategy.", "A safe backfill must be throttled and batched. You must process the table in small chunks (e.g., `WHERE id BETWEEN 1 AND 1000`). Crucially, between each chunk, the script must `sleep()` or check database replication lag to yield resources back to production traffic. This prevents filling up the WAL/Transaction Log, prevents massive MVCC bloat, prevents long-held row locks, and allows replicas to keep up with the primary.", ["Process in small batches (e.g., 1000 rows at a time)", "Introduce sleep/yields between batches", "Monitor replication lag to prevent WAL bloat and lock contention"], ["Just run it on Sunday night"]),
    ("B4", "tradeoff", "easy", "tradeoff", ["Schema Migration"], "When validating a massive database migration (e.g., moving from Postgres to Cassandra), what is the tradeoff between relying on 'Application Metric Monitoring' versus 'Out-of-band Diffing'?", "Application monitoring (checking 500 error rates or latency) is instant and easy, but it suffers from 'Silent Corruption'—if the new database silently drops 5% of records but returns HTTP 200s, the app metrics look perfect. Out-of-band Diffing (running a background script that explicitly compares every row in Postgres against Cassandra) guarantees exact data integrity, but it is extremely complex to engineer, highly CPU intensive, and difficult to manage with constantly updating data.", ["App Metrics: Easy/fast, but completely misses silent data corruption", "Diffing: Guarantees exact data integrity, but complex and CPU intensive", "Diffing is required to mathematically prove migration safety"], ["Diffing is for text files, not databases"]),
    ("B4", "architecture", "hard", "architecture", ["Database Operations"], "What is the architectural purpose of a 'Dead-Letter Queue' (DLQ) in an asynchronous database replication pipeline (like Debezium / Change Data Capture)?", "In an asynchronous CDC pipeline, the consumer reads database changes from a stream (Kafka) and applies them to a target system. If a specific payload is malformed or hits a constraint error, the consumer crashes. If it restarts, it reads the exact same malformed payload and crashes again (a 'Poison Pill' infinite loop). A DLQ solves this: after N failed retries, the consumer routes the bad payload to a separate DLQ topic and continues processing the rest of the stream, allowing engineers to manually debug the poison pill later.", ["Prevents 'Poison Pill' infinite crash loops in streaming replication", "Routes malformed/failing payloads to a separate queue after N retries", "Allows the replication stream to continue flowing for healthy data"], ["It stores deleted emails"]),

    # Bucket 5: STORAGE ENGINES & OBSERVABILITY (LSM vs B-TREE)
    ("B5", "compare", "hard", "compare", ["Storage Engines"], "Explain the fundamental structural tradeoff between a B-Tree storage engine (e.g., Postgres/MySQL) and an LSM-Tree (Log-Structured Merge-Tree) storage engine (e.g., Cassandra/RocksDB) regarding I/O performance.", "B-Trees update data in-place on disk. They provide blazing-fast, consistent Reads, but suffer from heavy 'Write Amplification' (updating a tiny row requires rewriting an entire disk page), making them poor for massive write-heavy workloads. LSM-Trees are append-only; writes are sequentially dumped to memory and flushed to disk immutably. This provides astronomical Write throughput (no random I/O). The tradeoff is degraded Read performance (reads must scan multiple immutable files) and high CPU overhead for background Compaction.", ["B-Trees: In-place updates, fast reads, but heavy random I/O Write Amplification", "LSM-Trees: Append-only sequential writes, extreme write throughput", "LSM tradeoff: Slower reads and high CPU background Compaction overhead"], ["B-Trees are for text, LSM is for numbers"]),
    ("B5", "explain", "medium", "concept", ["Storage Engines"], "In an LSM-Tree database, why is background 'Compaction' absolutely critical for read performance and disk usage?", "Because LSM-Trees are strictly append-only, updating a row 5 times creates 5 distinct, immutable files (SSTables) on disk. To read the current value, the database must scan all 5 files, crushing read performance (Read Amplification). Compaction is a background CPU process that periodically merges these fragmented files, discards the old overwritten versions, and writes a single new, clean file. This reclaims disk space and restores fast read performance.", ["LSM-Trees are append-only; updates create fragmented, redundant files", "Compaction merges files and discards overwritten/deleted data", "Restores read performance and reclaims disk space"], ["Compaction compresses the data into a ZIP file"]),
    ("B5", "diagnose", "medium", "debugging", ["Storage Engines"], "You issue a `DELETE` query to an LSM-Tree database (like Cassandra) to remove 1 million old rows. However, disk space actually *increases*, and `SELECT` queries suddenly become much slower. What architectural mechanism causes this?", "LSM-Trees are immutable; they cannot physically delete data in-place. A `DELETE` statement actually writes a brand new record called a 'Tombstone' (a marker saying the row is deleted). This consumes *more* disk space immediately. During a `SELECT`, the database must scan the original data AND the Tombstone to realize the data is hidden, slowing down reads. The disk space is only reclaimed, and reads optimized, later when background Compaction runs.", ["LSM-Trees are immutable; deletes are written as new 'Tombstone' markers", "Tombstones consume extra disk space immediately", "Reads slow down because they must scan and evaluate the tombstones until Compaction runs"], ["The database has a recycle bin"]),
    ("B5", "architecture", "medium", "architecture", ["Database Operations"], "What is the specific architectural purpose of the Write-Ahead Log (WAL) in providing Durability (the 'D' in ACID) during a catastrophic power failure?", "In a database, writing data directly to the scattered B-Tree on disk requires random I/O, which is slow. Instead, databases modify data in fast RAM (Buffer Pool) and only append a sequential, fast text record of the change to the WAL on disk. When returning 'Success' to the client, only the WAL is guaranteed to be on disk. If power fails, the RAM is wiped. Upon reboot, the database reads the WAL and mathematically replays every sequential change to reconstruct the B-Tree in RAM perfectly.", ["Avoids slow random I/O by appending sequential logs to disk", "Changes are kept in fast RAM; only the WAL is guaranteed persisted on commit", "On crash reboot, the WAL is replayed to perfectly reconstruct the RAM state"], ["It keeps a log of user IP addresses for security"]),
    ("B5", "diagnose", "medium", "debugging", ["Database Operations"], "Your application servers spawn 5,000 parallel threads, opening 5,000 direct connections to PostgreSQL. The database completely locks up, utilizing 100% of its RAM without processing queries. What architectural limitation did you hit, and how do you fix it?", "PostgreSQL uses a 'Process-per-Connection' architecture (unlike MySQL's thread-per-connection). Each of the 5,000 connections forks a heavy, memory-intensive OS process. This consumes all available RAM and causes massive OS context-switching (thrashing), locking the CPU. You must implement a Connection Pooler (e.g., PgBouncer) architected *in front* of Postgres. The application connects 5,000 times to PgBouncer, which multiplexes those lightweight requests into a small, healthy pool of ~100 actual heavy Postgres connections.", ["Postgres forks a heavy OS process for every single connection", "5,000 connections cause memory exhaustion and CPU thrashing", "Fix by deploying a multiplexing Connection Pooler (like PgBouncer)"], ["Postgres requires a license for more than 100 connections"]),
    ("B5", "diagnose", "hard", "debugging", ["Database Operations"], "In Postgres (an MVCC database), a table with 10 million rows is heavily updated. Over time, queries slow to a crawl, and the table consumes 5x its normal disk space. You discover `autovacuum` has failed to run. What is happening internally?", "This is 'Table Bloat' (or Dead Tuples). Because Postgres uses Multi-Version Concurrency Control (MVCC), an `UPDATE` does not overwrite the row; it creates a brand new hidden row and marks the old one as 'dead'. Without `autovacuum` running to reclaim the physical disk space of those dead rows, the table bloats massively. The B-Tree indexes also bloat. Sequential scans and index scans now have to read gigabytes of dead garbage data, destroying performance.", ["MVCC UPDATEs create new rows and mark old rows as 'dead'", "Failed autovacuum means dead rows (Table Bloat) are never reclaimed", "Queries must scan massive amounts of garbage data, destroying IO performance"], ["The database is saving a backup in the same table"]),
    ("B5", "scenario", "medium", "scenario", ["Database Operations"], "Transaction A locks Row 1 and wants to update Row 2. Transaction B locks Row 2 and wants to update Row 1. Both wait infinitely. What is this state, and how do databases structurally resolve it?", "This is a 'Deadlock' (a circular lock dependency). The database engine structurally resolves this using a Deadlock Detector—a background process that periodically scans the lock graph for cycles. When it finds a cycle, it unilaterally violently kills one of the transactions (rolling it back) and throws a deadlock error to the client, freeing the locks for the surviving transaction. The architectural fix is for the application code to always acquire locks in a strict, consistent alphabetical/numerical order.", ["Deadlock (circular lock dependency)", "Database background detector finds the cycle and kills/rolls back one transaction", "App architecture fix: Always acquire locks in a consistent, deterministic order"], ["Reboot the server"]),
    ("B5", "tradeoff", "hard", "tradeoff", ["Transactions"], "Explain how 'Snapshot Isolation' (MVCC) prevents the 'Phantom Read' anomaly, but why it still suffers from the 'Write Skew' anomaly.", "Snapshot Isolation prevents Phantom Reads by giving each transaction a static, frozen snapshot of the database at the exact millisecond the transaction started; it simply cannot see rows inserted by other commits after that timestamp. However, it suffers from Write Skew because two concurrent transactions can read the *same* frozen snapshot, make disjoint independent updates based on that snapshot, and both commit successfully, resulting in a violated business constraint (e.g., two doctors un-scheduling themselves because they both saw the other on duty in their snapshot). Strict Serializable isolation is required to prevent Write Skew.", ["Snapshot prevents Phantom Reads by reading a frozen point-in-time state", "Write Skew occurs when two transactions make disjoint updates based on the same frozen read", "Requires strict Serializable isolation to block concurrent skewed writes"], ["Snapshot Isolation takes a photograph of the screen"]),
    ("B5", "architecture", "medium", "architecture", ["Database Operations"], "Explain the mechanics of 'Point-in-Time Recovery' (PITR). How do you restore a database to exactly 2:14 PM yesterday?", "PITR relies on two components: a physical Base Backup (a snapshot of the data files taken, e.g., weekly) and a continuous archive of every Write-Ahead Log (WAL) generated since that backup. To restore to 2:14 PM, the DBA restores the physical Base Backup to a new server, and then configures the database to sequentially replay the archived WAL files. The replay engine is instructed to mathematically halt execution the exact millisecond it processes the WAL timestamp of 2:14 PM.", ["Requires a physical Base Backup and a continuous archive of WAL files", "Restores the Base Backup first", "Sequentially replays the WAL logs and halts exactly at the target timestamp"], ["Ask the application logs for the data"]),
    ("B5", "diagnose", "hard", "debugging", ["Storage Engines"], "In a distributed NoSQL database, you partition data by `user_id`. A user requests their entire purchase history, sorted by `purchase_date`. The query is extremely slow. Why is sorting by a non-partition key slow, and what data modeling structure solves this?", "In NoSQL, data is physically scattered across the cluster by the partition key (`user_id`). If you sort by a field that isn't part of the physical clustering order, the database must pull all the user's records into RAM and perform an expensive in-memory sort. To solve this, you must define a 'Clustering Key' (or Sort Key) on `purchase_date` during table creation. The storage engine will then physically write the data sequentially on the hard drive pre-sorted by date within that specific user's partition, allowing blazing-fast O(1) sequential reads.", ["Sorting on non-clustering keys forces expensive in-memory sorts", "Define a Clustering Key / Sort Key on `purchase_date`", "Forces the storage engine to physically write the data pre-sorted on disk"], ["NoSQL databases cannot sort data natively"])
]

BUCKET_KEYS = {
    "B1": ("Distributed Consensus", "Raft/Paxos", "Distributed Systems", ["Database Developer", "Backend Developer"]),
    "B2": ("Replication", "High Availability", "Database Administration", ["Database Developer", "DevOps / Cloud Engineer"]),
    "B3": ("Distributed Databases", "Sharding", "NoSQL", ["Database Developer"]),
    "B4": ("Schema Migrations", "Zero-Downtime Deployments", "Database Operations", ["Database Developer", "Backend Developer"]),
    "B5": ("Storage Engines", "Database Internals", "RDBMS", ["Database Developer"])
}

def main():
    with open(OUT, encoding="utf-8") as f:
        prior = [json.loads(l) for l in f if l.strip()]
    
    staged_q = [p["question"] for p in prior]
    staged_a = [p["expected_answer"] for p in prior]
    
    sup = existing_supabase()
    staged_q.extend([q for q, _ in sup])
    staged_a.extend([a for _, a in sup])

    cands = []
    for b, intent, diff, qt, sec, q, a, strong, weak in Q:
        skill, topic, tech, roles = BUCKET_KEYS[b]
        cands.append({
            "primary_role": ROLE,
            "applicable_roles": roles,
            "primary_skill": skill,
            "secondary_skills": sec,
            "technology": tech,
            "topic": topic,
            "category": "Database Engineering",
            "intent": intent,
            "difficulty": diff,
            "question_type": qt,
            "question": q,
            "expected_answer": a,
            "evaluation_rubric": {"strong_indicators": strong, "weak_indicators": weak}
        })

    corpus = staged_q + staged_a + [c["question"] for c in cands] + [c["expected_answer"] for c in cands]
    vec = TfidfVectorizer(stop_words="english", ngram_range=(1, 2)).fit(corpus)
    SQ, SA = vec.transform(staged_q), vec.transform(staged_a)
    SC = vec.transform([x + " " + y for x, y in zip(staged_q, staged_a)])
    seen_norm = {normalize_text(q) for q in staged_q}

    rej = Counter()
    accepted = []
    details = []
    ans_flags = []
    
    for idx, c in enumerate(cands):
        nq = normalize_text(c["question"])
        reason = None
        if nq in seen_norm:
            reason = "exact_duplicate"
        else:
            qs = cosine_similarity(vec.transform([c["question"]]), SQ)[0]
            as_ = cosine_similarity(vec.transform([c["expected_answer"]]), SA)[0]
            comp = cosine_similarity(vec.transform([c["question"] + " " + c["expected_answer"]]), SC)[0]
            
            details.append((float(qs.max()), float(as_.max()), float(comp.max())))
            if as_.max() >= 0.5:
                ans_flags.append((c["question"][:70], round(float(as_.max()), 3)))
                
            if qs.max() >= 0.80:
                reason = "near_duplicate"
            elif comp.max() >= 0.60:
                reason = "semantic_competency_duplicate"
            elif as_.max() >= 0.70:
                reason = "expected_answer_overlap"
                
        if not reason and LEAK.search(c["question"] + " " + c["expected_answer"]):
            reason = "prompt_leakage"
        
        if reason:
            rej[reason] += 1
            print(f"Rejected Q{idx+1}: {reason}")
            continue
            
        seen_norm.add(nq)
        accepted.append(c)

    print(f"Attempted: {len(cands)}, Accepted: {len(accepted)}, Rejected: {sum(rej.values())}")
    
    if len(accepted) != 50:
        print(f"ERROR: Did not accept exactly 50 (got {len(accepted)}). Aborting write.")
        sys.exit(1)

    for c in accepted:
        c["id"] = "gen_" + str(uuid.uuid4())
        c["generation_batch"] = "batch_49_database_developer"

    with open(OUT, "a", encoding="utf-8") as f:
        for c in accepted:
            f.write(json.dumps(c) + "\n")
            
    final_staging_total = len(prior) + len(accepted)
    role_counts = Counter(p.get("primary_role") for p in prior)
    role_counts[ROLE] += len(accepted)
    
    diff_counts = Counter(c["difficulty"] for c in accepted)
    intent_counts = Counter(c["intent"] for c in accepted)
    skill_counts = Counter(c["primary_skill"] for c in accepted)
    tech_counts = Counter(c["technology"] for c in accepted)
    topic_counts = Counter(c["topic"] for c in accepted)
    openings = Counter(opening(c["question"], 3) for c in accepted)
    
    bq = [c["question"] for c in accepted]
    M = cosine_similarity(vec.transform(bq)) if bq else [[0]]
    intra = [(i, j, round(float(M[i][j]), 3)) for i in range(len(bq)) for j in range(i + 1, len(bq)) if M[i][j] >= 0.6]
    intra_qa = cosine_similarity(vec.transform([c["expected_answer"] for c in accepted])) if bq else [[0]]
    intra_ans = [(i, j, round(float(intra_qa[i][j]), 3)) for i in range(len(bq)) for j in range(i + 1, len(bq)) if intra_qa[i][j] >= 0.5]
    
    report = {
        "batch": "batch_49_database_developer",
        "records_attempted": len(cands),
        "records_accepted": len(accepted),
        "records_rejected": sum(rej.values()),
        "rejection_reasons": dict(rej),
        "max_similarity_scores": {
            "question": round(max((d[0] for d in details), default=0), 3),
            "answer": round(max((d[1] for d in details), default=0), 3),
            "combined": round(max((d[2] for d in details), default=0), 3)
        },
        "intra_batch_overlaps": len(intra),
        "intra_batch_answer_overlaps": len(intra_ans),
        "answer_flags_gt_50": len(ans_flags),
        "staging_metrics": {
            "previous_staging_total": len(prior),
            "final_staging_total": final_staging_total,
            "role_total": role_counts[ROLE],
            "remaining_to_500": max(0, 500 - role_counts[ROLE])
        },
        "distributions": {
            "difficulty": dict(diff_counts),
            "intent": dict(intent_counts),
            "primary_skill": dict(skill_counts),
            "technology": dict(tech_counts),
            "topic": dict(topic_counts),
            "opening_diversity": dict(openings.most_common(10))
        }
    }
    
    with open(os.path.join(REPORTS_DIR, "phase4d_batch49_report.json"), "w", encoding="utf-8") as f:
        json.dump(report, f, indent=2)
        
    with open(os.path.join(REPORTS_DIR, "phase4d_batch49_report.md"), "w", encoding="utf-8") as f:
        f.write(f"# Phase 4D - Batch 49 (Database Developer)\n\n")
        f.write(f"- **Attempted**: {len(cands)}\n")
        f.write(f"- **Accepted**: {len(accepted)}\n")
        f.write(f"- **Rejected**: {sum(rej.values())}\n")
        f.write(f"- **Rejections**: {dict(rej)}\n\n")
        f.write("### Staging Totals\n")
        f.write(f"- **Previous Staging Total**: {len(prior)}\n")
        f.write(f"- **Final Staging Total**: {final_staging_total}\n")
        f.write(f"- **Database Developer Role Total**: {role_counts[ROLE]}\n")
        f.write(f"- **Remaining to 500 Target**: {report['staging_metrics']['remaining_to_500']}\n\n")
        f.write("### Similarity\n")
        f.write(f"- **Max Question Sim**: {report['max_similarity_scores']['question']}\n")
        f.write(f"- **Max Answer Sim**: {report['max_similarity_scores']['answer']}\n")
        f.write(f"- **Max Combined Sim**: {report['max_similarity_scores']['combined']}\n")
        f.write(f"- **Intra-batch Overlaps**: {len(intra)}\n")
        f.write(f"- **Answer Overlaps (>0.5)**: {len(ans_flags)}\n\n")
        f.write("### Distributions\n")
        f.write(f"- **Difficulty**: {dict(diff_counts)}\n")
        f.write(f"- **Intent**: {dict(intent_counts)}\n")
        f.write(f"- **Primary Skill**: {dict(skill_counts)}\n")
        f.write(f"- **Technology**: {dict(tech_counts)}\n")
        f.write(f"- **Topic**: {dict(topic_counts)}\n\n")
        f.write("### Top Openings\n")
        for op, count in openings.most_common(8):
            f.write(f"- `{op}`: {count}\n")

    print(f"Successfully generated 50 Database Developer questions.")

if __name__ == "__main__":
    main()
