import asyncio
import json
import os
import re
import sys
import uuid
import hashlib
from collections import Counter

from dotenv import load_dotenv
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
load_dotenv()

BACKEND_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_DIR = os.path.join(BACKEND_DIR, "data")
OUT = os.path.join(DATA_DIR, "interview_question_bank_v2_generated.jsonl")

ROLE = "DevOps / Cloud Engineer"
LEAK = re.compile(r"(generate a question|generate \d+ questions|return only json|phase 4c gap plan|"
                  r"generation batch|candidate generation|system instructions|do not proceed|"
                  r"awaiting authorization|minimum target|generation pipeline|"
                  r"batch \d+ generation|expected answer|strong indicator|weak indicator|as an ai|"
                  r"here is the question|\bprompt text\b)", re.I)

Q = [
    # Group 3 (Remaining 4 questions): Infrastructure as Code
    ("B61_3_7", "diagnose", "medium", "debugging", ["Terraform"], "Your team uses Terraform workspaces to manage multiple environments (dev, staging, prod) within the exact same set of `.tf` files. A junior developer deploys to 'prod', and 5 minutes later accidentally runs `terraform destroy` while still in the 'prod' workspace instead of 'dev'. How do you architecturally prevent this from ever happening?", "Terraform Workspaces are a dangerous anti-pattern for environment isolation because they share the same physical backend and execution context; human error is one CLI command away. To prevent this, you must adopt a 'Directory-per-Environment' architecture (or use a tool like Terragrunt). 'Prod' and 'Dev' should be physically separate folders with strictly separated state files (`prod.tfstate`, `dev.tfstate`) and strictly separate IAM execution roles in CI/CD. The 'dev' IAM role physically cannot delete resources in the 'prod' AWS account.", ["Workspaces share execution context and rely on human CLI discipline, leading to catastrophic accidents", "Architectural fix: Directory-per-environment separation (or Terragrunt)", "Use strict, isolated State Files and isolated CI/CD IAM roles so dev physically cannot mutate prod"], ["You take away the junior developer's keyboard"]),
    ("B61_3_8", "concept", "easy", "concept", ["Terraform"], "What is Open Policy Agent (OPA) and how does it integrate with Infrastructure as Code pipelines?", "OPA is a Policy-as-Code engine. It allows security teams to write strict governance rules in the Rego language (e.g., 'All S3 buckets must be encrypted', 'EC2 instances cannot use t2.micro'). You integrate OPA into the CI/CD pipeline immediately after `terraform plan`. OPA intercepts the JSON plan output and evaluates it against the rules. If a developer's code violates a policy, OPA instantly fails the pipeline *before* the `terraform apply` can execute, mathematically preventing non-compliant infrastructure from ever being deployed.", ["Policy-as-Code engine (using Rego) to enforce security and governance", "Runs against the `terraform plan` JSON output in CI/CD", "Blocks `terraform apply` if the infrastructure violates compliance rules"], ["It is an agent that helps you write open-source code"]),
    ("B61_3_9", "tradeoff", "hard", "tradeoff", ["Terraform"], "What is the tradeoff of relying heavily on massive, multi-tiered Terraform Modules published by the community versus writing custom, flatter Terraform code in-house?", "Community modules (e.g., the official `terraform-aws-vpc` module) are incredibly feature-rich and save hours of initial setup. The severe tradeoff is opacity and upgrade nightmares. A community module might contain 50 files and 200 nested variables to account for every possible edge case in the world. When a new Terraform version or AWS provider drops, upgrading that nested black-box module can take weeks of debugging obscure interpolation errors. Writing flatter, custom code in-house means you only maintain exactly the 5 variables your company actually uses, vastly simplifying long-term maintenance at the cost of higher initial development time.", ["Community modules provide instant, feature-complete setups", "Tradeoff: They are opaque black boxes built for every edge case, making them extremely difficult to upgrade/debug", "In-house code is flatter and tailored exactly to your needs, vastly reducing long-term maintenance overhead"], ["Community modules are written in French"]),
    ("B61_3_10", "implement", "medium", "implement", ["Terraform"], "How do you securely import a manually created database (ClickOps) into an existing Terraform state file so it can be managed by code?", "First, you must write the exact HCL declarative code (`resource \"aws_db_instance\" \"main\" { ... }`) in your `.tf` files that matches the existing manual database configuration. Then, you run the CLI command: `terraform import aws_db_instance.main db-instance-identifier`. This command fetches the live metadata from AWS and injects it into the Terraform State file, linking it to your code block. Finally, you run `terraform plan`. If the plan shows '0 to add, 0 to change, 0 to destroy', the import was perfectly successful.", ["Write the corresponding HCL resource block in your `.tf` file", "Run `terraform import <resource_path> <cloud_id>` to inject it into the State file", "Verify with `terraform plan` to ensure zero unintended changes (drift)"], ["You drag and drop the database icon into the Terraform folder"]),

    # Group 4: Cloud Reliability & DR
    ("B61_4_1", "concept", "medium", "concept", ["Reliability Engineering"], "Explain the difference between RTO (Recovery Time Objective) and RPO (Recovery Point Objective) in Disaster Recovery planning.", "RPO is about Data Loss: 'How much data can we legally/operationally afford to lose?' If you back up the database every 1 hour, your RPO is 1 hour (a crash at 1:59 means 59 minutes of data is permanently gone). RTO is about Downtime: 'How fast must the system be back online?' If the primary region burns down, and it takes 4 hours to spin up new servers in the backup region from Terraform, your RTO is 4 hours. High-availability architectures (Active-Active) strive for RPO=0 and RTO=0, but cost exponentially more than Active-Passive backups.", ["RPO (Recovery Point Objective): Acceptable amount of Data Loss (dictates backup frequency)", "RTO (Recovery Time Objective): Acceptable amount of Downtime (dictates infrastructure failover speed)", "Approaching zero for both requires extremely expensive Active-Active replication architecture"], ["RTO is for robots, RPO is for people"]),
    ("B61_4_2", "diagnose", "hard", "debugging", ["Reliability Engineering"], "Your multi-region Active-Active application uses AWS Aurora Global Database. `us-east-1` is the Primary (Writer), and `us-west-2` is the Secondary (Reader). The `us-east-1` region suffers a catastrophic physical outage. You manually trigger a DNS failover to route all users to `us-west-2`. The web servers in `us-west-2` are healthy, but the application is entirely broken, throwing HTTP 500s. Why?", "While the DNS successfully routed users to the secondary region, the Database in `us-west-2` is still configured strictly as a Read Replica. It physically rejects all `INSERT/UPDATE` queries. Global Databases do not automatically promote themselves to Writers upon a primary region failure to prevent 'Split-Brain' scenarios. You must manually execute an API call (or have an automated Lambda script) to 'Promote' the `us-west-2` cluster to a standalone Writer instance. Only then will the application be able to mutate data and function normally.", ["The secondary region's database is stuck in Read-Only mode", "Global Databases require manual or scripted 'Promotion' to Writer status during a failover to prevent split-brain", "Routing traffic without promoting the database causes all write queries to fail (HTTP 500)"], ["The DNS forgot the password to the database"]),
    ("B61_4_3", "implement", "hard", "implement", ["Reliability Engineering"], "How do you architect a system to handle a severe 'Dependency Failure' (e.g., Stripe API is completely down) without bringing down your entire e-commerce infrastructure?", "You must architect the system using 'Circuit Breakers', 'Timeouts', and 'Graceful Degradation' queues. If the Stripe API is down, standard synchronous API calls will hang, exhausting your backend connection pools and crashing your site. 1) Enforce strict 1-second timeouts. 2) The Circuit Breaker detects 5 consecutive timeouts and instantly 'trips' open, rejecting further calls to Stripe locally without waiting. 3) To save the user experience, the system degrades gracefully: it accepts the user's order, saves it to an internal Kafka 'Retry Queue' with a 'Payment Pending' status, and returns a friendly success message to the user. When Stripe recovers, a background worker processes the queue.", ["Enforce strict timeouts to prevent connection pool exhaustion", "Implement Circuit Breakers to fail-fast and shed load from the broken dependency", "Degrade gracefully by queueing the action asynchronously (Kafka/SQS) and processing it when the dependency recovers"], ["You just print an error message blaming Stripe"]),
    ("B61_4_4", "tradeoff", "medium", "tradeoff", ["Reliability Engineering"], "What is the tradeoff of designing a Disaster Recovery plan as 'Pilot Light' versus 'Warm Standby'?", "A 'Pilot Light' architecture replicates the core data (DB sync) to the secondary region, but keeps the expensive compute servers (EC2/EKS) turned completely OFF until a disaster actually happens. It is incredibly cheap, but the RTO (Recovery Time) is slow (e.g., 30 minutes to spin up the servers). A 'Warm Standby' architecture keeps a scaled-down version of the compute servers running continuously in the secondary region. It costs significantly more on a monthly basis, but provides a vastly faster RTO (minutes) because you only need to auto-scale the existing servers rather than booting them from scratch.", ["Pilot Light: Core data is synced, but compute is OFF. Cheap, but slow RTO (booting servers takes time)", "Warm Standby: Scaled-down compute is always ON. Faster RTO, but significantly higher monthly cloud costs", "Tradeoff: Monthly infrastructure cost versus the speed of disaster recovery (RTO)"], ["A pilot light requires actual natural gas to run in the datacenter"]),
    ("B61_4_5", "scenario", "medium", "scenario", ["Reliability Engineering"], "You are running a massive batch processing job on AWS Spot Instances to save money. The job takes 4 hours. Because Spot Instances can be terminated by AWS with a 2-minute warning at any time, the job rarely finishes. How do you re-architect the application to survive Spot terminations?", "You must re-architect the batch job to be 'Stateful and Checkpointed'. The application cannot process the massive payload in RAM. It must consume granular tasks from an SQS queue. Every 5 minutes, it must save its intermediate state (checkpoints) to S3/DynamoDB. When the 2-minute Spot termination signal hits, the application must catch the `SIGTERM`, gracefully stop taking new SQS messages, upload its final checkpoint, and exit. When the Autoscaler spins up a replacement Spot Instance, the new instance downloads the last checkpoint and resumes exactly where the dead node left off.", ["Spot instances are ephemeral and volatile; long-running monolithic jobs will constantly fail", "Architect the job to consume granular tasks (SQS) and save state 'Checkpoints' frequently (S3/DB)", "Catch the 2-minute termination warning, gracefully halt, and allow new nodes to resume from the last checkpoint"], ["You tell AWS not to terminate your specific instances"]),
    ("B61_4_6", "explain", "medium", "explain", ["Reliability Engineering"], "Explain the concept of 'Chaos Engineering' and how tools like Chaos Monkey improve systemic reliability.", "Chaos Engineering is the practice of intentionally injecting failures into a production (or staging) system to verify that the automated recovery mechanisms actually work before a real disaster hits. Chaos Monkey (developed by Netflix) randomly terminates EC2 instances in production during business hours. This forces the engineering team to architect systems that are fundamentally resilient to hardware failure (using Auto Scaling Groups, Load Balancers, and stateless microservices). If the system can survive continuous, random sabotage without users noticing, it is mathematically proven to be resilient to real-world outages.", ["The intentional injection of failures into a system to test resilience and recovery automation", "Chaos Monkey randomly terminates servers to enforce stateless, auto-scaling architectures", "Proves that theoretical Disaster Recovery plans actually work in reality"], ["Chaos engineering means hiring chaotic developers to write messy code"]),

    # Group 5: Observability & Incident Response
    ("B61_5_1", "concept", "medium", "concept", ["Observability"], "What are 'High Cardinality Metrics', and why do they cause monitoring systems like Prometheus to crash?", "Cardinality refers to the number of unique combinations of metric labels/tags. If you track HTTP requests with the label `status_code` (200, 404, 500), the cardinality is 3. It's safe. If a developer accidentally adds `user_id` as a label, and you have 10 million users, the cardinality instantly explodes to 10 million unique time-series data streams. Prometheus (and Datadog) must hold these unique streams in memory. A high cardinality explosion will instantly consume 100% of the monitoring server's RAM (OOMKill) and incur massive billing costs.", ["Cardinality is the number of unique label/tag combinations in a metric", "Adding unbounded labels (like `user_id` or `session_id`) creates millions of unique time-series streams", "Causes catastrophic memory exhaustion (OOMKill) in Prometheus and massive bills in Datadog"], ["High cardinality means the metrics are singing very loudly"]),
    ("B61_5_2", "diagnose", "hard", "debugging", ["Observability"], "You are the on-call DevOps engineer. At 2:00 AM, you get a PagerDuty alert: 'CPU usage on Node-A is 99%'. You log in, but the application is responding perfectly, latency is normal, and users are unaffected. By 4:00 AM, you have received 15 more identical alerts. What is wrong with your alerting philosophy, and how do you fix it?", "This is 'Alert Fatigue' caused by 'Cause-Based Alerting'. Alerting on raw infrastructure metrics (CPU, RAM) is an anti-pattern because high CPU does not necessarily mean the user is experiencing an outage (it might just be a healthy background compression job). You must shift to 'Symptom-Based Alerting' (SLO/SLI Alerting). You should only wake up an engineer if the *User Experience* is broken (e.g., 'API Error Rate > 5%' or 'P99 Latency > 2 seconds'). CPU spikes should be logged for capacity planning, but should never trigger a page unless they degrade the user-facing SLI.", ["Cause-Based Alerting (e.g., High CPU) creates noisy false positives and severe Alert Fatigue", "High resource usage does not automatically correlate to a degraded user experience", "Fix by shifting to Symptom-Based Alerting (SLIs/SLOs): only page when error rates or latency impact the user"], ["The CPU was just exercising at night"]),
    ("B61_5_3", "implement", "medium", "implement", ["Observability"], "How do you implement 'Distributed Tracing' across a microservice architecture to debug latency bottlenecks?", "You must implement the OpenTelemetry SDK (or a vendor equivalent) in every microservice. When the API Gateway receives an initial request, it generates a unique W3C `traceparent` Header (Trace ID). This ID must be injected into the HTTP headers of every downstream request (Service A -> Service B -> Database). Each service records the start and end time of its operation (Spans) and asynchronously ships them to a collector (Jaeger, Datadog). The tracing backend groups all spans by the Trace ID, rendering a visual Gantt chart that instantly reveals which specific microservice or DB query caused the latency.", ["Generate a unique Trace ID at the ingress layer", "Propagate the Trace ID via HTTP headers through every downstream microservice", "Services emit timed 'Spans' to a central collector, visualizing the end-to-end latency path"], ["You use a physical magnifying glass on the server rack"]),
    ("B61_5_4", "tradeoff", "medium", "tradeoff", ["Observability"], "What is the operational tradeoff of 100% Log Aggregation versus implementing dynamic 'Log Sampling' in a high-volume microservice environment?", "100% Log Aggregation sends every single `HTTP 200 OK` access log to Elasticsearch/Splunk. It guarantees perfect auditability, but the storage and indexing costs are astronomical (easily hundreds of thousands of dollars a year for heavy traffic). Log Sampling intelligently drops data. You might configure the collector to drop 99% of `HTTP 200` logs, but retain 100% of `HTTP 500` error logs and 100% of logs tied to a specific failing Trace ID. The tradeoff is massive cost savings versus the risk of losing benign operational context that might be useful during a forensic security audit.", ["100% Aggregation: Perfect auditability, but astronomical storage/indexing costs", "Log Sampling: Drops successful/benign logs (e.g., 99% of HTTP 200s) to save massive costs", "Tradeoff: Financial savings versus the risk of losing forensic context for benign anomalies"], ["Log sampling means you physically taste the wood of the logs"]),
    ("B61_5_5", "scenario", "hard", "scenario", ["Observability"], "A critical payment microservice silently stopped processing payments. There were no HTTP 500 errors, no CPU spikes, and the health checks returned 200 OK. The service was just deadlocked. How do you configure observability to catch 'Silent Failures' like this automatically?", "Standard metrics (CPU, HTTP Errors) cannot detect deadlocks because the system isn't technically 'failing', it's just 'doing nothing'. To catch silent failures, you must implement 'Business Logic Metrics' (Custom Metrics). The application should increment a Prometheus counter `payments_processed_total` on every success. You then create an alert in Alertmanager using a `rate()` function: `rate(payments_processed_total[5m]) == 0`. If the rate of successful business transactions drops to exactly zero during normal business hours, it instantly triggers an alert, catching the silent deadlock regardless of infrastructure health.", ["Infrastructure metrics (CPU, HTTP 500s) cannot detect internal thread deadlocks (Silent Failures)", "Implement Business Logic Custom Metrics (e.g., `payments_processed_total`)", "Alert on the velocity/rate of business metrics dropping to zero, bypassing infrastructure health illusions"], ["You just stare at the screen 24/7 waiting for a payment"]),
    ("B61_5_6", "explain", "medium", "explain", ["Observability"], "Explain the concept of 'Burn Rate' alerting in SRE (Site Reliability Engineering).", "Traditional alerting triggers if an error rate spikes over a static threshold (e.g., > 5%) for 5 minutes. This creates noise during minor blips. 'Burn Rate' alerting is tied directly to your Error Budget (the allowed downtime per month). If your SLA allows 43 minutes of downtime a month, a 'Fast Burn' alert calculates that the current outage is burning through your monthly budget 10x faster than normal, meaning your budget will be exhausted in 3 days. A 'Slow Burn' alert indicates you are burning the budget 2x faster than normal, which won't trigger a 2 AM page, but will create a Jira ticket for Monday morning. It perfectly aligns alerts with long-term business goals.", ["Ties alerts directly to the depletion of the monthly Error Budget (SLO)", "Fast Burn (e.g., 10x burn rate) triggers immediate 2 AM pages because the budget will exhaust rapidly", "Slow Burn (e.g., 2x burn rate) creates low-priority tickets, eliminating noisy alerts for minor anomalies"], ["Burn rate is how fast the server physically catches on fire"]),

    # Group 6: Security / IAM
    ("B61_6_1", "concept", "medium", "concept", ["Cloud Security"], "What is 'Workload Identity' (e.g., AWS IAM Roles for Service Accounts - IRSA) and why is it superior to using hardcoded API Keys?", "Historically, to give a Kubernetes pod access to an S3 bucket, you created a static IAM User, generated `Access Keys`, and stored them in a Kubernetes Secret. This is dangerous: keys leak, they never expire, and rotating them breaks apps. Workload Identity binds a native Kubernetes Service Account directly to an AWS IAM Role. The AWS provider automatically injects temporary, rotating STS credentials into the pod's memory. The pod uses the IAM Role natively. There are zero static keys to leak, zero rotation management, and the blast radius is restricted exactly to that single pod.", ["Eliminates the need for static, long-lived AWS IAM Access Keys stored in Kubernetes Secrets", "Binds a Kubernetes Service Account directly to a cloud IAM Role", "Provides temporary, automatically rotating credentials, drastically reducing credential theft risk"], ["Workload identity is a nametag the server wears to work"]),
    ("B61_6_2", "diagnose", "hard", "debugging", ["Cloud Security"], "You configure an S3 bucket with a strictly locked down Bucket Policy: `Deny * if aws:SourceIp != 10.0.0.0/16`. An EC2 instance inside that exact VPC (10.0.0.5) attempts to access the bucket, but gets `AccessDenied`. Why did the IP restriction block an internal resource?", "When the EC2 instance communicates with S3, it usually routes out through an Internet Gateway or NAT Gateway. If it goes through the NAT Gateway, its IP is masked by the NAT's public Elastic IP, which does not match the private `10.0.x.x` rule. Even if using a VPC Endpoint (PrivateLink), S3 evaluates the traffic as coming from the VPC Endpoint ID, not the raw private IP. To fix this securely, you must change the Bucket Policy from an IP restriction to a VPC Endpoint restriction (`Condition: StringEquals: aws:SourceVpce: vpce-12345`).", ["Traffic routing through a NAT Gateway masks the private IP with a Public IP, failing the condition", "S3 evaluating traffic over VPC Endpoints uses the VPCE ID, not the raw private IP", "Fix: Change the Bucket Policy condition to `aws:SourceVpce` to restrict access safely to the internal network"], ["The S3 bucket doesn't like the EC2 instance"]),
    ("B61_6_3", "implement", "hard", "implement", ["Cloud Security"], "How do you implement secure Cross-Account IAM access (e.g., Account A needs to read an S3 bucket in Account B) without sharing API keys?", "You use IAM Role Assumption (STS AssumeRole). In Account B (the target), you create an IAM Role with permission to read the S3 bucket. Crucially, you modify the 'Trust Relationship' of that Role to explicitly allow Account A's ID to assume it. In Account A (the source), you grant an EC2 instance permission to call `sts:AssumeRole` on Account B's Role ARN. When the code runs, Account A asks STS to assume the role. STS returns temporary, 1-hour credentials. Account A uses those credentials to read the bucket. Zero static keys are shared.", ["Create an IAM Role in Account B with a Trust Policy allowing Account A to assume it", "Grant the identity in Account A the `sts:AssumeRole` permission for that specific Role ARN", "Account A dynamically assumes the role at runtime to receive temporary, 1-hour credentials"], ["You just email the password from Account A to Account B"]),
    ("B61_6_4", "tradeoff", "medium", "tradeoff", ["Cloud Security"], "What is the operational tradeoff of using AWS KMS 'Customer Managed Keys' (CMK) versus 'AWS Managed Keys' to encrypt an S3 bucket?", "AWS Managed Keys are completely free and zero-maintenance; AWS rotates them automatically, and you just click a checkbox to enable encryption at rest. The severe tradeoff is loss of granular access control. With a Customer Managed Key (CMK), you pay a monthly fee and per-request API costs, but you control the Key Policy. You can dictate that even if an attacker hacks an AWS Administrator account and gives themselves full S3 read permissions, they STILL cannot read the bucket unless they are explicitly added to the CMK Key Policy, providing a secondary, unbreakable layer of encryption-based authorization.", ["AWS Managed: Free, zero maintenance, but lacks granular control", "Customer Managed (CMK): Costs money (monthly + API calls), but provides a powerful secondary authorization layer", "Tradeoff: Cost/Complexity vs the ability to explicitly deny access via Key Policies even to AWS Admins"], ["CMKs are made of brass, AWS keys are made of plastic"]),
    ("B61_6_5", "scenario", "medium", "scenario", ["Cloud Security"], "A developer accidentally commits an AWS Access Key to a public GitHub repository. Within 2 minutes, you get an automated alert from GitGuardian. What are your exact operational steps to remediate this incident?", "Speed is critical; bots scan GitHub in seconds and will spin up Bitcoin miners instantly. 1) DO NOT attempt to delete/rewrite the Git history first; the bots already have the key. 2) Log into the AWS Console immediately, find the IAM User, and DEACTIVATE (Inactivate) the exposed Access Key (do not delete it yet, in case it breaks a production app and you need to quickly audit CloudTrail to see what it was used for). 3) Review AWS CloudTrail for the last 5 minutes to see if the attacker successfully spun up EC2 instances or stole data. 4) Rotate the key (generate a new one and update the app). 5) Finally, delete the old key and scrub the Git history using BFG Repo-Cleaner.", ["DO NOT waste time scrubbing Git first; the key is already stolen by automated bots", "Immediately DEACTIVATE the key in AWS IAM to halt access", "Audit CloudTrail for unauthorized API calls, rotate the key in the application, and finally scrub the repo"], ["Just delete the git repository and pretend it never happened"]),
    ("B61_6_6", "explain", "hard", "explain", ["Cloud Security"], "Explain what a Software Bill of Materials (SBOM) is, and how it mitigates Supply Chain attacks in CI/CD.", "A Supply Chain attack occurs when an attacker compromises a popular open-source dependency (e.g., `log4j` or an NPM package). If your CI/CD pipeline blindly runs `npm install`, you pull the malware directly into your production Docker image. An SBOM is a mathematically generated, cryptographically signed manifest of every single library, dependency, and transitive dependency inside your container. By generating an SBOM during the CI build and enforcing policies against it (e.g., scanning it for known CVEs or unapproved licenses before deployment), you gain absolute visibility and prevent compromised third-party code from entering your infrastructure.", ["A cryptographic, exhaustive inventory of every dependency inside a compiled artifact/container", "Mitigates supply chain attacks (e.g., compromised NPM packages)", "Allows CI/CD admission controllers to block deployments if the SBOM contains banned or vulnerable libraries"], ["An SBOM is a receipt from the grocery store for the developers"])
]

def run_batch():
    # Load all existing records to do deduplication
    with open(OUT, "r", encoding="utf-8") as f:
        existing = [json.loads(line) for line in f if line.strip()]

    print(f"Loaded {len(existing)} existing records.")
    
    for q in Q:
        if LEAK.search(q[5]) or LEAK.search(q[6]):
            print(f"PROMPT LEAK DETECTED in: {q[5]}")
            sys.exit(1)
            
    existing_texts = [ex["question"] for ex in existing]
    new_texts = [q[5] for q in Q]
    
    vec = TfidfVectorizer(stop_words="english", ngram_range=(1,2))
    all_texts = existing_texts + new_texts
    vec.fit(all_texts)
    
    existing_vecs = vec.transform(existing_texts)
    new_vecs = vec.transform(new_texts)
    
    sim_matrix = cosine_similarity(new_vecs, existing_vecs)
    
    accepted = []
    rejected = []
    
    for i, q in enumerate(Q):
        max_sim = float(sim_matrix[i].max()) if sim_matrix.shape[1] > 0 else 0
        if max_sim > 0.85:
            print(f"REJECTED (Sim: {max_sim:.2f}): {q[5][:50]}...")
            rejected.append(q)
        else:
            accepted.append(q)
            
    print(f"Accepted {len(accepted)} / {len(Q)} questions (Part 2).")
    
    new_records = []
    for q in accepted:
        rec = {
            "primary_role": ROLE,
            "applicable_roles": ["Cloud Architect", "Security Engineer"],
            "primary_skill": q[4][0],
            "secondary_skills": q[4][1:] if len(q[4]) > 1 else [],
            "technology": "AWS / Kubernetes",
            "topic": q[4][0] if len(q[4]) > 0 else "General",
            "category": "Infrastructure",
            "intent": q[1],
            "difficulty": q[2],
            "question_type": q[3],
            "question": q[5],
            "expected_answer": q[6],
            "evaluation_rubric": {
                "strong_indicators": q[7],
                "weak_indicators": q[8]
            },
            "id": str(uuid.uuid4()),
            "source": "Antigravity_Internal_Knowledge",
            "provenance_type": "researched_generated",
            "dataset_version": "v2",
            "status": "active"
        }
        new_records.append(rec)
        
    with open(OUT, "a", encoding="utf-8") as f:
        for r in new_records:
            f.write(json.dumps(r) + "\n")
            
    # Final audit reporting
    with open(OUT, "r", encoding="utf-8") as f:
        final_existing = [json.loads(line) for line in f if line.strip()]
        
    role_counts = Counter(r["primary_role"] for r in final_existing)
    
    print("\n========================================")
    print("POST-BATCH AUDIT")
    print("========================================")
    print(f"Batch: 61")
    print(f"Target role: {ROLE}")
    print(f"Attempted: {len(Q)}")
    print(f"Accepted: {len(accepted)}")
    print(f"Rejected: {len(rejected)}")
    print(f"Replacement count: 0")
    print(f"Cumulative total: {len(final_existing)}")
    print(f"{ROLE} total: {role_counts[ROLE]}")

if __name__ == "__main__":
    run_batch()
