"""Batch 6 question content (Database Developer). Antigravity-native, no Gemini API."""

ROLE = "Database Developer"

# bucket: (skill, technology, topic, category, applicable_roles)
BUCKETS = {
    "WIN": ("Advanced SQL", "SQL", "Window Functions", "Database", ["Data Analyst", "Backend Developer"]),
    "BTR": ("Indexing", "B-Tree Indexes", "B-Trees", "Database", ["Backend Developer", "Performance Engineer"]),
    "EXP": ("Query Optimization", "PostgreSQL", "Execution Plans", "Database", ["Backend Developer", "Performance Engineer"]),
    "ACD": ("Transactions", "Relational Databases", "ACID", "Database", ["Backend Developer"]),
    "NRM": ("Relational Theory", "Relational Model", "Normalization", "Database", ["Data Analyst", "Backend Developer"]),
}

# (bucket, intent, difficulty, qtype, secondary_skills, question, expected_answer, strong, weak)
Q = [
# ---------------- Window Functions ----------------
("WIN", "fundamentals", "easy", "concept", ["SQL Fundamentals"],
 "What separates a window function from a regular aggregate function like SUM() with GROUP BY?",
 "A GROUP BY aggregate collapses each group into a single output row. A window function computes its value over a set of related rows (the window) but keeps every input row in the result, so each row can show its own detail alongside the group-level calculation.",
 ["Rows are not collapsed", "Calculation over a window of related rows", "Detail and aggregate shown together"],
 ["Thinks window functions are just faster GROUP BY"]),
("WIN", "explain", "easy", "concept", [],
 "Inside an OVER() clause, what do PARTITION BY and ORDER BY each control?",
 "PARTITION BY splits the result set into independent groups so the function restarts for each partition. ORDER BY defines the row ordering within each partition, which determines ranking, running calculations and the default frame boundaries.",
 ["PARTITION BY defines independent groups", "ORDER BY defines ordering inside the partition", "Function restarts per partition"],
 ["Treats PARTITION BY as a filter"]),
("WIN", "fundamentals", "easy", "concept", [],
 "What does LAG() return for the first row in a partition, and how can you change that?",
 "There is no previous row, so LAG() returns NULL by default. A third argument sets a default value, for example LAG(amount, 1, 0) OVER (...), which returns 0 when no prior row exists.",
 ["Returns NULL by default", "Third argument is the default value", "Offset is the second argument"],
 ["Believes it errors out or wraps around to the last row"]),
("WIN", "implement", "medium", "implementation", ["Query Design"],
 "Show how you would return the three highest-paid employees in each department using a window function.",
 "Compute a rank per department in a subquery or CTE: ROW_NUMBER() (or DENSE_RANK() if ties should be kept) OVER (PARTITION BY department_id ORDER BY salary DESC) AS rn. Then filter WHERE rn <= 3 in the outer query, because window functions cannot be used directly in WHERE.",
 ["PARTITION BY department", "ORDER BY salary DESC", "Filter in outer query or CTE", "Chooses ROW_NUMBER vs DENSE_RANK deliberately"],
 ["Tries to put the window function in the WHERE clause"]),
("WIN", "compare", "medium", "comparison", [],
 "How do ROW_NUMBER, RANK and DENSE_RANK behave differently when two rows tie on the ordering column?",
 "ROW_NUMBER assigns unique sequential numbers and breaks ties arbitrarily. RANK gives tied rows the same rank and then skips numbers (1,1,3). DENSE_RANK gives tied rows the same rank without gaps (1,1,2).",
 ["ROW_NUMBER is always unique", "RANK leaves gaps after ties", "DENSE_RANK has no gaps"],
 ["Believes all three return identical results"]),
("WIN", "implement", "medium", "implementation", ["Query Design"],
 "How would you compute a 7-day moving average of daily sales with a window function?",
 "Aggregate to one row per day, then use AVG(sales) OVER (ORDER BY day ROWS BETWEEN 6 PRECEDING AND CURRENT ROW). ROWS counts physical rows, so days with no sales must be present (via a calendar join) for the window to represent seven calendar days; otherwise use a RANGE frame on a date interval where supported.",
 ["Explicit ROWS frame with 6 PRECEDING", "Aware of missing days", "One row per day beforehand"],
 ["Uses AVG OVER without a frame and assumes it is a moving average"]),
("WIN", "tradeoff", "medium", "tradeoff", ["Performance"],
 "To fetch the latest order per customer, would you rely on a window function or a correlated subquery, and why?",
 "ROW_NUMBER() OVER (PARTITION BY customer_id ORDER BY created_at DESC) with rn = 1 scans and sorts the data once, which usually scales better on large tables. A correlated subquery with MAX(created_at) can be fast when a (customer_id, created_at) index supports per-customer lookups, especially for few customers. PostgreSQL's DISTINCT ON is another concise option. The choice depends on indexes and data volume.",
 ["Single pass with window function", "Correlated subquery benefits from composite index", "Mentions measuring with the plan"],
 ["Declares one approach always faster"]),
("WIN", "optimize", "medium", "optimization", ["Performance"],
 "A report uses six window functions with different OVER definitions and is slow. How would you reduce the sorting cost?",
 "Each distinct window definition (partition and order combination) typically needs its own sort. Rewrite the functions to share identical PARTITION BY/ORDER BY definitions, factor them into a named WINDOW clause, and move calculations that need different orderings into separate steps. An index matching the partition and order columns can also avoid the sort.",
 ["Distinct window definitions require separate sorts", "Share a window specification or WINDOW clause", "Supporting index to avoid sort"],
 ["Suggests adding LIMIT without addressing the sorts"]),
("WIN", "diagnose", "hard", "debugging", ["Debugging"],
 "LAST_VALUE(price) OVER (PARTITION BY product ORDER BY day) keeps returning the current row's price instead of the final one. What is going on and how do you fix it?",
 "When ORDER BY is present, the default frame is RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW, so the last row of the frame is the current row. Fix it by specifying ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING, or use FIRST_VALUE with a reversed ORDER BY.",
 ["Identifies default frame ending at CURRENT ROW", "Specifies explicit UNBOUNDED FOLLOWING frame", "Alternative via FIRST_VALUE with reverse order"],
 ["Blames NULL values or data issues"]),
("WIN", "scenario", "hard", "scenario", ["Query Design"],
 "A login table records one row per user per active day. How would you find each user's consecutive-day streaks using only SQL?",
 "Use the gaps-and-islands technique: number each user's rows with ROW_NUMBER() OVER (PARTITION BY user_id ORDER BY day) and subtract it (as days) from the date. Consecutive days produce the same constant, so grouping by user_id and that constant yields islands, and MIN/MAX/COUNT per group give streak start, end and length.",
 ["Gaps-and-islands pattern", "Date minus row number yields constant per streak", "Group by that constant to get streak length"],
 ["Proposes a procedural loop over rows"]),

# ---------------- B-Trees ----------------
("BTR", "fundamentals", "easy", "concept", [],
 "Why do most relational databases default to B-Tree indexes?",
 "A B-Tree is a balanced, sorted, high-fanout tree, so lookups, inserts and deletes all take logarithmic time with very few page reads. Because keys are kept in order, it supports equality, range scans, ORDER BY and prefix matching, which covers most query patterns.",
 ["Balanced and sorted", "Logarithmic lookup with high fanout", "Supports range and equality"],
 ["Thinks it is a binary tree stored in memory"]),
("BTR", "explain", "easy", "concept", [],
 "What does the leftmost-prefix rule mean for a composite index on (country, city, zip)?",
 "The index is sorted by country, then city within country, then zip. It can efficiently serve predicates on country, country+city, or all three, but a query filtering only on city or zip cannot use the ordering effectively and usually cannot seek into it.",
 ["Sorted by columns in order", "Works for leading prefixes", "Filtering on later column alone is not efficient"],
 ["Believes column order in a composite index is irrelevant"]),
("BTR", "explain", "easy", "concept", [],
 "Why can a B-Tree index answer WHERE price BETWEEN 10 AND 50 but a hash index cannot?",
 "A B-Tree stores keys in sorted order and its leaf pages are linked, so the engine seeks to 10 and scans sequentially to 50. A hash index scatters keys by hash value, which destroys ordering, so it can only answer exact equality.",
 ["Sorted keys", "Linked leaf pages enable range scan", "Hash loses ordering"],
 ["Says hash indexes are just slower for ranges"]),
("BTR", "debug", "medium", "debugging", ["Debugging"],
 "An index exists on users(email), yet WHERE LOWER(email) = 'a@b.com' does a sequential scan. Why, and what is the fix?",
 "The index stores the raw email values, so applying LOWER() to the column makes the predicate non-sargable and the planner cannot seek on the index. Create a functional (expression) index on LOWER(email), or store emails normalized and compare directly, or use a case-insensitive collation or type.",
 ["Function on column defeats index", "Expression index on LOWER(email)", "Or normalize stored data"],
 ["Suggests adding a second plain index on email"]),
("BTR", "tradeoff", "medium", "tradeoff", ["Performance"],
 "What is the write-side cost of adding another B-Tree index to a busy table?",
 "Every insert, delete and any update touching indexed columns must also modify each index, which adds I/O, WAL volume and lock contention. Leaf page splits and extra storage and cache pressure follow. Reads improve only if queries actually use the index, so unused indexes should be dropped.",
 ["Each index updated on writes", "Page splits and extra WAL", "Storage and cache cost", "Drop unused indexes"],
 ["Claims indexes only cost disk space"]),
("BTR", "compare", "medium", "comparison", [],
 "How do clustered and secondary B-Tree indexes differ, for example in InnoDB?",
 "In InnoDB the table is stored as the clustered index on the primary key, with full rows in its leaf pages. A secondary index leaf holds the indexed columns plus the primary key, so a lookup traverses the secondary index and then the clustered index to fetch the row, which is why long primary keys inflate every secondary index.",
 ["Rows live in clustered index leaves", "Secondary leaves store the primary key", "Double lookup", "Long PK inflates secondary indexes"],
 ["Thinks both store physical row pointers identically"]),
("BTR", "implement", "medium", "implementation", ["Query Design"],
 "For WHERE status = 'open' AND created_at >= ? ORDER BY created_at, how would you design a composite index and why that column order?",
 "Index (status, created_at). The equality column goes first so the tree narrows to one status, and within it entries are already sorted by created_at, serving both the range filter and the ORDER BY without a separate sort. Reversing the order would break the sort benefit.",
 ["Equality column first", "Range/order column second", "Avoids a separate sort step"],
 ["Puts the range column first"]),
("BTR", "scenario", "hard", "scenario", ["Performance"],
 "A MySQL InnoDB table uses random UUIDv4 primary keys, and insert throughput drops as it grows beyond memory. What is happening and what would you change?",
 "Random keys insert into arbitrary leaf pages across the clustered index, causing frequent page splits, fragmentation and constant buffer pool misses as cold pages are loaded. Use time-ordered keys (auto-increment, UUIDv7 or ULID, or an ordered binary UUID) so inserts append to the rightmost pages, and keep secondary indexes small.",
 ["Random inserts cause page splits and fragmentation", "Buffer pool misses", "Time-ordered or sequential keys"],
 ["Blames the UUID length only"]),
("BTR", "diagnose", "hard", "debugging", ["Debugging"],
 "An index on is_active (95% of rows true) is ignored by the planner for WHERE is_active = true. Is the planner wrong, and what would help?",
 "No. The predicate is not selective, so a sequential scan is cheaper than many random heap fetches through the index. Indexes help for the rare value: use a partial index such as WHERE is_active = false, or combine the column with a selective one in a composite index.",
 ["Low selectivity makes seq scan cheaper", "Partial index for the rare value", "Composite with selective column"],
 ["Forces the index with hints as the primary answer"]),
("BTR", "optimize", "hard", "optimization", ["Maintenance"],
 "An update-heavy table's B-Tree indexes keep growing and queries slow down over time. How would you investigate and manage index bloat?",
 "Dead tuples and half-empty pages accumulate because of MVCC and page splits. Measure with pgstattuple or bloat estimation queries, make sure autovacuum keeps up, lower fillfactor on hot tables to enable HOT updates, avoid indexing frequently updated columns, and rebuild with REINDEX CONCURRENTLY (or pg_repack) when bloat is significant.",
 ["Measures bloat", "Autovacuum tuning", "Fillfactor and HOT updates", "Online reindex"],
 ["Only suggests dropping and recreating indexes during peak"]),

# ---------------- Execution Plans ----------------
("EXP", "fundamentals", "easy", "concept", [],
 "What is a query execution plan and who produces it?",
 "It is the step-by-step strategy for running a SQL statement: scan methods, join algorithms and order, and sort or aggregate steps. The query optimizer generates it by estimating the cost of alternatives using table statistics and picking the cheapest.",
 ["Tree of operations", "Produced by the cost-based optimizer", "Uses statistics"],
 ["Thinks the developer defines the plan in SQL text"]),
("EXP", "explain", "easy", "concept", [],
 "Why must you be careful using EXPLAIN ANALYZE on an UPDATE or DELETE?",
 "EXPLAIN only shows the estimated plan, but EXPLAIN ANALYZE actually executes the statement, so the data changes happen. Wrap it in a transaction and roll back, or test on a copy.",
 ["ANALYZE executes the statement", "Use BEGIN/ROLLBACK", "Plain EXPLAIN does not run it"],
 ["Assumes both only simulate"]),
("EXP", "explain", "easy", "concept", [],
 "When reading a plan, what is the practical difference between a Seq Scan and an Index Scan node?",
 "A Seq Scan reads the whole table in physical order and filters rows, which is efficient when most rows are needed. An Index Scan uses an index to jump to matching rows, which wins when the predicate is selective.",
 ["Seq scan reads everything", "Index scan seeks to matches", "Depends on selectivity"],
 ["Says Seq Scan always indicates a problem"]),
("EXP", "compare", "medium", "comparison", [],
 "When does the optimizer choose a nested loop, hash join or merge join?",
 "Nested loop suits a small outer input with an indexed inner lookup. Hash join builds a hash table on the smaller input and works well for large unsorted equality joins. Merge join needs both inputs sorted (or index-ordered) and shines for large sorted inputs or range-friendly joins.",
 ["Nested loop with index for small outer", "Hash for large equality joins", "Merge for sorted inputs"],
 ["Believes join type is determined by SQL join keyword"]),
("EXP", "explain", "medium", "concept", ["Statistics"],
 "In EXPLAIN ANALYZE output, estimated rows are 10 but actual rows are 200,000. What does that tell you?",
 "The optimizer's cardinality estimate is badly off, usually from stale or missing statistics, skewed data or correlated columns, so downstream choices such as join type and order may be poor. Run ANALYZE, raise the statistics target, or create extended statistics.",
 ["Cardinality misestimate", "Stale or insufficient statistics", "Run ANALYZE or extended statistics"],
 ["Says the query is simply slow"]),
("EXP", "diagnose", "medium", "debugging", ["Debugging"],
 "A plan shows a Sort node with 'Sort Method: external merge Disk'. What does it mean and how do you respond?",
 "The sort did not fit in work_mem and spilled to temporary disk files, which is much slower. Raise work_mem for the session or query, reduce the rows being sorted, or provide an index that returns rows already ordered.",
 ["Spill to disk due to work_mem", "Increase work_mem carefully", "Index to avoid sort"],
 ["Suggests more CPU"]),
("EXP", "optimize", "medium", "optimization", ["Query Design"],
 "A paginated endpoint using LIMIT 20 OFFSET 200000 gets slower on deeper pages. How would you fix it?",
 "OFFSET forces the database to read and discard all skipped rows. Use keyset (seek) pagination: remember the last seen sort key and query WHERE (created_at, id) < (?, ?) ORDER BY created_at DESC, id DESC LIMIT 20, backed by a matching index.",
 ["OFFSET scans and discards rows", "Keyset pagination", "Index on sort keys with tiebreaker"],
 ["Only suggests caching pages"]),
("EXP", "compare", "medium", "comparison", ["Query Design"],
 "Between IN (subquery), EXISTS and a JOIN, how do you decide which form to write and what do you check in the plan?",
 "Modern optimizers often turn IN and EXISTS into semi-joins that stop at the first match, while a plain JOIN can multiply rows if the right side has duplicates, requiring DISTINCT. EXISTS is clear for existence checks, and NOT EXISTS is safer than NOT IN with NULLs. Verify in the plan that a semi-join or anti-join was used and compare the timings.",
 ["Semi-join semantics", "JOIN can duplicate rows", "NOT IN NULL pitfall", "Confirm via plan"],
 ["Claims one form is always fastest"]),
("EXP", "diagnose", "hard", "debugging", ["Statistics"],
 "A nested loop was chosen because the planner estimated 1 row for WHERE city = 'X' AND zip = 'Y', but 500,000 rows came back. What is the root cause and fix?",
 "The planner assumes predicates are independent and multiplies selectivities, but city and zip are strongly correlated, so it underestimates. Create extended statistics (CREATE STATISTICS ... (dependencies) ON city, zip), run ANALYZE, and recheck that the planner switches to a hash or merge join.",
 ["Independence assumption", "Correlated columns", "Extended statistics", "Re-ANALYZE and verify"],
 ["Disables nested loops globally as the main fix"]),
("EXP", "tradeoff", "hard", "tradeoff", ["Performance"],
 "Prepared statements sometimes run far slower after the fifth execution in PostgreSQL. How do generic and custom plans explain that, and what are the trade-offs?",
 "PostgreSQL plans with actual parameter values for the first five executions, then may switch to a cached generic plan if its estimated cost is not much worse. With skewed data the generic plan can be bad for particular values. Options are plan_cache_mode = force_custom_plan, query restructuring, or per-value statistics. Custom plans cost planning time on every call, generic plans save it.",
 ["Custom versus generic plan", "Skewed parameter values", "plan_cache_mode setting", "Planning time trade-off"],
 ["Thinks prepared statements are always faster"]),

# ---------------- ACID ----------------
("ACD", "fundamentals", "easy", "concept", [],
 "Can you define atomicity, consistency, isolation and durability with one practical example each?",
 "Atomicity: a transfer debits and credits both accounts or neither. Consistency: constraints such as non-negative balance hold before and after. Isolation: concurrent transfers behave as if run in some serial order, to the degree of the isolation level. Durability: once committed, the transfer survives a crash.",
 ["All four defined correctly", "Concrete example", "Isolation is level dependent"],
 ["Equates consistency with CAP-style consistency"]),
("ACD", "explain", "easy", "concept", [],
 "How does a write-ahead log let a database be durable without writing every data page at commit?",
 "At commit the database flushes the sequential log record describing the change to stable storage, which is cheap. Data pages can be written lazily later. After a crash, recovery replays the log to redo committed changes and undo uncommitted ones.",
 ["Log flushed before commit returns", "Data pages written lazily", "Recovery replays the log"],
 ["Says data files are fsynced on every commit"]),
("ACD", "explain", "easy", "concept", [],
 "What is the difference between a dirty read, a non-repeatable read and a phantom read?",
 "A dirty read sees uncommitted data from another transaction. A non-repeatable read gets different values when re-reading the same row because another transaction committed an update. A phantom read gets a different set of rows when re-running a range query because another transaction inserted or deleted matching rows.",
 ["Dirty is uncommitted data", "Non-repeatable is changed row", "Phantom is changed set"],
 ["Mixes up phantom and non-repeatable"]),
("ACD", "compare", "medium", "comparison", [],
 "How does PostgreSQL's REPEATABLE READ differ from READ COMMITTED in practice?",
 "READ COMMITTED takes a new snapshot for every statement, so later statements can see data committed meanwhile. REPEATABLE READ uses one snapshot for the whole transaction, giving stable reads, and aborts with a serialization failure if you try to update a row changed after the snapshot, so the application must retry.",
 ["Per-statement versus per-transaction snapshot", "Serialization failure on conflicting update", "Retry logic"],
 ["Says REPEATABLE READ blocks other writers"]),
("ACD", "scenario", "medium", "scenario", ["Concurrency"],
 "Two requests withdraw from the same account at the same moment, and the balance ends up wrong. How do you prevent this lost update?",
 "Both read the old balance and write back a stale value. Fix it with SELECT ... FOR UPDATE to lock the row before reading, or an atomic UPDATE accounts SET balance = balance - ? WHERE id = ? AND balance >= ?, or optimistic concurrency with a version column and retry.",
 ["Identifies read-modify-write race", "Row lock or atomic update", "Optimistic version check alternative"],
 ["Relies on application-level mutex only"]),
("ACD", "explain", "medium", "concept", [],
 "How does MVCC let readers avoid blocking writers?",
 "Each write creates a new row version with transaction metadata. Readers use a snapshot to see only versions committed before it started, so they never need read locks. Writers only conflict with other writers on the same row. Old versions must later be cleaned up by vacuum or purge.",
 ["Multiple row versions", "Snapshot visibility", "Writers conflict only with writers", "Garbage collection of old versions"],
 ["Says readers take shared locks on all rows"]),
("ACD", "diagnose", "medium", "debugging", ["Debugging"],
 "Your logs show 'deadlock detected' between two transactions updating the same two rows. How do you resolve it?",
 "Transaction A locks row 1 then wants row 2 while B locks row 2 then wants row 1. The database aborts one as the victim. Fix by acquiring locks in a consistent order, keeping transactions short, locking up front with SELECT FOR UPDATE ordered by key, and retrying the victim.",
 ["Circular wait explained", "Consistent lock ordering", "Short transactions", "Retry"],
 ["Only increases the lock timeout"]),
("ACD", "tradeoff", "hard", "tradeoff", ["Concurrency"],
 "When would you choose optimistic locking over pessimistic locking for a high-traffic edit workflow?",
 "Optimistic locking uses a version or timestamp check at update time and retries on conflict, avoiding held locks and scaling well when conflicts are rare, such as edits to a document. Pessimistic locking holds row locks and suits high contention or when retries are costly, at the price of blocking, deadlock risk and reduced throughput.",
 ["Version check and retry", "Low contention favors optimistic", "High contention or costly retry favors pessimistic", "Blocking and deadlock cost"],
 ["Says pessimistic is always safer so always use it"]),
("ACD", "scenario", "hard", "scenario", ["Concurrency"],
 "Two on-call doctors each check that at least one other doctor is on call, then both go off call, leaving none. Which anomaly is this and how do you prevent it?",
 "This is write skew: each transaction reads overlapping data but writes different rows, so snapshot isolation allows both to commit. Prevent it with SERIALIZABLE isolation (such as PostgreSQL SSI, handling serialization failures with retries), explicit locking of the rows read, or a constraint that enforces the invariant.",
 ["Names write skew", "Snapshot isolation allows it", "SERIALIZABLE with retries or explicit locks"],
 ["Says REPEATABLE READ always prevents it"]),
("ACD", "architecture", "hard", "architecture", ["Maintenance"],
 "A reporting session sits 'idle in transaction' for hours and the database starts bloating. Why does that happen and how would you guard against it?",
 "An open transaction keeps its snapshot, so vacuum cannot remove dead row versions newer than that snapshot's horizon, causing bloat and possibly blocking DDL. Set idle_in_transaction_session_timeout and statement_timeout, fix applications that begin transactions without committing, and route long reports to a replica.",
 ["Old snapshot holds back vacuum", "Timeouts for idle transactions", "Move reports to a replica"],
 ["Blames autovacuum being broken"]),

# ---------------- Normalization ----------------
("NRM", "fundamentals", "easy", "concept", [],
 "Which insert, update and delete anomalies does an unnormalized table expose you to?",
 "Redundant data lets an update change one copy but miss others (update anomaly), forces you to invent unrelated data to record a fact (insert anomaly), and may erase unrelated facts when deleting a row (delete anomaly). Normalization removes these by storing each fact once.",
 ["Update anomaly", "Insert anomaly", "Delete anomaly", "Each fact stored once"],
 ["Describes only storage savings"]),
("NRM", "explain", "easy", "concept", [],
 "Why does a column holding comma-separated phone numbers violate first normal form, and how do you restructure it?",
 "1NF requires atomic values, so each column holds a single value and rows are uniquely identifiable. A list in one cell makes searching and constraints awkward. Create a child table, such as customer_phone(customer_id, phone), with one row per number.",
 ["Atomic values required", "Child table for repeating values"],
 ["Suggests adding phone1, phone2, phone3 columns"]),
("NRM", "fundamentals", "easy", "concept", [],
 "What is a functional dependency, and how does it relate to choosing keys?",
 "X determines Y if each X value is associated with exactly one Y value. A candidate key is a minimal set of attributes that functionally determines all other attributes. Normal forms are defined by which dependencies exist on keys.",
 ["Definition of X determines Y", "Candidate key determines all attributes", "Normal forms rely on dependencies"],
 ["Confuses it with a foreign key relation"]),
("NRM", "compare", "medium", "comparison", [],
 "Using an order_items table keyed on (order_id, product_id), how would you show the difference between 2NF and 3NF violations?",
 "A 2NF violation is a partial dependency: product_name depends only on product_id, part of the composite key, so move it to a product table. A 3NF violation is a transitive dependency: a non-key attribute determines another, such as customer_zip determining customer_city, so move that dependency into its own table.",
 ["Partial dependency for 2NF", "Transitive dependency for 3NF", "Concrete decomposition"],
 ["Says 3NF only concerns composite keys"]),
("NRM", "compare", "medium", "comparison", [],
 "How is BCNF stricter than 3NF, and when does the difference matter?",
 "3NF allows a dependency X->Y if Y is a prime attribute, while BCNF demands every determinant be a superkey. The difference appears with overlapping candidate keys, for example (student, subject)->teacher with teacher->subject. BCNF decomposition may lose dependency preservation.",
 ["Every determinant a superkey", "Overlapping candidate keys", "May not preserve dependencies"],
 ["Says they are the same"]),
("NRM", "scenario", "medium", "scenario", ["Data Modeling"],
 "Why would you store unit_price in order_items even though the price already exists in the products table?",
 "The price on an order is a historical fact that must not change when the catalog price changes. Copying the price at purchase time is intentional, controlled redundancy that preserves order history, rather than a normalization failure.",
 ["Historical snapshot", "Catalog price changes must not alter old orders", "Deliberate redundancy"],
 ["Calls it always bad design"]),
("NRM", "tradeoff", "medium", "tradeoff", ["Performance"],
 "For a read-heavy analytics dashboard, when is denormalizing a normalized schema justified?",
 "Normalization optimizes write integrity; heavy reads over many joins can be slow. Denormalize via summary tables, materialized views or star schemas when measured joins are the bottleneck, and accept extra storage and the burden of keeping copies consistent (refresh jobs, triggers). Keep the normalized source of truth.",
 ["Joins as measured bottleneck", "Materialized views or star schema", "Consistency maintenance cost", "Keep normalized source"],
 ["Denormalizes everything by default"]),
("NRM", "implement", "medium", "implementation", ["Data Modeling"],
 "How would you model students enrolling in courses, including the grade, in a relational schema?",
 "Many-to-many needs a junction table enrollment(student_id, course_id, grade, enrolled_at) with a composite primary key (student_id, course_id) and foreign keys to both tables. The grade depends on the whole key, so it lives in the junction table, not in student or course.",
 ["Junction table", "Composite primary key", "Attributes of relationship placed in junction table"],
 ["Stores course ids in a column on student"]),
("NRM", "architecture", "hard", "architecture", ["Data Modeling"],
 "An employee table has independent multi-valued facts: skills and spoken languages in one table, producing row explosion. Which normal form is violated and how do you fix it?",
 "This is a multivalued dependency violating 4NF: employee ->> skill and employee ->> language independent of each other, so every combination must be stored. Decompose into employee_skill(employee_id, skill) and employee_language(employee_id, language).",
 ["Names multivalued dependency and 4NF", "Independent facts cause combinations", "Separate tables per fact"],
 ["Says 3NF already solves it"]),
("NRM", "explain", "hard", "concept", ["Data Modeling"],
 "What does it mean for a decomposition to be lossless-join and dependency-preserving, and why can you not always have both with BCNF?",
 "Lossless-join means rejoining the decomposed tables reproduces the original rows exactly, with no spurious tuples, typically guaranteed when the shared attributes form a key of one part. Dependency-preserving means every dependency can be enforced within a single table. BCNF decomposition always yields a lossless join, but certain schemas (overlapping keys) have dependencies that span tables, so BCNF may sacrifice preservation while 3NF can guarantee both.",
 ["Lossless join definition", "Dependency preservation definition", "BCNF always lossless but may lose dependencies", "3NF can achieve both"],
 ["Thinks lossless means no data deleted"]),
]
