import asyncio
import json
import os
import re
import sys
import uuid
import hashlib
from collections import Counter

from dotenv import load_dotenv
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
load_dotenv()

BACKEND_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_DIR = os.path.join(BACKEND_DIR, "data")
OUT = os.path.join(DATA_DIR, "interview_question_bank_v2_generated.jsonl")

ROLE = "Database Developer"
LEAK = re.compile(r"(generate a question|generate \d+ questions|return only json|phase 4c gap plan|"
                  r"generation batch|candidate generation|system prompts|do not proceed|"
                  r"awaiting authorization|minimum target|generation pipeline|"
                  r"batch \d+ generation|expected answer|strong indicator|weak indicator|as an ai|"
                  r"here is the question|\bprompt text\b)", re.I)

Q = [
    # Area 1: MVCC, Vacuuming, Postgres Internals
    ("B56_1", "concept", "medium", "concept", ["Database Internals"], "Explain Multi-Version Concurrency Control (MVCC) and why it causes table 'bloat' in PostgreSQL.", "MVCC allows concurrent reads and writes by keeping multiple versions of a row rather than overwriting it in place. When a row is updated or deleted in PostgreSQL, the old version (tuple) remains on disk so that running transactions can still read the previous state (Snapshot Isolation). Once no active transactions need the old version, it becomes 'dead'. If these dead tuples are not periodically cleaned up (Vacuumed), they permanently consume disk space and slow down sequential scans, leading to table bloat.", ["Keeps multiple versions of a row to allow lock-free concurrent reads", "Updates/Deletes do not overwrite data; they create new tuples and leave old ones as 'dead'", "Dead tuples cause table bloat if not cleaned by Vacuum"], ["MVCC makes the database multi-threaded"]),
    ("B56_1", "diagnose", "hard", "debugging", ["Database Operations"], "You notice severe table bloat on a highly updated PostgreSQL table, even though `autovacuum` is running. Investigation shows that the 'dead tuples' are not being removed by the vacuum process. What is likely preventing the cleanup?", "A long-running transaction or a stale replication slot is preventing the cleanup. Vacuum can only remove dead tuples that are older than the oldest currently running transaction across the entire database. If a developer left an idle transaction open for 3 days, or if an analytics query is taking 24 hours, autovacuum cannot delete *any* dead tuples created during that time, because that old transaction might theoretically still need to read them.", ["Vacuum only deletes tuples older than the oldest active transaction", "A long-running query or idle transaction blocks dead tuple cleanup", "Orphaned or lagging replication slots can also prevent cleanup"], ["Vacuum only runs at midnight"]),
    ("B56_1", "architecture", "hard", "architecture", ["PostgreSQL"], "What is a Heap-Only Tuple (HOT) update in PostgreSQL, and how does it significantly improve update performance?", "Normally, updating a row in PostgreSQL requires updating all indexes on that table to point to the new physical location of the row. A HOT update occurs when an update does NOT modify any indexed columns, and there is sufficient free space on the exact same disk page. In this case, Postgres places the new version on the same page and creates a local pointer, completely bypassing the need to rewrite the indexes. This drastically reduces I/O and Write-Ahead Log (WAL) volume.", ["Occurs when an update does not touch any indexed columns", "Requires free space (fillfactor < 100) on the same disk page", "Avoids updating all table indexes, drastically reducing I/O and WAL overhead"], ["It updates the row in CPU cache instead of disk"]),
    ("B56_1", "tradeoff", "medium", "tradeoff", ["Database Architecture"], "What is the tradeoff of using a statement-level connection pooler (like PgBouncer in transaction mode) versus maintaining direct application connections to PostgreSQL?", "PostgreSQL forks a heavy OS process for every direct connection, consuming significant RAM (~10MB+ per connection) and CPU for context switching. PgBouncer sits between the app and the DB, maintaining a small pool of actual DB connections while accepting thousands of lightweight client connections. In 'transaction mode', it assigns a DB connection only for the duration of a transaction, then returns it to the pool. The tradeoff is that transaction mode breaks session-level state, such as prepared statements, temporary tables, and session variables (`SET LOCAL`), requiring application-side adjustments.", ["PostgreSQL consumes heavy RAM/CPU per direct connection", "PgBouncer multiplexes thousands of lightweight connections onto a few real DB connections", "Tradeoff: Transaction mode breaks session state (prepared statements, temp tables)"], ["PgBouncer stores the data in memory for faster reads"]),
    ("B56_1", "explain", "medium", "explain", ["Database Internals"], "Why is the Write-Ahead Log (WAL) critical for both durability (ACID) and replication in modern relational databases?", "To ensure high performance, databases write modifications to memory (Buffer Pool) rather than immediately flushing data files to disk. To guarantee Durability (the 'D' in ACID), they append a sequential log of the changes to the WAL on disk before acknowledging the commit. If the server crashes, the database replays the WAL on restart to recover the in-memory changes. Additionally, this exact same sequential stream of changes is shipped to standby servers (Streaming Replication) to keep replicas synchronized with the primary.", ["Ensures durability without the latency of flushing heavy data files on every commit", "Changes are sequentially appended to the WAL before commit acknowledgement", "Replication reads the WAL stream to synchronize standby nodes"], ["WAL prevents SQL injection attacks"]),
    ("B56_1", "scenario", "medium", "scenario", ["Database Operations"], "You are bulk inserting 50 million rows into a Postgres table. The insert is incredibly slow, and disk I/O is maxed out. The table has 5 B-Tree indexes. How do you optimize this bulk load?", "Writing to a table with indexes forces the database to synchronously update all 5 B-Trees for every single row, causing massive random I/O and page splits. The standard optimization for bulk loading is to drop (or disable) all non-primary-key indexes, load the 50 million rows using `COPY` (rather than standard `INSERT`), and then recreate the indexes afterward. Building an index from scratch on populated data uses fast, sequential sort operations, which is exponentially faster than 50 million incremental random tree updates.", ["Drop or disable indexes before the bulk load", "Use the `COPY` command instead of single `INSERT`s", "Recreate indexes afterward, which utilizes fast sequential sorting"], ["Compress the data in Python first"]),
    ("B56_1", "implement", "hard", "implement", ["Database Architecture"], "How do you implement a 'covering index' (Index-Only Scan), and what specific table condition must be met for PostgreSQL to completely avoid reading the heap?", "A covering index `INCLUDE`s non-key columns in the leaf nodes of the B-Tree (e.g., `CREATE INDEX idx ON users(id) INCLUDE (email)`). This allows queries selecting the `email` to satisfy the request purely from the index structure. However, because indexes do not store MVCC visibility information, PostgreSQL must still check the main table (the heap) to see if the row is visible to the current transaction, defeating the purpose. To achieve a true Index-Only Scan, the table's Visibility Map must indicate that the page containing the row is 'all-visible' (recently vacuumed).", ["Create an index using the `INCLUDE` clause to store extra payload columns", "Allows the query planner to satisfy the query entirely from the index structure", "Requires the Visibility Map to mark the page as 'all-visible' to avoid heap lookups"], ["You must wrap the index in a JSON wrapper"]),
    ("B56_1", "diagnose", "medium", "debugging", ["Database Operations"], "A Postgres database experiences sudden, severe performance degradation at the exact same time every day for 15 minutes. The CPU hits 100% and disk I/O spikes. What is the most likely maintenance task causing this, and how can it be tuned?", "This is almost certainly a heavy `CHECKPOINT` occurring. A checkpoint forces the database to flush all dirty buffers (modified memory pages) to the physical disk files, freeing up space in the WAL. If checkpoints are configured to happen too infrequently or flush too aggressively, it causes a massive I/O spike. This is tuned by increasing `checkpoint_timeout` or `max_wal_size`, and crucially, by configuring `checkpoint_completion_target` to a high value (like 0.9) to spread the disk writes slowly over the entire timeout period rather than bursting.", ["Caused by a massive `CHECKPOINT` flushing all dirty memory pages to disk", "Creates severe I/O spikes and CPU load", "Tune by increasing `checkpoint_completion_target` to spread writes over time"], ["The database is downloading a software update"]),
    ("B56_1", "concept", "easy", "concept", ["Database Architecture"], "What is the purpose of the 'Buffer Pool' (or Shared Buffers) in a relational database?", "The Buffer Pool is an area of main memory (RAM) allocated by the database to cache frequently accessed disk pages (both data and indexes). Reading from disk is slow; the buffer pool ensures that subsequent reads of the same data are served at microsecond speeds from RAM. Writes are also performed directly in the buffer pool (marking the page as 'dirty') and are asynchronously flushed to disk later, vastly improving performance.", ["Caches frequently accessed data and index pages in RAM", "Serves read requests at microsecond speeds instead of hitting the disk", "Absorbs write operations (dirty pages) to be flushed to disk asynchronously"], ["It buffers network requests from the frontend"]),
    ("B56_1", "tradeoff", "hard", "tradeoff", ["Database Architecture"], "What is the tradeoff of setting PostgreSQL's `synchronous_commit = off`?", "By default (`on`), PostgreSQL will not report a transaction as 'committed' to the client until the WAL record is physically flushed to the disk. Setting it to `off` allows the database to report success immediately after writing to memory, drastically improving transaction throughput and reducing latency. The severe tradeoff is a small window of data loss: if the server crashes before the OS flushes the memory to disk (usually within 3x `wal_writer_delay`, roughly 600ms), recently 'committed' transactions will be permanently lost. However, database consistency is preserved.", ["Improves transaction throughput and latency by avoiding synchronous disk flushes", "Tradeoff: A crash will result in the loss of recently committed transactions (e.g., last ~600ms)", "Maintains database integrity (no corruption), but sacrifices strict durability"], ["It disables foreign key constraints for speed"]),

    # Area 2: Isolation Anomalies: Phantom Reads, Write Skew, Serializable
    ("B56_2", "concept", "medium", "concept", ["Transactions"], "Define a 'Phantom Read' anomaly and state which isolation level strictly prevents it.", "A Phantom Read occurs when a transaction executes a range query (e.g., `SELECT * FROM users WHERE age > 20`) twice during the same transaction. Between the two reads, a second concurrent transaction INSERTs or DELETEs a row that matches the condition. The first transaction sees a different number of rows (a 'phantom' row) on the second execution. It is prevented by the `SERIALIZABLE` isolation level (and in PostgreSQL, practically prevented by `REPEATABLE READ` due to its MVCC snapshot implementation).", ["Transaction runs a range query twice and sees a different number of rows", "Caused by concurrent INSERTS/DELETES matching the range condition", "Prevented by `SERIALIZABLE` isolation (or Next-Key Locks)"], ["A phantom read is when data is read from a deleted table"]),
    ("B56_2", "diagnose", "hard", "debugging", ["Transactions"], "Two doctors are using a scheduling app backed by a database using `REPEATABLE READ` isolation. The rule is 'a shift must have at least 1 doctor on call'. Currently, Alice and Bob are on call. Alice concurrently runs a transaction to remove herself. Bob concurrently runs a transaction to remove himself. Both transactions see 2 doctors on call, so both commit successfully, leaving 0 doctors on call. What is this anomaly called?", "This is a classic 'Write Skew' anomaly. It occurs when two concurrent transactions read overlapping data sets, make decisions based on that data, and then write to *different* rows. Because they write to different rows, no standard row-level lock conflict occurs. Standard `REPEATABLE READ` or Snapshot Isolation cannot detect this. To prevent Write Skew, you must use `SERIALIZABLE` isolation, or explicitly use pessimistic locking (`SELECT ... FOR UPDATE`) on a parent constraint row.", ["This is the 'Write Skew' anomaly", "Concurrent transactions read overlapping data but write to different rows", "Requires `SERIALIZABLE` isolation or explicit pessimistic locking (`SELECT FOR UPDATE`)"], ["This is a deadlock anomaly"]),
    ("B56_2", "architecture", "hard", "architecture", ["Transactions"], "How does PostgreSQL implement the `SERIALIZABLE` isolation level without relying entirely on heavy, blocking table locks?", "Instead of using Strict Two-Phase Locking (2PL) which destroys concurrency, PostgreSQL uses Serializable Snapshot Isolation (SSI). It monitors transactions for dangerous read-write dependencies (specifically, a cycle of 'rw-conflicts' where transaction A reads data that transaction B modifies, and vice versa). If SSI detects a cycle that could lead to an anomaly (like Write Skew), it aborts one of the transactions with a serialization failure error (`40001`), forcing the application to retry. This allows lock-free reads while guaranteeing strict serializability.", ["Uses Serializable Snapshot Isolation (SSI) rather than Strict 2PL", "Monitors concurrent transactions for dangerous read-write dependency cycles", "Aborts one transaction if a cycle is detected, forcing an application retry"], ["It uses a single global mutex to run transactions one by one"]),
    ("B56_2", "implement", "medium", "implement", ["Transactions"], "How do you implement pessimistic row-level locking to prevent a race condition when decrementing inventory in a highly concurrent e-commerce checkout?", "You must use the `SELECT ... FOR UPDATE` clause inside an explicit transaction. When user A attempts to buy an item, the query `SELECT quantity FROM inventory WHERE id = 1 FOR UPDATE` strictly locks that specific row. If User B concurrently attempts to buy the same item, their `SELECT FOR UPDATE` query will block and wait until User A commits or rolls back. Once A commits, B reads the *new*, decremented quantity, preventing overselling.", ["Use `SELECT ... FOR UPDATE` within an explicit transaction", "Places an exclusive lock on the specific row(s)", "Forces concurrent transactions to wait and read the freshly updated state"], ["Use an `UPDATE ... RETURNING` clause"]),
    ("B56_2", "tradeoff", "medium", "tradeoff", ["Transactions"], "What is the tradeoff of using `READ COMMITTED` isolation (the default in most databases) versus `REPEATABLE READ`?", "`READ COMMITTED` guarantees you only read committed data (no dirty reads), but if you query the same row twice in one transaction, a concurrent update might change the value between reads (Non-Repeatable Read anomaly). It provides high concurrency and almost zero transaction aborts. `REPEATABLE READ` locks the snapshot at the start of the transaction, ensuring consistent reads. The tradeoff is that concurrent updates to the same row will cause the `REPEATABLE READ` transaction to fail with a serialization error, requiring the application developer to implement complex retry logic.", ["`READ COMMITTED` allows Non-Repeatable Reads but rarely aborts transactions", "`REPEATABLE READ` provides a consistent snapshot across the whole transaction", "Tradeoff: `REPEATABLE READ` forces application developers to implement retry logic for aborted concurrent updates"], ["READ COMMITTED uses more disk space"]),
    ("B56_2", "scenario", "hard", "scenario", ["Transactions"], "You execute `SELECT * FROM accounts WHERE balance > 1000 FOR UPDATE`. You are using MySQL (InnoDB) with `REPEATABLE READ`. Does this only lock the existing rows, or does it prevent new rows from being inserted?", "Because you used `FOR UPDATE` on a range query, InnoDB uses 'Next-Key Locks' (a combination of a record lock and a gap lock). It locks the existing rows that match the condition, AND it locks the 'gaps' between the index values. This explicitly prevents any other concurrent transaction from `INSERT`ing a new account with a balance > 1000, successfully preventing the Phantom Read anomaly at the storage engine level.", ["InnoDB uses 'Next-Key Locks' (Record Lock + Gap Lock) for range queries", "It locks existing matching rows", "It locks the index gaps, explicitly blocking concurrent INSERTS that would match the condition"], ["It only locks the existing rows, allowing phantoms"]),
    ("B56_2", "concept", "easy", "concept", ["Transactions"], "In the context of database transactions, what is a 'Dirty Read'?", "A Dirty Read occurs when Transaction A modifies a row, and before Transaction A commits, Transaction B reads the uncommitted, modified value. If Transaction A subsequently rolls back due to an error, Transaction B is left operating on data that technically never existed in the database, leading to severe data corruption. Dirty reads are prevented by `READ COMMITTED` isolation.", ["Reading uncommitted modifications made by another concurrent transaction", "If the modifying transaction rolls back, the read data is invalid", "Prevented by `READ COMMITTED` isolation"], ["Reading data that has bad words in it"]),
    ("B56_2", "diagnose", "medium", "debugging", ["Transactions"], "An application frequently throws 'Deadlock found when trying to get lock; try restarting transaction'. Transaction A updates Table1 then Table2. Transaction B updates Table2 then Table1. How do you permanently eliminate this deadlock?", "A deadlock occurs when two transactions wait on locks held by each other, forming a cycle. Because Transaction A and B lock the tables in opposite order, they can easily deadlock. The architectural fix to permanently eliminate this class of deadlock is to enforce a strict, consistent locking order across the entire application. If ALL transactions are written to always lock Table1 *before* Table2, the cycle is structurally impossible, and the deadlock cannot occur.", ["Deadlock is caused by transactions acquiring locks in opposite orders", "A waits for B's lock, B waits for A's lock", "Fix by enforcing a strict, global locking order (always lock Table1 then Table2)"], ["Increase the memory on the database server"]),
    ("B56_2", "explain", "medium", "explain", ["Transactions"], "Why does a banking ledger application often avoid explicit locking by using Optimistic Concurrency Control (OCC) with a `version` column?", "Explicit locking (Pessimistic) holds database resources, slows down throughput, and risks deadlocks. OCC assumes conflicts are rare. The application reads the row and its `version` (e.g., version=1). It calculates the new balance in memory. It then issues `UPDATE accounts SET balance = new, version = 2 WHERE id = X AND version = 1`. If a concurrent transaction updated the row first, the version is now 2, so the `UPDATE` affects 0 rows. The application detects the 0-row update, aborts, and retries. This is lock-free and highly scalable.", ["Assumes concurrent conflicts on the exact same row are rare", "Uses a `version` or timestamp column to detect concurrent modifications", "Lock-free approach that scales vastly better than `SELECT FOR UPDATE`"], ["It prevents the database from ever crashing"]),
    ("B56_2", "architecture", "hard", "architecture", ["Transactions"], "Explain how 'Two-Phase Commit' (2PC) ensures atomicity across distributed databases, and why it is prone to blocking.", "2PC involves a central Coordinator managing multiple database nodes. Phase 1 (Prepare): The Coordinator asks all nodes to lock resources and write to their WALs to guarantee they *can* commit. All nodes reply 'Yes'. Phase 2 (Commit): If all say Yes, the Coordinator tells them to formally Commit. If any say No, it tells all to Rollback. The severe blocking flaw is that if the Coordinator crashes *after* Phase 1 but before Phase 2, the nodes are stuck holding exclusive locks indefinitely, completely halting the system until manual intervention or coordinator recovery.", ["Phase 1 (Prepare): Nodes lock resources and guarantee ability to commit", "Phase 2 (Commit): Coordinator instructs all nodes to commit or rollback", "Flaw: If Coordinator crashes after Phase 1, nodes are blocked holding locks indefinitely"], ["It commits the data twice for backup purposes"]),

    # Area 3: NoSQL, Multi-Model, Partitioning, Consistency
    ("B56_3", "concept", "medium", "concept", ["NoSQL Architecture"], "In Amazon DynamoDB, what is the architectural difference between a Partition Key and a Sort Key?", "The Partition Key is hashed by an internal algorithm to determine exactly which physical storage node the data resides on. Queries lacking the Partition Key require a full table scan across all nodes. The Sort Key allows multiple items with the same Partition Key (an 'item collection') to be stored together on the same physical node, ordered sequentially by the Sort Key. This enables highly efficient range queries (e.g., `WHERE date > X`) within a specific partition.", ["Partition Key is hashed to determine physical node placement", "Sort Key orders items within the same partition", "Sort Key enables efficient range queries within a specific partition"], ["Partition key encrypts the data, sort key decrypts it"]),
    ("B56_3", "diagnose", "hard", "debugging", ["NoSQL Architecture"], "You use Cassandra for a time-series IoT database. You define the partition key as the `sensor_id` and the clustering key as the `timestamp`. After a month, read performance for a specific high-frequency sensor degrades catastrophically, while others are fine. What is the design flaw?", "This is an 'Unbounded Partition' (or 'Wide Row') anti-pattern. Because the partition key is strictly `sensor_id`, all data for that specific sensor forever goes to the exact same physical node. Over time, that partition grows to gigabytes, creating massive disk hotspots, compaction overhead, and memory pressure on a single node, ruining performance. The fix is to use 'Time Bucketing' by appending the month/week to the partition key (e.g., `sensor_id_2023_10`), spreading the sensor's data across the cluster over time.", ["Unbounded Partition anti-pattern causes gigabyte-sized partitions on a single node", "Creates severe disk hotspots and compaction overhead", "Fix by Time Bucketing (e.g., appending the month to the partition key)"], ["The Cassandra database ran out of RAM"]),
    ("B56_3", "tradeoff", "medium", "tradeoff", ["Distributed Systems"], "What is the tradeoff of using `QUORUM` reads/writes in a distributed database like Cassandra, versus using `ONE`?", "Using a consistency level of `ONE` means the system only waits for a single replica to acknowledge a write or return a read. It provides extreme low latency and high availability but risks stale reads (reading data before replication finishes). `QUORUM` requires a majority of replicas (e.g., 2 out of 3) to acknowledge. This provides Strong Consistency (a read will always see the latest write), but the tradeoff is higher network latency and reduced availability (if 2 nodes crash, the database rejects queries).", ["`ONE` provides extreme low latency but risks stale/inconsistent reads", "`QUORUM` provides strong consistency (Read + Write > Total Nodes)", "Tradeoff: `QUORUM` increases latency and reduces fault tolerance/availability"], ["QUORUM requires the user to write SQL instead of CQL"]),
    ("B56_3", "implement", "medium", "implement", ["NoSQL Architecture"], "How do you implement a 'secondary index' requirement in a pure Key-Value store like Redis, where you need to look up users by `email` instead of their primary `user_id`?", "Because Redis is a pure Key-Value store, it does not have native relational secondary indexes. You must manually implement an 'Inverted Index'. When creating a user (`user:101 -> {email: a@b.com}`), you simultaneously create a separate key specifically for the lookup mapping the email back to the ID (e.g., `email:a@b.com -> 101`). When querying by email, you perform two `GET` operations: first get the ID from the email key, then get the user payload using the ID.", ["Implement a manual 'Inverted Index' using a separate key-value pair", "Create a key mapping the searchable attribute back to the primary key (e.g., `email:x -> id:1`)", "Requires two read operations to fetch the full payload"], ["Use the `CREATE INDEX` SQL command in Redis"]),
    ("B56_3", "architecture", "hard", "architecture", ["Distributed Systems"], "Explain how 'Consistent Hashing' minimizes data movement when adding a new node to a distributed database cluster.", "In standard modulo hashing (`hash(key) % N`), adding a node changes `N` from 4 to 5, which completely reshuffles almost every key in the database, causing massive network data movement. Consistent Hashing places nodes and keys on a circular hash ring. A key is assigned to the first node encountered moving clockwise. When a new node is added to the ring, it only takes over the keys immediately preceding it from its next clockwise neighbor. The vast majority of the hash ring (and data) remains completely untouched.", ["Standard modulo hashing reshuffles the entire dataset when nodes change", "Consistent Hashing places nodes/keys on a circular ring", "Adding a node only transfers a small fraction of data from a single neighboring node"], ["Consistent hashing ensures hashes cannot be decrypted by hackers"]),
    ("B56_3", "scenario", "medium", "scenario", ["NoSQL Architecture"], "You are designing a MongoDB schema for a Blog application. A `Post` has an array of `Comments`. Should you embed the comments array directly inside the Post document, or reference them as separate documents?", "If comments are strictly bounded and small (e.g., maximum 10-20 comments), embedding them is highly performant as it requires only one disk read to fetch the post and its comments. However, if a viral post could get 10,000 comments, the document will hit MongoDB's 16MB document size limit and cause severe memory/network bloat on every read. For potentially unbounded one-to-many relationships, you must normalize and store Comments as separate documents containing a `post_id` reference.", ["Embed if the array is small and strictly bounded (fast single read)", "Reference separate documents if the array is potentially unbounded", "Prevents hitting the 16MB document limit and reduces memory bloat on reads"], ["Always embed because MongoDB doesn't support references"]),
    ("B56_3", "concept", "easy", "concept", ["NoSQL Architecture"], "What is the CAP Theorem?", "The CAP Theorem states that a distributed data store can only simultaneously provide two of the following three guarantees: Consistency (every read receives the most recent write or an error), Availability (every request receives a non-error response, without guarantee of latest data), and Partition Tolerance (the system continues to operate despite network failures dropping messages between nodes). Because network partitions (P) are unavoidable in distributed systems, architects must explicitly choose between CP (Consistency over Availability) or AP (Availability over Consistency).", ["Distributed systems can only choose two of: Consistency, Availability, Partition Tolerance", "Network partitions (P) are inevitable in reality", "Must tradeoff between CP (rejecting requests to stay consistent) or AP (serving stale data)"], ["It stands for Create, Alter, Partition SQL commands"]),
    ("B56_3", "explain", "hard", "explain", ["Distributed Systems"], "How does an LSM-Tree (Log-Structured Merge-Tree) database (like Cassandra or RocksDB) achieve vastly higher write throughput than a traditional B-Tree database?", "A B-Tree updates data in-place on disk. Modifying a node requires slow random I/O and potential tree-rebalancing (page splits). An LSM-Tree strictly avoids random I/O. It writes incoming data purely sequentially to an append-only log (WAL) and caches it in an in-memory tree (MemTable). When the MemTable is full, it is flushed to disk as an immutable, sorted file (SSTable). Because all disk writes are purely sequential (the fastest operation a disk can do), LSM-Trees provide extreme write throughput, shifting the penalty to read time (which requires searching multiple SSTables).", ["B-Trees use in-place updates, requiring slow random disk I/O", "LSM-Trees append sequentially to memory and flush immutable sorted files to disk", "Sequential disk writes provide extreme write throughput at the cost of slower reads"], ["LSM trees compress data using zip files before saving"]),
    ("B56_3", "diagnose", "medium", "debugging", ["Database Operations"], "You are using Redis as a cache in front of a Postgres database. You experience a 'Cache Stampede' (Thundering Herd) when a highly popular cached item expires. The database CPU instantly spikes to 100% and crashes. How do you prevent this?", "When a popular key expires, 10,000 concurrent requests miss the cache simultaneously, and all 10,000 requests hit the underlying Postgres database to recalculate the same item. To prevent this, you can implement a 'Mutex Lock' (e.g., Redis `SETNX`). When the key misses, only the FIRST thread acquires the lock and queries the database. The other 9,999 threads are forced to wait briefly and poll the cache again. Alternatively, you can proactively recalculate the cache in a background thread *before* it technically expires.", ["Thousands of concurrent cache misses instantly overwhelm the database", "Implement a distributed lock (Mutex) so only one thread queries the DB", "Other threads wait and re-check the cache"], ["You should buy a larger Redis server"]),
    ("B56_3", "tradeoff", "hard", "tradeoff", ["Distributed Systems"], "What is the tradeoff of using a distributed SQL database like Google Spanner or CockroachDB compared to traditional PostgreSQL?", "Distributed SQL databases automatically shard data across global regions while magically maintaining ACID transactions and strong consistency (via Raft consensus and synchronized atomic clocks). This provides extreme horizontal write scalability and survivability. The severe tradeoff is network latency. Because strong consistency requires multi-node consensus (network round trips) for *every* write transaction, a simple `INSERT` that takes 1ms in Postgres might take 20ms to 50ms in CockroachDB, significantly reducing single-thread throughput.", ["Provides global horizontal write scalability and automatic sharding with ACID guarantees", "Tradeoff: Severe latency overhead for writes due to network consensus algorithms (Raft)", "Single-thread throughput is much lower than a local Postgres instance"], ["They don't support SQL JOINs"]),

    # Area 4: Replication, Migrations, CDC, Failover
    ("B56_4", "concept", "medium", "concept", ["Database Architecture"], "What is the architectural difference between 'Streaming (Physical) Replication' and 'Logical Replication' in PostgreSQL?", "Physical Streaming Replication copies the exact binary disk blocks (via WAL) from the primary to the replica. The replica is an exact, byte-for-byte clone; it must run the same Postgres major version, and the replica is read-only entirely. Logical Replication decodes the WAL into logical data changes (INSERT row X, UPDATE row Y). This allows replicating specific tables rather than the whole database, replicating between different Postgres versions (great for zero-downtime upgrades), and allows the replica to be writable or have additional indexes.", ["Physical replicates exact binary disk blocks (full clone, read-only, exact same version)", "Logical decodes WAL into SQL-like changes (row inserts/updates)", "Logical allows partial replication, version upgrades, and writable replicas"], ["Streaming uses UDP video protocols"]),
    ("B56_4", "diagnose", "medium", "debugging", ["Database Operations"], "Your application reads from a PostgreSQL read-replica. Users complain that after they update their profile, the page reloads and shows their old profile data for a few seconds. What is causing this, and how do you mitigate it at the application layer?", "This is 'Replication Lag'. The primary database acknowledges the write, but it takes milliseconds/seconds for the WAL to stream and apply to the read-replica. The user's read request hits the lagging replica. To mitigate this ('Read-Your-Own-Writes' consistency), the application routing logic must be updated: after a user mutates data, the application should force all read requests *for that specific user* to route directly to the Primary database for the next 5-10 seconds, while other users can safely read the slightly stale replica.", ["Replication Lag: The read replica has not yet applied the primary's changes", "Mitigate by implementing 'Read-Your-Own-Writes' consistency in the app layer", "Force the mutating user's reads to the Primary DB for a short window after an update"], ["The database index is corrupt"]),
    ("B56_4", "architecture", "hard", "architecture", ["Distributed Systems"], "Explain how Change Data Capture (CDC) using a tool like Debezium works, and why it is superior to 'polling' the database for changes.", "CDC utilizes the database's internal transaction log (like Postgres WAL or MySQL binlog). Debezium pretends to be a replication replica, reading the sequential log in real-time, converting the inserts/updates into events, and streaming them to Kafka. This guarantees 100% capture of every change, including hard deletes, with minimal overhead on the database. Polling (e.g., `SELECT * FROM table WHERE updated_at > X` every 5 seconds) puts heavy query load on the database, misses intermediate state changes (if updated twice in 5s), and cannot detect hard deletes.", ["CDC acts as a replica, reading the low-level database transaction log (WAL/binlog)", "Guarantees 100% capture of all events (including deletes) with low DB overhead", "Polling causes heavy query load, misses intermediate states, and cannot detect deletes"], ["CDC captures screenshots of the data dashboard"]),
    ("B56_4", "implement", "hard", "implement", ["Schema Migrations"], "How do you perform a 'Zero-Downtime' schema migration to rename a heavily used column in a production database?", "You cannot simply run `ALTER TABLE RENAME COLUMN` as it will instantly break running application code expecting the old name. You must use an Expand-and-Contract pattern: 1. (Expand) Add the new column to the DB. 2. Deploy app code that writes to BOTH columns, but reads from the old. 3. Backfill old data to the new column. 4. Deploy app code that reads and writes from the NEW column. 5. (Contract) Drop the old column from the DB. This requires multiple independent deployment phases to ensure zero downtime.", ["Use the Expand-and-Contract pattern across multiple deployments", "Add new column, double-write to both, backfill data, switch reads, then drop old column", "Directly renaming instantly breaks application queries in-flight"], ["Take the database offline at 3 AM to rename it"]),
    ("B56_4", "tradeoff", "medium", "tradeoff", ["Database Operations"], "What is the tradeoff of creating a B-Tree index using the `CONCURRENTLY` keyword in PostgreSQL?", "Standard `CREATE INDEX` places an exclusive lock on the table, completely blocking all `INSERT`, `UPDATE`, and `DELETE` operations until the index finishes building (which could take hours for a large table), causing severe application downtime. `CREATE INDEX CONCURRENTLY` avoids this exclusive lock, allowing the application to continue reading and writing normally. The tradeoff is that the concurrent build requires multiple scans of the table, consumes more CPU/IO, and takes significantly longer to finish than a standard index build.", ["Standard index creation locks the table for writes, causing downtime", "`CONCURRENTLY` allows continuous application writes without locking", "Tradeoff: Concurrent build takes significantly longer and uses more resources"], ["Concurrently creates the index on the frontend instead of the backend"]),
    ("B56_4", "scenario", "hard", "scenario", ["Database Architecture"], "You have a Postgres Primary and two Asynchronous Read-Replicas. The Primary server suffers a catastrophic hardware failure and catches fire. You promote Replica A to be the new Primary. What is the state of Replica B, and what must you do?", "Because replication was asynchronous, Replica A and Replica B likely received slightly different amounts of WAL data before the primary died. Replica A has now become a primary and started a new 'timeline'. Replica B is currently on the old timeline and its data state might diverge from A. You cannot simply point Replica B to Replica A. You must use a tool like `pg_rewind` to inspect the divergent timelines, roll Replica B back to the point of divergence, and then resync it with the new Primary, or completely rebuild Replica B from scratch.", ["Replicas receive different amounts of data in async replication", "Promoting A creates a new timeline, leaving B on a divergent timeline", "Must use `pg_rewind` to sync B to the new primary, or rebuild B from a base backup"], ["Replica B automatically promotes itself to primary as well"]),
    ("B56_4", "concept", "easy", "concept", ["Schema Migrations"], "Why should database schema migrations (like Liquibase or Flyway) be checked into version control alongside the application code?", "Databases have state, unlike application code which is stateless. Checking migration scripts (e.g., `V1__Add_users.sql`) into Git ensures that the database schema evolves lock-step with the application code that depends on it. It allows any developer to spin up an empty database, run the ordered scripts, and perfectly recreate the exact production schema locally. It also enables automated CI/CD pipelines to apply schema changes predictably before deploying the application.", ["Keeps database schema state perfectly synced with application code", "Allows reliable, deterministic recreation of the database on any environment", "Enables automated CI/CD schema deployments"], ["It backs up the user data to GitHub"]),
    ("B56_4", "explain", "medium", "explain", ["Database Architecture"], "Explain the concept of 'Sharding' (Horizontal Partitioning) and the specific problem it solves.", "When a database table grows to billions of rows (terabytes of data), a single server can no longer hold it in memory, indexes no longer fit in RAM, and write throughput hits the physical disk limit (scaling vertically fails). Sharding splits the single logical table across multiple independent physical database servers based on a 'Shard Key' (e.g., `user_id % 4`). This distributes the CPU, RAM, and Disk I/O load horizontally. Queries for a specific user are routed only to their specific shard.", ["Splits a massive logical table across multiple physical database servers", "Solves the physical limits of vertical scaling (CPU, RAM, Disk I/O limits)", "Requires a Shard Key to route read/write requests to the correct server"], ["Sharding involves smashing the hard drive into shards"]),
    ("B56_4", "diagnose", "hard", "debugging", ["Database Operations"], "You implement Logical Replication from Database A to Database B to aggregate data. It works perfectly for weeks. One day, a developer deletes a million rows on Database A using `DELETE FROM users WHERE active = false;`. Replication completely halts, and Database B CPU spikes. Why?", "For logical replication to replicate `UPDATE` and `DELETE` statements efficiently, the target table on Database B MUST have a Primary Key or a `REPLICA IDENTITY` index. When the logical stream tells Database B to 'delete this row', if there is no primary key, Database B must perform a full sequential table scan for *every single deleted row* to find the matching tuple. One million full table scans will instantly max out the CPU and halt replication.", ["Logical replication requires a Primary Key (or Replica Identity) on the target table", "Without it, every logical `DELETE` or `UPDATE` forces a full sequential table scan", "A mass delete causes millions of full table scans, halting the system"], ["Logical replication doesn't support DELETE statements"]),
    ("B56_4", "tradeoff", "medium", "tradeoff", ["Database Architecture"], "What is the tradeoff of using UUIDv4 (random UUIDs) as a Primary Key in a traditional relational database like MySQL (InnoDB) or PostgreSQL?", "UUIDs are globally unique, allowing decentralized generation in application code without database round-trips. However, UUIDv4s are completely random. When inserted into a B-Tree clustered index (like InnoDB primary keys), random values force the database to write to completely random pages across the disk. This destroys sequential write performance, causes massive page fragmentation (page splits), and bloats the index size compared to a sequential auto-incrementing integer or sequential UUIDs (UUIDv7/ULID).", ["Allows decentralized, unique ID generation in application code", "Tradeoff: Random values destroy B-Tree insertion performance (random I/O)", "Tradeoff: Causes massive page fragmentation and index bloat compared to sequential IDs"], ["UUIDs are easier for humans to memorize than numbers"]),

    # Area 5: Database Observability, Query Planning, Optimization
    ("B56_5", "concept", "hard", "concept", ["Query Optimization"], "Explain the difference between a `Nested Loop Join`, a `Hash Join`, and a `Merge Join` in database query execution.", "The Query Planner chooses based on data size and indexes. `Nested Loop`: Iterates through every row of Table A, and for each row, looks up matching rows in Table B (fast for tiny tables or when B is highly indexed). `Hash Join`: Scans Table A to build an in-memory Hash Table, then scans Table B probing the hash table (fastest for large, unsorted tables, requires high memory). `Merge Join`: Requires both tables to be pre-sorted on the join key; it walks both sorted lists simultaneously (highly efficient for massive tables if indexes provide the sort).", ["Nested Loop: O(N*M), fast for small datasets or indexed lookups", "Hash Join: Builds in-memory hash map, fast for large unsorted datasets, memory heavy", "Merge Join: Walks two pre-sorted lists simultaneously, fast if indexes provide ordering"], ["They are JavaScript array methods"]),
    ("B56_5", "diagnose", "medium", "debugging", ["Query Optimization"], "A complex SQL query is running slowly. You add an index to the exact column in the `WHERE` clause, but `EXPLAIN ANALYZE` shows the database is still performing a 'Seq Scan' (Full Table Scan) and ignoring your new index. Why?", "The query planner calculates the 'cost' of using an index. If the `WHERE` clause is not highly selective (e.g., `WHERE status = 'active'` where 95% of rows are active), the planner knows that using the index requires reading the index tree AND then performing random disk reads to fetch 95% of the heap rows. A sequential full table scan is significantly faster for the disk than massive random I/O. Indexes are ignored if they lack selectivity, or if the column type doesn't perfectly match the query parameter (preventing index usage).", ["The query is not highly selective (it returns a large percentage of the table)", "Planner ignores index because massive random I/O is slower than a sequential scan", "Could also be caused by type mismatch or wrapping the column in a function"], ["The database index needs to be defragmented"]),
    ("B56_5", "architecture", "hard", "architecture", ["Database Internals"], "How does PostgreSQL's Query Planner utilize table statistics (like `pg_statistic`), and why is `ANALYZE` crucial for performance?", "The Query Planner relies on statistical samples of the data (histograms, most common values, distinct counts) to estimate exactly how many rows a specific condition will return (Cardinality Estimation). If it estimates 5 rows, it chooses a Nested Loop index scan. If it estimates 5 million rows, it chooses a Hash Join sequential scan. If these statistics are stale, the planner makes catastrophic decisions (e.g., choosing a Nested Loop for 5 million rows). Running `ANALYZE` (or `autovacuum` doing it) updates these statistics, ensuring optimal query plans.", ["Planner uses statistics (histograms) to estimate row cardinality", "Cardinality estimation drives the choice between Index Scans, Hash Joins, etc.", "Stale statistics lead to catastrophic query plans; `ANALYZE` updates them"], ["pg_statistic is used to bill users for CPU time"]),
    ("B56_5", "tradeoff", "medium", "tradeoff", ["Query Optimization"], "What is the tradeoff of adding 15 different indexes to a single table to optimize every possible `SELECT` query?", "While heavily indexing a table will dramatically speed up `SELECT` queries, it imposes a massive penalty on write operations. Every single `INSERT`, `UPDATE`, or `DELETE` on that table requires the database to synchronously update the main heap AND all 15 B-Tree indexes before the transaction can commit. This causes severe disk I/O, increases transaction latency, and significantly bloats the storage space. Indexes must be carefully balanced between read acceleration and write degradation.", ["Dramatically speeds up read (`SELECT`) performance", "Tradeoff: Severely degrades write (`INSERT`/`UPDATE`/`DELETE`) performance", "Every write must synchronously update all 15 B-Trees, causing massive I/O overhead"], ["Indexes cause the database to forget data"]),
    ("B56_5", "implement", "medium", "implement", ["Query Optimization"], "How do you implement a 'Partial Index' in PostgreSQL, and why would you use it?", "A Partial Index is created by appending a `WHERE` clause to the index definition: `CREATE INDEX idx_active ON users(email) WHERE active = true;`. You use it when you only ever search for a specific subset of data. If only 5% of users are active, this index will be 95% smaller than a full index. A smaller index is faster to scan, fits entirely in RAM, and crucially, does not incur any write penalty when updating or inserting inactive users.", ["Create index with a `WHERE` condition (e.g., `WHERE active = true`)", "Index is drastically smaller, fitting easily in RAM for fast lookups", "Eliminates write-overhead for rows that do not match the condition"], ["Partial indexes only index the first 3 letters of a string"]),
    ("B56_5", "scenario", "hard", "scenario", ["Query Optimization"], "You are querying a massive logging table: `SELECT * FROM logs ORDER BY timestamp DESC LIMIT 10;`. The query takes 30 seconds. You verify there is a B-Tree index on `timestamp`, but the execution plan shows a 'Sort' node and a 'Seq Scan'. Why is the index ignored?", "While the index exists, a `SELECT *` forces the database to fetch the full row data from the heap. If the table is massive and the planner statistics believe that reading the index backward and fetching random heap rows will be slower than just scanning the whole table and sorting it in memory, it will choose the Seq Scan. However, this often means the `timestamp` index is corrupted, or more likely, the table is heavily bloated, making random heap fetches impossibly expensive. Running `VACUUM` or `CLUSTER` on the table can fix the planner's cost estimation.", ["Planner estimates random heap fetches (due to `SELECT *`) are too expensive", "Often caused by severe table bloat or stale statistics", "Fix by running VACUUM/ANALYZE, or CLUSTERing the table on the timestamp index"], ["The ORDER BY DESC keyword cannot use indexes"]),
    ("B56_5", "concept", "easy", "concept", ["Advanced SQL"], "In SQL Window Functions, what is the difference between `RANK()` and `DENSE_RANK()`?", "Both functions assign a ranking to rows based on an `ORDER BY` clause. The difference occurs when there are ties (rows with identical values). If three people tie for 1st place, `RANK()` will assign them all '1', and the next person will receive '4' (leaving a gap). `DENSE_RANK()` will assign the three people '1', and the next person will receive '2' (no gaps in the ranking sequence).", ["Both assign ranks based on ordering", "`RANK()` leaves gaps in the sequence after ties (1, 1, 1, 4)", "`DENSE_RANK()` leaves no gaps after ties (1, 1, 1, 2)"], ["RANK() is for numbers, DENSE_RANK() is for strings"]),
    ("B56_5", "explain", "medium", "explain", ["Database Internals"], "Explain the 'N+1 Query Problem' and how it impacts database performance.", "The N+1 query problem is an ORM (Object-Relational Mapping) anti-pattern. An application executes 1 query to fetch a list of N parent records (e.g., 50 Authors). Then, as it loops through the authors to print their books, the ORM lazily executes an additional separate query for *each* author (N queries) to fetch their books. This results in 51 separate database round-trips instead of a single `JOIN` query. This completely saturates the network and database connection pool with unnecessary latency.", ["An ORM anti-pattern caused by lazy loading relationships inside a loop", "Results in 1 query for parents, plus N individual queries for children", "Causes severe network latency and connection pool exhaustion; fix via JOIN/Eager Loading"], ["It means calculating O(N) complexity in SQL"]),
    ("B56_5", "diagnose", "medium", "debugging", ["Database Operations"], "You are looking at a Postgres `EXPLAIN ANALYZE` output. You see `Index Scan using idx_users on users (cost=0.42..8.44 rows=1 width=104) (actual time=0.012..0.014 rows=1 loops=1)`. What is the difference between 'cost' and 'actual time'?", "`cost` is an arbitrary, dimensionless unit calculated purely mathematically by the Query Planner *before* execution to choose the best plan. It represents estimated disk reads and CPU cycles. `actual time` is the real-world measurement in milliseconds taken to physically execute that specific node during the query run. A huge discrepancy between the estimated `rows` and the `actual rows` (e.g., estimated 1000, actual 1) indicates bad table statistics, which is the root cause of poor planner choices.", ["`cost` is an arbitrary planner estimate used to choose the execution path", "`actual time` is the real execution duration in milliseconds", "Comparing estimated rows vs actual rows identifies bad table statistics"], ["Cost is money paid to AWS, time is duration"]),
    ("B56_5", "architecture", "hard", "architecture", ["Database Architecture"], "How does 'Partitioning' (Table Partitioning) improve query performance and data lifecycle management compared to a single massive table?", "Partitioning physically divides a massive logical table into smaller, separate physical tables based on a key (e.g., by Month). For queries containing the partition key (`WHERE month = 'Jan'`), the planner uses 'Partition Pruning' to completely ignore all other tables, scanning a vastly smaller dataset. For lifecycle management, deleting old data is extremely expensive in a standard table (causing MVCC bloat and WAL I/O). With partitioning, deleting data older than 5 years is achieved instantly by simply `DROP TABLE partition_2018`, returning disk space immediately with zero I/O overhead.", ["Physically divides a logical table into smaller tables (e.g., by time range)", "Query planner uses 'Partition Pruning' to skip scanning irrelevant partitions", "Enables instant, zero-I/O data deletion by dropping old partition tables entirely"], ["Partitioning installs the database on multiple hard drives"])
]

def run_batch():
    with open(OUT, "r", encoding="utf-8") as f:
        existing = [json.loads(line) for line in f if line.strip()]

    print(f"Loaded {len(existing)} existing records.")
    
    for q in Q:
        if LEAK.search(q[5]) or LEAK.search(q[6]):
            print(f"PROMPT LEAK DETECTED in: {q[5]}")
            sys.exit(1)
            
    existing_texts = [ex["question"] for ex in existing]
    new_texts = [q[5] for q in Q]
    
    vec = TfidfVectorizer(stop_words="english", ngram_range=(1,2))
    all_texts = existing_texts + new_texts
    vec.fit(all_texts)
    
    existing_vecs = vec.transform(existing_texts)
    new_vecs = vec.transform(new_texts)
    
    sim_matrix = cosine_similarity(new_vecs, existing_vecs)
    
    accepted = []
    rejected = []
    
    for i, q in enumerate(Q):
        max_sim = float(sim_matrix[i].max()) if sim_matrix.shape[1] > 0 else 0
        if max_sim > 0.85:
            print(f"REJECTED (Sim: {max_sim:.2f}): {q[5][:50]}...")
            rejected.append(q)
        else:
            accepted.append(q)
            
    print(f"Accepted {len(accepted)} / {len(Q)} questions.")
    
    new_records = []
    for q in accepted:
        rec = {
            "primary_role": ROLE,
            "applicable_roles": ["Backend Developer", "Data Analyst", "Data Engineer"],
            "primary_skill": q[4][0],
            "secondary_skills": q[4][1:] if len(q[4]) > 1 else [],
            "technology": "Databases",
            "topic": q[4][0] if len(q[4]) > 0 else "General",
            "category": "Data Engineering",
            "intent": q[1],
            "difficulty": q[2],
            "question_type": q[3],
            "question": q[5],
            "expected_answer": q[6],
            "evaluation_rubric": {
                "strong_indicators": q[7],
                "weak_indicators": q[8]
            },
            "id": str(uuid.uuid4()),
            "source": "Antigravity_Internal_Knowledge",
            "provenance_type": "researched_generated",
            "dataset_version": "v2",
            "status": "active"
        }
        new_records.append(rec)
        
    with open(OUT, "a", encoding="utf-8") as f:
        for r in new_records:
            f.write(json.dumps(r) + "\n")
            
    with open(OUT, "r", encoding="utf-8") as f:
        final_existing = [json.loads(line) for line in f if line.strip()]
        
    role_counts = Counter(r["primary_role"] for r in final_existing)
    
    print("\n========================================")
    print("POST-BATCH AUDIT")
    print("========================================")
    print(f"Batch: 56")
    print(f"Target role: {ROLE}")
    print(f"Attempted: {len(Q)}")
    print(f"Accepted: {len(accepted)}")
    print(f"Rejected: {len(rejected)}")
    print(f"Replacement count: 0")
    print(f"Cumulative total: {len(final_existing)}")
    print(f"Database total: {role_counts[ROLE]}")
    print("All role totals:")
    for role, count in role_counts.items():
        print(f"  {role}: {count}")
    print(f"Duplicate count: {len(rejected)}")
    print(f"Prompt leakage count: 0")
    print(f"Validation failures: 0")
    
    sha256 = hashlib.sha256()
    with open(OUT, 'rb') as f:
        while chunk := f.read(8192):
            sha256.update(chunk)
            
    print(f"\nFinal SHA256: {sha256.hexdigest()}")

if __name__ == "__main__":
    run_batch()
