import asyncio
import json
import os
import re
import sys
import uuid
import hashlib
from collections import Counter

from dotenv import load_dotenv
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
load_dotenv()

BACKEND_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_DIR = os.path.join(BACKEND_DIR, "data")
OUT = os.path.join(DATA_DIR, "interview_question_bank_v2_generated.jsonl")

ROLE = "Python Developer"
LEAK = re.compile(r"(generate a question|generate \d+ questions|return only json|phase 4c gap plan|"
                  r"generation batch|candidate generation|system instructions|do not proceed|"
                  r"awaiting authorization|minimum target|generation pipeline|"
                  r"batch \d+ generation|expected answer|strong indicator|weak indicator|as an ai|"
                  r"here is the question|\bprompt text\b)", re.I)

Q = [
    # Type Hinting Internals
    ("B63_5_1", "concept", "hard", "concept", ["Type Hinting"], "In Python type hinting, what is `ParamSpec` and how does it solve the problem of preserving type signatures when writing generic Decorators?", "Historically, when you wrote a decorator using `*args, **kwargs` and annotated the return type, `mypy` lost all visibility into the original function's parameters. If the decorated function required `(x: int, y: str)`, the type checker would silently allow `decorated_func(1, 2)`. `ParamSpec` allows you to capture the entire parameter signature of a callable and bind it to a TypeVar. By annotating the decorator as `Callable[P, R]`, the type checker preserves the exact arguments of the wrapped function and strictly enforces them at the call site of the decorated function.", ["Without `ParamSpec`, generic decorators using `*args, **kwargs` erase the underlying function's argument types", "`ParamSpec` captures the entire signature of a callable (its parameter specification)", "Allows `mypy` to strictly type-check calls to decorated functions, preventing silent signature mismatches"], ["ParamSpec specifies the parameters of the server hardware"]),
    ("B63_5_2", "diagnose", "medium", "debugging", ["Type Hinting"], "You type hint a function that accepts a list of integers or floats: `def process(data: list[int | float])`. You pass a variable typed as `list[int]` to the function. `mypy` throws an error: `Argument 1 to process has incompatible type list[int]; expected list[int | float]`. Why does this fail, given that an int is an int or float?", "This fails because standard Python lists are 'Invariant' types, not 'Covariant'. If `mypy` allowed you to pass a `list[int]` into a function expecting `list[int | float]`, the function could legally append a `float` (e.g., `3.14`) into the list. When the function returns, the caller's original `list[int]` would now contain a float, completely corrupting the caller's type safety. To fix this, you must type the function parameter as `Sequence[int | float]`. `Sequence` is a read-only Covariant type, guaranteeing to `mypy` that the function will not mutate the list, making it safe to pass narrower types.", ["Lists are 'Invariant' because they are mutable", "Passing `list[int]` to `list[int | float]` is unsafe because the function could append a float, corrupting the caller's list", "Fix: Use `Sequence[int | float]` which is read-only (Covariant), proving no unsafe mutations will occur"], ["Mypy is just broken and throws random errors"]),
    ("B63_5_3", "implement", "medium", "implement", ["Type Hinting"], "How do you implement a `Protocol` (Structural Subtyping) in Python, and why is it preferred over `abc.ABC` (Nominal Subtyping) for duck typing?", "In Nominal Subtyping (`abc.ABC`), a class MUST explicitly inherit from the base class (`class Duck(Animal)`). If you are using a 3rd-party library class that acts like an Animal but doesn't inherit from your ABC, `mypy` will reject it. Structural Subtyping (`Protocol`) solves this. You define `class Animal(Protocol): def speak(self): ...`. Any class in any library that happens to have a `speak()` method is automatically considered an `Animal` by the type checker, without requiring any explicit inheritance or modification of the 3rd-party source code.", ["`Protocol` enables Structural Subtyping (Static Duck Typing)", "Unlike `abc.ABC`, a class does not need to explicitly inherit from a Protocol to satisfy it", "It allows strict type-checking of 3rd-party or legacy objects purely based on their behavior/methods"], ["Protocol means you have to use HTTPS to connect to the types"]),
    ("B63_5_4", "tradeoff", "hard", "tradeoff", ["Type Hinting"], "What is the tradeoff of using `@typing.runtime_checkable` on a `Protocol`?", "By default, a `Protocol` is purely a static type-checking construct (used by `mypy`); it physically doesn't exist at runtime, so `isinstance(obj, MyProtocol)` throws an error. Decorating it with `@runtime_checkable` allows you to use `isinstance()`. The massive tradeoff is Runtime Performance and Safety. `isinstance` on a Protocol requires Python to dynamically inspect the `__dict__` and `dir()` of the object to see if all required methods exist. This is incredibly slow compared to a normal `isinstance` check. Furthermore, it only checks the *names* of the methods, not their signatures; if the Protocol requires `speak(volume: int)` and the object has `speak(color: str)`, `isinstance` will falsely return True, causing a crash later.", ["Allows `isinstance()` checks against structural Protocols at runtime", "Tradeoff 1: Massive performance penalty due to dynamic attribute inspection", "Tradeoff 2: False sense of security; it only verifies method names exist, not that their argument signatures match"], ["Runtime checkable makes the code compile into C++"]),

    # Advanced OOP & Design Patterns
    ("B63_5_5", "concept", "medium", "concept", ["OOP"], "What is the 'Monostate' (Borg) pattern in Python, and how does it differ from a standard Singleton?", "A traditional Singleton restricts class instantiation so that `__new__` always returns the exact same physical object (same memory address). The 'Monostate' or 'Borg' pattern allows infinite distinct objects to be instantiated (different memory addresses), but explicitly forces them all to share the exact same internal state. It is implemented by overriding the `__dict__` of every new instance to point to a shared class-level dictionary (`self.__dict__ = cls._shared_state`). This provides the global state benefits of a Singleton while avoiding subclassing complexities and `__new__` override bugs.", ["Singleton restricts instantiation to a single physical memory address", "Monostate (Borg) allows infinite distinct instances, but forces them all to share the same `__dict__` state", "Solves global state needs without the restrictive boilerplate of `__new__` Singleton implementations"], ["Monostate means the server only has one state variable"]),
    ("B63_5_6", "diagnose", "hard", "debugging", ["OOP"], "You implement a classic Singleton pattern in Python by overriding `__new__`: `if cls._instance is None: cls._instance = super().__new__(cls)`. However, under high web traffic, the `__init__` method randomly executes multiple times, overwriting production data. Why?", "The standard `__new__` Singleton implementation is not Thread-Safe. If two concurrent HTTP requests (threads) hit the `if cls._instance is None:` line at the exact same millisecond, both threads evaluate it to True. Both threads call `super().__new__`, creating two distinct objects, and both threads sequentially execute `__init__`, destroying the Singleton guarantee. To fix this, you MUST wrap the instantiation check inside a `threading.Lock()`. Furthermore, even if `__new__` returns an existing instance, Python will always call `__init__` on it automatically. You must add a boolean flag (`_initialized = True`) to prevent `__init__` from re-executing.", ["The `if instance is None` check is vulnerable to Race Conditions in multithreaded environments", "Even when returning an existing instance, Python always automatically calls `__init__` again", "Fix: Use a `threading.Lock()` around the instantiation, and add an initialization flag to guard `__init__`"], ["The singleton got tired and cloned itself"]),
    ("B63_5_7", "implement", "medium", "implement", ["OOP"], "How do you correctly implement a 'Mixin' class in Python, and why should a Mixin never define an `__init__` method?", "A Mixin is a small class designed to inject a specific behavior (like `to_json()`) into multiple unrelated classes via Multiple Inheritance. A Mixin should NEVER define an `__init__` method because it breaks the `super().__init__()` chain in complex MRO (Method Resolution Order) trees. If a Mixin requires state, it should define abstract properties or require the host class to provide the state. A Mixin is correctly implemented by placed it first in the inheritance list (`class User(JsonMixin, BaseModel):`) so its methods take precedence, but without interfering with the instantiation of the core `BaseModel`.", ["Mixins inject isolated functionality (like logging or serialization) via multiple inheritance", "Defining `__init__` in a Mixin creates severe MRO conflicts and breaks the `super()` initialization chain", "Fix: Mixins should rely on the host class for state, or define abstract properties to enforce state contracts"], ["Mixins are a type of blender used for data science"]),
    ("B63_5_8", "tradeoff", "hard", "tradeoff", ["OOP"], "What is the architectural tradeoff of using strict Dependency Injection (DI) frameworks in Python (e.g., `injector` or `Dependency-Injector`) versus Python's dynamic duck-typing nature?", "In compiled languages (Java), DI frameworks are mandatory to decouple hardcoded classes. In Python, rigorous DI frameworks add massive boilerplate, complex wiring configurations, and obscure stack traces. The tradeoff is that Python natively supports 'Monkey Patching' and first-class functions. You can achieve 90% of the benefits of DI simply by passing functions or classes as default keyword arguments (`def process(db=production_db):`). However, for massive enterprise monoliths with hundreds of services, native Python becomes tangled. A formal DI framework mathematically guarantees that object lifecycles (singletons vs factories) are strictly managed and decoupled, at the cost of losing Pythonic simplicity.", ["DI frameworks provide rigorous, enterprise-grade decoupling and lifecycle management (Singletons/Factories)", "Tradeoff: Adds massive, un-Pythonic boilerplate and obfuscates stack traces", "Python's dynamic nature often makes formal DI overkill, as default keyword arguments and monkey-patching easily achieve the same testability"], ["Dependency injection involves injecting vaccines into the servers"]),

    # Context Managers & Resource Lifecycles
    ("B63_5_9", "concept", "medium", "concept", ["Context Managers"], "What is `contextlib.ExitStack` in Python, and how does it solve the 'dynamic resource' problem?", "Normally, you use a `with` statement for a known number of resources (`with open(a), open(b):`). However, if you need to open a dynamic list of 50 files based on user input, you cannot write 50 nested `with` blocks. `ExitStack` solves this. You instantiate `with ExitStack() as stack:`, and inside a `for` loop, you call `stack.enter_context(open(file))`. The `ExitStack` tracks every single context manager you pushed onto it. When the block exits (or an exception is thrown), `ExitStack` automatically and safely closes all 50 files in reverse order.", ["Used to dynamically manage an unknown or variable number of Context Managers at runtime", "Avoids impossible syntax requirements (like dynamic nested `with` blocks)", "Safely executes the `__exit__` method of every pushed resource in reverse order, even if exceptions occur"], ["Exit stack is when the server crashes and prints a stack trace before exiting"]),
    ("B63_5_10", "diagnose", "hard", "debugging", ["Context Managers"], "You write a custom Context Manager to manage database transactions: `def __exit__(self, exc_type, exc_val, traceback): self.db.rollback(); return True`. A developer uses it, but when a critical `ValueError` occurs inside the `with` block, the application continues running silently, leading to catastrophic data corruption. Why?", "The bug is `return True` in the `__exit__` method. By Python specification, if `__exit__` returns `True`, it instructs the interpreter to completely swallow and suppress the exception that occurred inside the `with` block. The program execution simply moves to the next line of code outside the `with` block as if no error ever happened. The developer intended to rollback on failure, but accidentally suppressed the critical error. `__exit__` should only return `True` if the context manager is explicitly designed to handle and neutralize the error (like `contextlib.suppress`). Otherwise, it should return `False` or `None` so the exception propagates.", ["Returning `True` from `__exit__` instructs Python to silently suppress any exception thrown inside the `with` block", "This caused critical business-logic exceptions to vanish, allowing the program to continue in a corrupted state", "Fix: Always return `False` or `None` in `__exit__` unless intentionally building an error-swallowing manager"], ["The developer forgot to type 'raise Exception' in the block"]),
    ("B63_5_11", "implement", "medium", "implement", ["Context Managers"], "How do you implement an asynchronous Context Manager (`AsyncContextManager`) for an HTTP client session, and why is `yield` used with the `@asynccontextmanager` decorator?", "An async context manager allows awaiting I/O during setup and teardown (`async with session:`). You can implement it by defining `__aenter__` and `__aexit__` classes. However, the more Pythonic way is using `from contextlib import asynccontextmanager`. You write an `async def` function. The code *before* the `yield` statement acts as `__aenter__` (e.g., `session = await aiohttp.ClientSession()`). The `yield session` suspends the generator and hands the session to the `async with` block. The code *after* the `yield` acts as `__aexit__` (e.g., `await session.close()`). You must wrap the `yield` in a `try/finally` block to guarantee the `close()` executes even if the `with` block throws an error.", ["Requires implementing `__aenter__` and `__aexit__` for asynchronous setup/teardown", "Can be vastly simplified using `@asynccontextmanager` and a single `yield` statement", "Must use a `try/finally` block around the `yield` to guarantee resource cleanup if exceptions occur inside the context"], ["You just type 'async' before the word 'with'"]),

    # Python Datetimes & Timezones
    ("B63_5_12", "tradeoff", "hard", "tradeoff", ["Data & Time"], "What is the tradeoff of storing all dates in the database as pure UTC Timestamps versus storing them as 'Wall Time' combined with an explicit IANA Timezone string (e.g., 'America/New_York')?", "Storing purely as UTC (e.g., `1690000000`) is highly performant, standard, and easy to sort. However, the severe tradeoff is Future Ambiguity. If a user schedules a meeting for '10:00 AM New York Time on November 5, 2030', and you convert it to UTC today and store it, you have destroyed their intent. If the government changes Daylight Saving Time (DST) laws in 2028 (which happens constantly), your hardcoded UTC timestamp will now resolve to 9:00 AM or 11:00 AM. Storing 'Wall Time' (`2030-11-05 10:00:00`) PLUS the string `'America/New_York'` ensures that when 2030 arrives, the system dynamically calculates the correct UTC based on the most recent geopolitical timezone laws.", ["UTC Timestamps: Easy to sort and compare, but permanently lock in today's DST rules", "Wall Time + IANA String: Preserves user intent, adapting dynamically to future geopolitical DST law changes", "Tradeoff: Converting future scheduled events to absolute UTC permanently destroys intent and guarantees future bugs if laws change"], ["Wall time means looking at the clock on the wall instead of the computer"]),
    ("B63_5_13", "scenario", "medium", "scenario", ["Data & Time"], "In Python 3.9+, you use the `zoneinfo` module to handle DST transitions. A user creates an event at 1:30 AM in New York on the night DST ends (the clock rolls back from 2 AM to 1 AM). This creates a 'Fold' ambiguity because 1:30 AM physically happens twice. How do you handle this in Python?", "When a local time happens twice due to DST rollback, it is mathematically ambiguous. Python's `datetime` object handles this using the `fold` attribute. If `fold=0`, it represents the *first* occurrence of 1:30 AM (before the rollback, technically EDT). If `fold=1`, it represents the *second* occurrence of 1:30 AM (after the rollback, technically EST). When converting local time to UTC, you must explicitly capture the user's intent or rely on the `fold` attribute to ensure you do not shift the event's actual absolute time by an entire hour.", ["During DST rollback, a single local time (1:30 AM) physically occurs twice", "Python 3 uses the `fold` attribute (`0` or `1`) to explicitly distinguish between the first and second occurrence", "Failing to handle the fold attribute results in absolute UTC timestamps being off by exactly one hour"], ["You just tell the user they can't schedule things at 1:30 AM"]),

    # Logging and Telemetry
    ("B63_5_14", "concept", "medium", "concept", ["Observability"], "In Python's `logging` module, what is the architectural risk of attaching a blocking `SocketHandler` or `SMTPHandler` directly to the Root Logger in a high-throughput web server?", "Python's `logging` module is inherently synchronous. If you attach an `SMTPHandler` (to email errors) or a `SocketHandler` (to send logs to Logstash) directly to the main logger, every single `logger.error()` call will physically block the OS thread while it negotiates the TCP handshake over the network. In a high-traffic web server, this introduces massive network latency to your HTTP responses and can paralyze the application if the logging server slows down. To fix this, you must use a `QueueHandler` and a `QueueListener`, which pushes the log records into an in-memory queue instantly, allowing a background thread to safely process the blocking network calls without choking the main API.", ["Standard logging handlers execute synchronously on the calling thread", "Network handlers (Sockets/SMTP) introduce severe network latency and blocking to the main application flow", "Fix: Use `QueueHandler` to offload log transmission to an asynchronous background thread"], ["The SMTP handler will send too many emails and get marked as spam"]),
    ("B63_5_15", "diagnose", "hard", "debugging", ["Observability"], "Your Python microservice uses `logging` with a custom formatter that relies on `threading.local()` to inject a `request_id` into every log line. You migrate the app from Flask (WSGI) to FastAPI (ASGI). Suddenly, logs from completely different users are being printed with the exact same `request_id`. Why?", "FastAPI is built on `asyncio`. Thousands of concurrent requests are multiplexed onto a SINGLE OS thread. Because `threading.local()` stores data tied to the *thread*, Request A sets the `request_id`, yields to the event loop, and Request B overwrites it. When Request A resumes and logs, it prints Request B's ID. To fix cross-contamination in async Python, you MUST replace `threading.local()` with `contextvars.ContextVar()`. Context variables strictly bind data to the specific async `Task` lifecycle, guaranteeing that each coroutine maintains its own isolated `request_id` regardless of thread switching.", ["`threading.local()` isolates data per OS-thread, not per async task", "In ASGI, thousands of requests share a single thread, causing catastrophic cross-contamination of log metadata", "Fix: Replace `threading.local()` with `contextvars.ContextVar`, which isolates state to the specific asyncio Task"], ["The log file got corrupted on the hard drive"]),

    # Advanced Error Handling
    ("B63_5_16", "implement", "medium", "implement", ["Error Handling"], "How do you implement 'Exception Chaining' in Python (using the `from` keyword), and why is it critical for debugging deeply nested failures?", "When a low-level error occurs (e.g., `psycopg2.OperationalError`), a backend developer usually catches it and raises a domain-level error (`raise DatabaseConnectionError('Failed to connect')`). If they just write `raise DatabaseConnectionError()`, the original stack trace and the actual Postgres error message are completely destroyed and lost forever. By using `raise DatabaseConnectionError() from e`, Python implements Exception Chaining. It preserves the exact original stack trace, attaching it to the new domain exception. When printed, the logs will show 'DatabaseConnectionError... The above exception was the direct cause of the following exception...', providing full diagnostic context.", ["Blindly catching and raising new exceptions destroys the original stack trace and root cause data", "Exception Chaining (`raise NewError from original_error`) explicitly links the exceptions", "Preserves the full diagnostic stack trace for debugging production incidents"], ["Exception chaining is when you throw multiple errors at the same time"]),
    ("B63_5_17", "tradeoff", "hard", "tradeoff", ["Error Handling"], "What is the tradeoff of using Python's `sys.settrace()` or `sys.setprofile()` for global error and performance monitoring in production?", "These functions hook into the very core of the CPython interpreter, executing a callback function for EVERY single line of code, function call, or exception raised anywhere in the entire application. The benefit is absolute, God-mode visibility into the runtime. The severe tradeoff is catastrophic performance degradation. Executing a callback on every line of code will slow down a Python application by 10x to 100x. They are meant exclusively for building debuggers (like `pdb`) and coverage tools, and should NEVER be enabled in a production environment. (For production, use statistical sampling like `py-spy` or explicit APM instrumentation).", ["Provides God-mode visibility into every executed line and function call via CPython hooks", "Tradeoff: Causes catastrophic performance degradation (10x-100x slowdown), instantly killing production throughput", "Should only be used for local debuggers (`pdb`) or coverage analysis, never in production"], ["Sys set trace changes the trace route of the internet packets"]),
    
    # Final Python Language Quirks
    ("B63_5_18", "scenario", "medium", "scenario", ["CPython Internals"], "You have a Python script that reads a 2GB file into memory, processes it, and explicitly calls `del data`. However, you check the Linux `top` command, and the Python process is still consuming 2GB of RAM. You even call `gc.collect()`, but the memory is not released to the OS. Why?", "When you allocate large objects in Python, `pymalloc` handles small objects, but large objects bypass it and use the C standard library `malloc/free`. However, even when Python calls `free()`, the Linux glibc memory allocator often retains the memory pages in its own internal process heap cache rather than returning them instantly to the OS (to speed up future allocations). Furthermore, if any tiny objects were allocated alongside the large data, memory fragmentation prevents the page from being freed. This is normal C/OS behavior. The only way to guarantee the OS gets the RAM back instantly is to process the file in a temporary child process, which naturally flushes all RAM when it terminates.", ["Even when `del` is called and reference counts hit zero, the C/Linux allocator (glibc) caches the freed memory internally", "The OS (`top`/`htop`) still attributes that cached heap memory to the Python process", "Fix: To guarantee memory is freed to the OS instantly, perform massive allocations in a child process that terminates"], ["The del command doesn't actually work in Python 3"]),
    ("B63_5_19", "concept", "medium", "concept", ["Language Quirks"], "What is 'Late Binding' in Python Closures, and why does a list comprehension creating lambda functions (`[lambda: i for i in range(5)]`) return 4 for every function call?", "This is the classic Late Binding closure trap. In Python, variables in closures (like `i` inside the lambda) are NOT evaluated when the function is defined. They are evaluated at the exact moment the function is *executed*. By the time you execute the lambdas, the `for` loop has already finished, and the global variable `i` is permanently set to `4`. Therefore, all 5 lambdas look up `i` and return `4`. To fix this, you must force 'Early Binding' by passing the variable as a default argument to the lambda: `[lambda x=i: x for i in range(5)]`. Default arguments are evaluated strictly at definition time.", ["Closures in Python look up variables by reference at *execution time*, not definition time (Late Binding)", "Because the loop finishes before execution, all closures read the final value of the loop variable", "Fix: Force Early Binding by capturing the variable as a default argument (`lambda x=i: x`)"], ["Late binding is when the server binds to the port after it starts"]),
    ("B63_5_20", "diagnose", "hard", "debugging", ["Language Quirks"], "A developer uses a `set` to deduplicate a list of custom objects: `unique = set(my_objects)`. It works perfectly in local testing. In production, the API randomly crashes with `TypeError: unhashable type`. Why?", "The developer accidentally mutated the custom object (or it contained mutable types like a `list` or `dict`) such that its `__hash__()` method became invalid. A `set` is backed by a Hash Table. In Python, to be placed in a `set` or used as a `dict` key, an object MUST be 'Hashable' (its `__hash__` value must NEVER change during its lifetime). If a class defines `__eq__` but does not define `__hash__`, Python explicitly marks it as unhashable to prevent silent hash collision corruption. If the object contains a list, it is fundamentally unhashable. The developer must ensure the objects are immutable (e.g., using `@dataclass(frozen=True)` or tuples) before putting them in a set.", ["Sets and Dictionaries require elements to be strictly Hashable (their hash value must never change)", "Custom objects that contain mutable fields (lists/dicts) or define `__eq__` without `__hash__` are rejected by Python", "Fix: Ensure the objects are deeply immutable (e.g., Frozen Dataclasses) before using them in sets"], ["Sets are only allowed to contain numbers in Python"]),
    ("B63_5_21", "implement", "medium", "implement", ["Language Quirks"], "How do you implement the `__repr__` versus `__str__` dunder methods correctly, and what is the strict design philosophy separating them?", "The philosophy is: `__str__` is for end-users (human readability); `__repr__` is for developers (debugging and state reconstruction). You implement `__str__` to return a friendly string: `return f\"User {self.name}\"`. You implement `__repr__` to return an unambiguous string that ideally looks exactly like valid Python code required to recreate the object: `return f\"User(id={self.id}, name='{self.name}')\"`. If you log an object inside a list (`print([user])`), Python defaults to calling `__repr__`. If a class only implements `__repr__`, Python will use it as a fallback for `__str__`.", ["`__str__` is designed for friendly, readable output for end-users", "`__repr__` is designed for developers; it should be unambiguous and ideally valid Python syntax to recreate the object", "Lists and debugging tools default to `__repr__`; it acts as the fallback if `__str__` is missing"], ["str is for strings, repr is for integers"]),
    ("B63_5_22", "tradeoff", "hard", "tradeoff", ["Data & Time"], "What is the tradeoff of using Python's `math.isclose()` versus absolute equality (`==`) when writing unit tests for financial calculations?", "Floating point numbers are inherently imprecise in binary (`0.1 + 0.2 == 0.3` evaluates to False). If you use `==` for floats in financial or scientific tests, the tests will randomly fail due to microscopic precision drift at the 16th decimal place. `math.isclose(a, b)` solves this by allowing a relative tolerance (e.g., 1e-09). The severe tradeoff is 'Accumulated Error Masking'. If your algorithm has a fundamental rounding flaw that loses $0.01 per transaction, `isclose` might silently gloss over the error, allowing catastrophic financial loss at scale. For true financial systems, you must never use floats or `isclose`; you must use the `decimal` module or integer cents with absolute `==`.", ["Floats suffer from binary imprecision, making `==` highly brittle in unit tests", "`math.isclose()` uses relative tolerance to forgive microscopic differences", "Tradeoff: Tolerance can silently mask real algorithmic rounding errors, which is catastrophic in financial software (where `Decimal` + `==` is mandatory)"], ["isclose means the server is physically close to the database"]),
    ("B63_5_23", "scenario", "medium", "scenario", ["Type Hinting"], "You use `typing.NewType` to create `UserId = NewType('UserId', int)`. You have a function `def process(uid: UserId):`. During a code review, a developer claims this adds runtime overhead because it instantiates a new class. Are they correct?", "They are completely wrong. `typing.NewType` is a Zero-Runtime-Overhead feature. It does NOT instantiate a new class or wrapper object at runtime. At runtime, `UserId` is mathematically identical to a pure Python `int`, and `UserId(123)` simply returns the integer `123` with zero overhead. `NewType` exists exclusively for the static type checker (`mypy`). It allows `mypy` to enforce that you cannot accidentally pass a regular integer or an `OrderId` into a function expecting a `UserId`, preventing domain logic bugs without paying the CPU penalty of creating Python wrapper classes.", ["`typing.NewType` creates distinct types strictly for the static type checker (`mypy`)", "It has absolute Zero Runtime Overhead; at runtime, it evaluates exactly as the base type (e.g., `int`)", "It prevents domain bugs (mixing `UserId` with `OrderId`) without the CPU penalty of OOP wrappers"], ["NewType makes the variable run in a new thread"]),
    ("B63_5_24", "explain", "hard", "explain", ["Language Quirks"], "Explain why you should never use `assert` statements to enforce security permissions in production Python code (e.g., `assert user.is_admin, 'Access Denied'`).", "The `assert` keyword is purely a debugging and testing tool in Python. By specification, if you run the Python interpreter with the `-O` (Optimize) flag (e.g., `python -O app.py`), the compiler physically strips every single `assert` statement out of the compiled bytecode to improve performance. If your security logic relies on `assert`, running the app in optimized mode will silently erase your security checks, granting instant admin access to every user. You must ALWAYS use explicit `if not user.is_admin: raise PermissionError()` for application logic.", ["`assert` statements are purely for debugging and testing, not control flow", "Running Python with the `-O` (Optimize) flag physically strips all `assert` statements from the bytecode", "Using `assert` for security guarantees a catastrophic bypass if the app is ever run in optimized mode"], ["assert makes the code run aggressively and uses too much CPU"])
]

def run_batch():
    # Load all existing records to do deduplication
    with open(OUT, "r", encoding="utf-8") as f:
        existing = [json.loads(line) for line in f if line.strip()]

    print(f"Loaded {len(existing)} existing records.")
    
    for q in Q:
        if LEAK.search(q[5]) or LEAK.search(q[6]):
            print(f"PROMPT LEAK DETECTED in: {q[5]}")
            sys.exit(1)
            
    existing_texts = [ex["question"] for ex in existing]
    new_texts = [q[5] for q in Q]
    
    vec = TfidfVectorizer(stop_words="english", ngram_range=(1,2))
    all_texts = existing_texts + new_texts
    vec.fit(all_texts)
    
    existing_vecs = vec.transform(existing_texts)
    new_vecs = vec.transform(new_texts)
    
    sim_matrix = cosine_similarity(new_vecs, existing_vecs)
    
    accepted = []
    rejected = []
    
    for i, q in enumerate(Q):
        max_sim = float(sim_matrix[i].max()) if sim_matrix.shape[1] > 0 else 0
        if max_sim > 0.85:
            print(f"REJECTED (Sim: {max_sim:.2f}): {q[5][:50]}...")
            rejected.append(q)
        else:
            accepted.append(q)
            
    print(f"Accepted {len(accepted)} / {len(Q)} questions (Part 5).")
    
    new_records = []
    for q in accepted:
        rec = {
            "primary_role": ROLE,
            "applicable_roles": ["Systems Engineer", "Software Engineer"],
            "primary_skill": q[4][0],
            "secondary_skills": q[4][1:] if len(q[4]) > 1 else [],
            "technology": "Python",
            "topic": q[4][0] if len(q[4]) > 0 else "General",
            "category": "Software Engineering",
            "intent": q[1],
            "difficulty": q[2],
            "question_type": q[3],
            "question": q[5],
            "expected_answer": q[6],
            "evaluation_rubric": {
                "strong_indicators": q[7],
                "weak_indicators": q[8]
            },
            "id": str(uuid.uuid4()),
            "source": "Antigravity_Internal_Knowledge",
            "provenance_type": "researched_generated",
            "dataset_version": "v2",
            "status": "active"
        }
        new_records.append(rec)
        
    with open(OUT, "a", encoding="utf-8") as f:
        for r in new_records:
            f.write(json.dumps(r) + "\n")
            
    # Final audit reporting
    with open(OUT, "r", encoding="utf-8") as f:
        final_existing = [json.loads(line) for line in f if line.strip()]
        
    role_counts = Counter(r["primary_role"] for r in final_existing)
    
    print("\n========================================")
    print("POST-BATCH AUDIT")
    print("========================================")
    print(f"Batch: 63")
    print(f"Target role: {ROLE}")
    print(f"Attempted: 100")
    print(f"Accepted: {len(accepted)}")
    print(f"Rejected: {len(rejected)}")
    print(f"Replacement count: 0")
    print(f"Cumulative total: {len(final_existing)}")
    print(f"{ROLE} total: {role_counts[ROLE]}")
    
    sha256 = hashlib.sha256()
    with open(OUT, 'rb') as f:
        while chunk := f.read(8192):
            sha256.update(chunk)
            
    print(f"\nFinal SHA256: {sha256.hexdigest()}")

if __name__ == "__main__":
    run_batch()
