import asyncio
import json
import os
import re
import sys
import uuid
from collections import Counter

from dotenv import load_dotenv
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
load_dotenv()

from phase4d_diversity_audit import fetch_all_supabase, normalize_text

BACKEND_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_DIR = os.path.join(BACKEND_DIR, "data")
REPORTS_DIR = os.path.join(BACKEND_DIR, "reports")
OUT = os.path.join(DATA_DIR, "interview_question_bank_v2_generated.jsonl")

ROLE = "Full Stack Developer"
VALID_INTENTS = {"fundamentals", "explain", "implement", "tradeoff", "debug", "scenario", "compare",
                 "architecture", "optimize", "diagnose"}
LEAK = re.compile(r"(generate a question|generate \d+ questions|return only json|phase 4c gap plan|"
                  r"generation batch|candidate generation|system prompts|do not proceed|"
                  r"awaiting authorization|minimum target|generation pipeline|"
                  r"batch \d+ generation|expected answer|strong indicator|weak indicator|as an ai|"
                  r"here is the question|\bprompt text\b)", re.I)

def existing_supabase():
    out = []
    for r in asyncio.run(fetch_all_supabase()):
        meta = r.get("metadata", {})
        if meta.get("status") == "inactive":
            continue
        c = r.get("content", "")
        if "### Instruction:" in c and "### Output:" in c:
            q = c.split("### Instruction:")[1].split("### Output:")[0].strip()
            if "write a program" in q.lower() or "implement a function" in q.lower():
                continue
            a = c.split("### Output:")[1].strip()
        elif "**Answer:**" in c:
            q = c.split("**Answer:**")[0].replace("### Technical Interview Question", "").replace("**Question:**", "").strip()
            a = c.split("**Answer:**")[1].strip()
        else:
            q = meta.get("question", c[:200])
            a = meta.get("expected_answer", "")
        if len(set(re.findall(r"[a-z0-9]+", q.lower()))) < 3:
            continue
        out.append((q, a))
    return out

def opening(q, n=3):
    return " ".join(normalize_text(q).split()[:n])

Q = [
    # Bucket 1: END-TO-END OBSERVABILITY & TRACING
    ("B1", "diagnose", "hard", "debugging", ["Observability"], "A user clicks a 'Submit' button on a React frontend. The browser network tab shows the API call took 500ms. However, the backend server's logs claim the request took only 20ms to process. Explain this massive latency discrepancy across the stack.", "This 480ms gap exists in the network and infrastructure layers outside the application code. It is typically caused by: 1. TLS/SSL handshake negotiation and DNS resolution in the browser. 2. Geographic latency (speed of light from user to datacenter). 3. The Reverse Proxy / API Gateway buffering the massive JSON payload before passing it to the backend. 4. HTTP connection overhead. You diagnose this using the browser's Timing API (Waterfall) combined with an Edge Gateway tracing layer.", ["Latency gap is in the network/infrastructure layers, not backend code", "Includes TLS/SSL handshakes, DNS, and geographic network latency", "Includes API Gateway/Load Balancer connection buffering and routing"], ["The backend timer is broken"]),
    ("B1", "architecture", "medium", "architecture", ["Observability"], "How do you architect OpenTelemetry (OTel) to trace a single user interaction end-to-end, from the browser's button click, through the API Gateway, into the microservices, and down to the database query?", "You must implement W3C Trace Context propagation. The frontend generates a unique `traceparent` (Trace ID) when the user clicks the button. It injects this ID into the HTTP headers of the `fetch` request. The API Gateway extracts the header, logs it, and forwards it to the backend microservices. The backend propagates the same Trace ID into its internal logs and database driver. Distributed tracing tools (Jaeger/DataDog) aggregate all spans sharing this single Trace ID into a unified flame graph.", ["Implement W3C Trace Context propagation", "Frontend generates a Trace ID and injects it into HTTP headers", "Backend extracts and propagates the Trace ID to internal logs and DB calls"], ["Use console.log everywhere"]),
    ("B1", "scenario", "medium", "scenario", ["Observability"], "In a distributed trace, you see a request perfectly span from the browser to the backend API, but the trace abruptly 'breaks' and disappears when the backend sends an asynchronous email via Kafka. How do you fix the broken trace?", "The trace broke because asynchronous message queues (like Kafka or RabbitMQ) do not automatically carry HTTP headers. To fix this, you must explicitly inject the OpenTelemetry Trace Context (Trace ID and Span ID) into the Kafka message's *metadata headers*. The worker service consuming the Kafka message must be configured to extract those specific headers and resume the trace context before executing the email logic.", ["Traces break over async queues because HTTP headers are lost", "Must explicitly inject Trace Context into the Kafka message headers", "The worker must extract the headers and resume the trace"], ["Kafka does not support tracing"]),
    ("B1", "tradeoff", "hard", "tradeoff", ["Observability"], "What is the tradeoff between 'Head-based Sampling' and 'Tail-based Sampling' in full-stack distributed tracing, particularly regarding intermittent frontend UI errors?", "Head-based sampling makes the 'keep or drop' decision at the very beginning of the request (e.g., in the browser or gateway), randomly keeping only 1% of traces. It uses minimal CPU/memory, but you will permanently lose 99% of rare intermittent frontend errors. Tail-based sampling collects 100% of traces in memory and makes the decision at the *end* of the transaction. It guarantees rare errors (500s or timeouts) are kept, but requires massive memory buffers and expensive collector infrastructure.", ["Head-based: Decides at the start (1% random), uses low memory, but loses rare errors", "Tail-based: Decides at the end, guarantees errors are captured, but uses massive memory", "Tail-based is required to reliably debug intermittent full-stack errors"], ["Head-based samples the HTML head, Tail-based samples the footer"]),
    ("B1", "diagnose", "medium", "debugging", ["Observability"], "A complex React page loads slowly. You look at a distributed trace and see the backend API responds instantly, but the trace shows a 2-second gap between the API response and the next UI render span. What is happening in the frontend?", "The 2-second gap is entirely client-side CPU execution. The browser received the JSON payload quickly, but the frontend JavaScript thread is completely blocked. This is typically caused by executing heavy synchronous data transformations (e.g., massive array `.map()` or `.reduce()`), attempting to render thousands of DOM nodes simultaneously without virtualization, or a severe React re-render cascade. The solution is Web Workers, pagination, or list virtualization.", ["Gap is caused by client-side JavaScript CPU blocking", "Frontend is executing heavy synchronous data transformations or massive DOM updates", "Fix via Web Workers, virtualization, or optimizing React re-renders"], ["The JSON payload got lost in the wires"]),
    ("B1", "architecture", "easy", "architecture", ["Observability"], "When migrating from legacy unstructured logging to modern distributed tracing, why do we replace custom 'Correlation IDs' with standard 'Trace IDs'?", "Legacy Correlation IDs were often proprietary, ad-hoc HTTP headers generated by developers (e.g., `X-My-App-Request-ID`) that didn't propagate cleanly across third-party tools, databases, or service meshes. Standard 'Trace IDs' (specifically W3C Trace Context) are an industry-wide open standard. Modern frameworks, load balancers, and observability tools automatically parse, inject, and propagate W3C Trace Context without requiring manual string-passing in code.", ["W3C Trace Context is an industry-wide standard", "Proprietary Correlation IDs don't propagate automatically through third-party tools", "OTel/Standard Trace IDs are automatically parsed and propagated by modern frameworks"], ["Trace IDs are integers, Correlation IDs are strings"]),
    ("B1", "optimize", "medium", "optimize", ["Observability"], "How do you leverage High-Cardinality attributes in OpenTelemetry to diagnose a performance issue affecting only one specific enterprise customer in a multi-tenant SaaS application?", "High-Cardinality attributes have millions of unique possible values (like `tenant_id`, `user_id`, or `order_id`). By appending `tenant_id=AcmeCorp` to the root OTel Span, you can filter your entire observability dashboard to *only* show traces, latency metrics, and database queries for that specific customer. This isolates the noisy-neighbor or data-skew problem causing their slowness without getting lost in global aggregate metrics.", ["High-Cardinality attributes have millions of unique values (e.g., tenant_id)", "Append tenant_id to the root span", "Allows filtering dashboards/traces to isolate that specific customer's traffic"], ["You cannot store IDs in traces due to GDPR"]),
    ("B1", "scenario", "hard", "scenario", ["Observability"], "In a Next.js application, a user request hits a Server-Side Rendered (SSR) page, which then makes client-side API calls. In your tracing tool, you see two completely disconnected traces instead of one unified flow. Why?", "The SSR execution happens in the Node.js backend environment, generating its own Root Trace ID. When the HTML is sent to the browser, the client-side React hydration starts a brand new lifecycle with a completely different Trace ID for subsequent `fetch` calls. To unify them, the SSR backend must inject its Trace ID directly into the HTML payload (e.g., via a `<meta>` tag or global window object), and the client-side tracer must extract it and use it as the parent trace for subsequent API calls.", ["SSR happens in Node.js (generating one Trace ID), client-side generates a new one", "Must inject the SSR Trace ID into the HTML payload (meta tag / window object)", "Client-side tracer must extract and resume the SSR parent trace"], ["Next.js blocks all tracing for security"]),
    ("B1", "architecture", "medium", "architecture", ["Observability"], "What is the architectural purpose of Real User Monitoring (RUM) compared to Backend APM when diagnosing end-to-end full stack reliability?", "Backend APM only sees traffic that successfully reaches your servers. It is completely blind to failures in the 'last mile'. If a CDN fails, a DNS lookup times out, a third-party ad script blocks the main thread, or a JavaScript runtime error crashes the UI before an API call is even made, the backend logs show a 100% success rate while users see a blank white screen. RUM instruments the browser directly to capture these pure client-side failures and actual user-perceived performance metrics (Core Web Vitals).", ["Backend APM is blind to client-side crashes, DNS failures, and CDN issues", "RUM instruments the browser to capture actual user-perceived performance (Core Web Vitals)", "RUM captures JS runtime errors before API calls are made"], ["RUM monitors user webcam activity"]),
    ("B1", "diagnose", "easy", "debugging", ["Observability"], "A user complains that a database-driven dashboard takes 10 seconds to load. You check the Database slow query logs, and the maximum query time is 50ms. Where else in the stack must you investigate?", "You must investigate the entire chain outside the database: 1. Frontend N+1 API calls (the UI is making 200 sequential fast requests instead of 1). 2. Backend ORM N+1 queries (the backend issues 200 fast DB queries sequentially). 3. Massive JSON payload serialization in the backend or parsing in the frontend. 4. Network latency/bandwidth constraints downloading a massive payload. 5. Client-side rendering bottlenecks (DOM thrashing).", ["Frontend N+1 API calls (sequential waterfall)", "Backend ORM N+1 queries", "Massive payload serialization, network download, or DOM rendering bottlenecks"], ["The database is lying in its logs"]),

    # Bucket 2: B2B MULTI-TENANCY & ISOLATION
    ("B2", "architecture", "hard", "architecture", ["Authentication", "Multi-Tenancy"], "You are building a B2B SaaS application. Customer A requires login via Okta (SAML), Customer B requires Microsoft Entra ID (OIDC), and smaller customers use standard email/password. Detail the architecture to handle this SSO routing cleanly across the stack.", "You must implement an Identity Broker or a 'Home Realm Discovery' flow. The frontend login page only asks for the `email` address initially. The BFF/Backend looks up the email domain (e.g., `@customerA.com`) in a tenant configuration database. It then returns a redirect instruction. The frontend (or backend proxy) dynamically redirects the user to their specific Enterprise IdP (Okta/Entra). Upon successful auth, the IdP redirects back to the backend, which validates the SAML/OIDC assertion, generates a standard internal JWT containing the `tenant_id`, and issues it to the frontend.", ["Home Realm Discovery: Ask for email first to determine tenant domain", "Backend looks up tenant config and redirects to specific IdP (Okta/Entra)", "Backend validates assertion and issues a unified internal JWT with `tenant_id`"], ["Build 50 different login pages for each customer"]),
    ("B2", "diagnose", "hard", "debugging", ["Multi-Tenancy"], "In a multi-tenant React/Node application, a user from Tenant A suddenly sees a dashboard containing Tenant B's financial data. You verify that the authorization logic in the database is perfect. What cross-layer caching disaster caused this?", "This is a Tenant Cache Poisoning / Cross-Tenant Leak. A caching layer (like a CDN, Apollo GraphQL cache, or Redis in the BFF) cached the API response based *only* on the URL path (e.g., `/api/dashboard/financials`). Because the cache key omitted the `tenant_id` or `user_id`, the first user to request the data (Tenant B) populated the global cache. When Tenant A hit the exact same URL, the cache blindly returned Tenant B's data, completely bypassing the backend database authorization logic.", ["Tenant Cache Poisoning / Cross-Tenant Leak", "Cache key relied only on the URL, omitting the `tenant_id` or `user_id`", "Cache blindly returned the first tenant's data, bypassing database auth"], ["The database confused the letters A and B"]),
    ("B2", "scenario", "medium", "scenario", ["Multi-Tenancy"], "A massive 'Whale' tenant runs an unoptimized end-of-month report. The database CPU spikes to 100%, causing the UI to time out and crash for all 500 other smaller tenants. How do you architecturally solve this 'Noisy Neighbor' problem?", "You must implement Tenant Isolation and QoS (Quality of Service) controls. 1. Implement Tenant-Scoped Rate Limiting at the Edge/Gateway to prevent one tenant from monopolizing API threads. 2. Architecturally decouple analytical reads (reports) from the primary OLTP database (using a Read Replica). 3. Impose strict timeout budgets and row-scan limits on the backend queries. 4. Ultimately, move massive whale tenants to physically isolated database shards/compute pools.", ["Tenant-Scoped Rate Limiting at the Edge/Gateway", "Decouple heavy analytical reads using a Read Replica", "Impose strict query timeouts/limits, or physically isolate the whale tenant"], ["Tell the other 500 tenants to stop using the app at the end of the month"]),
    ("B2", "architecture", "medium", "architecture", ["Multi-Tenancy"], "When architecting Row-Level Security (RLS) in a Postgres database for a multi-tenant application, how does the frontend securely prove its tenant identity all the way down to the database engine?", "The frontend holds an HttpOnly cookie or JWT containing the `tenant_id` claim (cryptographically signed by the auth server). The frontend sends this to the backend API. The backend validates the signature, extracts the `tenant_id`, and immediately executes a session configuration command (e.g., `SET app.current_tenant = '123'`) on the database connection pool before executing any queries. The Postgres RLS policies then strictly enforce that all `SELECT/UPDATE` operations only return rows matching `app.current_tenant`.", ["JWT contains a cryptographically signed `tenant_id` claim", "Backend extracts the claim and sets a session variable on the DB connection", "Postgres RLS policies evaluate the session variable to restrict row access"], ["The frontend writes the SQL query directly"]),
    ("B2", "tradeoff", "hard", "tradeoff", ["Multi-Tenancy"], "What is the tradeoff between implementing multi-tenancy via a 'Shared Database, Shared Schema' (distinguished only by a `tenant_id` column) versus a 'Database-per-Tenant' architecture?", "Shared Schema is highly efficient, cheap to scale, and allows instant deployment of schema changes across all customers, but it requires flawless application-level code (or RLS) to prevent catastrophic data leaks, and suffers from noisy-neighbor problems. Database-per-Tenant offers absolute physical security isolation (required by some enterprise compliance) and eliminates noisy neighbors, but the tradeoff is astronomical infrastructure costs, connection pooling exhaustion, and massive operational complexity when rolling out a schema migration across 5,000 separate databases.", ["Shared Schema: Cheap, easy schema migrations, but high risk of data leaks and noisy neighbors", "DB-per-Tenant: Absolute physical isolation, no noisy neighbors", "DB-per-Tenant tradeoff: Astronomical cost, connection exhaustion, complex migrations"], ["Shared schema uses Excel, DB-per-tenant uses Access"]),
    ("B2", "diagnose", "medium", "debugging", ["Security"], "A user from Tenant A discovers they can view Tenant B's private PDF report by manually changing the URL in the React frontend from `/reports/101` to `/reports/102`. What full-stack security failure occurred?", "This is an Insecure Direct Object Reference (IDOR) combined with missing backend tenant validation. The frontend correctly updated the view based on the URL parameter, but the Backend API blindly queried the database for `report_id = 102` without verifying ownership. The backend must mathematically verify that `report_id = 102` belongs to the `tenant_id` extracted from the authenticated user's JWT before returning the data.", ["Insecure Direct Object Reference (IDOR)", "Backend failed to validate ownership of the requested resource", "Backend must verify the resource belongs to the JWT's `tenant_id`"], ["The URL was not encrypted via SSL"]),
    ("B2", "architecture", "medium", "architecture", ["Multi-Tenancy"], "Your SaaS allows enterprise customers to define their own custom data fields for the 'Employee' object (e.g., Tenant A wants `shoe_size`, Tenant B wants `zodiac_sign`). How do you architect this from the UI form down to the relational database?", "You can use the Entity-Attribute-Value (EAV) pattern or a JSONB column. A JSONB column is standard modern practice. The backend database has a `custom_fields` JSONB column. The API dynamically serves a configuration payload to the frontend, telling React how to render the dynamic form inputs based on the current tenant's settings. When the user submits, React serializes the dynamic inputs into a JSON object, and the backend stores it in the Postgres JSONB column, allowing indexable, schema-less flexibility per tenant.", ["Use a JSONB column in the relational database (e.g., Postgres)", "API serves a dynamic UI configuration payload based on tenant settings", "Frontend serializes dynamic inputs into a JSON object stored in JSONB"], ["Create 10,000 empty columns in the database just in case"]),
    ("B2", "scenario", "hard", "scenario", ["Authentication"], "An enterprise IT admin completely disables a malicious employee's account in their central Active Directory (SAML IdP). However, the employee is still actively clicking around and modifying data in your React application 4 hours later. Why did this happen?", "This occurs because your application is relying on a long-lived, stateless JWT session. While the employee was disabled at the IdP (Okta/AD), your backend API does not synchronously check the IdP on every single click. It merely cryptographically validates the JWT signature, which is still valid until its 24-hour expiration time. To fix this, you must implement short-lived JWTs (e.g., 15 minutes) with a Refresh Token rotation, or maintain a centralized blacklist/revocation check in the backend for critical actions.", ["Relied on long-lived, stateless JWTs without revocation checks", "Backend API doesn't know the IdP disabled the user until the JWT expires", "Fix via short-lived JWTs + Refresh Tokens or a backend blacklist cache"], ["The employee hacked the mainframe"]),
    ("B2", "architecture", "easy", "architecture", ["Multi-Tenancy"], "Why is it an anti-pattern to hardcode tenant-specific logic (e.g., `if tenant == 'IBM' then display_blue_button()`) directly into the frontend React components?", "Hardcoding tenant logic creates an unmaintainable, brittle codebase that requires a full engineering deployment every time a new customer is onboarded or changes their preferences. It also bloats the Javascript bundle for everyone. The correct architecture is Configuration-Driven UI. The frontend fetches a tenant configuration JSON payload from the API on boot, which contains the theming, feature flags, and access rules, dynamically driving the UI rendering.", ["Creates an unmaintainable, brittle codebase requiring constant deployments", "Bloats the JS bundle for all users", "Must use Configuration-Driven UI driven by a backend JSON payload"], ["React cannot process if statements"]),
    ("B2", "tradeoff", "medium", "tradeoff", ["Multi-Tenancy"], "When implementing Multi-Tenant Feature Flags, what is the tradeoff between evaluating the flags on the Frontend versus evaluating them on the Backend?", "Evaluating on the Frontend allows instant, snappy UI changes (hiding/showing tabs) without network latency, but requires sending the entire ruleset payload to the browser, exposing upcoming unreleased features to curious users (security/PR risk). Evaluating on the Backend prevents data leakage and ensures bulletproof enforcement, but adds latency to API calls. The standard architecture is hybrid: Frontend handles cosmetic UI toggles via a minimal payload, while the Backend strictly re-verifies the flag before executing any actual database logic.", ["Frontend: Snappy UI, but exposes unreleased feature configurations to the browser", "Backend: Secure enforcement, but adds latency", "Hybrid: UI handles cosmetic toggles, Backend strictly enforces logic access"], ["Frontend feature flags crash the CSS"]),

    # Bucket 3: BFF, EDGE & API GATEWAYS
    ("B3", "explain", "medium", "concept", ["Architecture"], "What is the 'Backend-For-Frontend' (BFF) pattern, and what specific performance problem does it solve for modern Single Page Applications (SPAs)?", "The BFF pattern places a lightweight backend service (often Node.js or GraphQL) directly in front of internal microservices, tailored specifically for one client type (e.g., Web vs Mobile). It solves the 'Over-fetching' and 'Network Waterfall' problems. Instead of a mobile app making 10 high-latency REST calls to 10 different microservices over a slow cellular network, it makes a single call to the BFF. The BFF aggregates, filters, and formats the data from the 10 microservices over a lightning-fast internal datacenter network, returning one optimized JSON payload.", ["BFF aggregates multiple microservice calls into one optimized response", "Solves Network Waterfalls and Over-fetching on high-latency client networks", "Leverages fast internal datacenter networks for complex compositions"], ["BFF stands for Best Friends Forever"]),
    ("B3", "architecture", "hard", "architecture", ["Security", "Architecture"], "Storing JWTs in `localStorage` in the browser is vulnerable to XSS. Storing them in `HttpOnly` cookies makes API requests to multiple different cross-domain microservices extremely difficult due to CORS. How does a BFF solve this security vs architecture conflict using the 'Token Handler' pattern?", "The BFF sits on the exact same domain as the frontend (e.g., `app.example.com` and `app.example.com/api`). The frontend authenticates, and the BFF issues a strict, secure `HttpOnly`, `SameSite` session cookie. The browser automatically sends this secure cookie to the BFF, completely safe from XSS. The BFF securely translates/exchanges this cookie into a rich JWT, and passes the JWT via standard `Authorization: Bearer` headers to the internal microservices on the private network. The frontend never touches the JWT.", ["Frontend relies entirely on secure HttpOnly, SameSite cookies to the BFF", "Cookie prevents XSS attacks and simplifies CORS", "BFF translates the cookie into a JWT and proxies it to internal microservices"], ["The BFF encrypts the JWT into a JPEG image"]),
    ("B3", "tradeoff", "medium", "tradeoff", ["Edge Architecture"], "What is the tradeoff between caching an API response in the Browser (via `Cache-Control` headers) versus caching it at the Edge (CDN)?", "Browser Caching is perfectly tailored to an individual user, completely eliminates network latency, and works offline, but is difficult to instantly invalidate (stale data). Edge/CDN Caching is incredibly fast, instantly invalidatable globally (via Purge commands), and protects the origin backend from traffic spikes (Cache Stampedes) across millions of users, but it cannot easily cache highly personalized user data without complex Edge Computing logic (e.g., Cloudflare Workers).", ["Browser: Zero network latency, offline support, but hard to invalidate", "Edge/CDN: Protects origin from spikes, instantly invalidatable globally", "Edge cannot easily cache highly personalized, logged-in data"], ["Browser caches use RAM, Edge caches use CD-ROMs"]),
    ("B3", "scenario", "hard", "scenario", ["Architecture"], "Your SPA needs to upload massive 5GB video files. Currently, the browser uploads the file to the BFF, which holds it in memory, then uploads it to an S3 bucket. During uploads, the BFF crashes due to OOM (Out of Memory). How do you re-architect this cross-layer flow?", "You must implement the 'Pre-Signed URL' (or Direct Upload) pattern. The browser makes a tiny API call to the BFF requesting an upload token. The BFF uses its secure AWS credentials to generate a short-lived 'Pre-Signed URL' for S3 and returns it to the UI. The browser then uploads the massive 5GB file *directly* to the S3 bucket using that URL, completely bypassing the BFF. Once S3 succeeds, the browser notifies the BFF to update the database.", ["Implement Pre-Signed URLs / Direct Upload pattern", "Browser requests a temporary secure upload URL from the BFF", "Browser uploads massive file directly to S3, bypassing BFF memory entirely"], ["Buy 1000GB of RAM for the BFF"]),
    ("B3", "diagnose", "medium", "debugging", ["Edge Architecture"], "Your frontend app generates absolute URLs for emails (e.g., password resets) by inspecting the incoming HTTP request. In development, the URLs correctly start with `http://localhost`. In production, the generated URLs incorrectly start with `http://example.com` instead of `https://`. What Edge Gateway configuration is missing?", "The SSL/TLS connection was terminated at the Load Balancer or Edge Gateway. The Load Balancer then proxied the request to your backend over internal, unencrypted HTTP. Because the backend explicitly saw an HTTP connection, it generated an `http://` link. The Gateway must be configured to pass the `X-Forwarded-Proto: https` header, and the backend framework must be configured to trust that proxy header when generating absolute URLs.", ["SSL Termination occurred at the Load Balancer/Gateway", "Backend sees internal HTTP and generates the wrong scheme", "Must configure Gateway to pass `X-Forwarded-Proto: https` and backend to trust it"], ["The browser forgot the S in HTTPS"]),
    ("B3", "architecture", "medium", "architecture", ["Architecture"], "A non-critical backend recommendation service goes down. The BFF waits 30 seconds for it, causing the entire frontend UI to lock up on a white loading screen. How do you re-architect the BFF to handle this?", "You must implement a 'Circuit Breaker' and aggressive timeouts in the BFF. If the recommendation service fails or takes longer than 200ms, the BFF should instantly break the circuit, catch the error, and return a graceful fallback response (e.g., an empty list or a static list of trending items) alongside the rest of the critical payload. The frontend UI renders immediately with the fallback data instead of crashing or hanging.", ["Implement a Circuit Breaker and strict timeouts in the BFF", "Fail fast and return a graceful fallback payload (e.g., static trending items)", "Allows the UI to render the critical path without hanging"], ["Delete the recommendation service"]),
    ("B3", "tradeoff", "medium", "tradeoff", ["Architecture"], "What is the tradeoff of using a GraphQL BFF compared to a standard REST BFF?", "GraphQL BFFs drastically reduce frontend Over-Fetching (fetching data you don't need) and Under-Fetching (requiring multiple waterfall requests) by allowing the UI to declare exactly what data it wants in a single query. The tradeoff is massive backend complexity: GraphQL is highly susceptible to deep, recursive N+1 database query problems, is very difficult to cache at the CDN/Edge layer (since everything is a `POST` to a single endpoint), and introduces complex security risks (query depth attacks).", ["GraphQL: Eliminates over/under-fetching, allows UI to dictate shape in one call", "Tradeoff: Severe N+1 query risks, complex to secure (query depth)", "Tradeoff: Difficult to cache at the CDN/Edge layer because of POST semantics"], ["GraphQL uses SQL, REST uses JSON"]),
    ("B3", "explain", "easy", "concept", ["Edge Architecture"], "In modern full-stack deployments (like Next.js or Nuxt), what is the architectural difference between Edge Runtime and Node.js Serverless Functions?", "Node.js Serverless Functions run in a specific geographic region (e.g., `us-east-1`), require a full Node.js cold boot (often 1-2 seconds), and have full access to native filesystem/OS APIs. Edge Runtime functions are deployed globally to CDN nodes (Points of Presence) within milliseconds of the user. They use a stripped-down V8 isolate environment (like Cloudflare Workers). They boot almost instantly (0ms cold starts) but have severe limitations (no native Node APIs, restricted execution time, limited database driver support).", ["Node Serverless: Runs in one region, full OS access, slow cold starts", "Edge Runtime: Deployed globally to CDNs, stripped-down V8 engine, 0ms cold start", "Edge is extremely fast but cannot use heavy native libraries or standard DB drivers"], ["Edge runs on the user's phone, Serverless runs in space"]),
    ("B3", "scenario", "hard", "scenario", ["Architecture"], "Your company has a massive legacy monolith API. You are building a brand new React SPA that requires data formatted completely differently. Modifying the fragile monolith is prohibited. What pattern do you use?", "You implement the 'Strangler Fig' pattern combined with a BFF (Backend-For-Frontend) or API Gateway layer. The new SPA talks exclusively to the new BFF. The BFF acts as an anti-corruption layer, taking the clean new requests, translating them into the ugly, complex requests required by the legacy monolith, and reshaping the ugly response back into clean JSON for the SPA. Over time, you slowly migrate logic out of the monolith into new microservices behind the BFF, entirely transparent to the SPA.", ["Use a BFF as an Anti-Corruption Layer (Strangler Fig pattern)", "BFF translates clean SPA requests into ugly legacy monolith requests", "Allows slow migration of backend logic without breaking the frontend API contract"], ["Write a python script to hack the monolith"]),
    ("B3", "diagnose", "medium", "debugging", ["Edge Architecture"], "You deploy a new frontend build, but users are complaining that the app looks broken and CSS is missing. You check the CDN logs and see aggressive caching. What standard deployment practice prevents stale asset caching across deployments?", "The deployment failed to use 'Asset Fingerprinting' (or Cache Busting). In modern build tools (Webpack/Vite), static assets must be generated with a unique content hash in the filename (e.g., `main.a3f9b2.js`). The CDN is configured to aggressively cache these files indefinitely (`Cache-Control: immutable, max-age=31536000`). The `index.html` file, however, is NEVER cached (`no-cache`). When a user requests the new `index.html`, it requests the brand new fingerprinted JS/CSS files, completely bypassing the stale CDN cache.", ["Failed to use Asset Fingerprinting / Content Hashing (e.g., main.hash.js)", "Assets should be cached indefinitely, but index.html must NEVER be cached", "New index.html forces the browser to fetch the new unique filenames"], ["The CSS was written in French"]),

    # Bucket 4: END-TO-END RELIABILITY & IDEMPOTENCY
    ("B4", "architecture", "hard", "architecture", ["Reliability"], "A user clicks 'Submit Payment'. The UI shows a loading spinner, but the user's internet drops for a second. The UI receives a `Network Error` and allows the user to click 'Submit' again. The user is charged twice. How do you architect cross-layer Idempotency to prevent this?", "You must generate an 'Idempotency Key' (e.g., a UUID v4) on the *Frontend* the moment the form is opened or the button is clicked. The UI passes this exact key in the HTTP header or payload to the backend. The backend checks a fast cache/database (e.g., Redis). If it has seen the key before, it skips the payment logic and immediately returns the previously cached success response. The UI can retry the exact same request safely as many times as it wants.", ["Generate an Idempotency Key (UUID) on the Frontend", "Backend checks if the key was already processed before executing logic", "Allows safe, infinite network retries from the UI without double charging"], ["Disable the submit button forever"]),
    ("B4", "tradeoff", "medium", "tradeoff", ["Reliability"], "What is the danger of configuring the Frontend UI (e.g., Axios) to automatically retry failed requests on a `504 Gateway Timeout`?", "A `504 Gateway Timeout` simply means the Load Balancer gave up waiting for the backend. It does *not* mean the backend failed. The backend API might still be slowly processing the database transaction and is about to commit it. If the UI blindly retries without an Idempotency Key, it sends a duplicate request. The backend will process both, resulting in duplicate data creation, double charges, or race conditions. Retries on `POST/PUT` are highly dangerous without explicit idempotency.", ["504 means the gateway timed out, but the backend is likely still executing the write", "Blind UI retries cause duplicate transactions and corrupted data", "Only safe to retry if the request is idempotent (GET) or uses an Idempotency Key"], ["The timeout will melt the server CPU"]),
    ("B4", "scenario", "hard", "scenario", ["Reliability"], "In a distributed transaction, the backend successfully charges a credit card via Stripe, but the subsequent database `INSERT` for the order fails. The backend returns a `500` to the UI. How do you ensure data consistency across these external layers?", "You cannot use a standard database transaction because Stripe is an external system. You must implement the 'Saga Pattern' or rely on asynchronous reconciliation. The backend must immediately trigger a compensating transaction (e.g., calling Stripe's refund API) if the database insert fails. Alternatively, use a 'Transactional Outbox': save the order in a `PENDING` state to the DB *first* within a local transaction, and only then call Stripe via a reliable background worker with retries.", ["Requires Compensating Transactions (Saga pattern) to undo external calls", "Or use a Transactional Outbox: Save to DB in PENDING state first", "Cannot wrap external APIs in local database transactions"], ["Call the user and ask them for a refund"]),
    ("B4", "diagnose", "medium", "debugging", ["Reliability"], "A React UI optimistically adds a new comment to a list instantly for UX. However, immediately after, the list flickers and the comment vanishes, only to reappear 5 seconds later. What cross-layer inconsistency caused this?", "This is a Read-After-Write inconsistency caused by database replication lag. The UI optimistically updated its state. The backend successfully wrote the comment to the Primary Database and returned `200 OK`. The UI then re-fetched the comment list to ensure it was in sync. However, the `GET` request was routed to a Read-Replica database that hadn't synchronized the new comment yet. The UI replaced its optimistic state with the stale backend state. Fix by routing immediate subsequent reads to the Primary.", ["Read-After-Write inconsistency due to database replication lag", "UI re-fetched data from a stale Read-Replica immediately after writing", "Fix by delaying the re-fetch or routing immediate reads to the Primary DB"], ["React crashed and restarted"]),
    ("B4", "architecture", "medium", "architecture", ["Reliability"], "Your frontend has a 5-second timeout for an API call. Your backend database query takes 15 seconds. Even though the user has already seen a timeout error and left the page, the database continues grinding for 10 more seconds. How do you optimize this cross-layer waste?", "You must implement Context Cancellation (Timeout Propagation). When the frontend closes the connection or times out at the Gateway, the Gateway must signal the backend API (e.g., dropping the TCP connection). The backend framework must listen for request cancellation (e.g., Go Contexts, Node `AbortController`), immediately halt its execution, and pass a cancellation signal down to the database driver to explicitly `KILL` the running SQL query, saving massive CPU waste.", ["Implement Context Cancellation / Timeout Propagation", "Backend must detect the closed HTTP connection from the dropped UI", "Backend explicitly propagates cancellation to the database to KILL the query"], ["Buy a faster database"]),
    ("B4", "scenario", "hard", "scenario", ["Reliability"], "Two users open the exact same Wiki document in a React rich-text editor. User A changes the title. User B changes the body. Both click save. User B's save overwrites and destroys User A's title change. How do you architecturally prevent this 'Lost Update'?", "This requires Optimistic Concurrency Control (OCC). When the UI fetches the document, the backend includes a `version_number` (e.g., `v=1`). Both User A and B hold `v=1`. User A saves first, passing `v=1` to the backend. The backend updates the DB and increments to `v=2`. When User B saves, they pass `v=1`. The backend detects the mismatch (`1 != 2`), rejects the write with a `409 Conflict`, and forces User B's UI to merge the latest changes before trying again.", ["Implement Optimistic Concurrency Control (OCC)", "Include a `version_number` or ETag in the UI payload", "Backend rejects writes if the UI's version doesn't match the database's version (409 Conflict)"], ["Just tell them not to edit at the same time"]),
    ("B4", "diagnose", "medium", "debugging", ["Performance"], "A frontend list view of 50 users is extremely slow. The network tab shows exactly 51 API calls (1 call to `/users`, and 50 concurrent calls to `/users/{id}/avatar`). What is this problem, and how do you solve it?", "This is the classic N+1 Query Problem manifesting at the Network layer (Over-fetching). The React component maps over the 50 users, and each child component independently fetches its own avatar data. The solution is to aggregate the data at the Backend/BFF layer. The backend `/users` endpoint should perform a SQL `JOIN` or batch resolution, and return the avatar data embedded directly inside the initial JSON list payload, reducing the network waterfall to exactly 1 call.", ["N+1 Query Problem at the Network API layer", "Child components independently fetch data in a waterfall", "Fix by aggregating data in the BFF/Backend (e.g., SQL JOIN) and returning one payload"], ["The browser can only make 10 requests at a time"]),
    ("B4", "architecture", "medium", "architecture", ["Reliability"], "You need to deploy a highly destructive database schema change (dropping a table) and a new frontend that no longer relies on it. Why is it impossible to do this safely in a single deployment?", "You cannot control when the user refreshes their browser. If you deploy the backend and drop the table, users who currently have the old React application loaded in their browser tabs will click buttons that hit the old API endpoints, resulting in catastrophic `500 Server Errors`. You must use a Multi-Phase Rollout: 1. Deploy the new frontend/API side-by-side. 2. Wait for old sessions to bleed out or force a hard UI reload. 3. Drop the table days later.", ["Cannot control when users refresh the browser (old UI code remains active)", "Old UI will call missing API endpoints/tables, causing catastrophic crashes", "Requires a Multi-Phase Rollout (Expand and Contract pattern)"], ["The database refuses to delete tables during business hours"]),
    ("B4", "tradeoff", "easy", "tradeoff", ["Architecture"], "When designing real-time UI updates, what is the tradeoff between WebSockets and Server-Sent Events (SSE)?", "WebSockets provide true full-duplex, bi-directional communication, excellent for highly interactive apps like chat or multiplayer games, but are complex to scale, require load balancer tuning, and don't automatically reconnect. Server-Sent Events (SSE) are mono-directional (Server to Client only), perfect for live feeds, stock tickers, or progress bars. SSE operates over standard HTTP, making it vastly easier to scale, traverse firewalls, cache, and it features built-in automatic reconnection.", ["WebSockets: Bi-directional, complex to scale/load-balance, good for chat", "SSE: Mono-directional (Server->Client), operates over standard HTTP", "SSE is vastly easier to scale and features automatic reconnection"], ["WebSockets use UDP, SSE uses TCP"]),
    ("B4", "scenario", "medium", "scenario", ["Reliability"], "A user requests a massive data export. The backend takes 2 minutes to generate the CSV. If the UI simply waits on the HTTP request, it will time out. How do you architect this asynchronous flow?", "You must implement the 'Asynchronous Polling' or 'Webhook' pattern. The UI sends a `POST /export` request. The backend instantly returns a `202 Accepted` with a `job_id`. A background worker (Celery/SQS) generates the CSV. Meanwhile, the UI periodically polls `GET /export/{job_id}/status` every 5 seconds. Once the status is `COMPLETED`, the backend returns the secure download URL to the UI. Alternatively, the backend notifies the UI via a WebSocket when the job finishes.", ["Backend returns a 202 Accepted with a Job ID instantly", "Background worker processes the massive file", "UI polls a status endpoint (or listens via WebSockets) for completion"], ["Make the HTTP timeout 10 minutes in the browser"]),

    # Bucket 5: CROSS-LAYER SECURITY
    ("B5", "compare", "hard", "compare", ["Security"], "Compare the vulnerability risks of storing an authentication token in `localStorage` versus storing it in an `HttpOnly` Cookie.", "Storing in `localStorage` exposes the token directly to Javascript. If the application suffers an XSS (Cross-Site Scripting) attack, malicious scripts can read the token and exfiltrate it to an attacker's server, granting total account takeover. An `HttpOnly` Cookie mathematically hides the token from Javascript, making it immune to XSS theft. However, Cookies are automatically attached by the browser to every request, making the application highly vulnerable to CSRF (Cross-Site Request Forgery) attacks unless explicitly protected via `SameSite` attributes or anti-CSRF tokens.", ["localStorage: Vulnerable to XSS (token theft)", "HttpOnly Cookie: Immune to XSS token theft", "HttpOnly Cookie tradeoff: Highly vulnerable to CSRF without strict protections"], ["localStorage is secure because it is stored locally on the hard drive"]),
    ("B5", "diagnose", "medium", "debugging", ["Security"], "Your backend API receives a POST request to update a user profile. The UI only sends `{\"name\": \"John\"}`. However, a malicious user uses Postman to send `{\"name\": \"John\", \"is_admin\": true}`. The database successfully upgrades the user to admin. What vulnerability is this?", "This is a 'Mass Assignment' (or Over-Posting) vulnerability. The backend framework or ORM blindly took the incoming JSON payload and bound it directly to the database model without explicitly filtering the allowed fields. The backend must enforce a strict allowlist (e.g., DTOs, Pydantic models, or Strong Parameters) to strip out sensitive fields like `is_admin`, `role`, or `password` before the ORM touches the database.", ["Mass Assignment / Over-Posting vulnerability", "Backend ORM blindly binds incoming JSON to the database model", "Must use a strict allowlist (DTOs/Strong Parameters) to strip sensitive fields"], ["The database assumed John was a trustworthy name"]),
    ("B5", "architecture", "hard", "architecture", ["Security"], "A user enters a URL into your frontend UI (e.g., an image URL for an avatar). The UI sends this to the Backend, and the Backend fetches the image to save it to S3. A hacker enters `http://169.254.169.254/latest/meta-data/`. What is this attack, and how do you mitigate it?", "This is a Server-Side Request Forgery (SSRF) attack. The hacker tricked your backend server into making an HTTP request to the internal AWS EC2 metadata endpoint, potentially exfiltrating strict IAM credentials or internal VPC data. To mitigate this, the backend must strictly validate the URL, resolve the DNS, and explicitly deny requests targeting local IP ranges (`127.0.0.1`), private subnets (`10.0.0.0/8`), or cloud metadata IP addresses before making the outbound HTTP request.", ["Server-Side Request Forgery (SSRF)", "Hacker tricks backend into fetching internal/sensitive cloud metadata endpoints", "Mitigate by validating DNS and blocking private/metadata IP ranges"], ["The hacker caused a SQL injection in the image file"]),
    ("B5", "scenario", "medium", "scenario", ["Security"], "You implement a strict form validation schema in your React frontend (using Yup/Zod) that ensures `age` is a positive integer and `password` is at least 8 characters. Is your application secure? Why or why not?", "No, the application is fundamentally insecure. Frontend validation is strictly for User Experience (UX) to provide instant feedback and save network round-trips. It provides absolute zero security. An attacker can completely bypass the browser, open Postman or curl, and send a malicious JSON payload directly to your backend API. You must completely duplicate the exact same validation logic at the Backend layer (the actual trust boundary).", ["Frontend validation is for UX only, it provides ZERO security", "Attackers bypass the browser and hit the API directly (e.g., via Postman/curl)", "Must strictly duplicate and enforce all validation at the Backend API layer"], ["Yes, because React is mathematically immune to hacking"]),
    ("B5", "architecture", "easy", "architecture", ["Security"], "Why does a modern Single Page Application (SPA) using a completely separate API domain (e.g., UI on `app.com`, API on `api.com`) require a CORS preflight `OPTIONS` request?", "CORS (Cross-Origin Resource Sharing) is a strict browser security mechanism designed to prevent malicious websites from making unauthorized background API calls to other domains. Before sending a complex request (like a `POST` with JSON or Auth headers), the browser automatically sends a lightweight `OPTIONS` request (Preflight) to the API. It asks, 'Does this API permit requests from `app.com`?' If the API replies 'Yes', the browser proceeds with the actual `POST`. If 'No', the browser blocks it to protect the user.", ["Browser security mechanism to prevent cross-domain unauthorized requests", "Preflight (OPTIONS) asks the API if the origin domain is permitted", "Browser blocks the actual request if the API rejects the preflight"], ["It checks if the server is awake before sending heavy data"]),
    ("B5", "diagnose", "hard", "debugging", ["Security"], "A Node.js backend receives a JSON payload from a frontend. The hacker manipulated the JSON payload to include `__proto__: { isAdmin: true }`. Suddenly, unrelated users logging in are granted admin privileges. What vulnerability is this?", "This is 'Prototype Pollution'. In Javascript, if you deeply merge an untrusted, malformed JSON payload into an object without sanitizing it, the `__proto__` key overwrites the global `Object.prototype` in the Node.js V8 engine memory. Every single object instantiated globally in the backend suddenly inherits the `isAdmin: true` property. The fix is to use safe deep-merge libraries, freeze prototypes (`Object.freeze`), or instantiate objects with `Object.create(null)`.", ["Prototype Pollution", "Untrusted JSON overwrites the global `Object.prototype` in Node.js memory", "Causes all global objects to suddenly inherit the malicious property"], ["The JSON payload was too large and crashed the memory"]),
    ("B5", "tradeoff", "medium", "tradeoff", ["Security"], "When architecting a secure password reset flow, what is the architectural risk of generating a random Reset Token and storing it directly in the database column as plain text?", "If the database is compromised (e.g., via SQL injection or a leaked backup), the attacker instantly acquires all the active password reset tokens in plain text. They can immediately use them to hijack the accounts. Just like passwords, Reset Tokens must be cryptographically hashed (e.g., SHA-256) before being stored in the database. The API emails the plain-text token to the user, and when the user clicks the link, the backend hashes the incoming token and compares it to the hashed DB column.", ["Leaked database exposes plain-text active reset tokens for instant account hijacking", "Reset Tokens must be cryptographically hashed in the DB, just like passwords", "Email the plain text, but only store the hash"], ["Plain text takes up too much database storage"]),
    ("B5", "scenario", "medium", "scenario", ["Security"], "A user logs into your React app on a public library computer, then clicks 'Log Out' and walks away. You clear the React state, but the next person sits down, hits the browser's 'Back' button, and sees the previous user's sensitive dashboard data. How do you prevent this?", "While clearing the frontend state and destroying the backend session/cookie is correct, the browser heavily cached the sensitive HTML/JSON responses in its local history. To prevent the 'Back Button' exposure, the Backend API must explicitly serve sensitive endpoints with aggressive anti-caching headers: `Cache-Control: no-cache, no-store, must-revalidate`. This forces the browser to re-request the data from the server (which will now return a 401 Unauthorized since the session is gone).", ["Browser cached the sensitive data in local history", "Backend must serve sensitive data with `Cache-Control: no-cache, no-store`", "Forces the browser to re-fetch on 'Back', resulting in a secure 401 Unauthorized"], ["Tell users not to use public computers"]),
    ("B5", "architecture", "hard", "architecture", ["Security"], "You are building a financial dashboard. You need to prevent a user from opening the browser DevTools, finding the API token, and writing a Python script to scrape their own data at 1000 requests per second. Is this possible to fully prevent?", "No, it is fundamentally impossible to fully prevent. If the frontend browser possesses the token and can make the request, a determined user can always extract that token and mimic the request via Python. The browser is an untrusted environment. You cannot trust the client. Instead of attempting impossible client-side obfuscation, you must architect robust Backend defenses: strict Rate Limiting, API abuse detection heuristics, and IP anomaly blocking.", ["Fundamentally impossible: The browser is an untrusted environment", "If the browser can make the request, a script can extract the token and mimic it", "Must rely strictly on Backend defenses (Rate Limiting, Abuse Detection)"], ["Yes, just encrypt the javascript code"]),
    ("B5", "diagnose", "medium", "debugging", ["Security"], "A developer uses the React `dangerouslySetInnerHTML` attribute to render a blog post string fetched directly from the database. A malicious author wrote `<img src=x onerror=alert('Hacked')>` in the post. What happens to the readers?", "This causes a Stored XSS (Cross-Site Scripting) attack. The backend stored the malicious payload in the database. Because the frontend explicitly bypassed React's built-in escaping using `dangerouslySetInnerHTML`, the victim's browser blindly executes the injected Javascript payload upon rendering the page. This script can instantly steal the victim's local storage, rewrite the DOM, or make unauthorized API calls on their behalf. You must use a sanitizer library (like DOMPurify) before rendering raw HTML.", ["Stored XSS (Cross-Site Scripting) attack", "Bypassing React's escaping allows execution of malicious injected Javascript", "Must sanitize untrusted HTML using libraries like DOMPurify before rendering"], ["React will automatically delete the post from the database"])
]

BUCKET_KEYS = {
    "B1": ("Observability", "Distributed Tracing", "OpenTelemetry", ["Full Stack Developer", "Backend Developer"]),
    "B2": ("Multi-Tenancy", "Tenant Isolation", "Architecture", ["Full Stack Developer", "Database Developer"]),
    "B3": ("BFF / Edge Architecture", "API Gateway", "Architecture", ["Full Stack Developer", "DevOps / Cloud Engineer"]),
    "B4": ("Reliability", "Cross-Layer Consistency", "System Design", ["Full Stack Developer", "Backend Developer"]),
    "B5": ("Security", "Cross-Layer Vulnerabilities", "AppSec", ["Full Stack Developer", "Frontend Developer"])
}

def main():
    with open(OUT, encoding="utf-8") as f:
        prior = [json.loads(l) for l in f if l.strip()]
    
    staged_q = [p["question"] for p in prior]
    staged_a = [p["expected_answer"] for p in prior]
    
    sup = existing_supabase()
    staged_q.extend([q for q, _ in sup])
    staged_a.extend([a for _, a in sup])

    cands = []
    for b, intent, diff, qt, sec, q, a, strong, weak in Q:
        skill, topic, tech, roles = BUCKET_KEYS[b]
        cands.append({
            "primary_role": ROLE,
            "applicable_roles": roles,
            "primary_skill": skill,
            "secondary_skills": sec,
            "technology": tech,
            "topic": topic,
            "category": "System Design",
            "intent": intent,
            "difficulty": diff,
            "question_type": qt,
            "question": q,
            "expected_answer": a,
            "evaluation_rubric": {"strong_indicators": strong, "weak_indicators": weak}
        })

    corpus = staged_q + staged_a + [c["question"] for c in cands] + [c["expected_answer"] for c in cands]
    vec = TfidfVectorizer(stop_words="english", ngram_range=(1, 2)).fit(corpus)
    SQ, SA = vec.transform(staged_q), vec.transform(staged_a)
    SC = vec.transform([x + " " + y for x, y in zip(staged_q, staged_a)])
    seen_norm = {normalize_text(q) for q in staged_q}

    rej = Counter()
    accepted = []
    details = []
    ans_flags = []
    
    for idx, c in enumerate(cands):
        nq = normalize_text(c["question"])
        reason = None
        if nq in seen_norm:
            reason = "exact_duplicate"
        else:
            qs = cosine_similarity(vec.transform([c["question"]]), SQ)[0]
            as_ = cosine_similarity(vec.transform([c["expected_answer"]]), SA)[0]
            comp = cosine_similarity(vec.transform([c["question"] + " " + c["expected_answer"]]), SC)[0]
            
            details.append((float(qs.max()), float(as_.max()), float(comp.max())))
            if as_.max() >= 0.5:
                ans_flags.append((c["question"][:70], round(float(as_.max()), 3)))
                
            if qs.max() >= 0.80:
                reason = "near_duplicate"
            elif comp.max() >= 0.60:
                reason = "semantic_competency_duplicate"
            elif as_.max() >= 0.70:
                reason = "expected_answer_overlap"
                
        if not reason and LEAK.search(c["question"] + " " + c["expected_answer"]):
            reason = "prompt_leakage"
        
        if reason:
            rej[reason] += 1
            print(f"Rejected Q{idx+1}: {reason}")
            continue
            
        seen_norm.add(nq)
        accepted.append(c)

    print(f"Attempted: {len(cands)}, Accepted: {len(accepted)}, Rejected: {sum(rej.values())}")
    
    if len(accepted) != 50:
        print(f"ERROR: Did not accept exactly 50 (got {len(accepted)}). Aborting write.")
        sys.exit(1)

    for c in accepted:
        c["id"] = "gen_" + str(uuid.uuid4())
        c["generation_batch"] = "batch_50_full_stack_developer"

    with open(OUT, "a", encoding="utf-8") as f:
        for c in accepted:
            f.write(json.dumps(c) + "\n")
            
    final_staging_total = len(prior) + len(accepted)
    role_counts = Counter(p.get("primary_role") for p in prior)
    role_counts[ROLE] += len(accepted)
    
    diff_counts = Counter(c["difficulty"] for c in accepted)
    intent_counts = Counter(c["intent"] for c in accepted)
    skill_counts = Counter(c["primary_skill"] for c in accepted)
    tech_counts = Counter(c["technology"] for c in accepted)
    topic_counts = Counter(c["topic"] for c in accepted)
    openings = Counter(opening(c["question"], 3) for c in accepted)
    
    bq = [c["question"] for c in accepted]
    M = cosine_similarity(vec.transform(bq)) if bq else [[0]]
    intra = [(i, j, round(float(M[i][j]), 3)) for i in range(len(bq)) for j in range(i + 1, len(bq)) if M[i][j] >= 0.6]
    intra_qa = cosine_similarity(vec.transform([c["expected_answer"] for c in accepted])) if bq else [[0]]
    intra_ans = [(i, j, round(float(intra_qa[i][j]), 3)) for i in range(len(bq)) for j in range(i + 1, len(bq)) if intra_qa[i][j] >= 0.5]
    
    report = {
        "batch": "batch_50_full_stack_developer",
        "records_attempted": len(cands),
        "records_accepted": len(accepted),
        "records_rejected": sum(rej.values()),
        "rejection_reasons": dict(rej),
        "max_similarity_scores": {
            "question": round(max((d[0] for d in details), default=0), 3),
            "answer": round(max((d[1] for d in details), default=0), 3),
            "combined": round(max((d[2] for d in details), default=0), 3)
        },
        "intra_batch_overlaps": len(intra),
        "intra_batch_answer_overlaps": len(intra_ans),
        "answer_flags_gt_50": len(ans_flags),
        "staging_metrics": {
            "previous_staging_total": len(prior),
            "final_staging_total": final_staging_total,
            "role_total": role_counts[ROLE],
            "remaining_to_500": max(0, 500 - role_counts[ROLE])
        },
        "distributions": {
            "difficulty": dict(diff_counts),
            "intent": dict(intent_counts),
            "primary_skill": dict(skill_counts),
            "technology": dict(tech_counts),
            "topic": dict(topic_counts),
            "opening_diversity": dict(openings.most_common(10))
        }
    }
    
    with open(os.path.join(REPORTS_DIR, "phase4d_batch50_report.json"), "w", encoding="utf-8") as f:
        json.dump(report, f, indent=2)
        
    with open(os.path.join(REPORTS_DIR, "phase4d_batch50_report.md"), "w", encoding="utf-8") as f:
        f.write(f"# Phase 4D - Batch 50 (Full Stack Developer)\n\n")
        f.write(f"- **Attempted**: {len(cands)}\n")
        f.write(f"- **Accepted**: {len(accepted)}\n")
        f.write(f"- **Rejected**: {sum(rej.values())}\n")
        f.write(f"- **Rejections**: {dict(rej)}\n\n")
        f.write("### Staging Totals\n")
        f.write(f"- **Previous Staging Total**: {len(prior)}\n")
        f.write(f"- **Final Staging Total**: {final_staging_total}\n")
        f.write(f"- **Full Stack Developer Role Total**: {role_counts[ROLE]}\n")
        f.write(f"- **Remaining to 500 Target**: {report['staging_metrics']['remaining_to_500']}\n\n")
        f.write("### Similarity\n")
        f.write(f"- **Max Question Sim**: {report['max_similarity_scores']['question']}\n")
        f.write(f"- **Max Answer Sim**: {report['max_similarity_scores']['answer']}\n")
        f.write(f"- **Max Combined Sim**: {report['max_similarity_scores']['combined']}\n")
        f.write(f"- **Intra-batch Overlaps**: {len(intra)}\n")
        f.write(f"- **Answer Overlaps (>0.5)**: {len(ans_flags)}\n\n")
        f.write("### Distributions\n")
        f.write(f"- **Difficulty**: {dict(diff_counts)}\n")
        f.write(f"- **Intent**: {dict(intent_counts)}\n")
        f.write(f"- **Primary Skill**: {dict(skill_counts)}\n")
        f.write(f"- **Technology**: {dict(tech_counts)}\n")
        f.write(f"- **Topic**: {dict(topic_counts)}\n\n")
        f.write("### Top Openings\n")
        for op, count in openings.most_common(8):
            f.write(f"- `{op}`: {count}\n")

    print(f"Successfully generated 50 Full Stack Developer questions.")

if __name__ == "__main__":
    main()
