"""Batch 10 question content (DevOps / Cloud Engineer). Antigravity-native, no Gemini API."""

ROLE = "DevOps / Cloud Engineer"

# key: (plan skill, plan topic, applicable_roles)
BUCKET_KEYS = {
    "DKR": ("Docker", "Images", ["Backend Developer", "Full Stack Developer"]),
    "K8S": ("Kubernetes Core", "Deployments", ["Backend Developer"]),
    "IAM": ("AWS IAM", "Policies", ["Backend Developer"]),
    "TFS": ("Terraform", "State", []),
    "ALR": ("Monitoring", "Alerting", ["Backend Developer"]),
}

# (bucket, intent, difficulty, qtype, secondary_skills, question, expected_answer, strong, weak)
Q = [
# ---------------- Docker Images ----------------
("DKR", "fundamentals", "easy", "concept", [],
 "What is the difference between a Docker image and a container?",
 "An image is an immutable, layered template containing the filesystem and metadata needed to run an application. A container is a running (or stopped) instance of an image with a thin writable layer on top, plus its own process, network and runtime state. Many containers can be started from one image.",
 ["Image is a read-only template", "Container is a running instance", "Writable layer on top"],
 ["Uses the terms interchangeably"]),
("DKR", "explain", "easy", "concept", [],
 "How do Docker image layers and the build cache work together, and why does instruction order in a Dockerfile matter?",
 "Each Dockerfile instruction that changes the filesystem creates a layer, and Docker caches layers by instruction and inputs. Once a layer changes, every later layer is rebuilt. So instructions that change rarely (installing dependencies) should come before those that change often (copying source code).",
 ["Each instruction creates a layer", "Cache invalidated from the changed layer onwards", "Stable steps first"],
 ["Says the cache is global regardless of order"]),
("DKR", "compare", "easy", "comparison", [],
 "What is the difference between CMD and ENTRYPOINT in a Dockerfile?",
 "ENTRYPOINT defines the executable that always runs when the container starts, and CMD supplies default arguments (or a default command if no ENTRYPOINT) that can be overridden by arguments to docker run. A common pattern is ENTRYPOINT for the program and CMD for default flags.",
 ["ENTRYPOINT is the fixed executable", "CMD provides overridable defaults", "Combination pattern"],
 ["Says they are identical"]),
("DKR", "scenario", "easy", "scenario", [],
 "A colleague builds production images from 'FROM node:latest'. Why is that a problem, and what would you use instead?",
 "The latest tag moves, so builds are not reproducible and a new major version can silently break the application or introduce vulnerabilities. Pin a specific version (for example node:20.11-slim) or better a digest, and update it deliberately through a reviewed change.",
 ["Latest is a moving tag", "Reproducibility", "Pin version or digest"],
 ["Says latest is always the safest"]),
("DKR", "optimize", "medium", "optimization", [],
 "Every code change makes your Node.js image rebuild and reinstall all npm dependencies, taking minutes. How do you restructure the Dockerfile?",
 "Copy only package.json and the lockfile first, run npm ci to install dependencies in its own layer, and only then COPY the application source. The dependency layer stays cached unless the manifests change. Adding a .dockerignore keeps node_modules and other noise out of the build context.",
 ["Copy manifests before source", "Separate dependency layer", ".dockerignore"],
 ["Copies everything first then installs"]),
("DKR", "implement", "medium", "implementation", [],
 "How would you use a multi-stage build to produce a small production image for a compiled application such as a Go or Java service?",
 "Use one stage with the full toolchain to compile or package the application, then start a minimal runtime stage (slim, distroless or scratch) and COPY --from=builder only the built artifact. The final image excludes compilers, source and build caches, making it smaller and with a reduced attack surface.",
 ["Builder stage and runtime stage", "COPY --from the builder", "Smaller image and attack surface"],
 ["Deletes files in the final layer thinking it shrinks the image"]),
("DKR", "tradeoff", "medium", "tradeoff", [],
 "How do you choose between alpine, slim and distroless base images?",
 "Alpine is very small but uses musl libc, which can cause compatibility or performance issues with some binaries and Python wheels. Slim Debian images are larger but more compatible. Distroless images contain no shell or package manager, reducing attack surface but making debugging harder. Choose based on compatibility, security needs and debuggability.",
 ["Alpine musl compatibility", "Slim is compatible", "Distroless is minimal but hard to debug"],
 ["Always chooses the smallest image"]),
("DKR", "debug", "medium", "debugging", [],
 "Your image has grown to 1.8 GB. How do you find out why and what do you change?",
 "Inspect layers with docker history or a tool like dive to find large layers. Typical causes are a heavy base image, build tools and package caches left in the final image, a missing .dockerignore copying .git or data, and files removed in a later layer (still stored in the earlier one). Fix with a slimmer base, multi-stage builds, cleaning caches in the same RUN step, and .dockerignore.",
 ["docker history or dive", "Common causes identified", "Multi-stage and cache cleanup in same RUN"],
 ["Just compresses the image with gzip"]),
("DKR", "diagnose", "medium", "debugging", ["Security"],
 "A security scan finds an API token inside a pushed image even though your Dockerfile deleted the .env file in a later step. Why is it still there, and what is the right approach?",
 "Image layers are immutable and additive, so a file added in one layer remains retrievable from that layer even if a later layer removes it. Never COPY secrets or pass them as build ARGs. Use BuildKit secret mounts (RUN --mount=type=secret) or inject secrets at runtime, and rotate the exposed token.",
 ["Layers retain deleted files", "BuildKit secrets or runtime injection", "Rotate exposed secret"],
 ["Believes rm in a later step removes it from the image"]),
("DKR", "scenario", "hard", "scenario", ["Security"],
 "You are asked to harden the container image pipeline for a set of production services. What measures would you put in place?",
 "Use minimal, pinned base images (preferably by digest), run as a non-root user with a read-only filesystem where possible, scan images for vulnerabilities in CI and block on critical findings, generate an SBOM and sign images, avoid secrets in layers, and rebuild regularly to pick up patched base images. Enforce policies (admission control) so only signed, scanned images from a trusted registry run.",
 ["Pinned minimal base", "Non-root user", "Vulnerability scanning in CI", "Signing and SBOM", "Policy enforcement and regular rebuilds"],
 ["Relies on scanning only once manually"]),

# ---------------- Kubernetes Deployments ----------------
("K8S", "fundamentals", "easy", "concept", [],
 "What does a Kubernetes Deployment manage, and how does it relate to ReplicaSets and Pods?",
 "A Deployment declares the desired state of an application (image, replicas, update strategy). It creates and manages ReplicaSets, and each ReplicaSet maintains the desired number of identical Pods. During an update the Deployment creates a new ReplicaSet and scales the old one down.",
 ["Deployment manages ReplicaSets", "ReplicaSet maintains Pods", "New ReplicaSet per rollout"],
 ["Says a Deployment directly runs containers"]),
("K8S", "explain", "easy", "concept", [],
 "What are the ways to change the number of replicas of a Deployment, and which is preferable for repeatable infrastructure?",
 "You can run kubectl scale, edit the live object, change spec.replicas in the manifest and apply it, or attach a HorizontalPodAutoscaler for automatic scaling. Keeping spec.replicas in version-controlled manifests (GitOps) is preferable, though when an HPA owns scaling the manifest should not fight it.",
 ["kubectl scale and manifest replicas", "HPA for automatic scaling", "Declarative version-controlled config preferred"],
 ["Says replicas can only change by deleting pods"]),
("K8S", "explain", "easy", "concept", [],
 "Why does a rolling update need a properly configured readiness probe?",
 "The Deployment controller uses pod readiness to decide when a new pod can receive traffic and when old pods can be removed. Without a correct readiness probe a pod is considered ready as soon as the container starts, so traffic may be sent to an application that is not ready and the rollout may proceed with broken pods.",
 ["Readiness gates traffic and rollout progress", "Without it pods get traffic too early"],
 ["Confuses readiness with liveness restarts"]),
("K8S", "implement", "medium", "implementation", [],
 "How do maxSurge and maxUnavailable control a rolling update, and what values would you use for a zero-downtime deployment?",
 "maxSurge sets how many extra pods above the desired count may be created during the update, and maxUnavailable sets how many pods may be unavailable. For zero downtime set maxUnavailable to 0 and maxSurge to at least 1 (or a percentage), so a new ready pod exists before an old one is terminated, provided the cluster has spare capacity.",
 ["maxSurge extra pods", "maxUnavailable pods down", "maxUnavailable 0 with surge >= 1", "Needs spare capacity"],
 ["Sets both to 0"]),
("K8S", "debug", "medium", "debugging", [],
 "A new rollout is stuck and the new pods are in CrashLoopBackOff. How do you investigate, and how do you restore service?",
 "Check kubectl rollout status and describe the pod for events, view logs including the previous container with kubectl logs --previous, and examine exit codes, config, secrets and probe failures. Because the Deployment keeps old pods while the new ones are not ready, service is usually still up, and you can run kubectl rollout undo to return to the previous ReplicaSet while fixing the cause.",
 ["rollout status and describe", "logs --previous", "rollout undo", "Old pods keep serving"],
 ["Deletes the Deployment and recreates it"]),
("K8S", "diagnose", "medium", "debugging", [],
 "After deploying, pods show ImagePullBackOff. What are the common causes?",
 "A wrong image name or tag, a tag that does not exist, a private registry that needs imagePullSecrets, expired or missing registry credentials, network or registry outages, or rate limits on a public registry. kubectl describe pod shows the exact pull error.",
 ["Wrong name or tag", "Missing imagePullSecrets", "Registry access or rate limit", "describe pod events"],
 ["Blames CPU limits"]),
("K8S", "scenario", "medium", "scenario", [],
 "Your HorizontalPodAutoscaler never scales up even though CPU is clearly high. What do you check?",
 "Verify metrics-server is installed and the HPA can read metrics (kubectl describe hpa), that the pods define CPU resource requests because utilization targets are relative to requests, that the target and maxReplicas are sensible, and that the cluster has capacity to schedule new pods. Also check that the HPA targets the right Deployment.",
 ["metrics-server available", "Resource requests required", "describe hpa and maxReplicas", "Cluster capacity"],
 ["Only increases the CPU limit"]),
("K8S", "compare", "medium", "comparison", [],
 "Compare the Recreate and RollingUpdate strategies, and how blue-green or canary releases differ from them.",
 "Recreate terminates all old pods before starting new ones, causing downtime but guaranteeing no two versions overlap. RollingUpdate replaces pods gradually with no downtime but versions run side by side. Blue-green runs a full second environment and switches traffic at once for fast rollback, while canary sends a small share of traffic to the new version to validate it first, usually needing a service mesh or ingress features.",
 ["Recreate downtime", "RollingUpdate overlap", "Blue-green instant switch", "Canary gradual traffic"],
 ["Says RollingUpdate also removes version overlap"]),
("K8S", "diagnose", "hard", "debugging", [],
 "Even with a RollingUpdate strategy, clients see a few seconds of failed requests on every deploy. What are the likely causes and fixes?",
 "Pods may be marked ready before the application can serve (fix the readiness probe), and terminating pods may be removed abruptly. Endpoint removal and SIGTERM happen concurrently, so in-flight requests and new requests routed by stale endpoints fail. Handle SIGTERM with graceful shutdown, add a preStop sleep or delay, set an adequate terminationGracePeriodSeconds, and make sure connection draining on the load balancer is configured.",
 ["Accurate readiness probe", "Graceful SIGTERM handling", "preStop delay for endpoint propagation", "Termination grace period"],
 ["Blames the Kubernetes scheduler"]),
("K8S", "architecture", "hard", "architecture", [],
 "How would you configure a Deployment for a critical customer-facing API so it stays available during node failures, upgrades and traffic spikes?",
 "Run several replicas with resource requests and limits, readiness and liveness (and startup) probes, and spread pods across nodes and zones with topology spread constraints or anti-affinity. Add a PodDisruptionBudget to limit voluntary disruptions, an HPA for load, a safe rolling update strategy (maxUnavailable 0), graceful shutdown handling, and sensible priority classes. Pair it with monitoring and alerting on availability.",
 ["Multiple replicas across zones", "Probes and resource requests", "PodDisruptionBudget", "HPA and safe rollout", "Graceful shutdown"],
 ["Uses a single replica with a large instance"]),

# ---------------- AWS IAM Policies ----------------
("IAM", "fundamentals", "easy", "concept", [],
 "What are the main elements of an AWS IAM policy statement?",
 "Effect (Allow or Deny), Action (the API operations), Resource (the ARNs the actions apply to), and optionally Condition (circumstances such as source IP, tags or MFA), plus Principal in resource-based policies and a Sid for identification.",
 ["Effect, Action, Resource", "Optional Condition", "Principal in resource-based policies"],
 ["Omits Resource and Effect"]),
("IAM", "explain", "easy", "concept", [],
 "How do implicit deny and explicit deny work in IAM policy evaluation?",
 "By default all requests are implicitly denied. An explicit Allow in an applicable policy permits the request, unless any applicable policy contains an explicit Deny, which always overrides any Allow.",
 ["Default deny", "Allow grants access", "Explicit deny overrides everything"],
 ["Says an Allow always beats a Deny"]),
("IAM", "compare", "easy", "comparison", [],
 "What is the difference between an identity-based policy and a resource-based policy, for example an S3 bucket policy?",
 "An identity-based policy is attached to a user, group or role and defines what that identity can do. A resource-based policy is attached to a resource and defines who (the principal) can access it, including principals from other accounts. Both contribute to the authorization decision.",
 ["Attached to identity versus resource", "Resource policies name principals", "Cross-account use"],
 ["Says only identity policies exist"]),
("IAM", "implement", "medium", "implementation", [],
 "How would you write a least-privilege policy letting an application read only objects under the 'reports/' prefix of one S3 bucket?",
 "Allow s3:GetObject on arn:aws:s3:::my-bucket/reports/* and, if listing is needed, allow s3:ListBucket on arn:aws:s3:::my-bucket with a Condition limiting s3:prefix to reports/*. Note that object actions use the object ARN with /* while ListBucket applies to the bucket ARN.",
 ["GetObject on prefixed object ARN", "ListBucket on bucket ARN with prefix condition", "Separate bucket and object ARNs"],
 ["Uses s3:* on all resources"]),
("IAM", "debug", "medium", "debugging", [],
 "A Lambda function's role has a policy allowing s3:GetObject, yet calls fail with AccessDenied. What do you check?",
 "Confirm the policy is attached to the actual execution role in use and that the Resource ARN matches the object (arn:aws:s3:::bucket/* rather than just the bucket). Look for an explicit Deny, a bucket policy that restricts access, a permission boundary, an SCP, a KMS key policy if objects are encrypted with a customer-managed key, and wrong region or account.",
 ["Right role and ARN form", "Explicit deny or bucket policy", "Boundary or SCP", "KMS permissions"],
 ["Re-creates the Lambda function"]),
("IAM", "compare", "medium", "comparison", [],
 "When would you use AWS managed policies, customer managed policies and inline policies?",
 "AWS managed policies are maintained by AWS and convenient but often broader than needed. Customer managed policies are reusable, versioned and tailored, and are the best default for least privilege. Inline policies are embedded in a single identity, tightly coupled and not reusable, suitable only when a strict one-to-one relationship is required.",
 ["AWS managed are broad", "Customer managed reusable and versioned", "Inline is one-to-one coupling"],
 ["Says inline policies are preferred for everything"]),
("IAM", "scenario", "medium", "scenario", [],
 "A role in account B must read a bucket in account A. What has to be configured for the access to work?",
 "Cross-account access needs both sides to allow it: the bucket policy in account A must grant the account B principal the required actions, and an identity policy in account B must allow the role to perform those actions on the bucket. If the bucket uses KMS encryption, the key policy must also allow it.",
 ["Resource policy in account A", "Identity policy in account B", "KMS key policy if encrypted"],
 ["Only configures one account"]),
("IAM", "explain", "medium", "concept", [],
 "How do permission boundaries and service control policies (SCPs) affect what an IAM role can do?",
 "They do not grant permissions; they limit the maximum permissions. A permission boundary caps what an IAM user or role can receive from its identity policies, and an SCP caps what any principal in an organization account can do. The effective permissions are the intersection of the allows across identity policy, boundary and SCP, with any explicit deny overriding.",
 ["They set maximum permissions", "Intersection of allows", "Explicit deny wins"],
 ["Believes boundaries grant permissions"]),
("IAM", "diagnose", "hard", "debugging", [],
 "A request is denied even though the caller's identity policy allows the action. Walk through how you determine which layer is denying it.",
 "Follow IAM evaluation: look for an explicit deny in any policy type (identity, resource, permission boundary, SCP, session policy, VPC endpoint policy). Then confirm an applicable allow exists in the necessary combination (for same-account, identity or resource policy; for cross-account, both). Use the IAM policy simulator, CloudTrail's error message and Access Analyzer, and check conditions such as source IP, VPC endpoint or MFA that might not be met.",
 ["Explicit deny search across policy types", "Boundary, SCP and session policy", "Policy simulator and CloudTrail", "Condition keys"],
 ["Only re-reads the identity policy"]),
("IAM", "architecture", "hard", "architecture", [],
 "A platform team runs 40 microservices and developers keep using wildcard IAM policies to get unblocked. How would you drive the organization toward least privilege without blocking delivery?",
 "Provide reusable, scoped policy modules or templates through infrastructure as code, and generate tight policies from real usage using CloudTrail data and IAM Access Analyzer policy generation. Use ABAC with resource and principal tags to avoid per-service policies, enforce guardrails with permission boundaries and SCPs, review wildcards in CI with policy linters, and regularly remove unused permissions using last-accessed data.",
 ["Reusable scoped policy templates", "Access Analyzer and CloudTrail generation", "ABAC with tags", "Guardrails and CI checks", "Unused permission cleanup"],
 ["Bans developers from touching IAM entirely"]),

# ---------------- Terraform State ----------------
("TFS", "fundamentals", "easy", "concept", [],
 "What does the Terraform state file record, and why does Terraform need it?",
 "State maps resources declared in configuration to real infrastructure objects (IDs and attributes). Terraform uses it to know what already exists, compute the difference between desired and actual state, track dependencies and improve performance, without which it could not safely update or destroy resources.",
 ["Maps config to real resources", "Used to compute diffs", "Needed for updates and destroys"],
 ["Says it is just a log of previous commands"]),
("TFS", "explain", "easy", "concept", [],
 "Why shouldn't you commit the Terraform state file to Git, and what do teams use instead?",
 "State can contain sensitive values (passwords, keys) in plain text, and concurrent changes by team members cause conflicts and corruption. Teams use a remote backend such as S3, Terraform Cloud or Azure Storage with encryption, access control, versioning and state locking.",
 ["Secrets in state", "Concurrency and conflicts", "Remote backend with locking"],
 ["Says Git is fine if the repo is private"]),
("TFS", "explain", "easy", "concept", [],
 "What does terraform plan compare to decide what to change?",
 "It compares the desired configuration with the state, after refreshing the state against the real infrastructure, and produces a plan of creates, updates and deletes needed to make real infrastructure match the configuration.",
 ["Configuration versus state", "Refresh against real infrastructure", "Outputs a change plan"],
 ["Says it only validates syntax"]),
("TFS", "implement", "medium", "implementation", [],
 "How do you set up an S3 remote backend with locking, and what problem does locking solve?",
 "Configure a backend 's3' block with bucket, key and region (with encryption and versioning on the bucket), and a DynamoDB table (or the S3 native lock in newer versions) for locking. Locking prevents two applies from modifying the same state simultaneously, which could corrupt state or create conflicting changes.",
 ["Backend S3 configuration", "Lock table or native locking", "Prevents concurrent applies", "Versioning and encryption"],
 ["Uses a local file but says it is shared"]),
("TFS", "scenario", "medium", "scenario", [],
 "Someone manually deleted an EC2 instance in the console, and terraform plan now wants to create it. How do you handle drift in general?",
 "Terraform detects the missing resource during refresh and plans to recreate it, which is often the desired fix. If the manual change was intentional, update the configuration or use terraform state rm to stop tracking. Prevent drift by restricting console changes, running scheduled plans to detect drift, and using terraform plan -refresh-only to review changes before accepting them.",
 ["Refresh detects drift", "Recreate or update config or state rm", "Drift detection and access restriction"],
 ["Edits the state file by hand"]),
("TFS", "implement", "medium", "implementation", [],
 "How do you bring an existing manually created resource under Terraform management?",
 "Write the resource block in configuration, then use terraform import (or an import block in newer versions) with the resource address and real ID to add it to state. Then run terraform plan and adjust the configuration until there is no diff, since import populates state but does not generate the configuration automatically (unless using config generation).",
 ["Resource block plus import", "Run plan until no diff", "Import fills state not config"],
 ["Expects import to write the configuration"]),
("TFS", "debug", "medium", "debugging", [],
 "A CI job was cancelled and now every run fails with 'Error acquiring the state lock'. What do you do?",
 "First confirm that no other run is actually in progress by checking the lock info (ID, who and when). If it is stale, release it with terraform force-unlock <LOCK_ID>, or remove the lock record in the lock table as a last resort. Then rerun, and make CI handle cancellation gracefully and use timeouts.",
 ["Verify no active run", "force-unlock with lock ID", "Prevent stale locks in CI"],
 ["Deletes the state file"]),
("TFS", "tradeoff", "medium", "tradeoff", [],
 "Should an organization keep all infrastructure in a single Terraform state or split it by environment and component? What are the trade-offs?",
 "A single state is simple and handles dependencies easily but makes plans slow, increases the blast radius of mistakes and creates lock contention between teams. Splitting by environment and component limits blast radius, speeds up plans and allows separate permissions, but requires sharing values via outputs, remote state data sources or other mechanisms and managing ordering between stacks.",
 ["Blast radius and plan speed", "Lock contention", "Cross-state dependencies"],
 ["Says one state is always best"]),
("TFS", "implement", "medium", "implementation", [],
 "You renamed a resource in your configuration and terraform plan wants to destroy and recreate it. How do you avoid downtime?",
 "Terraform sees the new name as a different resource. Tell it the object is the same by adding a moved block (or running terraform state mv old_address new_address) so the existing state entry is reassigned, and then the plan should show no changes.",
 ["Rename looks like destroy/create", "moved block or state mv", "Plan shows no changes"],
 ["Accepts the recreation of a production database"]),
("TFS", "scenario", "hard", "scenario", ["Security"],
 "Your Terraform state contains database passwords and private keys. How would you secure it across a multi-team organization?",
 "Store state in a remote backend with encryption at rest and in transit, strict IAM or RBAC limiting read access (often only CI roles), versioning and audit logging. Note that marking values sensitive hides them from output but they are still stored in state, so avoid putting secrets in Terraform where possible by generating them in a secrets manager and referencing them at runtime, and separate states by sensitivity.",
 ["Encrypted remote backend", "Least-privilege access and audit", "sensitive does not remove from state", "Use a secrets manager"],
 ["Believes sensitive = true keeps secrets out of state"]),

# ---------------- Prometheus Alerting ----------------
("ALR", "fundamentals", "easy", "concept", [],
 "What are the key parts of a Prometheus alerting rule?",
 "A name, a PromQL expression that evaluates to the condition, an optional 'for' duration the condition must hold before firing, labels (such as severity) and annotations (summary and description) that describe the alert. Prometheus evaluates the rule and sends firing alerts to Alertmanager.",
 ["expr and for", "Labels and annotations", "Sent to Alertmanager"],
 ["Says Prometheus sends emails itself"]),
("ALR", "explain", "easy", "concept", [],
 "What does the 'for' clause do in a Prometheus alerting rule, and why is it useful?",
 "It requires the expression to be continuously true for the stated duration before the alert moves from pending to firing. This avoids paging on short spikes or flapping conditions.",
 ["Pending then firing", "Avoids noise from brief spikes"],
 ["Says it sets how long the alert stays active"]),
("ALR", "explain", "easy", "concept", [],
 "What does Alertmanager do that Prometheus itself does not?",
 "Alertmanager receives alerts from Prometheus and handles deduplication, grouping, routing to receivers (Slack, PagerDuty, email), silencing, inhibition and throttling repeat notifications, while Prometheus only evaluates the rules.",
 ["Grouping and deduplication", "Routing to receivers", "Silencing and inhibition"],
 ["Says Alertmanager collects the metrics"]),
("ALR", "explain", "easy", "concept", [],
 "Why do experienced teams page on symptoms such as user-facing errors rather than on causes such as high CPU?",
 "Symptoms indicate actual user impact and are what needs urgent action, while causes like high CPU may be harmless or may not predict problems. Paging on symptoms reduces false alarms and alert fatigue, while cause-based metrics are kept for dashboards and diagnosis.",
 ["Symptoms reflect user impact", "Causes create noise", "Cause metrics used for diagnosis"],
 ["Says CPU alerts are always the most important"]),
("ALR", "implement", "medium", "implementation", [],
 "Write the idea for an alert that fires when more than 5% of HTTP requests return 5xx for 10 minutes.",
 "Use a ratio of rates: sum(rate(http_requests_total{status=~\"5..\"}[5m])) / sum(rate(http_requests_total[5m])) > 0.05 with 'for: 10m', optionally grouped by service. Using rate over a window handles counters correctly, and guarding against division by zero or low traffic helps avoid noisy alerts.",
 ["Ratio of 5xx rate to total rate", "rate() over a window for counters", "for: 10m", "Low traffic consideration"],
 ["Alerts on raw counter value"]),
("ALR", "scenario", "medium", "scenario", [],
 "The on-call engineer receives about 200 alerts a night, mostly not actionable. How would you fix the alerting?",
 "Audit alerts and remove or downgrade those that are not actionable, page only on symptoms or SLO violations, and send the rest to tickets or dashboards. Use Alertmanager grouping, inhibition and sensible 'for' durations, tune thresholds, add runbooks, and review alert quality regularly through postmortems and alert metrics.",
 ["Actionable alerts only", "Severity and routing", "Grouping and inhibition", "Runbooks and regular review"],
 ["Mutes the alerts channel"]),
("ALR", "debug", "medium", "debugging", [],
 "The condition looks true on a Grafana graph, but the Prometheus alert never fires. What do you check?",
 "Check that the rule is loaded and healthy in the Prometheus Rules page, whether the alert is stuck in pending because of the 'for' duration, that the expression in the rule matches the one in Grafana (labels, ranges, evaluation interval), whether staleness or missing series affect it, and whether Alertmanager routing or silences are suppressing notifications.",
 ["Rule loaded and healthy", "Pending due to for", "Expression and label differences", "Alertmanager silences or routes"],
 ["Assumes Grafana and Prometheus alerting are the same system"]),
("ALR", "implement", "medium", "implementation", [],
 "How do you alert when a service target stops being scraped or a metric disappears entirely?",
 "Use the up metric (up{job=\"api\"} == 0) to detect failed scrapes, and absent() or absent_over_time() to detect a metric that no longer exists. A threshold alert on a missing series never fires because there is no data, so you need an explicit absence check.",
 ["up == 0", "absent() for missing metrics", "Missing data does not trigger threshold alerts"],
 ["Relies on a threshold alert for missing data"]),
("ALR", "compare", "medium", "comparison", [],
 "Compare simple threshold alerts with SLO burn-rate alerts.",
 "Threshold alerts fire when a metric crosses a fixed value and are simple but can be noisy or miss slow degradations unrelated to the threshold. Burn-rate alerts measure how fast the error budget is being consumed against an SLO, so they page proportionally to the impact on the objective and are better aligned with user experience, but need well-defined SLOs and more complex rules.",
 ["Fixed threshold simplicity and noise", "Burn rate relates to error budget", "Alignment with SLO"],
 ["Says burn-rate alerts are just threshold alerts"]),
("ALR", "architecture", "hard", "architecture", [],
 "Explain how a multi-window, multi-burn-rate alert works for a 99.9% availability SLO and why it is used.",
 "A 99.9% SLO leaves a 0.1% error budget. Burn rate is the error rate divided by the budget. Pair a long and short window, such as a high burn rate (for example 14.4x) over 1 hour and 5 minutes to page quickly on severe, ongoing incidents, and a lower burn rate over longer windows (such as 6x over 6 hours, 1x over 3 days) for slower burns that create tickets. The short window confirms the problem is still happening, which reduces false positives and speeds resets.",
 ["Burn rate relative to the error budget", "Fast and slow burn tiers", "Long window plus short window", "Reduces false positives"],
 ["Confuses the error budget with the SLO target"]),
]
