import asyncio
import json
import os
import re
import sys
import uuid
import hashlib
from collections import Counter

from dotenv import load_dotenv
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
load_dotenv()

BACKEND_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_DIR = os.path.join(BACKEND_DIR, "data")
OUT = os.path.join(DATA_DIR, "interview_question_bank_v2_generated.jsonl")

ROLE = "Backend Developer"
LEAK = re.compile(r"(generate a question|generate \d+ questions|return only json|phase 4c gap plan|"
                  r"generation batch|candidate generation|system instructions|do not proceed|"
                  r"awaiting authorization|minimum target|generation pipeline|"
                  r"batch \d+ generation|expected answer|strong indicator|weak indicator|as an ai|"
                  r"here is the question|\bprompt text\b)", re.I)

Q = [
    # Group 13: API Evolution & Versioning
    ("B62_13_1", "concept", "medium", "concept", ["API Evolution"], "What is the 'Tolerant Reader' pattern in microservice API evolution, and how does it prevent breaking changes?", "The Tolerant Reader (Postel's Law) dictates that an API consumer should only extract the exact fields it needs from a JSON payload and silently ignore any unknown or extra fields. If Service A returns `{\"id\": 1, \"name\": \"Bob\"}`, and Service B only cares about `id`, Service B should not use strict schema validation that fails if new fields appear. This allows the backend team managing Service A to continuously add new fields (`\"age\": 30`) to the production payload without breaking backward compatibility or forcing Service B to redeploy. It decouples deployments.", ["Consumers should strictly parse only the fields they need and gracefully ignore unknown fields", "Prevents downstream services from crashing when the upstream service adds new data to the payload", "Enables backward-compatible API evolution without requiring coordinated synchronized deployments"], ["Tolerant readers are developers who don't complain about bad code"]),
    ("B62_13_2", "diagnose", "hard", "debugging", ["API Evolution"], "Your team renames a database column from `first_name` to `given_name`. To maintain API compatibility, you map `given_name` back to `first_name` in the JSON response. However, during the deployment, mobile clients randomly crash for 5 minutes, and then start working perfectly again. Why did this backend deployment cause a temporary mobile outage?", "This is a 'Rolling Deployment Schema Mismatch'. During a rolling deployment in Kubernetes, the old API pods (V1) and the new API pods (V2) run simultaneously for a few minutes. If you run the Database Migration (renaming the column) *before* all V1 pods are terminated, the V1 pods will attempt to `SELECT first_name` from the DB, get a SQL error (Column does not exist), and crash, throwing HTTP 500s to the mobile clients. To fix this, you MUST use 'Expand and Contract' deployments: Phase 1 adds the new column. Phase 2 deploys V2 API to read/write both. Phase 3 (weeks later) deletes the old column.", ["Rolling deployments run old code (V1) and new code (V2) simultaneously", "The DB migration broke the V1 code because it renamed a column the V1 code still expected", "Fix: Enforce strict 'Expand and Contract' schema migrations (additive changes only) so DB changes are backward compatible with V1 code"], ["The mobile phones had a virus"]),
    ("B62_13_3", "implement", "medium", "implement", ["API Evolution"], "How do you implement API Versioning for a public REST API without breaking mobile clients that haven't updated in 2 years?", "You must implement explicit versioning using either URL paths (`/v1/users`, `/v2/users`) or HTTP Headers (`Accept: application/vnd.company.v1+json`). Crucially, you do NOT maintain two entirely separate codebases. You maintain the core business logic as V2. When a V1 request arrives, you use an 'API Gateway / Translation Layer' (or middleware) to intercept the V1 request, mutate it to look like a V2 request, pass it to the core logic, and then mutate the V2 response back into the V1 JSON schema before returning it to the client. This provides backward compatibility with minimal code duplication.", ["Use explicit version identifiers in the URL path (`/v1/`) or HTTP Accept headers", "Do not duplicate the entire backend codebase for each version", "Use a translation/middleware layer to dynamically down-convert V2 responses into V1 schemas for legacy clients"], ["You just force all users to update their apps immediately"]),
    ("B62_13_4", "tradeoff", "hard", "tradeoff", ["API Evolution"], "What is the architectural tradeoff of evolving an API using GraphQL versus traditional REST v1/v2 versioning?", "REST traditionally requires creating entirely new endpoints (v2) for breaking changes, forcing clients to migrate to the new URL. GraphQL eliminates URL versioning entirely. It uses a single endpoint (`/graphql`) and a strongly-typed schema. To evolve it, you simply add new fields and mark old fields with the `@deprecated` directive. Clients explicitly request exactly the fields they want. The massive benefit is zero 'v2' endpoints and seamless evolution. The severe tradeoff is the N+1 Query problem on the backend (requiring DataLoaders), caching complexity (you cannot cache a generic `/graphql` POST request at the CDN level like you can a REST GET request), and the inability to simply 'delete' a field without breaking legacy queries.", ["GraphQL eliminates URL versioning (v1/v2) by allowing clients to explicitly query only the fields they need", "Deprecated fields remain in the schema alongside new fields for backward compatibility", "Tradeoff: GraphQL destroys CDN edge caching (all requests are POSTs) and introduces severe N+1 database query risks"], ["GraphQL is a graph database, REST is a resting database"]),
    ("B62_13_5", "scenario", "medium", "scenario", ["API Evolution"], "You are deprecating a legacy `/v1/payments` endpoint. You emailed all clients 6 months ago, but the logs show 500 requests per minute are still hitting it. You cannot just turn it off without causing an outage. How do you force clients to migrate using backend engineering?", "You implement 'Brownout Deployments'. Instead of turning it off completely, you introduce intentional, rolling degradation to force client developers to notice. Week 1: You intentionally return an `HTTP 429 Too Many Requests` or `HTTP 503` for exactly 1% of requests. Week 2: You increase the failure rate to 10% and add a 2-second artificial latency delay. Week 3: 50% failure rate. This creates noisy alerts in the client companies' monitoring systems, forcing their engineers to prioritize the migration ticket, while still allowing the majority of their traffic to succeed during the early phases.", ["Do not hard-delete endpoints heavily used by legacy clients without warning", "Implement 'Brownouts' by intentionally injecting minor, rolling failures (e.g., 1% HTTP 503s) or artificial latency", "This triggers the clients' monitoring alerts, forcing their developers to migrate without causing a total immediate outage"], ["You hack into their servers and change their code"]),
    ("B62_13_6", "concept", "hard", "concept", ["API Evolution"], "What is 'Consumer-Driven Contract Testing' (e.g., Pact) and how does it prevent backend developers from accidentally breaking downstream microservices?", "Normally, Backend A writes its own tests, but has no idea how Service B actually uses its payload. In Consumer-Driven Contract Testing, the Consumer (Service B) writes a 'Contract' defining exactly the JSON fields it expects from Service A. Service B publishes this Contract to a central broker. When the Backend Developer for Service A commits code, their CI pipeline downloads Service B's Contract and automatically runs a test to ensure Service A's new payload satisfies it. If the developer deleted a field Service B needs, the test fails instantly in Service A's CI pipeline, preventing the breaking change from ever being deployed.", ["The Consumer defines a strict Contract of exactly what fields it expects from the Provider", "The Provider's CI/CD pipeline automatically downloads and validates against this Contract before deploying", "Mathematically prevents a backend developer from deploying a change that breaks downstream services"], ["Consumer driven testing is when you ask the customers to write the unit tests"]),
    ("B62_13_7", "diagnose", "medium", "debugging", ["API Evolution"], "You add a new required JSON field `\"country_code\": \"US\"` to your backend POST endpoint. You update the frontend to send this field. You deploy the backend, then deploy the frontend. Suddenly, production error rates spike with `HTTP 400 Bad Request: missing country_code`. Why did the frontend requests fail despite being updated?", "This is a Cache/CDN propagation issue. While the backend was instantly updated to require the new field, and the new frontend HTML/JS was deployed, millions of users still have the old frontend Javascript cached in their browser or at the CDN edge. When they click 'Submit', their stale Javascript sends the old JSON payload missing the `country_code`, triggering the backend's strict 400 Bad Request validation. To fix this, backend API changes must always be backward compatible (make the new field Optional with a default value) until the CDN TTL expires and 100% of clients have the new frontend code.", ["Browsers and CDNs cache frontend Javascript; users will continue sending stale JSON payloads for hours/days", "The backend strictly required a new field, breaking all cached clients instantly", "Fix: Make new fields Optional with a default fallback in the backend until all frontend caches expire"], ["The users intentionally deleted the country code to hack the system"]),
    
    # Group 14: Data Consistency & Distributed State
    ("B62_14_1", "concept", "medium", "concept", ["Distributed Systems"], "Explain the CAP Theorem and why a modern distributed backend almost always chooses AP over CP.", "The CAP Theorem states a distributed database can only provide two of three guarantees: Consistency (all nodes see the exact same data), Availability (every request receives a response), and Partition Tolerance (the system survives network cable cuts between nodes). Because network partitions (P) are a physical reality of the internet, you MUST choose between C and A. If you choose CP, a network blip causes the database to freeze and return errors to protect data perfection. Modern backends (like Amazon Shopping Cart) choose AP (Eventual Consistency): the system always accepts writes (high availability), even if it means momentarily serving stale data, because dropping a customer's order is financially worse than them seeing a stale product review.", ["CAP Theorem: Consistency, Availability, Partition Tolerance (You can only pick 2)", "Network Partitions (P) are unavoidable physical realities, forcing a choice between C and A", "Modern backends choose AP (Eventual Consistency) to maximize uptime and revenue, tolerating brief periods of stale data"], ["CAP stands for Computer Application Programming"]),
    ("B62_14_2", "diagnose", "hard", "debugging", ["Distributed Systems"], "Your backend reads from a PostgreSQL Read-Replica to generate a user's dashboard. A user uploads a profile picture, the API returns 200 OK, and redirects them to their dashboard. The dashboard shows their old picture. They refresh 5 seconds later, and it shows the new picture. What is the exact architectural cause, and how do you fix it without routing all traffic to the Primary DB?", "This is 'Replication Lag'. The write went to the Primary DB. The dashboard immediately queried the Read-Replica, but the asynchronous binary log (WAL) hadn't finished copying the new row over the network yet. To fix this without abandoning read-replicas, you implement 'Read-Your-Writes' consistency via Caching. When the user updates the picture, the backend writes to the Primary DB AND saves the new picture URL in Redis (with a 10-second TTL). The dashboard endpoint always checks Redis first. If the key exists, it returns the fresh Redis data. If it doesn't, it safely falls back to the Read-Replica.", ["Replication Lag: The asynchronous copy from Primary to Read-Replica takes milliseconds to seconds", "The immediate redirect queries the replica before the data arrives, causing stale reads", "Fix: Implement 'Read-Your-Writes' consistency by caching the mutation in Redis for a few seconds to mask the replica lag"], ["The database was busy processing the picture's pixels"]),
    ("B62_14_3", "implement", "hard", "implement", ["Distributed Systems"], "How do you implement a 'Distributed Lock' safely using Redis (Redlock algorithm) to ensure two background workers don't process the same invoice concurrently?", "A simple `SETNX key value` is dangerous; if the worker crashes before `DEL`, the lock is held infinitely. You must include a TTL (Time-To-Live): `SET resource_name my_random_token NX PX 30000` (locks for 30s). Crucially, when releasing the lock, the worker CANNOT just call `DEL`. If Worker A's process paused for 40s (GC pause), its lock expired. Worker B acquired the lock. Worker A wakes up and calls `DEL`, accidentally deleting Worker B's lock! To prevent this, Worker A must execute a Lua Script that checks if the value matches `my_random_token`. It only deletes the lock if it physically owns it. (For absolute mission-critical data, use Database Fencing Tokens instead of Redis).", ["Must use a Time-To-Live (TTL) to prevent infinite deadlocks if the worker crashes", "Cannot blindly use `DEL` to release; a delayed worker will accidentally delete another worker's lock", "Must use a Lua Script to verify ownership (compare the random token) before deleting the lock atomically"], ["You use a physical padlock on the server door"]),
    ("B62_14_4", "tradeoff", "medium", "tradeoff", ["Distributed Systems"], "What is the tradeoff of using a 'Two-Phase Commit' (2PC) across microservices versus achieving eventual consistency via an Event Bus?", "Two-Phase Commit (2PC) acts as a distributed transaction manager. It asks Service A and Service B to 'prepare', and if both agree, it issues a 'commit'. It guarantees perfect ACID consistency across multiple databases. The severe tradeoff is Latency, Blocking, and Single Point of Failure. If Service B is slow to respond, Service A's database locks remain held open, freezing all other traffic. Eventual Consistency (via an Event Bus like Kafka) is entirely non-blocking and insanely fast, providing massive availability. The tradeoff is complex failure handling: if Service A succeeds but Service B fails later, you must write custom 'Compensating Transactions' (Sagas) to manually undo Service A's work.", ["2PC: Guarantees perfect ACID consistency across distributed DBs, but uses synchronous blocking locks that cripple performance and scalability", "Event Bus: Non-blocking, highly scalable, and available (Eventual Consistency)", "Tradeoff: Eventual consistency requires writing complex Compensating Transactions (Sagas) to handle partial failures"], ["Two phase commit means you have to commit your code twice to git"]),
    ("B62_14_5", "scenario", "hard", "scenario", ["Distributed Systems"], "You are building a backend for a ticketing system (e.g., Taylor Swift concerts). 100,000 users click 'Buy' simultaneously for 10,000 available tickets. The database cannot handle 100,000 concurrent transactional locks. How do you architect the backend to prevent overselling while maintaining high availability?", "You completely decouple the ticket inventory from the SQL Database using an in-memory datastore (Redis). 1) You preload a Redis counter: `SET tickets_available 10000`. 2) When a user clicks Buy, the backend executes a fast Lua script in Redis: `if GET tickets_available > 0 then DECR tickets_available return true else return false`. This executes in microseconds and is mathematically atomic (single-threaded). 3) If true, the user is guaranteed a ticket. The backend drops an event into a Kafka queue: `ProcessOrder(UserA)`. 4) A background worker leisurely reads the queue and inserts the actual rows into the SQL database. The heavy SQL DB is completely shielded from the 100,000 concurrent clicks.", ["A traditional SQL database will crash or suffer massive lock contention under 100,000 concurrent transactional writes", "Architectural Fix: Move the atomic inventory count to Redis using a Lua script (`DECR`)", "If the Redis atomic decrement succeeds, push the heavy SQL transaction to an asynchronous background queue (Kafka) to shield the DB"], ["You just print more tickets"]),
    ("B62_14_6", "explain", "medium", "explain", ["Distributed Systems"], "Explain the concept of 'Idempotency' and why it is critical for POST requests in a distributed backend.", "In a distributed system, network calls fail randomly. If a mobile app sends `POST /charge-card`, and the network drops the HTTP response, the app doesn't know if the charge succeeded. If it retries, and the backend isn't idempotent, the user is charged twice. Idempotency guarantees that making the same request multiple times produces the exact same result as making it once. It is implemented by requiring the client to send a unique `Idempotency-Key` (UUID) in the header. The backend caches this key. On retry, the backend sees the cached key and safely returns the previous success response without executing the business logic again.", ["Guarantees that multiple identical requests produce the same side-effect as a single request", "Critical because network failures force clients to blindly retry requests", "Implemented using unique client-generated `Idempotency-Keys` cached by the backend to bypass duplicate processing"], ["Idempotency means the server is impotent and cannot write to the database"]),
    ("B62_14_7", "diagnose", "medium", "debugging", ["Distributed Systems"], "A backend cron job deletes old temporary files from AWS S3. It queries the database for files older than 30 days, deletes the S3 object via the AWS SDK, and then deletes the database row. Occasionally, the script crashes halfway through due to a memory limit. When it restarts, you find orphaned objects in S3 that no longer exist in the database, costing you money. Why?", "This is a 'Dual-Write' ordering bug. If the script deletes the S3 object first, and then crashes before deleting the DB row, the DB still thinks the file exists. On restart, it retries, but S3 returns a 404 (Object Not Found), causing an unhandled exception that halts the script. Conversely, if it deletes the DB row first and then crashes before hitting S3, the S3 object becomes an invisible orphan (costing money forever) because the DB has forgotten about it. To fix this safely without distributed transactions: Mark the DB row as `status='PENDING_DELETE'`. Delete from S3. Finally, physically `DELETE` the DB row. If it crashes, the retry logic simply looks for `PENDING_DELETE` rows.", ["The script lacks atomic distributed transactions between the Database and the external S3 API", "Deleting the DB row first causes orphaned S3 objects if a crash occurs immediately after", "Fix: Use a state machine in the DB (`PENDING_DELETE`), perform the external network call, and then finalize the DB deletion"], ["S3 is hiding the files from the database"]),

    # Group 15: Concurrency, Threading, Async IO
    ("B62_15_1", "concept", "hard", "concept", ["Concurrency"], "What is the difference between an OS-level Thread (Java Threads, pthreads) and a User-Space Thread (Go Goroutines, Java Virtual Threads), and why does it matter for backend scalability?", "An OS-level thread is heavily managed by the Linux Kernel. It requires allocating a massive 1MB memory stack, and switching between them (Context Switching) requires expensive CPU traps into kernel mode. A backend server will crash if you spawn 10,000 OS threads. User-Space threads (Goroutines/Virtual Threads) are managed entirely by the language runtime in user-space. They start with a tiny 2KB stack and are multiplexed onto a small pool of OS threads. When a Goroutine makes a blocking DB call, the Go runtime instantly pauses it and swaps in another Goroutine on the same OS thread without ever asking the Linux kernel. This allows a single server to effortlessly run 1,000,000 concurrent Goroutines.", ["OS Threads: Require heavy 1MB memory stacks and expensive kernel-level context switching (caps at a few thousand)", "User-Space Threads (Goroutines/Virtual Threads): Tiny 2KB stacks managed by the language runtime, avoiding kernel traps", "Allows backends to effortlessly handle millions of concurrent blocking I/O connections without memory exhaustion"], ["OS threads wear uniforms, user threads wear casual clothes"]),
    ("B62_15_2", "diagnose", "medium", "debugging", ["Concurrency"], "Your Python FastAPI (using `async def`) application makes an HTTP request to an external API. The developer used the `requests.get()` library instead of `httpx.AsyncClient`. During a load test, the API handles exactly 1 request at a time, performing terribly. Why did using `requests.get()` destroy the asynchronous framework?", "The `requests` library is fully synchronous and blocking. In an async framework (Node.js, FastAPI, Asyncio), there is a single main Event Loop thread. When `requests.get()` is called, it physically blocks the entire OS thread waiting for network I/O. The Event Loop is paralyzed and cannot accept or process any other incoming HTTP connections until that specific network call finishes. To fix this, you must use an asynchronous, non-blocking HTTP client (like `httpx` or `aiohttp`), which yields control back to the Event Loop while waiting for the network response, allowing the server to handle thousands of concurrent requests.", ["Async frameworks rely on a single Event Loop thread yielding control during I/O waits", "Synchronous libraries (`requests`) physically block the entire OS thread, halting the Event Loop completely", "Fix: Use native asynchronous libraries (`httpx`, `aiohttp`) that yield control via `await`"], ["The requests library was deprecated in 1995"]),
    ("B62_15_3", "implement", "hard", "implement", ["Concurrency"], "How do you implement a 'Worker Pool' in Go (Golang) to process 1,000,000 jobs from a Kafka queue without spawning 1,000,000 Goroutines and crushing the database connection pool?", "While Go can easily spawn 1 million Goroutines, doing so will instantly open 1 million concurrent connections to your PostgreSQL database, crashing it. You must constrain concurrency using a Worker Pool and Channels. 1) Create a buffered Go Channel (e.g., `jobs = make(chan Job, 1000)`). 2) Spawn exactly a fixed number of worker Goroutines (e.g., 50). 3) Each worker runs an infinite `for job := range jobs` loop, processing one job at a time. 4) The main Kafka consumer reads the 1 million jobs and blindly pushes them into the `jobs` channel. The channel provides natural backpressure; if the workers are busy, the channel fills up, and the Kafka consumer automatically pauses reading.", ["Spawning unbound Goroutines will instantly exhaust downstream Database Connection Pools", "Implement a fixed-size Worker Pool (e.g., 50 Goroutines) reading from a shared buffered Channel", "The channel provides natural backpressure, limiting concurrency and protecting downstream dependencies"], ["You build a swimming pool for the workers in the datacenter"]),
    ("B62_15_4", "tradeoff", "medium", "tradeoff", ["Concurrency"], "What is the architectural tradeoff of using a 'Shared-Nothing' event loop architecture (Node.js) versus a 'Shared-Memory' multi-threaded architecture (Java/C#)?", "Shared-Memory (Java) allows multiple threads to access and mutate the exact same object in RAM concurrently. This is incredibly fast for complex data processing, but the severe tradeoff is 'Thread Safety'. Developers must meticulously use Mutexes and Locks to prevent Race Conditions. A single missing lock corrupts the data. Node.js (Shared-Nothing) uses a single thread per process. You mathematically cannot have a race condition on a variable in RAM, eliminating the need for complex locks. The tradeoff is that Node.js cannot utilize multi-core CPUs for heavy computation without spawning separate child processes, which cannot easily share RAM and must communicate via slower Inter-Process Communication (IPC).", ["Shared-Memory (Java): Fast computation across CPU cores, but requires complex Mutexes/Locks to prevent Race Conditions", "Shared-Nothing (Node): Single-threaded, mathematically immune to RAM race conditions, vastly simpler to code", "Tradeoff: Node.js cannot utilize multiple CPU cores for heavy computation without complex Inter-Process Communication (IPC)"], ["Shared nothing means the developers don't talk to each other"]),
    ("B62_15_5", "scenario", "medium", "scenario", ["Concurrency"], "Your backend executes a batch job that resizes 50 images. You rewrite the loop using `Promise.all()` (in JS) or `async.gather()` (in Python) to process them concurrently instead of sequentially. The execution time drops from 50 seconds to 2 seconds. However, when 10 users trigger this job simultaneously, the server crashes. Why?", "When you used `Promise.all()`, you unleashed unbounded concurrency. Processing 1 image takes 100MB of RAM. Processing 50 sequentially takes 100MB total (memory is freed after each). Processing 50 concurrently takes 5GB of RAM instantly. When 10 users hit the endpoint, `Promise.all()` attempts to process 500 images simultaneously, demanding 50GB of RAM, triggering an immediate OOMKill (Out of Memory). To fix this, you must strictly limit concurrency using a library like `p-limit` or a semaphore, ensuring `Promise.all()` only ever processes batches of 5 images concurrently, balancing speed and memory safety.", ["`Promise.all()` executes all async tasks simultaneously (Unbounded Concurrency)", "Concurrent heavy tasks multiply memory footprint instantly, causing OOMKilled crashes under load", "Fix: Throttle the concurrency using a Semaphore or batching library (e.g., `p-limit(5)`) to process chunks safely"], ["The images got tangled together in the CPU"]),
    ("B62_15_6", "explain", "hard", "explain", ["Concurrency"], "Explain the 'ABA Problem' in lock-free concurrent programming (e.g., using Compare-And-Swap variables).", "In lock-free programming, a thread reads a variable (sees value 'A'). It calculates a new value. Before it saves, it uses a CPU-level Compare-And-Swap (CAS) instruction: 'Only save this if the value is still A'. However, while it was calculating, Thread 2 changed the value to 'B', and then Thread 3 changed it BACK to 'A'. The original thread's CAS check sees 'A' and blindly assumes nothing has changed, succeeding the write. But the system state *did* change (the ABA sequence), which can corrupt lock-free data structures like linked lists. It is solved by attaching an incrementing version number to the pointer, so the check becomes 'Is it still A and version 1?'.", ["Occurs in lock-free concurrency (CAS) when a value changes from A to B, and back to A", "A thread checks the value, sees 'A', and falsely assumes no other thread modified the state in the interim", "Fix: Use stamped/versioned pointers so the CAS checks both the value and an incrementing version counter"], ["ABA is an acronym for Always Be Async"])
]

def run_batch():
    # Load all existing records to do deduplication
    with open(OUT, "r", encoding="utf-8") as f:
        existing = [json.loads(line) for line in f if line.strip()]

    print(f"Loaded {len(existing)} existing records.")
    
    for q in Q:
        if LEAK.search(q[5]) or LEAK.search(q[6]):
            print(f"PROMPT LEAK DETECTED in: {q[5]}")
            sys.exit(1)
            
    existing_texts = [ex["question"] for ex in existing]
    new_texts = [q[5] for q in Q]
    
    vec = TfidfVectorizer(stop_words="english", ngram_range=(1,2))
    all_texts = existing_texts + new_texts
    vec.fit(all_texts)
    
    existing_vecs = vec.transform(existing_texts)
    new_vecs = vec.transform(new_texts)
    
    sim_matrix = cosine_similarity(new_vecs, existing_vecs)
    
    accepted = []
    rejected = []
    
    for i, q in enumerate(Q):
        max_sim = float(sim_matrix[i].max()) if sim_matrix.shape[1] > 0 else 0
        if max_sim > 0.85:
            print(f"REJECTED (Sim: {max_sim:.2f}): {q[5][:50]}...")
            rejected.append(q)
        else:
            accepted.append(q)
            
    print(f"Accepted {len(accepted)} / {len(Q)} questions (Part 5).")
    
    new_records = []
    for q in accepted:
        rec = {
            "primary_role": ROLE,
            "applicable_roles": ["Systems Engineer", "Software Engineer"],
            "primary_skill": q[4][0],
            "secondary_skills": q[4][1:] if len(q[4]) > 1 else [],
            "technology": "Backend Core",
            "topic": q[4][0] if len(q[4]) > 0 else "General",
            "category": "Software Engineering",
            "intent": q[1],
            "difficulty": q[2],
            "question_type": q[3],
            "question": q[5],
            "expected_answer": q[6],
            "evaluation_rubric": {
                "strong_indicators": q[7],
                "weak_indicators": q[8]
            },
            "id": str(uuid.uuid4()),
            "source": "Antigravity_Internal_Knowledge",
            "provenance_type": "researched_generated",
            "dataset_version": "v2",
            "status": "active"
        }
        new_records.append(rec)
        
    with open(OUT, "a", encoding="utf-8") as f:
        for r in new_records:
            f.write(json.dumps(r) + "\n")
            
    # Final audit reporting
    with open(OUT, "r", encoding="utf-8") as f:
        final_existing = [json.loads(line) for line in f if line.strip()]
        
    role_counts = Counter(r["primary_role"] for r in final_existing)
    
    print("\n========================================")
    print("POST-BATCH AUDIT")
    print("========================================")
    print(f"Batch: 62")
    print(f"Target role: {ROLE}")
    print(f"Attempted: {len(Q)}")
    print(f"Accepted: {len(accepted)}")
    print(f"Rejected: {len(rejected)}")
    print(f"Replacement count: 0")
    print(f"Cumulative total: {len(final_existing)}")
    print(f"{ROLE} total: {role_counts[ROLE]}")
    
    sha256 = hashlib.sha256()
    with open(OUT, 'rb') as f:
        while chunk := f.read(8192):
            sha256.update(chunk)
            
    print(f"\nFinal SHA256: {sha256.hexdigest()}")

if __name__ == "__main__":
    run_batch()
