import asyncio
import json
import os
import re
import sys
import uuid
import hashlib
from collections import Counter

from dotenv import load_dotenv
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
load_dotenv()

BACKEND_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_DIR = os.path.join(BACKEND_DIR, "data")
OUT = os.path.join(DATA_DIR, "interview_question_bank_v2_generated.jsonl")

ROLE = "ML Engineer"
LEAK = re.compile(r"(generate a question|generate \d+ questions|return only json|phase 4c gap plan|"
                  r"generation batch|candidate generation|system instructions|do not proceed|"
                  r"awaiting authorization|minimum target|generation pipeline|"
                  r"batch \d+ generation|expected answer|strong indicator|weak indicator|as an ai|"
                  r"here is the question|\bprompt text\b)", re.I)

Q = [
    # Group 1: Distributed Training Systems
    ("B59_1_1", "concept", "medium", "concept", ["Distributed Training"], "Explain the difference between Data Parallelism and Model Parallelism in distributed Deep Learning.", "Data Parallelism duplicates the entire model across multiple GPUs; each GPU processes a different mini-batch of data, and gradients are synchronized (All-Reduce) at the end of the step. Model Parallelism splits a single massive model (which cannot fit in one GPU's VRAM) across multiple GPUs; each GPU computes a specific layer or tensor slice of the model sequentially for the same batch of data.", ["Data Parallelism duplicates the model, splits the data batch, and synchronizes gradients", "Model Parallelism splits the model layers/tensors across GPUs when it doesn't fit in VRAM", "Data parallel is communication-bound (gradients), Model parallel is latency-bound (sequential layers)"], ["Data parallelism runs on CPUs while Model parallelism runs on GPUs"]),
    ("B59_1_2", "diagnose", "hard", "debugging", ["Distributed Training"], "You are training a model using PyTorch DistributedDataParallel (DDP) on 8 GPUs. Training speed is terrible. GPU utilization is bouncing between 100% and 0%. CPU utilization is at 100%. What is the bottleneck, and how do you fix it?", "This is a DataLoader bottleneck, often called the 'I/O wall'. The GPUs finish computing the forward/backward pass instantly (100%), then sit completely idle (0%) waiting for the CPU to fetch, decode, and augment the next batch of images/text from the disk. To fix this, you must increase `num_workers` in the DataLoader (multiprocessing), move data augmentations to the GPU, use faster disk I/O (NVMe), or prefetch/cache the dataset in RAM.", ["The CPU cannot feed data to the GPUs fast enough (I/O or augmentation bottleneck)", "GPUs sit idle (0% utilization) waiting for the next batch", "Fix by increasing `num_workers`, prefetching, or moving augmentations to the GPU"], ["The GPUs are overheating and throttling"]),
    ("B59_1_3", "implement", "hard", "implement", ["Distributed Training"], "How do you implement 'Gradient Accumulation', and why is it used?", "Gradient Accumulation is used when your GPU VRAM is too small to fit the desired target batch size (e.g., you want batch size 256, but only 32 fits in VRAM). Instead of calling `optimizer.step()` and `optimizer.zero_grad()` after every forward/backward pass of size 32, you accumulate the gradients over 8 consecutive passes (8 * 32 = 256). Only on the 8th pass do you call `optimizer.step()` to update the weights. It mathematically simulates the exact same gradient update as a batch size of 256 using minimal memory.", ["Used to simulate large batch sizes when VRAM is too small", "Run multiple forward/backward passes, accumulating gradients without updating weights", "Call `optimizer.step()` and `zero_grad()` only after N passes to complete the simulated batch"], ["It means saving gradients to an SQL database for later analysis"]),
    ("B59_1_4", "tradeoff", "medium", "tradeoff", ["Distributed Training"], "What is the tradeoff of using Automatic Mixed Precision (AMP / FP16) during neural network training?", "AMP drastically reduces GPU VRAM usage (FP16 takes half the memory of FP32) and massively increases Tensor Core throughput, accelerating training speed by 2-3x. The severe tradeoff is numerical instability. FP16 has a very limited dynamic range; tiny gradients will underflow (become exactly 0.0), causing the network to stop learning or weights to diverge. This forces the use of a 'Gradient Scaler' to artificially multiply gradients before the FP16 backward pass and divide them afterward.", ["Saves 50% VRAM and massively accelerates training speed using Tensor Cores", "Tradeoff: Numerical instability (gradient underflow due to limited FP16 range)", "Requires implementing Gradient Scaling to prevent gradients from rounding to zero"], ["FP16 models can only predict 16 possible answers"]),
    ("B59_1_5", "scenario", "hard", "scenario", ["Distributed Training"], "You are training a 5B parameter model on a single GPU. It immediately throws a CUDA Out of Memory (OOM) error. You cannot afford more GPUs, and you are already using batch size 1 and AMP. How do you train it?", "You must implement 'Gradient Checkpointing' (Activation Checkpointing). During the forward pass, a neural network stores all intermediate activations in VRAM so it can compute derivatives during the backward pass. This consumes massive memory. Gradient Checkpointing drops the activations from VRAM after the forward pass. During the backward pass, it dynamically re-computes the necessary activations on-the-fly. This drastically reduces VRAM usage (O(sqrt(N)) instead of O(N)) at the tradeoff of roughly 25-30% slower training time (due to redundant compute).", ["Use Gradient Checkpointing (Activation Checkpointing)", "Trades compute for memory by dropping forward pass activations from VRAM", "Re-computes activations dynamically during the backward pass, preventing OOM"], ["Just upload the model to the cloud and it will run infinitely"]),
    ("B59_1_6", "explain", "medium", "explain", ["Distributed Training"], "Explain the 'All-Reduce' operation in the context of Data Parallel training.", "In Data Parallel training, each GPU computes gradients on its own local slice of the data batch. If left alone, each GPU would update its weights differently, breaking the model. 'All-Reduce' is a collective communication algorithm (often using Ring-All-Reduce) where every GPU shares its gradients over the network (NVLink/PCIe), sums or averages them together, and returns the globally averaged gradient to every single GPU. This ensures every GPU performs the exact same weight update and remains perfectly synchronized.", ["A collective network operation to synchronize gradients across all GPUs", "Aggregates (sums/averages) local gradients and broadcasts the global result back", "Ensures all replica models perform the exact same weight update"], ["All-reduce means compressing the dataset before training"]),
    ("B59_1_7", "concept", "easy", "concept", ["Distributed Training"], "What does 'FSDP' (Fully Sharded Data Parallel) do in large-scale model training?", "Standard DDP requires every GPU to hold a complete copy of the model weights, optimizer states, and gradients in VRAM, which makes it impossible to train a 70B parameter model. FSDP solves this by 'sharding' (splitting) the model weights, gradients, and optimizer states across all available GPUs. When a specific GPU needs a layer for a forward/backward pass, it briefly fetches it from the other GPUs via the network, computes, and instantly discards it, vastly expanding the size of the model you can train.", ["Shards/splits model weights, gradients, and optimizer states across all GPUs", "Prevents redundant VRAM waste (DDP keeps a full copy on every GPU)", "Fetches layers dynamically across the network only when needed for computation"], ["It splits the dataset into smaller folders"]),
    ("B59_1_8", "diagnose", "medium", "debugging", ["Distributed Training"], "You are training a massive deep learning model. Around epoch 5, the Loss suddenly prints as `NaN` (Not a Number), and the model is permanently ruined. What are the common causes of a NaN loss explosion?", "NaN loss is almost always caused by numerical instability blowing up to infinity or dividing by zero. Common causes: 1) Exploding gradients (fix: implement Gradient Clipping). 2) A bad learning rate that is vastly too high (fix: use a learning rate warmup). 3) Log(0) or Divide-by-Zero errors in the custom loss function or Softmax layer (fix: add an `epsilon` like 1e-8 to denominators/logs). 4) Corrupted training data containing NaN or infinite values.", ["Exploding gradients pushing weights to infinity (Fix: Gradient Clipping)", "Learning rate is far too high (Fix: LR Warmup / scheduling)", "Divide-by-zero or log(0) in loss function (Fix: add epsilon 1e-8)"], ["NaN means Not a Network, your internet dropped"]),
    ("B59_1_9", "architecture", "hard", "architecture", ["Distributed Training"], "How do you architect a fault-tolerant distributed training job on preemptible (Spot) cloud GPUs?", "Spot instances can be terminated by the cloud provider with only a 30-second warning. To architect fault tolerance, you must implement 1) High-frequency distributed checkpointing to a remote object store (e.g., S3). 2) A distributed orchestrator (like Torch Elastic / Torchrun) that intercepts the termination signal (SIGTERM). 3) When SIGTERM is caught, all nodes pause, finalize an emergency atomic checkpoint, and gracefully exit. 4) An auto-scaling group immediately provisions new spot instances, which download the latest checkpoint and resume training from that exact step.", ["Use Torch Elastic/Torchrun to handle dynamic node joining/leaving", "Intercept the 30-second SIGTERM to trigger an emergency atomic checkpoint to S3", "Auto-provision new nodes that resume seamlessly from the latest checkpoint"], ["Just ask the cloud provider politely not to turn them off"]),
    ("B59_1_10", "tradeoff", "hard", "tradeoff", ["Distributed Training"], "What is the tradeoff of using Pipeline Parallelism compared to pure Tensor Parallelism for splitting a large model?", "Pipeline Parallelism splits the model vertically (e.g., GPU 1 gets layers 1-10, GPU 2 gets 11-20). The tradeoff is 'Bubble Time': GPU 2 sits idle waiting for GPU 1 to finish its layers, severely hurting GPU utilization (requires micro-batching to mitigate). However, Pipeline Parallelism requires very little network bandwidth (only passing final layer activations). Tensor Parallelism splits the math horizontally (e.g., splitting a single matrix multiplication across GPUs). It has zero bubble time, but requires massive, constant network communication (All-Reduce) between GPUs, meaning it can only be used within a single server node connected by ultra-fast NVLink.", ["Pipeline splits layers sequentially (high idle 'bubble time', low network bandwidth)", "Tensor splits matrix math within layers (zero bubble time, massive network bandwidth)", "Tradeoff: Tensor is bound to single nodes (NVLink); Pipeline scales across slow networks"], ["Pipeline parallelism uses water cooling, Tensor parallelism uses air cooling"]),

    # Group 2: Production Serving Architecture
    ("B59_2_1", "concept", "medium", "concept", ["Model Deployment"], "What is the difference between 'Online Inference' and 'Batch Inference'?", "Online Inference (or Real-Time Inference) serves predictions synchronously via a REST/gRPC API. The user waits milliseconds for the response. It prioritizes ultra-low latency and requires expensive, always-on servers. Batch Inference (or Offline Inference) processes millions of records asynchronously on a scheduled basis (e.g., nightly Spark job). The results are saved to a database for later retrieval. It prioritizes massive throughput and cost efficiency, running on ephemeral compute clusters.", ["Online: Synchronous API, real-time, prioritizes low latency (milliseconds)", "Batch: Asynchronous scheduled jobs (e.g., nightly), prioritizes massive throughput", "Online requires always-on servers; Batch uses ephemeral compute and saves to a DB"], ["Online means it needs wifi, batch means it works offline"]),
    ("B59_2_2", "diagnose", "hard", "debugging", ["Model Deployment"], "Your online PyTorch model API processes single requests in 50ms. However, during a traffic spike of 500 requests per second, API latency skyrockets to 5 seconds, and GPU utilization is only 30%. Why is latency awful while the GPU is underutilized?", "You are processing requests sequentially (batch size = 1). A GPU processing a single image/text input leaves 99% of its CUDA cores idle, creating a severe compute bottleneck on the web server threads while the GPU starves. To fix this, you must implement 'Dynamic Batching' (using a serving layer like Triton or Ray Serve). The server pauses for ~10ms, aggregates 32 incoming concurrent requests into a single tensor, and sends one batched inference call to the GPU. This massively spikes GPU utilization and restores low latency under heavy load.", ["Processing requests sequentially (batch size 1) starves the massive parallelism of the GPU", "Server threads queue up waiting for sequential inference, causing latency spikes", "Fix by implementing Dynamic Batching (aggregating concurrent requests before GPU execution)"], ["The model weights became too heavy during the spike"]),
    ("B59_2_3", "implement", "medium", "implement", ["Model Deployment"], "How do you implement 'Shadow Deployment' for a high-risk ML model?", "In a Shadow Deployment, the new V2 model is deployed to production alongside the stable V1 model. 100% of live user traffic is routed to V1, and V1's prediction is returned to the user. Asynchronously, a copy of that exact same traffic is sent to the V2 model. V2's predictions are logged to a database but NEVER returned to the user. Data scientists compare V1 and V2's logs over a week to ensure V2's predictions, latency, and error rates are safe before actually shifting live user traffic to it.", ["Deploy V2 alongside V1 in production", "Route live traffic to both, but only return V1's predictions to the user", "Log V2's predictions silently for offline comparison to ensure safety and correctness"], ["You paint the model servers black to hide them from hackers"]),
    ("B59_2_4", "tradeoff", "medium", "tradeoff", ["Model Deployment"], "What is the architectural tradeoff of deploying an ML model embedded directly as a library inside the backend API (e.g., loading the .pkl in FastAPI) versus deploying it as a standalone microservice (e.g., Triton/TFServing)?", "Embedding the model in the monolith backend provides zero network latency (no HTTP calls) and simplifies deployment. The severe tradeoff is that the model is locked to the backend's scaling profile. If the web server runs on CPU, the model runs on CPU. Furthermore, heavy model inference will block the web server's async event loop, crashing the API. A standalone microservice adds network latency, but allows you to scale the ML hardware (GPUs) independently from the web servers, optimize dynamic batching, and update models without restarting the entire backend API.", ["Embedded: Zero network latency, simple deployment. Tradeoff: Blocks the web server event loop and couples scaling", "Standalone Microservice: Adds HTTP/gRPC network latency", "Tradeoff: Microservice allows independent GPU scaling, dynamic batching, and isolated failure domains"], ["Embedded models cannot be updated ever again"]),
    ("B59_2_5", "scenario", "hard", "scenario", ["Model Deployment"], "You deploy a Serverless AWS Lambda function to serve a lightweight Scikit-Learn model. Most requests take 200ms. But every 15 minutes, a user experiences a 6-second latency spike. How do you permanently eliminate this?", "This is a 'Cold Start' problem. When the Lambda is idle, AWS tears down the container. The next request forces AWS to provision a new container, download the model artifact from S3, load it into RAM, and initialize the Python runtime, causing a massive latency spike. To fix this permanently in a Serverless environment, you must use 'Provisioned Concurrency' (keeping X containers permanently warm), or move off Serverless to an always-on container service (ECS/EKS) so the model remains continuously loaded in RAM.", ["Cold Start: Serverless containers are destroyed when idle", "New requests require provisioning, downloading the model, and initializing Python", "Fix by enabling Provisioned Concurrency or moving to an always-on container architecture"], ["The user's internet connection drops exactly every 15 minutes"]),
    ("B59_2_6", "explain", "hard", "explain", ["Model Deployment"], "Explain how ONNX (Open Neural Network Exchange) and TensorRT optimize model serving.", "Data scientists train models in PyTorch or TensorFlow, which contain heavy debugging overhead and unoptimized Python code. ONNX provides a standardized, framework-agnostic graph representation. You export the PyTorch model to ONNX, stripping away Python dependencies. Then, you compile the ONNX graph using TensorRT (Nvidia's inference optimizer). TensorRT performs layer fusion (combining multiple math operations into one), precision calibration (FP32 to INT8), and hardware-specific kernel auto-tuning for your exact GPU architecture, often resulting in 3-5x faster inference latency.", ["ONNX converts framework-specific models into a standardized, Python-free computation graph", "TensorRT compiles that graph specifically for the target Nvidia GPU architecture", "Optimizes via layer fusion, quantization (INT8), and kernel auto-tuning for massive speedups"], ["They compress the model into a zip file for faster downloading"]),
    ("B59_2_7", "concept", "easy", "concept", ["Model Deployment"], "What is a 'Canary Deployment' in MLOps?", "A Canary Deployment minimizes risk when releasing a new model. Instead of swapping 100% of traffic to the new V2 model immediately, you route a tiny fraction (e.g., 5%) of live traffic to V2, while 95% remains on V1. You closely monitor V2's error rates, latency, and business metrics (like click-through rate) for a few hours. If V2 performs well, you gradually dial up the traffic (20%, 50%, 100%). If V2 throws errors, you instantly rollback the 5% routing, shielding the vast majority of users from the failure.", ["Routes a tiny fraction (e.g., 5%) of live traffic to the new model", "Monitors errors and metrics safely in production before rolling out fully", "Allows instant rollback with minimal user impact if the new model fails"], ["You deploy a literal bird into the server room to detect gas leaks"]),
    ("B59_2_8", "diagnose", "medium", "debugging", ["Model Deployment"], "Your online model server (FastAPI) loads a 4GB model into memory on startup. You set the Gunicorn workers to 8 to handle concurrent requests on a 16GB RAM server. The server instantly crashes on startup with an Out Of Memory (OOM) error. Why?", "When you use Gunicorn with standard multiprocessing workers, each of the 8 worker processes loads its *own* independent copy of the 4GB model into RAM. 8 workers * 4GB = 32GB of RAM required, instantly crashing your 16GB server. To fix this, you must either drastically reduce the worker count, load the model into shared memory before forking (pre-load), or switch to a dedicated serving framework (like Triton/Ray) that handles memory mapping intelligently across threads.", ["Standard multiprocessing loads a complete copy of the model into RAM for *every* worker", "8 workers * 4GB model = 32GB RAM required (exceeding the 16GB host)", "Fix by reducing workers, using shared memory, or a dedicated serving framework"], ["The model weights expanded due to heat in the server rack"]),
    ("B59_2_9", "architecture", "hard", "architecture", ["Model Deployment"], "How do you architect an asynchronous inference pipeline for processing heavy video files (e.g., 5 minutes of compute per video) without blocking the user's web request?", "You cannot process a 5-minute video synchronously on an HTTP request; the connection will timeout and the web server will block. You must use an Event-Driven / Pub-Sub architecture. 1) The user uploads the video to S3. 2) The web server instantly returns a HTTP 202 Accepted with a `job_id`. 3) The web server drops a message containing the S3 URI into a Message Queue (Kafka/RabbitMQ/SQS). 4) A fleet of autoscaling GPU worker nodes pulls messages from the queue, downloads the video, runs inference, and writes the result to a Database. 5) The client polls the backend with the `job_id` (or receives a WebSocket ping) to retrieve the final result.", ["Never run heavy compute synchronously on HTTP requests (causes timeouts/blocking)", "Use an Event-Driven architecture: Web server returns 202 Accepted and puts a job in a Queue", "Asynchronous GPU workers pull from the queue, process, and write to a DB. Client polls for results"], ["Just increase the HTTP timeout setting in Nginx to 600 seconds"]),
    ("B59_2_10", "tradeoff", "medium", "tradeoff", ["Model Deployment"], "What is the tradeoff of running Machine Learning inference on the Edge (e.g., directly on the user's mobile phone) versus in the Cloud?", "Edge inference provides zero network latency, works completely offline, and guarantees strict user privacy since the raw data (photos/voice) never leaves the device. The tradeoff is severe constraints on model complexity. The model must be tiny (quantized/pruned) to fit in mobile RAM, it drains the user's battery, and it cannot leverage massive cloud GPUs for complex architectures. Furthermore, updating the model requires the user to manually download an App Store update, unlike Cloud where updates are instantaneous.", ["Edge provides zero latency, offline capability, and total data privacy", "Tradeoff: Models must be tiny, sacrificing accuracy, and they drain user battery", "Tradeoff: Updating models requires a slow App Store rollout rather than a central cloud update"], ["Edge inference forces the phone to balance on its physical edge"]),

    # Group 3: Advanced Feature Engineering
    ("B59_3_1", "concept", "medium", "concept", ["Feature Engineering"], "What is 'Point-in-Time Correctness' (Time Travel) in feature engineering, and why is it critical for training data?", "Point-in-Time correctness ensures that when training a model on historical data, you only provide the model with features that were actually known *at that exact second in time*. If you are predicting a loan default on Jan 1st, but your SQL join accidentally grabs the user's bank balance from Jan 5th, you have introduced Target Leakage. The model will look like a genius in training and fail catastrophically in production. Feature Stores handle Point-in-Time joins ('As-Of' joins) automatically to prevent this future data leakage.", ["Ensures the model only sees data that was known at the exact historical timestamp of the prediction", "Prevents Target Leakage (accidentally including future data in the training set)", "Feature stores use 'As-Of' joins to automatically enforce temporal correctness"], ["It means ensuring the server clock is synced via NTP"]),
    ("B59_3_2", "diagnose", "hard", "debugging", ["Feature Engineering"], "Your fraud detection model achieves 99% accuracy in training and offline validation. In production, it completely fails (50% accuracy). You verify the code is identical. You notice the training data used a column `account_status`, which in production is updated by the legal team 3 days after an account is flagged. What happened?", "This is a catastrophic case of Target Leakage (Data Leakage). The `account_status` column in the data warehouse contains information from the *future* relative to the moment the prediction was made. The model learned a trivial rule: 'If account_status is Suspended, predict Fraud.' In production, at the exact millisecond the transaction occurs, the legal team hasn't reviewed it yet, so `account_status` is always 'Active'. The model is flying blind. You must remove all features that are realized *after* the prediction timestamp.", ["Target Leakage: The model trained on a feature that was updated *after* the target event occurred", "The model learned to rely on future information ('account_status') that doesn't exist at prediction time", "Fix by strictly removing temporal leak features or enforcing Point-in-Time correctness"], ["The hackers adapted to the model instantly"]),
    ("B59_3_3", "implement", "medium", "implement", ["Feature Engineering"], "How do you implement Target Encoding for a high-cardinality categorical feature (like `zip_code` with 40,000 unique values), and how do you prevent it from overfitting?", "One-Hot Encoding 40,000 zip codes destroys memory and creates sparse trees. Target Encoding replaces the categorical string (e.g., '10001') with the historical average of the target variable for that specific zip code (e.g., 0.15 default rate). To prevent massive overfitting (e.g., a zip code with only 1 user who defaulted gives a 100% default rate), you MUST implement Smoothing (mixing the zip code average with the global average based on sample size) and compute the encodings using K-Fold Cross-Validation so the current row's target doesn't leak into its own encoding.", ["Replaces a categorical string with the historical average of the target variable for that category", "Prevents explosive memory/sparsity issues of One-Hot Encoding high-cardinality features", "Must use Smoothing (Bayesian average) and K-Fold Out-of-Fold calculation to prevent overfitting/leakage"], ["Just delete the zip code column entirely"]),
    ("B59_3_4", "tradeoff", "hard", "tradeoff", ["Feature Engineering"], "What is the architectural tradeoff of using a centralized Feature Store versus allowing Data Scientists to write custom SQL pipelines for every model?", "Custom SQL pipelines allow Data Scientists to move extremely fast in notebooks (high flexibility). The tradeoff is 'Training-Serving Skew'. The DS writes Pandas logic in training, but a backend engineer must rewrite that exact logic in Java/Go for production serving. Minor discrepancies in how rolling averages are calculated destroy model accuracy. A Feature Store creates a single centralized repository. You define the feature logic once. The Feature Store serves the exact same historical data to the training notebook (offline) and the exact same low-latency data to the API (online), guaranteeing parity at the cost of rigid infrastructural overhead.", ["Custom SQL is highly flexible but causes Training-Serving Skew (rewriting Pandas logic into Java/Go)", "Feature Stores guarantee parity by serving the exact same logic for offline training and online APIs", "Tradeoff: Feature Stores introduce heavy, rigid infrastructural overhead and strict definitions"], ["Feature stores cost money, SQL is free"]),
    ("B59_3_5", "scenario", "medium", "scenario", ["Feature Engineering"], "You are building a real-time recommendation engine. The model needs to know the user's `total_clicks_last_10_minutes`. Calculating this with a massive SQL query over the data warehouse takes 30 seconds. How do you engineer this feature for a 50ms API?", "You cannot use a Data Warehouse (Snowflake/BigQuery) for real-time online inference features. You must implement a Streaming Aggregation architecture. Raw click events flow into an event bus (Kafka). A streaming processor (like Apache Flink or Spark Structured Streaming) calculates the tumbling/sliding 10-minute window aggregation in real-time. The processor constantly writes the updated integer to an ultra-fast in-memory Key-Value store (Redis / Online Feature Store). The model API simply does an O(1) Redis lookup (`GET user:123:clicks`), returning the feature in 1 millisecond.", ["Data Warehouses are too slow for real-time online feature calculation", "Use a streaming processor (Kafka + Flink) to pre-calculate sliding window aggregations in real-time", "Write the result to an in-memory Key-Value store (Redis) for O(1) millisecond retrieval during inference"], ["Buy a faster SSD for the SQL database"]),
    ("B59_3_6", "explain", "medium", "explain", ["Feature Engineering"], "Explain 'Training-Serving Skew' and provide a common example of how it occurs.", "Training-Serving Skew happens when the data pipeline used to train the model behaves slightly differently than the pipeline providing features in production, causing performance to crash. Example: A Data Scientist trains a model using `pandas.fillna(0)` to handle missing ages. In production, the backend engineer writes the API in Go and handles missing ages by omitting the JSON key entirely, causing the model to receive a `NULL` or throw an error. The model sees a different data distribution in production than it did in training.", ["A discrepancy between how features are calculated in offline training vs online production", "Causes production model performance to degrade silently or crash", "Example: Different handling of missing values (Pandas fillna vs Go JSON omission)"], ["It means the server is physically tilted on the rack"]),
    ("B59_3_7", "concept", "easy", "concept", ["Feature Engineering"], "What is 'Feature Scaling' (Standardization vs Normalization), and which ML algorithms strictly require it?", "Feature scaling transforms numerical data to a similar scale. Normalization (Min-Max) squashes data between 0 and 1. Standardization (Z-score) centers data at mean 0 with standard deviation 1. It is strictly required for distance-based algorithms (KNN, SVM, K-Means) and gradient descent algorithms (Neural Networks, Logistic Regression) because a feature with massive magnitude (like Salary $100,000) will mathematically dominate a small feature (like Age 30). Tree-based algorithms (Random Forest, XGBoost) do NOT require scaling because they split on rank-order thresholds.", ["Transforms numerical data to a standard range (e.g., 0 to 1, or mean 0 / std 1)", "Strictly required for distance-based (KNN, SVM) and Gradient Descent algorithms (Neural Networks)", "Tree-based models (XGBoost) do not require it as they split on rank/order"], ["It means weighing the data on a physical scale"]),
    ("B59_3_8", "diagnose", "medium", "debugging", ["Feature Engineering"], "You are training an XGBoost model. You notice that a feature called `customer_id` (an arbitrary integer) has the highest Feature Importance in the model. What is happening, and how do you fix it?", "This is an extreme case of Overfitting on high-cardinality noise. `customer_id` is a unique identifier; it contains no generalizable information. Because tree models can split infinitely, XGBoost essentially memorized the exact historical mapping: 'If customer_id == 1042, then predict Purchase.' The model will fail completely on any new customer. You must permanently drop unique identifiers, primary keys, and arbitrary hash strings from the dataset before training.", ["XGBoost memorized the exact historical mapping of the unique identifier (Overfitting)", "Unique IDs contain no generalizable signal, causing complete failure on new data", "Fix by permanently dropping primary keys, unique IDs, and hashes before training"], ["XGBoost is so smart it found a secret pattern in the IDs"]),
    ("B59_3_9", "architecture", "hard", "architecture", ["Feature Engineering"], "How does an 'Online Feature Store' synchronize with an 'Offline Feature Store' to maintain data consistency?", "The Offline Feature Store is backed by a Data Warehouse (Snowflake) or Data Lake (S3/Parquet) optimized for massive, high-throughput batch queries to create training datasets. The Online Feature Store is backed by a low-latency Key-Value store (Redis/DynamoDB) optimized for millisecond single-row lookups during inference. To synchronize them, you run scheduled 'Materialization Jobs' (e.g., Apache Airflow DAGs). Every hour, the job calculates the latest batch feature values in the Data Warehouse and 'pushes' (syncs) those updated Key-Value pairs into Redis, ensuring the online API has fresh data derived from the offline source of truth.", ["Offline is a Data Warehouse for massive batch training datasets", "Online is a fast Key-Value store (Redis) for millisecond inference lookups", "Materialization Jobs periodically compute features offline and push the latest state to the Online DB"], ["They communicate via telepathy"]),
    ("B59_3_10", "tradeoff", "medium", "tradeoff", ["Feature Engineering"], "What is the tradeoff of handling missing data via 'Mean Imputation' versus 'Iterative Model-Based Imputation' (e.g., KNN Imputer)?", "Mean Imputation (filling blanks with the column average) is blazing fast, computationally trivial, and easy to deploy. The severe tradeoff is that it distorts the variance of the dataset and destroys correlations with other features (e.g., filling all missing 'Income' values with $50k ignores that age/education strongly predict income). Model-based imputation (KNN/MICE) uses other columns to accurately predict the missing value, preserving correlations. The tradeoff is high computational cost and the requirement to deploy a secondary mini-model in production just to calculate features.", ["Mean Imputation is computationally trivial but distorts data variance and destroys correlations", "Model-Based Imputation (KNN/MICE) accurately preserves feature correlations", "Tradeoff: Model-Based is computationally heavy and requires deploying secondary imputation models in production"], ["Mean imputation is mean to the data"])
]

def run_batch():
    with open(OUT, "a", encoding="utf-8") as f:
        for q in Q:
            rec = {
                "primary_role": ROLE,
                "applicable_roles": ["Data Scientist", "Backend Developer"],
                "primary_skill": q[4][0],
                "secondary_skills": q[4][1:] if len(q[4]) > 1 else [],
                "technology": "Machine Learning",
                "topic": q[4][0] if len(q[4]) > 0 else "General",
                "category": "AI/ML",
                "intent": q[1],
                "difficulty": q[2],
                "question_type": q[3],
                "question": q[5],
                "expected_answer": q[6],
                "evaluation_rubric": {
                    "strong_indicators": q[7],
                    "weak_indicators": q[8]
                },
                "id": str(uuid.uuid4()),
                "source": "Antigravity_Internal_Knowledge",
                "provenance_type": "researched_generated",
                "dataset_version": "v2",
                "status": "active"
            }
            f.write(json.dumps(rec) + "\n")
            
    print(f"Appended {len(Q)} questions (Batch 59 Part 1).")

if __name__ == "__main__":
    run_batch()
