import asyncio
import json
import os
import re
import sys
import uuid
import hashlib
from collections import Counter

from dotenv import load_dotenv
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
load_dotenv()

BACKEND_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_DIR = os.path.join(BACKEND_DIR, "data")
OUT = os.path.join(DATA_DIR, "interview_question_bank_v2_generated.jsonl")

ROLE = "Python Developer"
LEAK = re.compile(r"(generate a question|generate \d+ questions|return only json|phase 4c gap plan|"
                  r"generation batch|candidate generation|system instructions|do not proceed|"
                  r"awaiting authorization|minimum target|generation pipeline|"
                  r"batch \d+ generation|expected answer|strong indicator|weak indicator|as an ai|"
                  r"here is the question|\bprompt text\b)", re.I)

Q = [
    # Packaging & Dependency Engineering
    ("B63_3_1", "concept", "medium", "concept", ["Packaging & Tooling"], "In Python packaging, what is the 'Diamond Dependency Problem' (Transitive Conflict), and why does `pip` historically struggle with it?", "The Diamond Problem occurs when your app depends on Library A and Library B. Library A requires `requests >= 2.0`, but Library B strictly requires `requests == 1.5`. The dependencies form a diamond shape pointing to two conflicting versions of `requests`. Historically, `pip` lacked a true strict dependency resolver and would blindly install whichever version it encountered last, silently breaking the other library. Modern `pip` (20.3+) includes a strict backtracking resolver that will explicitly fail the installation with a `ResolutionImpossible` error, forcing the developer to manually align the conflicting dependencies.", ["Occurs when two direct dependencies rely on mutually exclusive versions of the same transitive dependency", "Historically, `pip` would silently overwrite the library, breaking one of the packages at runtime", "Modern `pip` uses a backtracking resolver that halts and throws a strict error instead of silently failing"], ["The diamond dependency problem is when you spend too much money on python packages"]),
    ("B63_3_2", "diagnose", "hard", "debugging", ["Packaging & Tooling"], "Your CI/CD pipeline builds a Docker image using `pip install -r requirements.txt`. Yesterday the build succeeded. Today, the build fails with a massive C++ compilation error related to the `cryptography` package, even though you didn't change any code or versions. Why did this happen?", "This is a 'Wheel vs Source Distribution' (sdist) ABI failure. The `cryptography` package relies on compiled C/Rust extensions. Usually, `pip` downloads a pre-compiled binary 'Wheel' (`.whl`) for your specific Linux architecture (e.g., `manylinux`), which installs instantly. However, if a new version of the package was released *today* but the authors haven't finished uploading the pre-compiled Linux wheels yet, `pip` falls back to downloading the raw Source Code (`.tar.gz`). Your minimal Docker container likely lacks the raw `gcc` or `rustc` build tools required to compile the C-extension from scratch, causing the catastrophic compilation failure.", ["`pip` prefers pre-compiled binary 'Wheels' (.whl) but falls back to Source Distributions (.tar.gz) if a wheel isn't available for the architecture", "If a package updates and lacks a wheel, `pip` tries to compile the C/Rust extension from scratch", "Fix: Use a strict Lockfile (`pip-compile`) with explicit hashes, or pin the exact version to prevent pulling un-wheeled new releases"], ["The cryptography package was hacked by the NSA"]),
    ("B63_3_3", "implement", "medium", "implement", ["Packaging & Tooling"], "How do you enforce 'Lockfile Reproducibility' in a Python project to guarantee that the production server installs the exact same transitive dependency tree as your local laptop?", "A standard `requirements.txt` containing `flask==2.0` is NOT reproducible, because Flask's transitive dependencies (like `Werkzeug` or `Jinja2`) are unpinned and will silently upgrade in production. To guarantee absolute reproducibility, you must use a lockfile tool like `pip-tools` (`pip-compile`), `Poetry`, or `uv`. These tools resolve the entire dependency tree and generate a rigid `requirements.txt` containing explicit versions for EVERY single transitive dependency, alongside their SHA256 cryptographic hashes. Production then installs using `pip install --require-hashes -r requirements.txt`, guaranteeing the exact same byte-for-byte environment.", ["A naive `requirements.txt` only pins top-level dependencies, allowing transitive dependencies to silently upgrade and break production", "Use a lockfile generator (`pip-tools`, `Poetry`) to pin all transitive dependencies explicitly", "Use `--require-hashes` to guarantee byte-for-byte cryptographic reproducibility"], ["You just copy the `site-packages` folder manually from your laptop to the server"]),
    ("B63_3_4", "tradeoff", "hard", "tradeoff", ["Packaging & Tooling"], "What is the tradeoff of using `pip install -e .` (Editable Installs) during local development versus standard installs?", "An Editable Install creates a symlink (via a `.egg-link` file or PEP 660 hooks) pointing directly from the Python `site-packages` directory to your raw source code folder. This is phenomenal for development because any change you make to a `.py` file instantly takes effect without requiring you to re-run `pip install`. The severe tradeoff is accurately testing the 'Build Artifact'. An editable install completely bypasses the standard packaging process (e.g., it ignores `MANIFEST.in`). You might have a file missing from your `setup.py` that works perfectly on your laptop (because the symlink sees it), but crashes in production when built as a Wheel.", ["Editable installs (`-e`) use symlinks, allowing immediate code changes without re-installation", "Tradeoff: It bypasses the actual wheel building process, masking packaging bugs (like missing files in `MANIFEST.in`)", "Code that works perfectly locally via `-e` might be completely missing from the production `.whl` artifact"], ["Editable installs allow you to edit the pip source code directly"]),
    ("B63_3_5", "scenario", "medium", "scenario", ["Packaging & Tooling"], "You manage a massive monorepo with three internal Python packages: `company.auth`, `company.db`, and `company.api`. They are located in separate folders. When you try to import them, Python throws an `ImportError` because `company` doesn't have an `__init__.py`. How do you architect this without modifying `sys.path`?", "This requires the use of 'Implicit Namespace Packages' (PEP 420, introduced in Python 3.3). You must intentionally NOT place an `__init__.py` file in the root `company` directory of any of the three packages. If you omit `__init__.py`, Python's import machinery recognizes `company` as a virtual Namespace Package. It automatically stitches together the contents of all three physically separate directories into a single unified `company` module at runtime, allowing you to `import company.auth` and `import company.db` seamlessly across the monorepo.", ["Do NOT put an `__init__.py` in the root shared folder (`company`)", "This triggers PEP 420 'Implicit Namespace Packages' behavior", "Python will automatically aggregate the contents of multiple separate directories into a single virtual module"], ["You just rename the folders so they don't overlap"]),
    ("B63_3_6", "explain", "medium", "explain", ["Packaging & Tooling"], "Explain what 'Build Isolation' (PEP 517/518) is, and why a `pyproject.toml` file fixes legacy `setup.py` chicken-and-egg dependency problems.", "In legacy Python, to even execute `setup.py`, you already needed to have `setuptools` or `Cython` installed on your machine. This was a chicken-and-egg problem: you couldn't read the package's dependencies without already having its build dependencies installed. PEP 518 introduced `pyproject.toml`, which declares a `[build-system] requires = [\"setuptools\", \"wheel\"]` block. Modern `pip` reads this TOML file (which requires zero code execution to parse), creates a completely isolated, temporary virtual environment, installs the build dependencies into it, builds the Wheel, and then deletes the temporary environment. This guarantees deterministic builds regardless of what the developer has installed globally.", ["Legacy `setup.py` required build tools (like `Cython`) to be installed *before* the script could even be parsed", "`pyproject.toml` statically declares build dependencies in TOML format (no code execution needed)", "`pip` creates an isolated, ephemeral virtual environment just to build the wheel, ensuring clean determinism"], ["Build isolation means building the code in a room with no internet"]),

    # Advanced Multiprocessing
    ("B63_3_7", "concept", "hard", "concept", ["Multiprocessing"], "In Linux, `multiprocessing` defaults to the `fork` start method. Explain how 'Copy-on-Write' (CoW) memory behavior affects RAM usage when you fork 10 Python processes.", "When a parent process forks 10 child processes, the OS does NOT instantly multiply the memory footprint by 10 (which would cause an OOM). Instead, Linux uses Copy-on-Write: all 11 processes share the exact same physical RAM pages. However, Python uses Reference Counting (`ob_refcnt`) for Garbage Collection. The moment a child process even *reads* an object, Python increments the reference count integer on that object. This tiny integer mutation modifies the memory page. The Linux OS detects the mutation and instantly clones the entire 4KB page of RAM specifically for that child (breaking the CoW sharing). Thus, over a few seconds, the entire shared memory pool duplicates 10 times, crashing the server with OOM.", ["Linux uses Copy-on-Write to share RAM across forked processes", "Python's GC modifies an object's Reference Count integer even on simple reads", "This mutation breaks the OS-level CoW sharing, forcing the OS to physically clone the memory pages and causing massive RAM bloat"], ["Copy on write means you copy the text and write it down on paper"]),
    ("B63_3_8", "diagnose", "medium", "debugging", ["Multiprocessing"], "You use a `multiprocessing.Pool` to process 1,000,000 images. After 10 minutes, the parent process throws a `BrokenPipeError` or `EOFError`, and the entire pool permanently hangs. What happened to the worker processes?", "The worker processes experienced a fatal OS-level crash (e.g., a C-extension Segfault, or the Linux OOM Killer sent a `SIGKILL` because the image processing exhausted RAM). Because a `SIGKILL` cannot be caught or handled by Python, the worker process vanishes instantly without notifying the parent. The parent process is left sitting in an infinite `recv()` loop waiting for data on an IPC pipe that no longer exists on the other end, resulting in the `BrokenPipeError` and a deadlocked pool. To diagnose, you must check `/var/log/syslog` for `OOMKilled` messages, and configure `maxtasksperchild` to recycle memory.", ["A worker process was violently killed by the OS (OOM Killer) or a C-level Segfault", "The worker vanishes without cleanly closing its Inter-Process Communication (IPC) pipe", "The parent process permanently hangs waiting for data on the severed pipe (`BrokenPipeError`)"], ["The pipe got rusty and broke"]),
    ("B63_3_9", "implement", "medium", "implement", ["Multiprocessing"], "How do you securely share a massive 5GB read-only matrix across 8 Python `multiprocessing` workers without exhausting the server's 8GB of total RAM?", "You cannot pass a 5GB Python list as an argument to `Pool.map()`. Python will Pickle the 5GB object, pipe it to the 8 workers, and unpickle it 8 times, requiring 45GB of RAM and crashing instantly. To share it efficiently, you must use the `multiprocessing.shared_memory` module (Python 3.8+). You allocate a 5GB block in OS Shared Memory, write the matrix into it (usually via a NumPy array backed by a SharedMemory buffer), and pass only the STRING name of the shared memory block to the workers. All 8 workers map that exact same 5GB physical RAM segment into their own virtual memory space, achieving zero-copy reads.", ["Standard multiprocessing uses Pickle and IPC pipes, which duplicates the object in RAM for every worker", "Use `multiprocessing.shared_memory` to allocate an OS-level shared memory block", "Workers attach to the shared block by name, achieving zero-copy read access without duplicating RAM"], ["You just email the matrix to the workers"]),
    ("B63_3_10", "tradeoff", "hard", "tradeoff", ["Multiprocessing"], "What is the tradeoff of using the `spawn` start method instead of `fork` in Python's `multiprocessing` library on Linux?", "The `fork` method is instantaneous because it simply clones the OS process memory, but it is incredibly dangerous: child processes inherit corrupted Lock states, open file descriptors, and broken DB connections, leading to massive deadlocks. The `spawn` method is drastically safer. It starts a completely fresh, empty Python interpreter from scratch, avoiding all corrupted inherited state. The severe tradeoff is Startup Latency and Serialization Overhead. Because it's a blank slate, the child process must re-import all Python modules (`import django`, etc.) which takes hundreds of milliseconds, and the parent must Pickle all necessary context and send it over an IPC pipe.", ["`fork`: Instant startup, but inherits dangerous corrupted lock states and DB connections (causes deadlocks)", "`spawn`: Starts a fresh, clean, safe Python interpreter from scratch", "Tradeoff: `spawn` suffers massive startup latency (must re-import all modules) and requires heavy Pickling to transfer state"], ["Spawn means the process is born in a river"]),
    ("B63_3_11", "scenario", "medium", "scenario", ["Multiprocessing"], "Your Python script uses `subprocess.Popen` to launch an external bash script. The Python script then performs heavy CPU work for 5 minutes. The bash script finishes in 10 seconds. However, when you run `top`, the bash script is marked as `<defunct>` (a Zombie process) for the entire 5 minutes. Why, and how do you fix it?", "When a child process finishes in Linux, it exits, but the OS keeps a tiny 'Zombie' record of its exit code in the process table. The OS waits for the Parent Process to explicitly read this exit code (via the `wait()` syscall). Because your Python script was busy doing heavy CPU work, it never called `wait()` on the Popen object. The Zombie process stays in the table infinitely until the parent exits or calls wait. To fix this, you must explicitly call `process.wait()`, `process.communicate()`, or use an asynchronous wait mechanism so the OS can safely reap the Zombie process.", ["A Zombie (`<defunct>`) process is a terminated child waiting for its parent to read its exit code", "Because Python was busy, it never called the `wait()` syscall to reap the child", "Fix: Explicitly call `process.wait()` or `process.communicate()` to read the exit code and clear the process table"], ["The bash script was infected by a zombie virus"]),
    ("B63_3_12", "explain", "medium", "explain", ["Multiprocessing"], "Explain why a `multiprocessing.Queue` is required to communicate between Python processes instead of a standard `queue.Queue`.", "A standard `queue.Queue` is entirely thread-based; it uses threading Locks (`threading.Lock()`) and sits in a single process's memory space. Because `multiprocessing` spawns entirely separate OS processes with physically isolated memory spaces, Process B mathematically cannot read a memory variable inside Process A. `multiprocessing.Queue` solves this by acting as an Inter-Process Communication (IPC) bridge. Under the hood, it uses an OS Pipe (or Socket). When Process A puts an object in the queue, Python Pickles the object to binary, streams it across the OS Pipe, and Process B reads and unpickles it.", ["Standard `queue.Queue` is strictly thread-local and only works within a single memory space", "Separate OS processes have completely isolated memory; they cannot share normal Python variables", "`multiprocessing.Queue` uses OS Pipes and Pickling (IPC) to serialize and stream data between isolated process memory spaces"], ["Because a multiprocessing queue is longer than a normal queue"]),

    # CPython Internals & Memory
    ("B63_3_13", "concept", "medium", "concept", ["CPython Internals"], "In CPython, what is the 'Descriptor Protocol' (`__get__`, `__set__`), and what built-in Python features rely heavily on it?", "The Descriptor Protocol is the mechanism CPython uses to override the default attribute access behavior (the dot operator). If a class attribute is assigned an object that defines a `__get__`, `__set__`, or `__delete__` method, it becomes a Descriptor. When you type `instance.attribute`, Python intercepts the normal dictionary lookup (`__dict__`) and instead executes the descriptor's `__get__` method. This low-level CPython feature is the underlying magic that makes `@property`, `@classmethod`, `@staticmethod`, and even normal bound methods function correctly under the hood.", ["A low-level CPython protocol using `__get__` and `__set__` to intercept and customize attribute access", "Overrides the standard `__dict__` dictionary lookup", "It is the fundamental engine behind `@property`, `@classmethod`, `@staticmethod`, and bound methods"], ["The descriptor protocol is how you describe your code to the compiler"]),
    ("B63_3_14", "diagnose", "hard", "debugging", ["CPython Internals"], "You implement a caching system where a global dictionary stores references to large API response objects: `cache[user_id] = massive_object`. To prevent memory leaks, you write a background thread to periodically delete old keys. However, the application still crashes with OOM. Why did this manual caching approach fail, and what Python feature should you use?", "The global dictionary `cache` holds a 'Strong Reference' to the `massive_object`. As long as that dictionary exists, the object's Reference Count (`ob_refcnt`) will never reach zero, completely preventing CPython's Garbage Collector from deleting it. The background thread likely failed or couldn't keep up with the allocation rate. You should NEVER manually manage cache memory clearing like this. You must use the `weakref` module (specifically `weakref.WeakValueDictionary`). A Weak Dictionary holds a reference that does *not* increment the reference count. When the rest of the application is done using the object, the GC deletes it, and the Weak Dictionary automatically and safely removes the key.", ["Global dictionaries hold Strong References, preventing the GC from ever deleting the cached objects", "Manual deletion loops are prone to race conditions, failure, or falling behind allocation rates", "Fix: Use `weakref.WeakValueDictionary`, which allows the GC to safely reap the objects automatically when no other strong references exist"], ["The background thread fell asleep"]),
    ("B63_3_15", "implement", "medium", "implement", ["CPython Internals"], "How do you implement the `__slots__` attribute in a Python class, and why does it drastically reduce memory consumption for millions of instances?", "By default, every instance of a Python class creates a dynamic dictionary (`__dict__`) to store its attributes. A dictionary is extremely memory-heavy because it allocates hash tables and string keys. If you instantiate 10 million `Point` objects, you allocate 10 million dictionaries, exhausting RAM instantly. By declaring `__slots__ = ['x', 'y']` at the class level, you explicitly tell CPython NOT to create a `__dict__`. Instead, CPython allocates a strict, fixed-size C-array of pointers purely for `x` and `y`. This eliminates the massive dictionary overhead, often saving 50-70% of total RAM.", ["By default, every Python object instantiates a highly inefficient dynamic dictionary (`__dict__`)", "Declaring `__slots__ = ['attr']` prevents the creation of the dictionary", "It forces CPython to allocate a fixed-size, lightweight C-array instead, massively saving RAM for millions of instances"], ["Slots means the objects are stored in a casino slot machine"]),
    ("B63_3_16", "tradeoff", "hard", "tradeoff", ["CPython Internals"], "What is the tradeoff of relying entirely on CPython's 'Reference Counting' versus relying on the 'Generational Garbage Collector'?", "Reference Counting is deterministic and instantaneous. The exact microsecond an object's `ob_refcnt` hits zero (e.g., when a function returns and local variables drop out of scope), CPython instantly frees the memory. The massive tradeoff is that Reference Counting mathematically cannot detect 'Cyclic References' (e.g., Object A points to B, B points to A). Both counts remain at `1`, so they are never freed, causing a permanent memory leak. To solve this, CPython runs a slower, non-deterministic 'Generational Garbage Collector' in the background. It periodically scans memory specifically to detect and break these isolated cycles. You cannot disable the Generational GC safely unless you mathematically guarantee zero cycles.", ["Reference Counting: Deterministic and instant, but physically cannot detect or clean up Cyclic References (A <-> B)", "Generational GC: A periodic background sweep that detects isolated cycles and breaks them", "Tradeoff: Ref counting is fast but incomplete; the Generational GC fixes cycles but introduces non-deterministic CPU pauses"], ["Reference counting counts the references in the bibliography"]),
    ("B63_3_17", "scenario", "medium", "scenario", ["CPython Internals"], "You have a deep inheritance tree in Python: `class D(B, C)`. Both `B` and `C` inherit from `A`. All classes define a `process()` method. When you call `d.process()`, Python executes it in a very specific order, but when you change it to `class D(C, B)`, the program crashes with a `TypeError: Cannot create a consistent method resolution`. Why?", "This involves CPython's Method Resolution Order (MRO) and the C3 Linearization algorithm. Python uses C3 to build a strict, predictable list of which class's method to call first in Multiple Inheritance. The algorithm guarantees two rules: 1) Children are always checked before parents, and 2) Multiple parents are checked in the exact order they are listed in the class definition. If your inheritance tree violates these topological sorting rules (e.g., creating an ambiguous diamond pattern where the resolution order creates a contradiction), the C3 algorithm mathematically fails and Python throws a `TypeError` at compile-time to prevent unpredictable runtime behavior.", ["Python uses the C3 Linearization algorithm to determine the Method Resolution Order (MRO) in Multiple Inheritance", "C3 guarantees children execute before parents, and respects the left-to-right definition order", "If the inheritance tree creates an impossible contradiction, C3 fails mathematically and explicitly throws a TypeError to prevent bugs"], ["The classes got confused about who their father was"]),
    ("B63_3_18", "explain", "medium", "explain", ["CPython Internals"], "Explain the difference between `__getattr__` and `__getattribute__` in CPython, and why overriding `__getattribute__` is extremely dangerous.", "Both methods intercept attribute access (e.g., `obj.name`). `__getattr__` is a safe, fallback method. CPython ONLY calls `__getattr__` if the attribute absolutely cannot be found in the object's `__dict__` or class tree. It's used for dynamic defaults. `__getattribute__` is unconditional. CPython calls it for EVERY single attribute access, regardless of whether it exists. Overriding `__getattribute__` is incredibly dangerous because if you try to access `self.any_variable` *inside* the `__getattribute__` method, it intercepts its own access, calling `__getattribute__` again, instantly causing an infinite recursion crash (`RecursionError`). To read internal state safely, you must explicitly call `super().__getattribute__('any_variable')`.", ["`__getattr__` is a safe fallback called ONLY when an attribute does not exist (Cache Miss)", "`__getattribute__` is called unconditionally on EVERY access, even if the attribute exists", "Overriding `__getattribute__` risks instant Infinite Recursion if you access `self` inside the method"], ["__getattr__ gets attributes, __getattribute__ gets attributes with an attitude"]),
    ("B63_3_19", "concept", "hard", "concept", ["CPython Internals"], "What is 'Object Interning' in CPython, and why does `a is b` evaluate to True for `a = 256; b = 256` but False for `a = 257; b = 257`?", "Object Interning is a CPython optimization trick to save RAM and CPU. At startup, CPython pre-allocates and caches a global pool of small integers (from -5 to 256) and short string literals. Because these values are used constantly (e.g., in `for` loops or array indices), CPython doesn't want to waste CPU instantiating a new memory object every time you type `1`. When you assign `a = 256`, CPython just gives you a pointer to the pre-cached singleton object. Thus, `a is b` (which checks memory address identity) is True. `257` is outside the pre-cached range, so CPython creates two distinct, separate objects in RAM, meaning their memory addresses are different.", ["Object Interning: CPython pre-allocates and caches small integers (-5 to 256) and strings at startup to save RAM/CPU", "Variables assigned these values receive a pointer to the exact same global singleton memory address", "`is` checks memory identity; values outside the interned range instantiate new, separate objects in RAM"], ["257 is a prime number so it gets special treatment"]),
    ("B63_3_20", "diagnose", "medium", "debugging", ["CPython Internals"], "A developer uses a class attribute as a default value: `class User: permissions = []`. They create User A and `UserA.permissions.append('admin')`. They create User B, and User B is suddenly an admin. Why did this cross-instance leakage occur?", "In CPython, class-level attributes are evaluated exactly once when the class is parsed, and are bound to the Class object itself, not the Instance. A Python list `[]` is a mutable object. Because the list is defined at the Class level, every single instance of the class shares a pointer to the exact same physical list in RAM. When User A appends to it, they are mutating the shared global list. User B reads from the exact same list. To fix this, mutable defaults must ALWAYS be initialized inside the `__init__` method (`self.permissions = []`), which guarantees a brand new, physically distinct list is instantiated in RAM for every new object.", ["Class attributes are evaluated once and bound to the Class object, shared by all instances", "If the attribute is a Mutable object (like a list or dict), mutating it alters the shared state for all instances", "Fix: Always instantiate Mutable state inside the `__init__` method so each instance gets a distinct memory allocation"], ["User B hacked User A's account"])
]

def run_batch():
    # Load all existing records to do deduplication
    with open(OUT, "r", encoding="utf-8") as f:
        existing = [json.loads(line) for line in f if line.strip()]

    print(f"Loaded {len(existing)} existing records.")
    
    for q in Q:
        if LEAK.search(q[5]) or LEAK.search(q[6]):
            print(f"PROMPT LEAK DETECTED in: {q[5]}")
            sys.exit(1)
            
    existing_texts = [ex["question"] for ex in existing]
    new_texts = [q[5] for q in Q]
    
    vec = TfidfVectorizer(stop_words="english", ngram_range=(1,2))
    all_texts = existing_texts + new_texts
    vec.fit(all_texts)
    
    existing_vecs = vec.transform(existing_texts)
    new_vecs = vec.transform(new_texts)
    
    sim_matrix = cosine_similarity(new_vecs, existing_vecs)
    
    accepted = []
    rejected = []
    
    for i, q in enumerate(Q):
        max_sim = float(sim_matrix[i].max()) if sim_matrix.shape[1] > 0 else 0
        if max_sim > 0.85:
            print(f"REJECTED (Sim: {max_sim:.2f}): {q[5][:50]}...")
            rejected.append(q)
        else:
            accepted.append(q)
            
    print(f"Accepted {len(accepted)} / {len(Q)} questions (Part 3).")
    
    new_records = []
    for q in accepted:
        rec = {
            "primary_role": ROLE,
            "applicable_roles": ["Systems Engineer", "Software Engineer"],
            "primary_skill": q[4][0],
            "secondary_skills": q[4][1:] if len(q[4]) > 1 else [],
            "technology": "Python",
            "topic": q[4][0] if len(q[4]) > 0 else "General",
            "category": "Software Engineering",
            "intent": q[1],
            "difficulty": q[2],
            "question_type": q[3],
            "question": q[5],
            "expected_answer": q[6],
            "evaluation_rubric": {
                "strong_indicators": q[7],
                "weak_indicators": q[8]
            },
            "id": str(uuid.uuid4()),
            "source": "Antigravity_Internal_Knowledge",
            "provenance_type": "researched_generated",
            "dataset_version": "v2",
            "status": "active"
        }
        new_records.append(rec)
        
    with open(OUT, "a", encoding="utf-8") as f:
        for r in new_records:
            f.write(json.dumps(r) + "\n")
            
    # Final audit reporting
    with open(OUT, "r", encoding="utf-8") as f:
        final_existing = [json.loads(line) for line in f if line.strip()]
        
    role_counts = Counter(r["primary_role"] for r in final_existing)
    
    print("\n========================================")
    print("POST-BATCH AUDIT")
    print("========================================")
    print(f"Batch: 63")
    print(f"Target role: {ROLE}")
    print(f"Attempted: {len(Q)}")
    print(f"Accepted: {len(accepted)}")
    print(f"Rejected: {len(rejected)}")
    print(f"Replacement count: 0")
    print(f"Cumulative total: {len(final_existing)}")
    print(f"{ROLE} total: {role_counts[ROLE]}")

if __name__ == "__main__":
    run_batch()
