import os

ROLE = "AI Engineer"

# Bucket Keys mapping: bucket_id -> (primary_skill, topic, technology, applicable_roles)
BUCKET_KEYS = {
    "b5": ("Structured Outputs", "Structured Generation & Schema Evolution", "LLMs", ["AI Engineer", "Full Stack Developer"]),
    "b6": ("AI Evaluation", "Continuous Eval & Testing", "LLMs", ["AI Engineer", "ML Engineer"]),
    "b7": ("AI Operations", "Inference & Cost Optimization", "LLMs", ["AI Engineer", "Cloud Infrastructure"]),
}

# Questions list: (bucket, intent, difficulty, question_type, secondary_skills, question, expected_answer, strong_rubric, weak_rubric)
Q = [
    # Q35 (b5 - Structured Outputs, 7th question of b5)
    (
        "b5",
        "optimize",
        "medium",
        "problem_solving",
        ["Structured Outputs", "AI Operations"],
        "In a high-throughput extraction pipeline, verbose JSON Schema parameter definitions (including detailed descriptions, titles, and redundant field examples) consume 40% of the total prompt token budget on every single request. How do you optimize and minify the schema representation to minimize token overhead without degrading extraction accuracy?",
        "To optimize schema token overhead while preserving extraction fidelity: 1) Schema Minification: Strip development-only metadata from the generated JSON Schema before injecting it into production prompts. Remove non-essential fields such as `$schema`, `title`, and redundant `default` attributes if already enforced in backend code. 2) Description Pruning & Information Density: Audit field descriptions: replace verbose prose descriptions with concise 3-to-5 word functional constraints (e.g., replace 'The full street address where the client resides, including apartment or suite number if applicable' with 'Residential street address'). 3) Alternative Compact Schema Syntaxes: Where supported by the model or library (e.g., Pydantic or TypeScript definition format), provide compact TypeScript interfaces rather than sprawling JSON Schema boilerplate, as TypeScript syntax typically consumes 30-50% fewer tokens. 4) Leverage Prompt Prefix Caching: Position the static minified schema at the very beginning of the system prompt so provider caching engines (e.g., Anthropic or OpenAI prefix caching) serve the schema tokens at an 80-90% discount after the first invocation.",
        [
            "Identifies schema minification (stripping non-essential keys like `$schema`, `title`, redundant descriptions).",
            "Condenses verbose field descriptions into concise functional constraints or leverages TypeScript interface syntax.",
            "Positions static schemas at the top of the prompt to maximize prefix caching hit rates."
        ],
        [
            "Removes field names and types completely to save tokens, breaking JSON formatting.",
            "Claims JSON Schemas cannot be modified or minified once generated by Pydantic."
        ]
    ),
    # Q36 (b6 - AI Evaluation, 1st question of b6)
    (
        "b6",
        "diagnose",
        "medium",
        "problem_solving",
        ["AI Evaluation", "AI Operations"],
        "An engineering team rewrites their core system prompt to improve response quality. Automated offline LLM-as-a-judge scores jump by 14% on the evaluation benchmark, but during an online A/B test on live traffic, actual user conversion and thumbs-up feedback drop by 9%. What causes offline-to-online evaluation divergence, and how do you investigate the discrepancy?",
        "Offline-to-online evaluation divergence is driven by: 1) Judge Metric Misalignment & Verbosity Bias: LLM judges possess a well-documented bias toward longer, more elaborately formatted, and polite responses. The revised prompt may have caused the model to produce verbose, essay-like answers that the offline judge rated highly, but which frustrated real-world users who wanted fast, concise, and direct answers. 2) Evaluation Benchmark Distribution Skew: The offline evaluation dataset may consist of clean, well-formed synthetic queries that fail to represent the noisy, ambiguous, fragmented, and typo-heavy prompts submitted by real production users. 3) Neglected Downstream Task Metrics: The judge evaluated general 'helpfulness' while users cared about specific operational completion (e.g., clicking a link or completing a purchase). Investigation Steps: 1) Segment live user sessions by response length and correlate with thumbs-down ratings to identify verbosity fatigue. 2) Sample 100 live production queries where users gave negative feedback, run them through the offline judge, and identify blind spots where the judge gave high scores to unhelpful responses. 3) Re-align judge rubrics with explicit penalties for excessive length and unrequested preamble.",
        [
            "Identifies LLM judge verbosity bias and metric misalignment as a primary driver of offline-online divergence.",
            "Recognizes distribution skew between clean offline benchmarks and messy production user prompts.",
            "Proposes error analysis sampling live negative-feedback sessions and re-calibrating judge rubrics against human preferences."
        ],
        [
            "Assumes the offline judge must be 100% correct and that real production users are wrong.",
            "Suggests abandoning all evaluation entirely and relying only on subjective developer intuition."
        ]
    ),
    # Q37 (b6 - AI Evaluation, 2nd question of b6)
    (
        "b6",
        "architecture",
        "hard",
        "system_design",
        ["AI Evaluation", "AI Observability"],
        "You are designing a continuous online evaluation pipeline for an AI coding assistant. Manual human labeling is too slow and expensive to evaluate thousands of daily interactions. How do you architect an automated evaluation system that transforms implicit and explicit user telemetry signals into continuous quality metrics?",
        "To architect continuous telemetry-driven online evaluation: 1) Signal Instrumentation & Taxonomy: Collect both explicit and implicit behavioral telemetry tied to the unique generation `trace_id`. Explicit signals: thumbs up/down, user-submitted bug reports, CSAT surveys. Implicit signals: Code Acceptance Rate (tab-completions accepted vs rejected), Dwell Time (time spent reviewing suggestions), Downstream Edit Distance (measuring Levenshtein distance between generated code and code committed 5 minutes later), and Copy-to-Clipboard events. 2) Composite Quality Proxy Scoring: Develop a calibrated proxy score formula combining weighted signals: e.g., an accepted suggestion with zero downstream edits within 10 minutes receives a +1.0 score; an accepted suggestion immediately deleted or heavily refactored receives a -0.5 score; an explicit thumbs-down receives a -1.0 score. 3) Asynchronous Aggregation Pipeline: Stream frontend telemetry events into an event bus (Kafka), join them with LLM generation spans in a streaming engine (Flink/ClickHouse), and publish rolling hourly quality metrics per model checkpoint and prompt version. 4) Automated Active Learning & Failure Mining: Automatically route interactions with negative composite scores into an evaluation queue for targeted LLM-as-a-judge root cause diagnosis and regression test suite expansion.",
        [
            "Combines explicit feedback (thumbs up/down) with high-value implicit signals (edit distance, retention time, copy events).",
            "Formulates a composite proxy scoring model that correlates user behavior with true generation utility.",
            "Asynchronously joins client telemetry with generation traces in streaming pipelines for active failure mining."
        ],
        [
            "Relies solely on thumbs-up clicks, ignoring that 98% of users never click feedback buttons.",
            "Blocks user code execution synchronously while waiting for human reviewers to approve suggestions."
        ]
    ),
    # Q38 (b6 - AI Evaluation, 3rd question of b6)
    (
        "b6",
        "compare",
        "easy",
        "conceptual",
        ["AI Evaluation", "AI System Testing"],
        "When building automated CI/CD test suites for an LLM application, how do 'Deterministic Semantic Unit Tests' compare to 'Model-Based Assertion Tests' (LLM-as-a-judge) in terms of execution speed, cost, flakiness, and semantic coverage?",
        "Deterministic Semantic Unit Tests (e.g., regex pattern matching, JSON schema validation, exact substring presence, cosine similarity thresholds against ground truth): Execution Speed & Cost: Sub-millisecond execution running locally on CPU at virtually zero financial cost. Flakiness: Zero flakiness; tests are 100% deterministic and reproducible. Semantic Coverage: Brittle and narrow; struggles to evaluate nuanced subjective quality, multi-sentence reasoning, or valid paraphrasing that deviates from expected strings. Model-Based Assertion Tests (LLM-as-a-judge / G-Eval): Execution Speed & Cost: High latency (hundreds of milliseconds to seconds per test) and recurring API token costs, making them expensive to run on every micro-commit. Flakiness: Subject to non-determinism, model version drift, and occasional grading hallucinations, causing flaky CI builds unless averaged over multiple runs. Semantic Coverage: Broad and flexible; deeply evaluates qualitative attributes such as tone, factual grounding, conciseness, and complex instruction adherence. Best Practice: Run deterministic tests on every pull request / commit; run model-based evaluations as nightly integration builds or pre-release gatekeepers.",
        [
            "Contrasts deterministic tests (fast, free, reproducible, brittle) with model-based tests (slow, costly, flexible, non-deterministic).",
            "Identifies CI flakiness and cost implications of model-based evaluators in continuous integration pipelines.",
            "Recommends a tiered testing strategy: deterministic tests on PRs and model-based evaluations on nightly/release builds."
        ],
        [
            "Claims deterministic unit tests can evaluate subjective conversational humor and tone accurately.",
            "States that LLM-as-a-judge tests are 100% free and have zero latency."
        ]
    ),
    # Q39 (b6 - AI Evaluation, 4th question of b6)
    (
        "b6",
        "diagnose",
        "medium",
        "problem_solving",
        ["AI Evaluation", "LLM Fundamentals"],
        "Your team updates your production model from `gpt-4o-2024-05-13` to `gpt-4o-2024-08-06`. While overall public benchmark scores for the new checkpoint improved, 4% of your production business workflows experience catastrophic regressions in formatting compliance and tone. What causes capability regressions across model checkpoint updates, and how do you design an automated regression harness to catch them?",
        "Causes of Model Checkpoint Regression: 1) Alignment Shift & Objective Tradeoffs: Reinforcement Learning from Human Feedback (RLHF) and fine-tuning updates alter token probability distributions. Improving performance on safety or math benchmarks can inadvertently suppress subtle behaviors like adhering to legacy prompt formatting conventions or concise JSON output. 2) System Prompt Sensitivity: Prompts tuned specifically for the idiosyncrasies of one model checkpoint may perform poorly on a newer checkpoint whose instruction-following priors have shifted. Automated Regression Harness Design: 1) Immutable Golden Evaluation Suite: Curate an evaluation dataset of at least 200-500 historical, production-sampled prompt-response pairs covering all core business workflows, edge cases, and past failure points. 2) Differential Testing (Side-by-Side Comparison): Run identical inputs through both the current production checkpoint and the candidate checkpoint in parallel. Compare outputs using programmatic assert checks (schema compliance, regex format, length) and LLM-as-a-judge pairwise preference scoring. 3) Gated Deployment Thresholds: Define hard non-negotiable pass criteria: the new checkpoint must maintain 100% compliance on critical syntax and zero regression on safety before traffic can be switched. 4) Pinned Model Pinning: Never use dynamic floating model aliases (like `gpt-4o`) in production; always pin to explicit dated checkpoints (e.g., `gpt-4o-2024-08-06`).",
        [
            "Explains how RLHF alignment updates and prompt sensitivity cause subtle capability regressions across checkpoints.",
            "Establishes a differential testing harness comparing candidate checkpoints against production baselines using an immutable golden test suite.",
            "Enforces pinning explicit dated model versions rather than floating aliases in production."
        ],
        [
            "Assumes newer model checkpoints are always strictly better at every task without testing.",
            "Uses floating model tags in production and allows providers to change underlying checkpoints without warning."
        ]
    ),
    # Q40 (b6 - AI Evaluation, 5th question of b6)
    (
        "b6",
        "optimize",
        "medium",
        "problem_solving",
        ["AI Evaluation", "AI Data Quality"],
        "To evaluate an internal enterprise knowledge assistant, you generate a synthetic test dataset of 1,000 question-answer pairs using an LLM prompting pipeline. How do you prevent 'synthetic contamination' and verify that the generated test dataset realistically represents the complexity and failure modes of actual human users?",
        "To prevent synthetic contamination and ensure realistic evaluation datasets: 1) Multi-Persona & Seed Prompt Evolution (Evol-Instruct): Avoid generating all questions from a single uniform prompt. Use diverse persona prompts (e.g., non-native English speaker, hurried executive, technical novice) and apply prompt mutation techniques (adding domain constraints, creating multi-hop questions, inserting conversational ambiguity) to simulate human variation. 2) Contamination Auditing (De-duplication): Run n-gram overlap and embedding cosine similarity checks between the synthetic test dataset and any training or fine-tuning datasets to guarantee zero data leakage. 3) Distributional Alignment with Live Telemetry: Measure the distributional characteristics of the synthetic dataset against real production logs (comparing token length distributions, reading level, sentence structure complexity, and semantic clustering density). If synthetic questions are grammatically pristine while real queries are fragmented, inject realistic noise (typos, omitted punctuation, domain slang). 4) Human Verification & Pruning: Conduct a blind review of a stratified 10% sample by domain experts to verify that generated ground-truth answers are factually accurate and that questions reflect realistic operational tasks.",
        [
            "Uses multi-persona prompting and evolutionary mutation (Evol-Instruct) to prevent sterile, uniform synthetic datasets.",
            "Performs semantic and n-gram contamination checks against training and retrieval corpora.",
            "Validates synthetic complexity distributions against real production telemetry (token lengths, noise, vocabulary)."
        ],
        [
            "Prompts an LLM once with 'Generate 1,000 realistic questions' without verifying diversity or realism.",
            "Assumes synthetic data is always perfectly representative of human user behavior without auditing."
        ]
    ),
    # Q41 (b6 - AI Evaluation, 6th question of b6)
    (
        "b6",
        "compare",
        "easy",
        "conceptual",
        ["AI Evaluation", "RAG Architecture"],
        "In LLM system evaluation, how do 'Reference-Based Metrics' (such as BERTScore or Semantic Answer Similarity against human ground truth) compare to 'Reference-Free Metrics' (such as Faithfulness and Answer Relevance) in terms of setup cost, maintenance, and operational feasibility?",
        "Reference-Based Metrics (comparing model output to human-labeled golden answers): Setup & Maintenance: Very high initial setup cost; requires human subject-matter experts to author and maintain paired reference answers. In dynamic domains (such as weekly software releases or financial markets), reference answers rapidly become obsolete, requiring continuous manual maintenance. Feasibility: Excellent for fixed-domain benchmark evaluation, regression testing, and objective accuracy validation, but impractical for evaluating open-ended dynamic queries in production. Reference-Free Metrics (evaluating output against retrieved context or input query, e.g., RAG Triad: Faithfulness, Answer Relevance, Context Precision): Setup & Maintenance: Low initial setup cost; requires zero human-authored reference answers because evaluation relies on cross-checking the generated output against the retrieved source documents and user query. Feasibility: Highly feasible for continuous production monitoring and dynamic RAG pipelines where documentation changes daily. Limitation: Reference-free metrics can confirm that an answer is faithful to retrieved context, but cannot detect if the retrieved context itself is incomplete or missing the actual real-world truth.",
        [
            "Explains that reference-based metrics require expensive human-authored golden answers that decay as knowledge updates.",
            "Highlights reference-free metrics as scalable for continuous production monitoring by evaluating internal consistency.",
            "Identifies the blind spot of reference-free metrics: cannot detect missing context or systemic retrieval omissions."
        ],
        [
            "Claims reference-free metrics are always worse than reference-based metrics in all scenarios.",
            "Cannot articulate what reference-free metrics compare the model output against."
        ]
    ),
    # Q42 (b6 - AI Evaluation, 7th question of b6)
    (
        "b6",
        "tradeoff",
        "medium",
        "analytical",
        ["AI Evaluation", "AI Data Quality"],
        "When sampling production LLM interactions for human expert evaluation and fine-tuning annotation, how do you evaluate the tradeoffs between 'Uniform Random Sampling', 'Uncertainty / Low-Confidence Sampling', and 'Feedback-Triggered Negative Sampling'?",
        "Uniform Random Sampling: Pros: Provides an unbiased, statistically representative estimate of overall population performance (true baseline error rates, average user satisfaction). Cons: Highly inefficient for finding edge cases; in a system with 95% success, 95% of human annotation budget is wasted reading routine, correct answers. Uncertainty / Low-Confidence Sampling (sampling turns with high token entropy, borderline retrieval similarity, or ambiguous classifier scores): Pros: High information density; targets borderline decisions where model confidence is lowest, making it highly valuable for active learning and fine-tuning. Cons: Biased sample distribution; cannot be used to report true overall system accuracy to business stakeholders. Feedback-Triggered Negative Sampling (sampling turns with user thumbs-down, regenerations, or reported errors): Pros: Maximum return on investment for root cause bug fixes; focuses human effort exclusively on confirmed user pain points. Cons: Suffers from strong reporting bias (passive users rarely click thumbs-down); misses silent failures where the model sounded convincing but generated false information that the user believed. Recommended Strategy: Allocate budget into a hybrid split: 20% Uniform Random (for unbiased baseline tracking) and 80% Stratified Negative/Uncertainty (for targeted debugging and model fine-tuning).",
        [
            "Evaluates Uniform Random: statistically unbiased baseline but low annotation efficiency for finding bugs.",
            "Evaluates Uncertainty Sampling: high information density for active learning but biased overall metrics.",
            "Evaluates Feedback-Triggered Sampling: high ROI on known pain points but vulnerable to user reporting bias and silent hallucinations.",
            "Proposes a hybrid portfolio allocation balancing representative baseline tracking with targeted failure mining."
        ],
        [
            "Relies 100% on random sampling, wasting expert annotation budgets on obvious correct answers.",
            "Fails to identify reporting bias in user-submitted feedback."
        ]
    ),
    # Q43 (b6 - AI Evaluation, 8th question of b6)
    (
        "b6",
        "architecture",
        "medium",
        "system_design",
        ["AI Evaluation", "AI Security"],
        "You are tasked with designing an Automated Red-Teaming Harness that continuously probes an enterprise LLM chatbot for jailbreaks, prompt injections, and policy violations prior to production deployments. How do you structure the red-teaming orchestrator, adversarial attack strategies, and automated grading classifiers?",
        "To build an Automated Red-Teaming Harness: 1) Adversarial Attacker Agent (Red Agent): Deploy a dedicated LLM configured with red-teaming system prompts and attack strategies (e.g., automated implementations of PAIR - Prompt Automatic Iterative Refinement, or TAP - Tree of Attacks with Pruning). The Red Agent generates adversarial prompts across targeted threat categories (PII exfiltration, toxicity, jailbreaks, roleplay subversion). 2) Multi-Turn Attack Orchestrator: Manage conversational attack trees: rather than single-shot prompts, the harness allows the Red Agent to engage in multi-turn dialogues with the Target System, using deceptive conversational framing, emotional manipulation, and iterative refinement based on the Target's defenses. 3) Automated Vulnerability Judge (Judge Agent): Pass the Target System's responses to a specialized safety classifier or frontier LLM judge with strict rubrics evaluating safety compliance, information disclosure, and refusal appropriateness. 4) Attack Mutation & Fuzzing: Include non-LLM fuzzing techniques: character substitution, base64 encoding, leetspeak, language translation (e.g., attacking in low-resource languages), and delimiter manipulation. 5) CI/CD Quality Gate: Aggregate attack success rates across threat categories; enforce a zero-tolerance gate on high-severity vulnerability exploits before releasing new prompt or model updates.",
        [
            "Designs an attacker agent architecture using iterative refinement (PAIR/TAP) across targeted threat categories.",
            "Implements multi-turn conversational probing rather than relying purely on single-shot inputs.",
            "Combines automated safety judges with adversarial mutation/fuzzing and enforces automated CI/CD release gates."
        ],
        [
            "Relies on a static list of 10 hardcoded jailbreak phrases checked with string matching.",
            "Claims manual human red-teaming once a year is sufficient for continuous daily deployments."
        ]
    ),
    # Q44 (b7 - Inference & Cost Optimization, 1st question of b7)
    (
        "b7",
        "optimize",
        "medium",
        "problem_solving",
        ["AI Operations", "LLM Architecture"],
        "Provider Prompt Prefix Caching (such as Anthropic Prompt Caching and OpenAI Automatic Caching) offers up to 90% cost reductions and 80% latency reductions on cached input tokens. How do you systematically structure your prompt templates and conversational payloads to maximize cache hit rates in production?",
        "To maximize prompt prefix caching efficiency: 1) Strict Hierarchical Static-to-Dynamic Ordering: Prefix caching engines match tokens from the beginning of the prompt sequentially until the first modified token. Structure prompt templates in strict order of volatility: Place invariant system instructions first -> Static tool schemas second -> Large static reference documentation or few-shot examples third -> Dynamic conversation history fourth -> Transient user query last. Any dynamic variable (like current timestamp or user ID) placed at the top invalidates the entire cache for all subsequent tokens. 2) Normalization & Deterministic Serialization: Eliminate non-deterministic serialization: sort JSON schema keys alphabetically, avoid dynamic indentation changes, and strip dynamic system date injections from the static header (inject current date as a user-level message instead). 3) Breakpoint Threshold Alignment: Understand provider caching thresholds (e.g., Anthropic requires a minimum of 1,024 tokens for caching; OpenAI caches in 1,024-token increments). Consolidate static context into chunks that meet or exceed provider cache minimums to ensure caching activates. 4) Session Routing Affinity: Configure load balancers with session affinity (sticky routing) to dispatch consecutive user requests to the same underlying provider host/region where KV cache blocks are already warm.",
        [
            "Structures prompts hierarchically from least volatile (system, tools, docs) to most volatile (user query) to prevent early cache invalidation.",
            "Removes dynamic variables (timestamps, user IDs) from the prompt prefix.",
            "Aligns token volumes with provider caching thresholds (e.g., 1,024 tokens) and implements sticky routing affinity."
        ],
        [
            "Puts the user query or current timestamp at the very beginning of the system prompt, breaking the prefix cache every turn.",
            "Claims prompt caching works regardless of token ordering in the prompt."
        ]
    ),
    # Q45 (b7 - Inference & Cost Optimization, 2nd question of b7)
    (
        "b7",
        "architecture",
        "hard",
        "system_design",
        ["AI Operations", "LLM Architecture"],
        "You are designing a Cascading Dynamic Model Router that triages incoming enterprise user requests across a lightweight model (e.g., GPT-4o-mini or Claude 3.5 Haiku) and an expensive frontier reasoning model (e.g., GPT-4o or Claude 3.5 Sonnet). How do you architect the query classification layer, confidence evaluation, and fallback cascade to achieve 70% cost reduction without degrading overall response accuracy?",
        "To architect a high-accuracy cascading dynamic router: 1) Query Complexity Classification Layer: Deploy a fast, low-overhead routing classifier (e.g., a fine-tuned small BERT/DeBERTa classifier, fast embedding cosine search against intent clusters, or optimized rule heuristics) with <15ms latency. The classifier scores query attributes: required reasoning depth, code generation, multi-hop requirements, and context length. Simple factual queries, FAQ matching, and basic formatting are immediately routed to the Tier 1 lightweight model. 2) Speculative Execution & Confidence Scoring: For borderline complexity queries, dispatch to Tier 1 first. Measure confidence indicators: token log-probabilities, semantic self-consistency check, or structured output validation success. If the lightweight model returns low log-probability confidence, outputs refusal phrases ('I am not sure'), or fails JSON schema validation, trigger the cascade. 3) Fallback Cascade Pipeline: When Tier 1 signals low confidence, asynchronously promote the request to the Tier 2 frontier model. Include the Tier 1 draft response in the Tier 2 prompt as a speculative baseline if appropriate, or execute fresh frontier reasoning. 4) Continuous Calibration: Log router decisions, model outputs, and user feedback into a telemetry loop. Periodically recalculate the router's decision boundary threshold using Pareto frontier optimization to balance token cost savings against acceptable task accuracy.",
        [
            "Implements a fast, low-latency classifier (<15ms) based on query complexity and intent.",
            "Uses model confidence signals (log-probabilities, schema validation, refusal detection) to trigger dynamic fallback.",
            "Designs an automated calibration loop to optimize the cost-accuracy Pareto frontier."
        ],
        [
            "Sends all queries to the frontier model first and asks it if a smaller model could have done it.",
            "Uses an expensive frontier model to classify queries for the lightweight model, negating all cost savings."
        ]
    ),
    # Q46 (b7 - Inference & Cost Optimization, 3rd question of b7)
    (
        "b7",
        "compare",
        "easy",
        "conceptual",
        ["AI Operations", "LLM Fundamentals"],
        "When managing extensive document contexts in LLM prompts, how does 'Prompt Compression' (using semantic token-pruning algorithms like LLMLingua) compare to 'Naive Truncation' (dropping oldest tokens) in terms of information retention, computational overhead, and integration complexity?",
        "Naive Truncation (dropping oldest tokens or slicing text to fit context limits): Information Retention: Very poor; arbitrary truncation drops entire paragraphs, frequently severing critical instructions, entity definitions, or document conclusions located outside the truncation window. Computational Overhead & Latency: Zero overhead; simple string or array slicing requiring no GPU compute. Integration Complexity: Trivial; implemented in one line of code. Prompt Compression (e.g., LLMLingua using a small language model like LLaMA-2-7B or small transformer to calculate token perplexity and prune low-information tokens): Information Retention: Superior; retains high-perplexity tokens (names, numbers, actionable verbs, core instructions) while pruning predictable filler words across the entire document, preserving semantic integrity across long texts. Computational Overhead & Latency: Moderate overhead; requires running an inference pass on a local small language model, adding 50-150ms of preprocessing latency before dispatching to the target LLM. Integration Complexity: Higher; requires hosting and maintaining a local compressor model. Production Tradeoff: Use prompt compression for high-value document summarization and long-context RAG where token savings translate directly into significant API cost reductions.",
        [
            "Contrasts naive truncation (zero overhead, severe information loss) with prompt compression (retains high-perplexity tokens across documents).",
            "Identifies the computational cost and latency overhead of running local compressor models (50-150ms).",
            "Frames the tradeoff around cost-per-token savings versus preprocessing latency and infrastructure complexity."
        ],
        [
            "Claims naive truncation is semantically intelligent because newer tokens are always more important.",
            "Believes prompt compression changes the model weights of the destination LLM."
        ]
    ),
    # Q47 (b7 - Inference & Cost Optimization, 4th question of b7)
    (
        "b7",
        "diagnose",
        "medium",
        "problem_solving",
        ["AI Operations", "Cloud Infrastructure"],
        "An enterprise deploys a self-hosted vLLM inference cluster utilizing continuous batching and PagedAttention. Under heavy concurrent load, end-to-end request latency spikes by 350% and request queueing builds up, yet GPU compute core utilization (SM utilization) remains low at 60%. What memory and architectural bottlenecks cause this compute underutilization, and how do you resolve it?",
        "Root Cause: In LLM serving with continuous batching and PagedAttention, the primary bottleneck under high concurrency is almost always GPU VRAM capacity allocated to the KV Cache, not compute core (FLOPs) capacity. When hundreds of concurrent requests generate long token sequences, the KV cache memory blocks fill up entirely. Once KV cache memory reaches 100%, vLLM cannot schedule new incoming requests or continue decoding active sequences; it is forced to queue incoming requests or preempt running sequences. The GPU tensor cores sit idle (compute underutilization) waiting for memory allocations. Remediation: 1) KV Cache Memory Allocation Tuning: Increase `gpu_memory_utilization` parameter (e.g., from default 0.90 to 0.95) if VRAM headroom allows, dedicating more memory to KV cache blocks. 2) Chunked Prefill & Max Sequence Limits: Enable chunked prefill (`--enable-chunked-prefill`) to co-schedule compute-bound prefill requests with memory-bound decode requests, smoothing GPU compute utilization. 3) Reduce Context Limits / Enforce Max Model Length: Lower `--max-model-len` to realistic application bounds (e.g., reducing from 32k to 8k tokens if users only need 4k), drastically shrinking worst-case KV cache allocations per sequence. 4) Tensor Parallelism & Multi-GPU Scaling: Scale across additional GPUs using Tensor Parallelism (TP) or pipeline parallelism to distribute KV cache memory footprint across multiple GPU VRAM pools.",
        [
            "Identifies KV cache memory exhaustion (PagedAttention block starvation) as the driver of compute core underutilization.",
            "Explains that GPU compute cores sit idle while the engine pauses or queues requests due to lack of VRAM for KV blocks.",
            "Proposes tuning `gpu_memory_utilization`, enabling chunked prefill, capping max model length, and scaling tensor parallelism."
        ],
        [
            "Blames slow disk drives for GPU compute underutilization during token inference.",
            "Suggests switching from continuous batching back to legacy static batching."
        ]
    ),
    # Q48 (b7 - Inference & Cost Optimization, 5th question of b7)
    (
        "b7",
        "compare",
        "easy",
        "conceptual",
        ["AI Operations", "LLM Fundamentals"],
        "In LLM inference serving, how does 'Speculative Decoding' compare to 'Standard Autoregressive Decoding' in terms of throughput, hardware requirements, and suitability across different task domains?",
        "Standard Autoregressive Decoding: Mechanism: Generates exactly one token per forward pass. Memory-bandwidth bound; the entire model weights (tens of gigabytes) must be streamed from GPU memory to compute cores for every single generated token. Throughput: Bounded by memory bandwidth (typically 30-60 tokens/sec on modern GPUs). Hardware Requirements: Requires only the primary model loaded in VRAM. Speculative Decoding: Mechanism: A small, fast 'Draft Model' (e.g., 1B parameter model) generates a sequence of K candidate tokens in rapid succession. The large 'Target Model' (e.g., 70B parameter model) verifies all K candidate tokens concurrently in a single forward pass using parallel prefix verification. If the target model accepts M tokens (where M <= K), all M tokens are generated in the time of a single target forward pass. Throughput: Can achieve 2x to 3x higher generation throughput when acceptance rates are high. Hardware Requirements: Requires additional GPU memory to host both the draft model and target model concurrently. Task Domain Suitability: Excels in predictable, low-entropy domains (natural language conversations, structured formatting, repetitive boilerplates) where the draft model's acceptance rate is high (>70%). Degrades in high-entropy domains (complex mathematical proofs, cryptic code, highly creative prose) where low draft acceptance rates negate throughput gains.",
        [
            "Explains that standard decoding generates one token per forward pass and is memory-bandwidth bound.",
            "Details speculative decoding: small draft model proposes K tokens verified in parallel by the target model in one pass.",
            "Highlights domain suitability: 2x-3x speedup on low-entropy predictable text, but minimal benefit on high-entropy code/math."
        ],
        [
            "Claims speculative decoding changes the mathematical output distribution and makes answers inaccurate.",
            "States that speculative decoding requires no additional VRAM."
        ]
    ),
    # Q49 (b7 - Inference & Cost Optimization, 6th question of b7)
    (
        "b7",
        "tradeoff",
        "medium",
        "analytical",
        ["AI Operations", "Cloud Infrastructure"],
        "When implementing response caching for an enterprise LLM assistant, how do you evaluate the tradeoffs between 'Semantic Caching' (vector similarity matching on query embeddings) versus 'Deterministic Exact-Match Caching' (SHA-256 hashing of prompts)?",
        "Deterministic Exact-Match Caching (SHA-256 Hash): Pros: 100% precision with zero risk of false-positive semantic collisions; ultra-fast sub-millisecond lookup in Redis/Memcached; zero compute or embedding model inference cost. Cons: Extremely low cache hit rate in natural language systems; trivial variations (adding a question mark, greeting, or minor typo) yield completely different hashes, causing cache misses. Semantic Caching (Vector Similarity Matching, e.g., GPTCache with threshold >0.92): Pros: Substantially higher cache hit rates; recognizes that 'How do I reset my password?' and 'Steps to change account password' share the same intent, instantly serving cached answers. Cons: 1) False Positive Collisions & Semantic Drift: Similar queries with critical differences (e.g., 'How do I cancel my plan?' vs 'How do I upgrade my plan?') can trigger false positive cache hits if similarity thresholds are tuned too loosely. 2) Latency & Compute Overhead: Requires generating an embedding vector for every incoming query and performing an approximate nearest neighbor (ANN) vector search, adding 30-80ms of lookup overhead before knowing if there is a cache hit. 3) Stale Knowledge: Difficult to invalidate selectively when underlying knowledge changes. Recommendation: Use exact hashing for programmatic API calls and structured prompts; use semantic caching with strict similarity thresholds (>0.95) and tenant-scoped namespaces for conversational FAQs.",
        [
            "Contrasts exact-match caching (zero false positives, cheap, low hit rate) with semantic caching (high hit rate, semantic collision risk).",
            "Identifies semantic cache lookup overhead (embedding generation + vector search latency).",
            "Analyzes the risk of false-positive cache hits on subtly different user intents and cache invalidation challenges."
        ],
        [
            "Claims semantic caching is 100% safe with similarity thresholds as low as 0.70.",
            "States that SHA-256 exact matching takes longer to compute than vector similarity search."
        ]
    ),
    # Q50 (b7 - Inference & Cost Optimization, 7th question of b7)
    (
        "b7",
        "optimize",
        "medium",
        "problem_solving",
        ["AI Operations", "Cloud Infrastructure"],
        "An enterprise document analysis service processes 50,000 corporate financial filings per day. Real-time sub-second streaming is not required by end users, who only need reports within 12 hours. How do you re-architect the inference workload to leverage Batch Inference APIs (such as OpenAI Batch API or Anthropic Batch) to cut API costs by 50% while guaranteeing SLA compliance?",
        "To re-architect the workload for Batch Inference APIs: 1) Decouple Ingestion from Execution: Transition from synchronous HTTP request-response endpoints to an asynchronous event-driven architecture. Document upload endpoints store raw filings in cloud object storage (S3/GCS) and publish job metadata to an asynchronous task queue. 2) Scheduled JSONL Batch Bundling: Run a periodic batch aggregator (e.g., hourly cron worker) that groups pending extraction tasks into standardized JSONL batch manifest files (each line containing a custom `custom_id`, model name, and prompt payload) conforming to provider batch specifications. 3) Batch Submission & Polling Lifecycle: Upload the manifest file via the provider's Batch API endpoint (`/v1/batches` with `completion_window='24h'`). Store the batch ID and monitor execution status asynchronously via webhook notifications or exponential polling workers. 4) Cost & Throughput Advantages: Batch endpoints execute on surplus cloud provider compute during off-peak windows, providing a 50% discount on both input and output tokens and providing separate, substantially higher rate-limit pools that eliminate production 429 errors. 5) Partial Failure & Dead-Letter Handling: Upon batch completion, download the result JSONL file, parse outputs by `custom_id`, and write results to the database. Isolate individual failed rows (e.g., content moderation flags or timeouts) to a dead-letter queue for targeted single-request retries without reprocessing the entire batch.",
        [
            "Decouples ingestion into asynchronous JSONL batch bundling conforming to provider Batch APIs.",
            "Leverages the 50% cost discount and dedicated high-throughput quotas of batch inference windows.",
            "Implements asynchronous status monitoring, result reconciliation by `custom_id`, and isolated partial failure retries."
        ],
        [
            "Sends 50,000 synchronous requests concurrently from a single loop, hitting massive 429 rate limit errors.",
            "Believes Batch APIs provide real-time sub-second streaming tokens."
        ]
    )
]
