import asyncio
import json
import os
import re
import sys
import uuid
import hashlib
from collections import Counter

from dotenv import load_dotenv
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
load_dotenv()

BACKEND_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_DIR = os.path.join(BACKEND_DIR, "data")
OUT = os.path.join(DATA_DIR, "interview_question_bank_v2_generated.jsonl")

ROLE = "Python Developer"
LEAK = re.compile(r"(generate a question|generate \d+ questions|return only json|phase 4c gap plan|"
                  r"generation batch|candidate generation|system instructions|do not proceed|"
                  r"awaiting authorization|minimum target|generation pipeline|"
                  r"batch \d+ generation|expected answer|strong indicator|weak indicator|as an ai|"
                  r"here is the question|\bprompt text\b)", re.I)

Q = [
    # Deep Security
    ("B63_2_1", "concept", "hard", "concept", ["Security"], "Why is it mathematically impossible to securely 'unpickle' an untrusted file in Python, even if you try to sandbox it?", "The `pickle` format is not just a data structure (like JSON); it is a bytecode instruction language for the Python Virtual Machine. When `pickle.loads()` is called, it executes arbitrary opcodes to reconstruct objects. An attacker can craft a pickle payload that explicitly instructs the VM to execute `__import__('os').system('rm -rf /')` via the `__reduce__` method. There is no native sandbox in CPython that can restrict these opcodes. You must absolutely NEVER unpickle data from an untrusted source, period. You must use JSON, MessagePack, or Protobuf for external data.", ["Pickle is not data; it is an executable bytecode language", "The `__reduce__` method allows attackers to execute arbitrary shell commands during deserialization", "There is no secure sandbox for pickle; it must never be used for untrusted/external data"], ["Pickle is secure as long as you wrap it in a try-except block"]),
    ("B63_2_2", "diagnose", "medium", "debugging", ["Security"], "Your Python microservice uses `yaml.load(user_input)` to parse configuration files uploaded by users. A security researcher successfully gets Remote Code Execution (RCE) on your server. How did they achieve this, and what is the fix?", "The standard `yaml.load()` in the `PyYAML` library (historically) allowed the instantiation of arbitrary Python objects via YAML tags (e.g., `!!python/object/apply:os.system [\"ls\"]`). Because `load()` is highly permissive, it blindly executes the constructor of the specified class. To fix this catastrophic vulnerability, you must ALWAYS use `yaml.safe_load()`. The `safe_load` function strips out the ability to instantiate arbitrary Python classes, restricting the parser strictly to standard YAML data types (lists, dictionaries, strings, ints).", ["`yaml.load()` permits arbitrary Python object instantiation via special YAML tags", "Attackers can use `!!python/object/apply:os.system` to achieve RCE", "Fix: Always use `yaml.safe_load()` which restricts parsing to standard data structures"], ["The attacker wrote a virus in YAML syntax"]),
    ("B63_2_3", "implement", "hard", "implement", ["Security"], "How do you securely execute a user-provided command-line tool in Python using the `subprocess` module to absolutely prevent Command Injection?", "If a developer writes `subprocess.run(f\"ping {user_ip}\", shell=True)`, an attacker can pass `127.0.0.1; rm -rf /` and completely destroy the server. The `shell=True` argument passes the entire string to `/bin/sh`, which interprets the `;` operator. To prevent this, you MUST set `shell=False` (the default) and pass the command as a strict list of arguments: `subprocess.run([\"ping\", user_ip])`. When passed as a list, Python invokes the executable directly via the OS `execve` syscall. The OS treats `127.0.0.1; rm -rf /` purely as a literal string argument to the `ping` program, making injection mathematically impossible.", ["Never use `shell=True` as it invokes `/bin/sh` which evaluates dangerous shell operators (`;`, `|`, `&&`)", "Pass the command and arguments as a strict list of strings: `[\"ping\", user_ip]`", "This uses `execve` directly, forcing the OS to treat malicious payloads as literal string arguments, not executable commands"], ["You just use regex to remove semicolons from the string"]),
    ("B63_2_4", "tradeoff", "medium", "tradeoff", ["Security"], "What is the security tradeoff of using the `eval()` function in Python, even if you restrict its globals and locals dictionaries?", "Developers sometimes use `eval(user_math_string, {\"__builtins__\": None})` to build a \"secure\" calculator, thinking they removed access to `import` or `os`. The massive tradeoff is that Python's introspection is too powerful to sandbox easily. An attacker can still use deeply nested attribute traversal on standard objects (e.g., `[].__class__.__base__.__subclasses__()`) to walk up the inheritance tree, find the `os` module or `subprocess.Popen` class, and execute RCE. The tradeoff is that `eval` is fundamentally un-sandboxable in standard CPython. You must use `ast.literal_eval()` for safe evaluation of literals, or build a strict mathematical parser.", ["Restricting `globals` in `eval()` provides a false sense of security", "Attackers can use `__class__.__base__.__subclasses__()` to walk the MRO and find dangerous modules like `os`", "Tradeoff: `eval` cannot be secured. Use `ast.literal_eval` or a dedicated parsing library"], ["eval() is secure as long as you check if the string contains the word 'os'"]),
    ("B63_2_5", "scenario", "medium", "scenario", ["Security"], "Your Python application uses `requests.get(url_from_user)` to fetch a profile picture. The application is deployed in AWS. A user inputs `http://169.254.169.254/latest/meta-data/` and your API returns your server's temporary AWS IAM credentials. What is the precise Python fix for this Server-Side Request Forgery (SSRF)?", "You cannot rely on simple Regex to block `169.254.x.x` because attackers can use DNS rebinding, octal IP formats (`0251.0376...`), or short IPs (`169.254.1`). The robust Python fix is to resolve the URL's hostname to an IP address yourself using `socket.gethostbyname()`. Then, check if the resolved IP falls within restricted CIDR blocks (using the `ipaddress` module, e.g., `ipaddress.ip_address(ip).is_private`). Only if the IP is public do you pass the explicit IP to `requests.get()`, while explicitly setting the `Host` header to the original domain to satisfy SNI.", ["SSRF allows attackers to force the server to make requests to internal/cloud metadata networks", "Regex blocking fails against DNS rebinding and octal/hex IP encodings", "Fix: Resolve the hostname to an IP, validate it mathematically using the `ipaddress` module, and request the validated IP directly"], ["Just use a try/except block around the requests call"]),
    ("B63_2_6", "concept", "hard", "concept", ["Security"], "What is 'Dependency Confusion' in Python packaging (pip), and how do you prevent your internal company packages from being hijacked?", "Dependency Confusion occurs when a company uses a private PyPI server to host internal packages (e.g., `company-auth-lib v1.0`). If an attacker discovers the package name, they can upload a malicious package with the exact same name to the PUBLIC PyPI registry, but with a drastically higher version number (`v99.0`). When a developer runs `pip install company-auth-lib --extra-index-url https://private.repo`, `pip` defaults to downloading the highest version number available across ALL registries, silently pulling the malicious package from public PyPI and executing its `setup.py`. To prevent this, you must use `--index-url` (not `--extra-index-url`) to strictly restrict the search to the private registry, or use explicit Hash Checking in `requirements.txt`.", ["`pip` prioritizes the highest version number when searching across multiple registries", "Attackers upload internal package names to the public PyPI with massive version numbers to trick `pip`", "Prevention: Use strict `--index-url` (avoiding fallback), or use `pip install --require-hashes`"], ["Dependency confusion is when you forget which library you pip installed"]),
    ("B63_2_7", "diagnose", "medium", "debugging", ["Security"], "You use Python's `tempfile.mktemp()` to generate a temporary file name to store a sensitive user report. During a security audit, you are flagged for a 'Race Condition'. Why is `mktemp()` insecure?", "The `mktemp()` function only generates a random string filename; it does NOT physically create the file or lock it. Between the moment `mktemp()` returns `/tmp/abc` and the moment your Python code executes `open('/tmp/abc', 'w')`, an attacker on the same machine can quickly create a symlink at `/tmp/abc` pointing to `/etc/shadow` or another critical system file. When your script opens it for writing, it overwrites the system file (Symlink Attack). To fix this, you must use `tempfile.mkstemp()` or `tempfile.NamedTemporaryFile()`, which atomically create and lock the file at the OS level using the `O_CREAT | O_EXCL` flags, making the race condition physically impossible.", ["`mktemp()` generates a name but does not atomically create the file, leaving a window for Symlink attacks", "An attacker can create a symlink with that name pointing to a critical system file before your code opens it", "Fix: Use `mkstemp()` or `NamedTemporaryFile()` which use atomic OS-level file creation (`O_EXCL`)"], ["The temp file was too hot and melted the CPU"]),

    # Serialization & Data
    ("B63_2_8", "concept", "medium", "concept", ["Serialization"], "What is the fundamental flaw with using the standard `json` module to serialize massive (5GB) Python dictionaries, and how do you fix it?", "The standard `json.dumps()` method is entirely memory-bound. It attempts to traverse the entire 5GB dictionary, serialize it into a single contiguous 5GB String in memory, and then write it out. This requires at least 10GB of RAM (5GB dict + 5GB string) and will instantly crash the application with an `MemoryError`. To fix this, you must use 'Streaming JSON Serialization'. Libraries like `ijson` (for reading) or writing the JSON out in chunks/lines (JSONL), or using a library that supports generators, allows you to serialize and pipe the output to a file or network socket with a tiny, constant memory footprint.", ["`json.dumps()` materializes the entire serialized string in RAM simultaneously", "Massive objects will exceed available memory and cause an `MemoryError` crash", "Fix: Use streaming JSON parsers (`ijson`) or JSON Lines (`JSONL`) to serialize/deserialize iteratively"], ["The json module doesn't know how to count past 1GB"]),
    ("B63_2_9", "diagnose", "hard", "debugging", ["Serialization"], "A Python financial backend calculates taxes. `0.1 + 0.2` results in `0.30000000000000004`. The developer fixes this by using the `decimal.Decimal` module: `Decimal(0.1) + Decimal(0.2)`. However, the result is STILL mathematically imprecise. Why did `Decimal` fail here, and how do you fix it?", "The bug occurred because the developer passed Python floating-point literals directly into the `Decimal` constructor. Python evaluates `0.1` as an imprecise binary IEEE-754 float *before* passing it to `Decimal`. Therefore, `Decimal` receives the already-corrupted float (`0.10000000000000000555...`). To achieve absolute precision, you MUST initialize `Decimal` using Strings: `Decimal('0.1') + Decimal('0.2')`. By passing a string, the Decimal library parses the exact base-10 representation without any binary floating-point corruption.", ["Passing float literals to `Decimal()` corrupts the value before the object is even instantiated", "Python evaluates the float into a binary approximation before `Decimal` can process it", "Fix: Always instantiate `Decimal` objects using Strings (`Decimal('0.1')`) to guarantee exact base-10 representation"], ["The decimal module is just broken in Python 3"]),
    ("B63_2_10", "implement", "medium", "implement", ["Serialization"], "How do you optimize a Pydantic V2 model that is causing massive CPU bottlenecks when validating arrays of 100,000 JSON objects?", "Pydantic V2 is written in Rust (`pydantic-core`) and is incredibly fast, but validating 100,000 objects inherently requires heavy type-checking and coercion loops. If you entirely trust the internal data source (e.g., you already validated it on insertion to the DB, and are now just pulling it out), you can bypass validation entirely by using `Model.model_construct(**data)` instead of `Model(**data)`. `model_construct` completely skips the validation step and instantly assigns the attributes, providing a massive 10x-50x speedup for trusted data. For untrusted data, use `TypeAdapter` to validate raw lists in a single Rust pass.", ["Standard Pydantic instantiation `Model(**data)` runs heavy validation and coercion logic", "If the data is trusted (e.g., from an internal DB), use `Model.model_construct(**data)`", "This bypasses validation entirely, providing massive CPU speedups for large collections"], ["You just write the Pydantic models in C++ instead"]),
    ("B63_2_11", "tradeoff", "hard", "tradeoff", ["Serialization"], "What is the tradeoff of using `MessagePack` over standard `JSON` for serializing payloads between internal Python microservices?", "MessagePack is a binary serialization format. It is drastically faster to parse than JSON and creates much smaller payloads (especially for integers and byte arrays, which JSON struggles with). The massive tradeoff is Human Readability and Observability. If you use JSON, you can intercept the network traffic with Wireshark, `curl` the API, or look at the logs in Datadog and read the payload instantly. With MessagePack, the payloads look like garbled binary `\x81\xa7compact\xc3`. You lose the ability to easily debug API errors without writing custom scripts to unpack the binary data.", ["MessagePack (Binary): Significantly faster parsing and much smaller payload sizes, excellent for internal networking", "JSON (Text): Slower and larger, but universally supported and human-readable", "Tradeoff: MessagePack destroys the ability to easily `curl`, log, or packet-sniff payloads for human debugging"], ["MessagePack sends physical packages in the mail"]),
    ("B63_2_12", "scenario", "medium", "scenario", ["Serialization"], "You use Python's `pickle` to store machine learning models in a database. You rename a class from `OldModel` to `NewModel` in your codebase. Now, when fetching historical data from the database, `pickle.loads()` crashes with an `AttributeError`. How do you fix the schema evolution problem for legacy pickled data?", "Pickle does not store the source code of the class; it only stores the Module name and the Class name as a string reference. When it unpickles, it attempts to import that exact module and class. Because you renamed it, the import fails. To fix this without migrating the entire database, you must provide a backward-compatibility shim. You either create an alias in the old module path (`OldModel = NewModel`), or you implement a custom `Unpickler` class and override the `find_class(self, module, name)` method. In that method, you intercept the request for `OldModel` and explicitly return `NewModel`.", ["Pickle relies on exact string matches for Module and Class paths; renaming classes breaks deserialization instantly", "Fix: Override `pickle.Unpickler.find_class()` to dynamically map the old legacy class name to the new class structure", "Alternatively, leave a permanent alias (`OldModel = NewModel`) in the codebase"], ["You just tell pickle to ignore errors"]),
    ("B63_2_13", "explain", "medium", "explain", ["Serialization"], "Explain why Python's `datetime.datetime.now()` is considered dangerous for JSON serialization in distributed systems, and what you should use instead.", "The standard `datetime.now()` returns a 'Naive' datetime object—it has absolutely no timezone information attached to it. If a server in New York serializes `2023-10-01 12:00:00` and sends it to a server in London, the London server has no idea what timezone that represents, leading to corrupted data and missed SLA deadlines. Furthermore, the standard `json` module throws a `TypeError` because it doesn't know how to serialize datetime objects natively. You must ALWAYS use 'Timezone-Aware' datetimes, specifically UTC (`datetime.now(timezone.utc)`), and serialize them to strict ISO-8601 strings (`.isoformat()`) before passing them to the JSON serializer.", ["`datetime.now()` creates 'Naive' objects lacking timezone context, causing data corruption across global servers", "The standard `json` module cannot natively serialize datetime objects", "Fix: Always use `datetime.now(timezone.utc)` and explicitly convert to ISO-8601 strings (`.isoformat()`)"], ["It's dangerous because the time might change while it's serializing"]),

    # Production Failure Analysis & Diagnostics
    ("B63_2_14", "concept", "medium", "concept", ["Diagnostics & Profiling"], "What is `tracemalloc` in Python, and how does it diagnose 'Unexplained RSS Growth' (Memory Leaks) better than standard Garbage Collection inspection?", "Standard `gc.get_objects()` can tell you that you have 500,000 string objects in memory, but it cannot tell you *where* those strings were created in your massive codebase. `tracemalloc` is a core library that hooks into the Python memory allocator. When enabled, it captures the exact file name and line number of the traceback that allocated every single block of memory. By taking a Snapshot at Time A, and another Snapshot at Time B, you can use `snapshot2.compare_to(snapshot1)` to instantly see precisely which line of code is responsible for the increasing memory footprint.", ["`tracemalloc` hooks the allocator to track the exact file and line number of every memory allocation", "Allows developers to compare Snapshots over time to isolate the exact line of code causing a memory leak", "Far superior to `gc.get_objects()`, which only tells you the object type, not its origin"], ["Tracemalloc is a function that allocates memory to the trace buffer"]),
    ("B63_2_15", "diagnose", "hard", "debugging", ["Diagnostics & Profiling"], "Your Python web scraping application runs flawlessly for 3 hours. Then, it suddenly crashes with `OSError: [Errno 24] Too many open files`. You check the code: every `open()` call is wrapped in a `with` statement. Where is the file descriptor leak coming from?", "The `with` statement guarantees file closure, so the leak is not local files. In Linux, network sockets are also File Descriptors. Web scrapers using `requests` or `aiohttp` open TCP sockets to external websites. If the developer fails to use a `Session` object properly, or if they don't explicitly consume and close the HTTP response body, the TCP socket remains open in a `CLOSE_WAIT` state. The application rapidly exhausts the Linux `ulimit -n` (typically 1024 file descriptors). To fix this, you must use Connection Pooling (e.g., `requests.Session()`) and ensure all HTTP response bodies are fully read or explicitly closed.", ["In Unix, TCP/HTTP network Sockets consume File Descriptors just like local files", "Failing to use HTTP Connection Pooling (`requests.Session()`) or failing to close HTTP responses leaves sockets hanging", "The OS exhausts its `ulimit` for file descriptors, crashing the application"], ["The files were too big to fit in the OS memory"]),
    ("B63_2_16", "implement", "medium", "implement", ["Diagnostics & Profiling"], "How do you implement a continuous CPU profiler using `py-spy` to debug a Python production service that randomly spikes to 100% CPU, without restarting the application?", "`py-spy` is an out-of-process sampling profiler. Unlike `cProfile` (which requires modifying the source code and adds massive execution overhead), `py-spy` runs as a completely separate Linux process. You find the PID of the stuck Python service and run `py-spy top --pid <PID>` or `py-spy record --pid <PID> -o flamegraph.svg`. It safely reads the memory of the running Python process from the outside to determine exactly which line of code is executing. It adds near-zero overhead and does not require pausing or restarting the production application.", ["`py-spy` is an out-of-process sampling profiler", "It reads the memory of the target Python process without modifying the code or requiring a restart", "It adds near-zero overhead, making it safe for production environments to generate Flamegraphs"], ["You inject a spy virus into the server"]),
    ("B63_2_17", "tradeoff", "hard", "tradeoff", ["Diagnostics & Profiling"], "What is the tradeoff of using Python's built-in `cProfile` versus a sampling profiler like `py-spy` or `Austin`?", "`cProfile` is a 'Deterministic Profiler'. It injects C-level hooks into EVERY single function call, return, and exception. It guarantees perfect accuracy and exact call counts. The massive tradeoff is 'Observer Effect' overhead. `cProfile` can slow down a Python application by 50% to 200%. If you run it in production, you will cause a massive outage. Sampling profilers (`py-spy`) take a snapshot of the call stack 100 times a second. The tradeoff is they are statistically estimated (they might miss a function that runs in 1 microsecond), but they add less than 1% overhead, making them the only safe choice for live production debugging.", ["`cProfile` (Deterministic): Perfect accuracy and exact counts, but adds catastrophic overhead (50-200%) making it unusable in production", "Sampling Profilers (py-spy): Snapshots the stack at intervals. Adds near-zero overhead (safe for prod)", "Tradeoff: Sampling is statistical and might miss micro-fast functions, while deterministic profiling crushes performance"], ["cProfile profiles the C code, py-spy profiles the Python code"]),
    ("B63_2_18", "scenario", "medium", "scenario", ["Diagnostics & Profiling"], "Your FastAPI service uses an external Python library to process PDFs. During peak load, the latency spikes from 100ms to 30 seconds. You suspect the PDF library is blocking the Event Loop. How do you definitively prove this using native Python asyncio tools?", "You do not need external profilers for this. Python's `asyncio` module has built-in diagnostics for Event Loop blocking. You enable 'Debug Mode' by setting the environment variable `PYTHONASYNCIODEBUG=1` or running `asyncio.run(main(), debug=True)`. This automatically enables a slow-callback logger. When the PDF library blocks the main thread for more than 100 milliseconds (the default threshold), `asyncio` will print a severe warning to standard out: `Executing <Task...> took 2.5 seconds`. This instantly gives you the exact traceback of the synchronous function that is choking the asynchronous framework.", ["Enable asyncio debug mode via `PYTHONASYNCIODEBUG=1`", "The Event Loop continuously measures the execution time of every single coroutine step", "If a synchronous block exceeds 100ms, it loudly logs the exact traceback of the blocking function"], ["You just guess based on the code lines"]),
    ("B63_2_19", "concept", "hard", "concept", ["Diagnostics & Profiling"], "What is 'Memory Fragmentation' in Python, and why does a long-running process sometimes show 2GB of RAM usage in `htop`, but `sys.getsizeof()` says your objects only use 100MB?", "When Python allocates small objects (lists, dicts), it requests large blocks of memory (Arenas) from the OS via `pymalloc`. If you create 1,000,000 objects and delete 999,999 of them, Python frees the *internal* memory. However, if even ONE small object remains alive inside an Arena, Python mathematically cannot return that 256KB Arena back to the Linux OS. Over days of heavy churning, the memory becomes 'Swiss Cheese'. The OS sees 2GB of RAM checked out (`RSS` in `htop`), but the actual Python data only represents 100MB of that. The only solution is to restart the worker process periodically (e.g., Gunicorn `max_requests`).", ["`pymalloc` requests memory from the OS in large contiguous chunks called Arenas", "If a single object survives in an Arena, the entire Arena cannot be returned to the OS", "This causes 'Swiss Cheese' memory fragmentation, causing massive RSS bloat that requires process restarts to fix"], ["Memory fragmentation is when the hard drive gets scratched"]),
    ("B63_2_20", "diagnose", "medium", "debugging", ["Diagnostics & Profiling"], "You deploy a Python multiprocessing script to an AWS EC2 instance with 16 cores. You set the `Pool(processes=16)`. The CPU utilization only reaches 6%, and the processing takes hours. What is the bottleneck preventing full CPU utilization?", "The developer assumed the task was CPU-bound, but the bottleneck is I/O-bound (e.g., downloading files, querying a slow database). `multiprocessing` spins up 16 distinct Python processes. If each process spends 99% of its time waiting for a network socket to return data, the CPU does nothing (6% utilization). `multiprocessing` is ONLY useful for CPU-bound math/data processing. For I/O-bound tasks, you should use `asyncio` or `ThreadPoolExecutor`, which can spin up 1,000 concurrent network requests on a single core, fully saturating the network bandwidth instead of wasting heavy OS processes.", ["The task is I/O-bound (Network/Disk), not CPU-bound", "16 heavy processes spending all their time waiting on network latency results in near-zero CPU usage", "Fix: Use `asyncio` or Threading for I/O-bound tasks to achieve massive concurrency without process overhead"], ["The AWS instance was asleep"])
]

def run_batch():
    # Load all existing records to do deduplication
    with open(OUT, "r", encoding="utf-8") as f:
        existing = [json.loads(line) for line in f if line.strip()]

    print(f"Loaded {len(existing)} existing records.")
    
    for q in Q:
        if LEAK.search(q[5]) or LEAK.search(q[6]):
            print(f"PROMPT LEAK DETECTED in: {q[5]}")
            sys.exit(1)
            
    existing_texts = [ex["question"] for ex in existing]
    new_texts = [q[5] for q in Q]
    
    vec = TfidfVectorizer(stop_words="english", ngram_range=(1,2))
    all_texts = existing_texts + new_texts
    vec.fit(all_texts)
    
    existing_vecs = vec.transform(existing_texts)
    new_vecs = vec.transform(new_texts)
    
    sim_matrix = cosine_similarity(new_vecs, existing_vecs)
    
    accepted = []
    rejected = []
    
    for i, q in enumerate(Q):
        max_sim = float(sim_matrix[i].max()) if sim_matrix.shape[1] > 0 else 0
        if max_sim > 0.85:
            print(f"REJECTED (Sim: {max_sim:.2f}): {q[5][:50]}...")
            rejected.append(q)
        else:
            accepted.append(q)
            
    print(f"Accepted {len(accepted)} / {len(Q)} questions (Part 2).")
    
    new_records = []
    for q in accepted:
        rec = {
            "primary_role": ROLE,
            "applicable_roles": ["Systems Engineer", "Software Engineer"],
            "primary_skill": q[4][0],
            "secondary_skills": q[4][1:] if len(q[4]) > 1 else [],
            "technology": "Python",
            "topic": q[4][0] if len(q[4]) > 0 else "General",
            "category": "Software Engineering",
            "intent": q[1],
            "difficulty": q[2],
            "question_type": q[3],
            "question": q[5],
            "expected_answer": q[6],
            "evaluation_rubric": {
                "strong_indicators": q[7],
                "weak_indicators": q[8]
            },
            "id": str(uuid.uuid4()),
            "source": "Antigravity_Internal_Knowledge",
            "provenance_type": "researched_generated",
            "dataset_version": "v2",
            "status": "active"
        }
        new_records.append(rec)
        
    with open(OUT, "a", encoding="utf-8") as f:
        for r in new_records:
            f.write(json.dumps(r) + "\n")
            
    # Final audit reporting
    with open(OUT, "r", encoding="utf-8") as f:
        final_existing = [json.loads(line) for line in f if line.strip()]
        
    role_counts = Counter(r["primary_role"] for r in final_existing)
    
    print("\n========================================")
    print("POST-BATCH AUDIT")
    print("========================================")
    print(f"Batch: 63")
    print(f"Target role: {ROLE}")
    print(f"Attempted: {len(Q)}")
    print(f"Accepted: {len(accepted)}")
    print(f"Rejected: {len(rejected)}")
    print(f"Replacement count: 0")
    print(f"Cumulative total: {len(final_existing)}")
    print(f"{ROLE} total: {role_counts[ROLE]}")

if __name__ == "__main__":
    run_batch()
