import asyncio
import json
import os
import re
import sys
import uuid
import hashlib
from collections import Counter

from dotenv import load_dotenv
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
load_dotenv()

BACKEND_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_DIR = os.path.join(BACKEND_DIR, "data")
OUT = os.path.join(DATA_DIR, "interview_question_bank_v2_generated.jsonl")

ROLE = "ML Engineer"
LEAK = re.compile(r"(generate a question|generate \d+ questions|return only json|phase 4c gap plan|"
                  r"generation batch|candidate generation|system instructions|do not proceed|"
                  r"awaiting authorization|minimum target|generation pipeline|"
                  r"batch \d+ generation|expected answer|strong indicator|weak indicator|as an ai|"
                  r"here is the question|\bprompt text\b)", re.I)

Q = [
    # Group 4: Model Monitoring & Drift
    ("B59_4_1", "concept", "medium", "concept", ["Model Monitoring"], "What is the difference between 'Covariate Shift' (Data Drift) and 'Concept Drift' in production ML?", "Covariate Shift occurs when the statistical distribution of the input features changes, but the underlying relationship to the target remains identical (e.g., you trained a model on young users, but suddenly your app gets popular with older users). Concept Drift occurs when the statistical distribution of features is identical, but the underlying mathematical relationship to the target has fundamentally changed (e.g., the definition of 'Fraud' changed because hackers invented a new exploit). Concept Drift is much more dangerous because it directly ruins accuracy.", ["Covariate Shift: Input feature distribution changes, but relationship to target is stable", "Concept Drift: The underlying mathematical relationship between features and target fundamentally changes", "Concept Drift directly ruins model accuracy and requires immediate retraining"], ["Concept drift is when you forget how to code"]),
    ("B59_4_2", "diagnose", "hard", "debugging", ["Model Monitoring"], "Your fraud detection model predicts instantly, but you don't find out if a transaction was actually fraudulent until 90 days later (chargeback). How do you monitor model degradation in real-time when you have a 90-day 'Delayed Label' problem?", "You cannot monitor accuracy, precision, or recall because you lack ground-truth labels. You must monitor 'Prediction Drift' and 'Feature Drift' instead. You track the distribution of the model's outputs (e.g., if the model historically flagged 2% of transactions as fraud, but today it flags 15%, the model is degrading or the environment shifted). You also use statistical tests (like Population Stability Index or Kullback-Leibler divergence) on the input features to detect if the incoming data no longer matches the training data.", ["Cannot calculate accuracy/precision without ground-truth labels (delayed by 90 days)", "Must monitor Proxy Metrics: Prediction Drift (changes in the output distribution)", "Must monitor Feature Drift (using PSI or KL-Divergence) to detect input data shifts"], ["Just ask the users if they are committing fraud"]),
    ("B59_4_3", "implement", "medium", "implement", ["Model Monitoring"], "How do you implement monitoring for 'Feature Drift' in a categorical variable like `User_Country`?", "You cannot use numerical tests like Kolmogorov-Smirnov (KS test) on categorical strings. You must calculate the frequency distribution of each category in the reference (training) dataset (e.g., US: 50%, UK: 30%, CA: 20%). In production, you calculate the real-time frequency over a sliding window (e.g., past 24 hours). You then compare the two probability distributions using the Population Stability Index (PSI), Chi-Square test, or L-Infinity distance. If the PSI exceeds a threshold (e.g., >0.2), it triggers a data drift alert.", ["Categorical variables require frequency distribution comparisons, not numerical tests", "Calculate the historical distribution vs the sliding window production distribution", "Use Population Stability Index (PSI) or Chi-Square to measure the distance and trigger alerts"], ["Convert the strings to floats using ASCII codes"]),
    ("B59_4_4", "tradeoff", "medium", "tradeoff", ["Model Monitoring"], "What is the tradeoff of setting incredibly tight/sensitive alerts on your ML Monitoring dashboard (e.g., alerting if feature drift > 1%)?", "Tight alerts ensure you instantly catch any data anomaly, pipeline break, or subtle model degradation before it harms the business. The severe tradeoff is 'Alert Fatigue'. Data naturally fluctuates on weekends, holidays, and randomly throughout the day. A 1% threshold will trigger hundreds of false-positive alarms. Engineers will begin ignoring the alerts, marking them as spam, and eventually mute the entire PagerDuty channel, meaning a catastrophic 50% drift failure will be completely ignored.", ["Tight alerts catch subtle anomalies and pipeline breaks instantly", "Tradeoff: Causes severe Alert Fatigue due to natural daily/weekly data variance", "Engineers will ignore or mute the alerts, missing actual catastrophic failures"], ["Tight alerts use up all the database storage"]),
    ("B59_4_5", "scenario", "hard", "scenario", ["Model Monitoring"], "You deploy a pricing model. In training, the mean predicted price was $50. In production, the mean predicted price slowly creeps up to $65 over two months. Business metrics look fine. Should you trigger an automated retraining pipeline? Why or why not?", "No, you should not blindly trigger automated retraining on drift. Automated retraining is incredibly dangerous for Concept Drift. If the drift is caused by a broken upstream data pipeline (e.g., a currency conversion bug changing EUR to USD), retraining the model will bake that broken data/bug directly into the new model's weights, making the problem permanent and harder to fix. Drift is a symptom, not a diagnosis. You must manually investigate the root cause of the drift before updating weights.", ["Do not blindly automate retraining on drift alerts", "Drift is often caused by broken upstream data pipelines, not outdated models", "Automated retraining on broken data permanently bakes the bug into the model weights"], ["Yes, models should be retrained every hour automatically"]),
    ("B59_4_6", "explain", "medium", "explain", ["Model Monitoring"], "Explain 'Model Calibration' and why it is critical for business logic, even if the model's ROC-AUC is perfect.", "ROC-AUC only measures 'Ranking' (did the model score the positive case higher than the negative case). However, it ignores the absolute predicted probabilities. A poorly calibrated model might give a true positive a score of 0.4 and a true negative a score of 0.1; the ranking (AUC) is perfect, but the actual probability (0.4) is wrong. Calibration ensures that if the model predicts 0.8 for 100 users, exactly 80 of them actually convert. This is critical because business logic (e.g., Expected Value = Probability * Payout) relies on mathematically accurate probabilities, not just rankings.", ["ROC-AUC measures ranking, but ignores the absolute probability values", "Calibration ensures a predicted probability of 0.8 means exactly an 80% real-world occurrence rate", "Crucial for business math (Expected Value calculations) which rely on true probabilities, not relative ranks"], ["Calibration means cleaning the GPU fans"]),
    ("B59_4_7", "concept", "easy", "concept", ["Model Monitoring"], "What is 'Out-of-Distribution' (OOD) data?", "OOD data refers to input data seen in production that is fundamentally different from the data the model was trained on. This could be data from a new geographic region, values outside the historical min/max range, or an entirely new category. Neural Networks are notoriously bad at OOD data; instead of failing gracefully or saying 'I don't know', they will often output a wildly confident, completely incorrect prediction.", ["Production data that significantly differs from the training dataset", "Values outside historical ranges, new categories, or new demographics", "Models often fail silently on OOD data by making wildly confident but incorrect predictions"], ["Data that was deleted from the hard drive"]),
    ("B59_4_8", "diagnose", "hard", "debugging", ["Model Monitoring"], "A classification model in production suddenly starts predicting 'Class A' for 99% of requests. You check the incoming data pipeline, and all features look perfectly normal (no nulls, means/variances are identical to training). What could cause this silent failure?", "This is a 'Schema or Encoding Mismatch' in the production pipeline, often caused by categorical label encoding. In training, 'City_NewYork' was mapped to integer `1` and 'City_London' to `2`. During a production deployment, the backend engineer used a different hash map or alphabetical sort, accidentally mapping 'City_NewYork' to `2`. The statistical distribution of the features looks perfectly identical to a monitoring tool (the column still contains 50% 1s and 50% 2s), but the semantic meaning is completely scrambled, destroying the model's predictions.", ["Encoding Mismatch: The mapping of categorical strings to integers changed in production", "The statistical distribution (mean/variance) looks perfectly normal to drift monitors", "The semantic meaning of the features is scrambled, causing catastrophic prediction failure"], ["The model got tired of predicting Class B"]),
    ("B59_4_9", "architecture", "medium", "architecture", ["Model Monitoring"], "How do you architect a monitoring system that doesn't add latency to the user's real-time prediction request?", "You cannot perform heavy statistical calculations (like PSI or KS tests) synchronously inside the API route. You must implement asynchronous event logging. The API server computes the prediction, instantly returns it to the user (<50ms), and simultaneously drops a JSON payload (containing the input features, timestamp, and prediction) into an asynchronous Message Queue (Kafka) or a fast append-only log (Fluentd). A separate, offline batch process consumes this queue, aggregates the data into 1-hour windows, and runs the heavy statistical drift tests.", ["Never run heavy statistical drift calculations synchronously in the API route", "Log the inputs and predictions asynchronously to a Message Queue (Kafka) or fast logger", "Use an offline batch process to consume the queue and run drift tests on aggregated windows"], ["Run the monitoring system on a quantum computer"]),
    ("B59_4_10", "tradeoff", "hard", "tradeoff", ["Model Monitoring"], "What is the tradeoff of relying purely on 'Data Quality Rules' (e.g., age > 0, income != null) versus 'Statistical Drift Detection' (e.g., PSI tests) for ML monitoring?", "Data Quality Rules are deterministic, instantly identify the exact broken pipeline (e.g., a SQL bug outputting negative ages), and have zero false positives. The tradeoff is they are rigid; they cannot detect subtle, valid changes in user behavior (e.g., the average age shifting from 25 to 45). Statistical Drift Detection catches these subtle, complex behavioral shifts that degrade models. The tradeoff is Statistical Drift is highly probabilistic, generates massive false-positive alert fatigue, and rarely tells you the specific root cause of the shift.", ["Data Quality Rules are deterministic with zero false positives, but miss subtle behavioral shifts", "Statistical Drift catches complex, valid behavioral shifts that ruin model accuracy", "Tradeoff: Statistical Drift generates massive alert fatigue and lacks root-cause clarity"], ["Data rules require a lawyer to write"]),

    # Group 5: MLOps & CI/CD
    ("B59_5_1", "concept", "medium", "concept", ["MLOps"], "What is a 'Model Registry' and why is it essential for MLOps?", "A Model Registry is the centralized repository (the 'GitHub for Models') that manages the entire lifecycle of ML artifacts. It stores the serialized model files (e.g., `.pkl`, `.onnx`), tracks their lineage (which specific Git commit, data version, and hyperparameter run produced them), and manages their state transitions (e.g., Staging -> Production -> Archived). It ensures that any model running in production can be instantly audited, rolled back, or traced back to the exact code that generated it.", ["A centralized repository managing the lifecycle and state transitions of ML models", "Stores artifacts and tracks lineage (code commits, datasets, hyperparameters)", "Enables auditability, instant rollbacks, and reproducible deployments"], ["It is a government registry where you pay taxes on AI"]),
    ("B59_5_2", "diagnose", "hard", "debugging", ["MLOps"], "You train a model in a Jupyter Notebook. It hits 95% accuracy. You hand the Python script and the dataset to an MLOps engineer. They run the exact same script on the exact same dataset on the CI/CD server, but the model only hits 82% accuracy. Why?", "This is a failure of 'Environment and Seed Reproducibility'. The Jupyter Notebook likely had different implicit state. 1) The notebook was running a different version of scikit-learn or PyTorch, causing algorithmic differences. 2) The Data Scientist did not set a global random seed (`np.random.seed(42)`), so the train/test split or weight initialization was completely different on the CI server. 3) The DS ran cells out-of-order in the notebook, accidentally leaking data or mutating variables in a way the linear script cannot replicate.", ["Lack of Environment Reproducibility (different library versions between Notebook and CI)", "Failure to set global random seeds, causing different train/test splits or weight initialization", "Hidden Notebook state (running cells out of order) cannot be replicated by a linear script"], ["The CI server doesn't have a GPU so it guessed the answers"]),
    ("B59_5_3", "implement", "medium", "implement", ["MLOps"], "How do you implement 'Data Lineage' tracking for an ML training pipeline?", "To achieve true Data Lineage, you cannot just log 'trained on data.csv'. You must use a Data Versioning tool (like DVC) or a modern Data Lake (like Delta Lake / Iceberg). When the training pipeline kicks off, it must query the dataset for its specific immutable commit hash or version timestamp. The pipeline logs this exact hash, along with the Git commit hash of the training code, into the Experiment Tracker (like MLflow). This mathematically links the resulting model artifact to the exact byte-for-byte dataset used to train it.", ["Use Data Versioning tools (DVC) or time-travel Data Lakes (Delta Lake)", "Fetch the immutable commit hash or version timestamp of the dataset", "Log the Data Hash + Code Hash together into the Experiment Tracker (MLflow)"], ["You draw a line connecting the data to the model on a whiteboard"]),
    ("B59_5_4", "tradeoff", "medium", "tradeoff", ["MLOps"], "What is the tradeoff of running Model Training as a step inside your main CI/CD pipeline (e.g., GitHub Actions) versus using a dedicated ML orchestration tool (e.g., Kubeflow/Airflow)?", "Running training in GitHub Actions is incredibly simple to set up and keeps code and training tightly coupled in one repo. The severe tradeoff is compute limitation and timeout restrictions. GitHub Actions runners are generally small CPU VMs with 6-hour timeouts; they cannot train a massive Deep Learning model on an 8-GPU cluster for 3 days. Dedicated ML orchestrators (Kubeflow) manage complex Kubernetes GPU scheduling, distributed training, and massive data pipelines, but require immense infrastructure overhead and DevOps maintenance.", ["CI/CD runners (GitHub Actions) are simple but severely limited by CPU compute and strict timeouts", "Dedicated orchestrators (Kubeflow) handle massive distributed GPU training for days/weeks", "Tradeoff: Orchestrators require massive infrastructure overhead and Kubernetes expertise"], ["GitHub Actions deletes your code after 6 hours"]),
    ("B59_5_5", "scenario", "hard", "scenario", ["MLOps"], "A junior engineer accidentally deploys a completely broken model that rejects 100% of legitimate customer transactions. How do you architect your MLOps pipeline to ensure an instant, 10-second rollback to the previous model?", "You must decouple Model Deployment from Code Deployment. If models are baked into the Docker image, rolling back requires a full 10-minute CI/CD build and container rollout, costing millions in lost transactions. You must architect the API server to dynamically fetch models. The API server listens to the Model Registry (e.g., MLflow). When the engineer clicks 'Revert to V1' in the registry, the registry updates a tag. The running API server polls this tag, detects the change, hot-swaps the V1 model back into RAM, and restores service in milliseconds without restarting the container.", ["Decouple Model Deployment from Code Deployment (do not bake models into Docker images)", "API servers dynamically poll a centralized Model Registry for the 'Production' tag", "Updating the registry tag triggers a hot-swap in RAM, enabling instant millisecond rollbacks"], ["Just unplug the server and plug it back in"]),
    ("B59_5_6", "explain", "medium", "explain", ["MLOps"], "Explain the concept of 'Feature Store Point-in-Time Correctness' and how it prevents Target Leakage.", "When building a training dataset, you join historical events (e.g., 'Loan Application on Jan 5th') with user features. If you simply query `SELECT balance FROM users`, you will get the user's balance *today*, leaking future information into a past event (Target Leakage). A Feature Store maintains an append-only log of all feature changes. It uses 'Point-in-Time' (As-Of) joins to reconstruct exactly what the user's balance was at 11:59 PM on Jan 4th, guaranteeing the model only trains on data that was legally known at the moment of prediction.", ["Prevents joining current/future data to historical events (Target Leakage)", "Maintains an append-only log of all historical feature mutations", "Uses 'As-Of' joins to reconstruct the exact state of features at the precise historical timestamp"], ["It means the feature store uses a Swiss watch for timing"]),
    ("B59_5_7", "concept", "easy", "concept", ["MLOps"], "What is 'Experiment Tracking' in ML?", "Experiment Tracking is the process of logging all the metadata associated with a model training run. Instead of saving models as `model_v5_final_final.pkl` on a laptop, tools like MLflow or Weights & Biases automatically log the hyperparameters (learning rate, depth), the evaluation metrics (accuracy, loss curves), the dataset version, and the resulting artifact. This allows teams to compare hundreds of runs visually and guarantees reproducibility.", ["Logging all metadata associated with a training run (Hyperparameters, Metrics, Code version)", "Replaces chaotic local file naming (`model_final.pkl`) with a searchable database", "Tools like MLflow / Weights & Biases guarantee reproducibility and visual comparison"], ["It means tracking the data scientist's mouse movements"]),
    ("B59_5_8", "diagnose", "medium", "debugging", ["MLOps"], "Your automated retraining pipeline triggers every Sunday. For the past 3 weeks, it has successfully trained a new model, but the API is still serving the model from a month ago. What architectural gap in the MLOps pipeline caused this?", "This is a failure of 'Continuous Deployment / Model Promotion'. The training pipeline (Continuous Training) successfully generated the artifact and likely logged it to the Model Registry. However, there is no automated trigger linking the Registry to the Serving Infrastructure. You must implement a webhook or an evaluation gate. When the new model hits the registry, a script must evaluate it against a baseline. If it passes, the script updates the 'Production' alias, which explicitly triggers the Serving API to pull the new artifact.", ["Continuous Training (CT) is working, but Continuous Deployment (CD) is disconnected", "The pipeline lacks a Model Promotion step (evaluating and tagging the model as 'Production')", "Must implement a trigger/webhook to notify the serving infrastructure to pull the new tagged artifact"], ["The model was too heavy to lift onto the server"]),
    ("B59_5_9", "architecture", "hard", "architecture", ["MLOps"], "How do you architect an MLOps pipeline to handle 'Champion/Challenger' (A/B) model evaluation in production?", "You deploy a fast 'Router' or 'API Gateway' layer in front of the model servers. The Model Registry promotes the current stable model to 'Champion' and the new model to 'Challenger'. The Router dynamically splits incoming traffic based on user ID hashes (e.g., 90% Champion, 10% Challenger) to ensure consistent user experiences. The predictions and user outcomes (e.g., clicks) are logged to a Data Warehouse. A statistical engine (calculating p-values) continuously monitors the logs. If the Challenger achieves statistical significance on the core business metric without degrading latency/errors, the pipeline automatically promotes it to the new Champion.", ["Use an API Gateway/Router to split live traffic deterministically (e.g., 90/10) via User ID hashing", "Log predictions and actual business outcomes (clicks/revenue) to a Data Warehouse", "Use a statistical engine to monitor significance; auto-promote Challenger if it wins safely"], ["You put the models in a wrestling ring and the winner takes production"]),
    ("B59_5_10", "tradeoff", "hard", "tradeoff", ["MLOps"], "What is the tradeoff of baking Machine Learning feature-extraction logic directly into the database (via massive SQL views) versus writing it in the Python training code?", "Baking feature logic into SQL views guarantees massive scale (pushing compute to the data warehouse) and ensures that other BI analysts and backend engineers can use the exact same features simply by querying a table (eliminating training-serving skew). The severe tradeoff is agility and version control. SQL is notoriously difficult to test (no unit tests), hard to version-control (stateful migrations), and forces Data Scientists to rely on Data Engineers for every minor feature tweak, massively slowing down iteration speed compared to modifying a Python Pandas script.", ["SQL views scale massively and eliminate Training-Serving skew by centralizing logic", "Tradeoff: SQL is highly stateful, difficult to unit test, and hard to version control", "Tradeoff: Destroys Data Scientist agility, forcing them to rely on Data Engineering bottlenecks"], ["SQL uses less electricity than Python"]),

    # Group 6: Ranking & Recommendation Systems
    ("B59_6_1", "concept", "medium", "concept", ["Recommendation Systems"], "What is the 'Two-Tower' architecture in recommendation systems?", "The Two-Tower architecture is the industry standard for the 'Retrieval/Candidate Generation' phase. It consists of a User Tower (a neural network processing user features/history) and an Item Tower (processing item features/metadata). Both towers map their inputs into the exact same shared embedding space. To find the best items for a user, you compute the Dot Product (or Cosine Similarity) between the User Embedding and all Item Embeddings. Because the Item embeddings can be pre-computed and stored in an HNSW Vector Database, you can retrieve the top 1,000 items out of 100 million in milliseconds.", ["Uses separate neural networks (User Tower and Item Tower) mapped to a shared embedding space", "Computes similarity (Dot Product) between the User vector and Item vectors", "Allows pre-computing Item vectors for ultra-fast millisecond retrieval from a Vector DB"], ["It consists of two physical server towers to handle the traffic"]),
    ("B59_6_2", "diagnose", "hard", "debugging", ["Recommendation Systems"], "Your recommendation engine works perfectly for existing products. Marketing adds 10,000 new products to the catalog today. Over the next week, none of the new products are ever recommended to users. Why?", "This is the classic 'Item Cold Start' problem caused by Collaborative Filtering. CF algorithms rely strictly on historical user interaction matrices (who clicked what). Because the new items have exactly zero clicks, the algorithm mathematically cannot calculate their similarity to other items or users, effectively burying them forever. To fix this, you must implement Content-Based Filtering (using NLP/Vision to embed the item's description/image) or force an 'Exploration' algorithm (like Multi-Armed Bandits) to artificially inject new items into feeds to gather initial click data.", ["Item Cold Start: Collaborative Filtering requires historical clicks to rank items", "New items with zero clicks are mathematically invisible to interaction-based algorithms", "Fix by using Content-Based Filtering (metadata embeddings) or Multi-Armed Bandits for forced exploration"], ["The new products are ugly and nobody wants them"]),
    ("B59_6_3", "implement", "medium", "implement", ["Recommendation Systems"], "How do you implement the 'Exploration vs Exploitation' tradeoff using an Epsilon-Greedy algorithm?", "In a recommendation feed, 'Exploitation' means showing the user the exact items the model predicts they will click (maximizing immediate revenue). 'Exploration' means showing them random or brand new items to discover new interests and gather data on cold-start items. Epsilon-Greedy implements this by defining a variable epsilon (e.g., `e = 0.10`). For every item slot, the system generates a random number. If the number is > 0.10, it Exploits (shows the highest ranked item). If the number is < 0.10, it Explores (shows a random/new item).", ["Exploitation maximizes immediate revenue; Exploration gathers data on new items/interests", "Define epsilon (`e = 0.10`) as the exploration rate", "90% of the time show the top-ranked item; 10% of the time force a random/new item into the feed"], ["You exploit the user's data and explore their bank account"]),
    ("B59_6_4", "tradeoff", "hard", "tradeoff", ["Recommendation Systems"], "What is the architectural tradeoff of using a single massive Deep Learning model for ranking 100 million items versus a Two-Stage (Retrieval + Ranking) pipeline?", "A single massive Cross-Encoder or Deep Learning ranking model provides perfect accuracy because it evaluates the complex interaction between the User and the Item simultaneously. The catastrophic tradeoff is O(N) latency. Running inference on 100 million items dynamically for a single user request will take hours. A Two-Stage pipeline trades slight accuracy for massive speed. Stage 1 (Retrieval) uses a fast, dumb algorithm (like Two-Tower or Matrix Factorization) to instantly filter 100M items down to 1,000 candidates. Stage 2 (Ranking) applies the heavy Deep Learning model only to those 1,000 candidates, returning results in milliseconds.", ["Single heavy model offers perfect accuracy but O(N) latency (takes hours to score 100M items)", "Two-Stage pipeline uses a fast/dumb Retrieval phase to narrow 100M down to 1,000 candidates", "Applies the heavy, highly accurate Ranking model only to the 1,000 candidates to achieve millisecond latency"], ["Deep learning models get dizzy if they look at too many items"]),
    ("B59_6_5", "scenario", "medium", "scenario", ["Recommendation Systems"], "You are building a 'Similar Products' carousel for an e-commerce site. A user is looking at a $5,000 Rolex watch. The system recommends a $10 Casio watch because both are 'Men's Watches'. How do you re-architect the feature engineering to prevent this?", "The model is relying too heavily on broad categorical tags ('Category = Watch') and ignoring continuous latent features. You must engineer 'Price' and 'Brand Prestige' as heavy features. More effectively, you should implement Session-Based Collaborative Filtering (Item2Vec). The algorithm learns that users who view $5,000 Rolexes subsequently view $6,000 Omegas in the same session, not $10 Casios. This embeds the items based on actual sequential user behavior, capturing the latent 'luxury' dimension without manual tagging.", ["The model over-relies on broad categorical tags, missing latent dimensions like 'luxury' or 'price band'", "Must engineer Price embeddings or Brand embeddings directly", "Implement Session-Based Collaborative Filtering (Item2Vec) to capture actual sequential user viewing behavior"], ["Just ban cheap watches from the website"]),
    ("B59_6_6", "explain", "medium", "explain", ["Recommendation Systems"], "Explain what 'Matrix Factorization' is in the context of Collaborative Filtering.", "Imagine a massive, highly sparse matrix where rows are Users, columns are Movies, and cells are Ratings (1-5). Matrix Factorization mathematically decomposes this massive matrix into two much smaller, dense matrices: a User Matrix and an Item Matrix. Each row in the new matrices represents a 'Latent Vector' (e.g., 50 dimensions). These dimensions abstractly capture concepts like 'Comedy' or 'Action' without being explicitly told. By calculating the dot product of a User's latent vector and a Movie's latent vector, you can predict exactly how the user would rate a movie they haven't seen yet.", ["Decomposes a massive, sparse User-Item interaction matrix into two smaller, dense matrices", "Extracts 'Latent Vectors' that implicitly capture concepts like genre or style", "Predicts missing ratings by calculating the dot product of the User and Item latent vectors"], ["It means factoring the matrix out of the equation to save RAM"]),
    ("B59_6_7", "concept", "easy", "concept", ["Recommendation Systems"], "What is the 'User Cold Start' problem?", "The User Cold Start problem occurs when a brand new user registers for a service. Because they have zero historical interactions, clicks, or purchases, collaborative filtering algorithms have absolutely no data to profile them. The system cannot calculate their similarity to other users. To mitigate this, systems usually force the user through an 'Onboarding Questionnaire' (e.g., 'Pick 3 genres you like'), use location/device metadata, or simply display a 'Global Top Trending' fallback feed until enough click data is collected.", ["Occurs when a brand new user has zero historical interactions or clicks", "Collaborative algorithms cannot profile them or calculate similarity to others", "Mitigated via onboarding surveys, device metadata, or falling back to Global Trending feeds"], ["It happens when the user forgets their password"]),
    ("B59_6_8", "diagnose", "hard", "debugging", ["Recommendation Systems"], "You implement a sophisticated Deep Learning ranking model optimized for Click-Through Rate (CTR). CTR goes up 200%. However, overall company Revenue drops by 30%, and user retention plummets. What did the model do?", "The model discovered 'Clickbait'. By strictly optimizing the mathematical objective function (Clicks), the neural network realized that sensationalist, misleading, or highly controversial thumbnails generate the most clicks. Users click, realize the content is garbage or irrelevant (low dwell time/completion rate), and churn from the platform, destroying long-term revenue. To fix this, you must change the Objective Function to optimize for 'Watch Time', 'Completion Rate', or 'Expected Lifetime Value', not just raw binary clicks.", ["The model optimized strictly for Clicks, promoting sensationalist Clickbait", "Users click but immediately bounce due to low quality, destroying retention and revenue", "Fix by changing the objective function to optimize for Dwell Time, Completion Rate, or LTV"], ["The model accidentally deleted the checkout button"]),
    ("B59_6_9", "architecture", "hard", "architecture", ["Recommendation Systems"], "How do you architect a system to handle real-time 'In-Session' recommendations (e.g., TikTok updating your feed based on a video you watched 2 seconds ago)?", "Batch-processed matrix factorization runs nightly and cannot adapt to a user's current mood. To architect in-session real-time recs, you must use a Sequence Model (like GRU4Rec or Transformers). 1) The user's clicks are streamed via Kafka to a fast online feature store (Redis). 2) The sequence of the last 10 item embeddings is fetched in milliseconds. 3) An online RNN/Transformer model processes this sequence dynamically to predict the next intent. 4) The output vector is used to query the Vector DB for the next items. This entire loop happens synchronously in <100ms.", ["Batch pipelines (nightly SQL) cannot adapt to split-second user mood changes", "Must use Sequence Models (RNNs/Transformers) that process the rolling window of the last N clicks", "Stream clicks to Redis, fetch the sequence, and run dynamic online inference in <100ms"], ["You use a really fast SQL query in a `while True` loop"]),
    ("B59_6_10", "tradeoff", "medium", "tradeoff", ["Recommendation Systems"], "What is the tradeoff of using 'Content-Based Filtering' versus 'Collaborative Filtering'?", "Content-Based Filtering uses the attributes of the item (e.g., NLP on a book's summary). It solves the Cold Start problem effortlessly (new books have summaries) and provides highly interpretable recommendations. The severe tradeoff is the 'Filter Bubble'; it will only ever recommend things exactly like what you already consume, offering zero serendipity. Collaborative Filtering uses collective human behavior. It offers incredible serendipity (discovering a sci-fi book because users with your exact weird taste also liked it), but completely fails on new items (Cold Start) and is computationally massive.", ["Content-Based solves Cold Starts and is interpretable, but traps users in rigid Filter Bubbles (no serendipity)", "Collaborative Filtering provides massive serendipity by leveraging collective human behavior", "Tradeoff: Collaborative fails entirely on new items (Cold Start) and requires massive matrices"], ["Content-based means filtering out bad words"])
]

def run_batch():
    with open(OUT, "a", encoding="utf-8") as f:
        for q in Q:
            rec = {
                "primary_role": ROLE,
                "applicable_roles": ["Data Scientist", "Backend Developer"],
                "primary_skill": q[4][0],
                "secondary_skills": q[4][1:] if len(q[4]) > 1 else [],
                "technology": "Machine Learning",
                "topic": q[4][0] if len(q[4]) > 0 else "General",
                "category": "AI/ML",
                "intent": q[1],
                "difficulty": q[2],
                "question_type": q[3],
                "question": q[5],
                "expected_answer": q[6],
                "evaluation_rubric": {
                    "strong_indicators": q[7],
                    "weak_indicators": q[8]
                },
                "id": str(uuid.uuid4()),
                "source": "Antigravity_Internal_Knowledge",
                "provenance_type": "researched_generated",
                "dataset_version": "v2",
                "status": "active"
            }
            f.write(json.dumps(rec) + "\n")
            
    print(f"Appended {len(Q)} questions (Batch 59 Part 2).")

if __name__ == "__main__":
    run_batch()
