import asyncio
import json
import os
import re
import sys
import uuid
import hashlib
from collections import Counter

from dotenv import load_dotenv
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
load_dotenv()

BACKEND_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_DIR = os.path.join(BACKEND_DIR, "data")
OUT = os.path.join(DATA_DIR, "interview_question_bank_v2_generated.jsonl")

ROLE = "ML Engineer"
LEAK = re.compile(r"(generate a question|generate \d+ questions|return only json|phase 4c gap plan|"
                  r"generation batch|candidate generation|system instructions|do not proceed|"
                  r"awaiting authorization|minimum target|generation pipeline|"
                  r"batch \d+ generation|expected answer|strong indicator|weak indicator|as an ai|"
                  r"here is the question|\bprompt text\b)", re.I)

Q = [
    # Group 7: Advanced Evaluation
    ("B59_7_1", "concept", "medium", "concept", ["Model Evaluation"], "In an imbalanced classification problem (e.g., 99% benign, 1% fraud), why is ROC-AUC a misleading metric, and why is PR-AUC (Precision-Recall AUC) preferred?", "ROC-AUC plots True Positive Rate against False Positive Rate. Because the negative class (benign) is so massive (99%), a model can generate 10,000 False Positives and the False Positive Rate (FPR = FP/TN) will barely move, keeping the ROC-AUC artificially high and making a terrible model look great. PR-AUC evaluates Precision (TP / (TP + FP)). It completely ignores True Negatives, severely punishing the model for those 10,000 False Positives, making it the only reliable metric for highly imbalanced datasets.", ["ROC-AUC is artificially inflated by massive True Negative counts in imbalanced datasets", "FPR barely moves even with thousands of False Positives", "PR-AUC ignores True Negatives and focuses purely on Precision, exposing False Positives accurately"], ["ROC-AUC is for birds, PR-AUC is for mammals"]),
    ("B59_7_2", "diagnose", "hard", "debugging", ["Model Evaluation"], "You are evaluating a time-series forecasting model. Using standard K-Fold Cross Validation, the model achieves 95% accuracy. When deployed to production, it fails completely. Why did K-Fold invalidate your evaluation?", "Standard K-Fold randomly shuffles data and partitions it into folds. In a time-series dataset, this means the training set will contain data from December, and the validation fold will test on data from October. You just allowed the model to peek into the future to predict the past (Target Leakage). Time-series models must be evaluated using strictly 'Temporal Validation' (or Time-Series Split), where the training set is always chronologically prior to the validation set (e.g., Train on Jan-Oct, Validate on Nov).", ["Standard K-Fold randomly shuffles data, ignoring chronology", "Allows the model to train on 'future' data to predict 'past' data (Target Leakage)", "Fix by using strict Temporal Validation / Time-Series Split (Train on past, Predict the future)"], ["K-Fold requires exactly 10 folds, you used 5"]),
    ("B59_7_3", "implement", "medium", "implement", ["Model Evaluation"], "How do you implement 'Threshold Tuning' for a binary classifier when False Negatives cost the business $1,000 but False Positives only cost $10?", "By default, `.predict()` uses a threshold of 0.5. Because False Negatives are 100x more expensive, using 0.5 is a catastrophic financial decision. You must use `.predict_proba()` to get the raw probabilities. You then iterate over every possible threshold (from 0.01 to 0.99), multiplying the resulting Confusion Matrix by your custom Cost Matrix ($1000 for FN, $10 for FP). You select the mathematical threshold (e.g., 0.15) that minimizes the total dollar cost to the business, completely ignoring academic metrics like Accuracy or F1.", ["Default 0.5 thresholds ignore asymmetric business costs", "Use `.predict_proba()` and test thresholds from 0.01 to 0.99", "Multiply the Confusion Matrix by the Business Cost Matrix to find the threshold that minimizes dollar loss"], ["Just tell the model to be more careful"]),
    ("B59_7_4", "tradeoff", "hard", "tradeoff", ["Model Evaluation"], "What is the tradeoff of relying solely on Offline Evaluation (Holdout test sets) versus Online Evaluation (A/B testing) to approve a model for production?", "Offline Evaluation is safe, fast, and completely free of user impact. The severe tradeoff is 'Offline-Online Metric Skew'. A model might improve offline Log-Loss by 5%, but when deployed, the users might hate the new recommendations and churn, dropping revenue by 10%. Offline metrics (AUC/Loss) rarely correlate perfectly with actual human behavior. Online Evaluation (A/B testing) measures ground-truth business metrics (Revenue/Click-Through Rate), but risks showing broken models to live users, potentially harming the brand.", ["Offline is safe and fast, but suffers from Offline-Online Metric Skew (AUC != Revenue)", "Offline metrics rarely perfectly predict actual human behavioral changes", "Online A/B Testing measures ground truth but risks exposing broken experiences to live users"], ["Offline evaluation works without internet, online requires WiFi"]),
    ("B59_7_5", "scenario", "medium", "scenario", ["Model Evaluation"], "Your ranking model predicts the exact probability that a user will click an ad. The marketing team wants to bid on these ads, but they complain the model is 'overconfident', predicting 99% for ads that only click 40% of the time. The AUC is perfect. How do you fix this?", "The model has excellent Ranking (AUC) but terrible Calibration. Because neural networks and boosted trees often push probabilities to extremes (0 or 1), you must implement 'Platt Scaling' or 'Isotonic Regression' as a post-processing step. You hold out a validation dataset, pass it through the trained model, and map the model's raw uncalibrated scores to the actual empirical click rates. This calibration layer guarantees that a predicted score of 0.4 perfectly aligns with a 40% real-world click rate.", ["Neural networks and trees are notoriously uncalibrated, pushing scores to extremes", "AUC is perfect, but the absolute probabilities are useless for bidding math", "Fix by applying Platt Scaling or Isotonic Regression on a holdout set to calibrate probabilities"], ["Make the model apologize to the marketing team"]),
    ("B59_7_6", "explain", "medium", "explain", ["Model Evaluation"], "Explain the concept of 'Information Leakage' (Data Leakage) caused by improper Preprocessing.", "Information Leakage occurs when you apply a preprocessing step (like StandardScaler or TF-IDF) to the ENTIRE dataset before splitting it into Train and Test sets. When you compute the Mean and Variance for scaling on the entire dataset, the training data mathematically absorbs information about the test data's distribution. The model will appear to perform amazingly well, but will fail in production. You must ALWAYS split the data into Train/Test first, fit the scaler ONLY on the Train set, and then apply that scaler to the Test set.", ["Applying standardizers/scalers to the entire dataset before Train/Test splitting", "The Train set mathematically absorbs the statistical distribution (Mean/Variance) of the Test set", "Must Split first -> Fit scaler on Train only -> Transform Train and Transform Test"], ["Information Leakage is when hackers steal your dataset"]),
    ("B59_7_7", "concept", "easy", "concept", ["Model Evaluation"], "What is the difference between Precision and Recall?", "Precision asks: 'Out of all the items the model flagged as Positive, how many were actually Positive?' (Focuses on minimizing False Positives/Crying Wolf). Recall asks: 'Out of all the ACTUAL positive items in the real world, how many did the model successfully find?' (Focuses on minimizing False Negatives/Missing things). They are inversely related; improving one usually degrades the other.", ["Precision: Of all predicted positives, how many are true? (Minimizes False Positives)", "Recall: Of all actual positives, how many were caught? (Minimizes False Negatives)", "Inversely related: raising the threshold increases precision but lowers recall"], ["Precision is for math, Recall is for memory"]),
    ("B59_7_8", "diagnose", "hard", "debugging", ["Model Evaluation"], "You train a churn prediction model. The overall accuracy is 85%. However, when deployed, it fails to predict churn for high-net-worth users, causing massive revenue loss. You check the training data and high-net-worth users represent only 2% of the dataset. How do you evaluate and fix this?", "Global accuracy is masking severe sub-population failures (Slice-based failure). The model optimized for the 98% majority class (low-net-worth users). To diagnose, you must evaluate metrics specifically on 'Data Slices' (e.g., calculate F1 score purely for `wealth_tier='high'`). To fix it, you cannot just use global class weights. You must either oversample the minority slice, use Sample Weighting specifically penalizing errors on high-net-worth rows, or train a separate ensemble model explicitly for the VIP segment.", ["Global accuracy masks severe failures on critical minority sub-populations (Data Slices)", "Must evaluate metrics grouped by critical business slices (Slice-Based Evaluation)", "Fix by applying heavy Sample Weights to the VIP rows or oversampling that specific slice"], ["High net worth users don't use ML models"]),
    ("B59_7_9", "architecture", "hard", "architecture", ["Model Evaluation"], "How do you architect an evaluation pipeline for a model where the ground-truth labels are never known? (e.g., a chatbot response generator)", "When ground-truth labels are absent, you cannot use deterministic metrics like F1 or RMSE. You must architect a 'Proxy Evaluation' pipeline. 1) Use a powerful LLM (like GPT-4) as an automated Judge to score the chatbot's response on a scale of 1-5 for relevance and toxicity. 2) Implement implicit telemetry: track if the user clicked 'Copy', gave a 'Thumbs Up', or immediately closed the window (User Engagement metrics). 3) Use embedding distance (Cosine Similarity) between the user's question and the answer to measure semantic drift. Aggregate these proxies into a unified health score.", ["Cannot use deterministic metrics (F1/RMSE) without ground-truth labels", "Use LLM-as-a-Judge to score responses for quality and safety", "Capture implicit user telemetry (Thumbs Up, Copy clicks, Dwell time) as proxy metrics"], ["You just guess if the model is good"]),
    ("B59_7_10", "tradeoff", "medium", "tradeoff", ["Model Evaluation"], "What is the tradeoff of evaluating a regression model using RMSE (Root Mean Squared Error) versus MAE (Mean Absolute Error)?", "RMSE squares the errors before averaging them. This means it aggressively penalizes large outliers. If a model is off by 100 on one prediction, the penalty is 10,000. This is useful when large errors are catastrophically bad for the business. The tradeoff is that a few dirty data points or extreme outliers in the test set will completely ruin the RMSE score, hiding a generally well-performing model. MAE treats all errors linearly. It is highly robust to outliers (a 100 error is just a penalty of 100), but won't warn you if the model occasionally makes catastrophic mistakes.", ["RMSE squares errors, aggressively penalizing massive outliers", "Tradeoff: RMSE is easily ruined by a few dirty data points, masking general performance", "MAE is linear and robust to outliers, but ignores the severe business cost of catastrophic errors"], ["RMSE is measured in feet, MAE is measured in meters"]),

    # Group 8: Deep Learning Systems & Inference
    ("B59_8_1", "concept", "medium", "concept", ["Deep Learning Engineering"], "What is 'Model Quantization' (e.g., INT8/FP8), and how does it accelerate inference?", "Quantization reduces the precision of the weights and activations in a Neural Network. Instead of using 32-bit floats (FP32), it maps them to 8-bit integers (INT8). This slashes the model's memory footprint by 75%, allowing it to fit into much smaller, cheaper GPUs. More importantly, it accelerates inference because fetching 8-bit numbers from VRAM uses 4x less Memory Bandwidth (the primary bottleneck), and modern GPUs have specialized hardware (Tensor Cores) that perform INT8 math significantly faster than FP32 math.", ["Reduces the precision of weights/activations from FP32 to INT8", "Slashes memory footprint by 75% and drastically reduces Memory Bandwidth bottlenecks", "Leverages specialized GPU hardware (Tensor Cores) for vastly faster integer math"], ["Quantization means adding quantum mechanics to the AI"]),
    ("B59_8_2", "diagnose", "hard", "debugging", ["Deep Learning Engineering"], "You apply Post-Training Quantization (PTQ) to convert your PyTorch model to INT8. The model size shrinks by 75%, but the accuracy drops from 95% to 40%. What happened, and how do you fix it?", "This is a catastrophic Quantization Error caused by 'Outliers' in the network's activations. If a specific layer produces activations ranging from -2 to +2, but one outlier activation is +100, the entire 8-bit integer range (-128 to 127) is stretched to cover the +100 outlier. This crushes the subtle -2 to +2 values into a single bucket (e.g., they all become 0), destroying the network's logic. You must fix this by using Quantization-Aware Training (QAT), which simulates the INT8 precision during the training phase so the network learns to route around or minimize outliers.", ["Outlier activations stretch the limited INT8 integer range, crushing subtle data into zero", "Destroys the network's precision and logic, plummeting accuracy", "Fix by using Quantization-Aware Training (QAT) to let the network adapt to the precision loss during training"], ["The GPU forgot how to do math"]),
    ("B59_8_3", "implement", "medium", "implement", ["Deep Learning Engineering"], "How do you implement 'Graph Compilation' (e.g., `torch.compile` or TensorRT) to speed up deep learning inference?", "In standard PyTorch (eager mode), the Python interpreter executes every single mathematical operation (Layer 1 -> ReLU -> Layer 2) sequentially, creating massive overhead and hundreds of separate trips to the GPU memory. Graph Compilation analyzes the entire neural network structure ahead of time to create a Static Computation Graph. It implements 'Operator Fusion'—merging the Layer 1 matrix multiplication and the ReLU activation into a single, highly optimized CUDA kernel. This drastically reduces memory read/writes and bypasses the slow Python interpreter entirely during inference.", ["Eager mode executes ops sequentially, causing massive Python overhead and memory trips", "Graph compilation analyzes the entire network to create a Static Computation Graph", "Implements Operator Fusion (merging multiple layers into a single CUDA kernel) to bypass overhead"], ["You print the graph on paper and compile it in a binder"]),
    ("B59_8_4", "tradeoff", "hard", "tradeoff", ["Deep Learning Engineering"], "What is the architectural tradeoff of using a 'Dynamic Computation Graph' (e.g., standard PyTorch) versus a 'Static Computation Graph' (e.g., TensorFlow 1.x / TensorRT) for model serving?", "Dynamic graphs are evaluated on-the-fly, allowing for highly flexible architectures like variable-length RNNs, dynamic branching (if/else statements inside the forward pass), and easy debugging (standard Python print statements). The tradeoff is slow inference speed and inability to aggressively optimize kernels. Static graphs are locked and compiled ahead of time. You cannot easily change input sizes or use dynamic branching. The massive advantage is that the compiler can perform aggressive Operator Fusion, memory pre-allocation, and hardware-specific kernel tuning, resulting in vastly faster, production-grade inference.", ["Dynamic (PyTorch): Highly flexible, allows if/else branching, easy to debug. Tradeoff: Slow inference.", "Static (TensorRT): Locked architecture, no dynamic branching.", "Advantage: Compiler performs Operator Fusion and memory pre-allocation for vastly faster inference."], ["Dynamic graphs move around the screen, static graphs stand still"]),
    ("B59_8_5", "scenario", "medium", "scenario", ["Deep Learning Engineering"], "You deploy a Deep Learning vision model to a fleet of edge devices (Raspberry Pis). The model takes 5 seconds per image. You cannot upgrade the hardware, and quantization only reduced it to 3 seconds. How do you re-architect the model itself?", "You must implement 'Model Pruning' or 'Knowledge Distillation'. Pruning evaluates the trained model and systematically deletes the weights/neurons that contribute the least to the output (setting them to zero), converting dense matrices into sparse matrices. Knowledge Distillation trains a massive, highly accurate 'Teacher' model, and then trains a tiny, blazingly fast 'Student' model to mimic the Teacher's exact output probabilities. The Student model will be fractions of the size and hit sub-second latency on edge hardware.", ["Implement Knowledge Distillation (train a tiny Student model to mimic a massive Teacher model)", "Implement Model Pruning (systematically delete unimportant weights to create sparse matrices)", "Fundamentally reduces the mathematical operations required for an inference pass on weak hardware"], ["Spray the Raspberry Pi with compressed air"]),
    ("B59_8_6", "explain", "medium", "explain", ["Deep Learning Engineering"], "Explain the 'Memory Wall' problem in modern Deep Learning inference.", "The Memory Wall refers to the growing gap between the processing speed of GPU compute cores (TFLOPS) and the data transfer speed of the GPU memory (VRAM bandwidth). Modern GPUs can perform matrix multiplications incredibly fast. However, for a Transformer model to generate a token, it must load the entire multi-gigabyte weight matrix from VRAM into the compute cores. The compute cores finish the math instantly, then sit idle waiting for the next weights to arrive. Inference is almost entirely bottlenecked by memory bandwidth (moving the data), not compute capability.", ["The gap between ultra-fast GPU compute cores and slow VRAM data transfer speeds", "GPUs finish math instantly, then sit idle waiting for weights to be loaded from memory", "Inference is bottlenecked by Memory Bandwidth (data movement), not actual math compute"], ["The Memory Wall is a memorial for broken hard drives"]),

    # Group 9: Online/Continuous Learning
    ("B59_9_1", "concept", "medium", "concept", ["Continuous Training"], "What is 'Catastrophic Forgetting' in Continuous/Online Learning?", "Catastrophic Forgetting occurs when a neural network is incrementally trained on a stream of new data (e.g., fine-tuning yesterday's model on today's logs). As the gradient descent optimizes the weights for the new data, it aggressively overwrites the weights that were critical for understanding the old data. The model learns the new patterns perfectly but completely forgets the historical patterns, causing accuracy to plummet on older, stable edge cases.", ["Occurs when a model is incrementally trained on a stream of new data", "Gradient descent overwrites weights critical for understanding historical data", "The model learns the new patterns but completely forgets the older, stable patterns"], ["It happens when the Data Scientist forgets to save the model"]),
    ("B59_9_2", "diagnose", "hard", "debugging", ["Continuous Training"], "Your Continuous Training pipeline fine-tunes your NLP model on daily user queries. On Friday, a massive spam bot attack floods the system. On Saturday, the model is completely corrupted and classifies everything as spam. How do you prevent a data anomaly from poisoning an online learning system?", "Online Learning systems are highly vulnerable to Data Poisoning. If bad data enters the stream, it is immediately baked into the model's weights. To fix this, you cannot train directly on raw streams. You must implement 1) Strict Anomaly Detection / Statistical filtering on the incoming data before it hits the training queue. 2) 'Replay Buffers': mixing the new daily data with a curated, pristine 'Golden Dataset' of historical data during the fine-tuning step to anchor the model and prevent catastrophic forgetting or poisoning.", ["Online learning is highly vulnerable to rapid Data Poisoning from spikes or anomalies", "Must implement strict upstream statistical filtering / anomaly detection on training data", "Must use a 'Replay Buffer' (mixing new data with a curated historical Golden Dataset) to anchor weights"], ["The model got scared of the bots"]),
    ("B59_9_3", "implement", "medium", "implement", ["Continuous Training"], "How do you implement 'Shadow State' monitoring to determine exactly when a batch model needs to be retrained?", "Instead of blindly retraining the model every week (which wastes compute and risks deploying a worse model), you implement a continuous monitoring trigger. You log the live production inputs and wait for the ground-truth labels to arrive. You continuously compute the production model's accuracy on the fly. Simultaneously, you calculate the Statistical Drift (PSI) of the incoming features. You configure a Webhook/Airflow trigger: ONLY when the rolling 7-day accuracy drops below an SLA (e.g., 85%), or the Data Drift PSI exceeds 0.2, the system automatically triggers a new training pipeline run.", ["Do not retrain on fixed schedules; it wastes compute and adds risk", "Continuously log live inputs, join with delayed ground-truth labels, and calculate real-time accuracy", "Trigger retraining ONLY when accuracy breaches an SLA or Data Drift exceeds a strict threshold"], ["You shadow the model by following it home"]),
    ("B59_9_4", "tradeoff", "hard", "tradeoff", ["Continuous Training"], "What is the tradeoff of using true 'Online Learning' (updating weights via Stochastic Gradient Descent on every single live user request) versus 'Micro-Batch Continuous Training' (retraining hourly)?", "True Online Learning adapts instantly to user behavior in milliseconds, providing the ultimate personalized experience (e.g., TikTok). The severe tradeoff is immense engineering complexity, extreme vulnerability to adversarial data poisoning (a user deliberately manipulating the model in real-time), and the inability to properly run evaluation metrics or rollbacks. Micro-Batching (hourly) provides a 1-hour delay in adaptation, but allows you to aggregate the data, run anomaly detection, run an automated validation test suite on the new weights, and safely promote the model using standard CI/CD.", ["True Online adapts instantly but is highly vulnerable to adversarial data poisoning and cannot be safely validated", "Micro-Batch (hourly) delays adaptation but allows for data sanitization, validation suites, and safe rollbacks", "Tradeoff: Instant personalization vs Safety, Security, and Validation"], ["Online learning requires the model to have a webcam"])
]

def run_batch():
    # Write directly to file
    with open(OUT, "a", encoding="utf-8") as f:
        for q in Q:
            rec = {
                "primary_role": ROLE,
                "applicable_roles": ["Data Scientist", "Backend Developer"],
                "primary_skill": q[4][0],
                "secondary_skills": q[4][1:] if len(q[4]) > 1 else [],
                "technology": "Machine Learning",
                "topic": q[4][0] if len(q[4]) > 0 else "General",
                "category": "AI/ML",
                "intent": q[1],
                "difficulty": q[2],
                "question_type": q[3],
                "question": q[5],
                "expected_answer": q[6],
                "evaluation_rubric": {
                    "strong_indicators": q[7],
                    "weak_indicators": q[8]
                },
                "id": str(uuid.uuid4()),
                "source": "Antigravity_Internal_Knowledge",
                "provenance_type": "researched_generated",
                "dataset_version": "v2",
                "status": "active"
            }
            f.write(json.dumps(rec) + "\n")
            
    print(f"Appended {len(Q)} questions (Batch 59 Part 3).")

if __name__ == "__main__":
    run_batch()
