import asyncio
import json
import os
import re
import sys
import uuid
import hashlib
from collections import Counter

from dotenv import load_dotenv
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
load_dotenv()

BACKEND_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_DIR = os.path.join(BACKEND_DIR, "data")
OUT = os.path.join(DATA_DIR, "interview_question_bank_v2_generated.jsonl")

ROLE = "Full Stack Developer"
LEAK = re.compile(r"(generate a question|generate \d+ questions|return only json|phase 4c gap plan|"
                  r"generation batch|candidate generation|system instructions|do not proceed|"
                  r"awaiting authorization|minimum target|generation pipeline|"
                  r"batch \d+ generation|expected answer|strong indicator|weak indicator|as an ai|"
                  r"here is the question|\bprompt text\b)", re.I)

Q = [
    # Group 4: End-to-End Performance
    ("B60_4_1", "concept", "medium", "concept", ["End-to-End Performance"], "What is the architectural tradeoff of using SSR (Server-Side Rendering) versus CSR (Client-Side Rendering) for a content-heavy e-commerce site?", "SSR executes the JavaScript and API calls on the backend server, sending fully constructed HTML to the browser. This provides incredible SEO (crawlers see instant HTML) and an instant First Contentful Paint (FCP) for users on slow mobile networks. The tradeoff is 'Time to Interactive' (TTI) delay (the page is visible but the buttons don't work until hydration finishes) and massive backend server compute costs. CSR pushes the rendering logic to the user's browser; the server just sends a blank HTML file and a massive JS bundle. CSR is cheap to host and provides blazing-fast subsequent page navigation, but has terrible initial load times and poor SEO.", ["SSR: Excellent SEO and instant FCP, but high backend server costs and delayed Time-to-Interactive (Hydration)", "CSR: Cheap to host (CDN) and fast subsequent routing, but terrible initial load (blank screen) and poor SEO", "SSR is ideal for public content (e-commerce); CSR is ideal for gated, highly interactive apps (dashboards)"], ["SSR is used for databases, CSR is used for styling"]),
    ("B60_4_2", "diagnose", "hard", "debugging", ["End-to-End Performance"], "Your SPA's 'Dashboard' page takes 6 seconds to load. You check the Network tab and see 4 API requests: `getUser`, then `getCompany(userId)`, then `getInvoices(companyId)`, then `getInvoiceDetails(invoiceId)`. Each takes 1.5 seconds. How do you re-architect this to load in 1.5 seconds?", "This is a catastrophic 'Network Waterfall'. The frontend is making sequential API calls where each request is blocked waiting for the previous one to finish. To fix this end-to-end, you must shift the orchestration to the backend. You create a dedicated 'Backend-For-Frontend' (BFF) endpoint (e.g., `GET /dashboard-data`) or use a GraphQL query. The frontend makes exactly one HTTP request (taking 1.5 seconds total over the WAN). The backend executes the 4 sequential queries internally over the ultra-fast local LAN/Database connection (taking milliseconds), stitching the data together and returning a single payload.", ["Sequential Network Waterfall: Frontend API calls are blocking each other over a slow WAN", "Shift the orchestration logic from the frontend to the backend", "Create a BFF endpoint or use GraphQL to make a single frontend request, aggregating data quickly on the backend LAN"], ["Tell the user to upgrade their WiFi router"]),
    ("B60_4_3", "implement", "hard", "implement", ["End-to-End Performance"], "How do you implement 'Edge Caching' with CDN Surrogate Keys to instantly purge millions of cached product pages when a single price changes in the backend database?", "Standard URL-based CDN purging requires you to manually purge every URL that contains the product (e.g., the product page, category page, search results), which is impossible to track. You must implement 'Surrogate Keys' (Cache Tags). When the backend renders the HTML or JSON, it adds a header like `Surrogate-Key: product_123`. The CDN reads this header and tags the cached pages. When the price changes in the DB, the backend fires a single API call to the CDN: `PURGE /tag/product_123`. The CDN instantly drops every single URL across the globe that contains that tag, guaranteeing perfect end-to-end cache invalidation.", ["Standard URL purging cannot track all pages displaying a specific database item", "Backend injects `Surrogate-Key` (Cache Tags) headers into the response", "Backend triggers a single CDN purge by Tag, instantly dropping all globally cached pages referencing that ID"], ["You log into the CDN dashboard and click 'Clear All Cache' manually"]),
    ("B60_4_4", "tradeoff", "medium", "tradeoff", ["End-to-End Performance"], "What is the tradeoff of relying entirely on Frontend code-splitting (Lazy Loading) to improve Core Web Vitals?", "Frontend code-splitting (e.g., `React.lazy`) breaks a massive 5MB JavaScript bundle into smaller chunks, drastically improving the initial load time (Largest Contentful Paint) because the browser only downloads the code needed for the landing page. The tradeoff is 'Interaction Delay' and layout shifts. When the user clicks a button to open a Modal, the browser must suddenly freeze, make an HTTP request to download the Modal's JS chunk, parse it, and render it. This causes a noticeable delay in the UI. You must carefully balance splitting to optimize initial load without ruining the interactive experience.", ["Drastically improves initial load (LCP) by minimizing the upfront JS payload", "Tradeoff: Causes noticeable Interaction Delay when navigating, as the browser must fetch the split chunks on-the-fly", "Requires careful pre-fetching (e.g., hovering over a button triggers the chunk download) to mitigate"], ["Code splitting means breaking the server rack in half"]),
    ("B60_4_5", "scenario", "hard", "scenario", ["End-to-End Performance"], "A user uploads a 5GB video file on your frontend. The HTTP POST goes through your API Gateway, into your Node.js backend, which then uploads it to an S3 bucket. The backend crashes with an Out-of-Memory (OOM) error. How do you re-architect this flow?", "You must NEVER proxy massive file uploads through a backend application server. The Node.js server buffers the 5GB file in RAM, instantly causing an OOM crash and blocking the event loop. You must architect a 'Pre-Signed URL' flow. 1) The frontend sends a tiny JSON request to the backend: `{'file': 'video.mp4'}`. 2) The backend authenticates the user and generates a temporary, cryptographically signed AWS S3 URL. 3) The backend returns this URL to the frontend. 4) The frontend uploads the 5GB file *directly* from the browser to S3, completely bypassing the backend server.", ["Never proxy massive file uploads through backend RAM (causes OOM and blocks event loops)", "Backend authenticates the user and generates a temporary Pre-Signed S3 URL", "Frontend uploads the file directly to the S3 bucket, bypassing the backend entirely"], ["Compress the 5GB video into a zip file on the backend"]),
    ("B60_4_6", "explain", "medium", "explain", ["End-to-End Performance"], "Explain the concept of 'Backpressure' in a full-stack data streaming pipeline.", "Backpressure is a flow-control mechanism. Imagine a backend server streaming millions of rows of CSV data to a frontend table. If the backend pushes the data faster than the browser's JavaScript engine can parse and render it, the browser's memory buffer fills up and the tab crashes. Backpressure allows the slow consumer (the browser) to signal the fast producer (the backend) to pause. In WebSockets or TCP, this is handled automatically via window sizing; in application logic, the frontend must explicitly request data in chunks, forcing the backend to yield until the frontend is ready.", ["A flow-control mechanism where a slow consumer signals a fast producer to pause data transmission", "Prevents the frontend/consumer's memory buffer from overflowing and crashing the browser tab", "Ensures the system operates exactly at the speed of the slowest component"], ["Backpressure is the physical pressure on the server fans"]),
    ("B60_4_7", "concept", "easy", "concept", ["End-to-End Performance"], "What is the 'N+1 Query Problem' and how does it impact frontend latency?", "The N+1 problem occurs when an API fetches a list of items (1 query), and then iterates through that list, executing a separate database query for each item to fetch its relationships (N queries). For example, fetching 100 blog posts, then running 100 separate queries to fetch the author for each post. This causes 101 total database round-trips, creating massive backend latency. The frontend user experiences a terrible loading delay. The backend must fix this by using SQL `JOIN`s or an ORM DataLoader to fetch everything in exactly 2 queries.", ["Executes 1 query to get a list, and N subsequent queries to get relationships (e.g., 100 items = 101 queries)", "Causes massive backend latency due to excessive database round-trips", "Fixed using SQL JOINs or DataLoaders (batching the relationship queries)"], ["It is when the frontend has to press next page N+1 times"]),
    ("B60_4_8", "diagnose", "medium", "debugging", ["End-to-End Performance"], "Your React Native app makes an API call to your backend. On Wi-Fi, it takes 50ms. On a 3G mobile network, the exact same API call takes 2 seconds. The payload is only 1KB of JSON. What is dominating the latency, and how do you fix it?", "This is Connection Overhead (TCP Handshake + TLS Negotiation). On high-latency mobile networks, the actual data transmission (1KB) is instantaneous, but establishing the secure connection requires 3-4 round trips. At 300ms latency per trip on 3G, the handshake alone takes 1.2 seconds. To fix this, you must implement 'HTTP Keep-Alive' (Connection Pooling) on the client and server. This keeps the TCP/TLS connection open after the first request, reducing all subsequent API calls on that 3G network to a single round-trip (300ms).", ["Dominated by TCP/TLS Handshake round-trips over a high-latency mobile network", "The 1KB payload transfer is fast, but establishing the connection takes seconds", "Fix by enabling HTTP Keep-Alive (Connection Pooling) to reuse the secure connection"], ["The JSON payload is too heavy for the 3G network"]),
    ("B60_4_9", "architecture", "hard", "architecture", ["End-to-End Performance"], "How do you architect a system to handle a massive spike in frontend read traffic (e.g., a Super Bowl ad driving 1,000,000 users to a product page) without crashing the relational database?", "A relational database (PostgreSQL) will instantly crash under 1,000,000 concurrent reads. You must architect a multi-tiered caching strategy. Tier 1: CDN Edge Caching. Serve the static HTML/JSON directly from Cloudflare, absorbing 99% of the traffic globally. Tier 2: API Gateway Cache. For dynamic requests that bypass the CDN, cache the responses at the API Gateway (e.g., Redis). Tier 3: Database Read Replicas. If the cache misses, route the queries to horizontal Read Replicas, never the primary Write node. Finally, implement a 'Circuit Breaker' to return a stale cache or friendly error if the DB starts failing.", ["Relational DBs cannot survive massive concurrent read spikes", "Implement Tier 1: Global CDN Edge Caching to absorb 99% of traffic", "Implement Tier 2/3: Redis In-Memory caching and Database Read Replicas for cache misses"], ["Buy a bigger database server from AWS"]),
    ("B60_4_10", "tradeoff", "hard", "tradeoff", ["End-to-End Performance"], "What is the tradeoff of using GraphQL versus a traditional REST API for a Full Stack application?", "GraphQL solves the 'Over-fetching' problem. The frontend specifies exactly which fields it needs, saving massive mobile bandwidth, and solves the 'Network Waterfall' by aggregating relational data in a single request. The severe tradeoff is Backend Performance and Security. Because the frontend dynamically defines the query, a malicious or buggy frontend can request an infinitely deeply nested query (User -> Posts -> Comments -> User -> Posts), instantly causing a Denial of Service (OOM/CPU crash) on the backend database. You must implement strict Query Depth Limiting and Complexity Scoring on the GraphQL server.", ["GraphQL solves over-fetching and network waterfalls by allowing frontend-defined queries", "Tradeoff: Shifts the performance/security risk to the backend", "Malicious or nested queries can cause backend DoS, requiring strict Depth/Complexity limiters"], ["GraphQL is written in graph paper, REST is written in text"]),

    # Group 5: Backend for Frontend (BFF) & API Gateway
    ("B60_5_1", "concept", "medium", "concept", ["System Architecture"], "What is a 'Backend-for-Frontend' (BFF) architecture?", "A BFF is a dedicated microservice created specifically for one type of client interface (e.g., a Mobile BFF, a Web SPA BFF, a Smartwatch BFF). Instead of forcing the mobile app to make 10 complex API calls to 10 different generic microservices and parse massive XML payloads, the Mobile BFF handles the orchestration. It makes the 10 internal calls over the fast LAN, strips out useless data, formats it perfectly for the mobile screen, and returns a single, lightweight JSON payload to the phone.", ["A dedicated orchestration layer tailored to a specific client interface (Mobile, Web, Watch)", "Prevents the frontend from making complex, chatty requests to multiple microservices", "Aggregates, trims, and formats data into a single, optimized payload for that specific client"], ["It is an API that is best friends forever with the frontend"]),
    ("B60_5_2", "diagnose", "hard", "debugging", ["System Architecture"], "Your SPA makes requests to an API Gateway, which routes them to 5 microservices. The UI randomly hangs for 30 seconds before showing a 504 Gateway Timeout. You check the 5 microservices; 4 are healthy, but the 'Recommendations' service is completely dead. Why did the entire UI hang instead of just missing the recommendations?", "The API Gateway or BFF was architected synchronously and lacks 'Partial Failure' handling. When the Gateway queried the 5 microservices, it used `await Promise.all()`. Because the Recommendations service died without returning an error (it just hung), the Gateway waited the full 30-second TCP timeout. To fix this, you must implement a 'Circuit Breaker' and a strict timeout (e.g., 500ms) on the Gateway's call to the Recommendations service. If it fails, the Gateway must catch it, inject a default/empty array, and instantly return the healthy data from the other 4 services to the UI.", ["Synchronous orchestration (e.g., `Promise.all()`) causes the entire request to hang if one service dies", "Lack of timeouts and Circuit Breakers allows a non-critical service to take down the critical UI", "Gateway must enforce strict internal timeouts and return 'Partial Data' to the frontend gracefully"], ["The UI was feeling tired"]),
    ("B60_5_3", "implement", "medium", "implement", ["System Architecture"], "How do you implement 'Rate Limiting' at the API Gateway level to prevent a malicious user from brute-forcing a login endpoint?", "You implement a 'Token Bucket' or 'Sliding Window' algorithm in the API Gateway, backed by a fast, centralized Key-Value store like Redis. When a POST request hits `/login`, the Gateway hashes the user's IP address (or API Key) and checks Redis. If the count is < 5 within the last minute, it increments the Redis counter and allows the request to pass to the backend. If the count is > 5, the Gateway instantly drops the request and returns an `HTTP 429 Too Many Requests`, completely shielding the backend authentication microservice from the brute-force traffic.", ["Use a Token Bucket/Sliding Window algorithm in the API Gateway backed by Redis", "Track requests per IP or API Key within a time window", "If the threshold is exceeded, the Gateway returns HTTP 429, shielding the backend compute"], ["You ask the user to type slower"]),
    ("B60_5_4", "tradeoff", "hard", "tradeoff", ["System Architecture"], "What is the tradeoff of using 'Schema Stitching' (or Apollo Federation) in a GraphQL API Gateway?", "Schema Stitching allows you to maintain independent microservices (Users, Products, Reviews), each with their own local GraphQL schema. The API Gateway automatically combines them into one massive, unified 'Supergraph'. The frontend can query across domains seamlessly in one request. The severe tradeoff is immense operational complexity and 'N+1 Routing'. If a frontend query spans 3 domains, the Gateway must intelligently parse the AST, break the query apart, route sub-queries to the 3 services, wait for them, and manually stitch the JSON back together. This adds significant CPU latency at the Gateway layer and makes debugging deeply nested errors a nightmare.", ["Federation combines independent microservice schemas into a single unified Supergraph", "Allows seamless frontend querying across domains", "Tradeoff: Adds massive CPU latency at the Gateway due to AST parsing, routing, and JSON stitching"], ["It requires a literal needle and thread to deploy"]),
    ("B60_5_5", "scenario", "medium", "scenario", ["System Architecture"], "You are migrating a massive Django Monolith to Microservices. You cannot rewrite the frontend SPA all at once. How do you architect the deployment so the frontend doesn't break during the 6-month migration?", "You must implement the 'Strangler Fig Pattern' using an API Gateway (Reverse Proxy). You place Nginx or an API Gateway between the Frontend and the Backend. Initially, the Gateway routes 100% of API calls (e.g., `/*`) to the old Django Monolith. As you extract the 'Billing' service into a new Go microservice, you update the Gateway routing rules: `/api/billing/*` routes to the new Go service, while everything else still routes to Django. The frontend is completely unaware of the backend architectural shift, allowing a safe, incremental migration with zero UI downtime.", ["Implement the Strangler Fig Pattern using an API Gateway / Reverse Proxy", "Route specific extracted endpoints (e.g., `/billing`) to the new microservices", "Default all other traffic to the legacy Monolith; the frontend remains completely ignorant of the backend changes"], ["Just turn the server off for 6 months"]),
    ("B60_5_6", "explain", "medium", "explain", ["System Architecture"], "Explain the difference between an 'API Gateway' and a 'Load Balancer'.", "A Load Balancer operates primarily at Layer 4 (TCP). Its only job is to blindly distribute incoming network traffic across a fleet of identical servers (e.g., Round Robin) to prevent one server from crashing. An API Gateway operates at Layer 7 (HTTP). It is 'Application Aware'. It inspects the actual JSON payloads, headers, and URLs. It performs complex routing (sending `/users` to Service A and `/orders` to Service B), validates JWT tokens, strips CORS headers, and enforces Rate Limiting, acting as the intelligent bouncer for the microservice architecture.", ["Load Balancer (Layer 4): Blindly distributes raw network traffic across identical servers", "API Gateway (Layer 7): Application-aware; inspects URLs, headers, and payloads", "Gateway performs intelligent routing, Auth validation, Rate Limiting, and CORS management"], ["An API Gateway is a physical door, a load balancer is a scale"]),

    # Group 6: Resiliency & Partial Failures
    ("B60_6_1", "concept", "medium", "concept", ["Resilience & Error Handling"], "What is a 'Circuit Breaker' pattern, and how does it protect a Full Stack system?", "When a backend service (e.g., the Payment API) goes down, the frontend or API Gateway will keep sending it requests. Each request hangs until it times out, exhausting all available threads/memory on the caller, causing a cascading failure that takes down the entire application. A Circuit Breaker monitors the error rate. If it detects 5 consecutive failures, the circuit 'trips' (opens). For the next 30 seconds, the Gateway instantly rejects all requests to the Payment API (returning a fast 503 error or fallback UI) without actually attempting the network call, allowing the broken service time to recover.", ["Prevents cascading failures when a downstream service is down/hanging", "Monitors error rates; trips 'open' if thresholds are exceeded", "Instantly rejects calls to save threads/memory, allowing the broken service time to recover"], ["It is a literal fuse box in the server room"]),
    ("B60_6_2", "diagnose", "hard", "debugging", ["Resilience & Error Handling"], "Your frontend SPA is configured to automatically retry failed API requests up to 3 times. The backend Database experiences a minor 5-second CPU spike, causing a few API requests to timeout. Suddenly, the entire Database crashes completely. What architectural flaw in your retry logic caused this?", "This is a 'Retry Storm' (Thundering Herd). Because the frontend encountered a timeout, it immediately retried the request. Thousands of active clients all experienced the 5-second timeout and immediately fired 3x the normal traffic volume at the backend exactly at the same time. The struggling database was instantly overwhelmed by the tidal wave of retries and crashed. To fix this, frontend retries MUST implement 'Exponential Backoff' (wait 1s, then 2s, then 4s) AND 'Jitter' (add a random millisecond delay). Jitter desynchronizes the retries, preventing the traffic wave from hitting the DB at the exact same millisecond.", ["Retry Storm: Immediate frontend retries amplified the traffic, crushing a struggling backend", "Thousands of clients synchronized their retries precisely due to the timeout", "Fix: Frontend MUST implement Exponential Backoff and Jitter (randomization) to spread out retry traffic"], ["The database was scared of the frontend"]),
    ("B60_6_3", "implement", "hard", "implement", ["Resilience & Error Handling"], "How do you implement 'Idempotency' across the Frontend, API, and Database to safely handle network timeouts during a payment transaction?", "If the frontend sends a `POST /charge`, the backend charges the card and commits to the DB, but the network drops before the 200 OK reaches the frontend. The frontend sees a timeout and retries, double-charging the user. To implement Idempotency: 1) The frontend generates a unique UUID (Idempotency-Key) when the checkout page loads. 2) It attaches this key to the POST headers. 3) The backend checks the DB/Redis for this key. If it doesn't exist, it processes the charge and saves the Key + the JSON response. 4) If the frontend retries, the backend sees the Key exists, skips the credit card charge, and simply returns the saved 200 OK JSON.", ["Frontend generates a unique UUID (Idempotency-Key) per transaction intent", "Backend checks a persistent store for the key before processing", "If the key exists, the backend skips the mutation and returns the cached successful response, preventing double-charges"], ["You make the user type their password twice"]),
    ("B60_6_4", "tradeoff", "medium", "tradeoff", ["Resilience & Error Handling"], "What is the tradeoff of designing a frontend UI to be 'Offline-First' (e.g., using IndexedDB and Service Workers) versus requiring a persistent network connection?", "Offline-First provides incredible resiliency. If the user is on a subway, they can still navigate the app, create records (saved locally to IndexedDB), and experience zero UI blocking. When the network returns, the Service Worker syncs the queue to the backend. The severe tradeoff is massive complexity in Conflict Resolution. If the user edits a document offline, and a colleague edits the same document online, the backend must merge the conflicting states when the offline user reconnects. It also requires heavy client-side storage management and complex background sync logic.", ["Offline-First provides extreme resiliency and zero-latency UX by reading/writing to local IndexedDB", "Tradeoff: Massive engineering complexity to handle data sync and Conflict Resolution upon reconnection", "Tradeoff: Requires complex Service Worker lifecycle management and client storage limits"], ["Offline first means you turn off the server first"]),
    ("B60_6_5", "scenario", "medium", "scenario", ["Resilience & Error Handling"], "You are building a Netflix-style UI. The page displays the Movie Video, a list of 'Similar Movies', and a 'User Comments' section. The 'User Comments' microservice goes down. How do you architect the frontend/backend contract to ensure the user can still watch the movie?", "You must architect the system for 'Graceful Degradation'. The Backend BFF (or API Gateway) must NOT treat the 3 microservices as a single synchronous dependency. It should use `Promise.allSettled()` (not `Promise.all()`). If the Comments service times out, the BFF catches the error, sets `comments: []`, and returns a 200 OK with the Video and Similar Movies data, plus an error flag `comments_failed: true`. The Frontend reads this flag, renders the Video perfectly, and displays a friendly 'Comments temporarily unavailable' UI block instead of a blank white screen of death.", ["Use `Promise.allSettled()` in the backend orchestration, not `Promise.all()`", "Catch individual microservice failures and inject default/empty data arrays", "Frontend detects partial failure flags and renders Fallback UI blocks, preserving the core user experience"], ["Just delete the comments section from the codebase"]),
    ("B60_6_6", "explain", "medium", "explain", ["Resilience & Error Handling"], "Explain what a 'Dead Letter Queue' (DLQ) is in a Full Stack event-driven architecture.", "In an event-driven system, the frontend might trigger an event (e.g., 'User Registered') that is placed on a Message Queue (Kafka/RabbitMQ) for a background worker to send a Welcome Email. If the email API is down, or the JSON payload is malformed, the worker fails. If the worker just drops the message, data is permanently lost. If it loops infinitely, it blocks the queue. A Dead Letter Queue is a secondary queue. After a message fails N retries, the worker moves it to the DLQ. Engineers can inspect the DLQ, fix the bug, and replay the exact messages without data loss.", ["A secondary storage queue for messages that repeatedly fail processing in an asynchronous pipeline", "Prevents infinite retry loops (blocking the main queue) and prevents silent data loss", "Allows engineers to manually inspect, debug, and replay the failed events once the bug is fixed"], ["It is a mailbox for letters that were lost in the mail"])
]

def run_batch():
    with open(OUT, "a", encoding="utf-8") as f:
        for q in Q:
            rec = {
                "primary_role": ROLE,
                "applicable_roles": ["Frontend Developer", "Backend Developer"],
                "primary_skill": q[4][0],
                "secondary_skills": q[4][1:] if len(q[4]) > 1 else [],
                "technology": "Full Stack",
                "topic": q[4][0] if len(q[4]) > 0 else "General",
                "category": "Software Engineering",
                "intent": q[1],
                "difficulty": q[2],
                "question_type": q[3],
                "question": q[5],
                "expected_answer": q[6],
                "evaluation_rubric": {
                    "strong_indicators": q[7],
                    "weak_indicators": q[8]
                },
                "id": str(uuid.uuid4()),
                "source": "Antigravity_Internal_Knowledge",
                "provenance_type": "researched_generated",
                "dataset_version": "v2",
                "status": "active"
            }
            f.write(json.dumps(rec) + "\n")
            
    print(f"Appended {len(Q)} questions (Batch 60 Part 2).")

if __name__ == "__main__":
    run_batch()
