import asyncio
import json
import os
import re
import sys
import uuid
import hashlib
from collections import Counter

from dotenv import load_dotenv
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
load_dotenv()

BACKEND_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_DIR = os.path.join(BACKEND_DIR, "data")
OUT = os.path.join(DATA_DIR, "interview_question_bank_v2_generated.jsonl")

ROLE = "Full Stack Developer"
LEAK = re.compile(r"(generate a question|generate \d+ questions|return only json|phase 4c gap plan|"
                  r"generation batch|candidate generation|system instructions|do not proceed|"
                  r"awaiting authorization|minimum target|generation pipeline|"
                  r"batch \d+ generation|expected answer|strong indicator|weak indicator|as an ai|"
                  r"here is the question|\bprompt text\b)", re.I)

Q = [
    # Group 7: Multi-Tenancy & B2B
    ("B60_7_1", "concept", "medium", "concept", ["System Architecture"], "What is the difference between a 'Shared Database, Shared Schema' and a 'Database-per-Tenant' architecture in a B2B SaaS application?", "In a 'Shared DB, Shared Schema' architecture, all customers (tenants) live in the exact same SQL tables. Every single row has a `tenant_id` column. It is incredibly cheap to host and easy to run global analytics, but highly risky; a single forgotten `WHERE tenant_id = ?` clause in a backend query instantly leaks Customer A's data to Customer B. In a 'Database-per-Tenant' architecture, every customer gets their own physical database. This guarantees absolute data isolation and makes backup/restore for a single customer trivial, but creates an infrastructural nightmare when you need to run schema migrations across 5,000 separate databases.", ["Shared DB: All tenants in one table separated by `tenant_id`. Cheap, but high risk of cross-tenant data leaks", "DB-per-Tenant: Complete physical isolation. Perfect security, but nightmare schema migrations (N databases)", "Shared DB requires strict Row-Level Security (RLS) or rigorous ORM filters to prevent data leakage"], ["Shared DB means sharing passwords, DB per tenant means everyone gets their own password"]),
    ("B60_7_2", "diagnose", "hard", "debugging", ["System Architecture"], "Your multi-tenant SaaS uses subdomains (e.g., `pepsi.myapp.com` and `coke.myapp.com`). A user successfully logs into Pepsi. They manually change the URL to `coke.myapp.com`. The UI loads, and they can see all of Coke's internal data. Why did this happen, and how do you fix it end-to-end?", "This is a catastrophic 'Cross-Tenant Authentication Leak'. When the user logged into `pepsi`, the backend set the authentication cookie domain to the apex `.myapp.com` instead of the strict subdomain `pepsi.myapp.com`. The browser blindly sent the valid session cookie to `coke.myapp.com`. Furthermore, the Backend API lacked Tenant-ID validation. To fix this: 1) The Backend must scope cookies strictly to the subdomain. 2) The Backend API must extract the `tenant_id` from the URL/Host header and explicitly compare it against the `tenant_id` hardcoded inside the user's JWT/Session. If they don't match, return 403 Forbidden.", ["The session cookie was scoped to the apex domain (`.myapp.com`) allowing it to leak across subdomains", "The Backend API blindly trusted the valid session without cross-checking the Tenant Context", "Fix by scoping cookies to the strict subdomain AND enforcing backend DB checks ensuring User ID belongs to the requested Tenant ID"], ["The user hacked the DNS server"]),
    ("B60_7_3", "implement", "hard", "implement", ["System Architecture"], "How do you implement B2B Single Sign-On (SAML/OIDC) so that when an enterprise employee is fired, they are instantly locked out of your SaaS application?", "You cannot rely on the enterprise IT admin to manually log into your SaaS app and click 'Delete User'. You must implement SCIM (System for Cross-domain Identity Management) alongside SAML. SCIM creates an automated API bridge between the enterprise Identity Provider (like Okta/Active Directory) and your Backend. When the employee is terminated in Active Directory, Okta instantly fires a SCIM HTTP DELETE webhook to your Backend. Your backend immediately revokes the user's sessions and JWTs, instantly locking them out of the frontend SPA without human intervention.", ["SAML only handles login (AuthN); it does not handle automated provisioning/deprovisioning", "Must implement SCIM (System for Cross-domain Identity Management)", "SCIM allows the enterprise Identity Provider (Okta) to send automated API webhooks to your backend to instantly delete users"], ["You call their boss and ask if they still work there"]),
    ("B60_7_4", "tradeoff", "medium", "tradeoff", ["System Architecture"], "What is the architectural tradeoff of using Row-Level Security (RLS) in PostgreSQL to enforce multi-tenancy versus enforcing it strictly in the Application Code (ORM)?", "Enforcing multi-tenancy in the Application Code (e.g., appending `.where(tenantId=X)` to every ORM call) is highly visible to developers and database-agnostic. The severe tradeoff is human error; a junior developer forgetting the `.where()` clause once will leak data. PostgreSQL RLS pushes the security directly into the database engine. You define a policy (`tenant_id = current_setting('app.current_tenant')`). If the app code forgets the where clause, the DB engine actively blocks it. The tradeoff is that RLS adds a slight performance overhead on every query, is difficult to debug, and requires managing Postgres-specific session variables.", ["Application Code (ORM): Highly visible and DB-agnostic, but relies entirely on developers never making a mistake", "PostgreSQL RLS: Pushes security to the DB engine; mathematically prevents leaks even if the backend code is buggy", "Tradeoff: RLS adds query latency, is hard to debug, and tightly couples security to the specific DB vendor"], ["RLS requires you to hire a security guard for the server room"]),
    ("B60_7_5", "scenario", "medium", "scenario", ["System Architecture"], "Your multi-tenant API is healthy. Suddenly, 'Tenant A' runs a massive automated script that sends 10,000 complex search requests per second. 'Tenant A' receives data fine, but 'Tenant B' and 'Tenant C' experience massive timeouts and 500 errors. How do you re-architect to prevent this?", "This is the classic 'Noisy Neighbor' problem in shared architecture. The heavy load from Tenant A exhausted the backend connection pool or Database CPU, crashing the system for everyone. To fix this, you must implement 'Per-Tenant Rate Limiting' at the API Gateway. The Gateway hashes the `tenant_id` and tracks limits in Redis. Tenant A hits their isolated cap (e.g., 500 req/sec) and receives 429 Too Many Requests, while Tenant B and C remain completely unaffected. For absolute isolation, you might move Tenant A to a dedicated physical database/server.", ["The 'Noisy Neighbor' problem: One tenant exhausts shared resources (CPU/Connection Pool), crashing others", "Implement 'Per-Tenant Rate Limiting' at the API Gateway (using Redis)", "Limits the abuser with HTTP 429s while preserving healthy resources for other tenants"], ["Just ban Tenant A and delete their account"]),
    ("B60_7_6", "explain", "medium", "explain", ["System Architecture"], "Explain the concept of 'Tenant Isolation' and why it affects frontend caching strategies.", "Tenant Isolation ensures that data from one customer is never accessible by another. This drastically complicates Frontend and CDN caching. If you cache a JSON response for `GET /api/dashboard` in the browser or CDN, Tenant A might log out, and Tenant B logs in on the same machine. If the cache key is just the URL, Tenant B will instantly see Tenant A's cached dashboard. Caching layers MUST include the `Tenant-ID` or a strict authorization hash in the Cache Key (e.g., `Cache-Key: /api/dashboard|Tenant-123`) to mathematically guarantee isolation.", ["Ensures strict data separation between customers (tenants)", "Blindly caching URLs (e.g., `/dashboard`) will serve Tenant A's data to Tenant B on shared machines/CDNs", "All caching mechanisms (Browser, CDN, Redis) MUST use the `Tenant-ID` as part of the composite Cache Key"], ["It means building separate office buildings for each customer"]),

    # Group 8: End-to-End Testing & Deploy
    ("B60_8_1", "concept", "medium", "concept", ["Deployment & Architecture"], "What is 'Contract Testing', and how does it prevent integration failures between Frontend and Backend teams?", "In large teams, the Backend might rename an API field from `user_name` to `userName`. The backend unit tests pass, but the Frontend crashes in production. End-to-End (E2E) tests catch this, but they are slow and brittle. Contract Testing (using tools like Pact) defines a strict, programmatic JSON schema (the 'Contract') agreed upon by both teams. The Frontend writes tests asserting it can consume the contract. The Backend writes tests asserting it produces the exact contract. If the Backend renames a field, their CI/CD pipeline instantly fails because the generated output violates the shared contract, preventing the broken code from ever merging.", ["A programmatic agreement (JSON schema) defining the exact shape of the API request/response", "Frontend tests ensure it can consume the contract; Backend tests ensure it produces the contract", "Catches integration breaks (renamed fields, changed types) instantly in CI/CD without running slow E2E browser tests"], ["Contract testing is when HR tests your employment contract"]),
    ("B60_8_2", "diagnose", "hard", "debugging", ["Deployment & Architecture"], "You use Cypress for End-to-End (E2E) testing. The test 'User can create a post' passes 80% of the time, but randomly fails 20% of the time in the CI pipeline with a 'Timeout waiting for element' error. The code hasn't changed. Why are the tests 'flaky'?", "Flaky E2E tests are almost always caused by 'Network/State Race Conditions'. The Cypress script clicks 'Submit', and immediately asserts that the 'Success Message' element exists in the DOM. However, the backend API might take 10ms (test passes) or 5000ms (test fails due to timeout). The UI state is unpredictable. To fix this, you must explicitly force Cypress to wait for the network state. You intercept the specific API route (`cy.intercept('/api/posts').as('createPost')`) and instruct the test to strictly wait for that network call to resolve (`cy.wait('@createPost')`) BEFORE asserting the DOM element exists.", ["Flakiness is caused by Race Conditions between the test runner speed and the unpredictable backend API latency", "The test runner looks for a DOM element before the API response has triggered the UI update", "Fix by intercepting the network route and forcing the test runner to wait for the API response explicitly before asserting"], ["Cypress gets tired after running 80% of the time"]),
    ("B60_8_3", "implement", "hard", "implement", ["Deployment & Architecture"], "How do you orchestrate a database schema migration (e.g., renaming a column from `first_name` to `given_name`) in a production environment with Zero Downtime?", "You CANNOT simply run `ALTER TABLE RENAME` and deploy the new backend. During the 5-minute deployment window, the old running servers will query `first_name` (which no longer exists) and crash, causing downtime. You must orchestrate a 3-phase Zero Downtime Migration: Phase 1) Add the new column `given_name` to the DB. Deploy backend code that writes to BOTH columns, but reads from the old one. Phase 2) Run a background script to backfill the data from the old column to the new one. Phase 3) Deploy backend code that reads and writes strictly to the new column. Phase 4) Safely delete the old column.", ["Directly renaming/deleting columns causes immediate downtime for actively running legacy servers", "Phase 1: Add new column; deploy backend that dual-writes to both", "Phase 2: Backfill historical data", "Phase 3: Deploy backend that reads/writes only to new column. Phase 4: Drop old column"], ["You take the database offline at 3 AM on a Sunday"]),
    ("B60_8_4", "tradeoff", "medium", "tradeoff", ["Deployment & Architecture"], "What is the tradeoff of using a 'Blue/Green' deployment strategy versus a 'Canary' deployment strategy for a Full Stack application?", "Blue/Green duplicates your entire production infrastructure. You deploy the new code to the 'Green' environment, run tests, and instantly flip the Load Balancer to route 100% of traffic to Green. It allows instant rollback, but requires 2x the server cost and doesn't test the code against real user traffic until the 100% flip. Canary deployment routes 1% of live user traffic to the new code, monitoring errors. If stable, it scales to 10%, then 100%. Canary is vastly safer for finding obscure real-world bugs, but is extremely complex to orchestrate (requires intelligent load balancers) and makes database schema changes very difficult (both versions must share the DB simultaneously).", ["Blue/Green: 100% traffic flip to a duplicate environment. Instant rollback, but high cost and untested by live users until flip", "Canary: Gradual 1% -> 100% rollout to live users. Safest for finding edge cases", "Tradeoff: Canary requires complex routing and makes breaking DB schema changes incredibly difficult to manage simultaneously"], ["Blue green means the UI colors change, Canary means the UI plays bird sounds"]),
    ("B60_8_5", "scenario", "medium", "scenario", ["Deployment & Architecture"], "Your SPA (Single Page Application) is hosted on an S3/Cloudfront CDN. You deploy a new version with critical bug fixes. Users complain they still see the buggy version. You cleared the CDN cache, but they still see the bug. Why?", "The user's local browser heavily cached the old `main.js` and `index.html` files. Even though the CDN has the new files, the browser doesn't ask the network for them. To fix this end-to-end, you must implement 'Asset Fingerprinting' (Cache Busting) in your build tool (Webpack/Vite). The build tool appends a unique hash to the JS file (`main.[hash].js`). You must configure the CDN to serve `index.html` with strict headers (`Cache-Control: no-cache`). The browser is forced to download the new `index.html`, which references the brand new hashed JS filename, bypassing the local browser cache instantly.", ["The local browser cache trapped the old JavaScript files, ignoring the CDN purge", "Must configure `index.html` to NEVER cache (`Cache-Control: no-cache`)", "Must use Webpack/Vite Asset Fingerprinting (`main.[hash].js`) so the new HTML requests a totally unique filename"], ["The users are lying to you"]),
    ("B60_8_6", "explain", "medium", "explain", ["Deployment & Architecture"], "Explain the concept of 'Feature Flags' (Feature Toggles) and how they decouple Deployment from Release.", "Historically, deploying code to production immediately exposed that code to users (Deployment = Release). Feature Flags are conditional logic blocks (`if (flags.newCheckout) { renderNew() } else { renderOld() }`) backed by a remote configuration service (like LaunchDarkly). You can deploy the new checkout code to production, but keep the flag 'Off'. The code is in production, but completely hidden (Deployment without Release). Product managers can then flip the flag 'On' for 5% of users to test it. If it crashes, they flip it 'Off' in milliseconds without requiring a 20-minute CI/CD engineering rollback.", ["Feature Flags decouple Code Deployment (moving code to servers) from Feature Release (exposing code to users)", "Allows code to be safely deployed but hidden behind a remote-controlled boolean toggle", "Enables instant millisecond rollbacks and targeted user testing without requiring a CI/CD pipeline run"], ["A feature flag is a literal flag you plant on top of the server rack"]),

    # Group 9: Full Stack Security
    ("B60_9_1", "diagnose", "hard", "debugging", ["Application Security"], "Your backend API is configured with `Access-Control-Allow-Origin: *`. A security auditor flags this as a critical vulnerability. The junior developer argues that since the API doesn't use cookies (it uses a Bearer token in the header), CSRF is impossible, so `*` is perfectly safe. Is the junior developer correct?", "The junior developer is wrong. While Bearer tokens prevent traditional CSRF, `Access-Control-Allow-Origin: *` introduces a massive data exfiltration vulnerability if combined with an Intranet/VPN setup. If an employee is on the corporate VPN, they can access internal APIs (e.g., `http://internal-hr-api`). If they visit `malicious.com`, the malicious JS can execute a fetch to `http://internal-hr-api`. Because the API responds with `*`, the browser allows `malicious.com` to read the highly sensitive HTTP response and exfiltrate the data. You must always restrict CORS origins to trusted domains.", ["CORS `*` allows any malicious website to read the HTTP response if they can hit the API", "Highly dangerous for APIs hosted on internal networks or VPNs (SSRF-style exfiltration)", "Even without cookies, malicious JS can read sensitive data and exfiltrate it; always restrict Origins"], ["The junior developer is correct, security auditors just want to cause trouble"]),
    ("B60_9_2", "implement", "medium", "implement", ["Application Security"], "How do you securely implement file uploads from a Frontend SPA to an AWS S3 bucket without exposing AWS API Keys to the browser or overloading the backend?", "You must implement the 'Pre-Signed URL' pattern. 1) The Frontend sends a tiny request to the Backend (`POST /upload-intent` with the filename/size). 2) The Backend authenticates the user, validates the file type, and uses its secure AWS IAM credentials to generate a temporary, cryptographically signed URL restricted to a specific S3 path and a 5-minute expiry. 3) The Backend returns this Pre-Signed URL. 4) The Frontend executes a `PUT` request directly to S3 using that URL. This keeps AWS keys completely off the frontend and keeps massive file payloads completely off the backend servers.", ["Frontend requests a temporary upload URL from the Backend", "Backend uses secure AWS credentials to generate a time-limited Pre-Signed S3 URL", "Frontend uploads the massive file directly to S3, bypassing backend compute and protecting AWS keys"], ["You hardcode the AWS keys in the React code but use base64 encoding to hide them"]),
    ("B60_9_3", "architecture", "hard", "architecture", ["Application Security"], "How do you architect a system to prevent 'Server-Side Request Forgery' (SSRF) when your application allows users to submit a URL (e.g., a webhook or profile image) that the backend must fetch?", "If a user submits `http://localhost/admin/delete-db` or `http://169.254.169.254/latest/meta-data/` (AWS Metadata endpoint), the backend will blindly execute the HTTP request, exposing internal services or cloud credentials. To prevent SSRF, you must architect a strict 'Network Boundary/Sandbox'. 1) Use an explicit Allowlist of domains (if possible). 2) Resolve the DNS of the provided URL and strictly block any IP addresses in the private/loopback ranges (127.0.0.1, 10.x, 192.168.x). 3) Best practice: Execute the URL fetching in an isolated, egress-only serverless function (Lambda) that has absolutely zero network routing access to your internal VPC/databases.", ["SSRF occurs when a backend is tricked into fetching internal/malicious URLs (e.g., AWS Metadata, localhost)", "Must perform DNS resolution and block all private, loopback, and cloud metadata IP ranges", "Architecturally isolate the fetcher (e.g., run it in a Sandbox/Lambda with no internal VPC access)"], ["You just ask the user nicely not to type localhost"]),
    ("B60_9_4", "tradeoff", "medium", "tradeoff", ["Application Security"], "What is the tradeoff of relying entirely on a Web Application Firewall (WAF) to prevent SQL Injection versus parameterizing queries in the application code?", "A WAF analyzes incoming HTTP traffic and blocks payloads that look like SQL injection (e.g., `OR 1=1`). It requires zero code changes and provides immediate blanket protection. The severe tradeoff is that WAFs rely on regex/heuristics; they suffer from False Positives (blocking legitimate users with weird names) and False Negatives (sophisticated attackers easily bypass regex rules using encoding/obfuscation). Parameterized queries (prepared statements) in the application code guarantee 100% mathematical immunity to SQLi by separating the SQL syntax from the data payload, but require disciplined coding standards across the entire engineering team.", ["WAF provides instant, code-free protection but uses heuristics (vulnerable to obfuscation bypasses and false positives)", "Parameterized Queries mathematically guarantee SQLi immunity by separating syntax from data", "Tradeoff: Parameterization requires disciplined code refactoring, while WAF acts as an unreliable band-aid"], ["WAFs require a literal wall of fire in the data center"])
]

def run_batch():
    # Write directly to file
    with open(OUT, "a", encoding="utf-8") as f:
        for q in Q:
            rec = {
                "primary_role": ROLE,
                "applicable_roles": ["Frontend Developer", "Backend Developer"],
                "primary_skill": q[4][0],
                "secondary_skills": q[4][1:] if len(q[4]) > 1 else [],
                "technology": "Full Stack",
                "topic": q[4][0] if len(q[4]) > 0 else "General",
                "category": "Software Engineering",
                "intent": q[1],
                "difficulty": q[2],
                "question_type": q[3],
                "question": q[5],
                "expected_answer": q[6],
                "evaluation_rubric": {
                    "strong_indicators": q[7],
                    "weak_indicators": q[8]
                },
                "id": str(uuid.uuid4()),
                "source": "Antigravity_Internal_Knowledge",
                "provenance_type": "researched_generated",
                "dataset_version": "v2",
                "status": "active"
            }
            f.write(json.dumps(rec) + "\n")
            
    print(f"Appended {len(Q)} questions (Batch 60 Part 3).")

if __name__ == "__main__":
    run_batch()
