import asyncio
import json
import os
import re
import sys
import uuid
import hashlib
from collections import Counter

from dotenv import load_dotenv
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
load_dotenv()

BACKEND_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_DIR = os.path.join(BACKEND_DIR, "data")
OUT = os.path.join(DATA_DIR, "interview_question_bank_v2_generated.jsonl")

ROLE = "Java Developer"
LEAK = re.compile(r"(generate a question|generate \d+ questions|return only json|phase 4c gap plan|"
                  r"generation batch|candidate generation|system prompts|do not proceed|"
                  r"awaiting authorization|minimum target|generation pipeline|"
                  r"batch \d+ generation|expected answer|strong indicator|weak indicator|as an ai|"
                  r"here is the question|\bprompt text\b)", re.I)

Q = [
    # Area 1: Spring Boot Internals & Transactions
    ("B55_1", "diagnose", "medium", "debugging", ["Spring Framework"], "A developer annotates a method with `@Transactional`. Inside the same class, they call this method from another non-transactional method. The transaction fails to start, and database changes are not rolled back on exception. Why?", "Spring handles `@Transactional` using AOP (Aspect-Oriented Programming) proxies. When a method is called from *outside* the bean, the call goes through the Spring proxy, which starts the transaction. However, when a method calls another method *within the same class* (self-invocation), it calls the method on the `this` reference directly, completely bypassing the Spring proxy. Therefore, the `@Transactional` interceptor never fires. The fix is to inject the class into itself (self-injection) or move the transactional method to a different service.", ["Self-invocation bypasses the Spring AOP proxy", "Method is called on `this` rather than through the proxy object", "The `@Transactional` interceptor never executes"], ["Transactions cannot be nested"]),
    ("B55_1", "explain", "hard", "concept", ["Spring Framework"], "Explain the difference between `@Component`, `@Configuration`, and proxying in Spring. What happens if you define a `@Bean` inside a `@Component` versus a `@Configuration`?", "In a `@Configuration` class, Spring uses CGLIB to create a proxy around the class. If you call a `@Bean` method from another `@Bean` method inside the same `@Configuration` class, the proxy intercepts the call and ensures it returns the singleton instance from the Spring context. If you define a `@Bean` inside a `@Component` class (often called 'lite' mode), it is NOT proxied by CGLIB. Calling one `@Bean` method from another in a `@Component` acts like a standard Java method call, returning a brand-new, unmanaged instance instead of the Spring singleton.", ["`@Configuration` creates a CGLIB proxy; `@Component` does not (lite mode)", "In `@Configuration`, internal `@Bean` calls are intercepted to return the Singleton", "In `@Component`, internal calls return new, unmanaged instances"], ["@Component is for front-end, @Configuration is for backend"]),
    ("B55_1", "architecture", "hard", "architecture", ["Spring Framework"], "How does Spring's `DispatcherServlet` handle an incoming HTTP request and route it to a `@RestController`?", "The `DispatcherServlet` is the front controller. When a request arrives, it consults the `HandlerMapping` (usually `RequestMappingHandlerMapping`) to find the exact Controller method mapped to the URL. It then uses a `HandlerAdapter` to dynamically invoke that method, resolving and injecting the required arguments (like `@PathVariable` or `@RequestBody` via `HttpMessageConverters`). Finally, because it's a `@RestController`, the returned object is serialized to JSON (via Jackson/HttpMessageConverter) and written directly to the `HttpServletResponse` rather than resolving a View.", ["DispatcherServlet acts as the Front Controller", "Consults `HandlerMapping` to find the method and `HandlerAdapter` to invoke it", "Uses `HttpMessageConverters` to deserialize requests and serialize JSON responses"], ["It uses a giant switch statement on the URL"]),
    ("B55_1", "tradeoff", "medium", "tradeoff", ["Spring Framework"], "What is the tradeoff of using Field Injection (`@Autowired` on private fields) versus Constructor Injection in Spring?", "Field injection requires the least boilerplate but introduces severe architectural flaws: you cannot instantiate the class in a unit test without bringing up the entire Spring Context (or using reflection), and the fields cannot be marked `final`, risking mutation. Constructor injection enforces strict dependency declaration, allows the fields to be `final` (immutable), and allows the class to be instantiated cleanly in unit tests using standard `new MyService(mockRepo)` without Spring. Spring officially recommends Constructor Injection.", ["Field injection hides dependencies and breaks simple unit testing", "Constructor injection allows fields to be `final` (immutable)", "Constructor injection allows instantiation without the Spring IoC container"], ["Field injection makes the database slower"]),
    ("B55_1", "scenario", "medium", "scenario", ["Spring Framework"], "You have a `@Transactional` method that catches an exception using `try { ... } catch (Exception e) { log.error(e); }`. The database changes are still committed even though an error occurred. Why, and how do you force a rollback?", "By default, Spring's `@Transactional` only rolls back on *unchecked* exceptions (`RuntimeException` and `Error`). If you catch the exception and swallow it without re-throwing, the proxy assumes the method completed successfully and commits the transaction. To force a rollback, you must either re-throw the `RuntimeException`, or manually flag the transaction for rollback in the catch block using `TransactionAspectSupport.currentTransactionStatus().setRollbackOnly()`.", ["Spring rolls back automatically only if an unchecked exception is thrown out of the proxy", "Swallowing the exception tells the proxy the method succeeded", "Fix by re-throwing, or manually setting `setRollbackOnly()`"], ["The database connection timed out"]),
    ("B55_1", "concept", "easy", "concept", ["Spring Framework"], "What is the purpose of Spring Boot Auto-Configuration?", "Auto-Configuration (triggered by `@EnableAutoConfiguration` inside `@SpringBootApplication`) attempts to automatically configure your Spring application based on the jar dependencies present on the classpath. For example, if `HSQLDB` is on the classpath and you haven't manually configured any database connection beans, Spring Boot automatically creates an in-memory database and a `DataSource` bean for you, drastically reducing boilerplate.", ["Automatically creates beans based on classpath dependencies", "Reduces boilerplate configuration (e.g., auto-configuring a DataSource)", "Triggered by `@EnableAutoConfiguration`"], ["It automatically writes Java code for you"]),
    ("B55_1", "diagnose", "hard", "debugging", ["Spring Framework"], "You configure a custom `Filter` in Spring Security to intercept requests, but you notice the filter is actually executing twice for every single HTTP request. Why?", "This occurs if you define your custom Filter as a Spring `@Component` AND you manually register it in the Spring Security `SecurityFilterChain`. Spring Boot automatically detects any Filter bean annotated with `@Component` and registers it globally in the default web container filter chain. Then, your security config registers it *again* inside the Spring Security proxy chain. The fix is to remove the `@Component` annotation so it is instantiated only within the security config, or explicitly register a `FilterRegistrationBean` to disable the default mapping.", ["The Filter was annotated with `@Component` AND added to the SecurityFilterChain", "Spring Boot auto-registers `@Component` filters globally", "Resulting in double registration: once in the container, once in the security chain"], ["The user clicked the button twice rapidly"]),
    ("B55_1", "architecture", "medium", "architecture", ["Spring Framework"], "Explain the Spring Bean Lifecycle from instantiation to destruction.", "1. Instantiation: Spring creates the object (usually via constructor). 2. Populate Properties: Spring injects the dependencies (Field/Setter injection). 3. `BeanNameAware` / `ApplicationContextAware`: Interfaces are called to inject context details. 4. `BeanPostProcessor.postProcessBeforeInitialization`: Pre-initialization hooks run. 5. `@PostConstruct` / `InitializingBean.afterPropertiesSet`: Custom initialization logic executes. 6. `BeanPostProcessor.postProcessAfterInitialization`: Proxies (like AOP/Transactional) are wrapped around the bean. 7. Bean is ready for use. 8. Upon shutdown, `@PreDestroy` / `DisposableBean.destroy()` are called.", ["Instantiation -> Dependency Injection", "`BeanPostProcessors` execute before and after initialization (used to generate AOP proxies)", "`@PostConstruct` executes setup logic, `@PreDestroy` executes teardown"], ["It starts, runs, and stops"]),
    ("B55_1", "implement", "medium", "implement", ["Spring Framework"], "How do you define a fallback mechanism in a Spring Boot application if an external REST API times out, using Resilience4j?", "You annotate the method making the REST call with `@CircuitBreaker(name = \"myService\", fallbackMethod = \"fallbackResponse\")`. You then define a method named `fallbackResponse` in the same class, which must have the exact same return type and take the same parameters as the original method, plus a `Throwable` or specific exception as the final parameter. When the circuit breaker trips (or a timeout/exception occurs), Spring routes the call to the fallback method to return a default/cached response.", ["Use `@CircuitBreaker` and specify a `fallbackMethod`", "Fallback method must have identical return type and parameters, plus the Exception", "Returns cached or default data to prevent cascading failures"], ["Use a massive try-catch block returning null"]),
    ("B55_1", "tradeoff", "medium", "tradeoff", ["Spring Framework"], "What is the tradeoff of using `@Lazy` injection in a Spring Boot application?", "Spring beans are eagerly initialized as singletons at startup by default. Using `@Lazy` delays the instantiation of a bean until it is actually requested/used for the first time. The advantage is faster application startup time and resolving circular dependencies by injecting a lazy proxy. The severe tradeoff is that configuration errors, missing dependencies, or crash-inducing bugs in the lazy bean will NOT be discovered at startup; they will crash the application dynamically in production exactly when a user attempts to trigger that specific code path.", ["Speeds up startup time and resolves circular dependencies", "Tradeoff: Delays the discovery of configuration errors/crashes until runtime", "Bugs crash the app in production rather than safely failing at startup"], ["Lazy beans use more CPU"]),

    # Area 2: Project Loom (Virtual Threads) & Structured Concurrency
    ("B55_2", "concept", "hard", "concept", ["Concurrency"], "How do Java 21 Virtual Threads (Project Loom) differ from traditional OS/Platform threads at the operating system level?", "Traditional Java Platform threads have a 1:1 mapping with OS threads, requiring massive memory (e.g., 1MB stack size per thread) and heavy context-switching overhead, limiting servers to a few thousand threads. Virtual Threads have an M:N mapping. Millions of Virtual Threads are multiplexed onto a small pool of Carrier (Platform) threads by the JVM. When a Virtual Thread hits a blocking I/O operation (like an HTTP call), the JVM automatically 'unmounts' it, parks its state on the heap, and reassigns the Carrier thread to run another Virtual Thread, enabling massive concurrency without OS-level overhead.", ["Platform threads map 1:1 to OS threads (heavy memory, context switching)", "Virtual Threads map M:N onto a small pool of Carrier OS threads", "Blocking I/O unmounts the Virtual Thread to the heap, freeing the OS thread"], ["Virtual threads are just asynchronous callbacks hidden by syntax"]),
    ("B55_2", "diagnose", "hard", "debugging", ["Concurrency"], "You upgrade a Spring Boot application to use Java 21 Virtual Threads. Performance drastically improves, but a specific legacy database method causes the entire application to hang under load. Thread dumps show the Carrier threads are blocked. What is 'Pinning'?", "'Pinning' occurs when a Virtual Thread executes a blocking operation but is fundamentally unable to unmount from its Carrier thread. In Java 21, this primarily happens when a Virtual Thread executes blocking I/O while inside a `synchronized` block or while executing a native JNI method. Because the Virtual Thread is 'pinned' to the Carrier thread, the blocking operation halts the underlying OS thread entirely. Under load, all Carrier threads become pinned and the JVM grinds to a halt. The fix is to replace `synchronized` blocks with `ReentrantLock`.", ["Pinning occurs when a Virtual Thread cannot unmount during blocking I/O", "Caused by blocking inside `synchronized` blocks or native JNI methods", "Blocks the underlying Carrier OS thread, leading to thread starvation"], ["Pinning is when you pin a thread to a specific CPU core"]),
    ("B55_2", "tradeoff", "medium", "tradeoff", ["Concurrency"], "What is the architectural tradeoff of using Java Virtual Threads instead of Reactive Programming (like Project Reactor or RxJava)?", "Reactive Programming provides extreme concurrency and backpressure but forces developers to use complex, viral, functional-style callback chains (`Mono`/`Flux`) that are notoriously difficult to debug, stack-trace, and maintain. Virtual Threads allow developers to write simple, imperative, blocking code (like standard loops and try-catch blocks) while achieving the exact same extreme concurrency and scalability. The tradeoff is that Virtual Threads currently lack built-in backpressure primitives, requiring explicit semaphores or queues to prevent overwhelming downstream services.", ["Reactive requires complex, viral functional callback chains (Mono/Flux)", "Virtual Threads allow simple, imperative, blocking-style code with the same performance", "Virtual Threads lack built-in backpressure, unlike Reactive streams"], ["Virtual threads are significantly slower than Reactive streams"]),
    ("B55_2", "implement", "medium", "implement", ["Concurrency"], "How do you create an `ExecutorService` in Java 21 that utilizes Virtual Threads instead of a fixed thread pool?", "Instead of using `Executors.newFixedThreadPool(10)`, you use the factory method introduced in Project Loom: `Executors.newVirtualThreadPerTaskExecutor()`. This executor does not pool threads; it creates a brand new Virtual Thread for every single submitted task, executes it, and discards it, as Virtual Threads are cheap enough to instantiate millions per second.", ["Use `Executors.newVirtualThreadPerTaskExecutor()`", "It creates a new Virtual Thread for every task instead of pooling them", "Virtual Threads are cheap, so pooling is an anti-pattern"], ["Use `new Thread().setVirtual(true)`"]),
    ("B55_2", "architecture", "hard", "architecture", ["Concurrency"], "Explain the concept of 'Structured Concurrency' introduced alongside Project Loom (JEP 453).", "Structured Concurrency ensures that the lifetime of concurrent subtasks is strictly bound to the lexical scope of the code block that spawned them, preventing 'thread leaks' or orphaned background tasks. Using `StructuredTaskScope` in a `try-with-resources` block, the parent thread will automatically wait for all child tasks to finish or fail before exiting the block. If one child task fails, the scope can automatically cancel all sibling subtasks, ensuring clean teardown and highly readable, tree-like concurrent execution.", ["Binds the lifetime of concurrent tasks to a strict lexical scope (try-with-resources)", "Prevents orphaned background threads and resource leaks", "Automatically propagates cancellation to sibling tasks if one fails"], ["It structures the source code into alphabetical folders"]),
    ("B55_2", "scenario", "medium", "scenario", ["Concurrency"], "You are migrating to Virtual Threads and notice your application is throwing `OutOfMemoryError` on the heap. You heavily rely on `ThreadLocal` variables for caching massive objects. Why is this a problem?", "Traditional thread pools have a fixed number of threads (e.g., 200), so caching large objects in `ThreadLocal` consumed a predictable, bounded amount of memory (200 objects). With Virtual Threads, the application might spawn 1,000,000 concurrent threads. If each virtual thread allocates a large object in a `ThreadLocal`, you instantly allocate 1 million large objects, causing a massive heap OOM. `ThreadLocal` should be strictly avoided for caching with Virtual Threads (replaced with `ScopedValue` or passed explicitly).", ["Virtual Threads can scale to millions concurrently", "ThreadLocal variables are multiplied by millions, causing massive Heap OOM", "ThreadLocals must not be used for caching in a Virtual Thread environment"], ["Virtual threads store their data on the hard drive"]),
    ("B55_2", "concept", "medium", "concept", ["Concurrency"], "In the context of Structured Concurrency, what is the difference between `ShutdownOnFailure` and `ShutdownOnSuccess` policies?", "`ShutdownOnFailure` is used when you need ALL subtasks to succeed (like an 'AND' operation). If any subtask throws an exception, the scope automatically cancels all other running subtasks and throws the error. `ShutdownOnSuccess` is used when you only need the result of the FIRST successful subtask (like an 'OR' operation, e.g., querying 3 redundant databases). As soon as one task returns successfully, it automatically cancels the remaining running subtasks and returns the result.", ["`ShutdownOnFailure`: Cancels all siblings if ANY task fails (AND logic)", "`ShutdownOnSuccess`: Cancels all siblings as soon as ONE task succeeds (OR logic)", "Provides automatic short-circuiting and clean cancellation"], ["They are used to shut down the physical server rack"]),
    ("B55_2", "explain", "easy", "explain", ["Concurrency"], "Is it recommended to pool Virtual Threads using a Thread Pool?", "No, pooling Virtual Threads is a strict anti-pattern. Thread pools were invented because OS threads are expensive to create and destroy (taking milliseconds and megabytes of memory). Virtual Threads take nanoseconds to create and consume negligible memory. You should create a brand-new Virtual Thread for every single concurrent task and discard it when finished. Pooling them adds unnecessary orchestration overhead for zero benefit.", ["Pooling Virtual Threads is an anti-pattern", "They are incredibly cheap to create and destroy (nanoseconds)", "Always create a new Virtual Thread per task"], ["Yes, pooling saves CPU cycles"]),
    ("B55_2", "diagnose", "medium", "debugging", ["Concurrency"], "You use `CompletableFuture.supplyAsync()` to execute a task. Does this run on a Virtual Thread by default in Java 21?", "No. By default, `CompletableFuture.supplyAsync()` executes on the common `ForkJoinPool`, which is backed by standard, heavy OS Platform threads. If you want a `CompletableFuture` to execute on a Virtual Thread, you must explicitly pass a Virtual Thread executor as the second argument: `CompletableFuture.supplyAsync(() -> doWork(), Executors.newVirtualThreadPerTaskExecutor())`.", ["No, it defaults to the common `ForkJoinPool` (Platform threads)", "Must explicitly pass a Virtual Thread executor to the method", "Otherwise, you do not get the scalability benefits of Project Loom"], ["Yes, Java 21 automatically converts everything to Virtual Threads"]),
    ("B55_2", "architecture", "hard", "architecture", ["Concurrency"], "How do Virtual Threads impact the architecture of connection pools (like HikariCP) and external databases?", "Virtual Threads allow the JVM to easily handle 10,000 concurrent HTTP requests. However, if your database connection pool is maxed at 100 connections (because Postgres cannot efficiently handle 10,000 active connections), 9,900 Virtual Threads will simply block waiting for a connection from the pool. While the JVM can handle this without crashing, the database becomes the strict bottleneck. Virtual Threads do not magically increase the concurrency limit of external resources; they often require implementing strict semaphores or external backpressure to avoid starving the pool.", ["Virtual Threads shift the bottleneck from the JVM to external resources (databases)", "Thousands of Virtual Threads will block waiting on a small connection pool", "Requires explicit backpressure or semaphores to prevent overwhelming downstream services"], ["Virtual Threads automatically multiply the database connections"]),

    # Area 3: Java Memory Model, Happens-Before, & Atomics
    ("B55_3", "concept", "hard", "concept", ["JVM Internals"], "Explain the 'Happens-Before' relationship in the Java Memory Model (JMM).", "The JMM allows threads to cache variables in CPU registers or L1 caches for performance, leading to visibility issues where Thread B cannot see updates made by Thread A. A 'Happens-Before' relationship is a strict guarantee by the JMM that memory writes made by one specific action will be visibly fully propagated to a subsequent action. For example, unlocking a monitor (mutex) 'happens-before' a subsequent lock of that same monitor, and writing to a `volatile` variable 'happens-before' a subsequent read of that variable, preventing memory staleness and instruction reordering.", ["A strict JMM guarantee regarding memory visibility and instruction reordering", "Ensures writes by action A are visible to action B", "Established by `volatile`, locks, thread joins, and final fields"], ["It forces the JVM to execute code backwards"]),
    ("B55_3", "diagnose", "medium", "debugging", ["Concurrency"], "Thread A executes `flag = true;`. Thread B spins in a loop `while (!flag) {}`. Both run concurrently. The loop never terminates, even though Thread A sets the flag. Why?", "The `flag` variable is not marked as `volatile`. The JVM's JIT compiler or the CPU hardware is allowed to optimize the `while (!flag)` loop in Thread B. Because it sees no writes to `flag` inside the loop, it hoists the read outside the loop (essentially compiling it to `if (!flag) { while (true) {} }`), or caches it in an L1 register. Marking `boolean volatile flag` enforces a happens-before relationship, forcing Thread B to read the fresh value from main memory on every single iteration.", ["The variable is not `volatile`, so the thread caches the value locally", "The JIT compiler optimizes/hoists the read outside the loop", "`volatile` forces reads directly from main memory, preventing caching"], ["Thread B is running on a broken CPU"]),
    ("B55_3", "tradeoff", "hard", "tradeoff", ["Concurrency"], "What is the tradeoff of using `AtomicInteger.incrementAndGet()` versus using a `synchronized` block to increment an integer?", "A `synchronized` block uses a Pessimistic Locking strategy (mutex), which requires the OS to suspend the thread if the lock is contended, causing massive context-switching overhead. `AtomicInteger` uses an Optimistic, lock-free strategy utilizing a hardware-level Compare-And-Swap (CAS) CPU instruction. CAS is vastly faster under low-to-medium contention. However, the tradeoff is that under extreme contention, CAS spins continuously in a `while(true)` loop trying to update the value, burning 100% CPU without making progress, whereas synchronized would politely park the thread.", ["`AtomicInteger` uses lock-free hardware CAS (Compare-And-Swap)", "CAS is extremely fast and avoids OS context switching overhead", "Under extreme contention, CAS spins burning CPU cycles, whereas `synchronized` parks the thread"], ["AtomicInteger only works for numbers below 100"]),
    ("B55_3", "architecture", "hard", "architecture", ["JVM Internals"], "How does the JMM treat `final` fields during object construction, and how does it prevent 'partially constructed' object escapes?", "In Java, an object's memory is allocated before its constructor finishes. Without `final` fields, another thread could theoretically see a reference to the object and read its fields *before* the constructor has finished assigning them (seeing nulls or zeros). The JMM provides a special 'freeze' guarantee for `final` fields: any thread that sees the object reference is mathematically guaranteed to see the correctly initialized values of its `final` fields. However, this guarantee is void if you leak the `this` reference out of the constructor before it finishes.", ["JMM guarantees `final` fields are fully initialized before any other thread sees the object", "Prevents seeing 'partially constructed' objects with default zero/null values", "Requires that the `this` reference is not leaked during construction"], ["Final fields are stored on the hard drive"]),
    ("B55_3", "scenario", "medium", "scenario", ["Concurrency"], "You are implementing a Singleton pattern using Double-Checked Locking. You use `if (instance == null) { synchronized(this) { if (instance == null) instance = new Singleton(); } }`. You forget to mark the `instance` variable as `volatile`. What catastrophic bug can occur?", "Object instantiation in Java (`instance = new Singleton();`) is not atomic; it consists of three steps: 1) allocate memory, 2) execute constructor, 3) assign reference. The JIT compiler or CPU is allowed to reorder steps 2 and 3. It can assign the memory reference to `instance` *before* the constructor finishes. If Thread B enters the first `if (instance == null)` at that exact microsecond, it sees a non-null reference and returns a partially-constructed, uninitialized object, causing NullPointerExceptions. `volatile` strictly prevents this instruction reordering.", ["Object creation is not atomic; steps can be reordered (allocate, assign, construct)", "Thread B can read a non-null reference to an uninitialized object", "`volatile` prevents instruction reordering, enforcing the happens-before edge"], ["The singleton will create two objects"]),
    ("B55_3", "concept", "easy", "concept", ["Concurrency"], "What is a 'Race Condition' in Java concurrency?", "A race condition occurs when two or more threads attempt to read and write to a shared variable or resource simultaneously without proper synchronization, and the final state of the data depends on the unpredictable, precise timing (the 'race') of the OS thread scheduler. For example, two threads executing `count++` might read the same initial value, increment it, and overwrite each other, losing an increment.", ["Simultaneous, unsynchronized access to shared mutable data", "Final outcome depends on the unpredictable OS thread scheduling", "Often results in lost updates or corrupted state"], ["It's when threads run a benchmark test"]),
    ("B55_3", "explain", "medium", "explain", ["Concurrency"], "Explain the concept of 'False Sharing' in multi-threaded Java applications and how the `@Contended` annotation helps.", "Modern CPUs read memory in 'Cache Lines' (typically 64 bytes). If two distinct `volatile` variables (e.g., Thread A's counter and Thread B's counter) happen to sit next to each other in memory, they fall into the same cache line. When Thread A updates its counter, the CPU invalidates the *entire* cache line across all cores. Thread B is forced to fetch from main memory even though its specific variable didn't change, causing severe performance degradation. `@Contended` pads the variable with empty bytes to ensure it sits on its own dedicated cache line, eliminating the false sharing.", ["Variables close in memory share a 64-byte CPU Cache Line", "Updates to one variable invalidate the cache for the other thread, causing CPU stalls", "`@Contended` adds memory padding to isolate variables to distinct cache lines"], ["False sharing is when threads steal memory from each other"]),
    ("B55_3", "implement", "medium", "implement", ["Concurrency"], "How do you safely update multiple independent fields in an object atomically without using heavy `synchronized` blocks?", "You can use `AtomicReference` combined with immutable objects. You encapsulate all the fields into a single immutable class (e.g., `State`). You store this object in an `AtomicReference<State>`. To update, you use a CAS loop (`updateAndGet()` or `accumulateAndGet()`) to read the current state, instantiate a brand new `State` object with the modified fields, and atomically swap the reference. Because the swap is a single reference change, the entire multi-field update is lock-free and atomic.", ["Encapsulate the multiple fields into a single immutable object", "Store the object in an `AtomicReference`", "Use Compare-And-Swap (CAS) to atomically swap the old reference with a newly constructed object"], ["Put all fields into an ArrayList"]),
    ("B55_3", "diagnose", "hard", "debugging", ["Concurrency"], "You use `LongAdder` instead of `AtomicLong` for a highly concurrent metric counter. When you read the total count, it is sometimes slightly lower than expected for a fraction of a second. Why?", "`LongAdder` is designed for extreme write contention. Instead of forcing all threads to CAS a single memory location (like `AtomicLong`), `LongAdder` creates an array of separate memory cells. Threads update different cells independently, completely eliminating contention. However, when you call `longAdder.sum()`, it must iterate and add up all the cells. This summation is NOT atomic. If threads are actively updating cells while `sum()` is executing, the returned total is an eventual, approximate snapshot, not a strict real-time value.", ["`LongAdder` spreads contention across an array of cells", "Calling `sum()` iterates the cells, but this read is NOT atomic", "Provides high write throughput but approximate, eventual-consistency reads"], ["LongAdder suffers from integer overflow"]),
    ("B55_3", "tradeoff", "hard", "tradeoff", ["Concurrency"], "What is the tradeoff between `ReentrantLock` and `ReentrantReadWriteLock`? When is the ReadWriteLock actually slower?", "A `ReentrantReadWriteLock` allows multiple threads to hold the Read lock simultaneously, but enforces exclusive access for the Write lock. In theory, this optimizes read-heavy workloads. However, the internal bookkeeping to manage shared read locks is complex and computationally expensive. If the read operations are extremely fast (e.g., reading a cached variable), the overhead of acquiring the Read lock is actually slower than just using a standard, exclusive `ReentrantLock`. `ReadWriteLock` is only beneficial if the read operations take a significantly long time to execute.", ["`ReadWriteLock` allows concurrent readers but exclusive writers", "Internal state bookkeeping for shared locks is highly computationally expensive", "Slower than standard locks if the read operations are very short/fast"], ["ReadWriteLock requires the user to type more code"]),

    # Area 4: Modern Java Features (Records, Sealed Classes, Pattern Matching)
    ("B55_4", "concept", "medium", "concept", ["Language Features"], "What are Java `record`s, and how do they differ fundamentally from standard POJOs?", "Introduced in Java 14, a `record` is a specialized, concise class designed purely as a transparent carrier for immutable data. Unlike a POJO, you do not write getters, setters, constructors, `equals()`, `hashCode()`, or `toString()`; the compiler generates them automatically based on the state description. Fundamentally, a record's state is strictly immutable (fields are implicitly `private final`), and it cannot extend any other class (it implicitly extends `java.lang.Record`).", ["Concise, transparent carriers for immutable data", "Compiler auto-generates constructor, getters, equals, hashCode, and toString", "Fields are strictly `private final`, and records cannot extend other classes"], ["Records are used to save data to the hard drive"]),
    ("B55_4", "architecture", "hard", "architecture", ["Language Features"], "Explain the concept of 'Sealed Classes' (JEP 409) and how they enable exhaustive Pattern Matching in Java.", "A `sealed` class or interface explicitly restricts which other classes may extend or implement it using the `permits` clause (e.g., `public sealed class Shape permits Circle, Square`). Because the compiler knows the absolute, exhaustive list of all possible subclasses, when you use Pattern Matching in a `switch` statement over a `Shape`, the compiler can guarantee you have covered all possible cases (`case Circle c`, `case Square s`). If you cover all permitted subclasses, you do not need to provide a `default` case.", ["Restricts inheritance to a specific `permits` list of subclasses", "Compiler knows all possible implementations statically", "Enables exhaustive `switch` pattern matching without needing a `default` case"], ["Sealed classes are encrypted in memory"]),
    ("B55_4", "implement", "medium", "implement", ["Language Features"], "How do you safely validate data during the instantiation of a Java `record` without rewriting the entire constructor signature?", "You use a 'Compact Constructor'. In a record, you can declare a constructor without parameters (e.g., `public MyRecord { }`). Inside this block, you have access to the implicitly passed arguments, allowing you to validate them (e.g., `if (age < 0) throw new IllegalArgumentException();`) or mutate them before they are assigned to the final fields. You do not write `this.age = age;`; the compiler handles the final assignment automatically after your compact block finishes.", ["Use a Compact Constructor (no parameter list)", "Allows validation or normalization of arguments", "Compiler automatically handles the assignment to final fields afterward"], ["You must use a Builder pattern"]),
    ("B55_4", "diagnose", "medium", "debugging", ["Language Features"], "You write `Object obj = \"Hello\"; if (obj instanceof String) { String s = (String) obj; s.toUpperCase(); }`. How do you modernize this using Java Pattern Matching for `instanceof`?", "Java 16 introduced Pattern Matching for `instanceof`. It eliminates the need for the redundant cast. You can directly bind the matched variable in the condition: `if (obj instanceof String s) { s.toUpperCase(); }`. The variable `s` is scoped securely to the true-block of the `if` statement, making the code safer and more concise.", ["Use Pattern Matching: `if (obj instanceof String s)`", "Eliminates the boilerplate and risk of explicit casting", "The bound variable `s` is scoped strictly to the true-block"], ["You must cast it using Reflection"]),
    ("B55_4", "tradeoff", "medium", "tradeoff", ["Language Features"], "What is the tradeoff of replacing all standard JPA/Hibernate `@Entity` classes with Java `record`s?", "It is generally impossible or a severe anti-pattern. The tradeoff is that JPA fundamentally relies on proxying, reflection, and mutability. JPA providers (like Hibernate) require a no-arg constructor, require the class to be non-final (so they can create lazy-loading proxies), and often require mutating fields (setters) to update database state. Records are strictly immutable, have no no-arg constructor, and are implicitly `final`. Therefore, records are excellent for DTOs and projections, but completely incompatible as JPA Entities.", ["JPA requires mutability, no-arg constructors, and non-final classes for proxies", "Records are strictly immutable, final, and lack no-arg constructors", "Records are perfect for DTOs, but incompatible as JPA Entities"], ["Records consume more database storage"]),
    ("B55_4", "concept", "easy", "concept", ["Language Features"], "What does the `var` keyword do in Java, and is Java dynamically typed when using it?", "The `var` keyword (Local-Variable Type Inference) allows you to omit the explicit type declaration for a local variable, letting the compiler infer the type from the right-hand assignment (e.g., `var list = new ArrayList<String>();`). Java is absolutely NOT dynamically typed when using `var`. It remains strictly, statically typed. The compiler just fills in the type at compile time. You cannot reassign `list` to an integer later.", ["Enables Local-Variable Type Inference", "Java remains 100% statically typed; the type is locked at compile time", "Reduces boilerplate for complex generic types"], ["var makes Java dynamically typed like JavaScript"]),
    ("B55_4", "explain", "hard", "explain", ["Language Features"], "Explain how Java 21's 'Pattern Matching for switch' handles nulls compared to legacy switch statements.", "Historically, passing a `null` value into a `switch` statement resulted in an immediate `NullPointerException`. In modern Java Pattern Matching for `switch`, you can explicitly handle nulls using `case null:`. If you do not provide a `case null`, and the input is null, it continues to throw an NPE for backward compatibility. You can also combine cases, e.g., `case null, default:`, providing complete, safe control over null references directly within the switch construct.", ["Legacy switch statements throw NPE on null input", "Modern switch allows explicit `case null:` branches", "Provides safe, declarative null handling directly in the control flow"], ["Switch statements still cannot accept nulls"]),
    ("B55_4", "scenario", "medium", "scenario", ["Language Features"], "You need to extract the X and Y coordinates from a `Point` record. How can Java 21 Record Patterns make this cleaner?", "Java 21 introduced Record Patterns, which allow you to deconstruct a record directly in an `instanceof` or `switch` expression. Instead of writing `if (obj instanceof Point p) { int x = p.x(); }`, you can deconstruct it inline: `if (obj instanceof Point(int x, int y)) { System.out.println(x + y); }`. This extracts the components directly into local variables `x` and `y` without needing to call the accessor methods.", ["Record Patterns deconstruct the record into local variables inline", "Syntax: `if (obj instanceof Point(int x, int y))`", "Eliminates the need to manually call accessor methods"], ["You must serialize it to JSON first"]),
    ("B55_4", "architecture", "hard", "architecture", ["Language Features"], "How does the JVM implement String interpolation/templates (JEP 430) securely to prevent SQL Injection, compared to basic string concatenation?", "Basic string concatenation (`\"SELECT * FROM users WHERE id = \" + id`) blindly merges text, leaving the app vulnerable to injection. Java String Templates use Template Processors (like `STR` or custom SQL processors). Instead of concatenating, the compiler passes the raw template structure and the independent values to the Processor as an object. A secure SQL Template Processor (e.g., `SQL.\"SELECT...\\{id}\"`) intercepts the values, safely parameterizes them into a `PreparedStatement`, and executes it, structurally eliminating injection risks at the language level.", ["Concatenation blindly merges text, risking injection", "String Templates pass the structure and values independently to a Processor", "Custom processors (like SQL) can safely bind variables as parameters, preventing injection"], ["It uses a Regex to filter out bad characters"]),
    ("B55_4", "tradeoff", "medium", "tradeoff", ["Language Features"], "What is the tradeoff of using Text Blocks (`\"\"\"`) in Java for JSON payloads?", "Text Blocks allow multi-line strings without tedious `\n` and `+` concatenation, making JSON highly readable in the source code. The tradeoff is primarily formatting and whitespace management: the compiler auto-strips incidental leading whitespace based on the position of the closing `\"\"\"`. If a developer misaligns the closing quotes, the resulting string will contain unintended leading spaces on every line, which could subtly break strict JSON parsers or hash-based signature algorithms.", ["Makes multi-line JSON readable without manual escape characters", "Compiler calculates incidental whitespace based on the closing quote position", "Misaligning the closing quote can inject unintended leading spaces, breaking strict parsers/hashes"], ["Text Blocks use more memory than standard strings"]),

    # Area 5: Classloading, Reflection, & Bytecode
    ("B55_5", "concept", "hard", "concept", ["JVM Internals"], "Explain the Java ClassLoader 'Parent Delegation Model'. Why is it critical for JVM security?", "When a ClassLoader is asked to load a class, it does not load it immediately. Instead, it delegates the request up to its Parent ClassLoader. This continues recursively up to the Bootstrap ClassLoader. Only if the parent cannot find the class does the child attempt to load it. This prevents severe security attacks (like 'Class Spoofing'). If an attacker creates a malicious `java.lang.String` class in their application jar, the delegation model ensures the Bootstrap ClassLoader finds and loads the legitimate, secure OS-level `String` class first, completely ignoring the malicious override.", ["ClassLoaders recursively delegate load requests up to the parent (Bootstrap) first", "Child only loads the class if all parents fail", "Prevents 'Class Spoofing', ensuring core secure classes (like `java.lang.String`) cannot be overridden by malicious jars"], ["Parents delete the child classes"]),
    ("B55_5", "diagnose", "hard", "debugging", ["JVM Internals"], "You deploy an application to a Tomcat server and get a `java.lang.NoSuchMethodError`. However, you inspect the WAR file, and the exact method definitely exists in a dependency JAR. What is causing this, and what is 'Jar Hell'?", "This is a classic 'Jar Hell' ClassPath conflict. The web server (Tomcat) or a parent classloader already has an older version of that exact dependency (or class) loaded in memory. Because ClassLoaders load the *first* matching class they find on the classpath and cache it, the JVM executes the older class (which lacks the new method) and completely ignores the correct JAR bundled in your WAR file. The fix requires classloader isolation (like OSGi or Spring Boot fat jars) or excluding the conflicting dependency.", ["Caused by multiple versions of the same library on the ClassPath", "The ClassLoader finds and loads the older version first", "The newer version in the WAR is ignored, causing `NoSuchMethodError`"], ["The method is marked private"]),
    ("B55_5", "architecture", "medium", "architecture", ["JVM Internals"], "What is the architectural difference between 'Static Proxies' (Interfaces) and 'Dynamic Proxies' (CGLIB) in Java frameworks like Spring or Hibernate?", "Static Proxies (JDK Dynamic Proxies) are built into Java but can strictly ONLY proxy interfaces. If a class doesn't implement an interface, the JDK cannot proxy it. CGLIB (Code Generation Library) generates Dynamic Proxies by performing runtime Bytecode Manipulation. It generates a brand-new subclass that extends the target class, overriding its methods to inject behavior (like lazy-loading or transactions). Because CGLIB relies on inheritance, it cannot proxy classes marked `final` or methods marked `final`.", ["JDK Proxies can only proxy explicit Interfaces", "CGLIB performs bytecode manipulation to create dynamic subclasses at runtime", "CGLIB cannot proxy `final` classes or `final` methods"], ["Static proxies are faster because they use C++"]),
    ("B55_5", "tradeoff", "hard", "tradeoff", ["JVM Internals"], "What is the severe performance tradeoff of using Java Reflection heavily (e.g., `Method.invoke()`) in a high-throughput transaction loop?", "Reflection defeats the JVM's static type checking and heavily inhibits the JIT (Just-In-Time) Compiler. The JIT compiler optimizes code via method inlining (pasting the method body into the caller to avoid jump overhead). Reflection calls are dynamic, meaning the JIT cannot predict which method will be called, entirely preventing inlining. Furthermore, reflection requires security manager checks and argument array boxing on every invocation. In modern Java, `MethodHandle` (from `java.lang.invoke`) provides a much faster, JIT-friendly alternative to reflection.", ["Reflection inhibits JIT Compiler optimizations (specifically Method Inlining)", "Incurs overhead from security checks and argument boxing", "`MethodHandle` provides a vastly faster, JIT-optimizable modern alternative"], ["Reflection uses internet bandwidth"]),
    ("B55_5", "implement", "medium", "implement", ["JVM Internals"], "How do you bypass private access modifiers to read a private field of an object using Reflection?", "You obtain the `Field` object using `Class.getDeclaredField(\"fieldName\")`. Because the field is private, calling `.get()` will throw an `IllegalAccessException`. You must first call `field.setAccessible(true)`. This instructs the JVM security manager to bypass the language-level access checks, allowing you to read or mutate the private state. Note that modern Java modules (JPMS) heavily restrict this 'deep reflection' across module boundaries to improve security.", ["Use `Class.getDeclaredField()` to get the field reference", "Call `field.setAccessible(true)` to bypass the private access modifier", "Modern Java Modules (JPMS) restrict this cross-module deep reflection"], ["Use the `public` casting keyword"]),
    ("B55_5", "concept", "easy", "concept", ["JVM Internals"], "What is Java Bytecode?", "Java Bytecode is the intermediate, platform-independent instruction set generated by the `javac` compiler when compiling `.java` source code into `.class` files. The JVM (Java Virtual Machine) executes this bytecode. Because it is intermediate, the exact same bytecode can run unmodified on Windows, Linux, or macOS, fulfilling the 'Write Once, Run Anywhere' paradigm.", ["Platform-independent instruction set stored in `.class` files", "Generated by the `javac` compiler", "Interpreted and compiled by the JVM across different operating systems"], ["It is binary machine code for Intel CPUs"]),
    ("B55_5", "explain", "medium", "explain", ["JVM Internals"], "Explain the concept of 'Type Erasure' in Java Generics. Why was it designed this way?", "Type Erasure means that generic type parameters (like `<String>` in `List<String>`) are strictly a compile-time construct. During compilation, the compiler strips (erases) all generic type information and replaces it with raw `Object` types (and inserts automatic casts). At runtime, the JVM has absolutely no idea if the list was a `List<String>` or a `List<Integer>`. This was a deliberate architectural decision to ensure 100% backward compatibility with legacy Java code written before Generics were introduced in Java 5.", ["Generics are a compile-time safety check only", "The compiler erases the type to raw `Object` during bytecode generation", "Designed strictly to maintain backward compatibility with pre-Java 5 legacy code"], ["Type erasure wipes the hard drive"]),
    ("B55_5", "scenario", "hard", "scenario", ["JVM Internals"], "You need to serialize a generic `List<User>` to JSON using Jackson. You pass `List.class` to the ObjectMapper, but Jackson deserializes it into a `List<LinkedHashMap>` instead of `List<User>`. Why did this happen, and how do you fix it?", "Because of Type Erasure, `List.class` completely loses the `<User>` type information at runtime; Jackson only sees a raw `List`, so it defaults to deserializing JSON objects into generic `LinkedHashMap`s. To fix this, you must use a 'Super Type Token'. In Jackson, this is done by passing `new TypeReference<List<User>>() {}`. By creating an anonymous subclass, the generic type information is preserved in the compiled bytecode signature of the subclass, allowing Jackson to read it via reflection.", ["Type Erasure destroys the `<User>` generic type at runtime", "Jackson defaults to `LinkedHashMap` when the type is unknown", "Fix by using a Super Type Token (`TypeReference<List<User>>`) to preserve generics in subclass metadata"], ["Jackson doesn't support Lists"]),
    ("B55_5", "diagnose", "medium", "debugging", ["JVM Internals"], "You attach a Java Agent (like an APM tool) to your JVM using `-javaagent`. Suddenly, application startup slows down from 5 seconds to 45 seconds. What is the agent doing to cause this?", "Java Agents heavily utilize the `Instrumentation` API to intercept and modify class bytecode dynamically *as it is being loaded* into the JVM. To inject timing or tracing metrics (like Datadog or New Relic), the agent must decompile, analyze, modify, and recompile the bytecode of thousands of application and framework classes during startup. This massive CPU-bound bytecode manipulation overhead causes the severe startup latency.", ["Agents use the `Instrumentation` API to modify bytecode at load time", "Injecting tracing/metrics requires decompiling and recompiling thousands of classes", "The CPU overhead of this bytecode manipulation causes severe startup delay"], ["The agent is downloading updates from the internet"]),
    ("B55_5", "concept", "hard", "concept", ["JVM Internals"], "What is the 'Constant Pool' in a compiled Java `.class` file?", "The Constant Pool is a localized symbol table inside every `.class` file. Instead of duplicating string literals, method names, and class references repeatedly throughout the bytecode instructions, the compiler stores them exactly once in the Constant Pool array. The bytecode instructions then reference them by their index (e.g., `#14`). This drastic deduplication reduces the size of the class file. During class loading, the JVM resolves these symbolic references into actual direct memory pointers.", ["A symbol table inside the `.class` file storing strings, method names, and class references", "Bytecode instructions refer to these constants via an array index", "Deduplicates data to reduce file size and aids symbolic resolution during loading"], ["It is a pool of threads that never die"])
]

def run_batch():
    with open(OUT, "r", encoding="utf-8") as f:
        existing = [json.loads(line) for line in f if line.strip()]

    print(f"Loaded {len(existing)} existing records.")
    
    for q in Q:
        if LEAK.search(q[5]) or LEAK.search(q[6]):
            print(f"PROMPT LEAK DETECTED in: {q[5]}")
            sys.exit(1)
            
    existing_texts = [ex["question"] for ex in existing]
    new_texts = [q[5] for q in Q]
    
    vec = TfidfVectorizer(stop_words="english", ngram_range=(1,2))
    all_texts = existing_texts + new_texts
    vec.fit(all_texts)
    
    existing_vecs = vec.transform(existing_texts)
    new_vecs = vec.transform(new_texts)
    
    sim_matrix = cosine_similarity(new_vecs, existing_vecs)
    
    accepted = []
    rejected = []
    
    for i, q in enumerate(Q):
        max_sim = float(sim_matrix[i].max()) if sim_matrix.shape[1] > 0 else 0
        if max_sim > 0.85:
            print(f"REJECTED (Sim: {max_sim:.2f}): {q[5][:50]}...")
            rejected.append(q)
        else:
            accepted.append(q)
            
    print(f"Accepted {len(accepted)} / {len(Q)} questions.")
    
    new_records = []
    for q in accepted:
        rec = {
            "primary_role": ROLE,
            "applicable_roles": ["Backend Developer", "Full Stack Developer"],
            "primary_skill": q[4][0],
            "secondary_skills": q[4][1:] if len(q[4]) > 1 else [],
            "technology": "Java",
            "topic": q[4][0] if len(q[4]) > 0 else "General",
            "category": "Software Engineering",
            "intent": q[1],
            "difficulty": q[2],
            "question_type": q[3],
            "question": q[5],
            "expected_answer": q[6],
            "evaluation_rubric": {
                "strong_indicators": q[7],
                "weak_indicators": q[8]
            },
            "id": str(uuid.uuid4()),
            "source": "Antigravity_Internal_Knowledge",
            "provenance_type": "researched_generated",
            "dataset_version": "v2",
            "status": "active"
        }
        new_records.append(rec)
        
    with open(OUT, "a", encoding="utf-8") as f:
        for r in new_records:
            f.write(json.dumps(r) + "\n")
            
    with open(OUT, "r", encoding="utf-8") as f:
        final_existing = [json.loads(line) for line in f if line.strip()]
        
    role_counts = Counter(r["primary_role"] for r in final_existing)
    
    print("\n========================================")
    print("POST-BATCH AUDIT")
    print("========================================")
    print(f"Batch: 55")
    print(f"Target role: {ROLE}")
    print(f"Attempted: {len(Q)}")
    print(f"Accepted: {len(accepted)}")
    print(f"Rejected: {len(rejected)}")
    print(f"Replacement count: 0")
    print(f"Cumulative total: {len(final_existing)}")
    print(f"Java total: {role_counts[ROLE]}")
    print("All role totals:")
    for role, count in role_counts.items():
        print(f"  {role}: {count}")
    print(f"Duplicate count: {len(rejected)}")
    print(f"Prompt leakage count: 0")
    print(f"Validation failures: 0")
    
    sha256 = hashlib.sha256()
    with open(OUT, 'rb') as f:
        while chunk := f.read(8192):
            sha256.update(chunk)
            
    print(f"\nFinal SHA256: {sha256.hexdigest()}")

if __name__ == "__main__":
    run_batch()
