"""Batch 9 question content (Full Stack Developer). Antigravity-native, no Gemini API."""

ROLE = "Full Stack Developer"

# key: (plan skill, plan topic, applicable_roles)
BUCKET_KEYS = {
    "JWT": ("Authentication", "JWT", ["Backend Developer", "Frontend Developer"]),
    "OAU": ("Authentication", "OAuth", ["Backend Developer", "Frontend Developer"]),
    "ARC": ("System Architecture", "Monolith vs Microservices", ["Backend Developer", "DevOps / Cloud Engineer"]),
    "NET": ("Debugging", "Network Tab", ["Frontend Developer", "Backend Developer"]),
    "LOG": ("Debugging", "Server Logs", ["Backend Developer", "DevOps / Cloud Engineer"]),
}

# (bucket, intent, difficulty, qtype, secondary_skills, question, expected_answer, strong, weak)
Q = [
# ---------------- JWT across the stack ----------------
("JWT", "explain", "easy", "concept", ["Security"],
 "A teammate puts the user's role and email in a JWT payload and says it is safe because the token is signed. What can the browser user see, and what can't they change?",
 "A signed JWT is only encoded (base64url), not encrypted, so anyone holding it can decode and read the payload. Signing protects integrity: if the user alters the payload the signature check on the server fails. So sensitive data should not be placed in the payload, though tampering is detectable.",
 ["Payload is readable", "Signature protects integrity", "Do not store secrets in payload"],
 ["Believes a signed JWT is encrypted"]),
("JWT", "scenario", "easy", "scenario", [],
 "Your React app calls an API and gets a 401 because the access token expired. What should the frontend do?",
 "Detect the 401, try to obtain a new access token using the refresh mechanism once, and retry the original request. If refresh fails, clear the session and redirect to login. Avoid retrying in an infinite loop.",
 ["Refresh then retry once", "Redirect to login on failure", "No infinite retry loop"],
 ["Only shows an error message and leaves the user stuck"]),
("JWT", "implement", "easy", "implementation", ["React"],
 "How would you make a React client attach the access token to every API request without repeating code in each call?",
 "Centralize it in an HTTP client wrapper: an Axios request interceptor or a fetch helper that reads the token and sets the Authorization: Bearer <token> header. A response interceptor can also handle 401 responses in one place.",
 ["Interceptor or wrapper", "Authorization Bearer header", "Central 401 handling"],
 ["Adds the header manually in every component"]),
("JWT", "debug", "easy", "debugging", [],
 "Login succeeds and the token is stored, but every following API call returns 401. The request header shows 'Authorization: eyJhbGci...'. What is a likely cause?",
 "The server expects the standard scheme 'Authorization: Bearer <token>' and the client omitted the 'Bearer ' prefix, so the auth middleware cannot parse the token. Fix the client header (or the parser) and confirm using the Network tab.",
 ["Missing Bearer prefix", "Middleware parsing expectation", "Verify in request headers"],
 ["Blames the database"]),
("JWT", "explain", "easy", "concept", ["Security"],
 "Why shouldn't hiding an admin page in the frontend, based on a role decoded from the JWT, be your only access control?",
 "Frontend checks are only user-experience gating because the user controls their browser and can alter code, storage or requests. The server must verify the token and enforce authorization on every API endpoint; UI hiding just avoids showing unusable options.",
 ["Client is untrusted", "Server enforces authorization", "UI gating is UX only"],
 ["Says the JWT check in React is enough"]),
("JWT", "tradeoff", "medium", "tradeoff", ["Security"],
 "For a single-page app, what are the trade-offs between storing tokens in localStorage and in an HttpOnly cookie?",
 "localStorage is readable by any JavaScript, so an XSS vulnerability can steal the token, but it is not sent automatically so there is no CSRF exposure. An HttpOnly cookie is invisible to JavaScript, protecting against token theft by XSS, but the browser sends it automatically, so CSRF protection (SameSite, CSRF tokens) is needed. Neither fixes XSS itself.",
 ["XSS risk for localStorage", "CSRF risk for cookies", "SameSite and CSRF tokens", "HttpOnly hides from scripts"],
 ["Says one option has no security risk"]),
("JWT", "architecture", "medium", "architecture", [],
 "Describe how a short-lived access token and refresh token flow works across the SPA and API, including how the SPA avoids sending several refresh requests when many calls fail at once.",
 "The API issues a short-lived access token and a longer-lived refresh token (ideally HttpOnly cookie, rotated on use). When the access token expires, the client calls the refresh endpoint to get a new pair. To avoid parallel refreshes, the client keeps one in-flight refresh promise: calls that get 401 wait for it and then retry. Rotation lets the server detect refresh token reuse.",
 ["Short-lived access plus refresh token", "Single in-flight refresh", "Refresh token rotation"],
 ["Uses one long-lived token only"]),
("JWT", "scenario", "medium", "scenario", ["Security"],
 "An admin removes a user's access, but the user's JWT stays valid for another 15 minutes. How would you deal with that?",
 "Stateless JWTs cannot be revoked before expiry without extra state. Options: keep access tokens short-lived, revoke refresh tokens so no new token is issued, maintain a denylist or a per-user token version checked on sensitive requests, or use opaque tokens with introspection. Choose based on how fast revocation must be versus the cost of server lookups.",
 ["Stateless tokens persist until expiry", "Short expiry and revoke refresh tokens", "Denylist or token version", "Trade-off with lookup cost"],
 ["Says deleting the user record invalidates existing JWTs automatically"]),
("JWT", "diagnose", "medium", "debugging", ["CORS"],
 "The React app on app.example.com authenticates with a cookie, but the API on api.example.com never receives it. The login request works. What do you check?",
 "Cross-origin requests omit cookies unless the client sets credentials (fetch credentials: 'include' or axios withCredentials). The server must send Access-Control-Allow-Credentials: true with a specific origin (not *), and the cookie needs suitable attributes (Domain, SameSite=None; Secure for cross-site contexts). Verify using the Network tab and Set-Cookie warnings.",
 ["Client credentials option", "Allow-Credentials with specific origin", "SameSite and Secure attributes"],
 ["Only adds a wildcard origin"]),
("JWT", "implement", "medium", "implementation", [],
 "How should logout work in a JWT-based app where the API is otherwise stateless?",
 "The client discards its tokens, and the server revokes the refresh token (delete or mark it as used in the store) and clears any auth cookie so no new access tokens can be issued. The existing access token stays valid until it expires, so keep its lifetime short or add a denylist for high-risk cases.",
 ["Client clears tokens", "Server revokes refresh token", "Access token valid until expiry"],
 ["Believes deleting localStorage fully ends the session"]),

# ---------------- OAuth ----------------
("OAU", "fundamentals", "easy", "concept", [],
 "Why would an app offer 'Sign in with Google' through OAuth instead of asking users for their Google password?",
 "OAuth delegates authorization: the user authenticates with Google directly, and the app receives a limited token, never the password. It limits exposure, supports scopes and revocation, and reduces the app's own credential storage risk.",
 ["User authenticates with the provider", "App never sees the password", "Scoped and revocable tokens"],
 ["Says OAuth sends the password securely to the app"]),
("OAU", "explain", "easy", "concept", [],
 "In the authorization code flow, which parties are involved and what does each one do?",
 "The resource owner (user) grants consent. The client application requests access. The authorization server authenticates the user and issues the code and tokens. The resource server (API) accepts access tokens and serves protected data.",
 ["User, client, authorization server, resource server", "Roles described correctly"],
 ["Merges the authorization server and the client"]),
("OAU", "explain", "easy", "concept", [],
 "Why must a redirect URI be registered with the OAuth provider and matched exactly?",
 "The provider sends the authorization code to the redirect URI. If any URL were accepted, an attacker could redirect the code to their own site. Exact matching of pre-registered URIs prevents code interception and open-redirect abuse.",
 ["Code delivered to redirect URI", "Prevents attacker redirect", "Exact match required"],
 ["Says it is only for user experience"]),
("OAU", "explain", "easy", "concept", [],
 "What does OpenID Connect add on top of OAuth 2.0?",
 "OAuth 2.0 handles authorization (access tokens). OpenID Connect adds an authentication layer: an ID token (a JWT) describing who the user is, standard scopes like openid and profile, and a UserInfo endpoint, so apps can log users in.",
 ["Authentication layer on OAuth", "ID token", "openid scope"],
 ["Says OAuth already provides an identity token"]),
("OAU", "implement", "medium", "implementation", ["Security"],
 "How does the authorization code flow with PKCE work for a single-page app, and what attack does it prevent?",
 "The SPA generates a random code_verifier and sends its hash (code_challenge) in the authorization request. After login the provider returns a code to the redirect URI, and the SPA exchanges it, sending the original code_verifier. The provider verifies the hash matches. A stolen authorization code is useless without the verifier, preventing authorization code interception for public clients without a client secret.",
 ["code_verifier and code_challenge", "Verifier sent on token exchange", "Protects public clients from code interception"],
 ["Embeds a client secret in the SPA"]),
("OAU", "tradeoff", "medium", "tradeoff", [],
 "Should the OAuth token exchange happen directly in the SPA or through a backend-for-frontend? What are the trade-offs?",
 "Doing it in the SPA is simple and needs no server, but tokens live in browser JavaScript and are exposed to XSS. A backend-for-frontend performs the exchange with a client secret and stores tokens server-side, giving the browser only an HttpOnly session cookie. It improves security and hides tokens but adds a server component, session management and CSRF considerations.",
 ["SPA exposure to XSS", "BFF keeps tokens server-side", "Extra infrastructure and CSRF"],
 ["Declares one choice always better"]),
("OAU", "debug", "medium", "debugging", [],
 "Google login works locally, but after deploying to production the provider shows 'redirect_uri_mismatch'. What is wrong?",
 "The production callback URL (domain, scheme, port and path) is not registered in the provider's OAuth client, or the app builds a different URL such as http instead of https behind a proxy. Register the exact production URI and make the app generate it correctly, for example by trusting forwarded headers.",
 ["Unregistered production URI", "Exact scheme, host and path", "Proxy and https issues"],
 ["Regenerates the client secret"]),
("OAU", "scenario", "medium", "scenario", ["Security"],
 "A security review notes that your OAuth callback does not check the 'state' parameter. What can go wrong and how do you fix it?",
 "Without state, an attacker can trick a user's browser into completing a login with the attacker's authorization code (login CSRF), tying the victim's session to the attacker's account. Generate an unguessable state per request, store it in the session, and reject callbacks whose state does not match.",
 ["Login CSRF", "Random state tied to session", "Reject mismatch"],
 ["Says state is optional decoration"]),
("OAU", "scenario", "medium", "scenario", ["Security"],
 "A user signs in with Google using an email that already belongs to a password-based account in your app. How do you handle account linking safely?",
 "Only link if the provider asserts the email is verified (email_verified true) and ideally require the user to prove ownership of the existing account (log in with the password or confirm via email) before linking. Automatically merging on an unverified email enables account takeover.",
 ["Check email verification", "Prove ownership before linking", "Avoid automatic merge on unverified email"],
 ["Merges accounts automatically on matching email"]),
("OAU", "architecture", "hard", "architecture", ["Security"],
 "Design the authentication flow for a React SPA and a mobile app that both call the same API and sign in with an external OAuth/OIDC provider. Cover token handling, refresh and logout.",
 "Use authorization code with PKCE for both public clients (system browser on mobile). The API validates access tokens (signature, issuer, audience, expiry, scopes) or uses a BFF for the web client to keep tokens off the browser. Access tokens are short-lived with rotating refresh tokens stored securely (Keychain/Keystore on mobile, HttpOnly cookie or server-side for the web). Logout clears local sessions, revokes refresh tokens and optionally calls the provider's end-session endpoint. Keep authorization on the server, with minimal scopes per client.",
 ["PKCE for public clients", "API validates issuer, audience and expiry", "Secure token storage per platform", "Refresh rotation and revocation on logout"],
 ["Stores long-lived tokens in plain local storage on both clients"]),

# ---------------- Monolith vs Microservices ----------------
("ARC", "fundamentals", "easy", "concept", [],
 "What is the basic difference between deploying a full-stack application as a monolith and as microservices?",
 "A monolith ships as one deployable unit with modules sharing a process and usually one database. Microservices split the application into independently deployable services, each owning its data and communicating over the network, trading simplicity for independent scaling and deployment.",
 ["Single versus independent deployables", "Data ownership per service", "Network communication"],
 ["Says microservices simply means more code files"]),
("ARC", "tradeoff", "easy", "tradeoff", [],
 "Why is a modular monolith often a good starting point for a small team building a new product?",
 "It keeps deployment, debugging, transactions and local development simple while enforcing module boundaries in code. It avoids early network, versioning and operations overhead, and clean boundaries make later extraction into services easier if needed.",
 ["Simple deployment and debugging", "Clear module boundaries", "Easier later extraction"],
 ["Says monoliths cannot be well organized"]),
("ARC", "explain", "easy", "concept", [],
 "What role does an API gateway play between the frontend and a set of backend services?",
 "It provides a single entry point that routes requests to services and can handle cross-cutting concerns such as authentication, rate limiting, TLS termination, logging and request aggregation, so the frontend does not need to know each service's address.",
 ["Single entry point", "Routing", "Cross-cutting concerns"],
 ["Says it stores the application data"]),
("ARC", "scenario", "easy", "scenario", [],
 "A three-person startup is building the first version of a marketplace app. A friend suggests microservices from day one. What would you recommend and why?",
 "Start with a well-structured monolith: a small team benefits from fast iteration, one deployment, easy transactions and low operational burden. Domain boundaries are still unclear, so premature services would create costly distributed complexity. Revisit when scaling or team independence needs justify splitting.",
 ["Favors monolith for small team", "Unclear boundaries early", "Defers microservices until justified"],
 ["Recommends microservices for scalability alone"]),
("ARC", "tradeoff", "medium", "tradeoff", [],
 "What new problems do you take on when you split a monolith into microservices?",
 "Network latency and partial failure, distributed transactions and eventual consistency, data duplication, service discovery, versioning of APIs, more complex deployments and testing, and the need for centralized logging, tracing and monitoring. The benefits are independent scaling and deployment, but the operational cost is real.",
 ["Latency and partial failures", "Distributed data consistency", "Operational overhead", "Observability needs"],
 ["Lists only benefits"]),
("ARC", "scenario", "medium", "scenario", [],
 "A single page in your React frontend now needs data from five different microservices and loads slowly because the browser fires many requests. How would you improve it?",
 "Introduce an aggregation layer: a backend-for-frontend or GraphQL gateway that fetches from the services in parallel on the server and returns one tailored response. This reduces round trips over the client network, hides internal topology and lets you cache and handle partial failures on the server.",
 ["Backend-for-frontend or gateway aggregation", "Server-side parallel calls", "Fewer client round trips"],
 ["Suggests the browser should keep calling all five services"]),
("ARC", "implement", "medium", "implementation", [],
 "How would you gradually extract the payments module out of a monolith using the strangler fig approach?",
 "Identify a clear seam, define the interface, and build the new payments service alongside the monolith. Place a proxy or router in front so selected traffic goes to the new service while the rest still hits the monolith, migrate data ownership carefully, and shift traffic gradually with the ability to roll back. Remove the old code once the new path is proven.",
 ["Define seam and interface", "Routing layer to split traffic", "Gradual migration with rollback"],
 ["Rewrites everything and switches in one release"]),
("ARC", "diagnose", "medium", "debugging", [],
 "After splitting checkout into order and payment services, some orders appear without a payment record. What is likely happening and how do you fix it?",
 "A distributed operation lacks atomicity: the order service commits, then the call or event to payments fails or the service crashes, leaving inconsistent state. Use patterns such as the transactional outbox to publish events reliably, sagas with compensating actions, and idempotent consumers with retries, plus reconciliation jobs.",
 ["No distributed transaction", "Outbox pattern", "Saga with compensation", "Idempotent retries"],
 ["Assumes a single database transaction still covers both services"]),
("ARC", "architecture", "hard", "architecture", [],
 "Propose service boundaries and data ownership for an e-commerce system with catalog, cart, orders and payments, and explain how they communicate.",
 "Split around business capabilities, each with its own data store: catalog (read-heavy, cached/search), cart (session-like, low latency), orders (workflow and state machine) and payments (strict consistency, external provider). Use synchronous calls for queries needing an immediate answer and asynchronous events for state changes (OrderPlaced, PaymentCompleted), with sagas for the checkout flow, idempotency keys, and no shared database. Accept eventual consistency for read models and carefully define contracts.",
 ["Boundaries by business capability", "Each service owns its data", "Sync versus async communication", "Saga and idempotency"],
 ["Uses one shared database for all services"]),
("ARC", "tradeoff", "hard", "tradeoff", [],
 "Between synchronous REST calls and asynchronous events for service-to-service communication, how do you choose, and what failure modes does each introduce?",
 "Synchronous calls are simple and give immediate answers but couple availability and latency (cascading failures, timeouts), needing retries, circuit breakers and timeouts. Asynchronous messaging decouples services and absorbs spikes but adds eventual consistency, ordering, duplicates and harder debugging, needing idempotent consumers, dead-letter queues and correlation IDs. Use sync where the caller needs the result now and async for workflows and notifications.",
 ["Coupling versus decoupling", "Resilience patterns for sync", "Idempotency and DLQ for async", "Choose by use case"],
 ["Claims async messaging is always better"]),

# ---------------- Network Tab ----------------
("NET", "fundamentals", "easy", "concept", [],
 "What useful information does the browser's Network tab show for each request?",
 "The URL, method, status code, request and response headers, request payload, response body, timing breakdown (queueing, waiting for the server, download), size, initiator and whether it came from cache. It lets you see exactly what the frontend sent and what the backend returned.",
 ["Headers, payload and response", "Status code and timing", "Initiator and cache info"],
 ["Says it only shows page load time"]),
("NET", "scenario", "easy", "scenario", [],
 "You click 'Save' and nothing visibly happens. How does the Network tab help you decide whether the bug is in the frontend or the backend?",
 "Check whether a request was sent at all. If no request appears, the problem is in the frontend (handler, validation, wrong event). If a request appears, inspect the payload, status and response: a wrong payload points to the frontend, while a 4xx/5xx or an incorrect response points to the backend.",
 ["Request sent or not", "Inspect payload and status", "Frontend versus backend isolation"],
 ["Starts by changing backend code"]),
("NET", "explain", "easy", "concept", [],
 "How do 4xx and 5xx status codes in the Network tab help you locate where a problem lies?",
 "4xx means the server rejected the request as a client problem (bad input, missing auth, not found), so look at what the frontend sent. 5xx means the server failed handling a valid request, so look at the backend logs. It guides which side to debug first.",
 ["4xx is client-side cause", "5xx is server-side cause"],
 ["Says 5xx errors are always the browser's fault"]),
("NET", "explain", "easy", "concept", [],
 "Before your POST to another origin, the Network tab shows an OPTIONS request. What is it?",
 "It is a CORS preflight request: the browser asks the server whether the actual cross-origin request with certain methods or headers is allowed. The server must respond with the appropriate Access-Control-Allow-* headers, otherwise the real request is blocked.",
 ["CORS preflight", "Server must allow origin, method and headers"],
 ["Says it is a duplicate POST caused by a bug"]),
("NET", "explain", "easy", "concept", [],
 "How can you tell from the Network tab whether a response came from the cache or from the server?",
 "The Size column shows '(memory cache)' or '(disk cache)' for responses served locally, and a 304 Not Modified status shows a conditional request that revalidated with the server and reused the cached body. Cache-Control and ETag headers explain the behavior.",
 ["memory/disk cache labels", "304 revalidation", "Cache-Control and ETag"],
 ["Says a 200 is always a fresh server response"]),
("NET", "diagnose", "medium", "debugging", ["Performance"],
 "In the waterfall, one API request shows a very long 'Waiting for server response' (TTFB) but a short download time. What does that indicate?",
 "The server took long to start responding, so the bottleneck is on the backend (slow queries, heavy computation, blocking calls, cold start) or network latency to it, not the payload size. A long content-download phase would instead point to large responses. Investigate server timing and logs.",
 ["TTFB indicates server processing", "Short download means payload not the issue", "Use server timing and logs"],
 ["Says the user's bandwidth is the problem"]),
("NET", "debug", "medium", "debugging", [],
 "A POST to your API returns 400 and the backend says the body is empty, but your form data looks right in React state. What do you check in the Network tab?",
 "Inspect the request headers and payload: a missing or wrong Content-Type (for example the body is JSON but the header is text/plain, or FormData sent where JSON is expected), a stringified body missing JSON.stringify, or the server lacking the matching body parser. Align Content-Type with how the body is serialized and parsed.",
 ["Check Content-Type", "Verify body serialization", "Server body parser"],
 ["Rewrites the form component first"]),
("NET", "diagnose", "medium", "debugging", ["Caching"],
 "After updating a record, the page still shows old data even though the database has the new value. The Network tab shows a 304 or a disk cache hit for the GET. What is happening?",
 "The browser (or a CDN) is reusing a cached response because of Cache-Control/ETag settings, so the client is not getting the updated data. Fix by setting appropriate cache headers for dynamic API data (no-cache or short max-age with revalidation), invalidating or versioning the request after mutation, or refetching with cache control.",
 ["Cached response reuse", "Cache-Control and ETag", "Cache invalidation after mutation"],
 ["Concludes the database write failed"]),
("NET", "scenario", "medium", "scenario", ["React"],
 "The Network tab shows the same API request firing twice on every page load of your React app. How do you investigate and respond?",
 "Check the initiator to see which code triggers each request. Common causes are React StrictMode double-invoking effects in development, an effect with missing or changing dependencies, or two components fetching the same data. Fix with correct dependency arrays, shared data fetching with a cache library such as React Query, and cleanup or abort logic; the double call in StrictMode dev mode is expected.",
 ["Use initiator information", "StrictMode and effect dependencies", "Shared fetching or caching"],
 ["Adds a delay to hide the duplicate request"]),
("NET", "debug", "medium", "debugging", ["API Contracts"],
 "The API returns 200, but the UI renders an empty list. The Network response shows {\"data\": {\"items\": [...]}} while the UI reads response.items. How do you find and prevent this class of bug?",
 "Compare the actual response shape in the Network tab with what the component expects: the frontend and API contract disagree. Fix the mapping, and prevent recurrence with a shared contract such as an OpenAPI schema, generated TypeScript types or runtime validation (for example zod), plus contract tests.",
 ["Compare actual versus expected shape", "Shared schema or generated types", "Runtime validation or contract tests"],
 ["Blames the browser rendering"]),

# ---------------- Server Logs ----------------
("LOG", "fundamentals", "easy", "concept", [],
 "What are the common log levels, and when would you use each?",
 "DEBUG for detailed diagnostics in development, INFO for normal significant events, WARN for unexpected but handled situations, ERROR for failures needing attention, and sometimes FATAL for unrecoverable states. Levels allow filtering noise and alerting on severity.",
 ["Levels named in order", "Right use for each", "Filtering and alerting"],
 ["Logs everything as one level"]),
("LOG", "explain", "easy", "concept", [],
 "Why is structured JSON logging better than plain text log lines for a production web application?",
 "Structured logs have consistent fields (timestamp, level, request id, user id, route, latency) that tools can index, filter and aggregate without fragile regex parsing, which makes searching and building dashboards or alerts much easier.",
 ["Consistent queryable fields", "No regex parsing", "Aggregation and alerting"],
 ["Says JSON is only prettier"]),
("LOG", "scenario", "easy", "scenario", [],
 "A user reports 'Something went wrong' during checkout at around 2:15 PM. What do you look for first in the server logs?",
 "Filter by the time window and the user or request identifier, find the error entry and stack trace for that request, and check the surrounding entries (the route, inputs, downstream calls). Then determine whether it is an application error, a dependency failure or bad input.",
 ["Filter by time and request or user", "Locate stack trace", "Check surrounding context"],
 ["Searches every log line manually without filters"]),
("LOG", "explain", "easy", "concept", [],
 "What is a correlation (request) ID, and how does it travel from the browser to the server logs?",
 "It is a unique identifier assigned to a request that is attached to every log line it produces. The frontend or gateway generates it (or the server does if missing), passes it in a header such as X-Request-ID, and every service logs and forwards it, so you can follow one request across components.",
 ["Unique per request", "Passed in a header", "Logged and forwarded by every service"],
 ["Confuses it with a user session cookie"]),
("LOG", "implement", "medium", "implementation", ["Node.js"],
 "How would you add request correlation IDs to an Express API?",
 "Add middleware early that reads X-Request-ID or generates a UUID, stores it in request-scoped context (such as AsyncLocalStorage), sets it on the response header, and ensures the logger includes it on every line. Forward the same header on outgoing calls to other services.",
 ["Middleware generates or reads ID", "Request-scoped context", "Response header and downstream propagation"],
 ["Generates a new unrelated ID per log line"]),
("LOG", "debug", "medium", "debugging", [],
 "The frontend receives a generic 500 from your API, but there is no stack trace in the logs. What might be wrong?",
 "The error is probably caught and swallowed (catch block returning a generic response without logging), or there is no centralized error handler logging it, or async errors in routes are not forwarded to the error handler. Add a global error-handling middleware that logs the error with the request ID and handle async rejections properly.",
 ["Swallowed exception", "Global error handler", "Async error propagation"],
 ["Assumes the browser hides the log"]),
("LOG", "diagnose", "medium", "debugging", ["DevOps"],
 "Users see intermittent 502 or 504 errors from the load balancer, but the application logs show nothing unusual. How do you diagnose it?",
 "The requests may never reach the app or may time out before the app finishes. Check load balancer and reverse proxy logs, upstream health checks, timeouts versus slow endpoints, app crashes or restarts (container logs, OOM kills), connection limits, and deployment events. Correlate timestamps across layers.",
 ["Check proxy and load balancer logs", "Timeouts and health checks", "Crashes or OOM restarts", "Correlate timestamps"],
 ["Only inspects application logs"]),
("LOG", "tradeoff", "medium", "tradeoff", ["Security"],
 "What should you avoid logging in a production web app, and how do you balance log detail against cost?",
 "Avoid secrets and sensitive data: passwords, tokens, full card numbers and unnecessary personal data, which creates security and compliance risk. Balance detail with volume, storage and performance by using appropriate levels, sampling high-volume debug logs, redacting fields and setting retention policies, while keeping enough context to diagnose failures.",
 ["No secrets or PII", "Redaction", "Levels, sampling and retention"],
 ["Logs full request bodies including passwords for debugging"]),
("LOG", "scenario", "medium", "scenario", ["Observability"],
 "JavaScript errors happen in users' browsers but never appear in your server logs. How would you make frontend errors visible and connect them to backend activity?",
 "Add client-side error reporting (window error handlers, React error boundaries) that sends errors to a collection service or endpoint, with release version, user or session ID and the request/correlation ID of recent API calls. This lets you link a frontend failure to the backend trace or logs for the same request.",
 ["Client error reporting", "Error boundaries", "Correlation IDs link frontend and backend"],
 ["Waits for users to report bugs"]),
("LOG", "diagnose", "hard", "debugging", ["Performance"],
 "One endpoint's latency spikes only under load. Logs show some requests taking 8 seconds while the average is 200 ms. How do you find the cause?",
 "Add timing to the logs for each stage (handler, DB queries, external calls) and examine the slow requests' correlation IDs. Typical culprits are database connection pool exhaustion (requests waiting for a connection), slow or unindexed queries under concurrent load, lock contention, N+1 queries, or a slow downstream dependency. Confirm with pool metrics, slow query logs and traces, then fix by tuning the pool, indexing or batching queries, adding timeouts and caching.",
 ["Per-stage timing in logs", "Connection pool exhaustion or lock contention", "Slow query logs and traces", "Targeted fixes"],
 ["Just adds more servers without diagnosis"]),
]
