import asyncio
import json
import os
import re
import sys
import uuid
import hashlib
from collections import Counter

from dotenv import load_dotenv
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
load_dotenv()

BACKEND_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_DIR = os.path.join(BACKEND_DIR, "data")
OUT = os.path.join(DATA_DIR, "interview_question_bank_v2_generated.jsonl")

ROLE = "Frontend Developer"
LEAK = re.compile(r"(generate a question|generate \d+ questions|return only json|phase 4c gap plan|"
                  r"generation batch|candidate generation|system instructions|do not proceed|"
                  r"awaiting authorization|minimum target|generation pipeline|"
                  r"batch \d+ generation|expected answer|strong indicator|weak indicator|as an ai|"
                  r"here is the question|\bprompt text\b)", re.I)

Q = [
    # Data Fetching & Networking
    ("B64_2_1", "diagnose", "hard", "debugging", ["Data Fetching"], "A user quickly types 'apple' into a search bar. The component fires 5 distinct API requests: 'a', 'ap', 'app', 'appl', 'apple'. Even though the server processes 'apple' last, the 'ap' request hits a slow database and returns 2 seconds later. The UI now displays the search results for 'ap' instead of 'apple'. What is this bug and how do you fix it at the network level?", "This is a 'Race Condition' caused by Out-of-Order API responses. The slow request ('ap') overwrote the fast request ('apple') in the component state. To fix this at the network level, you MUST use an `AbortController`. When the user types the next keystroke, you call `controller.abort()` on the previous request BEFORE firing the new one. The browser physically terminates the old HTTP connection, ensuring that the slow 'ap' request can mathematically never resolve and overwrite the final state.", ["Out-of-order network responses overwrite the correct UI state (Race Condition)", "Debouncing reduces requests but does not mathematically prevent race conditions if latencies vary wildly", "Fix: Use `AbortController` to physically cancel the previous HTTP request when a new one begins"], ["The server should just reply faster"]),
    ("B64_2_2", "concept", "medium", "concept", ["Data Fetching"], "What is the 'Stale-While-Revalidate' (SWR) caching strategy, and how does it balance UX with data freshness?", "SWR is a caching strategy (often implemented via HTTP headers or libraries like React Query/SWR). When a user requests data, the browser instantly returns the 'Stale' data from the local cache to provide a zero-latency UI (perfect UX). Simultaneously, in the background, it fires a network request to 'Revalidate' (fetch) the fresh data from the server. Once the fresh data arrives, it silently updates the UI. This eliminates loading spinners while guaranteeing the user eventually sees the most up-to-date information.", ["Instantly returns stale cached data to the UI (zero latency)", "Simultaneously triggers a background network request to fetch fresh data", "Silently updates the UI with the fresh data when the request completes"], ["It means serving stale bread while baking fresh bread"]),
    ("B64_2_3", "implement", "medium", "implement", ["Data Fetching"], "How do you implement 'Request Deduplication' in a large React application where 5 different components on the same page all independently call `fetchUserProfile()` on mount?", "If 5 isolated components call `fetch()` on mount, the browser will fire 5 identical HTTP requests simultaneously, wasting bandwidth and server CPU. To implement Deduplication, you must hoist the caching logic outside the React render cycle (e.g., using a Singleton, React Query, or Apollo). When the first component calls `fetchUserProfile()`, you store the unresolved `Promise` in a global Map (e.g., `cache['user'] = fetch(...)`). When the other 4 components call the function 1 millisecond later, they check the Map, see the pending Promise, and `await` that exact same Promise instead of firing a new `fetch()`. All 5 components resolve simultaneously from a single network request.", ["5 isolated components mounting simultaneously will trigger 5 identical network requests", "Fix: Cache the unresolved `Promise` globally (not just the data)", "Subsequent calls return the exact same pending Promise, ensuring only 1 physical network request fires"], ["You just tell the components to talk to each other"]),
    ("B64_2_4", "tradeoff", "hard", "tradeoff", ["Data Fetching"], "What is the tradeoff of using HTTP `ETag` headers for caching JSON API responses versus purely relying on Client-Side Caching (like Redux/Zustand)?", "Client-side caching completely bypasses the network; it instantly returns data from RAM (0ms latency, 0 network bandwidth). The severe tradeoff is that the client has no way to know if the database mutated 5 minutes ago, leading to infinitely stale data unless manually refreshed. HTTP `ETag` is a server-side hash of the data. The client must still make a network request (`If-None-Match: <hash>`). If the data hasn't changed, the server returns an empty `304 Not Modified` response. The tradeoff is that ETag guarantees 100% data freshness, but you still pay the absolute network latency penalty (e.g., 50ms) to do the round-trip check, preventing instantaneous zero-latency UI renders.", ["Client Cache: 0ms latency but risks infinitely stale data", "ETag: Guarantees freshness and saves payload bandwidth by returning `304 Not Modified`", "Tradeoff: ETag still requires a full network round-trip to validate, meaning it cannot provide zero-latency instantaneous UI updates"], ["ETags are used to tag graffiti on the web"]),
    ("B64_2_5", "scenario", "medium", "scenario", ["Data Fetching"], "Your frontend application uses a standard `fetch()` retry loop. If a request fails, it waits 1 second and retries, up to 5 times. During a massive AWS outage, your API goes down. When the API comes back online, it is instantly crushed and crashes again. Why did the frontend cause this, and how do you fix the retry logic?", "The frontend caused a 'Retry Storm' (Thundering Herd). Because thousands of users were all looping and retrying exactly every 1.0 seconds, their requests synchronized. When the server rebooted, it was hit by 10,000 requests in the exact same millisecond, instantly crashing it again. To fix this, you must implement 'Exponential Backoff' (waiting 1s, 2s, 4s, 8s) AND 'Jitter'. Jitter adds randomized milliseconds to the delay (e.g., `sleep(1000 + Math.random() * 500)`). This mathematically desynchronizes the clients, spreading the retry load out over time and allowing the server to recover safely.", ["Strict retry intervals synchronize thousands of clients into a single massive spike (Thundering Herd)", "This concentrated spike instantly crashes recovering servers", "Fix: Implement Exponential Backoff with 'Jitter' (randomized delay) to desynchronize the clients"], ["The frontend just needs to click the button harder"]),

    # State Management Architecture
    ("B64_2_6", "concept", "hard", "concept", ["State Management"], "In frontend state architecture, what is 'Normalized State' versus 'Nested/Hierarchical State', and why is normalization critical for large-scale applications?", "If you fetch a Twitter feed, the API returns a deeply nested JSON tree: `posts[0].author.name`. If you store it nested in Redux, updating the author's name requires cloning and rebuilding the entire deeply nested tree. Furthermore, if that author appears in 5 different posts, you have 5 duplicate copies of the author in memory; updating one leaves the other 4 stale (Data Inconsistency). 'Normalized State' flattens the data into flat dictionary lookup tables (like a relational database): `usersById: { 1: {...} }, postsById: { 10: { authorId: 1 } }`. This guarantees a single source of truth, prevents stale duplicate data, and makes updates O(1) instead of deep O(N) traversals.", ["Nested state causes massive data duplication and requires expensive deep-cloning to update", "Updating a duplicated entity in a nested tree leaves other copies stale (UI inconsistency)", "Normalization flattens data into lookup tables by ID, ensuring O(1) updates and a Single Source of Truth"], ["Normalized state means the state is feeling normal today"]),
    ("B64_2_7", "diagnose", "medium", "debugging", ["State Management"], "A user clicks 'Like' on a post. The UI instantly turns the heart red. A second later, a network error occurs, but the heart remains red. If the user refreshes, the heart is gray. What architectural pattern was implemented incorrectly?", "The developer implemented 'Optimistic Updates' but failed to implement the 'Rollback' phase. Optimistic UI instantly mutates the client state to provide a snappy, zero-latency experience, assuming the backend request will succeed. However, network requests are inherently volatile. If the `fetch()` fails, the client state is now fundamentally desynchronized from the true database state. To fix this, the developer MUST catch the network error and explicitly revert/rollback the client state to its previous snapshot (turning the heart gray again) and optionally showing an error toast.", ["Optimistic UI mutates client state before the server confirms the mutation", "If the network request fails, the UI is permanently desynchronized from the database", "Fix: The implementation MUST include a failure `catch` block that explicitly rolls back the UI to the previous snapshot"], ["The red color got stuck in the CSS buffer"]),
    ("B64_2_8", "implement", "hard", "implement", ["State Management"], "How do you implement Cross-Tab State Synchronization in a modern browser without relying on constant polling or a heavy WebSocket server?", "If a user has your web app open in Tab A and Tab B, and they change the dark mode setting in Tab A, Tab B must update instantly. You do not need WebSockets or polling for this. You implement the `BroadcastChannel` API. Tab A instantiates `const bc = new BroadcastChannel('app-state')` and calls `bc.postMessage({ theme: 'dark' })`. Tab B listens via `bc.onmessage`. The browser natively and instantly routes the message between the isolated JavaScript environments of the two tabs. Alternatively, if you are persisting to `localStorage`, you can listen to the global `window.addEventListener('storage')` event, which fires across all tabs when local storage mutates.", ["Isolated browser tabs do not share JavaScript memory or state", "Fix: Instantiate a `BroadcastChannel` to natively pass messages between tabs without hitting a server", "Alternative: Use `window.addEventListener('storage')` to sync state changes persisted to `localStorage`"], ["You just ask the user to refresh the other tab"]),
    ("B64_2_9", "tradeoff", "medium", "tradeoff", ["State Management"], "What is the tradeoff of storing global application state (like the current user's profile) in a React Context Provider at the very top of the DOM tree?", "React Context is phenomenal for avoiding prop-drilling, but it is NOT a dedicated state management system. The severe tradeoff is 'Render Cascades'. By architectural definition, whenever the value inside a `Context.Provider` changes, React MUST re-render absolutely every single component in the tree that consumes that Context via `useContext()`. If you store a massive object in Context and update one tiny field, you trigger a massive re-render across the entire application, destroying performance. Dedicated state managers (like Zustand or Redux) solve this by using external stores and atomic selector subscriptions (`useStore(state => state.tinyField)`), bypassing the React Context render cascade entirely.", ["Context triggers a re-render of EVERY consuming component whenever its value reference changes", "Storing large, frequently mutating state in Context causes catastrophic application-wide render cascades", "Tradeoff: Context is easy but lacks atomic selector subscriptions (which Redux/Zustand provide)"], ["Context makes the application read books to understand the state"]),
    ("B64_2_10", "scenario", "hard", "scenario", ["State Management"], "Your application has a complex checkout form. You store `items`, `taxRate`, and `totalPrice` in Redux. Every time an item is added, you dispatch an action to update `items`, and a separate action to update `totalPrice`. Occasionally, the total is completely wrong. What is the architectural flaw here?", "The flaw is storing 'Derived State' in the global store. `totalPrice` is not an independent piece of truth; it is a mathematical derivation of `items * taxRate`. By manually dispatching two separate actions, you created a Race Condition and a Synchronization Nightmare. If the second dispatch fails, or a developer forgets to call it in a new feature, the data is permanently corrupted. You MUST never store derived data in state. You must compute it dynamically on the fly during the render phase (e.g., using a memoized selector like Reselect: `const total = useMemo(() => calculate(items, tax), [items, tax])`).", ["`totalPrice` is Derived State (computable from other state), not independent truth", "Manually synchronizing derived state via multiple dispatches causes race conditions and permanent data corruption", "Fix: Never store derived state. Compute it dynamically on the fly using memoized Selectors"], ["The math library in JavaScript is notoriously bad at addition"]),
    
    # JavaScript Runtime & Execution
    ("B64_2_11", "concept", "hard", "concept", ["JavaScript Runtime"], "Explain the difference between Macrotasks (e.g., `setTimeout`) and Microtasks (e.g., `Promise.then()`) in the JavaScript Event Loop, and why a `while(true)` loop generating Promises will crash the browser but generating `setTimeout`s will not.", "The Event Loop has a strict priority queue. After executing the current call stack, it MUST completely empty the Microtask Queue (Promises, `queueMicrotask`) before it is legally allowed to render the DOM or process the Macrotask Queue (`setTimeout`, user clicks). If a Promise continuously queues another Promise, the Microtask Queue never empties. The Event Loop is permanently trapped in the Microtask phase, starving the rendering pipeline and crashing the tab (Task Starvation). A `setTimeout` queues a Macrotask; the Event Loop will process one Macrotask, update the DOM, and breathe, preventing a browser freeze.", ["Microtasks (Promises) have strict priority; the Event Loop MUST empty them completely before rendering the DOM", "Macrotasks (`setTimeout`) yield control back to the Event Loop after each execution", "An infinite loop of Microtasks starves the Event Loop, preventing DOM rendering and freezing the browser"], ["Macrotasks are for Apple computers, Microtasks are for Microsoft computers"]),
    ("B64_2_12", "diagnose", "medium", "debugging", ["JavaScript Runtime"], "You build a Single Page Application (SPA). Users report that after 4 hours of navigating between routes, the application uses 3GB of RAM and crashes. You take a heap snapshot and find thousands of detached DOM nodes. What caused this memory leak?", "A 'Detached DOM Node' occurs when a JavaScript variable still holds a reference to an HTML element that has been removed from the visible document (`document.body`). In an SPA, when you navigate away from a page, React/Vue destroys the UI components and removes the DOM nodes. However, if you manually attached an event listener to the `window` or `document` (`window.addEventListener('scroll', myNodeFunc)`) and forgot to call `removeEventListener` on component unmount, the global `window` object retains a strong reference to that function, which via closure retains a strong reference to the deleted DOM node, preventing the Garbage Collector from freeing it.", ["A Detached DOM Node is a deleted HTML element that cannot be Garbage Collected because JS still references it", "Global event listeners (`window.addEventListener`) that are not explicitly removed on unmount are the primary cause", "The global listener creates a closure that permanently traps the component's memory"], ["The DOM nodes fell off the tree and got lost in RAM"]),
    ("B64_2_13", "implement", "hard", "implement", ["JavaScript Runtime"], "How do you implement a `WeakMap` to associate private metadata with a 3rd-party DOM element without causing a memory leak when the 3rd-party library deletes the element?", "If you use a standard `Map` to associate data: `map.set(domElement, { clicks: 5 })`, the standard Map holds a 'Strong Reference' to the `domElement`. If the 3rd-party library deletes the element from the DOM, the Garbage Collector sees that your Map still references it, so the memory is never freed (Memory Leak). By using a `WeakMap`, the keys must be Objects (like DOM elements), and the Map holds a 'Weak Reference'. When the 3rd-party library deletes the element and drops its references, the Garbage Collector instantly deletes the element from RAM, and the `WeakMap` automatically and safely removes the entry.", ["Standard `Map` holds strong references to its keys, preventing Garbage Collection of deleted DOM elements", "`WeakMap` keys are weakly held; if no other references exist, the object is Garbage Collected", "The `WeakMap` automatically clears the entry, mathematically preventing memory leaks for associated metadata"], ["You use a WeakMap because the data is not very important"]),
    ("B64_2_14", "tradeoff", "medium", "tradeoff", ["JavaScript Runtime"], "What is the tradeoff of using `structuredClone()` to deep-copy a massive nested JavaScript object versus using `JSON.parse(JSON.stringify(obj))`?", "For a decade, developers used the JSON hack to deep-copy objects. The severe tradeoff of the JSON hack is data destruction: it silently destroys `Date` objects (converting them to strings), completely strips `Set`, `Map`, `RegExp`, and functions, and crashes instantly on Circular References. The modern `structuredClone()` API natively deep-copies objects at the V8 engine level. It perfectly preserves `Date`, `Set`, `Map`, and safely handles Circular References without crashing. The only tradeoff is that `structuredClone()` still cannot clone Functions or DOM nodes (it throws a `DataCloneError`), and it may have slight CPU overhead for extremely trivial objects compared to highly optimized JSON parsers.", ["The JSON hack silently destroys complex types (`Date`, `Map`, `Set`) and crashes on Circular References", "`structuredClone()` perfectly preserves complex data types and handles circular structures natively", "Tradeoff: `structuredClone` strictly throws an error if it encounters a Function or DOM Node, enforcing data purity"], ["structuredClone requires you to build a cloning vat in CSS"]),
    ("B64_2_15", "scenario", "hard", "scenario", ["JavaScript Runtime"], "You use a Web Worker to process a massive 100MB Uint8Array image buffer. You use `worker.postMessage(buffer)`. The main thread freezes for 200ms during the transfer. How do you re-architect this transfer to achieve 0ms main-thread blocking?", "By default, `postMessage` uses the Structured Clone algorithm. It physically allocates a brand new 100MB block of RAM and byte-for-byte copies the entire array into the Worker's memory space. This CPU-intensive copy blocks the main thread. To achieve 0ms transfer, you MUST use 'Transferable Objects'. You invoke it as `worker.postMessage(buffer, [buffer.buffer])`. This executes a zero-copy pointer transfer. The V8 engine instantly strips ownership of the 100MB buffer from the main thread and hands the exact physical RAM address to the Worker. The main thread can no longer read the buffer, but the transfer takes 0 milliseconds.", ["Standard `postMessage` performs a deep byte-for-byte copy (Structured Clone), crushing the CPU for massive arrays", "Fix: Use Transferable Objects (`postMessage(data, [transferables])`)", "This performs a zero-copy pointer transfer, moving memory ownership instantly with 0ms blocking (though the sender loses access)"], ["You just compress the image into a JPEG first"]),

    # UI Architecture
    ("B64_2_16", "concept", "medium", "concept", ["UI Architecture"], "In large-scale UI rendering, what is 'Virtualization' (Windowing), and why is it mandatory for a React list containing 100,000 DOM rows?", "Browsers are inherently limited by DOM node counts. If React attempts to mount 100,000 `<div>` elements into the DOM simultaneously, the browser will consume gigabytes of RAM, the Layout engine will freeze, and the tab will crash. 'Virtualization' (e.g., `react-window` or `react-virtualized`) mathematically calculates the scroll position of the user's viewport. It ONLY renders the 20 DOM nodes that are physically visible on the screen, plus a few buffer rows. As the user scrolls, it recycles those exact same 20 DOM nodes, swapping out the data inside them. This keeps the DOM count permanently at ~20, using almost zero RAM, regardless of whether the dataset has 100 or 1,000,000 items.", ["Browsers crash when attempting to parse and layout hundreds of thousands of DOM nodes", "Virtualization calculates the viewport geometry and ONLY mounts the exact 20 rows currently visible to the user", "As the user scrolls, it dynamically swaps the data inside a fixed number of recycled DOM nodes, guaranteeing O(1) DOM memory"], ["Virtualization is when you put on a VR headset to view the list"]),
    ("B64_2_17", "diagnose", "hard", "debugging", ["UI Architecture"], "You have a massive React form with 500 controlled text inputs. Every time the user types a single character into one input, the entire page freezes for 300ms. Why is typing causing catastrophic lag, and how do you architect the form to fix it?", "In a standard 'Controlled Component', typing a character triggers `onChange`, which calls `setState` at the very top of the form hierarchy. This forces React to deeply re-render all 500 inputs on every single keystroke, destroying the CPU. To fix this, you must localize the state. Either use 'Uncontrolled Components' (using `ref` to read the values only upon final form submission), OR isolate the state into 500 independent, tiny leaf components. If you use a library like `react-hook-form`, it defaults to uncontrolled inputs and explicitly avoids re-rendering the entire parent form during typing, guaranteeing 60FPS input response.", ["Lifting controlled state to the top of a massive form forces React to re-render hundreds of inputs per keystroke", "Virtual DOM diffing 500 inputs 60 times a second crushes the CPU", "Fix: Use Uncontrolled Inputs (`refs`), or specialized libraries (`react-hook-form`) that bypass parent re-renders"], ["The keyboard drivers are incompatible with React"]),

    # Accessibility (A11y)
    ("B64_2_18", "implement", "medium", "implement", ["Accessibility"], "How do you correctly implement 'Focus Trapping' inside a custom React Modal dialog, and why is it a critical accessibility requirement?", "When a custom Modal opens, sighted users see the background darken. However, a blind user navigating via the 'Tab' key can easily Tab *out* of the modal and start interacting with hidden links in the darkened background, causing severe confusion. 'Focus Trapping' is a JavaScript architectural requirement. When the modal opens, you must use JS to forcefully move the browser's focus (`element.focus()`) into the first input of the modal. Furthermore, you must intercept the `keydown` event. If the user presses 'Tab' on the last element of the modal, you must explicitly route the focus back to the *first* element of the modal, mathematically trapping them inside until they hit 'Escape' or close it.", ["Without trapping, keyboard/screen-reader users will Tab out of the modal into the disabled background DOM", "Fix 1: Instantly move `element.focus()` into the modal upon opening", "Fix 2: Intercept the 'Tab' keydown event to loop focus from the last element back to the first element"], ["Focus trapping means forcing the user to stare at the screen without blinking"]),
    ("B64_2_19", "tradeoff", "hard", "tradeoff", ["Accessibility"], "What is the accessibility tradeoff of using `aria-live=\"assertive\"` versus `aria-live=\"polite\"` for dynamic UI updates (like toast notifications)?", "When a DOM element is marked with an `aria-live` region, the browser instructs the Screen Reader to announce any text changes inside it. `aria-live=\"assertive\"` is violently aggressive. It instantly interrupts and talks over whatever the Screen Reader was currently saying. This should ONLY be used for critical, life-saving errors (e.g., 'Session expired in 10 seconds'). `aria-live=\"polite\"` is respectful. It queues the notification in the Screen Reader's buffer, waiting until the user finishes reading their current paragraph before announcing the update. The tradeoff is urgency versus user disruption. Overusing `assertive` makes an application completely unusable for a blind user.", ["`aria-live` regions instruct screen readers to announce dynamic DOM text changes", "`assertive` instantly interrupts the user, violently cutting off current audio (use only for critical errors)", "Tradeoff: `polite` queues the message respectfully, preventing audio collisions but delaying the notification"], ["Polite asks for permission to speak, assertive just yells"]),
    ("B64_2_20", "scenario", "medium", "scenario", ["Accessibility"], "You build a beautiful Single Page Application (SPA) using React Router. When a sighted user clicks 'About', the page transitions instantly. When a blind screen-reader user clicks 'About', the screen reader remains completely silent and they have no idea the page changed. Why, and how do you fix this architecture?", "In a traditional Multi-Page Application (MPA), clicking a link causes a hard HTTP page reload. The browser natively forces the Screen Reader to announce the new `<title>` of the document. In a React SPA, the browser never actually reloads; JavaScript merely hot-swaps DOM nodes silently. The Screen Reader has absolutely no idea a 'Navigation' occurred. To fix this, your SPA architecture MUST include an Accessibility Route Announcer. On every route change, you must update the document `<title>`, and crucially, inject text like 'Navigated to About Page' into a visually-hidden `aria-live=\"polite\"` DOM node, forcing the Screen Reader to explicitly announce the successful navigation.", ["SPAs bypass native browser navigation, meaning Screen Readers are never natively informed of page changes", "Visually the page changes, but the blind user receives zero audio feedback", "Fix: Inject 'Navigated to X' into an `aria-live` region on every route change, and explicitly move `.focus()` to the new page header"], ["The screen reader doesn't understand JavaScript"]),
    ("B64_2_21", "concept", "medium", "concept", ["Accessibility"], "Why is setting `outline: none` in CSS considered one of the most destructive accessibility anti-patterns, and what is the modern solution using `:focus-visible`?", "Browsers natively provide a blue/black focus ring (`outline`) around interactive elements when a user Tabs to them. Designers hate this ring because it appears when mouse users click buttons. If a developer uses `button { outline: none; }`, they completely destroy the UI for Keyboard-Only users, who now have absolutely no visual indicator of where they are on the page. The modern architectural fix is `:focus-visible`. This CSS pseudo-class uses browser heuristics to ONLY show the outline if the user is navigating via Keyboard. If they click with a Mouse, the outline remains hidden, satisfying both designers and accessibility laws.", ["`outline: none` destroys the focus ring, making keyboard navigation mathematically impossible to track visually", "Designers do this to hide rings from mouse clicks, but it violates WCAG laws", "Fix: Use `:focus-visible` which intelligently shows rings ONLY for keyboard users, hiding them for mouse users"], ["Outline none removes the borders from tables"])
]

def run_batch():
    # Load all existing records to do deduplication
    with open(OUT, "r", encoding="utf-8") as f:
        existing = [json.loads(line) for line in f if line.strip()]

    print(f"Loaded {len(existing)} existing records.")
    
    for q in Q:
        if LEAK.search(q[5]) or LEAK.search(q[6]):
            print(f"PROMPT LEAK DETECTED in: {q[5]}")
            sys.exit(1)
            
    existing_texts = [ex["question"] for ex in existing]
    new_texts = [q[5] for q in Q]
    
    vec = TfidfVectorizer(stop_words="english", ngram_range=(1,2))
    all_texts = existing_texts + new_texts
    vec.fit(all_texts)
    
    existing_vecs = vec.transform(existing_texts)
    new_vecs = vec.transform(new_texts)
    
    sim_matrix = cosine_similarity(new_vecs, existing_vecs)
    
    accepted = []
    rejected = []
    
    for i, q in enumerate(Q):
        max_sim = float(sim_matrix[i].max()) if sim_matrix.shape[1] > 0 else 0
        if max_sim > 0.85:
            print(f"REJECTED (Sim: {max_sim:.2f}): {q[5][:50]}...")
            rejected.append(q)
        else:
            accepted.append(q)
            
    print(f"Accepted {len(accepted)} / {len(Q)} questions (Part 2).")
    
    new_records = []
    for q in accepted:
        rec = {
            "primary_role": ROLE,
            "applicable_roles": ["Frontend Engineer", "Software Engineer"],
            "primary_skill": q[4][0],
            "secondary_skills": q[4][1:] if len(q[4]) > 1 else [],
            "technology": "Frontend",
            "topic": q[4][0] if len(q[4]) > 0 else "General",
            "category": "Software Engineering",
            "intent": q[1],
            "difficulty": q[2],
            "question_type": q[3],
            "question": q[5],
            "expected_answer": q[6],
            "evaluation_rubric": {
                "strong_indicators": q[7],
                "weak_indicators": q[8]
            },
            "id": str(uuid.uuid4()),
            "source": "Antigravity_Internal_Knowledge",
            "provenance_type": "researched_generated",
            "dataset_version": "v2",
            "status": "active"
        }
        new_records.append(rec)
        
    with open(OUT, "a", encoding="utf-8") as f:
        for r in new_records:
            f.write(json.dumps(r) + "\n")
            
    # Final audit reporting
    with open(OUT, "r", encoding="utf-8") as f:
        final_existing = [json.loads(line) for line in f if line.strip()]
        
    role_counts = Counter(r["primary_role"] for r in final_existing)
    
    print("\n========================================")
    print("POST-BATCH AUDIT")
    print("========================================")
    print(f"Batch: 64")
    print(f"Target role: {ROLE}")
    print(f"Attempted: {len(Q)}")
    print(f"Accepted: {len(accepted)}")
    print(f"Rejected: {len(rejected)}")
    print(f"Replacement count: 0")
    print(f"Cumulative total: {len(final_existing)}")
    print(f"{ROLE} total: {role_counts[ROLE]}")

if __name__ == "__main__":
    run_batch()
