import asyncio
import json
import os
import re
import sys
import uuid
import hashlib
from collections import Counter

from dotenv import load_dotenv
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
load_dotenv()

BACKEND_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_DIR = os.path.join(BACKEND_DIR, "data")
OUT = os.path.join(DATA_DIR, "interview_question_bank_v2_generated.jsonl")

ROLE = "Python Developer"
LEAK = re.compile(r"(generate a question|generate \d+ questions|return only json|phase 4c gap plan|"
                  r"generation batch|candidate generation|system prompts|do not proceed|"
                  r"awaiting authorization|minimum target|generation pipeline|"
                  r"batch \d+ generation|expected answer|strong indicator|weak indicator|as an ai|"
                  r"here is the question|\bprompt text\b)", re.I)

Q = [
    # Area 1: Typing Internals (Protocols, Generics)
    ("B53_1", "explain", "medium", "concept", ["Typing"], "In Python's `typing` module, what is the fundamental difference between Nominal Subtyping (inheritance) and Structural Subtyping (`Protocol`)?", "Nominal subtyping means a class must explicitly inherit from a base class (e.g., `class MyList(List):`) to be considered a valid subtype by the type checker. Structural subtyping (using `typing.Protocol`) implements 'duck typing' statically. A class is considered a valid subtype of a Protocol as long as it implements the required methods and attributes defined in the Protocol, even if it does not explicitly inherit from it.", ["Nominal requires explicit inheritance from a base class", "Structural (Protocol) only requires implementing the correct methods (static duck typing)", "Protocol allows type checking without forcing rigid class hierarchies"], ["Protocols are for network ports"]),
    ("B53_1", "scenario", "hard", "scenario", ["Typing"], "You define a generic function `def get_first(items: list[T]) -> T:`. If you pass a `list[int]` to this function, it returns an `int`. How does the type checker (like mypy) resolve `T` at static analysis time, and does this exist at runtime?", "The type checker resolves `T` via Type Inference during static analysis. It inspects the AST, sees the argument is `list[int]`, binds the `TypeVar('T')` to `int`, and deduces the return type is `int`. At runtime, due to Type Erasure, `T` completely ceases to exist. The Python interpreter ignores the type hints, and the function simply takes a list and returns the first element, regardless of type.", ["Mypy resolves T via static Type Inference during AST analysis", "At runtime, Type Erasure occurs; the hints are ignored", "T does not enforce anything at runtime"], ["The interpreter compiles T into C code"]),
    ("B53_1", "tradeoff", "hard", "tradeoff", ["Typing"], "What is the tradeoff of using `Any` versus using a `TypeVar` (Generics) when writing a utility function like an identity function `def return_self(x): return x`?", "If you annotate it as `def return_self(x: Any) -> Any:`, you completely disable type checking for that function; if you pass a string, the type checker thinks the result could be literally anything, losing all autocompletion and safety downstream. If you use a `TypeVar` (`def return_self(x: T) -> T:`), the type checker strictly binds the input type to the output type. Passing a string guarantees the output is checked as a string, preserving type safety.", ["`Any` disables type checking entirely, losing downstream safety", "`TypeVar` (Generics) binds the input type to the output type", "Generics preserve type safety and IDE autocompletion"], ["TypeVar makes the function slower"]),
    ("B53_1", "diagnose", "medium", "debugging", ["Typing"], "A developer annotates a variable as `my_list: tuple[int] = (1, 2, 3)`. The mypy type checker immediately throws an error, but the code runs perfectly. Why is mypy complaining?", "In Python typing, `tuple[int]` specifically means a tuple with exactly ONE element, which must be an integer. Because the assigned value `(1, 2, 3)` has three elements, mypy flags a length mismatch. To specify a tuple of variable length containing only integers, the correct annotation is `tuple[int, ...]`. The code runs fine because Python ignores type hints at runtime.", ["`tuple[int]` means a tuple of exactly length 1", "To type a variable-length tuple, use `tuple[int, ...]`", "Mypy checks static types; runtime ignores them"], ["Tuples cannot hold integers"]),
    ("B53_1", "concept", "hard", "concept", ["Typing"], "Explain the difference between `Sequence` and `Iterable` in Python's typing system.", "An `Iterable` is any object that implements `__iter__` (e.g., a generator, a file object). It can be consumed exactly once and doesn't necessarily know its length. A `Sequence` is a more specific protocol that inherits from `Iterable` and `Sized`. It must additionally implement `__getitem__` and `__len__` (e.g., a list or a tuple). You can index into a `Sequence` (e.g., `seq[3]`), but you cannot index into a generic `Iterable`.", ["Iterable only requires `__iter__` (can be consumed once, like generators)", "Sequence requires `__iter__`, `__len__`, and `__getitem__` (allows indexing)", "All Sequences are Iterables, but not all Iterables are Sequences"], ["Sequences are for databases"]),
    ("B53_1", "implement", "medium", "implement", ["Typing"], "How do you use `typing.Literal` to restrict a function argument to a specific set of string values without using an Enum?", "`typing.Literal` allows you to specify exact, literal values that a variable can hold. You implement it by annotating the argument: `def set_mode(mode: Literal['read', 'write', 'append']):`. If a developer attempts to call `set_mode('delete')`, the static type checker will flag an error because 'delete' is not in the allowed literal set. It provides Enum-like static safety without the runtime overhead of an actual Enum class.", ["Use `Literal['value1', 'value2']` in the type hint", "Mypy will reject any value not explicitly listed in the Literal", "Provides static safety without creating an Enum class"], ["Literal is a string casting function"]),
    ("B53_1", "architecture", "hard", "architecture", ["Typing"], "What is 'Covariance' in Python's typing system, and why is `list` invariant but `Sequence` is covariant?", "Covariance means that if `Dog` is a subclass of `Animal`, then `Container[Dog]` is a valid subtype of `Container[Animal]`. `Sequence` is covariant because it is read-only; if you expect a sequence of Animals, passing a sequence of Dogs is perfectly safe because you can only read them. However, `list` is mutable (invariant). If you pass a `list[Dog]` to a function expecting `list[Animal]`, the function might append a `Cat` to the list. When the function returns, the original `list[Dog]` now contains a `Cat`, causing runtime crashes. Thus, mutable containers must be invariant.", ["Covariance: Container[Child] is a subtype of Container[Parent]", "Sequence is covariant because it is strictly read-only", "list is invariant because it is mutable; allowing covariance would let you append invalid types (Cats to a Dog list)"], ["Covariance is about virus transmission"]),
    ("B53_1", "diagnose", "medium", "debugging", ["Typing"], "You write `def get_user(id: int) -> User:` but sometimes the user doesn't exist, so you `return None`. Mypy flags this as an error. Why, and what is the modern Python 3.10+ way to fix it?", "Mypy flags it because returning `None` violates the strict `-> User` contract. You must explicitly declare that the function can return nothing. Prior to 3.10, this was done using `Optional[User]` or `Union[User, None]`. In Python 3.10+, the modern syntax uses the bitwise OR operator for type unions: `def get_user(id: int) -> User | None:`. This forces the caller to explicitly check for `None` before using the returned object.", ["Returning None violates a strict return type", "Modern fix: Use the union operator `User | None`", "Forces the caller to handle the None case statically"], ["Return a string 'None' instead"]),
    ("B53_1", "concept", "easy", "concept", ["Typing"], "What does the `typing.Callable` hint represent, and how do you annotate a function that takes an integer and returns a string?", "`Callable` represents a function, method, or any object that implements `__call__`. To annotate a function that takes an integer and returns a string, you use the syntax `Callable[[int], str]`. The first bracketed list defines the argument types, and the second part defines the return type.", ["Represents anything that can be called (functions/methods)", "Syntax is `Callable[[ArgType1, ArgType2], ReturnType]`", "Example: `Callable[[int], str]`"], ["Callable is a boolean flag for phone numbers"]),
    ("B53_1", "tradeoff", "medium", "tradeoff", ["Typing"], "What is the purpose of `if typing.TYPE_CHECKING:` in a Python module, and what tradeoff does it solve?", "When a module has circular imports solely for type hinting (e.g., Module A imports Class B for a type hint, and Module B imports Class A), the runtime interpreter will crash with an ImportError. `typing.TYPE_CHECKING` is a boolean flag that is `True` during static analysis (mypy) but strictly `False` at runtime. By placing the type imports inside this block and using stringified hints (or `from __future__ import annotations`), you resolve the static type checking needs without breaking the runtime import graph.", ["Solves circular import errors caused by type hinting", "`TYPE_CHECKING` is True during mypy, False at runtime", "Allows type checkers to see the imports without crashing the interpreter"], ["It makes the code compile to C"]),

    # Area 2: Advanced Context Managers & Resource Management
    ("B53_2", "concept", "medium", "concept", ["Resource Management"], "How does a Python Context Manager (`with` statement) guarantee resource cleanup even if a severe exception (like `KeyboardInterrupt`) occurs?", "A Context Manager relies on the `__enter__` and `__exit__` dunder methods. When the `with` block is entered, `__enter__` is executed. The Python interpreter strictly guarantees that `__exit__` will be executed when the block terminates, regardless of whether it finishes normally, returns early, or raises an exception. The exception details (type, value, traceback) are passed to `__exit__`, allowing it to cleanly close files, release locks, or rollback transactions before the exception propagates.", ["Relies on `__enter__` and `__exit__` dunder methods", "Interpreter guarantees `__exit__` execution even on unhandled exceptions", "Exception details are passed to `__exit__` for clean teardown"], ["It uses a try-catch block internally but only for syntax errors"]),
    ("B53_2", "implement", "medium", "implement", ["Resource Management"], "How can you suppress a specific exception from propagating outside a `with` block using the `__exit__` method?", "If the `__exit__(self, exc_type, exc_val, exc_tb)` method returns a truthy value (e.g., `True`), the Python interpreter assumes the exception has been fully handled within the context manager and suppresses it, preventing it from propagating up the call stack. If it returns `False` or `None`, the exception propagates normally. You can inspect `exc_type` to selectively return `True` only for specific errors you wish to swallow.", ["Return `True` from the `__exit__` method", "Returning a truthy value tells the interpreter the exception was handled", "Check `exc_type` to selectively suppress specific errors"], ["Use the `del` keyword on the exception object"]),
    ("B53_2", "architecture", "hard", "architecture", ["Resource Management"], "Explain how `@contextlib.contextmanager` transforms a standard generator function into a fully functional Context Manager.", "The `@contextmanager` decorator wraps a generator that `yield`s exactly once. The code before the `yield` acts as the `__enter__` logic. The value yielded is bound to the `as` variable. The decorator catches any exceptions raised in the `with` block and injects them back into the generator at the `yield` point (using `generator.throw()`). The code after the `yield` (usually inside a `finally` block) acts as the `__exit__` logic, executing the cleanup.", ["Uses a generator that yields exactly once", "Code before `yield` is `__enter__`, code after is `__exit__`", "Exceptions are injected back into the generator via `generator.throw()`"], ["It compiles the function into a class via metaclasses"]),
    ("B53_2", "diagnose", "hard", "debugging", ["Resource Management"], "You use `@contextlib.contextmanager` to open a database connection. Inside the `with` block, the application throws a `ValueError`. The database connection remains permanently open, exhausting the pool. What flaw exists in the generator function?", "The developer likely placed the cleanup code after the `yield` but forgot to wrap the `yield` in a `try...finally` block. When the `ValueError` occurs in the `with` block, the decorator throws the exception back into the generator at the `yield` line. Without a `try...finally` block to catch it, the generator itself crashes instantly, completely skipping the database closure code located below the `yield`.", ["Cleanup code was not placed inside a `finally` block", "Exceptions thrown into the `yield` cause the generator to crash", "Crashing skips all subsequent cleanup code"], ["The database server crashed"]),
    ("B53_2", "tradeoff", "medium", "tradeoff", ["Resource Management"], "What is the tradeoff of using a class-based context manager (`__enter__`/`__exit__`) versus the `@contextmanager` generator decorator?", "The `@contextmanager` decorator is much faster to write, highly readable, and keeps setup and teardown logic visually adjacent in a single function, but it cannot easily store complex state across multiple method calls. A class-based context manager requires more boilerplate, but because it instantiates a full object, it is vastly superior for maintaining complex state, executing helper methods within the `with` block, or implementing highly reusable inheritance hierarchies.", ["Decorator is concise and readable, grouping setup/teardown", "Class-based requires boilerplate but allows complex state management", "Class-based is better for helper methods and inheritance"], ["Decorator uses more memory than classes"]),
    ("B53_2", "scenario", "medium", "scenario", ["Resource Management"], "You have three nested context managers: opening a file, acquiring a lock, and starting a transaction. Writing `with A: with B: with C:` causes deep indentation (arrow code). How do you resolve this cleanly in Python 3?", "You can combine them into a single `with` statement separated by commas: `with open_file() as f, acquire_lock() as l, transaction() as t:`. Alternatively, if the number of context managers is dynamic (e.g., a list of varying locks), you can use `contextlib.ExitStack`. `ExitStack.enter_context()` allows you to programmatically enter an arbitrary number of context managers, and guarantees they will all be cleanly exited in reverse order.", ["Use comma-separated context managers in a single `with` statement", "Use `contextlib.ExitStack` for a dynamic/variable number of managers", "ExitStack guarantees cleanup in reverse order"], ["Use global variables to store the locks"]),
    ("B53_2", "concept", "hard", "concept", ["Resource Management"], "What happens if a Context Manager's `__enter__` method itself raises an exception? Does the `__exit__` method execute?", "No, the `__exit__` method will absolutely NOT execute. The Python interpreter only guarantees the execution of `__exit__` if the `__enter__` method completes successfully and returns control to the `with` block. If `__enter__` crashes (e.g., a file cannot be found or a lock times out), the context was never fully established, so teardown is entirely skipped and the exception propagates immediately.", ["`__exit__` does NOT execute if `__enter__` raises an exception", "Teardown is only guaranteed if setup succeeds completely", "Exception propagates immediately without entering the `with` block"], ["Yes, __exit__ always runs no matter what"]),
    ("B53_2", "implement", "medium", "implement", ["Resource Management"], "How do you implement an asynchronous context manager for use with `async with`?", "You must implement the asynchronous dunder methods `__aenter__` and `__aexit__`. These methods must be defined as `async def`, allowing you to `await` asynchronous operations (like establishing a database connection or waiting for a network socket) during the setup and teardown phases. Alternatively, you can use the `@contextlib.asynccontextmanager` decorator on an asynchronous generator function.", ["Implement `__aenter__` and `__aexit__` as `async def` methods", "Allows using `await` for I/O during setup and teardown", "Can also use `@contextlib.asynccontextmanager`"], ["Add the word async to the standard __enter__ method"]),
    ("B53_2", "diagnose", "easy", "debugging", ["Resource Management"], "A junior developer writes `with open('file.txt', 'w'):` without the `as f` binding, and then attempts to write to the file using a globally scoped file object. Why is this bad practice?", "The `as` clause binds the resource returned by `__enter__` (the file object) to a local variable. By omitting it and relying on a global, the code loses track of the specific resource being managed. While the `with` block will still close the file anonymously at the end, the developer cannot safely write to the file within the block without the explicit reference, leading to potential variable shadowing or writing to a closed/wrong file.", ["The `as` keyword binds the managed resource to a local variable", "Omitting it means you cannot safely interact with the specific resource being managed", "Leads to global variable pollution and bug-prone references"], ["It causes a syntax error"]),
    ("B53_2", "tradeoff", "hard", "tradeoff", ["Resource Management"], "What is the tradeoff of relying on the `__del__` method (finalizer) for resource cleanup instead of a Context Manager?", "Relying on `__del__` is highly dangerous and unpredictable. The `__del__` method is only called when the Garbage Collector destroys the object. Because Python's GC timing is non-deterministic (especially with reference cycles), the object might be kept alive indefinitely, leaving files open or database connections leased for hours. A Context Manager (`with`) provides strict, deterministic execution—cleanup happens instantaneously the millisecond the block ends, ensuring immediate resource release.", ["`__del__` is non-deterministic and relies on the Garbage Collector", "Object might stay alive indefinitely due to reference cycles, leaking resources", "Context Managers provide strict, deterministic, immediate cleanup"], ["__del__ deletes the actual file from the hard drive"]),

    # Area 3: Packaging, Wheels & Dependency Isolation
    ("B53_3", "concept", "medium", "concept", ["Packaging"], "What is the fundamental difference between an `sdist` (Source Distribution) and a `bdist_wheel` (Wheel) in Python packaging?", "An `sdist` is an archive (usually a `.tar.gz`) containing the raw source code and build instructions (`setup.py` or `pyproject.toml`). When `pip` installs an sdist, it must locally compile any C extensions on the user's machine. A Wheel (`.whl`) is a pre-compiled, built binary distribution. It contains the pre-compiled `.so` or `.pyd` binaries for a specific architecture. `pip` simply unzips the Wheel into the site-packages directory, making installation vastly faster and eliminating the need for a local C compiler.", ["`sdist` contains raw source code and requires local compilation", "Wheel is a pre-compiled binary distribution", "Wheels install much faster and do not require the user to have a C compiler"], ["sdist is for Windows, wheel is for Linux"]),
    ("B53_3", "architecture", "hard", "architecture", ["Packaging"], "Explain the role of PEP 517 and `pyproject.toml` in modern Python packaging compared to the legacy `setup.py`.", "Historically, installing a package meant explicitly executing `python setup.py install`, which forced the entire ecosystem to depend entirely on `setuptools` being installed beforehand. PEP 517 decoupled the build frontend (pip) from the build backend (setuptools, poetry, flit). The `pyproject.toml` file explicitly declares *which* backend the package uses. `pip` reads this, provisions an isolated temporary environment, installs the requested backend, and tells the backend to build the Wheel, standardizing the build process across entirely different packaging tools.", ["PEP 517 decouples the build frontend (pip) from the backend (setuptools/poetry)", "`pyproject.toml` declares the specific build system required", "Pip provisions an isolated environment to build the package, standardizing the ecosystem"], ["setup.py is written in Python, pyproject.toml is written in C"]),
    ("B53_3", "diagnose", "medium", "debugging", ["Packaging"], "A developer successfully installs a package using `pip install pandas`, but when they run their script using `python script.py`, they get `ModuleNotFoundError: No module named 'pandas'`. What environment isolation issue causes this?", "This is caused by Python executable mismatch (virtual environment confusion). The `pip` executable the developer ran belongs to a different Python environment (e.g., the global system Python or a conda env) than the `python` executable used to run the script (e.g., an active virtualenv). The package was installed successfully, but into a completely different `site-packages` directory. Fixing it requires running `python -m pip install pandas` using the exact same python executable.", ["Mismatch between the `pip` executable and the `python` executable", "Package was installed into a different environment's `site-packages`", "Fix by activating the correct virtualenv or using `python -m pip`"], ["Pandas deleted itself after installation"]),
    ("B53_3", "tradeoff", "hard", "tradeoff", ["Packaging"], "What is the tradeoff of strictly pinning exact dependency versions (e.g., `requests==2.28.1`) in a library's `setup.py` versus in an application's `requirements.txt`?", "Pinning exact versions is critical for an *Application* (`requirements.txt` or `Pipfile.lock`) to guarantee reproducible, deterministic deployments in production. However, pinning exact versions in a *Library* (`setup.py` / `pyproject.toml` dependencies) is an anti-pattern. If a library pins `requests==2.28.1`, it creates severe dependency conflicts (Dependency Hell) for any downstream user whose application also relies on a slightly different version of `requests`. Libraries should use broad, permissive version ranges (e.g., `requests>=2.0,<3.0`).", ["Applications should strictly pin versions for reproducible deployments (lock files)", "Libraries should use broad, permissive ranges to prevent dependency conflicts", "Pinning in a library causes 'Dependency Hell' for downstream users"], ["Pinning uses more disk space"]),
    ("B53_3", "scenario", "hard", "scenario", ["Packaging"], "You build a Wheel containing a C extension on an Ubuntu 22.04 machine and upload it to an internal PyPI. Developers on CentOS 7 try to install it and get massive GLIBC version mismatch crashes. How do you package C extensions so they work across all Linux distributions?", "You must compile the Wheel using the `manylinux` standard. `manylinux` is a highly constrained Docker image based on a very old, stable version of CentOS with an ancient version of GLIBC. Because GLIBC is backward-compatible but not forward-compatible, compiling the C extension against the ancient GLIBC guarantees that the resulting binary will execute flawlessly on almost all modern Linux distributions (Ubuntu, Alpine, RHEL) without crashing.", ["Compile using the `manylinux` standard Docker image", "`manylinux` uses an old, stable version of GLIBC", "GLIBC is backward-compatible, ensuring the binary works on modern distros"], ["Copy the C compiler to the CentOS machine"]),
    ("B53_3", "concept", "medium", "concept", ["Packaging"], "How does a Python Virtual Environment (`venv`) actually isolate dependencies without running a full virtual machine or container?", "A `venv` is essentially just a directory structure and a shell trick. When created, it copies or symlinks the Python interpreter into the `venv/bin` folder and creates an empty `site-packages` folder. When you 'activate' the venv, it merely prepends the `venv/bin` path to your shell's `$PATH` environment variable. When you type `python` or `pip`, the OS finds the venv's interpreter first. That interpreter is configured to exclusively use its own local `site-packages` directory, isolating it from the global system.", ["Prepend the venv's `bin` directory to the `$PATH` environment variable", "The venv contains a symlinked Python interpreter", "The interpreter relies exclusively on its local `site-packages` directory"], ["It runs a tiny Docker container in the background"]),
    ("B53_3", "architecture", "medium", "architecture", ["Packaging"], "What architectural problem does a tool like `Poetry` or `uv` solve over using raw `pip` and `requirements.txt`?", "Raw `pip` and `requirements.txt` lack a standardized dependency resolver lockfile. If you specify `Flask`, `pip` installs Flask and its sub-dependencies blindly. Next month, a sub-dependency updates and breaks your app, because `requirements.txt` didn't track the full sub-dependency tree. `Poetry` and `uv` implement a deterministic dependency resolver and generate a strict lockfile (`poetry.lock` / `uv.lock`). This lockfile mathematically guarantees that every developer and production server installs the exact same cryptographic hashes of the entire nested dependency tree.", ["Solves non-deterministic sub-dependency updates", "Generates a strict lockfile mathematically guaranteeing exact versions and hashes", "Provides a robust dependency resolver to prevent conflicting packages"], ["They make Python run multithreaded"]),
    ("B53_3", "diagnose", "hard", "debugging", ["Packaging"], "You try to install a package via `pip install my-internal-lib` from a private corporate repository. It fails with `SSL: CERTIFICATE_VERIFY_FAILED`. You know your corporate network uses a Deep Packet Inspection (DPI) firewall. How do you resolve this?", "The corporate DPI firewall intercepts TLS traffic by injecting its own internal root CA certificate, acting as a Man-In-The-Middle. `pip` uses its own bundled `certifi` trust store and does not automatically trust the OS-level keychain, so it rejects the corporate cert as invalid. You must explicitly configure `pip` to trust the corporate CA certificate by setting the `PIP_CERT` environment variable to the path of the corporate `.pem` file, or using `--cert <path>`.", ["Corporate DPI firewalls inject an internal CA certificate (MITM)", "`pip` uses its own trust store (`certifi`) and rejects the unknown CA", "Fix by passing the corporate CA cert path to `PIP_CERT` or `--cert`"], ["The internet is disconnected"]),
    ("B53_3", "explain", "easy", "explain", ["Packaging"], "What is the purpose of the `__init__.py` file in a Python directory?", "Historically (Python 2), an empty `__init__.py` file was strictly required to tell the Python interpreter that a directory should be treated as an importable module/package. In modern Python 3, Namespace Packages make it technically optional, but it is still widely used to define the public API of a package (using `__all__`), execute initialization code when the package is imported, or simply to ensure backward compatibility with older tools.", ["Marks a directory as a Python package", "Executes initialization code when the package is imported", "Defines the public API using `__all__`"], ["It compiles the python code to binary"]),
    ("B53_3", "tradeoff", "medium", "tradeoff", ["Packaging"], "What is the tradeoff of using a Monorepo for multiple Python packages versus multi-repo (one repo per package) regarding dependency management?", "In a multi-repo, each package handles its own dependencies independently, making CI/CD simple, but ensuring version compatibility across the entire ecosystem is a nightmare. In a Monorepo, you can enforce a single, unified lockfile (using tools like Bazel, Pants, or Poetry Workspaces) ensuring all internal packages perfectly interoperate with the exact same third-party dependency versions. However, the tradeoff is massive CI complexity: tooling must intelligently cache and only rebuild/test the specific packages affected by a commit.", ["Multi-repo: Simple CI, but dependency compatibility across packages is a nightmare", "Monorepo: Enforces unified dependency versions guaranteeing interoperability", "Monorepo tradeoff: Requires massive CI complexity (selective testing/building)"], ["Monorepo uses more RAM in PyCharm"]),

    # Area 4: Asyncio Cancellation & Structured Concurrency
    ("B53_4", "concept", "hard", "concept", ["Asyncio"], "How exactly does task cancellation work under the hood in Python's `asyncio`?", "Task cancellation is not a violent thread kill. When `task.cancel()` is called, the Event Loop schedules an `asyncio.CancelledError` exception to be injected into the coroutine at the exact point it is currently suspended (at an `await` statement). When the coroutine resumes, the exception is raised internally. The coroutine can catch this exception (via `try...except CancelledError`) to perform cleanup, but it must generally re-raise it to formally terminate the task.", ["Cancellation is not a hard kill; it is an exception injection", "Event loop throws `asyncio.CancelledError` into the coroutine at the current `await`", "Coroutine can catch it for cleanup but should usually re-raise it"], ["It kills the physical CPU thread instantly"]),
    ("B53_4", "diagnose", "hard", "debugging", ["Asyncio"], "You trigger `task.cancel()`, but the task continues running indefinitely, completely ignoring the cancellation request. The task contains a heavy `while True:` loop. Why did cancellation fail?", "The task is CPU-bound and lacks a yield point. `asyncio` is cooperatively scheduled. A task can ONLY be cancelled if it yields control back to the event loop via an `await` statement. If the `while True:` loop contains only synchronous, blocking CPU calculations (or a `time.sleep()`), the event loop is entirely blocked. The `CancelledError` can never be injected because the coroutine never suspends. You must use `await asyncio.sleep(0)` or offload the math to an executor.", ["`asyncio` is cooperatively scheduled; tasks must yield to be cancelled", "The CPU-bound loop lacks an `await` statement, blocking the event loop entirely", "CancelledError cannot be injected unless the task is suspended"], ["Cancel doesn't work on Tuesdays"]),
    ("B53_4", "architecture", "medium", "architecture", ["Asyncio"], "What is 'Structured Concurrency', and how do Python 3.11+ `TaskGroups` implement it?", "Structured Concurrency ensures that the lifetimes of concurrent tasks are strictly bound to a specific lexical scope (like a context manager). Without it, spawned background tasks can become 'orphaned' and leak. Python 3.11 `asyncio.TaskGroup` implements this: `async with asyncio.TaskGroup() as tg: tg.create_task(...)`. The `with` block will strictly wait for ALL child tasks to complete. If any child task crashes, the TaskGroup automatically cancels all other sibling tasks, ensuring no dangling coroutines are left behind.", ["Binds the lifetime of concurrent tasks to a strict lexical scope (a block)", "Prevents 'orphaned' dangling background tasks", "If one child crashes, `TaskGroup` cancels all siblings automatically"], ["It structures the code using alphabetical order"]),
    ("B53_4", "implement", "medium", "implement", ["Asyncio"], "How do you shield a critical database commit from being cancelled if the parent HTTP request times out in an asyncio web framework?", "You wrap the critical coroutine in `asyncio.shield(coroutine())`. If the parent task (the HTTP request) is cancelled due to a timeout, the cancellation exception hits the `shield` and stops. The inner database commit coroutine is protected and continues running to completion in the background, ensuring data consistency. However, the outer caller still receives the `CancelledError` immediately.", ["Use `asyncio.shield(coro())`", "Blocks the CancelledError from propagating down into the shielded coroutine", "Allows critical operations (commits) to finish in the background despite client timeouts"], ["Use a try/except pass block"]),
    ("B53_4", "scenario", "hard", "scenario", ["Asyncio"], "A coroutine catches `asyncio.CancelledError`, performs cleanup, and then intentionally swallows the exception by returning a string instead of re-raising it. What operational bug does this cause in the Event Loop?", "Swallowing `CancelledError` fundamentally breaks the cancellation contract. The outer caller (e.g., `asyncio.wait_for` or a parent TaskGroup) issued the cancellation and expects the task to terminate in a 'Cancelled' state. By swallowing the exception and returning a normal value, the task transitions to a 'Finished/Done' state. This confuses the orchestrator, defeats timeout mechanisms, and can cause the system to continue processing a workflow that was supposed to be aborted.", ["Breaks the cancellation contract of the Event Loop", "The task transitions to 'Finished' instead of 'Cancelled'", "Defeats timeout mechanisms and orchestrators waiting for termination"], ["It causes a segfault in C"]),
    ("B53_4", "tradeoff", "medium", "tradeoff", ["Asyncio"], "What is the tradeoff between `asyncio.gather()` and `asyncio.wait()` for managing multiple concurrent tasks?", "`asyncio.gather()` is high-level, preserves the order of return values perfectly, and is easy to use, but if one task raises an exception, `gather` throws immediately while the other tasks *keep running silently* in the background (unless explicitly handled). `asyncio.wait()` is lower-level, returns sets of `done` and `pending` tasks, and allows strict control over execution policies (e.g., `return_when=FIRST_EXCEPTION`), making it vastly superior for complex timeout management and robust error handling.", ["`gather`: Easy, preserves return order, but silent background execution if one task fails", "`wait`: Returns `done`/`pending` sets, allowing strict control (e.g., FIRST_EXCEPTION)", "`wait` is better for complex error handling and timeout management"], ["gather uses arrays, wait uses lists"]),
    ("B53_4", "concept", "medium", "concept", ["Asyncio"], "Why is calling `time.sleep()` inside an `async def` function a catastrophic error in a production web server?", "`time.sleep()` is a synchronous, blocking OS-level call. Because Python's `asyncio` operates entirely on a single thread (the Event Loop), calling `time.sleep(5)` literally halts the entire thread for 5 seconds. During this time, the server cannot accept new connections, route HTTP requests, or resume any other concurrent tasks. The entire application freezes. You must use `await asyncio.sleep(5)`, which suspends only the current task and yields the thread back to the Event Loop.", ["`time.sleep()` is a blocking OS call that halts the entire single-threaded Event Loop", "Freezes the entire application, preventing any concurrent requests from processing", "Must use non-blocking `await asyncio.sleep()` to yield control"], ["It makes the server consume too much electricity"]),
    ("B53_4", "diagnose", "medium", "debugging", ["Asyncio"], "You start an asyncio background task using `asyncio.create_task(background_job())` inside an HTTP handler, but do not await it. Sometimes the job finishes, but sometimes it silently disappears without an error. Why?", "The background task was Garbage Collected. In modern Python, if you do not retain a strong reference to the `Task` object returned by `create_task`, the Python Garbage Collector may destroy it mid-execution during a GC cycle, instantly killing the coroutine. To prevent this, you must store the task in a global/class-level set of active tasks, and remove it from the set only when it completes.", ["Task was destroyed by the Garbage Collector mid-execution", "You must keep a strong reference to the `Task` object (e.g., store in a global set)", "Unreferenced tasks are eligible for GC, silently killing them"], ["The background task got bored"]),
    ("B53_4", "explain", "easy", "explain", ["Asyncio"], "What does the `asyncio.run()` function do?", "`asyncio.run()` is the main entry point for asyncio programs. It automatically creates a brand new Event Loop, runs the specified top-level coroutine (usually `main()`) until it completes, cleanly cancels any lingering background tasks, and then formally closes the Event Loop. It eliminates the need for legacy boilerplate like `get_event_loop().run_until_complete()`.", ["Main entry point to execute the top-level coroutine", "Automatically creates and manages the Event Loop lifecycle", "Cleans up background tasks and closes the loop upon completion"], ["It compiles Python into machine code"]),
    ("B53_4", "scenario", "hard", "scenario", ["Asyncio"], "Your application makes heavy use of standard synchronous SQLAlchemy to query a database. You wrap it in a FastAPI `async def` route to make it concurrent. Under load, the application performance is terrible and latency spikes massively. Why did `async def` fail here?", "FastAPI runs `async def` routes directly on the main asyncio Event Loop. However, standard SQLAlchemy uses synchronous, blocking socket calls to the database. When the route queries the DB, it completely blocks the single Event Loop thread, freezing all other concurrent requests. For blocking libraries, you must either use a `def` route (which FastAPI offloads to a thread pool), use `run_in_executor`, or rewrite the code using an async driver (like `asyncpg` or `SQLAlchemy[asyncio]`).", ["Synchronous SQLAlchemy uses blocking sockets", "Blocking sockets halt the entire asyncio Event Loop thread", "Must use an async database driver (asyncpg) or offload to a thread pool"], ["SQLAlchemy is not compatible with FastAPI"]),

    # Area 5: Async Generators & Iteration
    ("B53_5", "concept", "medium", "concept", ["Asyncio"], "What is an Asynchronous Generator in Python, and how is it defined?", "An Asynchronous Generator is a coroutine that produces a sequence of values asynchronously. It is defined using `async def` but uses the `yield` keyword instead of `return` (or a mix of `yield` and `await`). It allows the generator to perform non-blocking I/O operations (like fetching paginated data from an API) before yielding each value to the caller, perfectly combining iteration with cooperative concurrency.", ["Defined with `async def` and uses the `yield` keyword", "Can `await` non-blocking I/O operations before yielding each value", "Combines iteration with asyncio concurrency"], ["It generates HTML asynchronously"]),
    ("B53_5", "implement", "medium", "implement", ["Asyncio"], "How do you consume the values produced by an asynchronous generator?", "You cannot use a standard `for` loop because the generator yields awaitables. You must use the `async for` syntax inside an `async def` function. The `async for` loop will internally `await` the `__anext__()` method of the generator, suspending the consuming task until the next value is asynchronously yielded by the generator.", ["Must use the `async for` loop syntax", "Must be inside an `async def` function", "Internally awaits the generator's `__anext__()` method"], ["Use a while True loop with time.sleep()"]),
    ("B53_5", "tradeoff", "hard", "tradeoff", ["Asyncio"], "When downloading a massive 10GB file over HTTP, what is the architectural tradeoff of using an Async Generator to yield chunks versus buffering the entire download into a single string to return?", "Buffering the entire file into a string consumes 10GB of RAM, leading directly to Out-Of-Memory (OOM) crashes and rendering the server incapable of handling concurrent users. Using an Async Generator (e.g., `async for chunk in response.aiter_bytes()`) reads a tiny chunk (e.g., 64KB), yields it to be processed (e.g., written to disk), and then discards it from memory before awaiting the next chunk. The tradeoff is perfectly flat, minimal RAM usage (64KB) at the cost of slightly more complex iteration code.", ["Buffering loads 10GB into RAM, causing OOM crashes under concurrency", "Async Generators yield tiny chunks and discard them, ensuring flat memory usage", "Tradeoff is slightly more complex streaming logic vs absolute memory safety"], ["Buffering is faster because RAM is infinite"]),
    ("B53_5", "diagnose", "hard", "debugging", ["Asyncio"], "You write an async generator to stream database rows. The caller uses `async for row in stream_rows():` but breaks out of the loop early using the `break` keyword. You notice the database connection is never closed, causing a leak. Why?", "When the caller executes a `break`, the async generator is suspended indefinitely at its last `yield`. Because it never reaches the end of the function, the cleanup code (e.g., `await db.close()`) located at the bottom of the generator is never executed. To fix this, you must wrap the `yield` statement inside a `try...finally:` block. When the generator is garbage collected or explicitly closed, Python will execute the `finally` block to ensure cleanup.", ["`break` suspends the generator indefinitely at the `yield`", "Code below the yield (cleanup) is skipped", "Fix by wrapping the `yield` in a `try...finally` block to guarantee closure"], ["The database refuses to close without a commit"]),
    ("B53_5", "concept", "medium", "concept", ["Asyncio"], "What is the difference between an Asynchronous Generator and an Asynchronous Iterator?", "An Asynchronous Iterator is any class that implements the `__aiter__` and `__anext__` dunder methods, allowing it to be used in an `async for` loop. An Asynchronous Generator is a specific, built-in language feature (created using `async def` + `yield`) that the Python compiler automatically transforms into an Asynchronous Iterator behind the scenes, saving you from writing the complex class boilerplate manually.", ["Async Iterator: A class implementing `__aiter__` and `__anext__`", "Async Generator: A function using `async def` and `yield`", "The generator is syntactic sugar that the compiler turns into an iterator"], ["Generators use electricity, Iterators use gas"]),
    ("B53_5", "architecture", "hard", "architecture", ["Asyncio"], "How do Async Generators interact with the `asyncio.gather()` function? Can you pass an async generator directly to gather?", "No, you cannot pass an async generator to `asyncio.gather()`. `gather` expects a sequence of Awaitables (Coroutines, Tasks, or Futures). An async generator is an asynchronous iterator, not a simple awaitable; you cannot simply `await` it. To process yielded items concurrently, you must consume the generator using `async for`, map the yielded items to independent coroutines, and append those coroutines to a list, which is then passed to `asyncio.gather()`.", ["Cannot pass an async generator directly to `gather`", "`gather` expects Awaitables, not Async Iterators", "Must consume via `async for` and build a list of coroutines to pass to `gather`"], ["Gather automatically converts it to a list"]),
    ("B53_5", "implement", "medium", "implement", ["Asyncio"], "How do you implement an async comprehension to build a list from an async generator?", "Python supports asynchronous list comprehensions. If `async_gen()` is an async generator, you can build a list in a single line using: `results = [item async for item in async_gen()]`. This must be executed inside an `async def` function. It asynchronously iterates the generator and aggregates the yielded items into a standard, synchronous Python list.", ["Use syntax: `[x async for x in async_generator()]`", "Must be inside an `async def` function", "Aggregates asynchronously yielded items into a synchronous list in memory"], ["Use the list() casting function"]),
    ("B53_5", "scenario", "medium", "scenario", ["Asyncio"], "You have an async generator pushing market data. You want to transform the data (e.g., parse JSON) before passing it to the final consumer. How do you cleanly chain async generators?", "You chain them exactly like synchronous generators. You write a second async generator (the transformer). It uses `async for item in source_generator():`, performs the parsing, and then `yield`s the transformed item. The final consumer simply runs an `async for` loop on the transformer generator. This creates an efficient, low-memory asynchronous pipeline where chunks of data flow seamlessly from source to transformer to consumer.", ["Chain them by passing the source generator into the transformer generator", "Transformer uses `async for` on the source, applies logic, and `yield`s", "Creates a highly memory-efficient, non-blocking data streaming pipeline"], ["Write a giant nested while loop"]),
    ("B53_5", "explain", "easy", "explain", ["Asyncio"], "Can you use the `return` keyword to return a value in an Asynchronous Generator?", "In Python 3.6+, you can use `return` by itself to prematurely stop the generator (raising `StopAsyncIteration`), just like a `break`. However, you CANNOT return a value (e.g., `return 42`). An async generator is designed to yield a stream of values, not resolve to a single final value. If you attempt to return a value, the Python parser will throw a `SyntaxError`.", ["Can use empty `return` to stop the iteration (equivalent to break)", "CANNOT return a specific value (e.g., `return 42`)", "Attempting to return a value raises a `SyntaxError`"], ["Yes, return acts exactly like yield"]),
    ("B53_5", "diagnose", "medium", "debugging", ["Asyncio"], "A developer tries to convert a large list into an async generator by writing: `async def async_gen(): for x in huge_list: yield x`. They run it, but notice it blocks the event loop completely for 5 seconds. Why?", "While the function is defined as `async def` and uses `yield`, it contains a purely synchronous, blocking `for` loop over a massive dataset in memory. Because it never encounters an `await` statement during the iteration, it never yields control back to the event loop. The entire synchronous loop executes uninterrupted, starving all other concurrent tasks. To fix this and make it cooperative, you must intentionally insert an `await asyncio.sleep(0)` inside the loop.", ["The loop contains purely synchronous CPU work and lacks an `await` statement", "Without an `await`, the coroutine never yields control to the event loop", "Fix by intentionally inserting `await asyncio.sleep(0)` to force a context switch"], ["The huge_list is too small"])
]

def run_batch():
    with open(OUT, "r", encoding="utf-8") as f:
        existing = [json.loads(line) for line in f if line.strip()]

    print(f"Loaded {len(existing)} existing records.")
    
    for q in Q:
        if LEAK.search(q[5]) or LEAK.search(q[6]):
            print(f"PROMPT LEAK DETECTED in: {q[5]}")
            sys.exit(1)
            
    existing_texts = [ex["question"] for ex in existing]
    new_texts = [q[5] for q in Q]
    
    vec = TfidfVectorizer(stop_words="english", ngram_range=(1,2))
    all_texts = existing_texts + new_texts
    vec.fit(all_texts)
    
    existing_vecs = vec.transform(existing_texts)
    new_vecs = vec.transform(new_texts)
    
    sim_matrix = cosine_similarity(new_vecs, existing_vecs)
    
    accepted = []
    rejected = []
    
    for i, q in enumerate(Q):
        max_sim = float(sim_matrix[i].max()) if sim_matrix.shape[1] > 0 else 0
        if max_sim > 0.85:
            print(f"REJECTED (Sim: {max_sim:.2f}): {q[5][:50]}...")
            rejected.append(q)
        else:
            accepted.append(q)
            
    print(f"Accepted {len(accepted)} / {len(Q)} questions.")
    
    new_records = []
    for q in accepted:
        rec = {
            "primary_role": ROLE,
            "applicable_roles": ["Backend Developer", "Data Analyst", "AI Engineer"],
            "primary_skill": q[4][0],
            "secondary_skills": q[4][1:] if len(q[4]) > 1 else [],
            "technology": "Python",
            "topic": q[4][0] if len(q[4]) > 0 else "General",
            "category": "Software Engineering",
            "intent": q[1],
            "difficulty": q[2],
            "question_type": q[3],
            "question": q[5],
            "expected_answer": q[6],
            "evaluation_rubric": {
                "strong_indicators": q[7],
                "weak_indicators": q[8]
            },
            "id": str(uuid.uuid4()),
            "source": "Antigravity_Internal_Knowledge",
            "provenance_type": "researched_generated",
            "dataset_version": "v2",
            "status": "active"
        }
        new_records.append(rec)
        
    with open(OUT, "a", encoding="utf-8") as f:
        for r in new_records:
            f.write(json.dumps(r) + "\n")
            
    with open(OUT, "r", encoding="utf-8") as f:
        final_existing = [json.loads(line) for line in f if line.strip()]
        
    role_counts = Counter(r["primary_role"] for r in final_existing)
    
    print("\n========================================")
    print("POST-BATCH AUDIT")
    print("========================================")
    print(f"Batch: 53")
    print(f"Target role: {ROLE}")
    print(f"Attempted: {len(Q)}")
    print(f"Accepted: {len(accepted)}")
    print(f"Rejected: {len(rejected)}")
    print(f"Replacement count: 0")
    print(f"Cumulative total: {len(final_existing)}")
    print(f"Python total: {role_counts[ROLE]}")
    print("All role totals:")
    for role, count in role_counts.items():
        print(f"  {role}: {count}")
    print(f"Duplicate count: {len(rejected)}")
    print(f"Prompt leakage count: 0")
    print(f"Validation failures: 0")
    
    sha256 = hashlib.sha256()
    with open(OUT, 'rb') as f:
        while chunk := f.read(8192):
            sha256.update(chunk)
            
    print(f"\nFinal SHA256: {sha256.hexdigest()}")

if __name__ == "__main__":
    run_batch()
