import asyncio
import json
import os
import re
import sys
import uuid
import hashlib
from collections import Counter

from dotenv import load_dotenv
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
load_dotenv()

BACKEND_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_DIR = os.path.join(BACKEND_DIR, "data")
OUT = os.path.join(DATA_DIR, "interview_question_bank_v2_generated.jsonl")

ROLE = "Backend Developer"
LEAK = re.compile(r"(generate a question|generate \d+ questions|return only json|phase 4c gap plan|"
                  r"generation batch|candidate generation|system instructions|do not proceed|"
                  r"awaiting authorization|minimum target|generation pipeline|"
                  r"batch \d+ generation|expected answer|strong indicator|weak indicator|as an ai|"
                  r"here is the question|\bprompt text\b)", re.I)

Q = [
    # Group 1: Distributed Consistency & Sagas
    ("B62_1_1", "concept", "medium", "concept", ["Distributed Consistency"], "What is the 'Saga Pattern' in microservices, and how does it handle distributed transactions differently from a Two-Phase Commit (2PC)?", "A traditional 2PC strictly locks rows across multiple databases until every system commits, ensuring absolute ACID consistency but completely destroying availability/scalability. The Saga Pattern breaks the transaction into a sequence of local, independent database transactions. If Service A succeeds, it publishes an event to trigger Service B. If Service C fails, you cannot simply 'rollback' the DBs in A and B because they already committed locally. Instead, the Saga must automatically execute compensating transactions (e.g., if A was 'Charge Card', the compensation is 'Refund Card') to eventually restore consistency without synchronous locks.", ["2PC enforces synchronous, blocking locks across all databases, crippling scalability", "Saga executes sequential, independent local transactions via asynchronous events", "Failures in Sagas require executing explicit 'compensating transactions' to undo previously committed steps"], ["Sagas are long stories about databases, 2PC is two databases"]),
    ("B62_1_2", "diagnose", "hard", "debugging", ["Distributed Consistency"], "Your distributed order system uses a Saga. Service A (Inventory) successfully reserves an item. Service B (Payment) fails. The Saga orchestrator fires a compensating event to Service A to un-reserve the item. Due to a network partition, Service A receives this compensating event 3 times. What architectural flaw causes inventory corruption, and how do you fix it?", "Service A lacks 'Idempotent Consumers'. If it blindly processes the compensating event 3 times, it might add +3 items back to the inventory instead of +1, permanently corrupting the stock count. In a distributed, asynchronous system (Kafka/RabbitMQ), 'exactly-once delivery' is a myth; you are only guaranteed 'at-least-once delivery'. To fix this, Service A MUST be idempotent. It must track the `transaction_id` or `event_id` in its local database. When the compensating event arrives, it checks if it already processed that ID. If yes, it ignores the duplicate event.", ["At-least-once delivery guarantees mean services will inevitably receive duplicate events", "The consumer (Service A) blindly executed the compensation multiple times, corrupting data", "Fix: The consumer must be Idempotent by tracking processed `event_ids` in its local database"], ["The network partition cloned the items in the database"]),
    ("B62_1_3", "implement", "hard", "implement", ["Distributed Consistency"], "How do you implement the 'Transactional Outbox Pattern' to guarantee that a database update and a Kafka event publish occur atomically?", "If you update a DB row and then call `kafka.send()`, the app might crash in the 1 millisecond between those two lines, leaving the DB updated but the event lost forever. You cannot wrap a Kafka network call in a SQL transaction. To implement the Outbox Pattern: 1) You write the domain data (e.g., `Order`) AND the event payload (e.g., `OrderCreatedEvent`) to two separate tables (`orders` and `outbox`) within the EXACT SAME local SQL transaction. 2) A separate background worker (or CDC tool like Debezium) continuously tails the `outbox` table, reads the committed events, publishes them to Kafka, and then marks them as sent. This guarantees atomic consistency.", ["Updating a DB and sending a network event sequentially is fundamentally unsafe (dual-write problem)", "Within a single SQL transaction, write both the domain mutation and the event payload to an `outbox` table", "A background CDC tailer/worker reliably forwards the outbox records to Kafka asynchronously"], ["You just put Kafka inside the database"]),
    ("B62_1_4", "tradeoff", "hard", "tradeoff", ["Distributed Consistency"], "What is the tradeoff of relying on 'Read-After-Write Consistency' versus 'Eventual Consistency' for a highly active user profile page?", "Eventual Consistency (e.g., saving to the primary DB, while the frontend reads from a lagging read-replica) provides massive read scalability and sub-millisecond latency. The severe tradeoff is the UI flicker: the user updates their profile picture, the page refreshes, and they still see the old picture because the replica hasn't synced. Read-After-Write Consistency forces the user's reads to be routed directly to the Primary Master database for 5 seconds after they perform a write. This completely eliminates the confusing UI flicker, but the tradeoff is putting massive read pressure directly on the fragile Primary Database.", ["Eventual Consistency: Fast and highly scalable, but causes confusing UI flickers due to replication lag", "Read-After-Write: Forces the user's immediate subsequent reads to hit the Master database (or cache)", "Tradeoff: Eliminates UI confusion but degrades scalability by routing heavy reads to the Master node"], ["Read-after-write means you have to write a book before reading one"]),
    ("B62_1_5", "scenario", "medium", "scenario", ["Distributed Consistency"], "A distributed background worker uses Redis for distributed locking to ensure only one worker processes a daily report. The worker acquires the lock, starts generating the report, but suddenly Garbage Collection pauses the worker for 45 seconds. The Redis lock TTL is 30 seconds. What catastrophic data race occurs, and how do you architecturally prevent it?", "The worker's 45-second GC pause causes the Redis lock to expire (at 30s). Worker B sees the lock is free, acquires it, and starts generating the report. When Worker A wakes up from GC, it thinks it still holds the lock and commits its data, causing massive duplicate data corruption (the ABA problem for distributed locks). To prevent this, you MUST implement 'Fencing Tokens'. When Redis grants a lock, it returns an incrementing token (e.g., 5). When the worker commits to the Database, it passes token 5. The Database is configured to reject any writes with a token <= the last one it saw. When Worker B gets the lock (Token 6) and writes, Worker A's subsequent delayed write (Token 5) is mathematically rejected.", ["GC pauses (or network delays) can outlast the lock TTL, allowing two workers to operate simultaneously", "Worker A wakes up and blindly commits, corrupting data because it doesn't know it lost the lock", "Fix: Use Fencing Tokens (incrementing lock IDs) and enforce monotonic token validation at the Database level"], ["You just tell Redis to wait until the worker is done"]),
    ("B62_1_6", "explain", "medium", "explain", ["Distributed Consistency"], "Explain the concept of 'Quorum' in distributed databases (like Cassandra or DynamoDB) and how it balances consistency and availability.", "In a distributed DB with a Replication Factor of 3 (data is stored on 3 nodes), Quorum defines how many nodes must acknowledge a Read (R) or Write (W) for it to be considered successful. Strict Quorum requires `W + R > Replication Factor`. If W=2 and R=2, it guarantees Strong Consistency (you will always read the most recent write, even if 1 node is dead). However, if 2 nodes crash, the database becomes completely unavailable for writes. If you set W=1 (fast, highly available), it only requires 1 node to acknowledge, but you risk reading stale data from the other 2 nodes. Quorum allows architects to explicitly dial the CAP theorem tradeoff.", ["Quorum dictates how many nodes must acknowledge an operation (Read/Write) to succeed", "Formula `W + R > N` guarantees Strong Consistency at the cost of Availability (if nodes die, the DB halts)", "Dialing down the quorum (e.g., W=1) boosts Availability and speed but introduces Eventual Consistency/stale reads"], ["A quorum is a tank you put virtual fish in"]),

    # Group 2: Event-Driven Architecture & Messaging
    ("B62_2_1", "concept", "medium", "concept", ["Event-Driven Architecture"], "What is a 'Poison Message' in a message queue (like SQS or RabbitMQ), and what is the standard architectural pattern for handling it?", "A Poison Message is a corrupted, malformed, or perfectly valid message that triggers a fatal bug in the consumer code (e.g., a Null Pointer Exception). The consumer crashes, the queue assumes the message wasn't processed, and puts it back on the queue. The consumer restarts, pulls the exact same message, and crashes again, creating an infinite loop that completely halts all message processing. The standard pattern is a Dead-Letter Queue (DLQ). You configure the queue: 'If a message fails processing 3 times, move it out of the main queue into the DLQ'. This unblocks the main queue and allows engineers to inspect the poison message safely.", ["A message that repeatedly crashes the consumer, creating an infinite loop that halts the entire queue", "Occurs due to malformed payloads or unhandled exceptions in the worker code", "Fix: Configure a Dead-Letter Queue (DLQ) to automatically quarantine messages after N failed retries"], ["A poison message is a text message with a virus in it"]),
    ("B62_2_2", "diagnose", "hard", "debugging", ["Event-Driven Architecture"], "Your backend service consumes a Kafka topic with 10 partitions using a Consumer Group of 10 workers. During peak load, you notice that Worker 1 is at 100% CPU, but Workers 2 through 10 are sitting completely idle at 0% CPU. The Kafka topic has millions of messages. What is misconfigured?", "This is a catastrophic Partition Key skew (Hot Partition). In Kafka, messages are routed to partitions based on a hash of the Message Key. If the publisher is sending millions of messages but using the exact same hardcoded key (e.g., `tenant_id=1`), the hash algorithm will route 100% of those messages to Partition 1. Because Kafka strictly assigns one partition to one consumer thread, Worker 1 receives all the traffic, while the other 9 partitions (and 9 workers) starve. To fix this, the publisher must use a highly randomized key (like `user_id` or `UUID`), or use a Round-Robin partitioning strategy for stateless events.", ["Partition Key Skew: The publisher is using a low-cardinality or hardcoded Message Key", "Kafka routes messages with the same key to the same physical partition to guarantee ordering", "Fix by randomizing the message key (e.g., UUID) to evenly distribute the hashing across all partitions"], ["The workers are on strike"]),
    ("B62_2_3", "implement", "medium", "implement", ["Event-Driven Architecture"], "How do you implement guaranteed message ordering in an asynchronous event-driven system while maintaining horizontal scalability?", "If you have 1 global queue and 10 workers pulling from it concurrently, absolute global ordering is mathematically impossible (Worker A pulls message 1, Worker B pulls message 2, but Worker B finishes writing to the DB first). To guarantee ordering while scaling, you must partition the data based on bounded context. In Kafka, you use a Partition Key (e.g., `order_id=123`). Kafka guarantees that all events with the same key will be routed to the exact same partition, and processed sequentially by exactly one consumer thread. Meanwhile, `order_id=456` goes to a different partition and is processed concurrently by a different thread.", ["Global strict ordering across multiple concurrent workers is mathematically impossible", "You must partition the data using a specific context key (e.g., `order_id`)", "Kafka guarantees strict sequential ordering *within a single partition*, allowing horizontal scaling across different keys"], ["You just tell the database to sort it later"]),
    ("B62_2_4", "tradeoff", "hard", "tradeoff", ["Event-Driven Architecture"], "What is the operational tradeoff of using an 'Event Sourcing' architecture versus a traditional 'CRUD' (Create, Read, Update, Delete) state-based architecture?", "In a traditional CRUD system, if a user changes their address from NY to LA, the database row is overwritten; the historical fact that they lived in NY is permanently lost. Event Sourcing never overwrites data. It stores a sequential, immutable append-only log of every state change (`UserCreated`, `AddressUpdated(NY)`, `AddressUpdated(LA)`). To get the current state, the backend 'replays' the events. The massive benefit is perfect auditing, the ability to time-travel (reconstruct state at any past date), and zero locking. The severe tradeoff is extreme complexity, eventual consistency, and the necessity to implement CQRS (Command Query Responsibility Segregation) because you cannot easily query 'SELECT * WHERE address=LA' without a dedicated read projection.", ["CRUD overwrites data (losing history) but is incredibly easy to query and conceptualize", "Event Sourcing stores immutable, append-only logs of state changes. Provides perfect audits and time-travel", "Tradeoff: Extreme architectural complexity. Requires replaying logs to find current state and mandates CQRS for querying"], ["Event sourcing means looking for events on Facebook"]),
    ("B62_2_5", "scenario", "medium", "scenario", ["Event-Driven Architecture"], "You deploy a new version of a microservice that consumes a RabbitMQ queue. The new version expects a JSON field `user_age` as an integer. The queue still contains 50,000 pending messages from the old version of the publisher where `user_age` was a string. The new consumers crash instantly. How do you architect event schemas to prevent this?", "You must implement strict 'Schema Evolution' and 'Forward/Backward Compatibility'. 1) Never introduce breaking schema changes instantly. The publisher should have been updated to send *both* fields (or a strongly typed format like Protobuf/Avro) weeks in advance. 2) The Consumer code MUST be defensively written to handle both versions simultaneously during the transition period (e.g., `parseInt(msg.user_age)` if it's a string). 3) Best practice: enforce a central Schema Registry (like Confluent) that actively blocks the CI/CD pipeline if a developer tries to publish a schema that violates backward compatibility.", ["The consumer aggressively assumed the new schema without handling the backlog of legacy messages", "Consumer code must be defensively written to support N and N-1 schema versions simultaneously", "Architectural Fix: Use a Schema Registry (Protobuf/Avro) to strictly enforce backward compatibility at build time"], ["You just delete all the old messages in the queue"]),

    # Group 3: Concurrency, Race Conditions & DB Interactions
    ("B62_3_1", "concept", "medium", "concept", ["Concurrency"], "What is 'Optimistic Concurrency Control' (OCC) and how does it prevent Lost Updates without locking the database?", "A Lost Update occurs when User A and User B read the same row, both modify it in memory, and both write it back; whoever writes last silently overwrites the other. Pessimistic locking (`SELECT FOR UPDATE`) prevents this by physically freezing the row, destroying read scalability. OCC prevents this without locking by adding a `version` integer column. User A and B both read `version=1`. User A saves their change, passing `WHERE id=X AND version=1`; the DB updates the row and increments to `version=2`. When User B tries to save, they pass `WHERE version=1`. The database returns 0 rows updated. The API throws an HTTP 409 Conflict, forcing User B to fetch the fresh data.", ["Prevents Lost Updates without using blocking database locks (Pessimistic Locking)", "Uses a `version` column (or timestamp/ETag) to validate that the record hasn't changed since it was read", "If the version mismatches, the DB write fails, and the application throws a 409 Conflict"], ["Optimistic concurrency means you hope the database doesn't crash"]),
    ("B62_3_2", "diagnose", "hard", "debugging", ["Concurrency"], "Your API endpoint `/transfer-funds` occasionally causes a complete Database Deadlock, freezing the entire application for minutes. You look at the code: it locks the sender's account row, then locks the receiver's account row, updates both balances, and commits. Why is this causing a deadlock?", "Deadlocks occur when two transactions acquire locks in opposing orders and wait for each other infinitely. Transaction 1 transfers money from Account A to Account B (Locks A, then tries to Lock B). At the exact same millisecond, Transaction 2 transfers money from Account B to Account A (Locks B, then tries to Lock A). Both transactions freeze, holding one lock and waiting for the other. To fix this, you must strictly enforce a 'Deterministic Locking Order' in your application code. For example, always lock the account with the lowest ID number first. (If ID 5 transfers to ID 10, lock 5 then 10. If 10 transfers to 5, lock 5 then 10). Both transactions will queue cleanly on ID 5.", ["Deadlocks happen when concurrent transactions acquire locks in different, opposing sequences", "Transaction 1 locks A and waits for B; Transaction 2 locks B and waits for A", "Fix: Enforce a Deterministic Locking Order (e.g., always lock the lowest primary key first)"], ["Deadlock is when the server gets stuck in a physical loop"]),
    ("B62_3_3", "implement", "medium", "implement", ["Concurrency"], "How do you implement a highly scalable 'Rate Limiter' across a distributed backend cluster with 20 nodes?", "If you use in-memory rate limiting (like a local Node.js variable), a user can make 100 requests to Node 1, and 100 requests to Node 2, completely bypassing the limit. You must use a centralized, extremely fast Key-Value store like Redis. The standard algorithm is the 'Sliding Window' or 'Token Bucket'. When an API request arrives, the backend executes a Lua script in Redis (to guarantee atomicity). The script checks the user's IP/API-Key counter. If `< 100`, it increments and allows the request. If `> 100`, it rejects it. Using a Lua script is critical because it prevents Race Conditions between the `GET` and `SET` commands under high concurrency.", ["Local memory fails because limits aren't shared across the 20 load-balanced nodes", "Must use a centralized, low-latency datastore like Redis", "Execute the limit check and increment atomically using a Redis Lua script to prevent Race Conditions"], ["You put a physical limit on the router"]),
    ("B62_3_4", "tradeoff", "hard", "tradeoff", ["Concurrency"], "What is the tradeoff of relying entirely on Database Constraints (Unique Indexes, Foreign Keys) versus enforcing those constraints purely in the Backend Application logic?", "Enforcing logic purely in the Application (e.g., checking `if user_exists` before inserting) is highly scalable and DB-agnostic, but is severely vulnerable to Race Conditions. If two concurrent requests pass the `if` check simultaneously, both will insert, resulting in duplicate data (Data Corruption). Database Constraints (Unique Indexes) guarantee 100% mathematical data integrity at the disk level, completely immune to application race conditions. The severe tradeoff is that DB constraints are rigid, difficult to migrate in production (locking tables), and force the backend to use messy `try/catch` blocks to parse raw SQL constraint violation strings into friendly HTTP 400 errors.", ["Application Logic: Highly scalable, but highly vulnerable to Race Conditions and duplicate data", "Database Constraints (Unique Indexes): Mathematically guarantees integrity against race conditions", "Tradeoff: DB constraints are rigid, slow down writes, and require messy try/catch parsing in the backend"], ["Database constraints limit how much data you can store in the database"]),
    ("B62_3_5", "scenario", "medium", "scenario", ["Concurrency"], "A cron job runs at midnight to calculate daily analytics. It queries 50 million rows. During this 10-minute job, the entire API becomes completely unresponsive for users trying to save new data. Why does a SELECT query block INSERTs, and how do you fix the architecture?", "This is an Isolation Anomaly/Lock Contention issue. In some databases (or due to table-level locking/escalation), a massive, long-running `SELECT` query will acquire shared read locks on millions of rows. When a user tries to `INSERT` or `UPDATE`, they require an exclusive write lock, which is blocked by the read lock, freezing the API. To fix this instantly, ensure the Database is using MVCC (Multi-Version Concurrency Control, default in Postgres) where 'Readers do not block Writers'. Architecturally, you should NEVER run massive analytics queries on the Primary transactional database. You must route the cron job to a Read Replica or a dedicated Data Warehouse.", ["Massive analytical queries can acquire locks or consume IOPS/Memory, starving the primary API", "If the DB lacks MVCC, read locks will physically block write locks (freezing INSERTs)", "Architectural Fix: Route all heavy OLAP/Analytics queries to a dedicated Read Replica or Data Warehouse"], ["The database was tired at midnight"]),
    ("B62_3_6", "explain", "medium", "explain", ["Concurrency"], "Explain the 'Connection Pool Exhaustion' failure mode, and why setting the pool size to 10,000 does not fix it.", "When a backend server receives an HTTP request, it borrows a DB connection from a pool. If the API is slow (e.g., making a 3rd party API call while holding the DB connection open), the connections stay checked out. During a traffic spike, all 100 connections are checked out, and new requests hang infinitely waiting for a connection, crashing the API. Developers often incorrectly increase the pool to 10,000. This is catastrophic. PostgreSQL cannot handle 10,000 active connections; the context switching and memory overhead will crash the database server instantly. The correct fix is to keep the pool small (e.g., 50), enforce strict DB timeouts, and NEVER hold a DB connection while waiting on external network I/O.", ["Connection pools borrow a persistent DB connection per request. Slow requests exhaust the pool", "Increasing the pool size massively (e.g., 10,000) will crash the DB due to memory and context-switching overhead", "Fix: Keep pools small, enforce strict query timeouts, and never hold a DB transaction open while making external HTTP calls"], ["Connection pool exhaustion is when the water drains out of the server cooling system"])
]

def run_batch():
    with open(OUT, "a", encoding="utf-8") as f:
        for q in Q:
            rec = {
                "primary_role": ROLE,
                "applicable_roles": ["Systems Engineer", "Software Engineer"],
                "primary_skill": q[4][0],
                "secondary_skills": q[4][1:] if len(q[4]) > 1 else [],
                "technology": "Backend Core",
                "topic": q[4][0] if len(q[4]) > 0 else "General",
                "category": "Software Engineering",
                "intent": q[1],
                "difficulty": q[2],
                "question_type": q[3],
                "question": q[5],
                "expected_answer": q[6],
                "evaluation_rubric": {
                    "strong_indicators": q[7],
                    "weak_indicators": q[8]
                },
                "id": str(uuid.uuid4()),
                "source": "Antigravity_Internal_Knowledge",
                "provenance_type": "researched_generated",
                "dataset_version": "v2",
                "status": "active"
            }
            f.write(json.dumps(rec) + "\n")
            
    print(f"Appended {len(Q)} questions (Batch 62 Part 1).")

if __name__ == "__main__":
    run_batch()
