import asyncio
import json
import os
import re
import sys
import uuid
import hashlib
from collections import Counter

from dotenv import load_dotenv
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
load_dotenv()

BACKEND_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_DIR = os.path.join(BACKEND_DIR, "data")
OUT = os.path.join(DATA_DIR, "interview_question_bank_v2_generated.jsonl")

ROLE = "DevOps / Cloud Engineer"
LEAK = re.compile(r"(generate a question|generate \d+ questions|return only json|phase 4c gap plan|"
                  r"generation batch|candidate generation|system instructions|do not proceed|"
                  r"awaiting authorization|minimum target|generation pipeline|"
                  r"batch \d+ generation|expected answer|strong indicator|weak indicator|as an ai|"
                  r"here is the question|\bprompt text\b)", re.I)

Q = [
    # Group 1: Cloud Networking
    ("B61_1_1", "concept", "hard", "concept", ["Cloud Networking"], "Explain the difference between a VPC Peering connection and an AWS Transit Gateway, and when you would choose one over the other.", "VPC Peering provides a direct, point-to-point network connection between two VPCs. It is incredibly fast and cheap, but it does NOT support transitive routing. If A peers with B, and B peers with C, A cannot talk to C. Connecting 100 VPCs requires 4,950 peering connections (a full mesh nightmare). Transit Gateway acts as a centralized Hub-and-Spoke router. You attach all 100 VPCs to the Transit Gateway, requiring only 100 attachments. It massively simplifies routing tables and supports transitive routing, but introduces a per-hour cost and a data processing fee per GB.", ["VPC Peering is point-to-point, non-transitive, cheap, and fast (ideal for 2-3 VPCs)", "Transit Gateway is a Hub-and-Spoke router, supports transitive routing, and simplifies large architectures", "Tradeoff: Transit Gateway introduces additional data processing fees per GB and per-attachment hourly costs"], ["Transit Gateway is for public internet, VPC Peering is for private"]),
    ("B61_1_2", "diagnose", "hard", "debugging", ["Cloud Networking"], "Your private EKS cluster nodes in AWS randomly start timing out when pulling container images from Docker Hub or communicating with external SaaS APIs. The CloudWatch metrics for your NAT Gateway show a massive spike in `ErrorPortAllocation`. What is happening and how do you fix it?", "This is NAT Gateway Port Exhaustion (SNAT exhaustion). A single NAT Gateway translates private IPs to a single public IP. TCP allows a maximum of 65,535 ephemeral ports per public IP. If your Kubernetes pods make >65k concurrent outbound connections to the exact same external destination (e.g., Docker Hub or a 3rd party API), the NAT Gateway runs out of available ports and drops traffic silently. To fix this: 1) Deploy multiple NAT Gateways in different AZs and split the routing, 2) Attach secondary Elastic IPs to the NAT Gateway (AWS supports up to 8), or 3) Use VPC Endpoints (PrivateLink) to route AWS-specific traffic internally without using the NAT Gateway.", ["NAT Gateway Port Exhaustion (SNAT exhaustion): Maximum 65,535 concurrent connections to the same destination per Public IP", "The pods are exhausting the ephemeral port range, causing outbound connection timeouts", "Fix by adding secondary EIPs to the NAT, splitting traffic across multiple NATs, or using VPC Endpoints for AWS services"], ["The NAT Gateway ran out of RAM"]),
    ("B61_1_3", "implement", "medium", "implement", ["Cloud Networking"], "How do you securely expose an internal, private Kubernetes service to a 3rd party vendor without exposing the service to the public internet, avoiding VPNs, and avoiding VPC Peering?", "You implement AWS PrivateLink (VPC Endpoint Services). You expose your internal Kubernetes service via an Internal Network Load Balancer (NLB). You then create a 'VPC Endpoint Service' linked to that NLB. The 3rd party vendor creates a 'VPC Endpoint' in their own AWS account. Traffic flows securely across the AWS internal backbone (never hitting the public internet) directly from their VPC to your NLB. This provides unidirectional, tightly controlled access without overlapping CIDR blocks or complex IPSec VPN tunnels.", ["Use AWS PrivateLink (VPC Endpoint Services) tied to an Internal Network Load Balancer", "The vendor creates a VPC Endpoint in their account, routing traffic over the AWS backbone", "Provides secure, unidirectional access without VPNs or overlapping IP CIDR concerns"], ["You email them the IP address and put their name in a firewall rule"]),
    ("B61_1_4", "tradeoff", "hard", "tradeoff", ["Cloud Networking"], "What is the architectural tradeoff of using 'Asymmetric Routing' across an Active-Active Multi-Region hybrid cloud setup (e.g., AWS and On-Premises via Direct Connect)?", "Asymmetric routing occurs when a packet leaves AWS to On-Prem via Path A, but the return packet goes from On-Prem to AWS via Path B. If you use stateless routers, this is perfectly fine and provides optimal, lowest-latency paths. The severe tradeoff is Stateful Firewalls (like Palo Alto or AWS Network Firewall). Stateful firewalls track TCP handshakes. If the firewall sees the `SYN-ACK` return packet on Path B, but never saw the original `SYN` on Path A, it considers the packet invalid/spoofed and drops it instantly. To fix this, you must force symmetric routing using strict BGP AS-Path prepending or source NAT (SNAT), which artificially inflates latency.", ["Asymmetric routing provides optimal latency but breaks Stateful Firewalls", "Stateful firewalls drop return packets if they didn't see the initiating TCP handshake", "Tradeoff: Forcing symmetric routing requires BGP manipulation or SNAT, adding architectural complexity and latency"], ["Asymmetric routing means one cable is thicker than the other"]),
    ("B61_1_5", "scenario", "medium", "scenario", ["Cloud Networking"], "You deploy a new internal microservice. It needs to communicate with an existing legacy database. Both are in private subnets, but in different VPCs. The VPCs cannot be peered because their IP CIDR blocks completely overlap (both are `10.0.0.0/16`). How do you architect connectivity?", "Because the CIDRs are identical, standard routing (Peering or Transit Gateway) will fail due to IP conflicts. You must use PrivateLink (if AWS) or implement a Reverse Proxy with SNAT (Source Network Address Translation). With PrivateLink, you expose the legacy database via an NLB and Endpoint Service. The new microservice accesses the database via a unique DNS name provided by the VPC Endpoint, which resolves to a local IP in the *new* VPC's subnet. The AWS hypervisor translates the traffic behind the scenes, completely sidestepping the CIDR overlap.", ["Overlapping CIDR blocks mathematically break standard IP routing and VPC Peering", "Must use AWS PrivateLink (VPC Endpoints) to expose the service via an NLB", "PrivateLink injects a local IP into the requesting VPC, abstracting the network translation and bypassing CIDR conflicts"], ["Just change the database IP address to 192.168.x.x without telling anyone"]),
    ("B61_1_6", "explain", "medium", "explain", ["Cloud Networking"], "Explain the difference between 'Anycast' and 'Unicast' IP routing, and why Anycast is critical for Global CDNs and DNS.", "In Unicast, an IP address points to exactly one physical server in the world. If that server is in London, a user in Tokyo suffers massive latency. In Anycast, the exact same IP address (e.g., Google DNS `8.8.8.8`) is advertised by hundreds of different servers globally using BGP (Border Gateway Protocol). When a user in Tokyo requests `8.8.8.8`, internet routers automatically deliver the packet to the physically closest server advertising that IP (the Tokyo datacenter). Anycast provides extreme global low-latency and automatic DDoS mitigation, as attacks are absorbed locally by the nearest edge node rather than overwhelming a central server.", ["Unicast maps an IP to a single specific machine; Anycast maps one IP to multiple machines globally", "BGP routing naturally sends traffic to the physically closest Anycast node", "Crucial for CDNs/DNS to minimize latency and distribute/absorb DDoS attacks geographically"], ["Anycast casts a spell on the network, unicast casts one spell"]),
    ("B61_1_7", "concept", "easy", "concept", ["Cloud Networking"], "What is a 'Bastion Host' (Jump Box), and why is AWS Systems Manager (SSM) Session Manager replacing it?", "A Bastion Host is a heavily secured, public-facing EC2 instance that engineers SSH into, and from there, SSH into private internal servers. It requires maintaining public IP addresses, opening port 22 to the internet, managing SSH key pairs, and OS patching. AWS SSM Session Manager replaces it by installing an agent on the private servers. Engineers authenticate via AWS IAM and open a secure tunnel directly to the private server through the AWS API. This completely eliminates the need for public IPs, open inbound ports, and SSH keys, vastly improving security.", ["Bastion: A public-facing proxy server used to SSH into private resources, requiring open inbound port 22", "SSM Session Manager uses an outbound agent, requiring zero open inbound ports or public IPs", "SSM uses strict IAM policies instead of managing risky SSH key pairs"], ["A Bastion Host is the CEO's personal computer"]),
    ("B61_1_8", "diagnose", "medium", "debugging", ["Cloud Networking"], "You have a public Application Load Balancer (ALB) pointing to EC2 targets. The EC2 security group allows inbound HTTP (Port 80) only from the ALB's security group. However, the ALB health checks are failing and returning 502 Bad Gateway. You SSH into the EC2 instance and verify the web server is returning 200 OK locally. What network configuration did you miss?", "The ALB and EC2 Security Groups are correct, but you likely missed the Network ACL (NACL) or the Subnet Routing. If it's a NACL issue, NACLs are stateless; you might have allowed inbound traffic on port 80, but forgot to allow outbound return traffic on the ephemeral port range (1024-65535). Alternatively, the ALB might be in public subnets with an Internet Gateway, but the EC2 instances are in private subnets with no route back to the ALB via the NAT Gateway, causing the health check SYN-ACK packets to drop.", ["Security Groups are stateful, but Network ACLs (NACLs) are stateless", "NACLs require explicitly allowing outbound return traffic on ephemeral ports (1024-65535)", "Alternatively, the subnet routing table lacks a return route for the health check traffic"], ["The ALB is on strike"]),
    ("B61_1_9", "architecture", "hard", "architecture", ["Cloud Networking"], "How do you architect DNS Failover for a multi-region Active-Passive application (e.g., Primary in `us-east-1`, Disaster Recovery in `us-west-2`) to guarantee a 1-minute RTO (Recovery Time Objective)?", "You configure Route 53 with a 'Failover Routing Policy'. You create a Primary Record pointing to the `us-east-1` ALB, and a Secondary (Passive) Record pointing to the `us-west-2` ALB. Crucially, you attach a Route 53 Health Check to the Primary endpoint. If `us-east-1` goes down, the health check fails, and Route 53 automatically updates the DNS resolution to point to the Secondary record. To guarantee a 1-minute RTO, you MUST set the DNS TTL (Time To Live) to a very low value (e.g., 60 seconds). If you leave the TTL at 24 hours, ISPs and browsers will cache the broken `us-east-1` IP, and the failover will effectively take hours.", ["Use Route 53 Failover Routing Policy tied to an active Health Check on the Primary Region", "When the health check fails, Route 53 automatically resolves queries to the Secondary Region", "Must enforce a strict, ultra-low DNS TTL (e.g., 60 seconds) so client caches expire quickly during failover"], ["You just email all your users the new IP address"]),
    ("B61_1_10", "tradeoff", "hard", "tradeoff", ["Cloud Networking"], "What is the tradeoff of implementing strict 'Zero Trust' mTLS (Mutual TLS) between every single microservice in your internal Kubernetes cluster?", "mTLS guarantees that traffic is encrypted in transit and mathematically proves the identity of both the client and the server (preventing internal spoofing or packet sniffing if the network is breached). The severe tradeoffs are: 1) Immense PKI (Public Key Infrastructure) complexity—you must continuously rotate thousands of certificates before they expire. 2) Latency—every internal API call now requires a CPU-heavy cryptographic handshake. 3) Debugging nightmare—you can no longer use simple tools like `tcpdump` or Wireshark to inspect internal cluster traffic because the payloads are fully encrypted.", ["mTLS guarantees encrypted transit and strict identity verification between internal services", "Tradeoff: Massive PKI certificate management and rotation complexity (usually requires a Service Mesh)", "Tradeoff: CPU latency overhead for handshakes, and impossible to packet-sniff (`tcpdump`) for debugging"], ["mTLS makes the server physically heavier due to the keys"]),

    # Group 2: Kubernetes Operations
    ("B61_2_1", "concept", "medium", "concept", ["Kubernetes Core"], "What is a Kubernetes 'Pod Disruption Budget' (PDB) and why is it critical for cluster upgrades?", "A PDB limits the number of concurrently disrupted (down) pods that a replicated application experiences during voluntary disruptions (like draining a node for a Kubernetes upgrade). If you have 3 replicas of an Nginx deployment, and you set `minAvailable: 2`, Kubernetes will guarantee that during a rolling node upgrade, it will only ever evict and restart 1 pod at a time. It explicitly blocks the Cluster Autoscaler or Node Upgrade scripts from draining multiple nodes simultaneously if it would violate the PDB, preventing self-inflicted downtime.", ["Limits concurrent pod evictions during voluntary disruptions (Node drains/upgrades)", "Guarantees a minimum number of healthy replicas are always serving traffic (`minAvailable`)", "Prevents automation scripts or autoscalers from accidentally taking down the entire application"], ["It is the financial budget for buying more pods"]),
    ("B61_2_2", "diagnose", "hard", "debugging", ["Kubernetes Core"], "Your Kubernetes pods are randomly being terminated with `OOMKilled`. You check the Pod's YAML and it has `limits: memory: 2Gi`. You check your APM/Prometheus, and the application's JVM heap usage never exceeded 1Gi. Why did the Linux kernel kill the pod?", "The JVM heap is only one part of a Java process's memory footprint. Off-heap memory (Metaspace, thread stacks, direct byte buffers) and the OS page cache consume additional RAM. The Linux kernel (cgroups) enforces the Kubernetes `2Gi` limit on the *entire* container's memory footprint. If the JVM heap is 1Gi, but off-heap memory consumes 1.2Gi, the total is 2.2Gi. The kernel detects the cgroup violation and instantly issues a `SIGKILL` (OOMKilled). You must profile the off-heap memory or increase the container limit.", ["Kubernetes memory limits are enforced by the Linux kernel (cgroups) on the total container footprint", "JVM heap metrics ignore off-heap memory (thread stacks, direct buffers, metaspace)", "The total OS footprint exceeded 2Gi, triggering an uncatchable `SIGKILL` from the kernel"], ["The pod ran out of oxygen"]),
    ("B61_2_3", "implement", "medium", "implement", ["Kubernetes Core"], "How do you implement high availability for a deployment so that if an entire AWS Availability Zone (AZ) goes offline, your application stays up?", "Setting `replicas: 3` is not enough; the Kubernetes scheduler might randomly place all 3 pods on 3 nodes that happen to be in the exact same `us-east-1a` AZ. To guarantee AZ redundancy, you must implement `topologySpreadConstraints`. You configure the constraint to spread pods evenly across the `topologyKey: topology.kubernetes.io/zone`. The scheduler will force the 3 pods to be placed in `us-east-1a`, `1b`, and `1c`. If AZ `1a` physically burns down, the other 2 pods in different datacenters will continue serving traffic seamlessly.", ["Relying on random scheduling does not guarantee geographic distribution", "Implement `topologySpreadConstraints` keyed on the Availability Zone label", "Forces the scheduler to evenly distribute replicas across physical data centers (AZs)"], ["You wrap the pods in fireproof blankets"]),
    ("B61_2_4", "tradeoff", "hard", "tradeoff", ["Kubernetes Core"], "What is the operational tradeoff of setting CPU Limits on Kubernetes Pods versus only setting CPU Requests?", "CPU Requests guarantee minimum compute scheduling. Setting CPU Limits restricts the pod from using idle CPU cycles on the node. The severe tradeoff of CPU Limits is 'CFS Throttling'. The Linux Completely Fair Scheduler measures CPU time in small slices (e.g., 100ms). If a multi-threaded app bursts and uses its quota in 20ms, the kernel strictly pauses/throttles all threads for the remaining 80ms, causing massive latency spikes (e.g., a 10ms API call suddenly takes 300ms). Removing CPU limits eliminates CFS throttling and allows apps to burst dynamically, but risks a 'Noisy Neighbor' consuming all node CPU if not carefully monitored.", ["CPU Limits trigger Linux CFS (Completely Fair Scheduler) quota throttling", "Causes artificial, severe latency spikes when multi-threaded apps burst over their micro-second quota", "Tradeoff: Removing limits stops throttling and boosts performance, but risks Noisy Neighbor resource starvation"], ["CPU limits make the server spin slower"]),
    ("B61_2_5", "scenario", "hard", "scenario", ["Kubernetes Core"], "During a massive traffic spike, the Horizontal Pod Autoscaler (HPA) scales your deployment from 5 to 50 pods. However, the pods stay in a `Pending` state. The Cluster Autoscaler does not spin up new EC2 nodes. You check the cluster, and there is plenty of CPU/RAM available on the existing nodes, but the scheduler refuses to place the pods. Why?", "This is likely caused by an IP Address Exhaustion in the VPC/Subnet or an Elastic Network Interface (ENI) limit on the EC2 instances. In AWS EKS (using the AWS VPC CNI), every single Pod requires a real, routable IP address from the VPC subnet. If the subnet is a `/24` (256 IPs), and you scale up 50 pods, you might simply run out of IP addresses. The scheduler cannot place the pod because the CNI plugin cannot assign an IP. The Cluster Autoscaler won't provision new nodes because the issue isn't compute/RAM capacity, it's network exhaustion.", ["AWS VPC CNI assigns native VPC IP addresses to every individual pod", "The underlying subnet ran out of available IP addresses (CIDR exhaustion), or the node hit its ENI limits", "Cluster Autoscaler doesn't scale on IP exhaustion; it only scales on CPU/RAM constraints"], ["The scheduler was on a lunch break"]),
    ("B61_2_6", "explain", "medium", "explain", ["Kubernetes Core"], "Explain the difference between a `LivenessProbe` and a `ReadinessProbe` in Kubernetes.", "A `ReadinessProbe` checks if the application is fully booted, connected to the DB, and ready to accept HTTP traffic. If it fails, Kubernetes stops sending traffic to the pod (removes it from the Service endpoint), but leaves the pod running so it can recover. A `LivenessProbe` checks if the application is deadlocked or frozen. If a LivenessProbe fails, Kubernetes assumes the container is irreparably broken and aggressively sends a `SIGKILL` to destroy and restart the pod. Using a LivenessProbe to check a DB connection is a catastrophic anti-pattern: if the DB goes down, Kubernetes will murder every single pod in the cluster simultaneously.", ["Readiness: Checks if pod can accept traffic. Failure removes it from the Load Balancer/Service.", "Liveness: Checks if pod is deadlocked. Failure causes Kubernetes to MURDER and restart the pod.", "Anti-pattern: Tying Liveness to external DBs causes cascading cluster reboots if the DB blips"], ["Liveness means it has a heartbeat, readiness means it brushed its teeth"]),
    ("B61_2_7", "concept", "easy", "concept", ["Kubernetes Core"], "What is `etcd` in the context of the Kubernetes Control Plane?", "`etcd` is the highly-available, distributed Key-Value store that acts as the 'brain' or source-of-truth for the entire Kubernetes cluster. It stores the state of everything: every pod, secret, configmap, and deployment. If `etcd` goes down or loses quorum (e.g., losing 2 out of 3 master nodes), the entire Kubernetes API freezes. Running pods will continue to serve traffic, but you cannot deploy, scale, or delete anything until `etcd` is restored from a backup.", ["The highly-available, distributed Key-Value store holding the cluster's complete state", "The absolute source of truth for the API server", "If etcd fails/loses quorum, the API freezes and no cluster mutations can occur"], ["etcd stands for extra terrestrial cd-rom"]),
    ("B61_2_8", "diagnose", "medium", "debugging", ["Kubernetes Core"], "A developer deploys a new `DaemonSet` to run a logging agent on every node in the cluster. However, they notice the agent is not running on the 3 Master (Control Plane) nodes. Why?", "By default, Master/Control Plane nodes have a `Taint` applied to them (e.g., `node-role.kubernetes.io/master:NoSchedule`). This prevents regular application workloads from being scheduled on the critical master nodes, protecting their CPU/RAM. For a `DaemonSet` to run on a tainted node, the developer must explicitly configure a `Toleration` in the DaemonSet YAML that explicitly matches and ignores that specific master taint.", ["Master/Control plane nodes are protected by `Taints` (e.g., `NoSchedule`)", "Taints repel pods to protect critical cluster infrastructure from being starved by workloads", "The DaemonSet must be updated with a matching `Toleration` to schedule on the master nodes"], ["Master nodes don't need logging because they never make mistakes"]),
    ("B61_2_9", "architecture", "hard", "architecture", ["Kubernetes Core"], "How do you architect a Kubernetes cluster to handle 'Graceful Node Shutdown' (e.g., an AWS Spot Instance termination warning)?", "Spot instances give a 2-minute warning before physically terminating. If a node suddenly vanishes, long-running HTTP requests and database connections are severed, causing user errors. You must run a daemon (like AWS Node Termination Handler). When it detects the 2-minute warning via the EC2 metadata API, it automatically issues a `kubectl cordon` and `kubectl drain` on the node. The node stops accepting new pods. Existing pods receive a `SIGTERM`. The application code catches the `SIGTERM`, stops accepting new HTTP requests, finishes processing active requests, and exits cleanly before the 2-minute hardware termination occurs.", ["Must intercept the cloud provider's hardware termination signal (e.g., AWS Node Termination Handler)", "Automation instantly Cordons (stops new pods) and Drains (evicts current pods) the node", "Pods receive `SIGTERM` and must execute graceful application shutdown logic to finish active requests"], ["You ask the AWS CEO for a 5-minute extension"]),
    ("B61_2_10", "tradeoff", "hard", "tradeoff", ["Kubernetes Core"], "What is the tradeoff of using a Kubernetes `Custom Resource Definition` (CRD) + Operator pattern versus managing external infrastructure via Terraform?", "An Operator allows you to declare external resources (like an AWS RDS Database) directly in Kubernetes YAML alongside your application code. The Operator continuously watches the state and reconciles it. The massive benefit is developer self-service and unified tooling (everything is just `kubectl apply`). The severe tradeoff is complexity and blast radius. Operators are highly complex Go programs running inside your cluster. A bug in the Operator's reconciliation loop can accidentally delete production databases automatically. Terraform requires a separate CI/CD pipeline, but provides a human-readable `terraform plan` phase, guaranteeing safe, reviewed, and predictable infrastructure changes.", ["Operator: Unified YAML workflow, continuous drift reconciliation, excellent dev self-service", "Tradeoff: Extremely complex to build/maintain, lacks a 'dry-run/plan' phase, risking catastrophic automated deletions", "Terraform: Requires separate pipelines but provides safe, human-reviewed execution plans"], ["Operators wear headsets, Terraform wears hard hats"]),

    # Group 3: Infrastructure as Code (Terraform)
    ("B61_3_1", "concept", "medium", "concept", ["Terraform"], "What is a Terraform State file (`terraform.tfstate`), and why must it be stored remotely (e.g., S3) rather than committed to Git?", "The State file acts as a mapping database between the Terraform code and the actual real-world cloud resources (e.g., mapping `aws_instance.web` to `i-12345678`). It must never be committed to Git for two critical reasons: 1) Security: The state file stores sensitive infrastructure data and secrets (database passwords, private keys) in absolute plaintext. 2) Collaboration: Remote backends (like S3 + DynamoDB) provide State Locking. If two developers run `terraform apply` simultaneously, the lock prevents a race condition that would corrupt the state file.", ["Maps declarative HCL code to real-world cloud resource IDs", "Security: Contains plaintext secrets and passwords; committing to Git is a massive breach", "Collaboration: Remote backends provide State Locking (Mutex) to prevent concurrent corruption"], ["The state file tells you what US state the server is in"]),
    ("B61_3_2", "diagnose", "hard", "debugging", ["Terraform"], "A developer manually deleted a critical S3 bucket via the AWS Web Console. The bucket is still defined in the Terraform code. When you run `terraform plan`, Terraform errors out with `AccessDenied` or `NoSuchBucket` instead of proposing to recreate it. Why did the drift detection fail, and how do you fix it?", "When Terraform runs a plan, its first step is the 'Refresh' phase: it calls the AWS API for every resource in the state file to check its current status. Because the bucket was manually deleted, the AWS API returns an error when Terraform tries to read its metadata. If the IAM permissions or the API behaves unexpectedly, the refresh phase crashes before the plan can even execute. To fix this, you must manually remove the ghost resource from the state file using `terraform state rm aws_s3_bucket.my_bucket`. On the next `plan`, Terraform will see it missing from state, see it in the code, and cleanly propose recreating it.", ["Manual deletion caused the API 'Refresh' phase to crash when polling the missing resource", "Terraform cannot plan if the refresh phase throws unhandled API errors", "Fix by explicitly removing the ghost resource via `terraform state rm`, forcing a clean recreation"], ["Terraform is emotionally attached to the bucket and is crying"]),
    ("B61_3_3", "implement", "medium", "implement", ["Terraform"], "How do you securely pass a database password into a Terraform deployment without hardcoding it in the `.tf` files or exposing it in CI/CD console logs?", "You must use a Secrets Manager (like AWS Secrets Manager or HashiCorp Vault) and Data Sources. You manually create the secret in AWS via the console/CLI. In Terraform, you use the `data \"aws_secretsmanager_secret_version\"` block to dynamically fetch the password at runtime during `terraform apply`. You pass this data reference to the RDS resource. Crucially, you must flag the variable or output as `sensitive = true` in Terraform to instruct the CLI engine to redact the plaintext password from the terminal console logs.", ["Never hardcode; use a `data` block to fetch dynamically from AWS Secrets Manager or Vault at runtime", "Pass the dynamic reference directly to the RDS resource block", "Mark outputs/variables as `sensitive = true` to mask the value in CI/CD terminal logs"], ["You write the password backward in the code"]),
    ("B61_3_4", "tradeoff", "medium", "tradeoff", ["Terraform"], "What is the tradeoff of structuring Terraform using one massive 'Monolithic' State file versus slicing it into dozens of 'Micro-States' (e.g., separating Network state from Database state)?", "A Monolithic state is simple: you can easily reference outputs between resources (the EC2 instance reads the VPC ID natively). The severe tradeoff is Blast Radius and Speed. A typo in the EC2 code could accidentally delete the Database, and running `plan` takes 15 minutes because it refreshes 5,000 resources. Slicing into Micro-States isolates risk (Network code cannot delete the Database) and runs in seconds. The tradeoff is complexity: you must use `terraform_remote_state` data sources to manually pass IDs (like VPC ID) across the isolated state boundaries, creating fragile dependencies.", ["Monolith: Simple cross-referencing, but massive blast radius (one typo deletes the DB) and slow execution", "Micro-States: Tiny blast radius and fast execution", "Tradeoff: Requires complex cross-state data passing (`terraform_remote_state`) creating dependency hell"], ["Monolithic state requires a monolithic monitor to read"]),
    ("B61_3_5", "scenario", "hard", "scenario", ["Terraform"], "You are tasked with refactoring a messy Terraform codebase. You rename `aws_instance.web_server` to `aws_instance.frontend_node` in the `.tf` file. When you run `terraform plan`, Terraform proposes to DESTROY the running production EC2 instance and CREATE a brand new one. How do you prevent this destruction?", "Terraform maps the logical HCL identifier (`web_server`) to the state file. By renaming it, Terraform assumes you deleted the old resource and added a totally new one. To safely rename resources without triggering hardware destruction, you must use the `moved` block (introduced in TF 1.1) in your code: `moved { from = aws_instance.web_server \n to = aws_instance.frontend_node }`. Alternatively, use the CLI command: `terraform state mv aws_instance.web_server aws_instance.frontend_node`. Terraform will simply update the logical mapping in the state file and execute zero infrastructure changes.", ["Renaming the logical identifier causes Terraform to plan a Destroy/Create cycle", "Use the declarative `moved { from = ... to = ... }` block in the code (TF 1.1+)", "Alternatively, use `terraform state mv` to manually update the mapping in the state file, avoiding hardware destruction"], ["You ask the EC2 instance nicely to change its name without rebooting"]),
    ("B61_3_6", "explain", "medium", "explain", ["Terraform"], "Explain the concept of 'Drift' in Infrastructure as Code, and how Terraform remediates it.", "Drift occurs when the actual real-world state of the cloud infrastructure deviates from the declarative code in version control. This usually happens when a developer urgently logs into the AWS Console and manually opens port 22 in a Security Group (ClickOps). When Terraform runs its next `plan`, it performs a 'Refresh', comparing the real-world API state to the `.tf` files. It detects the drift (the unauthorized open port) and proposes a plan to remediate it by explicitly removing the manual rule, forcing the infrastructure back into absolute alignment with the code.", ["Drift is when manual changes (ClickOps) cause real-world infrastructure to deviate from the Git code", "Terraform detects this during the 'Refresh' phase of a plan", "Terraform remediates drift by automatically undoing manual changes, forcing the cloud back to the declared code state"], ["Drift is when the server racks slide around during an earthquake"])
]

def run_batch():
    with open(OUT, "a", encoding="utf-8") as f:
        for q in Q:
            rec = {
                "primary_role": ROLE,
                "applicable_roles": ["Backend Developer", "Cloud Architect"],
                "primary_skill": q[4][0],
                "secondary_skills": q[4][1:] if len(q[4]) > 1 else [],
                "technology": "AWS / Terraform",
                "topic": q[4][0] if len(q[4]) > 0 else "General",
                "category": "Infrastructure",
                "intent": q[1],
                "difficulty": q[2],
                "question_type": q[3],
                "question": q[5],
                "expected_answer": q[6],
                "evaluation_rubric": {
                    "strong_indicators": q[7],
                    "weak_indicators": q[8]
                },
                "id": str(uuid.uuid4()),
                "source": "Antigravity_Internal_Knowledge",
                "provenance_type": "researched_generated",
                "dataset_version": "v2",
                "status": "active"
            }
            f.write(json.dumps(rec) + "\n")
            
    print(f"Appended {len(Q)} questions (Batch 61 Part 1).")

if __name__ == "__main__":
    run_batch()
