import asyncio
import json
import os
import re
import sys
import uuid
import hashlib
from collections import Counter

from dotenv import load_dotenv
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
load_dotenv()

BACKEND_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_DIR = os.path.join(BACKEND_DIR, "data")
OUT = os.path.join(DATA_DIR, "interview_question_bank_v2_generated.jsonl")

ROLE = "Frontend Developer"
LEAK = re.compile(r"(generate a question|generate \d+ questions|return only json|phase 4c gap plan|"
                  r"generation batch|candidate generation|system instructions|do not proceed|"
                  r"awaiting authorization|minimum target|generation pipeline|"
                  r"batch \d+ generation|expected answer|strong indicator|weak indicator|as an ai|"
                  r"here is the question|\bprompt text\b)", re.I)

Q = [
    # React Internals & Edge Cases
    ("B64_4_1", "concept", "hard", "concept", ["React Architecture"], "In React Concurrent Mode, how does the Fiber architecture allow the browser to remain responsive during an extremely heavy 500ms component render?", "In legacy React (Stack Reconciler), a render was a single, massive, synchronous JavaScript function call. Once started, it physically could not be stopped, freezing the browser's main thread for 500ms. The Fiber architecture rewrote the render engine into a 'Linked List' of units of work (Fibers). React processes a Fiber, then explicitly checks `requestIdleCallback` (or its internal scheduler) to see if the browser needs to paint the screen or handle a user click. If the browser needs the thread, React pauses the render, yields control back to the OS, and resumes the linked list exactly where it left off on the next frame.", ["Legacy Stack Reconciler executed rendering synchronously, blocking the main thread entirely", "Fiber breaks rendering into interruptible units of work (a Linked List of Fibers)", "React yields to the browser's scheduler between Fibers to process clicks or paints, achieving Concurrent Mode"], ["Fiber means the components are made of optical glass"]),
    ("B64_4_2", "diagnose", "medium", "debugging", ["React Architecture"], "You write a `useEffect` that sets a `setInterval` to increment a counter every second: `setInterval(() => setCount(count + 1), 1000)`. The counter goes from 0 to 1, and then stays at 1 forever. Why?", "This is the classic 'Stale Closure' bug. The arrow function inside `setInterval` was created during the VERY FIRST render, when the `count` variable was `0`. The interval loop repeatedly executes `setCount(0 + 1)`. Even though the component re-renders and the true state becomes 1, the interval is still permanently trapped using the closure from the first render. To fix this, you must use the functional updater pattern: `setCount(prevCount => prevCount + 1)`. This guarantees React passes the most recent state into the function, completely bypassing the stale closure.", ["Closures trap the exact state of variables at the moment they were created", "The interval continuously executes `setCount(0 + 1)` because it only saw the first render's scope", "Fix: Use the functional updater `setCount(prev => prev + 1)` or add `count` to the dependency array and clear the interval"], ["The setInterval function ran out of battery"]),
    ("B64_4_3", "implement", "medium", "implement", ["React Architecture"], "How do you implement an 'Error Boundary' in React to prevent a single component throwing `Cannot read property 'map' of undefined` from crashing the entire application into a white screen?", "If any component throws an unhandled error during rendering, React purposefully unmounts the ENTIRE component tree to prevent corrupted state, causing the 'White Screen of Death'. To prevent this, you must implement a Class Component that defines the `static getDerivedStateFromError(error)` lifecycle method. You wrap your application (or specific sections) in this `<ErrorBoundary>` component. When a child throws, the boundary catches it, updates its internal state to `hasError: true`, and renders a graceful fallback UI (like 'Something went wrong') while preserving the rest of the application.", ["Unhandled render errors cause React to unmount the entire tree (White Screen of Death)", "Fix: Create a Class Component implementing `getDerivedStateFromError`", "Wrap vulnerable trees in this component to catch errors and render a Fallback UI instead of crashing"], ["You just wrap the whole app in a try/catch block"]),
    ("B64_4_4", "tradeoff", "hard", "tradeoff", ["React Architecture"], "What is the architectural tradeoff of using `useLayoutEffect` versus `useEffect` for DOM mutations in React?", "When you use `useEffect`, React allows the browser to mathematically Paint the screen (showing pixels to the user), and THEN it runs your effect asynchronously. If your effect reads the DOM and mutates it (like calculating a tooltip's height and shifting it), the user sees a visible flicker. `useLayoutEffect` completely halts the browser's Paint phase. It runs synchronously immediately after React mutates the DOM, but BEFORE the browser is allowed to show it to the user. The tradeoff is perfectly smooth, flicker-free DOM mutations at the severe cost of blocking the main thread and delaying the initial visual render (hurting LCP/INP).", ["`useEffect` runs asynchronously AFTER the browser paints, causing visual flickering if it mutates the DOM", "`useLayoutEffect` runs synchronously BEFORE the paint, preventing flickering", "Tradeoff: `useLayoutEffect` strictly blocks the main thread and delays visual rendering, hurting performance metrics"], ["useLayoutEffect changes the CSS layout, useEffect changes the JavaScript"]),
    ("B64_4_5", "scenario", "medium", "scenario", ["React Architecture"], "You enable React `StrictMode` in your local environment. Suddenly, every single `useEffect` runs twice on mount, and your API is being called twice. A developer attempts to fix this by adding a `useRef` boolean flag to block the second call. Why is this a terrible architectural fix?", "React 18 intentionally double-invokes effects in `StrictMode` to simulate a component immediately unmounting and remounting. This proves that your application is resilient to Concurrent Mode and Fast Refresh. If you hack a `useRef` to block the second call, you are actively hiding a severe memory leak or race condition. The correct fix is to write a proper Cleanup Function (`return () => {...}`) inside the `useEffect`. If the effect opens a WebSocket, the cleanup must close it. If it fetches data, the cleanup must call `AbortController.abort()`. When written correctly, the double-invocation is harmless.", ["StrictMode intentionally double-invokes effects to expose missing cleanup logic and race conditions", "Hacking it with a `useRef` flag masks the underlying memory leak or unhandled promise", "Fix: Write a proper Cleanup Function (`return () => cleanup()`) to safely tear down the first effect"], ["Strict mode means you can't use any semicolons in the code"]),

    # Testing & Quality
    ("B64_4_6", "concept", "medium", "concept", ["Testing"], "In frontend E2E testing (e.g., Cypress/Playwright), what is 'Deterministic Flakiness', and why does hardcoding `cy.wait(2000)` cause it?", "Flakiness occurs when a test passes locally but randomly fails in CI. A junior developer often 'fixes' this by hardcoding a 2-second sleep to wait for an API call to finish. This is catastrophic. If the CI server is under heavy load, the API might take 2.1 seconds, causing the test to fail anyway (False Negative). Alternatively, if the API takes 50ms, the test wastes 1.95 seconds doing nothing, drastically bloating the CI pipeline time. Deterministic testing NEVER uses time. You must wait for *State*. You explicitly instruct the testing tool to wait for the specific network intercept to resolve (`cy.wait('@apiCall')`), or wait for the loading spinner DOM element to disappear.", ["Hardcoded sleeps (`wait(2000)`) are brittle because network and CPU latency varies wildly in CI environments", "Causes random test failures (if latency > 2s) and massive time waste (if latency < 2s)", "Fix: Deterministically wait for specific State changes (DOM elements appearing/disappearing) or explicit Network Intercepts"], ["Deterministic flakiness means the code has dandruff"]),
    ("B64_4_7", "diagnose", "hard", "debugging", ["Testing"], "You use Jest and JSDOM to test a React component that relies on `window.matchMedia` and `ResizeObserver`. The test suite instantly crashes with `TypeError: window.matchMedia is not a function`. Why?", "JSDOM is not a real browser; it is a pure JavaScript simulation of the DOM running inside Node.js. It does not possess a rendering engine, layout engine, or CSSOM. Therefore, APIs that require physical geometry (like `ResizeObserver`, `getBoundingClientRect`, or `IntersectionObserver`) or CSS parsing (like `matchMedia`) fundamentally do not exist in JSDOM. To fix this and prevent the crash, you must strictly Mock these APIs in your Jest setup file before the tests run (e.g., `window.matchMedia = jest.fn().mockImplementation(...)`), or upgrade to a real browser test runner like Playwright/Cypress Component Testing.", ["JSDOM is a headless Node.js simulation, not a real browser engine", "It completely lacks layout, geometry, and CSS APIs (`matchMedia`, `ResizeObserver`)", "Fix: Explicitly mock these APIs in the test setup, or migrate to true browser-based component testing"], ["JSDOM requires a graphics card to run"]),
    ("B64_4_8", "implement", "medium", "implement", ["Testing"], "How do you implement Mock Service Worker (MSW) in a frontend test suite, and why is it architecturally superior to using `jest.mock('axios')`?", "Using `jest.mock('axios')` is deeply flawed because it tests the *implementation detail*. If your team refactors the app to use `fetch()` instead of `axios`, every single test instantly breaks, even though the app works perfectly. MSW operates at the network level. It uses a Service Worker to literally intercept outbound HTTP requests emitted by the browser or Node.js, regardless of what library sent them. You define handlers (`http.get('/api/users', () => HttpResponse.json(...))`). This decouples your tests from the specific HTTP client library, testing the actual network contract.", ["`jest.mock('axios')` tightly couples tests to the specific HTTP library (implementation detail)", "Mock Service Worker (MSW) intercepts requests at the fundamental network level via a Service Worker", "Provides robust, library-agnostic tests that survive refactoring (e.g., swapping `axios` for `fetch`)"], ["MSW uses a physical ethernet cable to intercept the tests"]),
    ("B64_4_9", "tradeoff", "hard", "tradeoff", ["Testing"], "What is the tradeoff of relying heavily on Visual Regression Testing (e.g., Percy, Chromatic, pixel-diffing) versus standard DOM Snapshot Testing in Jest?", "Jest DOM snapshots output a massive JSON text file representing the HTML tree. They are famously brittle; changing a single CSS class name (`mr-2` to `mr-4`) breaks the text snapshot, even if the UI looks identical, leading developers to blindly hit 'Update Snapshot' without looking. Visual Regression testing actually spins up a real browser, takes a physical PNG screenshot of the component, and compares pixels. It ignores underlying code changes if the pixels look the same. The severe tradeoff is that Visual Testing is astronomically slower, requires expensive paid SaaS infrastructure to handle different OS/Browser rendering quirks (anti-aliasing differences), and is highly susceptible to flakiness from microscopic font rendering changes.", ["DOM Snapshots (Jest) are fast but highly brittle to trivial HTML/CSS class changes", "Visual Regression (Pixel diffing) accurately tests the human experience and ignores code refactors", "Tradeoff: Visual diffing is incredibly slow, expensive, and flaky due to OS-level font rendering and anti-aliasing quirks"], ["Visual regression means staring at the screen until your eyes hurt"]),

    # Advanced CSS & DOM
    ("B64_4_10", "concept", "medium", "concept", ["CSS Architecture"], "What is the `contain: strict` CSS property, and how does it drastically improve rendering performance for a heavy DOM element that constantly updates?", "When a standard DOM element changes its width or height, the browser's layout engine must traverse the entire DOM tree to ensure that the change didn't push or pull other sibling or parent elements out of place. This 'Style Recalculation' is incredibly expensive. `contain: strict` explicitly tells the browser rendering engine that this specific element is mathematically isolated from the rest of the page. It guarantees that nothing inside the element will ever affect the layout of the outside page, and vice versa. The browser can now instantly render updates to that element without recalculating the layout of the entire document.", ["Standard DOM changes trigger massive page-wide layout recalculations", "`contain: strict` mathematically isolates the element's layout, style, and paint from the rest of the document", "Allows the browser to render high-frequency updates inside the element without touching the parent DOM tree"], ["Contain strict prevents hackers from stealing the CSS"]),
    ("B64_4_11", "diagnose", "hard", "debugging", ["CSS Architecture"], "You have a small, scrollable `div` (a modal) overlaying the main page. When the user scrolls to the absolute bottom of the modal and keeps scrolling their mouse wheel, the main page underneath suddenly starts scrolling. How do you prevent this 'Scroll Chaining'?", "Scroll Chaining (or Scroll Bounce) is a native browser feature designed to pass scroll events up the DOM tree when a child boundary is reached. To stop it, developers used to write complex JavaScript (`e.preventDefault()` on wheel events) which destroyed scroll performance. The modern, native CSS fix is to apply `overscroll-behavior: contain` (or `none`) to the scrollable modal container. This strictly instructs the browser's scroll engine to instantly discard any excess scroll events once the bottom of the container is reached, completely preventing the parent page from moving.", ["Scroll Chaining natively passes excess scroll events from a child up to the parent document", "Using JS `preventDefault` on scroll events destroys native scrolling performance", "Fix: Use CSS `overscroll-behavior: contain` on the modal to natively swallow excess scroll events"], ["You just put a heavy rock on the bottom of the modal"]),
    ("B64_4_12", "implement", "medium", "implement", ["CSS Architecture"], "How do you correctly implement CSS `will-change: transform` to optimize a complex animation, and why is it dangerous to leave it applied permanently?", "You apply `will-change: transform` to an element shortly *before* an animation begins (e.g., on `:hover`). This gives the browser's GPU an advance warning to allocate a dedicated Compositor Layer in VRAM for that element, guaranteeing 60FPS when the animation actually triggers. However, every Compositor Layer consumes significant physical GPU memory. If you apply `will-change: transform` globally (e.g., `* { will-change: transform }`), the browser will attempt to allocate millions of GPU layers, instantly crashing the graphics card or causing catastrophic stuttering. You must remove the property immediately after the animation finishes.", ["`will-change` warns the browser to allocate a dedicated GPU Compositor Layer for the element", "Provides buttery smooth animations by pre-calculating the layer", "Danger: Leaving it on permanently exhausts GPU VRAM, crashing the browser or destroying performance"], ["Will-change asks the user if they want to change the animation"]),

    # Advanced Browser APIs
    ("B64_4_13", "tradeoff", "hard", "tradeoff", ["Browser APIs"], "What is the tradeoff of using the `IntersectionObserver` API versus binding an event listener directly to the `window.onscroll` event for infinite scrolling?", "Binding to `window.onscroll` fires a JavaScript callback hundreds of times a second. If you calculate `element.getBoundingClientRect()` inside that callback to check if an element is visible, you force synchronous Layout Thrashing hundreds of times a second, utterly destroying the frame rate. `IntersectionObserver` offloads this entirely. You declare a target, and the browser's internal engine asynchronously monitors its position off the main thread. It only fires your JS callback EXACTLY when the element crosses the threshold. The only tradeoff is that `IntersectionObserver` is asynchronous; it does not provide pixel-perfect real-time scroll tracking, making it unsuitable for parallax animations tied directly to the scrollbar.", ["`window.onscroll` with `getBoundingClientRect` causes catastrophic Layout Thrashing and main-thread blocking", "`IntersectionObserver` calculates visibility asynchronously off the main thread, providing massive performance gains", "Tradeoff: It only fires on threshold crossings, making it useless for continuous, pixel-perfect parallax animations"], ["Intersection observer sits at a traffic light and watches cars"]),
    ("B64_4_14", "scenario", "medium", "scenario", ["Browser APIs"], "Your Service Worker is installed and active. You push an update to `service-worker.js`. The user refreshes the page, but the old Service Worker is still controlling the page, and the new UI assets are not loading. Why?", "By design, a Service Worker will not instantly take over a page if an older version is currently controlling open tabs. The new SW enters the 'Waiting' phase to prevent breaking the currently running application with mismatched assets. It will remain in the 'Waiting' state forever until ALL tabs controlled by the old SW are physically closed by the user (a refresh is not enough). To force the update programmatically, the new Service Worker must explicitly call `self.skipWaiting()` during the `install` phase, and the client must listen for the update and call `window.location.reload()` to claim the new clients.", ["A new Service Worker enters the 'Waiting' state if the old SW is currently controlling ANY open tabs", "A simple page refresh does NOT kill the old SW; all tabs must be closed", "Fix: Programmatically call `self.skipWaiting()` in the SW and reload the clients to force the immediate update"], ["The service worker took a coffee break"]),

    # Security Edge Cases
    ("B64_4_15", "diagnose", "hard", "debugging", ["Web Security"], "You configure your CDN to send the header `Content-Security-Policy: default-src 'self'; script-src 'self'`. However, a penetration tester successfully executes an XSS attack by exploiting a vulnerability in a third-party library hosted on your own domain. How do you stop this without removing the library?", "The CSP `script-src 'self'` prevents attackers from loading scripts from external malicious domains. However, if the attacker finds a way to execute an inline `<script>alert(1)</script>` via a DOM injection vulnerability, `'self'` will happily allow the inline script to run unless explicitly blocked. WAIT, actually `script-src 'self'` BLOCKS inline scripts by default. The real vulnerability here is a 'JSONP endpoint' or an 'AngularJS Sandbox Escape' hosted on your own domain. If you host an endpoint that echoes user input (like a JSONP callback), the attacker can inject `<script src=\"/api/jsonp?callback=malicious_code\"></script>`. Because the script originates from `/api` (which is `'self'`), the CSP blindly allows it. To fix this, you must upgrade the CSP to use strict Nonces (`script-src 'nonce-123'`) or Hashes (`script-src 'sha256-...'`), which completely invalidates the `'self'` bypass.", ["`script-src 'self'` is highly vulnerable if your domain hosts any endpoint that echoes user input (JSONP, uploaded files)", "The attacker points the malicious script tag to your own vulnerable endpoint, perfectly bypassing the `'self'` CSP rule", "Fix: Abandon `'self'` and implement Strict CSP using cryptographic Nonces or Hashes for all script tags"], ["The penetration tester broke into the server room physically"]),
    ("B64_4_16", "concept", "medium", "concept", ["Web Security"], "What is 'Subresource Integrity' (SRI) in HTML, and what catastrophic supply-chain attack does it prevent?", "Modern frontend applications heavily rely on CDNs (like `unpkg.com` or `cdnjs`) to load libraries like React or Lodash: `<script src=\"https://cdn.example.com/lodash.js\">`. If a hacker breaches the CDN server and silently replaces `lodash.js` with a malicious script that steals credit cards, every single website using that CDN is instantly compromised (Supply-Chain Attack). Subresource Integrity (SRI) fixes this. You generate a cryptographic hash of the exact, safe file and add it to the tag: `<script src=\"...\" integrity=\"sha384-abc...\">`. When the browser downloads the file from the CDN, it hashes it locally. If the hacker altered even a single byte, the hash mismatches, and the browser violently blocks the execution.", ["Loading scripts from third-party CDNs exposes the app to Supply-Chain Attacks if the CDN is breached", "SRI attaches a cryptographic hash of the file to the `<script>` tag (`integrity=\"...\"`)", "The browser hashes the downloaded file; if it mismatches the attribute, it blocks execution, neutralizing the attack"], ["SRI means the server has high moral integrity"]),

    # Front-end Platform Architecture
    ("B64_4_17", "implement", "hard", "implement", ["UI Architecture"], "How do you implement a 'Strangler Fig' pattern to slowly migrate a massive 10-year-old AngularJS frontend to React without stopping product development?", "You cannot do a 'Big Bang' rewrite; it takes years and halts business value. The Strangler Fig pattern migrates the app route-by-route or component-by-component. You set up a reverse proxy (like Nginx) in front of the application. The proxy routes traffic to the old AngularJS app by default. You build the new React app. As you finish migrating the '/billing' page, you update the proxy to route '/billing' to the React app. Alternatively, at the micro-level, you use wrappers (like `ng-react`) to mount React components directly inside the legacy AngularJS DOM. Slowly, over months, the React 'fig tree' grows and replaces the old app, which is eventually 'strangled' and deleted.", ["Big Bang rewrites are highly dangerous and halt business delivery", "Strangler Fig replaces the app incrementally. Fix 1 (Macro): Use a Reverse Proxy to route specific URLs to the new app", "Fix 2 (Micro): Use adapter libraries to mount modern React components inside the legacy framework's DOM"], ["Strangler fig means you strangle the developers who wrote the old code"]),
    ("B64_4_18", "scenario", "medium", "scenario", ["UI Architecture"], "You configure Webpack to output CSS modules: `[name]__[local]--[hash:base64:5]`. Your app works perfectly locally. In production, users report that half the website has zero styling. You notice the HTML is requesting `button_1A2b3.css` but the stylesheet contains `.button_X8y9Z`. Why did the hashes mismatch?", "This is a severe build reproducibility issue, often caused by inconsistent OS-level paths or differing dependency versions across the build nodes. When Webpack calculates the `hash:base64:5`, it hashes the *absolute file path* of the module by default in some configurations. If Node A builds the JS in `/var/jenkins/workspace/frontend`, and Node B builds the CSS extraction in `/tmp/build`, the hashes diverge. To fix this, you must strictly configure Webpack to use stable, deterministic hash seeds (e.g., using relative paths or explicit content hashes `[contenthash]`) so the output is identical regardless of which CI server compiles the code.", ["CSS Module hashes often rely on the absolute file path of the module during compilation", "If different CI servers or parallel build nodes use different absolute paths, the generated hashes will diverge", "Fix: Configure Webpack to use deterministic hashing (`[contenthash]`) or relative paths"], ["The hash algorithm was written in ancient Greek"]),

    # State Management & Caching
    ("B64_4_19", "concept", "medium", "concept", ["State Management"], "In the context of Redux or Zustand, what is 'State Normalization' and how does it prevent 'Stale Data' bugs in deeply nested structures?", "If you fetch a blog post that contains nested comments `post: { id: 1, comments: [{id: 5, author: 'Alice'}] }`, and you later fetch a user profile for Alice, you now have two completely separate copies of 'Alice' in your global state. If Alice changes her name, you must manually write complex code to find and update her name in both the profile tree AND the deeply nested comments tree. If you miss one, the UI shows stale data. 'State Normalization' flattens the state into relational lookup tables: `users: { 5: {name: 'Alice'} }`. The post now only holds references: `comments: [5]`. When Alice changes her name, you update exactly one single source of truth in the `users` table, and all UI components instantly reflect the change.", ["Nested data structures result in duplicate entities scattered across memory", "Mutating a duplicated entity requires traversing and updating every copy, or risking stale UI bugs", "Normalization flattens data into dictionary lookup tables by ID, ensuring a Single Source of Truth and O(1) updates"], ["State normalization means forcing all variables to be lowercase"]),
    ("B64_4_20", "tradeoff", "hard", "tradeoff", ["Data Fetching"], "What is the architectural tradeoff of using GraphQL with Apollo Client versus standard REST endpoints for a massive, highly-cached enterprise application?", "GraphQL provides phenomenal benefits: the client requests exactly the fields it needs, eliminating over-fetching, and Apollo provides a deeply normalized, automatic client-side cache out of the box. The severe tradeoff is HTTP Network Caching and CDNs. REST relies on distinct URLs (`GET /users/1`). A CDN (like Cloudflare) can easily cache this URL globally for 10 minutes. GraphQL sends EVERYTHING as a generic `POST /graphql` request with a complex query body. CDNs mathematically cannot cache POST requests or inspect the body effectively. Therefore, GraphQL heavily centralizes load on the backend application servers, bypassing global edge-caching infrastructure unless you implement extremely complex 'Persisted Queries'.", ["GraphQL eliminates over-fetching and provides automatic normalized client caching", "REST utilizes standard URLs, allowing massive global caching via CDNs (Cloudflare)", "Tradeoff: GraphQL uses generic `POST` requests, entirely breaking native HTTP/CDN edge caching"], ["GraphQL uses graphs instead of text"]),

    # Final Quirks
    ("B64_4_21", "diagnose", "medium", "debugging", ["TypeScript"], "A junior developer writes `const API_KEY = process.env.API_KEY || 'default'` in a React application bootstrapped with Vite. When deployed to production, the app crashes with `process is not defined`. Why?", "The `process.env` object is a Node.js specific global variable. It exists when the code is executed on the server, but it does NOT physically exist in the browser's JavaScript environment (`window`). In legacy Webpack apps, the bundler magically polyfilled or string-replaced `process.env` for you. Modern bundlers like Vite do not polyfill Node.js globals by default to save bloat. In Vite, you must strictly use `import.meta.env.VITE_API_KEY`. The bundler will statically analyze this specific syntax and hardcode the string into the final JavaScript bundle before sending it to the browser.", ["`process.env` is a Node.js backend global; it does not exist in browser JavaScript", "Legacy bundlers (Webpack) automatically polyfilled it, hiding the error", "Fix: Modern bundlers (Vite) require explicit syntax like `import.meta.env.VITE_VAR` for static string replacement"], ["The process ran away"]),
    ("B64_4_22", "concept", "hard", "concept", ["Browser APIs"], "What is the `requestAnimationFrame` (rAF) API, and why is it architecturally superior to `setInterval(..., 16)` for building a JavaScript game engine or animation?", "`setInterval(..., 16)` blindly executes the JavaScript function every 16 milliseconds, regardless of what the browser or monitor is doing. If the user's monitor is 144Hz, the animation looks jittery. If the browser is currently busy calculating a massive CSS layout, the interval fires anyway, causing massive frame dropping. Furthermore, if the user switches to a different tab, the interval keeps firing, draining the laptop battery. `requestAnimationFrame` aligns perfectly with the monitor's physical refresh rate (v-sync). It only executes the JS exactly when the browser is fully idle and ready to paint the next frame, and it automatically pauses entirely when the tab is hidden, saving CPU and battery.", ["`setInterval` is blind; it fires out of sync with monitor refresh rates, causing stuttering and battery drain on hidden tabs", "`requestAnimationFrame` is natively synced to the monitor's v-sync and the browser's paint cycle", "It guarantees the smoothest possible animation and automatically pauses when the tab loses focus"], ["requestAnimationFrame requests permission from the user before showing the animation"])
]

def run_batch():
    # Load all existing records to do deduplication
    with open(OUT, "r", encoding="utf-8") as f:
        existing = [json.loads(line) for line in f if line.strip()]

    print(f"Loaded {len(existing)} existing records.")
    
    for q in Q:
        if LEAK.search(q[5]) or LEAK.search(q[6]):
            print(f"PROMPT LEAK DETECTED in: {q[5]}")
            sys.exit(1)
            
    existing_texts = [ex["question"] for ex in existing]
    new_texts = [q[5] for q in Q]
    
    vec = TfidfVectorizer(stop_words="english", ngram_range=(1,2))
    all_texts = existing_texts + new_texts
    vec.fit(all_texts)
    
    existing_vecs = vec.transform(existing_texts)
    new_vecs = vec.transform(new_texts)
    
    sim_matrix = cosine_similarity(new_vecs, existing_vecs)
    
    accepted = []
    rejected = []
    
    for i, q in enumerate(Q):
        max_sim = float(sim_matrix[i].max()) if sim_matrix.shape[1] > 0 else 0
        if max_sim > 0.85:
            print(f"REJECTED (Sim: {max_sim:.2f}): {q[5][:50]}...")
            rejected.append(q)
        else:
            accepted.append(q)
            
    print(f"Accepted {len(accepted)} / {len(Q)} questions (Part 4).")
    
    new_records = []
    for q in accepted:
        rec = {
            "primary_role": ROLE,
            "applicable_roles": ["Frontend Engineer", "Software Engineer"],
            "primary_skill": q[4][0],
            "secondary_skills": q[4][1:] if len(q[4]) > 1 else [],
            "technology": "Frontend",
            "topic": q[4][0] if len(q[4]) > 0 else "General",
            "category": "Software Engineering",
            "intent": q[1],
            "difficulty": q[2],
            "question_type": q[3],
            "question": q[5],
            "expected_answer": q[6],
            "evaluation_rubric": {
                "strong_indicators": q[7],
                "weak_indicators": q[8]
            },
            "id": str(uuid.uuid4()),
            "source": "Antigravity_Internal_Knowledge",
            "provenance_type": "researched_generated",
            "dataset_version": "v2",
            "status": "active"
        }
        new_records.append(rec)
        
    with open(OUT, "a", encoding="utf-8") as f:
        for r in new_records:
            f.write(json.dumps(r) + "\n")
            
    # Final audit reporting
    with open(OUT, "r", encoding="utf-8") as f:
        final_existing = [json.loads(line) for line in f if line.strip()]
        
    role_counts = Counter(r["primary_role"] for r in final_existing)
    
    print("\n========================================")
    print("POST-BATCH AUDIT")
    print("========================================")
    print(f"Batch: 64")
    print(f"Target role: {ROLE}")
    print(f"Attempted: {len(Q)}")
    print(f"Accepted: {len(accepted)}")
    print(f"Rejected: {len(rejected)}")
    print(f"Replacement count: 0")
    print(f"Cumulative total: {len(final_existing)}")
    print(f"{ROLE} total: {role_counts[ROLE]}")

if __name__ == "__main__":
    run_batch()
