"""
Pydantic schemas for interview-related API requests and responses.
"""

from __future__ import annotations

from datetime import datetime
from typing import Any, Dict, List, Optional
from uuid import UUID

from pydantic import BaseModel, Field, field_validator, model_validator


class HealthCheckDetails(BaseModel):
    """Health check status of subcomponents."""
    database: str = Field(default="connected", description="Database status")
    ai_provider: str = Field(default="ready", description="AI Provider status")


class HealthResponse(BaseModel):
    """Response schema for GET /api/health."""
    status: str = Field(default="healthy", description="Service status")
    version: str = Field(default="1.0.0", description="Backend version")
    checks: HealthCheckDetails = Field(default_factory=HealthCheckDetails)


class StartInterviewRequest(BaseModel):
    """
    Request schema for starting a new interview.
    Requires only candidate_name and role/job_role.
    """

    candidate_name: str = Field(
        ...,
        min_length=2,
        max_length=255,
        description="Name of the candidate",
        examples=["Dinesh"],
    )
    role: str = Field(
        default="Software Engineer",
        min_length=2,
        max_length=255,
        description="Job role for the interview",
        examples=["Frontend Developer"],
    )
    topic: Optional[str] = Field(
        default=None,
        max_length=255,
        description="Technical topic for the interview (defaults to role if omitted)",
        examples=["React"],
    )
    difficulty: str = Field(
        default="Easy",
        description="Starting difficulty level",
    )
    resume_text: Optional[str] = Field(
        default=None,
        max_length=16000,
        description="Cleaned resume text for personalized questions (optional)",
    )

    @model_validator(mode="before")
    @classmethod
    def handle_aliases_and_defaults(cls, data: Any) -> Any:
        if isinstance(data, dict):
            if "job_role" in data and ("role" not in data or not data["role"]):
                data["role"] = data["job_role"]
            if not data.get("topic") and data.get("role"):
                data["topic"] = data["role"]
            elif not data.get("topic"):
                data["topic"] = "General Technical"
        return data

    @field_validator("candidate_name", "role")
    @classmethod
    def validate_not_empty(cls, value: str) -> str:
        stripped = value.strip()
        if not stripped:
            raise ValueError("Field cannot be empty or whitespace only")
        return stripped


class StartInterviewResponse(BaseModel):
    """
    Response schema for starting a new interview.
    """

    interview_id: UUID = Field(
        ...,
        description="UUID of the created interview session",
    )
    question: str = Field(
        ...,
        description="First interview question generated by AI",
    )
    difficulty: str = Field(
        default="Easy",
        description="Difficulty level of the question",
    )


class AnswerRequest(BaseModel):
    """
    Request schema for submitting an answer.
    """

    interview_id: UUID = Field(
        ...,
        description="UUID of the active interview session",
    )
    answer: str = Field(
        ...,
        min_length=10,
        max_length=5000,
        description="Candidate's answer text (min 10 characters)",
        examples=["The Virtual DOM is a lightweight representation of the real DOM in memory."],
    )
    idempotency_key: Optional[str] = Field(
        default=None,
        min_length=8,
        max_length=128,
        description=(
            "Stable client-generated key for retrying this answer submission. "
            "Reusing the key with a different answer is rejected."
        ),
    )

    @field_validator("answer")
    @classmethod
    def validate_answer_not_empty(cls, value: str) -> str:
        stripped = value.strip()
        if not stripped:
            raise ValueError("Answer cannot be empty or whitespace only")
        return stripped


class CodingProblemRequest(BaseModel):
    """Optional preferences when requesting a role-specific coding problem."""

    difficulty: Optional[str] = Field(default=None, max_length=50)
    language: Optional[str] = Field(default=None, max_length=50)


class CodeSubmissionRequest(BaseModel):
    """A candidate submission for the currently selected coding problem."""

    problem_id: str = Field(..., min_length=2, max_length=100)
    source_code: str = Field(..., min_length=1, max_length=50_000)
    language: Optional[str] = Field(default=None, max_length=50)
    idempotency_key: Optional[str] = Field(default=None, min_length=8, max_length=128)

    @field_validator("source_code")
    @classmethod
    def validate_source_code(cls, value: str) -> str:
        if not value.strip():
            raise ValueError("Source code cannot be empty or whitespace only")
        return value


class AnswerResponse(BaseModel):
    """
    Response schema for submitting an answer.
    """

    score: int = Field(
        ...,
        ge=0,
        le=10,
        description="Evaluation score out of 10",
    )
    feedback: str = Field(
        ...,
        description="Detailed feedback on the answer",
    )
    strengths: List[str] = Field(
        default_factory=list,
        description="List of identified strengths",
    )
    improvements: List[str] = Field(
        default_factory=list,
        description="List of areas for improvement",
    )
    next_question: str = Field(
        ...,
        description="Next interview question",
    )


class InterviewHistoryResponse(BaseModel):
    """
    Response schema for interview history.
    """

    interview_id: UUID = Field(
        ...,
        description="UUID of the interview session",
    )
    candidate_name: str = Field(
        ...,
        description="Name of the candidate",
    )
    role: str = Field(
        ...,
        description="Job role",
    )
    topic: str = Field(
        ...,
        description="Technical topic",
    )
    difficulty: str = Field(
        ...,
        description="Current difficulty level",
    )
    status: str = Field(
        ...,
        description="Current interview status",
    )
    started_at: Optional[datetime] = Field(
        None,
        description="Interview start timestamp",
    )
    ended_at: Optional[datetime] = Field(
        None,
        description="Interview end timestamp",
    )
    messages: List[dict] = Field(
        default_factory=list,
        description="List of all Q&A messages in the interview",
    )


class InterviewDetailResponse(BaseModel):
    """
    Response schema for individual interview details.
    """

    interview_id: UUID = Field(
        ...,
        description="UUID of the interview session",
    )
    candidate_name: str = Field(
        ...,
        description="Name of the candidate",
    )
    role: str = Field(
        ...,
        description="Job role",
    )
    topic: str = Field(
        ...,
        description="Technical topic",
    )
    difficulty: str = Field(
        ...,
        description="Current difficulty level",
    )
    status: str = Field(
        ...,
        description="Current interview status",
    )
    started_at: Optional[datetime] = Field(
        None,
        description="Interview start timestamp",
    )
    ended_at: Optional[datetime] = Field(
        None,
        description="Interview end timestamp",
    )
    current_question: Optional[str] = Field(
        None,
        description="The most recent question asked",
    )
    total_questions: int = Field(
        default=0,
        description="Total number of Q&A turns",
    )


class EndInterviewResponse(BaseModel):
    """
    Response schema for ending an interview.
    """

    status: str = Field(
        default="completed",
        description="Status confirmation",
    )
    interview_id: UUID = Field(
        ...,
        description="UUID of the ended interview",
    )

